import fs from 'node:fs'
import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {sha} from '../nq5-s2/activity.mjs'
import {deriveBlueprint} from '../../src/controller/foundation/blueprint.ts'
import {VIEWPORT,validateViewport} from '../../src/controller/foundation/contracts.mjs'
import {admitFrozenCorpusCandidate} from '../../src/investigation/corpus-seam/authority.mjs'
import {createCanonicalView,browse} from '../../src/investigation/semantic-ux/model.ts'
import {testArtIndex} from '../../tests/fixtures/s5/art-index.ts'
const out='artifacts/g6p-s5/REPORTS/',put=(n,x)=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(out+n,JSON.stringify(x,null,2)+'\n')},read=p=>JSON.parse(fs.readFileSync(p))
const BASE='0f52131c9f56f49128e7a413396331917e687a1f',TREE='98fe920f0f61bb5ebdb8aa1bf7f4f8957b10a131',candidate=read('artifacts/g6p-s3/REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json')
const bp=await deriveBlueprint();assert.equal(bp.semanticTotal,25);assert.equal(bp.boundedNoMatches,7)
put('MVP_BLUEPRINT.json',bp)
const view=await createCanonicalView(await admitFrozenCorpusCandidate(candidate)),cells=[]
for(const lens of ['ACTIVITY','RELATIONSHIPS','STATE','RECEIPT'])cells.push({filter:{lens},count:browse(view,{lens}).visible,displayIds:browse(view,{lens}).cards.map(c=>c.display.id)})
for(const subjectId of view.options.subjects)cells.push({filter:{subjectId},count:browse(view,{subjectId}).visible,displayIds:browse(view,{subjectId}).cards.map(c=>c.display.id)})
for(const zeroStatus of ['observed','bounded-no-match'])cells.push({filter:{zeroStatus},count:browse(view,{zeroStatus}).visible,displayIds:browse(view,{zeroStatus}).cards.map(c=>c.display.id)})
put('CORPUS_COUNT_CROSSWALK.json',{status:'EXECUTED_LOCAL_FROZEN_MODEL',identity:candidate.identity,total:25,boundedNoMatches:7,cells,beatCounts:bp.beats.map(b=>({beatId:b.id,...b.acceptedCorpus})),noCountsInvented:true,proofLayerSeparate:true})
validateViewport(VIEWPORT);put('VIEWPORT_TERMINAL_CONTRACT.json',VIEWPORT)
put('SYNTHETIC_INTAKE_EXAMPLE.json',testArtIndex())
const pins=read('artifacts/g6p-s4/REPORTS/LANE_A_ADMISSION.json').laneFiles
for(const p of pins)assert.equal(sha(fs.readFileSync(p.file)),p.sha256)
const originals=[...read('artifacts/g6p-s4-r2/REPORTS/PRESERVATION.json').preservedFiles.map(x=>x.file),'artifacts/g6p-s3/REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json','artifacts/g6p-s3/REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json','src/investigation/state.ts','src/investigation/query.ts','src/investigation/fixture.ts','src/app/ExactIdentifier.tsx'].filter(n=>n!=='src/app/CaseTerminalWorkbench.tsx')
const files=[...new Set(originals)].map(file=>{const b=fs.readFileSync(file);assert.ok(b.equals(execFileSync('git',['show',BASE+':'+file],{maxBuffer:128000000})),file);return{file,sha256:sha(b)}})
put('PRESERVATION.json',{status:'PASS',reviewedStart:BASE,reviewedTree:TREE,preservedFiles:files,laneAFiles:pins,truthBytesChanged:0,frozenCorpusBytesChanged:0,exactProofAndQueryReducerBytesChanged:0,clientEntries:74,clientMapSha256:sha(fs.readFileSync('src/controller/content/runtime-content.json')),B_F01:'EXISTING_RECEIPT_REVIEW_GUARD_UNCHANGED',B_F02:'EXACT_IDENTIFIER_KEYBOARD_COPY_UNCHANGED'})
const inputs=read('docs/source/execution-s5/ADMITTED_INPUT_BINDINGS.json')
put('INPUT_ADMISSION.json',{status:'PASS',archiveSha256:'2792555b8a628516d9bdd0542efd6cc9bdbec1b0c6cebec436b79d0c7619ecfc',safeMembers:19,manifestHashes:11,archiveBoundExceptions:['MANIFEST.sha256','VERIFY_INPUT.py'],suppliedVerifierRerun:'PASS_OUTSIDE_ALL_WORKTREES',inputs:inputs.inputs,credentialAccess:false,productionArchiveCopies:0})
put('LANE_C_APPLICATION.json',{status:'EXACT_ADDITIVE_ADMISSION_PLUS_DECLARED_CONTROLLER_FOLLOWUPS',admissionCommit:execFileSync('git',['rev-parse','e902652'],{encoding:'utf8'}).trim(),exactSourceFiles:inputs.laneFiles,artifactBindings:inputs.laneArtifacts,patchIdentity:'PASS_EXACT_RECONSTRUCTION_OMITTING_15_GIT_BLOB_INDEX_METADATA_LINES',historicalBranchMerged:false,corpusIdentity:candidate.identity,followups:['C1-NB-01 origin-aware synthetic copy','C1-NB-02 permanent frozen REPORTS JSON inputs; no transient adjacent import'],rawAndWrapperHashesVerified:true,noProviderRuntimeAuthority:true})
put('PIXEL_GAP_MATRIX.json',{status:'HANDOFF_REFERENCE_ONLY_NOT_ARCHIVE_ADMISSION',artArchiveInspected:false,actorCanvas:{width:48,height:88,channels:'RGBA',exclusiveFootBaseline:84},rook:{handoffStatus:'FROZEN_USER_APPROVED_VERSION_SPECIFIC',frameRoles:83,distinctPNGs:73,recipes:125,remaining:'Separate object-layer fit; no redraw or new derivative approval implied.'},arthur:{approved:['core identity','conversation/pointing','glasses/tie adjustment','reading/page pickup','stamping','terminal gaze'],pending:['dry-reaction changed eyes/new affected chains','9 foundation companion continuities','2 presenting companions /5 timings','3 stamp-life companions /5 timings','forward-slouch downward-looking held speech/blink','camera-facing fourth-wall','surprise/startled and knowing/pleased'],dryReaction012:{cels:24,recipes:17,unchangedApprovedCels:8,priorApprovedRecipes:12}},capabilities:[{id:'TERMINAL_LAYERED_SHELL',status:'MISSING_FINAL_ART_STATIC_PLACEHOLDER_PRESENT',required:true},{id:'REQUEST_FORM_PEN_STAMP_TUBE_CANISTER',status:'MECHANICS_PRESENT_FINAL_OBJECT_FIT_PENDING',required:true},{id:'ACTOR_SPEECH_READ_LISTEN_USE_REACT',status:'HANDOFF_FAMILIES_AVAILABLE_BUT_NOT_ARCHIVE_VERIFIED',required:true},{id:'SLOUCH_FOURTH_WALL_REACTIONS',status:'FIRST_CLASS_ART_TASK_PENDING_NOT_MECHANIC_GATE',required:true},{id:'LAMP_GLOBE_MUG',status:'SEPARATE_PARTNER_LANE_LAMP_REVIEW_THEN_GLOBE_MUG_GLOWS_RETIRED',required:false}],finalRoomGeometryAndActorFurnitureFit:'OPEN',frontHandOcclusionContactsOwnership:'PENDING_JOINT_OBJECT_FIT',productionIds:'LATE_BOUND',technicalValidationNeverEqualsPrincipalApproval:true})
const md=['# MVP investigation blueprint — foundation pending MAIN review','','Counts below are executed unique semantic display counts, not events/proof/account volume. The exact Euler proof layer remains separate. STATE has no frozen display member and is shown honestly as zero.','','Story: misfiled arrival → request/form/pen/stamp → sealed tube/plunger → canister/First Breach strip → earned terminal → inspect context → test the First Engine stop hypothesis → exact 11:38:11 UTC falsifier → Amount/Receiver/Link → bounded conclusion → return/closure. Arthur structures/reviews; Rook interprets. Optional chemistry/density stays late-bound.','',...bp.beats.map(b=>'## '+b.id+'\n\n'+b.controllerState+'\n\nSemantic filter count: '+b.acceptedCorpus.before.count+' → '+b.acceptedCorpus.after.count+'. Required cards: '+(b.requiredCardIds.join(', ')||'none')+'. Clues: '+(b.requiredClueIds.join(', ')||'none')+'. Props: '+b.props+'. Visual capability: '+b.requiredVisualCapability+'. Performance: Rook '+b.performance.rook.intention+' RIGHT; Arthur LISTEN LEFT; static semantic fallback. Sound optional. Recovery: '+b.failureRecovery+'\n\nClaim limit: '+b.claimBoundary+' Copy IDs and corpus IDs are fully mapped in MVP_BLUEPRINT.json; final optional copy/art identifiers are not bound.'),'','# '+bp.conclusion,'',...bp.journeys.map(j=>j.id+': '+j.beats.join(' → ')+'. '+j.recovery),'','Plain/docked/CRT use one reducer; keyboard, selectable exact identifiers, focus/reset, instant text and static reduced-motion remain required. Actual AT certification remains pending.'].join('\n')
fs.writeFileSync(out+'MVP_BLUEPRINT.md',md+'\n')
console.log(JSON.stringify({status:'PASS',beats:bp.beats.length,lensCounts:cells.slice(0,4).map(x=>[x.filter.lens,x.count]),acceptedLaneAFiles:37,clientMapSha256:sha(fs.readFileSync('src/controller/content/runtime-content.json'))}))
