import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {execFileSync} from 'node:child_process'
import {fileURLToPath} from 'node:url'
import {sha,identity} from '../nq5-s2/activity.mjs'
import {privatePathFindings} from '../nq5-s1/privacy.mjs'
import {hasSecretLikeValue} from '../secret-patterns.mjs'
import {OFF,admitEntries} from '../nq5-s1/core.mjs'
import {attachPublishedRegressionInputs} from '../nq5-s2/published-regression-inputs.mjs'
export const OUTPUT='TRACE_ESCAPE_G6P_NQ5_T1_S2_R1_ACCOUNT_EVIDENCE_SEMANTICS_REMEDIATION_DELIVERY_v1.0.0.zip'
const BASE='12303488687b47a260ce63e44d670423810ff517',BASE_TREE='493eb81d654b48cd93312d5388c99c574d6bb77b',PARENT='12303488687b47a260ce63e44d670423810ff517',INPUT_ZIP_SHA='364ae3c9d847eb3475e2f5606b596b0dea8988011621194380b769ce9e013a75'
const reports=['MERIDIAN_ACCOUNT_ACTIVITY_REPORT.json','CPP_LOGICAL_OPERATION_REPORT.json','COMBINED_ACCOUNT_PLANNING_REPORT.json','S2_R1_DECISION_RECEIPT.json']
const root=process.cwd(),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'s2-delivery-')),dir=path.join(tmp,'package'),fresh=path.join(tmp,'reconstructed'),objectRoot=path.join(tmp,'pack-audit')
const env={PATH:process.env.PATH,LANG:'C.UTF-8',TZ:'UTC',TMPDIR:os.tmpdir(),NODE_OPTIONS:'--require '+path.join(root,'scripts/nq5-r2/hold.cjs'),CI:'1',NO_COLOR:'1',GIT_TERMINAL_PROMPT:'0',GIT_CONFIG_NOSYSTEM:'1'}
const run=(cmd,args,cwd=root)=>{try{return execFileSync(cmd,args,{cwd,env,maxBuffer:128000000,stdio:['pipe','pipe','pipe']}).toString()}catch(e){const d=path.join(root,'artifacts/g6p-s2-r1/LOGS');fs.mkdirSync(d,{recursive:true});let i=1;while(fs.existsSync(path.join(d,'package-stopped-'+i+'.log')))i++;fs.writeFileSync(path.join(d,'package-stopped-'+i+'.log'),sanitize((e.stdout||'').toString()+(e.stderr||'').toString())+'\nEXIT_CODE='+e.status+'\n');throw Error('S2R1_PACKAGE_STOPPED_'+cmd)}} ,git=(...a)=>run('git',a).trim()
const sanitize=t=>t.split(root).join('[CONTROLLER_ROOT]').split(tmp).join('[FRESH_VERIFICATION_ROOT]').split(os.tmpdir()).join('[LOCAL_VERIFICATION_ROOT]').replace(/\u001b\[[0-9;]*m/g,'')
fs.mkdirSync(dir)
const candidate={commit:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),parent:git('rev-parse','HEAD^')}
if(candidate.commit===PARENT||git('rev-parse',BASE+'^{tree}')!==BASE_TREE)throw Error('S2_ANCESTRY_IDENTITY');run('git',['merge-base','--is-ancestor',BASE,candidate.commit]);run('git',['merge-base','--is-ancestor',PARENT,candidate.commit])
if(git('diff','--name-only','HEAD','--','.',':(exclude)AGENTS.md',':(exclude).cursor',':(exclude)ART_PRODUCTION'))throw Error('S2_DIRTY_GOVERNED_TRACKED')
const changed=git('diff','--name-only',BASE,candidate.commit).split('\n')
if(changed.some(n=>n==='AGENTS.md'||n.startsWith('.cursor/')||n.startsWith('ART_PRODUCTION/')||n.startsWith('public/')||/NANSEN_API_KEY\.txt/i.test(n)))throw Error('S2_CHANGED_PATH_SCOPE')
const ownedFiles=new Set(['README.md','docs/ARCHITECTURE.md','docs/PROJECT_STATUS.yaml','docs/PROJECT_SCHEDULE.json','package.json','tests/unit/project-clock.test.mjs','tests/unit/s2-activity-corpus.test.mjs','tests/unit/s2-r1-measurement.test.mjs','scripts/nq5-s2/activity.mjs','scripts/nq5-s2/schema.mjs','scripts/nq5-s2/import.mjs','docs/G6P_NQ5_T1_S2_R1_NOTES_FOR_LEAD.md'])
if(changed.some(n=>!ownedFiles.has(n)&&!['docs/source/execution-s2-r1/','scripts/nq5-s2-r1/','artifacts/g6p-s2-r1/'].some(p=>n.startsWith(p))))throw Error('S2R1_CLOSED_CHANGED_PATH_SCOPE')
const payload=new Map(),put=(n,b)=>{if(!n||n.startsWith('/')||n.split('/').includes('..')||n.includes('\\')||payload.has(n))throw Error('S2_PACKAGE_PATH');b=Buffer.isBuffer(b)?b:Buffer.from(typeof b==='string'?b:JSON.stringify(b,null,2)+'\n');fs.mkdirSync(path.dirname(path.join(dir,n)),{recursive:true});fs.writeFileSync(path.join(dir,n),b,{flag:'wx'});payload.set(n,b)}
const log=(n,text)=>put('LOGS/'+n+'.log',sanitize(text))
const bundle=path.join(tmp,'incremental.bundle');run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD','^'+BASE])
const bytes=fs.readFileSync(bundle),boundary=bytes.indexOf(Buffer.from('\n\n'))
if(boundary<0)throw Error('S2_BUNDLE_HEADER');const header=bytes.subarray(0,boundary).toString()
if(!header.includes('-'+BASE+' ')||header.split('\n').filter(l=>l.startsWith('-')).length!==1)throw Error('S2_EXACT_BASE_PREREQUISITE')
fs.mkdirSync(objectRoot);run('git',['init','--quiet'],objectRoot);fs.mkdirSync(path.join(objectRoot,'.git/objects/info'),{recursive:true});fs.writeFileSync(path.join(objectRoot,'.git/objects/info/alternates'),path.join(root,'.git/objects')+'\n')
const indexed=execFileSync('git',['index-pack','--fix-thin','--stdin'],{cwd:objectRoot,env,input:bytes.subarray(boundary+2),maxBuffer:128000000}).toString().trim(),packHash=indexed.split(/\s+/).at(-1),packIndex=path.join(objectRoot,'.git/objects/pack','pack-'+packHash+'.idx')
const objects=run('git',['verify-pack','-v',packIndex],objectRoot).split('\n').filter(l=>/^[a-f0-9]{40} (?:blob|commit|tree|tag) /.test(l)).map(l=>{const[id,type]=l.split(' ');return{id,type}})
if(!objects.length)throw Error('S2_PACK_OBJECTS_EMPTY')
let scanned=0;for(const o of objects){if(!['blob','commit','tag'].includes(o.type))continue;const b=execFileSync('git',['cat-file',o.type,o.id],{cwd:objectRoot,env,maxBuffer:128000000});let text;try{text=new TextDecoder('utf8',{fatal:true}).decode(b)}catch{throw Error('S2_NON_TEXT_NEW_OBJECT')};if(privatePathFindings(text).length||hasSecretLikeValue(text))throw Error('S2_PACKAGED_GIT_OBJECT_PRIVACY');scanned++}
const objectReport={status:'PASS',bundleSha256:sha(bytes),prerequisiteCommit:BASE,objects:objects.length,textObjectsScanned:scanned,objectIds:objects,thinPackDependencyMaterialization:'Indexed with local existing base-object alternates; every object in the reconstructed incremental pack scanned, including any required delta bases.',privatePathFindings:0,secretFindings:0,completeInheritedHistoryPackaged:false,credentialFileOpened:false,networkRequests:0}
put('EVIDENCE/INCREMENTAL_GIT_OBJECT_PRIVACY.json',objectReport);put('GIT/trace-escape-incremental.bundle',bytes)
fs.mkdirSync(fresh);run('git',['init','--quiet'],fresh);fs.mkdirSync(path.join(fresh,'.git/objects/info'),{recursive:true});fs.writeFileSync(path.join(fresh,'.git/objects/info/alternates'),path.join(root,'.git/objects')+'\n')
const bv=run('git',['bundle','verify',bundle],fresh);run('git',['fetch','--quiet','--no-tags',bundle,'HEAD:refs/heads/candidate'],fresh);run('git',['symbolic-ref','HEAD','refs/heads/candidate'],fresh);run('git',['read-tree','HEAD'],fresh)
if(run('git',['rev-parse','HEAD'],fresh).trim()!==candidate.commit||run('git',['rev-parse','HEAD^{tree}'],fresh).trim()!==candidate.tree||run('git',['rev-parse','HEAD^'],fresh).trim()!==candidate.parent)throw Error('S2_RECONSTRUCTED_IDENTITY')
const names=run('git',['ls-files','-z','--','.',':(exclude).cursor',':(exclude)ART_PRODUCTION'],fresh).split('\0').filter(Boolean)
for(const n of names){if(n.startsWith('/')||n.split('/').includes('..'))throw Error('S2_FRESH_PATH');const b=execFileSync('git',['show','HEAD:'+n],{cwd:fresh,env,maxBuffer:128000000});fs.mkdirSync(path.dirname(path.join(fresh,n)),{recursive:true});fs.writeFileSync(path.join(fresh,n),b,{flag:'wx'})}
fs.symlinkSync(path.join(root,'node_modules'),path.join(fresh,'node_modules'),'dir');fs.appendFileSync(path.join(fresh,'.git/info/exclude'),'\nnode_modules\n')
const fsck=run('git',['fsck','--full','--strict'],fresh)
put('EVIDENCE/PUBLISHED_REGRESSION_INPUT_BINDINGS.json',attachPublishedRegressionInputs(root,tmp,env))
const diff=execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:root,env,maxBuffer:128000000}),freshDiff=execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:fresh,env,maxBuffer:128000000});if(!diff.equals(freshDiff))throw Error('S2_EXACT_DIFF_RECONSTRUCTION');put('SOURCE_DIFF.patch',diff)
log('incremental-reconstruction',bv+fsck+'\nExact accepted base prerequisite, candidate/tree/parent, strict fsck, and identical base-to-candidate patch: PASS. Local object alternates used; no complete history copied into delivery.\n')
log('fresh-schema-boundaries',run('node',['scripts/nq5-s2-r1/verify.mjs'],fresh))
log('fresh-schema-negative-mutations',run('python3',['scripts/nq5-s2-r1/schema-negative.py'],fresh))
const test=run('node',['node_modules/vitest/vitest.mjs','run'],fresh);log('fresh-broad-unit-acquisition',test)
const testCount=Number(test.match(/Tests\s+(\d+) passed/)?.[1]);if(!testCount||/\d+ failed/.test(test))throw Error('S2R1_FRESH_BROAD_TESTS')
log('fresh-typecheck',run('npm',['run','typecheck'],fresh));log('fresh-build',run('npm',['run','build'],fresh));log('fresh-lint',run('npm',['run','lint'],fresh))
for(const n of reports){put('REPORTS/'+n,fs.readFileSync(path.join(root,'artifacts/g6p-s2-r1/REPORTS',n)));put('SCHEMAS/'+n+'.schema.json',fs.readFileSync(path.join(root,'artifacts/g6p-s2-r1/SCHEMAS',n+'.schema.json')))}
put('SCHEMAS/MERIDIAN_ACTIVITY_INPUT.schema.json',fs.readFileSync(path.join(root,'artifacts/g6p-s2-r1/SCHEMAS/MERIDIAN_ACTIVITY_INPUT.schema.json')))
for(const n of ['PRINCIPAL_SAMPLE_TRANSFORMED.json','CPP_SAFE_TRANSFORMED_INPUT.json'])put('INPUTS/'+n,fs.readFileSync(path.join(root,'artifacts/g6p-s2-r1/INPUTS',n)))
put('REPORTS/TE_IFACE_CORPUS_RC1.json',fs.readFileSync(path.join(root,'artifacts/g6p-s2/REPORTS/TE_IFACE_CORPUS_RC1.json')))
put('SCHEMAS/TE_IFACE_CORPUS_RC1.json.schema.json',fs.readFileSync(path.join(root,'artifacts/g6p-s2/SCHEMAS/TE_IFACE_CORPUS_RC1.json.schema.json')))
const originalManifest=fs.readFileSync(path.join(root,'docs/source/execution-s2-r1/MANIFEST.sha256'),'utf8'),normalizations=[]
for(const line of originalManifest.trim().split('\n')){const[h,n]=line.split('  '),b=fs.readFileSync(path.join(root,'docs/source/execution-s2-r1',n)),original=n.endsWith('.csv')?Buffer.from(b.toString().replace(/\r?\n/g,'\r\n')):b;if(sha(original)!==h)throw Error('S2R1_PACKAGED_INPUT_BINDING');put('SOURCE_INPUT/'+n,original);normalizations.push({filename:n,originalSha256:h,originalBytes:original.length,installedSha256:sha(b),installedBytes:b.length,transformation:n.endsWith('.csv')?'REVERSIBLE_CRLF_TO_LF_ONLY':'BYTE_IDENTICAL'})}
put('SOURCE_INPUT/MANIFEST.sha256',originalManifest)
put('EVIDENCE/INPUT_ADMISSION_AND_NORMALIZATION.json',{status:'PASS',sourceInputArchiveSha256:INPUT_ZIP_SHA,uniquePathSafeRegularMembers:16,originalManifestEntries:15,suppliedValidator:'PASS',originalFullCPPArchiveOpened:false,artifactBindings:normalizations})
for(const n of fs.readdirSync(path.join(root,'artifacts/g6p-s2-r1/LOGS')).filter(n=>n.endsWith('.log')).sort())put('LOGS/'+n,fs.readFileSync(path.join(root,'artifacts/g6p-s2-r1/LOGS',n)))
for(const n of ['tests/unit/s2-r1-measurement.test.mjs','tests/unit/s2-activity-corpus.test.mjs','tests/e2e/s2-fixes.spec.ts'])put('TESTS/'+path.basename(n),fs.readFileSync(path.join(root,n)))
put('EVIDENCE/NOTES_FOR_LEAD.md',fs.readFileSync(path.join(root,'docs/G6P_NQ5_T1_S2_R1_NOTES_FOR_LEAD.md')))
put('CONTRACT/S2_R1_EXECUTION_CONTRACT.txt',fs.readFileSync(path.join(root,'docs/source/execution-s2-r1/CONTRACT/TRACE_ESCAPE_CODEX_G6P_NQ5_T1_S2_R1_ACCOUNT_EVIDENCE_SEMANTICS_REMEDIATION_PROMPT_v1.0.0_2026-09-17.txt')))
const currentBrowser=fs.readFileSync(path.join(root,'artifacts/g6p-s2-r1/LOGS/browser-current.log'),'utf8'),fixesBrowser=fs.readFileSync(path.join(root,'artifacts/g6p-s2-r1/LOGS/browser-fixes.log'),'utf8')
if(!currentBrowser.includes('34 passed')||!currentBrowser.includes('EXIT_CODE=0')||!fixesBrowser.includes('3 passed')||!fixesBrowser.includes('EXIT_CODE=0'))throw Error('S2R1_CURRENT_BROWSER_REQUIRED')
const preserved=['src/investigation/query.ts','src/investigation/state.ts','src/app/ExactIdentifier.tsx','src/app/CaseTerminalWorkbench.tsx','src/investigation/accounting.ts','scripts/nq5-s2/corpus.mjs','artifacts/g6p-s2/REPORTS/TE_IFACE_CORPUS_RC1.json','artifacts/g6p-s2/SCHEMAS/TE_IFACE_CORPUS_RC1.json.schema.json','docs/G6P_NQ5_T1_S2_CURATED_INPUT.json']
const snapshot=JSON.parse(fs.readFileSync(path.join(root,'docs/G6P_NQ5_T1_S1_PUBLIC_EVIDENCE_INPUT.json')));preserved.push(...snapshot.truth.files.map(f=>f.file))
const preservation=preserved.map(n=>{const a=execFileSync('git',['show',BASE+':'+n],{cwd:root,env,maxBuffer:128000000}),b=execFileSync('git',['show',candidate.commit+':'+n],{cwd:root,env,maxBuffer:128000000});if(!a.equals(b))throw Error('S2R1_PRESERVED_BYTE_CHANGE');return{file:n,sha256:sha(b),bytes:b.length,byteIdenticalToReviewedStart:true}})
put('EVIDENCE/ACCEPTED_SUBSYSTEM_BYTE_IDENTITIES.json',{status:'PASS',reviewedStartCommit:BASE,productionQueryCopyChanges:[],corpusReportChanges:[],curatedConcepts:25,exactEulerFiles:6,files:preservation})
const account=JSON.parse(payload.get('REPORTS/MERIDIAN_ACCOUNT_ACTIVITY_REPORT.json')),cpp=JSON.parse(payload.get('REPORTS/CPP_LOGICAL_OPERATION_REPORT.json')),corpus=JSON.parse(payload.get('REPORTS/TE_IFACE_CORPUS_RC1.json')),receipt=JSON.parse(payload.get('REPORTS/S2_R1_DECISION_RECEIPT.json'))
put('EVIDENCE/MAIN_OWNED_REVIEW.json',{status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',reviewType:'EIGHT_MAIN_OWNED_LENSES_NOT_INDEPENDENT_LEAD_ACCEPTANCE',candidate,lenses:['input/source/review identity','exact Git ancestry and recovery','measurement and nullable credits','mixed verified proof versus planning sets','mandatory false-success and schema rejection','network/credential/privacy boundaries','accepted production/corpus/truth preservation','lean packaging and bounded disposition'],finding:'S2-R1-P1-01_REMEDIATION_IMPLEMENTED_PENDING_MAIN_REVIEW',limitations:['same-account submission applicability unresolved','final provider quota unclaimed','Lane B independent integrated return not supplied by this task','RC unfrozen and Lane C inactive','actual AT, contrast, final-art and hardware/touch acceptance open'],externalMessagesSent:false,authorities:OFF})
// This result template is publishable only after the ten checked rejections below.
put('EVIDENCE/PACKAGE_POLICY_CHECKS.json',{status:'PASS',adversarialRejections:10,publicationConditionalOnActualExecution:true,cases:['changed byte','extra member','missing member','symlink member','rehashed quota promotion','resealed logical operations counted requests','resealed unknown credits zero-imputed','resealed combined quota promotion','rehashed original artifact byte mismatch','resealed corpus freeze promotion']})
put('EVIDENCE/VERIFICATION_SUMMARY.json',{status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',candidate,reviewedStart:{commit:BASE,tree:BASE_TREE},freshBroadUnitAcquisitionTests:testCount,currentBrowserRegression:{passed:34,failed:0},focusedBrowserTests:3,exactClipboardModeValueChecks:9,clipboardFailureModes:3,focusedSuitesAreNotAddedToBroadTotal:true,historicalS2LegacyBrowserDisposition:{passed:28,failed:17,preexistingJourneyFailures:11,retiredLabelExpectations:6,rerunInS2R1:false,reference:'SOURCE_INPUT/MAIN_REVIEW/TRACE_ESCAPE_MAIN_LEAD_REVIEW_S2_RECEIPT_v1.0.0_2026-09-17.json'},typecheck:'PASS',build:'PASS',lint:'PASS',schemas:5,newReports:4,originalInputManifestEntries:15,unchangedEulerFiles:6,externalApiProbesBlocked:4,strictFsck:'PASS',exactDiffReproduced:true,packagedGitPrivacy:'PASS',completeHistoryIncluded:false,baseDependentRecovery:true,networkRequests:0,credentialAccess:false,privateStateAccess:false,independentLeadReviewPending:true,authorities:OFF})
const expectedIdentities=Object.fromEntries([...reports,'TE_IFACE_CORPUS_RC1.json'].map(n=>[n,JSON.parse(payload.get('REPORTS/'+n)).identity]))
put('DELIVERY_MANIFEST.json',{schemaVersion:'2.0.0',status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',candidate,reviewedStartCommit:BASE,reviewedStartTree:BASE_TREE,acceptedAncestorCommit:'47f0466e4f6f31ba2583577c4ff747b2dc1dab3b',candidatePromoted:false,incrementalBundleSha256:sha(bytes),incrementalBundlePrerequisite:BASE,sourceDiffSha256:sha(diff),sourceInputArchiveSha256:INPUT_ZIP_SHA,reportIdentities:expectedIdentities,decisionReceiptIdentity:receipt.identity,completeHistoryIncluded:false,baseDependentRecovery:true,curatedAcceptedCalls:25,quotaClaimed:false,interfaceFrozen:false,LaneCActive:false,networkRequests:0,authorities:OFF})
put('00_READ_ME_FIRST.md','S2-R1 account-evidence measurement remediation. Status DELIVERED_PENDING_MAIN_LEAD_REVIEW. No external message sent.\n\nThe incremental Git bundle requires exact reviewed S2 commit '+BASE+' / tree '+BASE_TREE+' already available locally. It does not include inherited complete history. Verify the supplied ZIP SHA-256, safely extract unique regular path-safe members, then run node VERIFY_DELIVERY.mjs. Use an existing local Git repository containing that prerequisite to verify/fetch the bundle into a separate candidate ref; compare exact commit/tree/parent and git diff --binary with SOURCE_DIFF.patch, then git fsck --full --strict. Never fetch missing history or dependencies from a network. Locked installed dependencies and eight prior published local redacted regression-input archives are verification prerequisites only, not packaged ZIPs. Exact hash bindings are included.\n\nSOURCE_INPUT is the exact admitted safe controller input; the CPP CSV is restored to original CRLF. The committed derivative uses LF only and is reversibly bound in EVIDENCE/INPUT_ADMISSION_AND_NORMALIZATION.json. The original full CPP archive was never opened. INPUTS contains the explicit sanitized transformations. CPP logical operations are not provider requests; unknown credits remain null; non-billed commitments are separate. Original review/source files are references, not new authority. Sealed S2 reports remain historical; version2 reports and schemas are the active correction. Accepted query/copy/corpus/truth are unchanged. All current candidate authorities are false; quota unclaimed; RC unfrozen; Lane C inactive. No key, account body, raw provider/business payload, private path, dependencies/build preview, assets, lane payload or nested archive ships.\n')
const allowed=[...payload.keys(),'VERIFY_DELIVERY.mjs','MANIFEST.sha256'].sort()
function verifyDelivery(){
 const fail=n=>{throw Error(n)},read=n=>fs.readFileSync(path.join(root,n)),json=n=>JSON.parse(read(n))
 const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const f=path.join(d,e.name),s=fs.lstatSync(f);if(s.isSymbolicLink()||(!s.isDirectory()&&(!s.isFile()||s.nlink!==1)))fail('S2R1_NONREGULAR');return s.isDirectory()?walk(f):[path.relative(root,f).split(path.sep).join('/')] }).sort()
 if(JSON.stringify(walk(root))!==JSON.stringify(allowed))fail('S2R1_EXACT_MEMBERS')
 const seen=new Set(),lines=read('MANIFEST.sha256').toString().trimEnd().split('\n');if(lines.length!==allowed.length-1)fail('S2R1_HASH_COUNT')
 for(const l of lines){const h=l.slice(0,64),n=l.slice(66);if(!/^[a-f0-9]{64}$/.test(h)||l.slice(64,66)!=='  '||!allowed.includes(n)||n==='MANIFEST.sha256'||seen.has(n)||sha(read(n))!==h)fail('S2R1_HASH');seen.add(n)}
 const m=json('DELIVERY_MANIFEST.json'),v=json('EVIDENCE/VERIFICATION_SUMMARY.json'),a=json('REPORTS/MERIDIAN_ACCOUNT_ACTIVITY_REPORT.json'),c=json('REPORTS/CPP_LOGICAL_OPERATION_REPORT.json'),b=json('REPORTS/COMBINED_ACCOUNT_PLANNING_REPORT.json'),r=json('REPORTS/S2_R1_DECISION_RECEIPT.json'),corpus=json('REPORTS/TE_IFACE_CORPUS_RC1.json'),g=json('EVIDENCE/INCREMENTAL_GIT_OBJECT_PRIVACY.json')
 if(m.status!=='DELIVERED_PENDING_MAIN_LEAD_REVIEW'||m.reviewedStartCommit!==base||m.reviewedStartTree!==baseTree||JSON.stringify(m.candidate)!==JSON.stringify(candidate)||JSON.stringify(v.candidate)!==JSON.stringify(candidate)||m.candidatePromoted!==false||m.incrementalBundlePrerequisite!==base||m.incrementalBundleSha256!==sha(read('GIT/trace-escape-incremental.bundle'))||m.sourceDiffSha256!==sha(read('SOURCE_DIFF.patch'))||m.sourceInputArchiveSha256!==inputZipSha||m.completeHistoryIncluded!==false||m.baseDependentRecovery!==true||m.quotaClaimed!==false||m.interfaceFrozen!==false||m.LaneCActive!==false||m.networkRequests!==0)fail('S2R1_MANIFEST_BINDINGS')
 const bytes=read('GIT/trace-escape-incremental.bundle'),head=bytes.toString('utf8',0,bytes.indexOf(Buffer.from('\n\n')));if(!head.includes('-'+base+' ')||head.split('\n').filter(x=>x.startsWith('-')).length!==1||!head.includes(candidate.commit+' HEAD'))fail('S2R1_BUNDLE_PREREQUISITE')
 for(const x of [a,c,b,r,corpus]){const{identity:h,...body}=x;if(identity(body)!==h)fail('S2R1_REPORT_SEAL')}
 if(a.observed.requests!==20||a.observed.successes!==20||a.observed.failures!==0||a.observed.credits!==32||a.removedRows.length!==1||a.verifiedSuccessfulLowerBound!==0||JSON.stringify(Object.values(a.endpointTotals).map(x=>x.requests).sort((a,b)=>a-b))!=='[3,7,10]'||a.sourceBindings[0].measurementClass!=='PROVIDER_REQUEST_ROW'||a.sourceBindings[0].sourceClass!=='PRINCIPAL_TRANSCRIBED')fail('S2R1_SAMPLE_CONTRACT')
 if(c.sourceBindings.length!==1||c.sourceBindings[0].measurementClass!=='PROJECT_LOGICAL_OPERATION'||c.sourceBindings[0].sourceClass!=='PROJECT_LEDGER_SUMMARY'||c.sourceBindings[0].projectClass!=='CPP'||c.observed.requests!==0||c.observed.credits!==null||c.verifiedSuccessfulLowerBound!==0||c.independentlyVerifiedProviderRequests!==0||c.logicalOperations.distinctLogicalOperationLowerBound!==3772||c.logicalOperations.pureLiveControlledSuccessOperations!==3758||c.logicalOperations.operationsContainingLiveControlledSuccess!==3760||c.logicalOperations.exactHttpAttemptCount!==null||c.logicalOperations.exactHttpResponseCount!==null||c.logicalOperations.exactBilledCredits!==null||c.logicalOperations.unknownCreditOperations!==3772||c.sourceBindings[0].reviewIdentity!=='52f33a9437550be33169ce222e7f6529dd84b5cda3fefa9b53d778a137a68360'||c.planningCommitments[0].metric!=='NON_BILLED_CONSERVATIVE_PLANNING_COMMITMENT')fail('S2R1_CPP_MEASUREMENT')
 for(const x of [a,c,b])if(x.finalQuotaProofEligible!==false||x.quotaMet!==false||x.finalQuotaClaimable!==false||x.providerRequestFloorEvidenced!==false||x.sameAccountSubmissionApplicability!=='UNRESOLVED'||x.curatedGameEvidenceRows!==0||x.cppAutomaticallyCounts!==false||x.networkRequests!==0)fail('S2R1_NO_FALSE_SUCCESS')
 if(b.observed.requests!==20||b.observed.credits!==32||b.logicalOperations.distinctLogicalOperationLowerBound!==3772||r.sampleAccountReportIdentity!==a.identity||r.cppLogicalOperationReportIdentity!==c.identity||r.combinedReportIdentity!==b.identity||r.corpusCandidateIdentity!==corpus.identity||r.quotaClaimed!==false||r.interfaceFrozen!==false||r.LaneCActive!==false||r.packetsSent!==false)fail('S2R1_REPORT_BINDINGS')
 if(corpus.identity!=='64807a4cbfb7b5ea1fb4931c2b94731c9e8c6e4f7b751fc609f3ce1c45df5e53'||corpus.conceptCount!==25||corpus.concepts.length!==25||corpus.interfaceFrozen!==false||corpus.LaneCActive!==false||corpus.runtimeProviderCalls!==0)fail('S2R1_CORPUS_IDENTITY')
 if(JSON.stringify(m.reportIdentities)!==JSON.stringify(expectedIdentities))fail('S2R1_REPORT_IDENTITIES');for(const[n,h]of Object.entries(expectedIdentities))if(json('REPORTS/'+n).identity!==h)fail('S2R1_REPORT_IDENTITIES')
 const cppInput=json('INPUTS/CPP_SAFE_TRANSFORMED_INPUT.json'),sampleInput=json('INPUTS/PRINCIPAL_SAMPLE_TRANSFORMED.json')
 for(const[x,report]of [[cppInput,c],[sampleInput,a]])if(identity(x)!==report.sourceBindings[0].transformedInputIdentity||JSON.stringify(x.source_artifact)!==JSON.stringify(report.sourceBindings[0].originalArtifact))fail('S2R1_TRANSFORMED_ARTIFACT_BINDING')
 if(cppInput.rows.length!==3772||cppInput.rows.some(x=>x.measurement_class!=='PROJECT_LOGICAL_OPERATION'||x.displayed_credits!==null||'endpoint'in x||'http_status'in x))fail('S2R1_CPP_INPUT_SEMANTICS')
 const cppBytes=read('SOURCE_INPUT/CPP_EVIDENCE/CPP_ELIGIBLE_WINDOW_LOGICAL_OPERATIONS_LOWER_BOUND.csv');if(sha(cppBytes)!==cppInput.source_artifact.sha256||cppBytes.length!==cppInput.source_artifact.bytes)fail('S2R1_ORIGINAL_ARTIFACT_BINDING')
 for(const l of read('SOURCE_INPUT/MANIFEST.sha256').toString().trim().split('\n')){const[h,n]=l.split('  ');if(!allowed.includes('SOURCE_INPUT/'+n)||sha(read('SOURCE_INPUT/'+n))!==h)fail('S2R1_ORIGINAL_INPUT_MANIFEST')}
 if(g.status!=='PASS'||g.bundleSha256!==m.incrementalBundleSha256||g.prerequisiteCommit!==base||g.completeInheritedHistoryPackaged!==false||g.privatePathFindings!==0||g.secretFindings!==0||v.freshBroadUnitAcquisitionTests<1468||v.currentBrowserRegression.passed!==34||v.currentBrowserRegression.failed!==0||v.focusedBrowserTests!==3||v.strictFsck!=='PASS'||v.exactDiffReproduced!==true||v.networkRequests!==0||v.credentialAccess!==false||v.privateStateAccess!==false)fail('S2R1_EVIDENCE')
 for(const n of allowed){if(n.startsWith('GIT/'))continue;const text=read(n).toString();if(privatePathFindings(text).length||hasSecretLikeValue(text))fail('S2R1_TEXT_PRIVACY');if(n==='DELIVERY_MANIFEST.json'||n==='EVIDENCE/VERIFICATION_SUMMARY.json'||n==='EVIDENCE/MAIN_OWNED_REVIEW.json'||n==='REPORTS/S2_R1_DECISION_RECEIPT.json'){const x=JSON.parse(text);if(JSON.stringify(Object.keys(x.authorities).sort())!==JSON.stringify(Object.keys(off).sort())||Object.values(x.authorities).some(v=>v!==false))fail('S2R1_AUTHORITY')}}
 console.log(JSON.stringify({status:'PASS',members:allowed.length,hashes:seen.size,terminalStatus:m.status,sampleRequests:20,sampleCredits:32,cppLogicalOperations:3772,cppVerifiedProviderRequests:0,unknownCreditsPreserved:true,corpusUnchanged:true,authoritiesOff:true,baseDependentRecovery:true}))
}
const secret=fs.readFileSync(path.join(root,'scripts/secret-patterns.mjs'),'utf8').replace('export function','function'),privacy=fs.readFileSync(path.join(root,'scripts/nq5-s1/privacy.mjs'),'utf8').split('export function privatePathFindings')[1].split('export function currentTreeScan')[0]
put('VERIFY_DELIVERY.mjs',"import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';const root=path.dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex'),canonical="+canonicalFunction()+",identity=x=>sha(canonical(x)),allowed="+JSON.stringify(allowed)+",base="+JSON.stringify(BASE)+",baseTree="+JSON.stringify(BASE_TREE)+",candidate="+JSON.stringify(candidate)+",inputZipSha="+JSON.stringify(INPUT_ZIP_SHA)+",expectedIdentities="+JSON.stringify(expectedIdentities)+",off="+JSON.stringify(OFF)+";\n"+secret+'\nfunction privatePathFindings'+privacy+'\n('+verifyDelivery.toString()+')();\n')
for(const[n,b]of payload){if(n.startsWith('GIT/'))continue;if(privatePathFindings(b.toString()).length||hasSecretLikeValue(b.toString()))throw Error('S2R1_PACKAGE_TEXT_PRIVACY_'+n)}
put('MANIFEST.sha256',[...payload].sort(([a],[b])=>a.localeCompare(b)).map(([n,b])=>sha(b)+'  '+n).join('\n')+'\n')
run('node',['VERIFY_DELIVERY.mjs'],dir)
let adversarialPassed=0
const rehash=()=>fs.writeFileSync(path.join(dir,'MANIFEST.sha256'),allowed.filter(n=>n!=='MANIFEST.sha256').map(n=>sha(fs.readFileSync(path.join(dir,n)))+'  '+n).join('\n')+'\n')
const reject=(name,apply,restore,expected)=>{const originalManifest=fs.readFileSync(path.join(dir,'MANIFEST.sha256'));try{apply();let rejected=false;try{execFileSync('node',['VERIFY_DELIVERY.mjs'],{cwd:dir,env,stdio:['pipe','pipe','pipe']})}catch(e){if(!String(e.stderr).includes(expected))throw Error('S2R1_WRONG_ADVERSARIAL_FAILURE_'+name);rejected=true}if(!rejected)throw Error('S2R1_ADVERSARIAL_FALSE_SUCCESS_'+name);adversarialPassed++}finally{restore();fs.writeFileSync(path.join(dir,'MANIFEST.sha256'),originalManifest)}}
const mutate=(n,change,expected)=>{const original=fs.readFileSync(path.join(dir,n));reject(n,()=>{const x=JSON.parse(original);change(x);fs.writeFileSync(path.join(dir,n),JSON.stringify(x,null,2)+'\n');rehash()},()=>fs.writeFileSync(path.join(dir,n),original),expected)}
const logName='LOGS/browser-fixes.log',logBytes=fs.readFileSync(path.join(dir,logName))
reject('changed-byte',()=>fs.appendFileSync(path.join(dir,logName),'CORRUPTION'),()=>fs.writeFileSync(path.join(dir,logName),logBytes),'S2R1_HASH')
reject('extra-member',()=>fs.writeFileSync(path.join(dir,'EXTRA.txt'),'SYNTHETIC'),()=>fs.unlinkSync(path.join(dir,'EXTRA.txt')),'S2R1_EXACT_MEMBERS')
reject('missing-member',()=>fs.unlinkSync(path.join(dir,logName)),()=>fs.writeFileSync(path.join(dir,logName),logBytes),'S2R1_EXACT_MEMBERS')
reject('symlink-member',()=>{fs.unlinkSync(path.join(dir,logName));fs.symlinkSync('../schema-first.log',path.join(dir,logName))},()=>{fs.unlinkSync(path.join(dir,logName));fs.writeFileSync(path.join(dir,logName),logBytes)},'S2R1_NONREGULAR')
mutate('DELIVERY_MANIFEST.json',x=>{x.quotaClaimed=true},'S2R1_MANIFEST_BINDINGS')
mutate('REPORTS/CPP_LOGICAL_OPERATION_REPORT.json',x=>{x.observed.requests=3772;const{identity:h,...body}=x;x.identity=identity(body)},'S2R1_CPP_MEASUREMENT')
mutate('REPORTS/CPP_LOGICAL_OPERATION_REPORT.json',x=>{x.observed.credits=0;const{identity:h,...body}=x;x.identity=identity(body)},'S2R1_CPP_MEASUREMENT')
mutate('REPORTS/COMBINED_ACCOUNT_PLANNING_REPORT.json',x=>{x.finalQuotaClaimable=true;const{identity:h,...body}=x;x.identity=identity(body)},'S2R1_NO_FALSE_SUCCESS')
mutate('INPUTS/CPP_SAFE_TRANSFORMED_INPUT.json',x=>{x.source_artifact.bytes++;},'S2R1_TRANSFORMED_ARTIFACT_BINDING')
mutate('REPORTS/TE_IFACE_CORPUS_RC1.json',x=>{x.interfaceFrozen=true;const{identity:h,...body}=x;x.identity=identity(body)},'S2R1_REPORT_BINDINGS')
if(adversarialPassed!==10)throw Error('S2R1_ADVERSARIAL_TOTAL');run('node',['VERIFY_DELIVERY.mjs'],dir)
for(const n of allowed)fs.utimesSync(path.join(dir,n),new Date('2000-01-01Z'),new Date('2000-01-01Z'))
const zip=path.join(tmp,'delivery.zip'),repeat=path.join(tmp,'repeat.zip');run('zip',['-X','-q',zip,...allowed],dir);run('zip',['-X','-q',repeat,...allowed],dir);if(sha(fs.readFileSync(zip))!==sha(fs.readFileSync(repeat)))throw Error('S2R1_ZIP_DETERMINISM')
const metadata=`import zipfile,stat,json,sys\nwith zipfile.ZipFile(sys.argv[1]) as z:\n print(json.dumps([{'name':i.filename,'type':'regular' if not i.is_dir() and stat.S_IFMT(i.external_attr>>16) in (0,stat.S_IFREG) else 'nonregular'} for i in z.infolist()]))`
admitEntries(JSON.parse(run('python3',['-c',metadata,zip])),allowed);const extracted=path.join(tmp,'extracted');fs.mkdirSync(extracted);run('unzip',['-q',zip,'-d',extracted]);const finalVerification=run('node',['VERIFY_DELIVERY.mjs'],extracted)
for(const n of allowed)if(!fs.readFileSync(path.join(dir,n)).equals(fs.readFileSync(path.join(extracted,n))))throw Error('S2R1_BYTE_ROUNDTRIP')
if(git('rev-parse','HEAD')!==candidate.commit||git('rev-parse','HEAD^{tree}')!==candidate.tree)throw Error('S2R1_CANDIDATE_CHANGED')
const dest=path.join(path.dirname(root),OUTPUT);fs.copyFileSync(zip,dest,fs.constants.COPYFILE_EXCL)
console.log(JSON.stringify({status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',archive:dest,sha256:sha(fs.readFileSync(dest)),bytes:fs.statSync(dest).size,members:allowed.length,freshBroadUnitAcquisitionTests:testCount,currentBrowserTests:34,focusedBrowserTests:3,packageAdversarialRejections:adversarialPassed,exactClipboardChecks:9,candidate,reviewedStart:BASE,incrementalGitPrivacy:'PASS',completeHistoryIncluded:false,networkRequests:0,finalArchiveVerification:JSON.parse(finalVerification)},null,2))
function canonicalFunction(){return `(x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(canonical).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}')`}
