import fs from 'node:fs'
import path from 'node:path'
import {execFileSync} from 'node:child_process'
import {sha,identity} from '../nq5-s2/activity.mjs'
import {schemaOf} from '../nq5-s1/model.mjs'
import {compileFinal,syntheticFixture,launchContract,BASE,BASE_TREE} from './corpus.mjs'
const read=n=>JSON.parse(fs.readFileSync(n)),git=(...args)=>execFileSync('git',args,{encoding:'utf8'}).trim()
if(git('rev-parse',BASE+'^{tree}')!==BASE_TREE)throw Error('S3_START_TREE')
const input=read('docs/G6P_NQ5_T1_S2_CURATED_INPUT.json'),snapshot=read('docs/G6P_NQ5_T1_S1_PUBLIC_EVIDENCE_INPUT.json')
const files=['src/investigation/query.ts','src/investigation/state.ts','src/investigation/contracts.ts','src/investigation/fixture.ts','src/investigation/catalog.ts','src/investigation/accounting.ts','src/app/ExactIdentifier.tsx','src/app/CaseTerminalWorkbench.tsx','scripts/nq5-s2/corpus.mjs','artifacts/g6p-s2/REPORTS/TE_IFACE_CORPUS_RC1.json','artifacts/g6p-s2/SCHEMAS/TE_IFACE_CORPUS_RC1.json.schema.json','docs/G6P_NQ5_T1_S2_CURATED_INPUT.json',...snapshot.truth.files.map(x=>x.file)]
const preservation=files.map(file=>{const bytes=fs.readFileSync(file),base=execFileSync('git',['show',BASE+':'+file]);if(!bytes.equals(base))throw Error('S3_IMMUTABLE_BYTES');return {file,sha256:sha(bytes),bytes:bytes.length,byteIdentical:true}})
const compatibility={B_F01:'EXACTLY_ONE_DISTINCT_CANONICAL_ASSET_FOR_MIN_AMOUNT_RAW_CHIPS_PRESERVED',B_F02:'SHARED_NATIVE_KEYBOARD_COPY_FULL_SELECTABLE_IDENTIFIERS_ALL_THREE_MODES',preservedBytes:preservation,truthFiles:6,productionChanges:0}
const final=compileFinal(input,compatibility),synthetic=syntheticFixture(final),launch=launchContract(final)
const put=(n,x)=>{fs.mkdirSync(path.dirname(n),{recursive:true});fs.writeFileSync(n,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n')}
for(const[n,x]of [['TE_IFACE_CORPUS_FINAL_CANDIDATE.json',final],['SYNTHETIC_SEMANTIC_FIXTURE.json',synthetic],['LANE_C_LAUNCH_CONTRACT.json',launch],['ACCEPTED_BYTE_IDENTITIES.json',{status:'PASS',reviewedStartCommit:BASE,files:preservation}]]){
 put('artifacts/g6p-s3/REPORTS/'+n,x);put('artifacts/g6p-s3/SCHEMAS/'+n+'.schema.json',schemaOf(x))
}
const manifest=fs.readFileSync('docs/source/execution-s3/MANIFEST.sha256','utf8').trim().split('\n').map(l=>({file:l.slice(66),sha256:l.slice(0,64)}))
const decisions=manifest.filter(x=>x.file.startsWith('LANE_B/TEST_OVERLAY/')).map(x=>{
 let targets=[],reason='Evidence-only lane orchestration, disposable intake paths, duplicate configurations or brittle source-string policy; retained as hash-bound review inventory, not imported.'
 if(x.file.endsWith('/contract.test.ts')){targets=['tests/unit/s3-lane-b-contract.test.ts'];reason='Adapted only exhaustive phase edges B-U01, exact-proof mutation/assembly B-U04, and reorder determinism B-U05; removed file reporters and duplicate B-U02/B-U03/B-U06.'}
 if(x.file.endsWith('/s2-targets.test.ts')){targets=['tests/unit/s3-lane-b-query.test.ts'];reason='Adapted 1000 conflicting permutations and exact-decimal boundary; remaining raw-state/recovery cases already covered by accepted S2 tests.'}
 if(x.file.endsWith('/semantics.spec.ts')){targets=['tests/e2e/s3-semantics.spec.ts'];reason='Adapted B-A01 native-keyboard mode invariance/journey/live semantics and B-A04 bounded dead-end/no-proof; duplicate physical-dispatch and pointer-only copy cases omitted. DOM semantics are not actual AT.'}
 if(x.file.endsWith('/guard.spec.ts')){targets=['tests/e2e/s3-guard.spec.ts'];reason='Adapted three synthetic guard self-probes; blocked before issue, CSP bypass confined to this test, file reporter removed.'}
 if(x.file.includes('/fixtures/'))reason='Existing accepted tests/fixtures/s2 helpers cover this intent; no second helper tree imported.'
 if(x.file.includes('.repro.'))reason='Retired pre-fix diagnostic; accepted S2 repro and immutable closure bindings already retained, not added to active passing suites.'
 if(x.file.endsWith('/journeys.spec.ts'))reason='Duplicate Cartesian mode/input/journey grid; SCREEN_READER label is DOM keyboard semantics only, not an actual AT session. Existing current journeys plus selected semantic tests suffice.'
 if(x.file.endsWith('/runtime.spec.ts'))reason='Current large-corpus browser performance test already exists; unit reorder determinism admitted separately without invented performance threshold.'
 return {...x,status:targets.length?'ADMITTED_ADAPTED_SUBSET':'REJECTED_DUPLICATE_OR_ORCHESTRATION',reason,targets:targets.map(file=>({file,sha256:sha(fs.readFileSync(file))}))}
})
if(decisions.length!==26||decisions.filter(x=>x.status==='ADMITTED_ADAPTED_SUBSET').length!==4)throw Error('S3_OVERLAY_COMPLETE_MINIMAL')
put('artifacts/g6p-s3/REPORTS/OVERLAY_ADMISSION_INVENTORY.json',{status:'PASS',overlayPaths:26,adaptedPaths:4,unchangedImports:0,productionChanges:0,decisions})
const retained=manifest.filter(x=>fs.existsSync('docs/source/execution-s3/'+x.file)).map(x=>{if(sha(fs.readFileSync('docs/source/execution-s3/'+x.file))!==x.sha256)throw Error('S3_SOURCE_HASH_'+x.file);return x})
put('artifacts/g6p-s3/REPORTS/INPUT_ADMISSION.json',{status:'PASS',archiveSha256:'84acd2175d55612bd574d11040d55f00d1c729f3b12f502ea9fd1c91d6e5e082',zipMembers:46,manifestEntries:44,suppliedValidatorResult:'PASS_44_HASHED_MEMBERS',manifestSha256:sha(fs.readFileSync('docs/source/execution-s3/MANIFEST.sha256')),validatorSha256:sha(fs.readFileSync('docs/source/execution-s3/VERIFY_INPUT.py')),retainedReferences:retained,notRetained:manifest.filter(x=>!retained.some(y=>y.file===x.file)),retentionPolicy:'SELECTIVE_TEXT_REFERENCE_INSTALL_NOT_FULL_INPUT_REPLAY_ROOT; recovery binary checked pre-work but not copied; overlay paths reviewed and inventoried, only selected adapted test code retained',startCommit:BASE,startTree:BASE_TREE,documentTreatment:'Continue is the user request; supplied documents define bounded reference work, not independent authority for unrelated actions.',sourceConflict:'PROJECT_SOURCE/04_CURRENT_OPERATIONS.md trailing historical Lead disposition contradicts newer canonical record; exact MAIN receipt is current authority.',networkRequests:0,credentialAccess:false})
put('artifacts/g6p-s3/REPORTS/SEAM_INVENTORY.json',{status:'PASS',interface:final.interface,interfaceIdentity:final.identity,sourceFiles:['src/investigation/corpus-seam/contracts.ts','scripts/nq5-s3/corpus.mjs'],displayKeys:Object.keys(final.displayRecords[0]).sort(),auditSurfaces:['SOURCE','LEDGER'],displaySurfaces:['CASE','RESULTS','EXPLORE'],acceptedConcepts:25,boundedNoMatch:7,syntheticRoles:9,gameplayIntegrated:false,interfaceFrozen:false,LaneCActive:false,runtimeProviderCalls:0})
const lane='artifacts/g6p-s3/LANE_C_PREPARED_NOT_SENT/'
for(const[n,x]of [['TE_IFACE_CORPUS_FINAL_CANDIDATE.json',final],['SYNTHETIC_SEMANTIC_FIXTURE.json',synthetic],['LANE_C_LAUNCH_CONTRACT.json',launch]])put(lane+n,x)
for(const[n,source]of [['contracts.ts','src/investigation/corpus-seam/contracts.ts'],['corpus.mjs','scripts/nq5-s3/corpus.mjs'],['COMPATIBILITY_TEST.ts','tests/unit/s3-corpus-seam.test.ts']])put(lane+n,fs.readFileSync(source,'utf8'))
put(lane+'ORIENTATION_FIRST.txt','PREPARED NOT SENT. Do not execute activation. Read launch contract, exact interface candidate, seam contracts, synthetic fixture and compatibility tests. MAIN must first accept S3 and freeze the exact identity '+final.identity+'. Verify the outer delivery exact candidate commit/tree/parent on top of '+BASE+' before any later approved additive lane work. Orientation is endpoint-independent Investigation Semantic UX and Corpus Presentation only. Audit metadata stays SOURCE/LEDGER; no private provider/account/source access. No normalization, canonical truth, central reducers, interfaces, credentials, merges or release changes. Report shared blockers only; keep ordinary KT lane-local.\n')
put(lane+'ACTIVATION_SECOND_BLOCKED.txt','UNSENT TEMPLATE; NOT ACTIVATION AUTHORITY. Requires a later separate MAIN acceptance, exact interface freeze receipt '+final.identity+', candidate commit/tree/parent binding to outer manifest, and explicit principal transmission/activation approval. Until all exist, STOP. Thereafter work only additively within launch-contract ownedPaths. Do not modify any existing shared controller path, truth, reducer, interface, provider source, release state or other lane. No runtime external requests. Use local fixtures; preserve all three mode semantic values and full native keyboard exact identifiers. All branch integration remains MAIN-owned; no historical merges. Keep routine KT inside this lane.\n')
put(lane+'00_READ_ME_FIRST.md','Prepared, self-contained orientation materials; never sent, never activated. Contracts and tests are reference snapshots whose original imports are resolved in the outer candidate repository using its locked local dependencies. The standalone validator needs only Node stdlib. Run node VERIFY_LANE_C.mjs. Passing validates preparation integrity, NOT authorization to activate. Exact candidate identity is supplied by the enclosing delivery manifest; separate MAIN acceptance and freeze are mandatory.\n')
const laneNames=fs.readdirSync(lane).filter(n=>!['MANIFEST.sha256','VERIFY_LANE_C.mjs'].includes(n)).sort()
put(lane+'VERIFY_LANE_C.mjs',`import fs from 'node:fs';import {createHash} from 'node:crypto';import path from 'node:path';import {fileURLToPath} from 'node:url';const root=path.dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex'),expected=${JSON.stringify({interfaceIdentity:final.identity,launchIdentity:launch.identity,ownedPaths:launch.ownedPaths,hashes:Object.fromEntries(laneNames.map(n=>[n,sha(fs.readFileSync(lane+n))]))})};const names=fs.readdirSync(root).sort(),lines=fs.readFileSync(path.join(root,'MANIFEST.sha256'),'utf8').trim().split('\\n');if(names.length!==lines.length+1)throw Error('LANE_MEMBERS');const seen=new Set();for(const l of lines){const n=l.slice(66),s=fs.lstatSync(path.join(root,n));if(!names.includes(n)||n.includes('/')||n.includes('\\\\')||seen.has(n)||!s.isFile()||s.isSymbolicLink()||s.nlink!==1||sha(fs.readFileSync(path.join(root,n)))!==l.slice(0,64))throw Error('LANE_HASH');seen.add(n)}for(const[n,h]of Object.entries(expected.hashes))if(sha(fs.readFileSync(path.join(root,n)))!==h)throw Error('LANE_PINNED_CONTENT');if(JSON.stringify(names)!==JSON.stringify([...Object.keys(expected.hashes),'VERIFY_LANE_C.mjs','MANIFEST.sha256'].sort()))throw Error('LANE_PINNED_MEMBERS');const j=n=>JSON.parse(fs.readFileSync(path.join(root,n))),f=j('TE_IFACE_CORPUS_FINAL_CANDIDATE.json'),c=j('LANE_C_LAUNCH_CONTRACT.json');if(f.identity!==expected.interfaceIdentity||f.interface!=='TE-IFACE-CORPUS@1.0.0'||f.interfaceFrozen!==false||f.LaneCActive!==false||c.identity!==expected.launchIdentity||c.interfaceIdentity!==expected.interfaceIdentity||c.interfaceFrozen!==false||c.LaneCActive!==false||c.packetsSent!==false||JSON.stringify(c.ownedPaths)!==JSON.stringify(expected.ownedPaths)||c.status!=='PREPARED_NOT_SENT')throw Error('LANE_AUTHORITY');console.log(JSON.stringify({status:'PASS_PREPARATION_ONLY',interfaceIdentity:expected.interfaceIdentity,packetsSent:false,LaneCActive:false}));\n`)
put(lane+'MANIFEST.sha256',[...laneNames,'VERIFY_LANE_C.mjs'].sort().map(n=>sha(fs.readFileSync(lane+n))+'  '+n).join('\n')+'\n')
console.log(JSON.stringify({status:'READY_FOR_MAIN_FREEZE',identity:final.identity,concepts:25,noMatch:7,interfaceFrozen:false,LaneCActive:false,overlayPaths:decisions.length,retainedReferences:retained.length}))
