import { lessons as prior } from '../nq5-b3/lessons.mjs'
export function lessons(){const extra=[
 ['CONTROL_WITHOUT_RECURSION','Qualification-counted control falsely seeds frontier','Accepted hub has bounded control value but recursion is false','Counted implies recursive authority','Preserve qualification count while separately suppressing recursive frontier authority','Source-quality class/authority gate'],
 ['HUB_AMPLIFICATION','Large row/branch count mistaken for meaningful breadth','Raw780 rows/772 tuples do not imply useful candidates','Raw branching proves scale viability','Treat high degree as specificity risk and suppress hub-only recursion','Filtered complete matrix rather than raw branching extrapolation'],
 ['PLANNING_ONLY_CLASSES','External classes become provider/player claims','Exact Lead-supplied planning registry','Public-source classification is a Nansen label','Keep generic class codes in planning evidence only, never public projection/game','Strict public index excludes planning class fields'],
 ['SPECIFIC_INVESTIGATION_METADATA','Generic ACTIVITY metadata loses actual question','Rejected64 plan flattened every candidate','One generic consumer fits every role','Preserve candidate-specific lens/purpose/question/coverage/exact lineage/consumer','Seed/hash/repeat/single/control purpose mappings'],
 ['ACCEPTED_PENDING_SEPARATION','Pending public rows indistinguishable from accepted','Eight formal Lead crosswalk entries','Supplier terminal implies Lead acceptance','Explicit status/order/receipt with immutable supplier sequence separate','Accepted index/schema/crosswalk bindings'],
 ['SOURCE_FANOUT_CAPS','Support counts reward infrastructure recursion','Four/source and two control maxima','Highest support count alone is utility','Source caps, hub suppression and lower specificity risk precede scale-up','Per-source cap counted across every contributing support source'],
 ['NO_EXTERNAL_LABEL_LEAK','Planning classification leaks into player evidence','Generic registry code has planning-only scope','External label may be published as provider attribution','No human-readable external labels or planning classes in public index/game','Public schema privacy controls'],
 ['FILTERED_VIABILITY_BEFORE_SCALE','Formal scale-up follows raw candidate count','Fewer than four ordinary candidates blocks live','Padding preserves a scale target','Scale only from deduplicated non-hub bounded utility; no minimum/no padding','B4 minimum ordinary threshold; no credential access, documentation refresh, or private writes when blocked']]
 return {schemaVersion:'1.0.0',scope:'B1_THROUGH_B3_R1_ENGINEERING_KT_NOT_PUBLIC_GAME',rows:[...prior().rows.map(r=>r.classification==='CURRENT_OPERATIONAL_STATE'?{...r,classification:'HISTORICAL_B3_OPERATIONAL_STATE'}:r),...extra.map(([id,mechanism,falsifier,rejected,rule,test])=>({findingId:id,falseSuccessMechanism:mechanism,firstFalsifier:falsifier,rejectedInterpretation:rejected,acceptedRule:rule,directTestOrInvariant:test,sourceKtCarryForwardText:rule,classification:'STABLE_POLICY'}))],sourceConsolidationPending:true,gameplayIntegration:false}
}
