import { identity } from '../nq5/schema.mjs'
import { logicalRequest } from '../nq5/planner.mjs'
import { tuple, uniq } from '../nq5-b3/planner.mjs'
import { validAddress } from '../nq5-b1-r3-r1/semantics.mjs'
import { REGISTRY, opposite } from './quality.mjs'
import { seal, CONTRACT_SHA, ARCHIVE_SHA, HELD } from './authority.mjs'
const ZERO='0x'+'0'.repeat(40)
const equivalence=q=>identity({method:q.method,path:q.path,body:q.body})
export function enumerate({sources,truth,issuedRequests,template,qualityReport,maximum=16,sourceCap=4,batch=4}){
 if(maximum!==16&&maximum!==256||sourceCap!==4&&sourceCap!==8)throw new Error('B4_EXACT_POLICY_BOUNDS')
 const qualities=new Map(qualityReport.rows.map(r=>[r.logicalId,r])),pool=new Map(),tokens=new Set(['0x6b175474e89094c44da98b954eedeac495271d0f',...sources.flatMap(p=>p.semantic.tokenContracts??[])]),issued=new Set(issuedRequests.map(equivalence)),subjectsIssued=new Set(issuedRequests.map(q=>q.body.address.toLowerCase()))
 const add=(address,page)=>{const subject=address.toLowerCase(),key=subject+'/'+page;let r=pool.get(key);if(!r){r={subject,page,seed:false,proofs:new Map(),paginationProof:null};pool.set(key,r)}return r}
 for(const address of truth.seedAddresses)add(address,1).seed=true
 for(const p of sources){if(!qualities.has(p.logicalId))throw new Error('B4_SOURCE_QUALITY_REQUIRED');const subject=p.request.body.address.toLowerCase()
  for(const v of p.admission.normalizedRecords){const from=v.from_address.toLowerCase(),to=v.to_address.toLowerCase();if(from!==subject&&to!==subject)throw new Error('B4_INCIDENTAL_LINEAGE');const r=add(opposite(v,subject),1);let proof=r.proofs.get(p.logicalId);if(!proof){proof={logicalId:p.logicalId,transactions:new Set(),transfers:new Set(),exactHashes:new Set()};r.proofs.set(p.logicalId,proof)}const hash=v.transaction_hash.toLowerCase();proof.transactions.add(hash);proof.transfers.add(tuple(v));if(Object.hasOwn(truth.times,hash))proof.exactHashes.add(hash)}
  if(p.pagination.is_last_page===false)add(subject,p.request.body.pagination.page+1).paginationProof=p.logicalId
 }
 const rows=[...pool.values()].map(r=>{
  const proofs=[...r.proofs.values()],nonHub=proofs.filter(p=>qualities.get(p.logicalId).recursiveFrontierAuthority),exact=proofs.filter(p=>p.exactHashes.size),known=REGISTRY[r.subject]??null,nonHubIds=uniq(nonHub.map(p=>p.logicalId)),nonHubTx=uniq(nonHub.flatMap(p=>[...p.transactions])),allTx=uniq(proofs.flatMap(p=>[...p.transactions])),sourceIds=uniq(proofs.map(p=>p.logicalId)),exactHashes=uniq(exact.flatMap(p=>[...p.exactHashes])),nonHubSingle=nonHub.some(p=>p.transactions.size>=2)
  let role=r.seed?'UNUSED_ACCEPTED_SEED':exactHashes.length?'EXACT_ACCEPTED_HASH_JOIN':nonHubIds.length>=2?'INDEPENDENT_NON_HUB_REPEAT':'BOUNDED_NON_HUB_SINGLE'
  if(known)role='INFRASTRUCTURE_NEGATIVE_CONTROL';if(r.page>1)role='EXACT_DURABLE_PAGINATION'
  const lens=role==='UNUSED_ACCEPTED_SEED'||role==='EXACT_DURABLE_PAGINATION'?'ACTIVITY':role==='EXACT_ACCEPTED_HASH_JOIN'?'RECEIPT':'RELATIONSHIPS',purpose=role==='UNUSED_ACCEPTED_SEED'?'ANCHOR_ACTIVITY_PAGE':role==='EXACT_ACCEPTED_HASH_JOIN'?'TRACE_THREAD_LINK_TEST':role==='INDEPENDENT_NON_HUB_REPEAT'?'FLOW_DIRECTION_QUERY':role==='INFRASTRUCTURE_NEGATIVE_CONTROL'?'NEGATIVE_CONTROL':role==='EXACT_DURABLE_PAGINATION'?'PAGINATION_COMPLETENESS':'DEAD_END_DISCOVERY'
  const body=structuredClone(template.body);body.address=r.subject;body.pagination.page=r.page;const question='QUESTION.T1.B'+batch+'.'+purpose+'.'+r.subject,coverageKey={subject_id:r.subject,time_window_id:body.date.from+'/'+body.date.to,question_lens:lens,page_or_partition_id:'PAGE.'+r.page},cell='CELL.'+identity(coverageKey),control=role==='INFRASTRUCTURE_NEGATIVE_CONTROL'
  const proofIds=role==='UNUSED_ACCEPTED_SEED'?[]:role==='EXACT_ACCEPTED_HASH_JOIN'?uniq([...nonHubIds,...exact.map(p=>p.logicalId)]):nonHubIds
  const usedProofs=proofs.filter(p=>proofIds.includes(p.logicalId)),lineage=uniq([...(r.seed?['ACCEPTED_EULER_TRUTH.'+truth.sha256]:[]),...usedProofs.flatMap(p=>['DURABLE_SUBJECT_TRANSFER.'+p.logicalId,...[...p.transfers].map(h=>'TRANSFER_IDENTITY.'+h),...[...p.transactions].map(h=>'DURABLE_TRANSACTION.'+h)]),...exactHashes.map(h=>'ACCEPTED_EXACT_HASH.'+h),...(r.paginationProof?['DURABLE_PAGINATION.'+r.paginationProof]:[])])
  const test=control?'NEGATIVE_CONTROL.NO_INFRASTRUCTURE_RECURSION':purpose==='DEAD_END_DISCOVERY'?'DEADEND.TEST':purpose==='ANCHOR_ACTIVITY_PAGE'?'SEED.CONTEXT.TEST':purpose==='TRACE_THREAD_LINK_TEST'?'PROVENANCE.HASH_JOIN.TEST':purpose==='PAGINATION_COMPLETENESS'?'PAGINATION.TEST':'ROUTE.DIRECTIONAL.TEST',consumers=[test+'.T1.B'+batch+'.'+r.subject,'PROVENANCE.T1.B'+batch+'.'+r.subject,cell]
  const businessQuestion=control?'Does bounded contextual activity for '+r.subject+' falsify the named no-infrastructure-recursion classification invariant without seeding a route?':purpose==='FLOW_DIRECTION_QUERY'?'Do independent non-hub accepted calls support a contextual directional pattern for '+r.subject+' or a bounded dead end?':purpose==='TRACE_THREAD_LINK_TEST'?'Does the exact accepted transaction-hash join for '+r.subject+' reconcile the incident provenance thread without exact-time inference?':purpose==='ANCHOR_ACTIVITY_PAGE'?'Which contextual incident activity for unused accepted seed '+r.subject+' fills its case-specific activity cell?':purpose==='PAGINATION_COMPLETENESS'?'What contextual subject facts occur on the exact next durable page for '+r.subject+' without a completeness claim?':'Does independently testable incident activity for '+r.subject+' support the bounded multi-transaction dead-end question?'
  const q={family:template.family,method:template.method,path:template.path,contractHash:template.contractHash,publicProjectionPolicy:structuredClone(template.publicProjectionPolicy),body,sequence:1,lens,purpose,candidateRole:role,questionId:question,businessQuestion,coverageKey,coverageCells:[cell],lineage,consumers,frontierProof:{kind:role,subjectAddress:r.subject,supportingLogicalIds:proofIds,supportingTransactionHashes:uniq(usedProofs.flatMap(p=>[...p.transactions])),supportingTransferIdentities:uniq(usedProofs.flatMap(p=>[...p.transfers])),acceptedExactHashes:exactHashes},foregroundGameplayIntegrationAccepted:false,expectedCredits:1,worstCaseCredits:3,stopRule:'Stop first identity, semantic, storage, schema, provider-ID, rate, credit, reserve, audit or privacy breaker; drain issued calls independently. No replacement or request beyond the frozen gate.'};q.logicalId=logicalRequest(q)
  const eq=equivalence(q),selfOnly=proofs.length>0&&proofs.every(p=>sources.find(s=>s.logicalId===p.logicalId).request.body.address.toLowerCase()===r.subject),ordinary=!control
  let rejection=!validAddress(r.subject)?'INVALID_ADDRESS':r.subject===ZERO?'ZERO_ADDRESS':tokens.has(r.subject)?'TOKEN_CONTRACT_EXCLUDED':issued.has(eq)?'ALREADY_ISSUED_EQUIVALENT_CANONICAL_REQUEST':selfOnly&&!r.paginationProof?'SELF_ONLY_COUNTERPARTY':r.page>1&&batch===4?'B4_EXACT_PAGE1_ONLY':r.page>1&&!qualities.get(r.paginationProof)?.recursiveFrontierAuthority?'HUB_PAGINATION_RECURSION_SUPPRESSED':known&&nonHubIds.length===0?'INFRASTRUCTURE_CONTROL_WITHOUT_CASE_SPECIFIC_NON_HUB_LINEAGE':known&&!nonHubSingle&&nonHubIds.length<2?'INFRASTRUCTURE_CONTROL_WITHOUT_BOUNDED_CLASSIFICATION_UTILITY':!r.seed&&!exactHashes.length&&nonHubIds.length===0?'HUB_ONLY_RECURSIVE_LINEAGE_SUPPRESSED':!r.seed&&!exactHashes.length&&nonHubIds.length<2&&!nonHubSingle?'SINGLE_SUPPORT_REQUIRES_TWO_DISTINCT_NON_HUB_TRANSACTIONS':null
  if(lineage.some(x=>HELD.some(h=>x.includes(h))))throw new Error('B4_HELD_LINEAGE')
  const risk=proofIds.reduce((n,id)=>n+qualities.get(id).distinctOppositeAddresses,0),priority=control?4:role==='UNUSED_ACCEPTED_SEED'?0:role==='EXACT_ACCEPTED_HASH_JOIN'?1:role==='INDEPENDENT_NON_HUB_REPEAT'?2:3
  return {candidateIdentity:identity({subject:r.subject,page:r.page,proofs:proofs.map(p=>({logicalId:p.logicalId,transactions:uniq([...p.transactions]),transfers:uniq([...p.transfers]),exactHashes:uniq([...p.exactHashes])})),seed:r.seed,paginationProof:r.paginationProof}),subjectAddress:r.subject,page:r.page,sourceKinds:[...(r.seed?[subjectsIssued.has(r.subject)?'ACCEPTED_SEED_ALREADY_ISSUED':'UNUSED_ACCEPTED_EULER_SEED']:[]),...(sourceIds.length?['DURABLE_SUBJECT_COUNTERPARTY']:[]),...(exactHashes.length?['ACCEPTED_EXACT_HASH_JOIN']:[]),...(r.paginationProof?['EXACT_DURABLE_NONLAST_PAGE']:[])],supportingLogicalIds:sourceIds,supportingTransactionHashes:allTx,supportingTransferIdentities:uniq(proofs.flatMap(p=>[...p.transfers])),ordinaryProofSourceIds:proofIds,nonHubSupportingLogicalIds:nonHubIds,nonHubSupportingTransactionHashes:nonHubTx,sourceQualityClasses:uniq(sourceIds.map(id=>qualities.get(id).sourceQualityClass)),planningOnlyClassification:known,questionId:question,questionLens:lens,purpose,candidateRole:role,coverageKey,coverageCell:cell,namedConsumers:consumers,deduplicatedLineage:lineage,publicSafe:validAddress(r.subject)&&r.subject!==ZERO&&!tokens.has(r.subject),alreadyIssuedEquivalent:issued.has(eq),ordinaryCandidate:ordinary,marginalUtility:businessQuestion+' Independent non-hub calls='+nonHubIds.length+'; non-hub transactions='+nonHubTx.length+'; source degree is a risk, never a reward.',sourceCapResult:{maximumPerSource:sourceCap,contributingLogicalIds:proofIds,status:rejection?'NOT_APPLIED_REJECTED_EVIDENCE':'PENDING_SELECTION'},infrastructureControlInvariant:control?'NO_INFRASTRUCTURE_RECURSION':null,utilityRank:{classPriority:priority,independentNonHubSupportingRequests:nonHubIds.length,distinctSupportingTransactions:role==='EXACT_ACCEPTED_HASH_JOIN'?exactHashes.length:nonHubTx.length,uncoveredCaseQuestionCell:issued.has(eq)?0:1,namedConsumerValue:1,sourceDegreeRisk:risk},admitted:!rejection,rejectionCode:rejection,request:q}
 })
 rows.sort(compare);const counts=new Map();let selected=0,controls=0
 for(const r of rows)if(r.admitted){if(r.ordinaryProofSourceIds.some(id=>(counts.get(id)??0)>=sourceCap)){r.admitted=false;r.rejectionCode='DEFERRED_SOURCE_FANOUT_CAP_'+sourceCap}else if(!r.ordinaryCandidate&&controls>=2){r.admitted=false;r.rejectionCode='DEFERRED_INFRASTRUCTURE_CONTROL_MAXIMUM_2'}else if(selected>=maximum){r.admitted=false;r.rejectionCode='DEFERRED_EXACT_GATE_MAXIMUM_'+maximum}else{selected++;if(!r.ordinaryCandidate)controls++;for(const id of r.ordinaryProofSourceIds)counts.set(id,(counts.get(id)??0)+1)}r.sourceCapResult.status=r.admitted?'PASS':r.rejectionCode
 }
 const requests=rows.filter(r=>r.admitted).map((r,i)=>({...r.request,sequence:i+1})),matrix={schemaVersion:'1.0.0',planningOnly:true,playerFacingLabels:false,nansenLabels:false,allAcceptedSeedsEvaluated:truth.seedAddresses.length,durableAcceptedSourceCalls:sources.length,completeCandidateCount:rows.length,ordinaryAdmittedCount:rows.filter(r=>r.admitted&&r.ordinaryCandidate).length,infrastructureControlAdmittedCount:controls,admittedCount:requests.length,heldCallsExcluded:HELD,sourceQualityIdentity:qualityReport.hash,maximumRequests:maximum,maximumPerSource:sourceCap,noPadding:true,noExhaustionClaim:true,sourceCapCounts:Object.fromEntries([...counts].sort()),rows:rows.map(({request,...r})=>r)}
 matrix.rows.forEach((r,i)=>{const p=rows[i];r.observedSupportingLineage=uniq([...p.supportingLogicalIds.map(id=>'DURABLE_SUBJECT_TRANSFER.'+id),...p.supportingTransactionHashes.map(h=>'DURABLE_TRANSACTION.'+h),...p.supportingTransferIdentities.map(h=>'TRANSFER_IDENTITY.'+h)]);if(r.sourceKinds.some(k=>k.includes('SEED')))r.observedSupportingLineage=uniq([...r.observedSupportingLineage,'ACCEPTED_EULER_TRUTH.'+truth.sha256])})
 return {matrix,requests}
}
function compare(a,b){const x=a.utilityRank,y=b.utilityRank;return x.classPriority-y.classPriority||y.independentNonHubSupportingRequests-x.independentNonHubSupportingRequests||y.distinctSupportingTransactions-x.distinctSupportingTransactions||y.uncoveredCaseQuestionCell-x.uncoveredCaseQuestionCell||y.namedConsumerValue-x.namedConsumerValue||x.sourceDegreeRisk-y.sourceDegreeRisk||a.subjectAddress.localeCompare(b.subjectAddress)||a.page-b.page}
export function freeze(c,lead,index,audit,qualityReport){
 const all=[...c.prior.a.context.bound.plan.requests,...c.prior.a.b3PriorObjects['PLANS/T1_BATCH2_EXECUTION_PLAN.json'].requests,...c.prior.plans.plan.requests],issuedRequests=[...c.r.current.starts.values()].map(s=>{const q=all.find(q=>q.logicalId===s.logicalId);if(!q)throw new Error('B4_ISSUED_REQUEST_PROOF_MISSING');return q}).filter(q=>q.family==='profiler/address/transactions')
 const f=enumerate({sources:c.sources,truth:c.prior.a.context.truth,issuedRequests,template:c.prior.plans.plan.requests[0],qualityReport}),bind={campaignId:lead.campaignId,executionContractSha256:CONTRACT_SHA,reviewedB3ArchiveSha256:ARCHIVE_SHA,leadAcceptanceReceiptIdentity:lead.hash,acceptedPublicIndexIdentity:identity(index),requestAuditIdentity:identity(audit),sourceQualityIdentity:qualityReport.hash,candidateMatrixIdentity:identity(f.matrix),balanceAnchor:625707,protectedReserve:250}
 const policy=seal({schemaVersion:'1.0.0',...bind,maximumRequests:16,minimumRequests:0,minimumOrdinaryCandidatesForLive:4,maximumPerSource:4,maximumInfrastructureControls:2,hubRecursionAllowed:false,highRawDegreeUtilityReward:false,candidateSpecificMetadataRequired:true,canaryRequests:4,canaryConcurrency:4,postCanaryMaximumConcurrency:8,maximumAttempts:f.requests.length*3,old64RequestPlanRejected:true,rejectedPlanIdentity:'668922b6ddc07e4260588fbdb73465921aefecabdbcb7801a0fff1121aca628e',noSeventeenthRequest:true,noReplacement:true,page1Only:true,AUTHORIZED_TO_ISSUE:false})
 const plan=seal({schemaVersion:'1.0.0',...bind,requests:f.requests,ordinaryMeaningfulCandidates:f.matrix.ordinaryAdmittedCount,frontierPolicyIdentity:policy.hash,expectedCredits:f.requests.length,worstCaseCredits:f.requests.length*3,frozen:true,AUTHORIZED_TO_ISSUE:false}),reserve=seal({schemaVersion:'1.0.0',...bind,planIdentity:plan.hash,frontierPolicyIdentity:policy.hash,expectedCredits:plan.expectedCredits,worstCaseCredits:plan.worstCaseCredits,remainingAfterWorstCase:625707-plan.worstCaseCredits,reservePass:625707-plan.worstCaseCredits>=250,AUTHORIZED_TO_ISSUE:false})
 return {...f,plan,reserve,policy,liveGate:admissionGate(plan,policy)}
}
export function admissionGate(plan,policy){if(plan.hash!==identity(Object.fromEntries(Object.entries(plan).filter(([k])=>k!=='hash')))||policy.hash!==identity(Object.fromEntries(Object.entries(policy).filter(([k])=>k!=='hash')))||plan.frontierPolicyIdentity!==policy.hash||policy.maximumRequests!==16||policy.maximumPerSource!==4||policy.maximumInfrastructureControls!==2||!policy.old64RequestPlanRejected||plan.requests.length>16||plan.requests.some(q=>q.body.pagination.page!==1||logicalRequest(q)!==q.logicalId))throw new Error('B4_FILTERED_PLAN_SEAL_OR_POLICY');const ordinary=plan.requests.filter(q=>q.candidateRole!=='INFRASTRUCTURE_NEGATIVE_CONTROL').length;if(ordinary!==plan.ordinaryMeaningfulCandidates||new Set(plan.requests.map(q=>q.logicalId)).size!==plan.requests.length)throw new Error('B4_ORDINARY_COUNT_OR_DUPLICATE_DRIFT');return {pass:ordinary>=4,ordinaryMeaningfulCandidates:plan.ordinaryMeaningfulCandidates,minimumRequired:4,reason:plan.ordinaryMeaningfulCandidates>=4?'B4_LOCAL_REVIEW_DOCS_PRIVATE_AND_RUNTIME_GATES_STILL_REQUIRED':'B4_INSUFFICIENT_ORDINARY_NON_HUB_CANDIDATES',AUTHORIZED_TO_ISSUE:false}}
