#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {fileURLToPath} from 'node:url'
import {execFileSync,spawn} from 'node:child_process'
import {identity,sha} from '../nq5/schema.mjs'
import {LOCAL_SUITES} from '../nq5-b1/live.mjs'
import {REVIEW_LENSES} from '../nq5-r2/review-identity.mjs'
import {gitEnv} from '../nq5-b1-r1/gates.mjs'
import {assertLocalEvidence} from '../nq5-b3/gates.mjs'
import {sanitizeLog,pathScan} from '../nq5-b1-r2/privacy.mjs'
import {accepted,cut,digest,REVIEWS,BASE,ARCHIVE_SHA,CONTRACT_SHA,MANIFEST,OUTPUT} from './authority.mjs'
import {derive,serialize} from './model.mjs'
const root=path.resolve(fileURLToPath(new URL('../..',import.meta.url))),parent=path.dirname(root),local=path.join(root,'artifacts/g6p-b4-filtered/local')
const environment=Object.fromEntries(['PATH','HOME','USER','LOGNAME','SHELL','TMPDIR','LANG','LC_ALL','DISPLAY','XDG_RUNTIME_DIR','PLAYWRIGHT_BROWSERS_PATH','npm_config_cache'].flatMap(k=>process.env[k]===undefined?[]:[[k,process.env[k]]]))
const childEnv={...environment,PYTHONDONTWRITEBYTECODE:'1',NODE_OPTIONS:'--require '+path.join(root,'scripts/nq5-r2/hold.cjs'),npm_config_update_notifier:'false'}
const write=(dir,n,x)=>{const f=path.join(dir,n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,serialize(x))}
const run=(cmd,args,cwd=root)=>new Promise((resolve,reject)=>{const p=spawn(cmd,args,{cwd,env:childEnv,stdio:['ignore','pipe','pipe']});let out='';for(const s of[p.stdout,p.stderr])s.on('data',b=>{out+=b;if(out.length>64000000)p.kill()});p.on('error',()=>reject(new Error('B4_LOCAL_TOOL_UNAVAILABLE')));p.on('close',code=>{if(code===0)return resolve(out);const e=new Error('B4_LOCAL_TOOL_FAILED');e.safeOutput=out;reject(e)})})
const snapshot=()=>({candidate:cut(root),implementationSha256:digest(root)})
function persist(d){for(const[n,v]of Object.entries(d.entries))write(local,n,v)}
function reviewGate(index){const r=JSON.parse(fs.readFileSync(path.join(root,REVIEWS[index])));if(r.status!=='PASS_BOUNDED_NO_CREDENTIAL_SCOPE'||r.checkpoint!==(index===0?'B4_REVIEW_A_PRELIVE':'B4_REVIEW_B_POST_RECONSTRUCTION')||r.implementationSha256!==digest(root)||r.unresolvedAcceptedP0P1!==0||r.credentialAccess!==false||r.actualPrivateStateAccess!==false||r.providerRequests!==0||r.externalDocumentationGets!==0||identity(r.lenses.map(x=>x.name).sort())!==identity([...REVIEW_LENSES].sort())||r.lenses.some(x=>x.status!=='PASS_BOUNDED_SCOPE'))throw new Error('B4_BOUNDED_REVIEW_REQUIRED');if(execFileSync('git',['rev-parse',r.reviewedImplementationCommit+'^{tree}'],{cwd:root,env:gitEnv(),encoding:'utf8'}).trim()!==r.reviewedImplementationTree)throw new Error('B4_REVIEW_TREE');execFileSync('git',['merge-base','--is-ancestor',r.reviewedImplementationCommit,'HEAD'],{cwd:root,env:gitEnv()});return r}
function localGate(){const v=JSON.parse(fs.readFileSync(path.join(local,'VERIFICATION.json')));assertLocalEvidence(v,n=>fs.readFileSync(path.join(local,n+'.log')));if(identity(v.candidate)!==identity(cut(root))||v.implementationSha256!==digest(root))throw new Error('B4_CURRENT_ALL14_REQUIRED');return v}
async function verify(){accepted(root);const start=snapshot(),suites=[],assert=()=>{if(identity(start)!==identity(snapshot()))throw new Error('B4_VERIFICATION_SOURCE_CHANGED')},suite=async(name,cmd,args,cwd=root)=>{assert();process.stdout.write('LOCAL '+name+'\n');let out;try{out=await run(cmd,args,cwd)}catch(e){if(e.safeOutput?.trim())write(local,name+'.log',e.safeOutput);throw e}assert();if(!out.trim())throw new Error('B4_EMPTY_LOG');write(local,name+'.log',out);suites.push({name,status:'PASS',sha256:sha(Buffer.from(out))})};const names=['nq5-b1-executor','nq5-b1-r1-remediation','nq5-b1-r2-contracts','nq5-b1-r3-resume','nq5-b1-r3-r1-semantics','nq5-b1-r3-r2-signed-flow','nq5-b2-canary','nq5-b3-frontier','nq5-b4-filtered'];
 await suite('execution-adversarial','node',['node_modules/vitest/vitest.mjs','run',...names.map(n=>'tests/unit/'+n+'.test.mjs'),'--reporter=dot']);await suite('source-validator','python3',['VALIDATE_SOURCE_SET.py'],path.join(root,'docs/source/v1.7.0'));await suite('report-schema-controls','python3',['scripts/test-nq5-report-validation.py']);await suite('typecheck-lint','npm',['run','check']);await suite('acquisition-compile','npm',['run','acquisition:compile']);await suite('unit-regression','node',['node_modules/vitest/vitest.mjs','run','tests/unit',...names.flatMap(n=>['--exclude','tests/unit/'+n+'.test.mjs']),'--reporter=dot']);await suite('acquisition-regression','node',['node_modules/vitest/vitest.mjs','run','tests/acquisition','--reporter=dot']);await suite('browser-accessibility-performance','npm',['run','test:e2e','--','--reporter=line']);await suite('production-build','npm',['run','build']);await suite('browser-boundary','npm',['run','browser-boundary:verify']);await suite('records-office-boundary','npm',['run','g6p:a1:boundary:verify']);await suite('euler-public-pack','npm',['run','g6:pack:verify']);await suite('project-clock-status','npm',['run','project:status']);await suite('history-secret-boundary','node',['scripts/verify-git-secret-history.mjs']);assert();write(local,'VERIFICATION.json',{schemaVersion:'1.0.0',status:'PASS',generatedAtUtc:new Date().toISOString(),...start,suites,credentialAccess:false,actualPrivateStateAccess:false,privateMutation:false,externalRequests:0,networkHold:true,scope:'ISOLATED_LOCAL_REGRESSION_LOOPBACK_ONLY_NOT_PROVIDER_RUNTIME'});process.stdout.write('B4_ALL14_LOCAL_SUITES_PASS\n')
}

const PAYLOAD_NAMES=[
 'RECEIPTS/B3_LEAD_ACCEPTANCE_RECEIPT.json','CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json','CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json','EVIDENCE/B3_SOURCE_CALL_FRONTIER_QUALITY_CLASSIFICATION.json','EVIDENCE/BATCH4_FILTERED_CANDIDATE_REJECTION_MATRIX.json','EXECUTION/T1_BATCH4_FILTERED_EXECUTION_ENVELOPE.json','PLANS/T1_BATCH4_FILTERED_EXECUTION_PLAN.json','PLANS/T1_BATCH4_FILTERED_RESERVE_PLAN.json','PLANS/T1_BATCH4_FILTERED_FRONTIER_POLICY.json','REPORTS/T1_BATCH4_FILTERED_EXECUTION_REPORT.json','REPORTS/T1_BATCH4_FILTERED_RECONCILIATION_REPORT.json','REPORTS/T1_BATCH4_FILTERED_UTILITY_AND_VIABILITY_REPORT.json','REPORTS/T1_CAMPAIGN_STATE_REDACTED.json','SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json','SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json','PUBLIC/NQ5_PUBLIC_CALL_INDEX.json','PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256','EVIDENCE/NANSEN_API_REQUEST_AUDIT.json','EVIDENCE/B4_LIVE_REQUEST_IDENTITY_MATRIX.json','EVIDENCE/B4_ATTEMPT_CREDIT_COUNT_AND_PROVIDER_ID_RECONCILIATION.json','EVIDENCE/B4_PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json','EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json','OFFICIAL_DOCS/INDEX.json']
const EXTRA_NAMES=['README.md','DELIVERY_MANIFEST.json','MANIFEST.sha256','GIT/trace-escape-complete.bundle','SOURCE_DIFF.patch','SOURCE_INSTALL/B4_FILTERED_EXECUTION_CONTRACT_INSTALLATION_REPORT.json','SOURCE_INSTALL/ACTIVE_SOURCE_MANIFEST.sha256','EVIDENCE/BUGBOT_B4_PRELIVE_REVIEW.json','EVIDENCE/BUGBOT_B4_POSTLIVE_REVIEW.json','EVIDENCE/VERIFICATION_SUMMARY.json','EVIDENCE/REVIEW_FINDINGS_RESOLUTIONS.json','EVIDENCE/KNOWN_LIMITATIONS.md']
const LOG_NAMES=[...LOCAL_SUITES,'bundle-clone-fsck','fresh-clone-source-build-secret','fresh-clone-history-secret','redacted-delivery-secret','exact-readonly-baseline-filtered-reconstruction']
const files=d=>fs.readdirSync(d).sort().flatMap(n=>{const f=path.join(d,n),s=fs.lstatSync(f);if(s.isSymbolicLink())throw new Error('B4_PACKAGE_SYMLINK');return s.isDirectory()?files(f):[f]})
async function deliver(){
 const v=localGate(),reviews=[reviewGate(0),reviewGate(1)],d=derive(root),candidate=cut(root);if(d.frontier.liveGate.pass||d.report.newAttempts!==0)throw new Error('B4_BLOCKED_DELIVERY_SCOPE');if(fs.existsSync(path.join(parent,OUTPUT)))throw new Error('B4_EXISTING_DELIVERY_PRESERVED')
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'trace-b4-filtered-delivery-')),dir=path.join(temp,'delivery');fs.mkdirSync(dir)
 try{const payload={},bindings=[],allow=new Set([...PAYLOAD_NAMES,...EXTRA_NAMES,...LOG_NAMES.map(n=>'VERIFICATION/'+n+'.log')]),put=(n,x)=>{if(!allow.has(n))throw new Error('B4_EXACT_PACKAGE_ALLOWLIST');payload[n]=serialize(x);write(dir,n,payload[n])},log=(n,x)=>{const s=sanitizeLog(x,root);if(!s.text.trim())throw new Error('B4_EMPTY_DELIVERY_LOG');put('VERIFICATION/'+n+'.log',s.text);bindings.push({file:'VERIFICATION/'+n+'.log',sourceSha256:s.sourceSha256,sanitizedSha256:s.sanitizedSha256,otherPathRedactions:s.otherPathRedactions})}
  if(identity(Object.keys(d.entries).sort())!==identity([...PAYLOAD_NAMES].sort()))throw new Error('B4_EXACT_DERIVED_PAYLOAD_SET')
  for(const[n,x]of Object.entries(d.entries))put(n,x)
  put('README.md','# TRACE//ESCAPE filtered B4\n\nBLOCKED_WITH_EVIDENCE. Five B3 calls are formally Lead accepted: total8, immutable supplier count11, held3 excluded. The filtered ordinary non-hub frontier has '+d.frontier.matrix.ordinaryAdmittedCount+' meaningful unissued candidates; four are required before any live batch. No B4 credential resolution, docs refresh, private writes, locks, provider attempt or new credit. Rejected64 plan has no issue path. Planning-only generic source classes never become public provider/player labels. Complete reconstruction is not a negative proof or exhaustion claim. No Batch5 issue/plan, floor1024, qualification, exact UTC/proof/completeness/causation, gameplay integration, art, narrative, Mission02, hosting or release claim. Powered by Nansen API. Stop for Lead review.\n')
  put('DELIVERY_MANIFEST.json',{schemaVersion:'1.0.0',status:d.status,candidate,implementationSha256:digest(root),executionContractSha256:CONTRACT_SHA,acceptedB3ArchiveSha256:ARCHIVE_SHA,sourceManifestSha256:d.c.a.sourceManifestSha256,sourceFilesVerified:68,leadAcceptedBeforeB4:8,leadAcceptedAfterB4:8,supplierCountedTerminals:11,permanentlyHeldCalls:3,newAttempts:0,newKnownCredits:0,newLocalSupportCandidates:0,ordinaryMeaningfulCandidates:d.frontier.matrix.ordinaryAdmittedCount,thresholdRequired:4,planRequests:d.frontier.plan.requests.length,credentialAccess:false,credentialResolutionAttempted:false,privateMutation:false,reviewerExternalRequests:0,unauthenticatedDocumentationGets:0,authenticatedCampaignProviderRequests:0,accountRequests:0,browserRuntimeProviderRequests:0,BATCH4_AUTHORIZED_TO_ISSUE:false,BATCH5_AUTHORIZED_TO_ISSUE:false,rawPrivateBytesPackaged:false,privatePathsPackaged:false,externalHumanReadableLabelsPackaged:false,assetLanePackaged:false})
  put('SOURCE_INSTALL/B4_FILTERED_EXECUTION_CONTRACT_INSTALLATION_REPORT.json',{schemaVersion:'1.0.0',contractSha256:CONTRACT_SHA,acceptedBaseCommit:BASE,acceptedB3ArchiveSha256:ARCHIVE_SHA,acceptedB3SourceDiffSha256:d.c.a.archiveSourceDiffSha256,unchangedFoundationSourceFiles:67,additiveSourceFiles:1,all68SourceHashesVerified:true})
  put('SOURCE_INSTALL/ACTIVE_SOURCE_MANIFEST.sha256',fs.readFileSync(path.join(root,MANIFEST)))
  put('EVIDENCE/BUGBOT_B4_PRELIVE_REVIEW.json',reviews[0]);put('EVIDENCE/BUGBOT_B4_POSTLIVE_REVIEW.json',reviews[1]);put('EVIDENCE/REVIEW_FINDINGS_RESOLUTIONS.json',{schemaVersion:'1.0.0',unresolvedAcceptedP0P1:0,reviews,liveBatchNotIssued:true,blockedReason:d.frontier.liveGate.reason,noRuntimeImplementationClaimed:true})
  put('EVIDENCE/KNOWN_LIMITATIONS.md','# Known limitations\n\nThe current filtered frontier fails the exact four-ordinary-candidate prelive threshold; there is no B4 live transport/capability in this read-only implementation. Any future adequate frontier still requires its own reviewed runtime gates; no candidate artifact can authorize issue. All8 existing Lead acceptances preserve immutable supplier order1/5/6/7/8/9/10/11, separate Lead order1..8. Existing11 supplier counts include permanently held3. Planning-only public-source codes are Lead-supplied, not Nansen labels, human identity, causation or gameplay claims. High raw row count does not imply case utility. Per-call780 rows and772 distinct tuples are separate. New sole low-volume counterparty has only one supporting transaction; do not issue it to fill a count. Historical safe balance arithmetic remains unexplained; no account observation was added. Historical docs are accepted prior bindings, not fresh B4 runtime admission. No B4 issue or evidence of 75% live support; therefore no B5 plan. This is not a route-exhaustion or negative-proof claim. Product/art/narrative/accessibility/qualification/1024/hosting/release acceptance remain unchanged.\n')
  for(const n of LOCAL_SUITES)log(n,fs.readFileSync(path.join(local,n+'.log')))
  log('exact-readonly-baseline-filtered-reconstruction',JSON.stringify({status:'PASS_READONLY_BASELINE_FILTERED_HOLD',leadReceiptIdentity:d.lead.hash,sourceQualityIdentity:d.quality.hash,filteredMatrixIdentity:identity(d.frontier.matrix),ledgerSha256:d.report.ledgerSha256,ledgerBytes:d.report.ledgerBytes,rawMirrorsEqual:true,lead8:true,supplier11:true,held3:true,newRequests:0,credentialAccess:false,privateMutation:false,reason:d.frontier.liveGate.reason})+'\n')
  const bundle=path.join(dir,'GIT/trace-escape-complete.bundle');fs.mkdirSync(path.dirname(bundle));await run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD']);const bl=await run('git',['bundle','verify',bundle]),clone=path.join(temp,'clone');await run('git',['clone','--quiet',bundle,clone]);const cg=(...a)=>execFileSync('git',a,{cwd:clone,env:childEnv,encoding:'utf8'}).trim();if(cg('rev-parse','HEAD')!==candidate.commit||cg('rev-parse','HEAD^{tree}')!==candidate.tree)throw new Error('B4_BUNDLE_CLONE_IDENTITY');const fl=await run('git',['fsck','--full','--strict'],clone);log('bundle-clone-fsck',bl+'\nFresh clone '+candidate.commit+' / '+candidate.tree+'; fsck exit0 '+(fl.trim()||'no diagnostics')+'\n');put('GIT/trace-escape-complete.bundle',fs.readFileSync(bundle));put('SOURCE_DIFF.patch',execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:root,env:childEnv,maxBuffer:256000000}));fs.cpSync(path.join(root,'dist'),path.join(clone,'dist'),{recursive:true});log('fresh-clone-source-build-secret',await run('node',[path.join(root,'scripts/scan-prohibitions.mjs'),clone]));log('fresh-clone-history-secret',await run('node',['scripts/verify-git-secret-history.mjs'],clone));log('redacted-delivery-secret',await run('node',[path.join(root,'scripts/scan-prohibitions.mjs'),dir]))
  put('EVIDENCE/VERIFICATION_SUMMARY.json',{...Object.fromEntries(Object.entries(v).filter(([k])=>!['externalRequests','networkHold','scope'].includes(k))),localVerificationScope:v.scope,localExternalRequests:0,localNetworkHold:true,localActualPrivateStateAccess:false,actualPrivateStateAccess:true,runtimeScope:'READONLY_ACCEPTED_THIRTEEN_RESPONSE_BASELINE_AND_FILTERED_HOLD_NO_LIVE_BATCH',credentialAccess:false,privateMutation:false,reviewerExternalRequests:0,unauthenticatedDocumentationGets:0,authenticatedCampaignProviderRequests:0,accountRequests:0,browserRuntimeProviderRequests:0,sourceBundleFreshCloneIdentityVerified:true,deliveryLogBindings:bindings})
  const scan=pathScan(payload);if(scan.status!=='PASS')throw new Error('B4_ABSOLUTE_PATH_LEAK');put('EVIDENCE/VERIFICATION_SUMMARY.json',{...JSON.parse(payload['EVIDENCE/VERIFICATION_SUMMARY.json']),pathRedactionScan:scan})
  for(const f of files(dir))if(!allow.has(path.relative(dir,f)))throw new Error('B4_PACKAGE_FILE_ALLOWLIST')
  put('MANIFEST.sha256',files(dir).map(f=>sha(fs.readFileSync(f))+'  '+path.relative(dir,f)).sort().join('\n')+'\n')
  const final=derive(root);if(identity(cut(root))!==identity(candidate)||identity(Object.entries(d.entries).map(([n,x])=>[n,sha(serialize(x))]))!==identity(Object.entries(final.entries).map(([n,x])=>[n,sha(serialize(x))])))throw new Error('B4_FINAL_EVIDENCE_CHANGED')
  const names=files(dir).map(f=>{fs.utimesSync(f,new Date('2000-01-01T00:00:00Z'),new Date('2000-01-01T00:00:00Z'));return path.relative(dir,f)}).sort(),z=path.join(temp,'delivery.zip'),z2=path.join(temp,'rebuilt.zip');await run('zip',['-X','-q',z,...names],dir);await run('zip',['-X','-q',z2,...names],dir);if(sha(fs.readFileSync(z))!==sha(fs.readFileSync(z2)))throw new Error('B4_ARCHIVE_REBUILD');await run('unzip',['-t',z]);const ex=path.join(temp,'extracted');fs.mkdirSync(ex);await run('unzip',['-q',z,'-d',ex]);await run('sha256sum',['-c','MANIFEST.sha256'],ex);const output=path.join(parent,OUTPUT);fs.copyFileSync(z,output,fs.constants.COPYFILE_EXCL);process.stdout.write(JSON.stringify({status:d.status,archive:output,sha256:sha(fs.readFileSync(output)),leadAccepted:8,ordinaryCandidates:d.frontier.matrix.ordinaryAdmittedCount,newAttempts:0,newCredits:0,credentialAccess:false,BATCH4_AUTHORIZED_TO_ISSUE:false,BATCH5_AUTHORIZED_TO_ISSUE:false})+'\n')
 }finally{fs.rmSync(temp,{recursive:true,force:true})}
}
async function main(){process.env=environment;if(process.argv.length!==3)throw new Error('B4_UNSUPPORTED_MODE');switch(process.argv[2]){case'--derive':case'--post':{const d=derive(root);persist(d);process.stdout.write(JSON.stringify({status:d.status,reason:d.frontier.liveGate.reason,source:d.c.source,leadAccepted:8,supplierCounted:11,held:3,ordinaryCandidates:d.frontier.matrix.ordinaryAdmittedCount,planRequests:d.frontier.plan.requests.length,candidateRows:d.frontier.matrix.completeCandidateCount,newAttempts:0,newCredits:0,credentialAccess:false,privateMutation:false})+'\n');break}case'--local':await verify();break;case'--deliver':await deliver();break;case'--execute':{const d=derive(root);persist(d);throw new Error(d.frontier.liveGate.reason)}default:throw new Error('B4_UNSUPPORTED_MODE')}}
main().catch(e=>{process.stderr.write((/^B4_[A-Z0-9_]{1,120}$/.test(e.message)?e.message:'B4_FAIL_CLOSED_NO_UNSAFE_ERROR_EXPORT')+'; no provider issue, credentials, private mutation, reissue or repair.\n');process.exitCode=1})
