import fs from 'node:fs'
import path from 'node:path'
import { identity, sha, validateSchema } from '../nq5/schema.mjs'
import { parseExactJson } from '../nq5/exact-json.mjs'
import { temporal, TEMPORAL } from '../nq5-b1-r3/compatibility.mjs'
import { signedTransfers, RULE } from '../nq5-b1-r3-r2/signed-flow.mjs'
import { assertCampaignRecord } from '../nq5-b1-r3-r1/semantics.mjs'
import { AUTH as PUBLIC_AUTH } from '../nq5/planner.mjs'
import { IDS } from './authority.mjs'
export function admit(context,q,raw,row,sequence){
 const {a,plans,priorResult}=context,p=priorResult.profile,stages={},fail=(k,code,semantic=null)=>({safelyAdmissible:false,firstFailedStage:k,stages:{...stages,[k]:{status:'FAIL',code}},publicRecord:null,normalizedRecords:[],resultCount:0,normalizedSha256:null,semantic})
 if(!IDS.includes(q.logicalId)||!plans.plan.requests.some(r=>identity(r)===identity(q))||p.hash!==a.b2PriorObjects['CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json'].hash)throw new Error('B2_EXACT_PLAN_PROFILE_SCOPE')
 let exact,response;try{if(!Buffer.isBuffer(raw)||sha(raw)!==row.rawSha256||raw.length!==row.rawBytes)throw 0;exact=parseExactJson(raw);response=JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(raw));stages.json={status:'PASS'}}catch{return fail('json','RAW_HASH_BYTES_UTF8_DUPLICATE_JSON')}
 try{validateSchema('provider',response,a.context.profile.compatibilitySchema);stages.schema={status:'PASS',schemaIdentity:a.context.profile.compatibilitySchemaIdentity}}catch{return fail('schema','EXACT_NULL_TIME_SCHEMA')}
 try{const g=response.pagination;if(g.page!==1||g.per_page!==100||typeof g.is_last_page!=='boolean'||response.data.length>100||!g.is_last_page&&!response.data.length)throw 0;stages.pagination={status:'PASS'}}catch{return fail('pagination','EXACT_PAGE1_METADATA')}
 const times=[];try{const seen=new Map();for(const tx of response.data){const h=tx.transaction_hash.toLowerCase(),t=temporal(tx.block_timestamp,q,a.context.truth.times[h]);if(seen.has(h)&&seen.get(h)!==tx.block_timestamp)throw 0;seen.set(h,tx.block_timestamp);times.push(t)}stages.contextualTemporal={status:'PASS',timezoneEstablished:false,acceptedExactHashJoins:times.filter(t=>t.exactUtcFromAcceptedTruth).length}}catch{return fail('contextualTemporal','MALFORMED_OUTSIDE_BOUND_OR_TRUTH_CONFLICT')}
 let semantic;try{semantic=signedTransfers(exact,q,times,p,row.providerRequestId);if(!semantic.pass)return fail('normalization',semantic.code,semantic);stages.normalization={status:'PASS',signedFlowProfileIdentity:p.hash,normalizationRule:RULE,exactMagnitudeLexeme:true,subjectParticipation:true,deduplication:true}}catch{return fail('normalization','EXACT_SIGNED_TRANSFER_CORE')}
 try{if(semantic.normalizedRecords.some(r=>Object.keys(r).some(k=>!['transaction_hash','from_address','to_address','token_address','amount','evidence_grade','temporal_class','accepted_exact_utc','accepted_exact_time_source'].includes(k))))throw 0;stages.projection={status:'PASS',conversionMatrixIdentity:identity(semantic.matrix),allowlistOnly:true}}catch{return fail('projection','MAGNITUDE_ALLOWLIST',semantic)}
 const publicRecord={schema_version:'5.0.1',campaign_id:a.context.bound.envelope.campaignId,authorization_id:PUBLIC_AUTH,public_call_id:'NQ5-'+String(sequence).padStart(6,'0'),qualification_sequence:sequence,tranche_id:'T1',endpoint_family:q.family,business_question:q.businessQuestion,purpose_code:q.purpose,consumer_ids:q.consumers,request_body_sha256:identity(q.body),response_sha256:row.rawSha256,normalized_sha256:semantic.normalizedIdentity,result_count:semantic.normalizedRecords.length,route_disposition:'BOUNDED_ACTIVITY',evidence_grade:'CONTEXTUAL',temporal_class:TEMPORAL,coverage_scope:q.body.date.from+' through '+q.body.date.to+'; PAGE.1 server-filtered contextual activity only; no exact UTC, negative evidence, cutoff completeness or causation',selection_lineage_summary:q.lineage,coverage_cell_ids:q.coverageCells,coverage_key:q.coverageKey,raw_payload_published:false,attribution:'Powered by Nansen API',investigative_question_id:q.questionId,question_lens:q.lens}
 try{assertCampaignRecord(publicRecord);validateSchema('provider',publicRecord,JSON.parse(fs.readFileSync(path.join(a.context.root,'schemas/NQ5_PUBLIC_CALL_INDEX.schema.json'))).items);stages.publicSchema={status:'PASS',exactCampaignBinding:true}}catch{return fail('publicSchema','EXACT_PUBLIC_CAMPAIGN_SCHEMA',semantic)}
 return {safelyAdmissible:true,firstFailedStage:null,stages,publicRecord,normalizedRecords:semantic.normalizedRecords,normalizedSha256:semantic.normalizedIdentity,resultCount:semantic.normalizedRecords.length,semantic,pagination:exact.pagination}
}
