import fs from 'node:fs'
import path from 'node:path'
import { identity, validateSchema } from '../nq5/schema.mjs'
import { AUTH, CONTRACT_SHA, IDS } from './authority.mjs'
import { admit } from './admission.mjs'
const keys=['json','schema','pagination','contextualTemporal','normalization','projection','publicSchema']
export function audit(context,state,rawFor,prospective=null){
 const records=context.priorResult.audit.records.map(r=>structuredClone(r));let supported=0
 for(const q of context.plans.plan.requests){const starts=[...state.starts.values()].filter(s=>s.logicalId===q.logicalId),t=prospective?.logicalId===q.logicalId?prospective:state.terminals.get(q.logicalId),counted=t?.disposition==='SUCCESS_COUNTED';let latest=null
  const attempts=starts.map(s=>{const r=state.responses.get(q.logicalId+'.'+s.attempt),a=r?.httpStatus===200?admit(context,q,rawFor(r),r,t?.publicRecord?.qualification_sequence??5):null;latest=a;return {attemptNumber:s.attempt,attemptIdentity:s.hash,startSequence:s.sequence,responseSequence:r?.sequence??null,terminalSequence:t?.attempt===s.attempt?t.sequence??state.rows.length+1:null,issuedAtUtc:s.issuedAtUtc,completedAtUtc:r?.completedAtUtc??null,completedTimestampDisposition:r?'CAPTURED':'NO_RESPONSE',latencyMs:r?.latencyMs??null,httpStatus:r?.httpStatus??null,provider_request_id:r?.providerRequestId??null,providerRequestIdDisposition:r?r.providerRequestId?'CAPTURED':'MISSING_FUTURE_REQUEST_ID':'NO_RESPONSE',safeHeaders:r?.headers??{},quotedCredits:r?.quotedCredits??null,actualCredits:r?.actualCredits??null,remainingCredits:r?.remainingCredits??null,rawBytes:r?.rawBytes??null,primarySha256:r?.rawSha256??null,mirrorSha256:r?.rawSha256??null,bytesEqual:!!r,responseSchemaIdentity:context.a.context.profile.publishedResponseSchemaIdentity,validation:null}})
  if(counted){if(!latest?.safelyAdmissible||!latest.resultCount||latest.normalizedSha256!==t.normalizedSha256||latest.resultCount!==t.resultCount||identity(latest.publicRecord)!==identity(t.publicRecord))throw new Error('B2_AUDIT_DURABLE_ACCEPTANCE');supported++}
  records.push({authorizationId:AUTH,executionContractSha256:CONTRACT_SHA,campaignId:context.lead.campaignId,trancheId:'T1',batchId:'B2',planSequence:q.sequence,logicalId:q.logicalId,family:q.family,path:q.path,method:q.method,requestBodySha256:identity(q.body),investigativeQuestionId:q.questionId,questionLens:q.lens,purposeCode:q.purpose,businessQuestion:q.businessQuestion,selectionLineage:q.lineage,coverageCells:q.coverageCells,coverageKey:q.coverageKey,consumerIds:q.consumers,frontierProof:q.frontierProof,candidateRole:q.candidateRole,planIdentity:context.plans.plan.hash,leadAcceptanceReceiptIdentity:context.lead.hash,expectedCredits:1,worstCaseCredits:3,issued:starts.length>0,issueDisposition:starts.length?'ISSUED_B2':state.starts.size>6?'NOT_ISSUED_BREAKER':'NOT_ISSUED_PRELIVE_HOLD',attempts,terminalDisposition:t?.disposition??null,qualificationCounted:!!counted,qualificationSequence:counted?t.publicRecord.qualification_sequence:null,exclusionReason:counted?null:t?.reason??'NOT_ISSUED_OR_UNRESOLVED',publicCallId:counted?t.publicRecord.public_call_id:null,normalizedIdentity:counted?t.normalizedSha256:null,admittedResultCount:counted?t.resultCount:null,qualification_value:counted?'ADMITTED_BOUNDED_EVIDENCE':'ZERO_NOT_COUNTED',engineering_value:starts.length?['AUTHENTICATED_TRANSPORT','CONCURRENCY_OBSERVATION','DURABLE_PRIMARY_MIRROR_STORAGE','BILLING_RATE_HEADER_OBSERVATION',...(!counted?['VALIDATION_MISMATCH_DIAGNOSIS']:[])]:[],gameplay_consumer_value:counted?'ADMITTED_BOUNDED_EVIDENCE_NOT_INTEGRATION_ACCEPTANCE':'NO_ADMITTED_GAMEPLAY_EVIDENCE_FROM_B1_V1',competition_evidence_value:counted?'SAFE_ADMITTED_QUALIFICATION_AUDIT':starts.length?'SAFE_ENGINEERING_AUDIT_ONLY':'PLAN_ONLY_NOT_ISSUED',signedFlowReview:{profileIdentity:context.priorResult.profile.hash,observedNullTimeProfileIdentity:context.a.context.profile.hash,stageStatuses:Object.fromEntries(keys.map(k=>[k,latest?.stages[k]?.status??'NOT_RUN'])),stats:latest?.semantic?.stats??null,matrixIdentity:latest?.semantic?identity(latest.semantic.matrix):null,localSupportCandidate:!!counted,leadAccepted:false}})
 }
 const result={...context.priorResult.audit,records,b2ContractReview:{executionContractSha256:CONTRACT_SHA,leadAcceptanceReceiptIdentity:context.lead.hash,planIdentity:context.plans.plan.hash,leadAcceptedBeforeB2:1,permanentlyHeldCalls:3,newLocalSupportCandidates:supported}}
 validateSchema('provider',result,JSON.parse(fs.readFileSync(path.join(context.root,'schemas/NANSEN_API_REQUEST_AUDIT.schema.json'))));if(records.length!==17||identity(records.slice(0,15))!==identity(context.priorResult.audit.records))throw new Error('B2_AUDIT_PRIOR_RECORDS_CHANGED');return result
}
