import fs from 'node:fs'
import path from 'node:path'
import { identity, validateSchema } from '../nq5/schema.mjs'
import { accepted, CONTRACT_SHA, ARCHIVE_SHA } from './authority.mjs'
import { validateSpecific, receipt, requestsFromProof, freezeFromRequests, COUNTERPARTY, DURABLE_TX } from './planner.mjs'
import { audit as buildAudit } from './audit.mjs'
export function unknownCounters(){return {newAttempts:null,newProvider2xx:null,newSupplierCountedTerminals:null,supplierCountedTerminals:null,newKnownCredits:null,knownCampaignCredits:null,unresolvedReservations:null,unresolvedTerminals:null,currentLedgerSha256:null,currentLedgerBytes:null,currentOriginalPrefixUnchanged:null,newLocalSupportCandidates:0,newFactsAdmitted:false}}
export const SAFE_ARTIFACTS=new Set(['RECEIPTS/R3_R2_LEAD_ACCEPTANCE_RECEIPT.json','CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json','CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json','PLANS/T1_BATCH2_EXECUTION_PLAN.json','PLANS/T1_BATCH2_RESERVE_PLAN.json','PLANS/T1_BATCH2_FRONTIER_POLICY.json','SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json','SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json','EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json','EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'])
export function readSafeArtifact(root,name){if(!SAFE_ARTIFACTS.has(name))throw new Error('B2_FINITE_SAFE_ARTIFACT_NAME');const parts=['artifacts','g6p-b2','local',...name.split('/')];let f=root;for(const[i,n]of parts.entries()){f=path.join(f,n);const s=fs.lstatSync(f);if(s.isSymbolicLink()||s.uid!==process.getuid()||(i<parts.length-1?!s.isDirectory():!s.isFile()||s.nlink!==1||s.size>16000000))throw new Error('B2_SAFE_ARTIFACT_METADATA')}const fd=fs.openSync(f,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{return fs.readFileSync(fd)}finally{fs.closeSync(fd)}}
export function publicBaselineArtifacts(a){const o=a.b2PriorObjects,result={perCall:o['EVIDENCE/R3_PER_CALL_SEMANTIC_REVALIDATION.json'].calls,index:o['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'],audit:o['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'],profile:o['CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json']},state={identity:o['DELIVERY_MANIFEST.json'].immutablePrivateStateIdentity,privateHashes:{'qualification.jsonl':'99ac010b27f3b98bcbc1eb82b053b9c190ad0cf40ac0c393a8d604d02d436374'},rows:[]},lead=receipt(a,state,result),row=o['EVIDENCE/FRONTIER_CANDIDATE_REJECTION_MATRIX.json'].rows.find(r=>r.subjectAddress===COUNTERPARTY&&r.supportingTransactionHashes.includes(DURABLE_TX)),proof=row?.sourceLineage.find(r=>r.kind==='OPPOSITE_SIDE_SUBJECT_COUNTERPARTY')?.lineage.find(r=>r.startsWith('TRANSFER_IDENTITY.'));if(!proof)throw new Error('B2_PUBLIC_PINNED_COUNTERPARTY_PROOF');const q=requestsFromProof(a,lead,proof.slice('TRANSFER_IDENTITY.'.length)),plans=freezeFromRequests(a,state,result,lead,q);const auditTemplate=buildAudit({root:a.context.root,a,lead,plans,priorResult:result},{rows:[],starts:new Map(),responses:new Map(),terminals:new Map()},()=>{throw new Error('B2_PUBLIC_TEMPLATE_NO_RAW_ACCESS')});return {lead,...plans,auditTemplate}}
export function historicalBlocked(root,phase,reason){const a=accepted(root);return historicalBlockedModel(a,n=>readSafeArtifact(root,n),fs.readFileSync(path.join(root,'schemas/NANSEN_API_REQUEST_AUDIT.schema.json')),fs.readFileSync(path.join(root,'schemas/NQ5_PUBLIC_CALL_INDEX.schema.json')),phase,reason,publicBaselineArtifacts(a))}
export function historicalBlockedModel(a,readArtifact,auditSchema,publicSchema,phase,reason,expected){
 const j=n=>JSON.parse(readArtifact(n)),lead=j('RECEIPTS/R3_R2_LEAD_ACCEPTANCE_RECEIPT.json'),plan=j('PLANS/T1_BATCH2_EXECUTION_PLAN.json'),reserve=j('PLANS/T1_BATCH2_RESERVE_PLAN.json'),policy=j('PLANS/T1_BATCH2_FRONTIER_POLICY.json');for(const o of [lead,plan,reserve,policy]){const{hash,...payload}=o;if(hash!==identity(payload)||o.executionContractSha256!==CONTRACT_SHA)throw new Error('B2_HISTORICAL_SAFE_SEAL')}
 if(!expected||identity({lead,plan,reserve,policy})!==identity({lead:expected.lead,plan:expected.plan,reserve:expected.reserve,policy:expected.policy})||!expected.auditTemplate)throw new Error('B2_HISTORICAL_EXACT_PUBLIC_ARTIFACTS')
 validateSpecific(plan.requests);if(lead.reviewedR3R2ArchiveSha256!==ARCHIVE_SHA||lead.leadAcceptedSuccesses!==1||plan.leadAcceptanceReceiptIdentity!==lead.hash||reserve.planIdentity!==plan.hash||plan.frontierPolicyIdentity!==policy.hash)throw new Error('B2_HISTORICAL_SAFE_BINDING');const prior=a.b2PriorObjects,index=prior['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'],cachedAudit=j('EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'),audit=structuredClone(expected.auditTemplate);if(identity(cachedAudit.records.slice(0,15))!==identity(prior['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'].records))throw new Error('B2_HISTORICAL_AUDIT_PREFIX');for(const r of audit.records.slice(15)){r.issued=null;r.issueDisposition='ISSUE_STATE_UNKNOWN_AFTER_DURABLE_BREAKER';r.attempts=[];r.terminalDisposition=null;r.qualificationCounted=null;r.qualificationSequence=null;r.exclusionReason='CURRENT_DURABLE_STATE_UNVERIFIABLE_NO_NEW_FACTS_ADMITTED';r.publicCallId=null;r.normalizedIdentity=null;r.admittedResultCount=null;r.qualification_value='UNKNOWN_NOT_ADMITTED_AFTER_DURABLE_BREAKER';r.engineering_value=[];r.gameplay_consumer_value='NO_ADMITTED_GAMEPLAY_EVIDENCE_FROM_B1_V1';r.competition_evidence_value='SAFE_ENGINEERING_AUDIT_ONLY';r.signedFlowReview={profileIdentity:lead.signedFlowCompatibilityProfileIdentity,observedNullTimeProfileIdentity:lead.observedNullTimeProfileIdentity,stageStatuses:Object.fromEntries(['json','schema','pagination','contextualTemporal','normalization','projection','publicSchema'].map(k=>[k,'NOT_RUN'])),stats:null,matrixIdentity:null,localSupportCandidate:false,leadAccepted:false}}
 audit.b2ContractReview.newLocalSupportCandidates=0;audit.b2ContractReview.evidenceStatus='HISTORICAL_ONLY_CURRENT_PRIVATE_RECONCILIATION_BLOCKED';validateSchema('provider',audit,JSON.parse(auditSchema));const report={schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',reason,evidenceScope:'HISTORICAL_ACCEPTED_BASELINE_ONLY_CURRENT_PRIVATE_STATE_UNVERIFIABLE',historicalBaseline:{httpAttempts:6,provider2xx:6,supplierCountedTerminals:4,leadAccepted:1,knownCampaignCredits:6,ledgerBytes:32547,ledgerSha256:lead.immutableLedgerSha256,permanentlyHeldCalls:3},...unknownCounters(),leadAcceptedBeforeB2:1,leadAcceptedAfterB2:1,accountRequests:0,reissueAllowed:false,privateRepairAllowed:false,BATCH3_AUTHORIZED_TO_ISSUE:false};const entries={};for(const n of ['RECEIPTS/R3_R2_LEAD_ACCEPTANCE_RECEIPT.json','CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json','CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json','PLANS/T1_BATCH2_EXECUTION_PLAN.json','PLANS/T1_BATCH2_RESERVE_PLAN.json','PLANS/T1_BATCH2_FRONTIER_POLICY.json','SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json','SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json','EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json'])entries[n]=readArtifact(n)
 for(const n of ['CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json','CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json']){if(!Buffer.isBuffer(a.b2PriorBytes[n]))throw new Error('B2_PINNED_PUBLIC_PROFILE_REQUIRED');entries[n]=a.b2PriorBytes[n]}entries['SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json']=auditSchema;entries['SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json']=publicSchema;entries['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json']=a.b2PriorBytes['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'];entries['PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256']=a.b2PriorBytes['PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256'];entries['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json']=audit;for(const n of ['REPORTS/T1_B2_RECONCILIATION_REPORT.json','EVIDENCE/B2_ATTEMPT_CREDIT_COUNT_AND_PROVIDER_ID_RECONCILIATION.json','EVIDENCE/B2_PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json'])entries[n]=report;entries['REPORTS/T1_B2_EXECUTION_REPORT.json']={...phase,...report,credentialAccess:phase.credentialAccess,privateMutation:phase.privateMutation};entries['REPORTS/T1_CAMPAIGN_STATE_REDACTED.json']=report;entries['REPORTS/T1_B2_UTILITY_AND_FRONTIER_VIABILITY_REPORT.json']={schemaVersion:'1.0.0',status:'NOT_ASSESSABLE_DURABLE_BREAKER',reason,floor1024RouteUnproven:true,newFactsAdmitted:false,BATCH3_AUTHORIZED_TO_ISSUE:false};entries['EVIDENCE/BATCH3_FRONTIER_CANDIDATE_REJECTION_MATRIX.json']={schemaVersion:'1.0.0',status:'NOT_DERIVED_DURABLE_BREAKER',reason,rows:[],noExhaustionClaim:true,AUTHORIZED_TO_ISSUE:false};entries['EVIDENCE/B2_LIVE_REQUEST_IDENTITY_MATRIX.json']={schemaVersion:'1.0.0',status:'HISTORICAL_PLAN_ONLY_CURRENT_EXECUTION_UNKNOWN',reason,requests:plan.requests.map(q=>({logicalId:q.logicalId,sealedRequestIdentity:identity(q),questionId:q.questionId,lens:q.lens,purpose:q.purpose,frontierProof:q.frontierProof,lineage:q.lineage,consumers:q.consumers,coverageKey:q.coverageKey,coverageCells:q.coverageCells,issued:null,terminalDisposition:null,newLocalSupportCandidate:false}))};entries['EXECUTION/T1_B2_EXECUTION_ENVELOPE.json']={schemaVersion:'1.0.0',status:'LIVE_ARTIFACT_NOT_REVERIFIED_AFTER_DURABLE_BREAKER',reason,AUTHORIZED_TO_ISSUE:false,planIdentity:plan.hash,leadAcceptanceReceiptIdentity:lead.hash}
 return {status:'BLOCKED_WITH_EVIDENCE',entries,report,phase,c:{a,lead,state:{identity:a.b2PriorObjects['DELIVERY_MANIFEST.json'].immutablePrivateStateIdentity}},historicalOnly:true}
}
