import fs from 'node:fs'
import path from 'node:path'
import { identity, sha } from '../nq5/schema.mjs'
import { corpusAt } from '../nq5-b1-r2/gates.mjs'
import { get } from '../nq5-b1-r2/fetch-docs.mjs'
import { NAMES, allowed, assertFresh, validateCapturedIndex } from '../nq5-b1-r3/docs.mjs'
import { localGate, reviewGate } from './gates.mjs'
import { assertBaseline } from './context.mjs'
const proofs=new WeakMap()
export function readCaptured(root){let dir=root;for(const n of ['artifacts','g6p-b2','docs']){dir=path.join(dir,n);const s=fs.lstatSync(dir);if(s.isSymbolicLink()||!s.isDirectory()||s.uid!==process.getuid())throw new Error('B2_CAPTURE_DIRECTORY_METADATA')}const read=(name,max)=>{const f=path.join(dir,name),s=fs.lstatSync(f);if(s.isSymbolicLink()||!s.isFile()||s.nlink!==1||s.uid!==process.getuid()||s.size>max)throw new Error('B2_CAPTURE_FILE_METADATA');const fd=fs.openSync(f,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const q=fs.fstatSync(fd);if(q.ino!==s.ino||q.dev!==s.dev||q.nlink!==1||!q.isFile())throw new Error('B2_CAPTURE_OPEN_IDENTITY');return fs.readFileSync(fd)}finally{fs.closeSync(fd)}};const bytes=read('INDEX.json',100000),index=validateCapturedIndex(JSON.parse(bytes)),bodies={};for(const r of index.snapshots){if(!allowed(r.url)||!NAMES.includes(r.name)||r.filename!==r.name+'.md')throw new Error('B2_FINITE_CAPTURE_NAMES');if(!r.reusedR2){const b=read(r.filename,4000000);if(b.length!==r.bytes||sha(b)!==r.sha256)throw new Error('B2_CAPTURE_BODY_HASH');bodies[r.name]=b}}return {index,indexBytes:bytes,bodies}}
export function verifyCapturedBinding(root,expectedIdentity){const d=readCaptured(root);if(identity(d.index)!==expectedIdentity||d.index.snapshots.length!==5)throw new Error('B2_SEALED_CAPTURE_IDENTITY');return d}
export function assertLiveDocs(c,d){if(!proofs.has(d)||proofs.get(d)!==identity(d.index))throw new Error('B2_BRANDED_FRESH_DOCUMENTS_REQUIRED');validateCapturedIndex(d.index);const corpus=corpusAt(c.root).corpus,old=c.a.objects['OFFICIAL_DOCS/INDEX.json'],comparison=Object.fromEntries(NAMES.map(n=>[n,{...corpus[n],retrievedAtUtc:old.snapshots.find(r=>r.name===n).retrievedAtUtc}]));assertFresh(d.index,d.bodies,comparison);verifyCapturedBinding(c.root,identity(d.index));return true}
export async function freshness(c){assertBaseline(c);localGate(c.root);reviewGate(c.root,0);const corpus=corpusAt(c.root).corpus,oldIndex=c.a.objects['OFFICIAL_DOCS/INDEX.json'],dir=path.join(c.root,'artifacts/g6p-b2/docs');if(fs.existsSync(dir))throw new Error('B2_DOCUMENT_CAPTURE_NO_REENTRY');fs.mkdirSync(dir,{recursive:true});const reuse=oldIndex.snapshots.every(r=>Date.now()-Date.parse(r.retrievedAtUtc)<=7200000&&Date.now()>=Date.parse(r.retrievedAtUtc)),index={schemaVersion:'1.0.0',acceptedR2SourceIndexIdentity:'9dcd93f996b92d4c8afd44815a5786ace16ca8c667700ea342eeae3a8a3ffbcf',mode:reuse?'LOCAL_BYTE_EXACT_FRESH_R2_REUSE':'EXACT_FIVE_CONDITIONAL_REFRESH',unauthenticatedDocumentationGets:0,authenticatedNansenProviderRequests:0,accountRequests:0,browserRuntimeRequests:0,snapshots:[]},bodies={};for(const name of NAMES){const old=corpus[name],prior=oldIndex.snapshots.find(r=>r.name===name),url=old.url;if(!allowed(url))throw new Error('B2_FIXED_DOCUMENT_URL');const r=reuse?{status:200,bytes:Buffer.from(old.body),retrievedAtUtc:prior.retrievedAtUtc,transport:'LOCAL_EXACT_R2_REUSE'}:await get(url);if(!reuse)index.unauthenticatedDocumentationGets++;const row={name,url,retrievedAtUtc:r.retrievedAtUtc,httpStatus:r.status,bytes:r.bytes.length,sha256:sha(r.bytes),r2Sha256:old.sha256,unchangedFromR2:sha(r.bytes)===old.sha256,reusedR2:reuse,filename:name+'.md',transport:r.transport};index.snapshots.push(row);bodies[name]=r.bytes;if(!reuse)fs.writeFileSync(path.join(dir,row.filename),r.bytes,{flag:'wx'});fs.writeFileSync(path.join(dir,'INDEX.json'),JSON.stringify(index,null,2)+'\n');process.stdout.write('B2_DOC '+name+' status '+r.status+' bytes '+r.bytes.length+' sha256 '+row.sha256+'\n');if(r.status!==200||row.sha256!==old.sha256)throw new Error('B2_DOC_UNAVAILABLE_OR_CHANGE_REQUIRES_REVIEW')}
 // Reused R3 dates are checked against accepted R3 rows rather than older R2 retrieval times.
 validateCapturedIndex(index);const comparison=Object.fromEntries(NAMES.map(n=>[n,{...corpus[n],retrievedAtUtc:oldIndex.snapshots.find(r=>r.name===n).retrievedAtUtc}]));assertFresh(index,bodies,comparison);const d={index,bodies,comparison};proofs.set(d,identity(index));return d
}
