export function lessons(){const rows=[
 ['COUNT_SHAPED_PLANNING','Count-shaped subjects/pages inflate success without utility','Equivalent or utilityless candidate','Request count is progress','Meaningful named question/consumer/coverage before request','Canonical logical-ID uniqueness and bounded utility admission','STABLE_POLICY'],
 ['STALE_SEALS','Metadata changes leave old sealed identity attached','Canonical seal mismatch','Old hash still authorizes changed bytes','Reseal all policy/plan/audit/index dependencies and compare current cut','Seal payload identity and current digest gates','STABLE_POLICY'],
 ['OFFLINE_ACCOUNT_ORDER','Credential/account access precedes offline proof','Account START before admission','Account observation can repair local gates','Offline checks and reviews before docs and runtime credential; consumed account never repeats','No offline credential reads; account requests0','STABLE_POLICY'],
 ['EXACT_CAMPAIGN','Generic NQ5 alias passes unrelated campaign','Campaign constant mismatch','Generic alias denotes the current campaign','Exact full campaign binding; preserve old alias as historical crosswalk only','Current public schema rejects generic alias','STABLE_POLICY'],
 ['PROVIDER_ID','Transport discards provider request identity','Durable header absent','HTTP2xx alone is countable','Capture finite safe X-Request-Id before counting','Provider-ID/header/raw/terminal equality','STABLE_POLICY'],
 ['PURPOSE_VALUE_AUDIT','Qualification-shaped records omit purpose and value','Missing question/lens/consumer record','Count alone proves competition utility','Complete sealed per-request purpose/lineage/coverage/value audit before count','Current17 audit schema and prospective audit gate','STABLE_POLICY'],
 ['ACCOUNT_VS_CAMPAIGN','Account-wide balance drift labeled campaign cost','Balance delta exceeds observed billing','All balance movement belongs to this campaign','Separate known billed credits and unattributed total/interval change; assign no cause','Reconciliation billing versus safe header anchor arithmetic','STABLE_POLICY'],
 ['RATE_SCOPE','A new header overwrites unrelated rate windows','Independent window reset mismatch','One limit represents all rate scopes','Independent expiring official/provider rate windows and capacity reservations','Accepted RateGate adversarial regression','STABLE_POLICY'],
 ['OPTIONAL_NULL','Optional enrichment null discards otherwise safe facts','Nullable field schema falsifier','Null means zero or blanket endpoint admission','Exact Lead-owned null omission only; core and unknown fields remain strict','Narrow compatibility schema and omitted enrichment','STABLE_POLICY'],
 ['UNZONED_TIME','Timezone-less context relabeled exact UTC','Missing Z/offset or truth-time conflict','Invented UTC proves timing/completeness','Contextual server-filtered classification; only separately accepted hash time joins','Temporal request bounds and accepted truth conflict checks','STABLE_POLICY'],
 ['SUBJECT_PARTICIPATION','Incidental transfer or label supplies subject lineage','Neither from nor to equals requested subject','Any row in an address response is relevant','Case-insensitive sent/from or received/to participation; incidental exclusion','Signed row bucket/address tests','STABLE_POLICY'],
 ['SIGNED_FLOW','Negative encoding treated as negative onchain quantity or discarded','Signed amount with valid bucket/role','Sign alone proves direction or every negative fails response','Explicit observed signed-flow profile; remove one minus only, all other lexeme bytes unchanged','Exact high precision/exponent and wrong-bucket tests','STABLE_POLICY'],
 ['DUPLICATE_INFLATION','Self/duplicate transfers inflate normalized count','Repeated canonical magnitude identity','Every raw transfer is unique','Deterministic transaction/from/to/token/exact magnitude deduplication','Self and ordinary duplicate controls','STABLE_POLICY'],
 ['PER_CALL_ACCEPTANCE','One failure forces all calls to zero or forces all pass','Independent raw/terminal identity mismatch','HTTP batch is one qualification unit','Independent per-call support; immutable mismatches stay held','One accepted prior call versus three permanent holds; independent canary outcomes','STABLE_POLICY'],
 ['FRONTIER_COMPLETENESS','Omitted Main Trigger/counterparty makes false exhaustion','Unused safe seed or durable counterparty found','Empty chosen plan proves no routes','Enumerate all seeds/counterparties/hash joins/repeats/exact non-last pages with reasons','Complete candidate matrix and no fixed pagination enumeration','STABLE_POLICY'],
 ['CANDIDATE_SPECIFIC_LINEAGE','Cloned template proof names unrelated Early Trigger evidence','Main Trigger names EXACT_EARLY_NET','Inherited proof/consumer is harmless metadata','Build each candidate explicitly; correct seed or durable-counterparty proof with named consumers','Adversarial Main Trigger and counterparty proof guards','STABLE_POLICY'],
 ['DELTA_FIRST_MAINTENANCE','Historical status is edited as current authority','New contract conflicts with active gate','Rewrite foundation history to appear current','Add exact source/manifest delta and explicit current status; keep immutable foundation','66 pinned source hashes and prior archive identities','STABLE_POLICY'],
 ['BUGBOT_TRACEABILITY','Review receipt refers to stale cut or fabricated scope','Digest/tree or access-counter mismatch','Any historical review covers current bytes','Dedicated bounded pre/post checkpoints bound to included commit/tree or exact digest','Review ancestry/digest/lens and actual access checks','STABLE_POLICY'],
 ['BOUNDED_TRUTHFUL_PATH','Compatibility investigation continues after sufficient bounded rule','Accepted signed/null/time path already exists','More endpoint exploration is mandatory','Stop compatibility work once exact bounded path exists; live scope only two IDs','Fixed-five freshness and exact canary/no-third guards','CURRENT_OPERATIONAL_STATE']
 ];return {schemaVersion:'1.0.0',scope:'B1_THROUGH_B2_ENGINEERING_KT_NOT_PUBLIC_GAME',rows:rows.map(([id,mechanism,falsifier,rejected,rule,test,classification])=>({findingId:id,falseSuccessMechanism:mechanism,firstFalsifier:falsifier,rejectedInterpretation:rejected,acceptedRule:rule,directTestOrInvariant:test,sourceKtCarryForwardText:rule,classification})),sourceConsolidationPending:true,gameplayIntegration:false}
}
