import fs from 'node:fs'
import path from 'node:path'
import { identity, sha } from '../nq5/schema.mjs'
import { logicalRequest } from '../nq5/planner.mjs'
import { TRUTH } from '../nq5-b1-r3/compatibility.mjs'
import { seal, CONTRACT_SHA, ARCHIVE_SHA, ACCEPTED_ID, HELD, IDS, BASE, TREE } from './authority.mjs'
export const MAIN='0xb2698c2d99ad2c302a95a8db26b08d17a77cedd4',COUNTERPARTY='0x16710ce8c36756e59c38f76d3096bc666366d3ab',DURABLE_TX='0xdeb4569be5de5a1a81796e8e544cb99203e184f45e4349847baa42894ff6ae0f'
export function receipt(a,state,result){
 const o=a.b2PriorObjects,p=o['EVIDENCE/R3_PER_CALL_SEMANTIC_REVALIDATION.json'].calls.find(r=>r.logicalId===ACCEPTED_ID),r=result.perCall.find(r=>r.logicalId===ACCEPTED_ID),index=o['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'],audit=o['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'],profile=o['CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json']
 if(!r?.leadAcceptanceCandidate||identity(result.index)!==identity(index)||identity(result.audit)!==identity(audit)||identity(result.perCall)!==identity(o['EVIDENCE/R3_PER_CALL_SEMANTIC_REVALIDATION.json'].calls)||index.length!==1||p.oldNormalizedIdentity!=='a35ce36f24e043a60ffaf34a1c61bd8203877a87ad76886840e0aed77bdbe30c'||r.terminal.identity!==p.terminal.identity||state.identity!==o['DELIVERY_MANIFEST.json'].immutablePrivateStateIdentity)throw new Error('B2_LEAD_ACCEPTANCE_EXACT_BINDINGS')
 return seal({schemaVersion:'1.0.0',disposition:'ONE_QUALIFICATION_CALL_LEAD_ACCEPTED',executionContractSha256:CONTRACT_SHA,reviewedR3R2ArchiveSha256:ARCHIVE_SHA,reviewedCandidate:{commit:BASE,tree:TREE},reviewedCandidateDirectParent:'9e3663f779299056a55cb177831bccacf48ac610',acceptedR3R1Ancestor:'f2f248d97a263e2d16da8da9f0b0bcdc203a544d',reviewedImplementationDigest:'4016f3358092f1f193281bceae959786d779f3182c23f41f46efe974dcdee6c9',campaignId:a.context.bound.envelope.campaignId,logicalId:ACCEPTED_ID,providerRequestId:'b971df1271bb831a5fee0e3ae757b649',rawPrimarySha256:p.primarySha256,rawMirrorSha256:p.mirrorSha256,normalizedSha256:p.oldNormalizedIdentity,immutableTerminalIdentity:p.terminal.identity,publicCallId:'NQ5-000001',qualificationSequence:1,method:'POST',path:'/api/v1/profiler/address/transactions',subject:r.requestedSubject,signedFlowCompatibilityProfileIdentity:profile.hash,observedNullTimeProfileIdentity:a.context.profile.hash,correctedPublicIndexIdentity:identity(index),correctedRequestAuditIdentity:identity(audit),frontierCandidateMatrixIdentity:identity(o['EVIDENCE/FRONTIER_CANDIDATE_REJECTION_MATRIX.json']),accountingEvidenceFileSha256:sha(a.b2PriorBytes['EVIDENCE/ACCOUNT_WIDE_BALANCE_RECONCILIATION.json']),immutableLedgerSha256:state.privateHashes['qualification.jsonl'],immutableLedgerBytes:32547,supplierCountedTerminals:4,leadAcceptedSuccesses:1,permanentlyHeldLogicalIds:HELD,heldTerminalMutationAllowed:false,reissueAllowed:false,evidenceRole:'BOUNDED_CONTEXTUAL_ACTIVITY_AND_PROVENANCE_ONLY',exactProof:false,negativeEvidence:false,completeness:false,causation:false,gameplayIntegration:false})
}
export function requests(a,result,lead){const source=result.privateProjections.find(p=>p.logicalId===ACCEPTED_ID&&p.leadAcceptanceCandidate),transfer=source?.admission.normalizedRecords.find(r=>r.transaction_hash.toLowerCase()===DURABLE_TX&&r.from_address.toLowerCase()===COUNTERPARTY&&r.to_address.toLowerCase()===lead.subject.toLowerCase()&&r.amount==='0.0001');if(!transfer)throw new Error('B2_CANDIDATE_SPECIFIC_SOURCE_PROOF');return requestsFromProof(a,lead,identity([transfer.transaction_hash.toLowerCase(),transfer.from_address.toLowerCase(),transfer.to_address.toLowerCase(),transfer.token_address.toLowerCase(),transfer.amount]))}
export function requestsFromProof(a,lead,transferIdentity){
 const graph=JSON.parse(fs.readFileSync(path.join(a.context.root,TRUTH))),entity=graph.entities.find(e=>e.id==='main_trigger'),ev=graph.evidence.find(e=>e.id==='EXACT_MAIN_RECEIVER');if(entity?.address!==MAIN||entity.role!=='Main Trigger'||ev?.transactionHash!=='0x298bde3f9e53f7a5d870f7f5d56ee2f5e41fa25e6eb5e74611ac97025405db55'||!/^[a-f0-9]{64}$/.test(transferIdentity))throw new Error('B2_CANDIDATE_SPECIFIC_SOURCE_PROOF')
 const specifications=[{address:MAIN,lens:'ACTIVITY',purpose:'ANCHOR_ACTIVITY_PAGE',questionId:'QUESTION.T1.B2.ACTIVITY.INCIDENT.'+MAIN,businessQuestion:'Which subject-involved contextual activity facts for the accepted Main Trigger add route-candidate coverage inside the incident window?',lineage:['ACCEPTED_EULER_TRUTH.'+a.context.truth.sha256,'ACCEPTED_ENTITY.main_trigger','ACCEPTED_ROLE.Main Trigger','ACCEPTED_TRANSACTION.'+ev.transactionHash,'SEED_PROVENANCE.EXACT_MAIN_RECEIVER'],consumers:['CASEBOARD.MAIN_TRIGGER_CONTEXT','TEST.T1.B2.MAIN_TRIGGER_ACTIVITY','PROVENANCE.T1.B2.MAIN_TRIGGER'],frontierProof:{kind:'ACCEPTED_SEED',entityId:entity.id,role:entity.role,evidenceRecordId:ev.id,transactionHash:ev.transactionHash,acceptedTruthSha256:a.context.truth.sha256,seedProvenanceOnly:true},candidateRole:'MAIN_TRIGGER_CONTEXT',novelty:'Unused accepted Main Trigger seed activity; seed evidence is not a claim that the new call is exact evidence.'},{address:COUNTERPARTY,lens:'RELATIONSHIPS',purpose:'DEAD_END_DISCOVERY',questionId:'QUESTION.T1.B2.RELATIONSHIPS.DEADEND.'+COUNTERPARTY,businessQuestion:'Does the sender of the accepted Early Trigger contextual 0.0001 ETH transfer show route-relevant incident-window activity, or is it a bounded dead end?',lineage:['LEAD_ACCEPTED_REQUEST.'+ACCEPTED_ID,'PUBLIC_CALL.NQ5-000001','PROVIDER_REQUEST.'+lead.providerRequestId,'DURABLE_TRANSACTION.'+DURABLE_TX,'RELATION.OPPOSITE_SIDE_SUBJECT_COUNTERPARTY'],consumers:['DEADEND.T1.B2.EARLY_DUST_COUNTERPARTY','TEST.T1.B2.COUNTERPARTY_DEAD_END','PROVENANCE.T1.B2.COUNTERPARTY_LINEAGE'],frontierProof:{kind:'DURABLE_SUBJECT_COUNTERPARTY',logicalId:ACCEPTED_ID,publicCallId:lead.publicCallId,providerRequestId:lead.providerRequestId,transactionHash:DURABLE_TX,transferIdentity,relation:'REQUEST_SUBJECT_TO_OPPOSITE_FROM',sourceLeadAcceptanceReceiptIdentity:lead.hash},candidateRole:'EARLY_DUST_COUNTERPARTY_DEAD_END',novelty:'Unissued opposite-side subject counterparty from the one Lead-accepted call; bounded dead-end test, never negative evidence.'}]
 return specifications.map((s,i)=>{const coverageKey={subject_id:s.address,time_window_id:'2023-03-13T08:45:00Z/2023-03-13T12:15:00Z',question_lens:s.lens,page_or_partition_id:'PAGE.1'},cell='CELL.'+identity(coverageKey),q={family:'profiler/address/transactions',path:'/api/v1/profiler/address/transactions',method:'POST',body:{address:s.address,chain:'ethereum',date:{from:'2023-03-13T08:45:00Z',to:'2023-03-13T12:15:00Z'},pagination:{page:1,per_page:100}},lens:s.lens,purpose:s.purpose,questionId:s.questionId,businessQuestion:s.businessQuestion,lineage:s.lineage,consumers:[...s.consumers,cell],frontierProof:s.frontierProof,candidateRole:s.candidateRole,novelty:s.novelty,coverageKey,coverageCells:[cell],partition:{page:1,exactDurableNextPage:false},sequence:i+1,contractHash:a.context.plans.plan.requests[0].contractHash,publicProjectionPolicy:structuredClone(a.context.plans.plan.requests[0].publicProjectionPolicy),expectedCredits:1,worstCaseCredits:3,stopRule:'Stop first schema, privacy, storage, rate, credit, reserve, subject, raw, provider-ID or audit breaker; drain in-flight requests independently. No third, replacement, page2, exact-proof, negative-evidence or completeness claim.'};q.logicalId=logicalRequest(q);if(q.logicalId!==IDS[i])throw new Error('B2_CANONICAL_LOGICAL_ID_MISMATCH');return q})
}
export function validateSpecific(q){
 if(q.length!==2||q.some((r,i)=>logicalRequest(r)!==IDS[i]||r.sequence!==i+1||r.body.pagination.page!==1||r.lineage.some(x=>HELD.some(h=>x.includes(h)))))throw new Error('B2_EXACT_TWO_REQUEST_PLAN')
 const[a,b]=q;if(a.body.address!==MAIN||a.frontierProof.kind!=='ACCEPTED_SEED'||a.frontierProof.entityId!=='main_trigger'||a.frontierProof.evidenceRecordId!=='EXACT_MAIN_RECEIVER'||JSON.stringify(a).includes('EXACT_EARLY_NET')||a.lens!=='ACTIVITY'||a.purpose!=='ANCHOR_ACTIVITY_PAGE'||!a.consumers.includes('CASEBOARD.MAIN_TRIGGER_CONTEXT'))throw new Error('B2_MAIN_TRIGGER_FALSE_LINEAGE')
 if(b.body.address!==COUNTERPARTY||b.frontierProof.kind!=='DURABLE_SUBJECT_COUNTERPARTY'||b.frontierProof.logicalId!==ACCEPTED_ID||b.frontierProof.evidenceRecordId!==undefined||b.frontierProof.entityId!==undefined||b.lens!=='RELATIONSHIPS'||b.purpose!=='DEAD_END_DISCOVERY'||!b.consumers.includes('DEADEND.T1.B2.EARLY_DUST_COUNTERPARTY'))throw new Error('B2_COUNTERPARTY_FALSE_LINEAGE')
 return true
}
export function freeze(a,state,result,lead){return freezeFromRequests(a,state,result,lead,requests(a,result,lead))}
export function freezeFromRequests(a,state,result,lead,q){validateSpecific(q);if(q.some(r=>state.rows.some(s=>s.kind==='START'&&s.logicalId===r.logicalId)))throw new Error('B2_ISSUED_EQUIVALENT');const bind={campaignId:lead.campaignId,executionContractSha256:CONTRACT_SHA,reviewedR3R2ArchiveSha256:ARCHIVE_SHA,leadAcceptanceReceiptIdentity:lead.hash,signedFlowCompatibilityProfileIdentity:result.profile.hash,observedNullTimeProfileIdentity:a.context.profile.hash,correctedPublicIndexIdentity:identity(result.index),requestAuditIdentity:identity(result.audit),candidateMatrixIdentity:lead.frontierCandidateMatrixIdentity,balanceAnchor:626632,protectedReserve:250};const policy=seal({schemaVersion:'1.0.0',...bind,exactLogicalIds:IDS,maximumRequests:2,maximumAttempts:6,maximumCredits:6,maximumConcurrency:2,noThirdRequest:true,noReissue:true,noReplacement:true,noHeldLineage:true,AUTHORIZED_TO_ISSUE:false}),plan=seal({schemaVersion:'1.0.0',...bind,requests:q,frontierPolicyIdentity:policy.hash,expectedCredits:2,worstCaseCredits:6,maximumAttempts:6,maximumConcurrency:2,frozen:true,AUTHORIZED_TO_ISSUE:false}),reserve=seal({schemaVersion:'1.0.0',...bind,planIdentity:plan.hash,frontierPolicyIdentity:policy.hash,expectedCredits:2,worstCaseCredits:6,remainingAfterWorstCase:626626,reservePass:true,AUTHORIZED_TO_ISSUE:false});return {plan,reserve,policy}}
