#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import { fileURLToPath } from 'node:url'
import { execFileSync, spawn } from 'node:child_process'
import { identity, sha } from '../nq5/schema.mjs'
import { LOCAL_SUITES } from '../nq5-b1/live.mjs'
import { sanitizeLog, pathScan } from '../nq5-b1-r2/privacy.mjs'
import { accepted, cut, digest, BASE, CONTRACT_SHA, MANIFEST, ARCHIVE_SHA, OUTPUT, IDS } from './authority.mjs'
import { baseline } from './context.mjs'
import { localGate, reviewGate } from './gates.mjs'
import { freshness, readCaptured } from './docs.mjs'
import { authorize, Store, Executor, liveTransport } from './executor.mjs'
import { postContext, reconcile, nextFrontier, deliveryStatus } from './reconciliation.mjs'
import { historicalBlocked } from './blocked.mjs'
import { audit } from './audit.mjs'
import { admit } from './admission.mjs'
import { lessons } from './lessons.mjs'
import { readMirrored } from '../nq5-b1/store.mjs'
const environment=Object.fromEntries(['PATH','HOME','USER','LOGNAME','SHELL','TMPDIR','LANG','LC_ALL','DISPLAY','XDG_RUNTIME_DIR','PLAYWRIGHT_BROWSERS_PATH','npm_config_cache'].flatMap(k=>process.env[k]===undefined?[]:[[k,process.env[k]]]))
const root=path.resolve(fileURLToPath(new URL('../..',import.meta.url))),parent=path.dirname(root),local=path.join(root,'artifacts/g6p-b2/local'),childEnv={...environment,PYTHONDONTWRITEBYTECODE:'1',NODE_OPTIONS:'--require '+path.join(root,'scripts/nq5-r2/hold.cjs'),npm_config_update_notifier:'false'}
const serialize=x=>Buffer.isBuffer(x)?x:Buffer.from(typeof x==='string'?x:JSON.stringify(x,null,2)+'\n'),write=(dir,n,x)=>{const f=path.join(dir,n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,serialize(x))},read=n=>JSON.parse(fs.readFileSync(path.join(local,n)))
const run=(cmd,args,cwd=root)=>new Promise((resolve,reject)=>{const p=spawn(cmd,args,{cwd,env:childEnv,stdio:['ignore','pipe','pipe']});let out='';for(const stream of[p.stdout,p.stderr])stream.on('data',b=>{out+=b;if(out.length>64000000)p.kill()});p.on('error',()=>reject(new Error('B2_LOCAL_TOOL_UNAVAILABLE')));p.on('close',code=>{if(code===0)return resolve(out);const e=new Error('B2_LOCAL_TOOL_FAILED');e.safeOutput=out;reject(e)})})
const snapshot=()=>({candidate:cut(root),implementationSha256:digest(root)}),safeCode=e=>/^(?:B2|B1|R3|R31)_[A-Z0-9_]{1,120}$/.test(e.message)?e.message:'B2_FAIL_CLOSED_NO_UNSAFE_ERROR_EXPORT'
function identityMatrix(c,state=c.state){return {schemaVersion:'1.0.0',executionContractSha256:CONTRACT_SHA,leadAcceptanceReceiptIdentity:c.lead.hash,planIdentity:c.plans.plan.hash,noThirdRequest:true,canonicalLogicalIdsIndependentlyRecomputed:true,requests:c.plans.plan.requests.map(q=>{const t=state.terminals.get(q.logicalId),rs=[...state.responses.values()].filter(r=>r.logicalId===q.logicalId);return {logicalId:q.logicalId,sequence:q.sequence,body:q.body,method:q.method,path:q.path,questionId:q.questionId,lens:q.lens,purpose:q.purpose,coverageKey:q.coverageKey,coverageCells:q.coverageCells,lineage:q.lineage,consumers:q.consumers,frontierProof:q.frontierProof,candidateRole:q.candidateRole,sealedRequestIdentity:identity(q),issued:state.starts.has(q.logicalId+'.1'),terminalIdentity:t?.hash??null,terminalDisposition:t?.disposition??null,localSupportCandidate:t?.disposition==='SUCCESS_COUNTED',leadAccepted:false,attempts:rs.map(r=>{const raw=readMirrored(c.state.roots,'raw-b1/'+r.rawName),a=r.httpStatus===200?admit(c,q,raw,r,t?.publicRecord?.qualification_sequence??5):null;return {attempt:r.attempt,providerRequestId:r.providerRequestId,httpStatus:r.httpStatus,rawSha256:r.rawSha256,rawBytes:r.rawBytes,quotedCredits:r.quotedCredits,actualCredits:r.actualCredits,remainingCredits:r.remainingCredits,completedAtUtc:r.completedAtUtc,latencyMs:r.latencyMs,stages:a?.stages??{},signedStats:a?.semantic?.stats??null,signBucketDirectionMatrix:a?.semantic?.matrix??[],normalizedIdentity:a?.normalizedSha256??null,resultCount:a?.resultCount??0,primaryMirrorEquality:true}})}})}}
function baseEntries(c){return {
 'RECEIPTS/R3_R2_LEAD_ACCEPTANCE_RECEIPT.json':c.lead,
 'CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json':c.a.b2PriorBytes['CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json'],
 'CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json':c.a.b2PriorBytes['CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json'],
 'PLANS/T1_BATCH2_EXECUTION_PLAN.json':c.plans.plan,'PLANS/T1_BATCH2_RESERVE_PLAN.json':c.plans.reserve,'PLANS/T1_BATCH2_FRONTIER_POLICY.json':c.plans.policy,
 'SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json':fs.readFileSync(path.join(root,'schemas/NANSEN_API_REQUEST_AUDIT.schema.json')),'SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json':fs.readFileSync(path.join(root,'schemas/NQ5_PUBLIC_CALL_INDEX.schema.json')),
 'EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json':lessons()
}}
function preEntries(c,reason='PRELIVE_GATES_PENDING'){const entries=baseEntries(c),index=c.priorResult.index,indexBytes=serialize(index),plannedAudit=audit(c,c.state,r=>readMirrored(c.state.roots,'raw-b1/'+r.rawName));return {...entries,
 'EXECUTION/T1_B2_EXECUTION_ENVELOPE.json':{schemaVersion:'1.0.0',AUTHORIZED_TO_ISSUE:false,status:'NOT_LIVE_AUTHORITY',reason,planIdentity:c.plans.plan.hash,leadAcceptanceReceiptIdentity:c.lead.hash,executionContractSha256:CONTRACT_SHA},
 'REPORTS/T1_B2_EXECUTION_REPORT.json':{schemaVersion:'1.0.0',status:'NOT_ISSUED',reason,newAttempts:0,newCredits:0,credentialAccess:false,privateMutation:false,AUTHORIZED_TO_ISSUE:false},
 'REPORTS/T1_B2_RECONCILIATION_REPORT.json':{schemaVersion:'1.0.0',httpAttempts:6,provider2xx:6,supplierCountedTerminals:4,leadAcceptedBeforeB2:1,leadAcceptedAfterB2:1,permanentlyHeldCalls:3,newLocalSupportCandidates:0,knownCampaignCredits:6,unresolvedReservations:0,newAttempts:0,newKnownCredits:0,ledgerSha256:c.lead.immutableLedgerSha256,ledgerBytes:32547,latestSafeResponseBalance:626632,totalAccountWideDecrease:3395,totalCampaignKnownCredits:6,totalAccountWideUnattributedChange:3389,r3AndB2IntervalDecrease:846,r3AndB2IntervalKnownCredits:4,r3AndB2IntervalUnattributedChange:842,causeAssigned:false,accountRequests:0,publicIndexIdentity:identity(index),requestAuditIdentity:identity(plannedAudit)},
 'REPORTS/T1_B2_UTILITY_AND_FRONTIER_VIABILITY_REPORT.json':{schemaVersion:'1.0.0',status:'NOT_TESTED_NO_NEW_CALLS',floor1024RouteUnproven:true,BATCH3_AUTHORIZED_TO_ISSUE:false,nextRequestsIssued:0},
 'REPORTS/T1_CAMPAIGN_STATE_REDACTED.json':{schemaVersion:'1.0.0',campaignId:c.lead.campaignId,httpAttempts:6,provider2xx:6,supplierCountedTerminals:4,leadAcceptedSuccesses:1,newLocalSupportCandidates:0,permanentlyHeldCalls:3,knownCampaignCredits:6,unresolvedReservations:0,ledgerSha256:c.lead.immutableLedgerSha256,ledgerBytes:32547,privateMutation:false,newProviderRequests:0},
 'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':indexBytes,'PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256':sha(indexBytes)+'  NQ5_PUBLIC_CALL_INDEX.json\n','EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':plannedAudit,'EVIDENCE/B2_LIVE_REQUEST_IDENTITY_MATRIX.json':identityMatrix(c),
 'EVIDENCE/B2_ATTEMPT_CREDIT_COUNT_AND_PROVIDER_ID_RECONCILIATION.json':{schemaVersion:'1.0.0',status:'NOT_ISSUED',reason,existingSupplierCountedTerminals:4,existingLeadAcceptedSuccesses:1,newAttempts:0,newProvider2xx:0,newCredits:0,newLocalSupportCandidates:0},
 'EVIDENCE/B2_PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json':{schemaVersion:'1.0.0',status:'READONLY_BASELINE_PASS',privateStateIdentity:c.state.identity,ledgerSha256:c.lead.immutableLedgerSha256,ledgerBytes:32547,originalSixAttemptsResponsesAndTerminalsUnchanged:true,oldRawMirrorsEqual:true,publicIndexIdentity:identity(index),priorPublicIndexFileSha256:sha(indexBytes),leadAcceptedPublicCallId:'NQ5-000001',privateMutation:false},
 'EVIDENCE/BATCH3_FRONTIER_CANDIDATE_REJECTION_MATRIX.json':{schemaVersion:'1.0.0',status:'NOT_DERIVED_B2_NOT_ISSUED',sourcePriorMatrixIdentity:c.lead.frontierCandidateMatrixIdentity,rows:[],noExhaustionClaim:true,AUTHORIZED_TO_ISSUE:false}
}}
function postEntries(c,e,execution){const r=reconcile(c,e),f=nextFrontier(c,r),entries=baseEntries(c),indexBytes=serialize(r.index);Object.assign(entries,{
 'EXECUTION/T1_B2_EXECUTION_ENVELOPE.json':e,'REPORTS/T1_B2_EXECUTION_REPORT.json':execution,'REPORTS/T1_B2_RECONCILIATION_REPORT.json':r.report,'REPORTS/T1_B2_UTILITY_AND_FRONTIER_VIABILITY_REPORT.json':f.viability,
 'REPORTS/T1_CAMPAIGN_STATE_REDACTED.json':{schemaVersion:'1.0.0',campaignId:c.lead.campaignId,httpAttempts:r.current.starts.size,provider2xx:[...r.current.responses.values()].filter(x=>x.httpStatus>=200&&x.httpStatus<300).length,supplierCountedTerminals:r.report.supplierCountedTerminals,leadAcceptedSuccesses:1,newLocalSupportCandidates:r.projections.length,permanentlyHeldCalls:3,knownCampaignCredits:r.report.knownCampaignCredits,unresolvedReservations:r.report.unresolvedReservations,unresolvedTerminals:r.report.unresolvedTerminals,ledgerSha256:r.report.ledgerSha256,ledgerBytes:r.report.ledgerBytes,immutablePrefixUnchanged:true,gameplayIntegration:false,qualificationFloorClaimed:false},
 'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':indexBytes,'PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256':sha(indexBytes)+'  NQ5_PUBLIC_CALL_INDEX.json\n','EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':r.audit,'EVIDENCE/B2_LIVE_REQUEST_IDENTITY_MATRIX.json':identityMatrix(c,r.current),
 'EVIDENCE/B2_ATTEMPT_CREDIT_COUNT_AND_PROVIDER_ID_RECONCILIATION.json':{...r.report,exactProviderResponses:[...r.current.responses.values()].filter(x=>IDS.includes(x.logicalId)).map(x=>({logicalId:x.logicalId,attempt:x.attempt,providerRequestId:x.providerRequestId,httpStatus:x.httpStatus,actualCredits:x.actualCredits,quotedCredits:x.quotedCredits,rawSha256:x.rawSha256,completedAtUtc:x.completedAtUtc}))},
 'EVIDENCE/B2_PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json':{...r.report,oldFoundationPrivateStateIdentity:c.state.identity,publicIndexFileSha256:sha(indexBytes),permanentlyHeldCallsExcludedFromPublicIndex:true,leadAcceptedCallIdentityUnchanged:true,privatePathsIncluded:false,rawBodiesIncluded:false},
 'EVIDENCE/BATCH3_FRONTIER_CANDIDATE_REJECTION_MATRIX.json':f.matrix
 });if(f.plan){entries['PLANS/T1_BATCH3_CANDIDATE_PLAN.json']=f.plan;entries['PLANS/T1_BATCH3_RESERVE_PLAN.json']=f.reserve;entries['PLANS/T1_BATCH3_FRONTIER_POLICY.json']=f.policy}return {entries,report:r.report,status:deliveryStatus(r.report,execution)}
}
function persistEntries(entries){for(const[n,x]of Object.entries(entries))write(local,n,x)}
function derive(){const c=baseline(root),entries=preEntries(c);persistEntries(entries);process.stdout.write(JSON.stringify({status:'PRELIVE_OFFLINE_ONLY',leadAccepted:1,supplierCounted:4,held:3,planRequests:2,planHash:c.plans.plan.hash,receiptHash:c.lead.hash,providerRequests:0,credentialAccess:false,privateMutation:false,source:c.source})+'\n')}
async function verify(){accepted(root);const start=snapshot(),suites=[],assert=()=>{if(identity(start)!==identity(snapshot()))throw new Error('B2_VERIFICATION_SOURCE_CHANGED')},suite=async(name,cmd,args,cwd=root)=>{assert();process.stdout.write('LOCAL '+name+'\n');let out;try{out=await run(cmd,args,cwd)}catch(e){if(e.safeOutput?.trim())write(local,name+'.log',e.safeOutput);throw e}assert();if(!out.trim())throw new Error('B2_EMPTY_LOG');write(local,name+'.log',out);suites.push({name,status:'PASS',sha256:sha(Buffer.from(out))})};const names=['nq5-b1-executor','nq5-b1-r1-remediation','nq5-b1-r2-contracts','nq5-b1-r3-resume','nq5-b1-r3-r1-semantics','nq5-b1-r3-r2-signed-flow','nq5-b2-canary'];
 await suite('execution-adversarial','node',['node_modules/vitest/vitest.mjs','run',...names.map(n=>'tests/unit/'+n+'.test.mjs'),'--reporter=dot']);await suite('source-validator','python3',['VALIDATE_SOURCE_SET.py'],path.join(root,'docs/source/v1.7.0'));await suite('report-schema-controls','python3',['scripts/test-nq5-report-validation.py']);await suite('typecheck-lint','npm',['run','check']);await suite('acquisition-compile','npm',['run','acquisition:compile']);await suite('unit-regression','node',['node_modules/vitest/vitest.mjs','run','tests/unit',...names.flatMap(n=>['--exclude','tests/unit/'+n+'.test.mjs']),'--reporter=dot']);await suite('acquisition-regression','node',['node_modules/vitest/vitest.mjs','run','tests/acquisition','--reporter=dot']);await suite('browser-accessibility-performance','npm',['run','test:e2e','--','--reporter=line']);await suite('production-build','npm',['run','build']);await suite('browser-boundary','npm',['run','browser-boundary:verify']);await suite('records-office-boundary','npm',['run','g6p:a1:boundary:verify']);await suite('euler-public-pack','npm',['run','g6:pack:verify']);await suite('project-clock-status','npm',['run','project:status']);await suite('history-secret-boundary','node',['scripts/verify-git-secret-history.mjs']);assert();write(local,'VERIFICATION.json',{schemaVersion:'1.0.0',status:'PASS',generatedAtUtc:new Date().toISOString(),...start,suites,credentialAccess:false,actualPrivateStateAccess:false,privateMutation:false,externalRequests:0,networkHold:true,scope:'ISOLATED_LOCAL_REGRESSION_LOOPBACK_ONLY_NOT_PROVIDER_RUNTIME'});process.stdout.write('B2_ALL14_LOCAL_SUITES_PASS\n')
}
async function live(){localGate(root);reviewGate(root,0);if(fs.existsSync(path.join(local,'LIVE_PHASE.json'))||fs.existsSync(path.join(local,'LIVE_ENVELOPE.json')))throw new Error('B2_LIVE_INVOCATION_NO_REENTRY');const c=baseline(root),phase={schemaVersion:'1.0.0',status:'PRELIVE',credentialAccess:false,credentialResolutionAttempted:false,privateMutation:false,providerRequests:0,documentationGets:0};write(local,'LIVE_PHASE.json',phase);try{const docs=await freshness(c);phase.documentationGets=docs.index.unauthenticatedDocumentationGets;const e=authorize(c,{docs});write(local,'LIVE_ENVELOPE.json',e);phase.privateMutationAttempted=true;phase.privateMutation=true;write(local,'LIVE_PHASE.json',phase);const store=new Store(c,e);phase.credentialResolutionAttempted=true;phase.credentialAccess=true;const transport=liveTransport(c,store),controller=new AbortController(),cancel=()=>controller.abort();process.once('SIGINT',cancel);process.once('SIGTERM',cancel);let report;try{report=await new Executor({context:c,store,transport,signal:controller.signal}).run()}finally{process.removeListener('SIGINT',cancel);process.removeListener('SIGTERM',cancel)}phase.status=report.stopReason?'LIVE_STOPPED_FIRST_BREAKER':'LIVE_TWO_CALLS_SETTLED';phase.providerRequests=report.newAttempts;phase.executionReport=report;write(local,'LIVE_PHASE.json',phase);const p=postEntries(c,e,{schemaVersion:'1.0.0',...phase,...report,privateRawBodiesPackaged:false,accountRequests:0,noThirdRequest:true});persistEntries(p.entries);process.stdout.write(JSON.stringify({status:p.status,...report,leadAcceptedBeforeB2:1,leadAcceptedAfterB2:1,supplierCountedTerminals:p.report.supplierCountedTerminals,batch3PlanGenerated:!!p.entries['PLANS/T1_BATCH3_CANDIDATE_PLAN.json'],accountRequests:0})+'\n')}catch(error){phase.status='STOPPED_FIRST_BREAKER';phase.reason=safeCode(error);const ix=path.join(root,'artifacts/g6p-b2/docs/INDEX.json');if(fs.existsSync(ix)){try{phase.documentationGets=readCaptured(root).index.unauthenticatedDocumentationGets}catch{phase.documentationGets=null}}write(local,'LIVE_PHASE.json',phase);if(!phase.privateMutation)persistEntries(preEntries(c,phase.reason));else {const blocked=historicalBlocked(root,phase,phase.reason);persistEntries(blocked.entries)}throw error}
}
function deriveDelivery(){const phaseFile=path.join(local,'LIVE_PHASE.json'),phase=fs.existsSync(phaseFile)?read('LIVE_PHASE.json'):null;if(phase?.privateMutation){try{const c=postContext(root),e=read('LIVE_ENVELOPE.json'),p=postEntries(c,e,{schemaVersion:'1.0.0',...phase,...phase.executionReport,accountRequests:0,noThirdRequest:true});return {...p,c,phase}}catch(error){return historicalBlocked(root,phase,safeCode(error))}}const c=baseline(root);return {entries:preEntries(c,phase?.reason??'PRELIVE_NOT_EXECUTED'),status:'BLOCKED_WITH_EVIDENCE',c,phase,report:null}}
const files=d=>fs.readdirSync(d).sort().flatMap(n=>{const f=path.join(d,n),s=fs.lstatSync(f);if(s.isSymbolicLink())throw new Error('B2_PACKAGE_SYMLINK');return s.isDirectory()?files(f):[f]})
async function deliver(){const v=localGate(root),reviews=[reviewGate(root,0),reviewGate(root,1)],d=deriveDelivery(),candidate=cut(root);let capture=null,captureFailure=null;const captureIndex=path.join(root,'artifacts/g6p-b2/docs/INDEX.json');if(fs.existsSync(captureIndex)){try{capture=readCaptured(root)}catch(error){captureFailure=safeCode(error);d.status='BLOCKED_WITH_EVIDENCE'}}if(fs.existsSync(path.join(parent,OUTPUT)))throw new Error('B2_EXISTING_DELIVERY_PRESERVED');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'trace-b2-delivery-')),dir=path.join(temp,'delivery');fs.mkdirSync(dir);try{const payload={},bindings=[],put=(n,x)=>{payload[n]=serialize(x);write(dir,n,payload[n])},log=(n,x)=>{const s=sanitizeLog(x,root);if(!s.text.trim())throw new Error('B2_EMPTY_DELIVERY_LOG');put(n,s.text);bindings.push({file:n,sourceSha256:s.sourceSha256,sanitizedSha256:s.sanitizedSha256,otherPathRedactions:s.otherPathRedactions})};for(const[n,x]of Object.entries(d.entries))put(n,x)
 put('README.md','# TRACE//ESCAPE B2\n\n'+d.status+'. Exact Main Trigger activity and accepted Early Trigger counterparty dead-end canary only. Supplier counts, formal Lead acceptance1 and new local candidates are separate. The three prior held calls remain immutable and permanently excluded. No Batch3 issue, replacement, account request or other family. Contextual activity/provenance only; no exact proof, negative evidence, completeness, causation or gameplay integration. Powered by Nansen API. No floor1024, final qualification, product, art, narrative, Mission02, hosting or release claim. Stop for Lead review.\n')
 put('DELIVERY_MANIFEST.json',{schemaVersion:'1.0.0',status:d.status,candidate,implementationSha256:digest(root),executionContractSha256:CONTRACT_SHA,acceptedR3R2ArchiveSha256:ARCHIVE_SHA,sourceManifestSha256:d.c.a.sourceManifestSha256,sourceFilesVerified:66,leadAcceptedBeforeB2:1,leadAcceptedAfterB2:1,priorSupplierCountedTerminals:4,permanentlyHeldCalls:3,newLocalSupportCandidates:d.report?.newLocalSupportCandidates??0,newAttempts:d.historicalOnly?null:d.report?.newAttempts??0,newKnownCredits:d.historicalOnly?null:d.report?.newKnownCredits??0,documentationGets:d.phase?d.phase.documentationGets:0,documentationCaptureStatus:captureFailure?'REJECTED_UNSAFE_CAPTURE_OMITTED':capture?'FINITE_CAPTURE_VERIFIED':'NOT_RETRIEVED',credentialAccess:d.phase?.credentialAccess??false,privateMutation:d.phase?.privateMutation??false,accountRequests:0,BATCH3_AUTHORIZED_TO_ISSUE:false,privateBytesPackaged:false,privatePathsPackaged:false,labelsPackaged:false,assetLanePackaged:false})
 put('SOURCE_INSTALL/B2_EXECUTION_CONTRACT_INSTALLATION_REPORT.json',{schemaVersion:'1.0.0',contractSha256:CONTRACT_SHA,acceptedR3R2ArchiveSha256:ARCHIVE_SHA,acceptedBaseCommit:BASE,unchangedFoundationSourceFiles:65,additiveSourceFiles:1,all66SourceHashesVerified:true});put('SOURCE_INSTALL/ACTIVE_SOURCE_MANIFEST.sha256',fs.readFileSync(path.join(root,MANIFEST)));put('EVIDENCE/BUGBOT_B2_PRELIVE_REVIEW.json',reviews[0]);put('EVIDENCE/BUGBOT_B2_POSTLIVE_REVIEW.json',reviews[1]);put('EVIDENCE/REVIEW_FINDINGS_RESOLUTIONS.json',{schemaVersion:'1.0.0',unresolvedAcceptedP0P1:0,reviews,mainTriggerFalseInheritedEvidenceRemoved:true,counterpartyProofNeverAcceptedSeedProof:true,exactTwoRequestsOnly:true,blockedReason:d.phase?.reason??null});put('EVIDENCE/KNOWN_LIMITATIONS.md','# Known limitations\n\nOnly the exact prior Early Trigger call is formally Lead accepted. New durable successes are independent local candidates pending Lead review; supplier counts remain separate. Signed-flow and optional-null/time compatibility are narrow Lead-owned observations, not official semantics admission. Exact magnitude preserves decimal lexemes; zero and incidental rows have no utility. No invented UTC, negative evidence, completeness or cause. Unattributed balance changes remain unexplained. The two-call experiment cannot establish a route to floor1024. Batch3 is never authorized to issue. Reviewer scope is safe derived evidence only; private bytes stay in restrictive mirrored stores. Product, art, narrative, accessibility acceptance, Mission02, hosting and release are unchanged. Operational status snapshot is prelive; delivery reports are authoritative for this gate.\n')
 if(capture){put('OFFICIAL_DOCS/INDEX.json',capture.index);for(const r of capture.index.snapshots)if(!r.reusedR2)put('OFFICIAL_DOCS/'+r.filename,capture.bodies[r.name]);log('VERIFICATION/documentation-capture-validation.log',JSON.stringify({status:'PASS_FINITE_NAMES_REGULAR_FILES_HASHES',sourceIndexIdentity:identity(capture.index),capturedSnapshots:capture.index.snapshots.length,documentationGets:capture.index.unauthenticatedDocumentationGets})+'\n')}else if(captureFailure)log('VERIFICATION/documentation-capture-validation.log',JSON.stringify({status:'REJECTED_UNSAFE_CAPTURE_NO_BODY_EXPORT',reason:captureFailure})+'\n')
 for(const n of LOCAL_SUITES)log('VERIFICATION/'+n+'.log',fs.readFileSync(path.join(local,n+'.log')));log('VERIFICATION/exact-baseline-execution-reconciliation.log',JSON.stringify({leadAcceptanceReceiptIdentity:d.c.lead.hash,priorPrivateStateIdentity:d.c.state.identity,originalLedgerSha256:d.c.lead.immutableLedgerSha256,originalLedgerBytes:32547,executionStatus:d.status,reconciliation:d.report,noBatch3Issue:true},null,2)+'\n')
 const bundle=path.join(dir,'GIT/trace-escape-complete.bundle');fs.mkdirSync(path.dirname(bundle));await run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD']);const bl=await run('git',['bundle','verify',bundle]),clone=path.join(temp,'clone');await run('git',['clone','--quiet',bundle,clone]);const cg=(...a)=>execFileSync('git',a,{cwd:clone,env:childEnv,encoding:'utf8'}).trim();if(cg('rev-parse','HEAD')!==candidate.commit||cg('rev-parse','HEAD^{tree}')!==candidate.tree)throw new Error('B2_BUNDLE_CLONE_IDENTITY');const fl=await run('git',['fsck','--full','--strict'],clone);log('VERIFICATION/bundle-clone-fsck.log',bl+'\nFresh clone '+candidate.commit+' / '+candidate.tree+'; fsck exit0 '+(fl.trim()||'no diagnostics')+'\n');put('GIT/trace-escape-complete.bundle',fs.readFileSync(bundle));put('SOURCE_DIFF.patch',execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:root,env:childEnv,maxBuffer:64000000}));fs.cpSync(path.join(root,'dist'),path.join(clone,'dist'),{recursive:true});log('VERIFICATION/fresh-clone-source-build-secret.log',await run('node',[path.join(root,'scripts/scan-prohibitions.mjs'),clone]));log('VERIFICATION/fresh-clone-history-secret.log',await run('node',['scripts/verify-git-secret-history.mjs'],clone));log('VERIFICATION/redacted-delivery-secret.log',await run('node',[path.join(root,'scripts/scan-prohibitions.mjs'),dir]));put('EVIDENCE/VERIFICATION_SUMMARY.json',{...v,actualPrivateStateAccess:true,localActualPrivateStateAccess:false,privateMutation:d.phase?.privateMutation??false,credentialAccess:d.phase?.credentialAccess??false,providerRequests:d.historicalOnly?null:d.report?.newAttempts??0,documentationGets:d.phase?d.phase.documentationGets:0,accountRequests:0,browserProviderRequests:0,bundleFreshCloneIdentityVerified:true,deliveryLogBindings:bindings});const scan=pathScan(payload);if(scan.status!=='PASS')throw new Error('B2_ABSOLUTE_PATH_LEAK');put('EVIDENCE/VERIFICATION_SUMMARY.json',{...JSON.parse(payload['EVIDENCE/VERIFICATION_SUMMARY.json']),pathRedactionScan:scan})
 const allowed=new Set(['README.md','DELIVERY_MANIFEST.json','MANIFEST.sha256','GIT/trace-escape-complete.bundle','SOURCE_DIFF.patch','SOURCE_INSTALL/B2_EXECUTION_CONTRACT_INSTALLATION_REPORT.json','SOURCE_INSTALL/ACTIVE_SOURCE_MANIFEST.sha256','OFFICIAL_DOCS/INDEX.json','OFFICIAL_DOCS/transactions.md','OFFICIAL_DOCS/pricing.md','OFFICIAL_DOCS/rates.md','OFFICIAL_DOCS/coverage.md','OFFICIAL_DOCS/redistribution.md','RECEIPTS/R3_R2_LEAD_ACCEPTANCE_RECEIPT.json','CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json','CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json','EXECUTION/T1_B2_EXECUTION_ENVELOPE.json','PLANS/T1_BATCH2_EXECUTION_PLAN.json','PLANS/T1_BATCH2_RESERVE_PLAN.json','PLANS/T1_BATCH2_FRONTIER_POLICY.json','PLANS/T1_BATCH3_CANDIDATE_PLAN.json','PLANS/T1_BATCH3_RESERVE_PLAN.json','PLANS/T1_BATCH3_FRONTIER_POLICY.json','REPORTS/T1_B2_EXECUTION_REPORT.json','REPORTS/T1_B2_RECONCILIATION_REPORT.json','REPORTS/T1_B2_UTILITY_AND_FRONTIER_VIABILITY_REPORT.json','REPORTS/T1_CAMPAIGN_STATE_REDACTED.json','SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json','SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json','PUBLIC/NQ5_PUBLIC_CALL_INDEX.json','PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256','EVIDENCE/NANSEN_API_REQUEST_AUDIT.json','EVIDENCE/B2_LIVE_REQUEST_IDENTITY_MATRIX.json','EVIDENCE/B2_ATTEMPT_CREDIT_COUNT_AND_PROVIDER_ID_RECONCILIATION.json','EVIDENCE/B2_PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json','EVIDENCE/BATCH3_FRONTIER_CANDIDATE_REJECTION_MATRIX.json','EVIDENCE/BUGBOT_B2_PRELIVE_REVIEW.json','EVIDENCE/BUGBOT_B2_POSTLIVE_REVIEW.json','EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json','EVIDENCE/VERIFICATION_SUMMARY.json','EVIDENCE/REVIEW_FINDINGS_RESOLUTIONS.json','EVIDENCE/KNOWN_LIMITATIONS.md']);for(const f of files(dir)){const n=path.relative(dir,f);if(!allowed.has(n)&&!/^VERIFICATION\/[a-z-]+\.log$/.test(n))throw new Error('B2_PACKAGE_ALLOWLIST')}
 put('MANIFEST.sha256',files(dir).map(f=>sha(fs.readFileSync(f))+'  '+path.relative(dir,f)).sort().join('\n')+'\n');const final=deriveDelivery();if(identity(cut(root))!==identity(candidate)||identity(Object.entries(d.entries).map(([n,x])=>[n,sha(serialize(x))]))!==identity(Object.entries(final.entries).map(([n,x])=>[n,sha(serialize(x))])))throw new Error('B2_FINAL_EVIDENCE_CHANGED');const names=files(dir).map(f=>{fs.utimesSync(f,new Date('2000-01-01T00:00:00Z'),new Date('2000-01-01T00:00:00Z'));return path.relative(dir,f)}).sort(),z=path.join(temp,'delivery.zip'),z2=path.join(temp,'rebuilt.zip');await run('zip',['-X','-q',z,...names],dir);await run('zip',['-X','-q',z2,...names],dir);if(sha(fs.readFileSync(z))!==sha(fs.readFileSync(z2)))throw new Error('B2_ARCHIVE_REBUILD_IDENTITY');await run('unzip',['-t',z]);const extract=path.join(temp,'extracted');fs.mkdirSync(extract);await run('unzip',['-q',z,'-d',extract]);await run('sha256sum',['-c','MANIFEST.sha256'],extract);const output=path.join(parent,OUTPUT);fs.copyFileSync(z,output,fs.constants.COPYFILE_EXCL);process.stdout.write(JSON.stringify({status:d.status,archive:output,sha256:sha(fs.readFileSync(output)),leadAccepted:1,newLocalSupportCandidates:d.report?.newLocalSupportCandidates??0,newAttempts:d.historicalOnly?null:d.report?.newAttempts??0,newKnownCredits:d.historicalOnly?null:d.report?.newKnownCredits??0,documentationGets:d.phase?d.phase.documentationGets:0,credentialAccess:d.phase?.credentialAccess??false,BATCH3_AUTHORIZED_TO_ISSUE:false})+'\n')
 }finally{fs.rmSync(temp,{recursive:true,force:true})}}
async function main(){if(process.argv.length!==3)throw new Error('B2_UNSUPPORTED_MODE');if(process.argv[2]!=='--live')process.env=environment;switch(process.argv[2]){case'--derive':derive();break;case'--local':await verify();break;case'--live':await live();break;case'--post':{const d=deriveDelivery();persistEntries(d.entries);process.stdout.write(JSON.stringify({status:d.status,report:d.report,credentialAccess:false,externalRequests:0})+'\n');break}case'--deliver':await deliver();break;default:throw new Error('B2_UNSUPPORTED_MODE')}}
main().catch(e=>{process.stderr.write(safeCode(e)+'; no reissue, replacement, account request or private repair.\n');process.exitCode=1})
