import fs from 'node:fs'
import path from 'node:path'
import { identity, validateSchema } from '../nq5/schema.mjs'
import { AUTH, CONTRACT_SHA, IDS } from './authority.mjs'
import { admit } from './admission.mjs'
const keys=['json','schema','pagination','contextualTemporal','normalization','projection','publicSchema']
export function auditModel(context,state,rawFor,prospective=null){
 const records=acceptedRecords(context);let supported=0
 for(const q of context.plans.plan.requests){const starts=[...state.starts.values()].filter(s=>s.logicalId===q.logicalId),t=prospective?.logicalId===q.logicalId?prospective:state.terminals.get(q.logicalId),counted=t?.disposition==='SUCCESS_COUNTED';let latest=null
  const attempts=starts.map(s=>{const r=state.responses.get(q.logicalId+'.'+s.attempt),a=r?.httpStatus===200?admit(context,q,rawFor(r),r,t?.publicRecord?.qualification_sequence??7):null;latest=a;return {attemptNumber:s.attempt,attemptIdentity:s.hash,startSequence:s.sequence,responseSequence:r?.sequence??null,terminalSequence:t?.attempt===s.attempt?t.sequence??state.rows.length+1:null,issuedAtUtc:s.issuedAtUtc,completedAtUtc:r?.completedAtUtc??null,completedTimestampDisposition:r?'CAPTURED':'NO_RESPONSE',latencyMs:r?.latencyMs??null,httpStatus:r?.httpStatus??null,provider_request_id:r?.providerRequestId??null,providerRequestIdDisposition:r?r.providerRequestId?'CAPTURED':'MISSING_FUTURE_REQUEST_ID':'NO_RESPONSE',safeHeaders:r?.headers??{},quotedCredits:r?.quotedCredits??null,actualCredits:r?.actualCredits??null,remainingCredits:r?.remainingCredits??null,rawBytes:r?.rawBytes??null,primarySha256:r?.rawSha256??null,mirrorSha256:r?.rawSha256??null,bytesEqual:!!r,responseSchemaIdentity:context.a.context.profile.publishedResponseSchemaIdentity,validation:null}})
  if(counted){if(!latest?.safelyAdmissible||!latest.resultCount||latest.normalizedSha256!==t.normalizedSha256||latest.resultCount!==t.resultCount||identity(latest.publicRecord)!==identity(t.publicRecord))throw new Error('B3_AUDIT_DURABLE_ACCEPTANCE');supported++}
  records.push({authorizationId:AUTH,executionContractSha256:CONTRACT_SHA,campaignId:context.lead.campaignId,trancheId:'T1',batchId:'B3',planSequence:q.sequence,logicalId:q.logicalId,family:q.family,path:q.path,method:q.method,requestBodySha256:identity(q.body),investigativeQuestionId:q.questionId,questionLens:q.lens,purposeCode:q.purpose,businessQuestion:q.businessQuestion,selectionLineage:q.lineage,coverageCells:q.coverageCells,coverageKey:q.coverageKey,consumerIds:q.consumers,frontierProof:q.frontierProof,candidateRole:q.candidateRole,planIdentity:context.plans.plan.hash,leadAcceptanceReceiptIdentity:context.lead.hash,expectedCredits:1,worstCaseCredits:3,issued:starts.length>0,issueDisposition:starts.length?'ISSUED_B3':state.starts.size>8?'NOT_ISSUED_BREAKER':'NOT_ISSUED_PRELIVE_HOLD',attempts,terminalDisposition:t?.disposition??null,qualificationCounted:!!counted,qualificationSequence:counted?t.publicRecord.qualification_sequence:null,exclusionReason:counted?null:t?.reason??'NOT_ISSUED_OR_UNRESOLVED',publicCallId:counted?t.publicRecord.public_call_id:null,normalizedIdentity:counted?t.normalizedSha256:null,admittedResultCount:counted?t.resultCount:null,qualification_value:counted?'ADMITTED_BOUNDED_EVIDENCE':'ZERO_NOT_COUNTED',engineering_value:starts.length?['AUTHENTICATED_TRANSPORT','CONCURRENCY_OBSERVATION','DURABLE_PRIMARY_MIRROR_STORAGE','BILLING_RATE_HEADER_OBSERVATION',...(!counted?['VALIDATION_MISMATCH_DIAGNOSIS']:[])]:[],gameplay_consumer_value:counted?'ADMITTED_BOUNDED_EVIDENCE_NOT_INTEGRATION_ACCEPTANCE':'NO_ADMITTED_GAMEPLAY_EVIDENCE_FROM_B1_V1',competition_evidence_value:counted?'SAFE_ADMITTED_QUALIFICATION_AUDIT':starts.length?'SAFE_ENGINEERING_AUDIT_ONLY':'PLAN_ONLY_NOT_ISSUED',signedFlowReview:{profileIdentity:context.priorResult.profile.hash,observedNullTimeProfileIdentity:context.a.context.profile.hash,stageStatuses:Object.fromEntries(keys.map(k=>[k,latest?.stages[k]?.status??'NOT_RUN'])),stats:latest?.semantic?.stats??null,matrixIdentity:latest?.semantic?identity(latest.semantic.matrix):null,localSupportCandidate:!!counted,leadAccepted:false}})
 }
 const result={...context.priorResult.audit,records,b3ContractReview:{executionContractSha256:CONTRACT_SHA,leadAcceptanceReceiptIdentity:context.lead.hash,planIdentity:context.plans.plan.hash,leadAcceptedBeforeB3:3,permanentlyHeldCalls:3,newLocalSupportCandidates:supported}}
 if(records.length!==22||identity(records.slice(0,17))!==identity(acceptedRecords(context)))throw new Error('B3_AUDIT_PRIOR_RECORDS_CHANGED');return result
}

export function acceptedRecords(c){return c.priorResult.audit.records.map(v=>{const r=structuredClone(v),x=c.lead.acceptanceCrosswalk.find(x=>x.logicalId===r.logicalId);if(x){r.formalLeadAcceptance={receiptIdentity:c.lead.hash,leadAccepted:true,leadAcceptanceOrder:x.leadAcceptanceOrder,immutableSupplierSequence:x.immutableSupplierSequence};if(r.signedFlowReview)r.signedFlowReview.leadAccepted=true}return r})}

export function audit(...args){const r=auditModel(...args);validateSchema('provider',r,JSON.parse(fs.readFileSync(path.join(args[0].root,'schemas/NANSEN_API_REQUEST_AUDIT.schema.json'))));return r}
