import fs from 'node:fs'
import path from 'node:path'
import { identity, validateSchema } from '../nq5/schema.mjs'
import { accepted, IDS, B2_IDS, HELD, ACCEPTED_ID, seal } from './authority.mjs'
import { receipt, requests, freeze } from './planner.mjs'
import { audit } from './audit.mjs'
export function publicBaseline(root){
 const a=accepted(root),o=a.b3PriorObjects,index=o['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'],priorAudit=o['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'],matrix=o['EVIDENCE/B3_LIVE_REQUEST_IDENTITY_MATRIX.json']??o['EVIDENCE/B2_LIVE_REQUEST_IDENTITY_MATRIX.json'],report=o['REPORTS/T1_B2_RECONCILIATION_REPORT.json'];const terminals=new Map(),responses=new Map(),starts=new Map(),projections=[]
 for(const v of priorAudit.records.filter(v=>v.issued)){starts.set(v.logicalId+'.1',{logicalId:v.logicalId});responses.set(v.logicalId+'.1',{});terminals.set(v.logicalId,{})}
 for(const [i,id] of B2_IDS.entries()){const x=matrix.requests.find(v=>v.logicalId===id),v=x.attempts[0],p=index.find(v=>v.qualification_sequence===5+i);responses.set(id+'.1',{providerRequestId:v.providerRequestId,rawSha256:v.rawSha256,rawBytes:v.rawBytes});terminals.set(id,{hash:x.terminalIdentity,disposition:x.terminalDisposition,normalizedSha256:v.normalizedIdentity,resultCount:v.resultCount,publicRecord:p});projections.push({logicalId:id,request:{body:x.body},semantic:{matrix:v.signBucketDirectionMatrix},admission:{semantic:{}}})}
 const state={rows:Array(24).fill(null),starts,responses,terminals,bytesSha256:report.ledgerSha256},result={index,audit:priorAudit,projections,report,profile:o['CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json']},lead=receipt(a,state,result),q=requests(a,null,lead),plans=freezePublic(a,result,lead,q),c={root,a,lead,plans,priorResult:result,state:{rows:[],starts:new Map(),responses:new Map(),terminals:new Map()},source:null};return c
}
function freezePublic(a,r,lead,q){const c={...r,privateProjections:[]}; // Public reconstruction never brands a runtime execution capability.
 const bind={campaignId:lead.campaignId,executionContractSha256:lead.executionContractSha256,reviewedB2ArchiveSha256:lead.reviewedB2ArchiveSha256,leadAcceptanceReceiptIdentity:lead.hash,signedFlowCompatibilityProfileIdentity:r.profile.hash,observedNullTimeProfileIdentity:a.context.profile.hash,correctedPublicIndexIdentity:identity(r.index),candidateMatrixIdentity:lead.frontierCandidateMatrixIdentity,balanceAnchor:625974,protectedReserve:250},policy=seal({schemaVersion:'1.0.0',...bind,exactLogicalIds:IDS,maximumRequests:5,maximumAttempts:15,maximumCredits:15,canaryConcurrency:2,maximumConcurrency:3,noSixthRequest:true,noReissue:true,noReplacement:true,noHeldLineage:true,oldSingletonPlanRejected:true,AUTHORIZED_TO_ISSUE:false}),plan=seal({schemaVersion:'1.0.0',...bind,requests:q,frontierPolicyIdentity:policy.hash,expectedCredits:5,worstCaseCredits:15,maximumAttempts:15,canaryConcurrency:2,maximumConcurrency:3,frozen:true,AUTHORIZED_TO_ISSUE:false}),reserve=seal({schemaVersion:'1.0.0',...bind,planIdentity:plan.hash,frontierPolicyIdentity:policy.hash,expectedCredits:5,worstCaseCredits:15,remainingAfterWorstCase:625959,reservePass:true,AUTHORIZED_TO_ISSUE:false});return {plan,reserve,policy}
}
export function unknownCounters(){return {newAttempts:null,newProvider2xx:null,newKnownCredits:null,supplierCountedTerminals:null,httpAttempts:null,provider2xx:null,knownCampaignCredits:null,unresolvedReservations:null,unresolvedTerminals:null,ledgerSha256:null,ledgerBytes:null,newLocalSupportCandidates:0,newFactsAdmitted:false,leadAcceptedBeforeB3:3,leadAcceptedAfterB3:3}}
export function historicalBlocked(root,phase,reason){const c=publicBaseline(root),au=audit(c,c.state,()=>{throw new Error('B3_NO_PRIVATE_READ_IN_HISTORICAL_FALLBACK')});for(const r of au.records.filter(v=>v.batchId==='B3'))Object.assign(r,{issued:null,issueDisposition:'ISSUE_STATE_UNKNOWN_AFTER_DURABLE_BREAKER',qualificationCounted:null,qualification_value:'UNKNOWN_NOT_ADMITTED_AFTER_DURABLE_BREAKER',exclusionReason:reason});validateSchema('provider',au,JSON.parse(fs.readFileSync(path.join(root,'schemas/NANSEN_API_REQUEST_AUDIT.schema.json'))));return {status:'BLOCKED_WITH_EVIDENCE',historicalOnly:true,c,phase,report:{schemaVersion:'1.0.0',status:'CURRENT_PRIVATE_RECONCILIATION_UNAVAILABLE',reason,...unknownCounters()},audit:au}}
