import { lessons as prior } from '../nq5-b2/lessons.mjs'
export function lessons(){const rows=[
 ['REPRESENTATIVE_SCALING','Meaningful frontier reduced to one call','Five meaningful candidates versus one chosen','Micro-batch is mandatory after semantics mature','Freeze all meaningful candidates up to exact bounded gate maximum','Exact5 canary2 then3 / B4 maximum64 no minimum','STABLE_POLICY'],
 ['UTILITY_NOT_LEXICAL','Address-first selection masks branching utility','Lexical singleton despite repeat counts','First address is most useful','Rank seed status, distinct support requests/transactions, coverage, consumers and purpose; address last','Independent deterministic utility ordering','STABLE_POLICY'],
 ['GLOBAL_VS_PER_CALL','Per-call row sum labeled global uniqueness','12 rows versus11 distinct tuples','Sum means unique','Emit perCallNormalizedRowSum separately from globalDistinctTransferIdentityCount','Canonical cross-call tuple Set','STABLE_POLICY'],
 ['SCOPED_NETWORK_COUNTERS','Generic external0 masks provider traffic','Provider requests nonzero beside external0','Reviewer0 describes runtime traffic','Separate reviewer, documentation, campaign provider, account and browser scopes','Explicit five-scope accounting','STABLE_POLICY'],
 ['LEAD_VS_SUPPLIER','Lead acceptance overwrites supplier sequence','Supplier5/6 versus Lead2/3','Supplier order is Lead order','Preserve immutable supplier sequence and publish formal Lead crosswalk','Exact3 acceptance receipt; held3 excluded','STABLE_POLICY'],
 ['DEDUPLICATED_LINEAGE','Repeated logical lineage duplicated per transfer','Repeated DURABLE_SUBJECT_TRANSFER tag','Repeated tags add evidence','Each supporting logical ID, transaction and transfer identity once','Set equality per candidate','STABLE_POLICY'],
 ['PROPOSED_NOT_CONFIRMED','Frontier described as confirmed route','Unissued candidate called route','Proposal confirms directional route','Use proposed frontier classification until own call accepted','No route/floor/causation assertion','STABLE_POLICY'],
 ['MATURE_BOUNDED_BATCHES','Repeated one-call micro-rounds after compatibility stable','Accepted signed/null/time path already exists','More micro-rounds prove safety','Prefer larger bounded representative batches with conditional canary ramp','Two durable canaries before remaining3; no sixth/B4 issue','CURRENT_OPERATIONAL_STATE']
 ];const historical=prior().rows.map(r=>r.findingId==='BOUNDED_TRUTHFUL_PATH'?{...r,classification:'HISTORICAL_B2_OPERATIONAL_STATE'}:r);return {schemaVersion:'1.0.0',scope:'B1_THROUGH_B3_ENGINEERING_KT_NOT_PUBLIC_GAME',rows:[...historical,...rows.map(([id,mechanism,falsifier,rejected,rule,test,classification])=>({findingId:id,falseSuccessMechanism:mechanism,firstFalsifier:falsifier,rejectedInterpretation:rejected,acceptedRule:rule,directTestOrInvariant:test,sourceKtCarryForwardText:rule,classification}))],sourceConsolidationPending:true,gameplayIntegration:false}
}
