import { identity, sha } from '../nq5/schema.mjs'
import { logicalRequest } from '../nq5/planner.mjs'
import { seal, IDS, B2_IDS, ACCEPTED_ID, HELD, CONTRACT_SHA, ARCHIVE_SHA, BASE, TREE, LEDGER_SHA } from './authority.mjs'
export const SPECS=[
 ['0x620fefb079854dd89cad930bdb596338a8265bb6','1dd47e2614fe57be4e612f386b9ac0c46df0a2d9697eb6f4eefa7b394973bd78',3],
 ['0xb003df4b243f938132e8cadbeb237abc5a889fb4','1c8cf1999257fb0350c9dd10994d50ba9938e5ce9e6db4ea375459a46eaddc73',2],
 ['0xef1c6e67703c7bd7107eed8303fbe6ec2554bf6b','2d439ae9ab6aa1b732ee93b5bfafbca6c3cef4219b62880abb6f155eca62ffac',2],
 ['0xa5d7f0f7027fa8f4d1be8042e1e43bbdec36951e','8dc43eb0e4e665d369abf8ebb5c7664a8e4c956bf83c6fd4685bfa6460cdbdb8',1],
 ['0xf16e9b0d03470827a95cdfd0cb8a8a3b46969b91','691a3567b3cc0296b177335d925c67c14e1fb3ecb472783c74d5e70e24333192',1]]
export const uniq=x=>[...new Set(x)].sort()
export const tuple=r=>identity([r.transaction_hash.toLowerCase(),r.from_address.toLowerCase(),r.to_address.toLowerCase(),r.token_address.toLowerCase(),r.amount])
export function utility(row){return {acceptedSeed:row.sourceKinds.some(k=>k.includes('SEED'))?1:0,distinctSupportingRequests:new Set(row.supportingLogicalIds).size,distinctSupportingTransactions:new Set(row.supportingTransactionHashes).size,coverageGap:row.alreadyIssuedEquivalent?0:1,consumerValue:row.namedConsumers?.length?1:0,purposeValue:({FLOW_DIRECTION_QUERY:3,ANCHOR_ACTIVITY_PAGE:2,DEAD_END_DISCOVERY:1,PAGINATION_COMPLETENESS:1})[row.purpose]??0}}
export function compareUtility(a,b){const x=utility(a),y=utility(b);for(const k of Object.keys(x)){const n=y[k]-x[k];if(n)return n}return a.subjectAddress.localeCompare(b.subjectAddress)||a.page-b.page}
export function receipt(a,state,r){
 const o=a.b3PriorObjects,index=o['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'],au=o['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'],matrix=o['EVIDENCE/BATCH3_FRONTIER_CANDIDATE_REJECTION_MATRIX.json'];if(identity(r.index)!==identity(index)||identity(r.audit)!==identity(au)||state.rows.length!==24||state.starts.size!==8||state.responses.size!==8||state.terminals.size!==8||state.bytesSha256!==LEDGER_SHA||r.report.supplierCountedTerminals!==6||r.report.unresolvedReservations!==0||r.report.unresolvedTerminals!==0||index.length!==3||au.records.length!==17)throw new Error('B3_EXACT_ACCEPTED_BASELINE')
 const expected=[['b664024c022a72753ec8881d1bc7036e','837cad0c7e7cd01a02060e61c8c5cf29a81458850bd773432cb3a4c079e7b70c','9f8246f2bd8caecbfec904692094f30a38758ea5e11e42d5d51d8dade49d7bdc',750,1,'bcd4492c6e06315b4b5c14ae8d95fcc9097fc6e75ebf7440644ba9087d52e5c0'],['2672e36c539c18027d712c25426b1068','2ad3512d7f70ce767c13b0a5730144f6e3a9cce213bca85d0dfcb6b1774e7257','472f39c3c8b0653599d0f90b1fa4fba196dfd49436b4dce4c378f0fb11aa04ab',6196,10,'22cb7584af99a6f0cfd794f25cd2ac05d62c3c225044f1ab6a6460ca5a10f7d1']]
 const calls=B2_IDS.map((id,i)=>{const t=state.terminals.get(id),v=state.responses.get(id+'.1'),p=r.projections.find(p=>p.logicalId===id),e=expected[i];if(!p||t.disposition!=='SUCCESS_COUNTED'||v.providerRequestId!==e[0]||v.rawSha256!==e[1]||t.normalizedSha256!==e[2]||v.rawBytes!==e[3]||t.resultCount!==e[4]||identity(p.semantic.matrix)!==e[5]||t.publicRecord.qualification_sequence!==5+i||t.publicRecord.public_call_id!=='NQ5-00000'+(5+i))throw new Error('B3_TWO_CALL_ACCEPTANCE_BINDINGS');return {logicalId:id,subject:p.request.body.address,providerRequestId:v.providerRequestId,rawPrimarySha256:v.rawSha256,rawMirrorSha256:v.rawSha256,rawBytes:v.rawBytes,normalizedSha256:t.normalizedSha256,resultCount:t.resultCount,signBucketMatrixIdentity:e[5],immutableTerminalIdentity:t.hash,publicCallId:t.publicRecord.public_call_id,immutableSupplierSequence:5+i,leadAcceptanceOrder:2+i}})
 const first=index.find(x=>x.public_call_id==='NQ5-000001');return seal({schemaVersion:'1.0.0',disposition:'TWO_B2_CALLS_LEAD_ACCEPTED',executionContractSha256:CONTRACT_SHA,reviewedB2ArchiveSha256:ARCHIVE_SHA,reviewedCandidate:{commit:BASE,tree:TREE},campaignId:a.context.bound.envelope.campaignId,calls,acceptanceCrosswalk:[{logicalId:ACCEPTED_ID,publicCallId:first.public_call_id,immutableSupplierSequence:1,leadAcceptanceOrder:1},...calls.map(({logicalId,publicCallId,immutableSupplierSequence,leadAcceptanceOrder})=>({logicalId,publicCallId,immutableSupplierSequence,leadAcceptanceOrder}))],leadAcceptedSuccesses:3,supplierCountedTerminals:6,httpAttempts:8,provider2xx:8,knownCampaignCredits:8,immutableLedgerSha256:LEDGER_SHA,immutableLedgerBytes:47766,correctedPublicIndexIdentity:identity(index),priorRequestAuditIdentity:identity(au),frontierCandidateMatrixIdentity:identity(matrix),signedFlowCompatibilityProfileIdentity:r.projections[0].admission.semantic.profileIdentity??o['CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json'].hash,observedNullTimeProfileIdentity:a.context.profile.hash,permanentlyHeldLogicalIds:HELD,heldTerminalMutationAllowed:false,reissueAllowed:false,oldOneRequestBatch3PlanDisposition:'REJECTED_UNDERSCALED_NO_ISSUE_AUTHORITY',publicIndexRowsAfterLeadAcceptance:3,publicIndexRowsPendingLeadAcceptance:0,gameplayIntegration:false,exactProof:false,negativeEvidence:false,completeness:false,causation:false})
}
export function requests(a,result,lead){const matrix=a.b3PriorObjects['EVIDENCE/BATCH3_FRONTIER_CANDIDATE_REJECTION_MATRIX.json'],rows=SPECS.map(([s,id,n])=>{const row=matrix.rows.find(r=>r.candidateIdentity===id);if(!row||row.subjectAddress!==s||row.supportingTransactionHashes.length!==n||!row.publicSafe||row.alreadyIssuedEquivalent||!row.sourceKinds.every(k=>k==='OPPOSITE_SIDE_SUBJECT_COUNTERPARTY'))throw new Error('B3_EXACT_MATRIX_ROW');const transfers=result?result.privateProjections.filter(p=>[ACCEPTED_ID,...B2_IDS].includes(p.logicalId)).flatMap(p=>p.admission.normalizedRecords.filter(v=>(v.from_address.toLowerCase()===p.request.body.address.toLowerCase()?v.to_address:v.from_address).toLowerCase()===s).map(v=>({logicalId:p.logicalId,transferIdentity:tuple(v),transactionHash:v.transaction_hash.toLowerCase()}))):[];const line=uniq(row.sourceLineage.flatMap(v=>v.lineage)),tx=uniq(transfers.map(v=>v.transactionHash)),ids=uniq(transfers.map(v=>v.logicalId)),tags=result?uniq(transfers.map(v=>'TRANSFER_IDENTITY.'+v.transferIdentity)):line.filter(v=>v.startsWith('TRANSFER_IDENTITY.'));if(result&&(identity(tx)!==identity(row.supportingTransactionHashes)||identity(ids)!==identity(row.supportingLogicalIds)||identity(tags)!==identity(line.filter(v=>v.startsWith('TRANSFER_IDENTITY.')))||ids.some(x=>!lead.acceptanceCrosswalk.some(v=>v.logicalId===x))))throw new Error('B3_CANDIDATE_SPECIFIC_DURABLE_PROOF');return {...row,deduplicatedLineage:line,supportingTransferIdentities:tags.map(v=>v.slice(18))}});if(identity([...rows].sort(compareUtility).map(r=>r.subjectAddress))!==identity(SPECS.map(r=>r[0])))throw new Error('B3_UTILITY_ORDER')
 return rows.map((r,i)=>{const repeated=i<3,lens='RELATIONSHIPS',purpose=repeated?'FLOW_DIRECTION_QUERY':'DEAD_END_DISCOVERY',role=repeated?'REPEATED_COUNTERPARTY_FLOW_TEST':'SINGLE_COUNTERPARTY_DEAD_END_TEST',questionId='QUESTION.T1.B3.RELATIONSHIPS.'+(repeated?'FLOW.':'DEADEND.')+r.subjectAddress,coverageKey={subject_id:r.subjectAddress,time_window_id:'2023-03-13T08:45:00Z/2023-03-13T12:15:00Z',question_lens:lens,page_or_partition_id:'PAGE.1'},cell='CELL.'+identity(coverageKey),template=a.context.plans.plan.requests[0],q={family:'profiler/address/transactions',method:'POST',path:'/api/v1/profiler/address/transactions',body:{address:r.subjectAddress,chain:'ethereum',date:{from:'2023-03-13T08:45:00Z',to:'2023-03-13T12:15:00Z'},pagination:{page:1,per_page:100}},sequence:i+1,lens,purpose,candidateRole:role,questionId,businessQuestion:repeated?'Does repeated opposite-side contextual incident activity for '+r.subjectAddress+' support a route-relevant directional pattern or resolve to a bounded dead-end test?':'Does the single-support counterparty '+r.subjectAddress+' have independent incident-window contextual activity or resolve to a bounded dead-end test?',coverageKey,coverageCells:[cell],lineage:uniq([...r.deduplicatedLineage,...r.supportingTransactionHashes.map(h=>'DURABLE_TRANSACTION.'+h)]),consumers:['TEST.T1.B3.'+role+'.'+r.subjectAddress,'PROVENANCE.T1.B3.'+r.subjectAddress,(repeated?'FLOWTEST':'DEADEND')+'.T1.B3.'+r.subjectAddress,cell],frontierProof:{kind:'LEAD_ACCEPTED_DURABLE_COUNTERPARTY',sourceCandidateMatrixIdentity:lead.frontierCandidateMatrixIdentity,candidateMatrixRowIdentity:r.candidateIdentity,subjectAddress:r.subjectAddress,supportingLogicalIds:r.supportingLogicalIds,supportingTransactionHashes:r.supportingTransactionHashes,supportingTransferIdentities:r.supportingTransferIdentities,sourceLeadAcceptanceReceiptIdentity:lead.hash},utilityRank:utility({...r,purpose}),novelty:'Unissued public-safe counterparty with '+r.supportingTransactionHashes.length+' distinct supporting transactions; proposed frontier test, not a confirmed route.',partition:{page:1,exactDurableNextPage:false},contractHash:template.contractHash,publicProjectionPolicy:structuredClone(template.publicProjectionPolicy),expectedCredits:1,worstCaseCredits:3,foregroundGameplayIntegrationAccepted:false,stopRule:'Stop first schema/privacy/storage/rate/credit/reserve/subject/raw/provider-ID/audit breaker; drain issued work independently. No sixth, replacement, page2, exact proof, negative evidence, completeness, causation or integration claim.'};q.logicalId=logicalRequest(q);return q})
}
export function validateSpecific(q){if(q.length!==5||q.some((r,i)=>r.logicalId!==IDS[i]||logicalRequest(r)!==IDS[i]||r.sequence!==i+1||r.body.address!==SPECS[i][0]||r.method!=='POST'||r.family!=='profiler/address/transactions'||r.body.chain!=='ethereum'||r.body.pagination.page!==1||r.body.pagination.per_page!==100||r.lens!=='RELATIONSHIPS'||r.purpose!==(i<3?'FLOW_DIRECTION_QUERY':'DEAD_END_DISCOVERY')||r.candidateRole!==(i<3?'REPEATED_COUNTERPARTY_FLOW_TEST':'SINGLE_COUNTERPARTY_DEAD_END_TEST')||r.frontierProof.candidateMatrixRowIdentity!==SPECS[i][1]||r.frontierProof.supportingTransactionHashes.length!==SPECS[i][2]||r.frontierProof.supportingLogicalIds.some(x=>![ACCEPTED_ID,...B2_IDS].includes(x))||r.lineage.length!==new Set(r.lineage).size||r.lineage.some(x=>HELD.some(h=>x.includes(h)))||r.coverageCells[0]!=='CELL.'+identity(r.coverageKey)||r.coverageKey.subject_id!==r.body.address||r.coverageKey.question_lens!==r.lens||r.consumers.length!==4||!r.consumers.every(x=>x===r.coverageCells[0]||x.includes(r.body.address))||r.foregroundGameplayIntegrationAccepted!==false))throw new Error('B3_EXACT_FIVE_CANDIDATE_METADATA');return true}
export function freeze(a,state,result,lead){const q=requests(a,result,lead);validateSpecific(q);if(q.some(r=>state.starts.has(r.logicalId+'.1')))throw new Error('B3_NO_REISSUE');const bind={campaignId:lead.campaignId,executionContractSha256:CONTRACT_SHA,reviewedB2ArchiveSha256:ARCHIVE_SHA,leadAcceptanceReceiptIdentity:lead.hash,signedFlowCompatibilityProfileIdentity:result.profile.hash,observedNullTimeProfileIdentity:a.context.profile.hash,correctedPublicIndexIdentity:identity(result.index),candidateMatrixIdentity:lead.frontierCandidateMatrixIdentity,balanceAnchor:625974,protectedReserve:250},policy=seal({schemaVersion:'1.0.0',...bind,exactLogicalIds:IDS,maximumRequests:5,maximumAttempts:15,maximumCredits:15,canaryConcurrency:2,maximumConcurrency:3,noSixthRequest:true,noReissue:true,noReplacement:true,noHeldLineage:true,oldSingletonPlanRejected:true,AUTHORIZED_TO_ISSUE:false}),plan=seal({schemaVersion:'1.0.0',...bind,requests:q,frontierPolicyIdentity:policy.hash,expectedCredits:5,worstCaseCredits:15,maximumAttempts:15,canaryConcurrency:2,maximumConcurrency:3,frozen:true,AUTHORIZED_TO_ISSUE:false}),reserve=seal({schemaVersion:'1.0.0',...bind,planIdentity:plan.hash,frontierPolicyIdentity:policy.hash,expectedCredits:5,worstCaseCredits:15,remainingAfterWorstCase:625959,reservePass:true,AUTHORIZED_TO_ISSUE:false});return {plan,reserve,policy}}
