import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import { gitEnv } from '../nq5-b1-r1/gates.mjs'
import { identity, sha, validateSchema } from '../nq5/schema.mjs'
import { readMirrored, replay } from '../nq5-b1/store.mjs'
import { configuredCampaignRoots } from '../nq5-r3/genesis.mjs'
import { assertPrivateAncestry, assertRawInventory } from '../nq5-b1-r3/gate-proof.mjs'
import { IDS as OLD_IDS } from '../nq5-b1-r3/authority.mjs'
import { captureSafeHeaders } from '../nq5-b1-r1/headers.mjs'
import { revalidate } from '../nq5-b1-r3-r2/evidence.mjs'
import { frontier as buildFrontier } from './frontier.mjs'
import { tuple } from './planner.mjs'
import { postContext } from './context.mjs'
export { postContext }
import { accepted, cut, digest, seal, CONTRACT_SHA, IDS, AUTH, HELD, ACCEPTED_ID, ARCHIVE_SHA, historicalDigest, ISSUE_ORDER } from './authority.mjs'
import { receipt, freeze } from './planner.mjs'
import { extension, envelope, LOCK } from './executor.mjs'
import { verifyCapturedBinding } from './docs.mjs'
import { admit } from './admission.mjs'
import { audit } from './audit.mjs'
export function deliveryStatus(report,execution){return report.clean&&report.newDistinctRequests===5&&report.newSettledExactRequests===5&&report.newAttempts<=15&&!execution.stopReason?'DELIVERED_PENDING_LEAD_REVIEW':'BLOCKED_WITH_EVIDENCE'}
export function verifyEnvelope(c,e,docs){const{hash,...p}=e;if(hash!==identity(p))throw new Error('B3_EXECUTION_ENVELOPE_SEAL');const original={...c,source:{candidate:e.candidate,implementationSha256:e.implementationSha256}};if(identity(e)!==identity(envelope(original,docs)))throw new Error('B3_EXACT_EXECUTION_ENVELOPE_BINDINGS');return true}
export function transferMetrics(projections){const sum=k=>projections.reduce((n,p)=>n+p.semantic.stats[k],0),eligibleNonzeroRows=sum('eligibleNonzeroRows'),duplicateRows=sum('duplicateRows');return {rawTransferRows:sum('rawTransferRows'),duplicateRows,incidentalRows:sum('incidentalRows'),zeroRows:sum('zeroRows'),eligibleNonzeroRows,duplicateRatio:eligibleNonzeroRows?duplicateRows/eligibleNonzeroRows:0}}
export function reconcile(c,e){
 const docs=verifyCapturedBinding(c.root,e.officialSourceIdentity);verifyEnvelope(c,e,docs);if(e.implementationSha256!==historicalDigest(c.root,e.candidate.commit))throw new Error('B3_CURRENT_IMPLEMENTATION_BINDING')
 const git=(...args)=>execFileSync('git',args,{cwd:c.root,env:gitEnv(),encoding:'utf8'}).trim();if(!/^[a-f0-9]{40}$/.test(e.candidate.commit)||git('rev-parse',e.candidate.commit+'^{tree}')!==e.candidate.tree)throw new Error('B3_INCLUDED_EXECUTION_CUT');git('merge-base','--is-ancestor',e.candidate.commit,'HEAD')
 const current=replay(c.state.roots,extension(c)),bytes=readMirrored(c.state.roots,'qualification.jsonl');if(sha(bytes.subarray(0,47766))!==e.priorLedgerSha256||identity(current.rows.slice(0,24))!==identity(c.state.rows))throw new Error('B3_ORIGINAL_HISTORY_CHANGED');const lock=JSON.parse(readMirrored(c.state.roots,LOCK)),{hash:lh,...lp}=lock;if(lh!==identity(lp)||lock.executionEnvelopeHash!==e.hash||lock.campaignId!==c.lead.campaignId||identity(lock.candidate)!==identity(e.candidate)||lock.implementationSha256!==e.implementationSha256)throw new Error('B3_INVOCATION_LOCK_CHANGED')
 const added=current.rows.slice(24),starts=added.filter(r=>r.kind==='START'),responses=added.filter(r=>r.kind==='RESPONSE'),terminals=added.filter(r=>r.kind==='TERMINAL');if(starts.length>15||added.some(r=>!IDS.includes(r.logicalId)||r.b3ExecutionEnvelopeHash!==e.hash||r.authorizationId!==AUTH||r.executionContractSha256!==CONTRACT_SHA||r.planIdentity!==c.plans.plan.hash||r.sealedRequestIdentity!==identity(c.plans.plan.requests.find(q=>q.logicalId===r.logicalId))||r.leadAcceptanceReceiptIdentity!==c.lead.hash||r.signedFlowCompatibilityProfileIdentity!==c.priorResult.profile.hash))throw new Error('B3_ADDITIVE_AUTHORITY_DRIFT');for(const s of starts){const q=c.plans.plan.requests.find(q=>q.logicalId===s.logicalId);if(s.requestBodySha256!==identity(q.body)||s.reservedCredits!==1||!Number.isFinite(Date.parse(s.issuedAtUtc)))throw new Error('B3_START_IDENTITY')}
 assertRawInventory(c.state.roots,[...current.responses.values()].map(r=>r.rawName));const inventory=['B1_EXECUTION_LOCK.json','B1_R3_RESUME_LOCK.json','GENESIS_COMMIT.json','genesis.json','qualification.jsonl','raw-b1','T1_B2_EXECUTION_LOCK.json',LOCK].sort().join();for(const root of c.state.roots)if(fs.readdirSync(root).sort().join()!==inventory)throw new Error('B3_PRIVATE_INVENTORY')
 const projections=[],newPublic=[];for(const t of terminals){const q=c.plans.plan.requests.find(q=>q.logicalId===t.logicalId),r=current.responses.get(t.logicalId+'.'+t.attempt);if(t.disposition==='SUCCESS_COUNTED'){if(!r||r.httpStatus!==200||r.actualCredits!==1||r.quotedCredits!==1||!r.providerRequestId||r.providerRequestId!==r.headers['x-request-id']||identity(captureSafeHeaders(r.headers))!==identity(r.headers)||t.auditDisposition!=='PASS')throw new Error('B3_COUNT_CREDIT_PROVIDER_ID');const a=admit(c,q,readMirrored(c.state.roots,'raw-b1/'+r.rawName),r,7+newPublic.length);if(!a.safelyAdmissible||!a.resultCount||a.normalizedSha256!==t.normalizedSha256||a.resultCount!==t.resultCount||identity(a.publicRecord)!==identity(t.publicRecord)||identity(a.stages)!==identity(t.validationStages))throw new Error('B3_COUNT_REDERIVATION');newPublic.push(a.publicRecord);projections.push({logicalId:q.logicalId,request:q,admission:a,semantic:a.semantic,pagination:a.pagination,leadAcceptanceCandidate:true})}else if(t.publicRecord!==null)throw new Error('B3_NONCOUNTED_PUBLIC')}
 const known=responses.reduce((n,r)=>n+(r.actualCredits??0),0),unresolved=starts.filter(s=>!current.responses.has(s.logicalId+'.'+s.attempt)||current.responses.get(s.logicalId+'.'+s.attempt).actualCredits===null).length,unresolvedTerminals=IDS.filter(id=>starts.some(s=>s.logicalId===id)&&!current.terminals.has(id)).length;if(known>15)throw new Error('B3_CREDIT_CAP');const index=[...c.priorResult.index,...newPublic];validateSchema('provider',index,JSON.parse(fs.readFileSync(path.join(c.root,'schemas/NQ5_PUBLIC_CALL_INDEX.schema.json'))));if(new Set(index.map(r=>r.public_call_id)).size!==index.length)throw new Error('B3_PUBLIC_DUPLICATE');const auditResult=audit(c,current,r=>readMirrored(c.state.roots,'raw-b1/'+r.rawName)),remaining=Math.min(625974,...responses.map(r=>r.remainingCredits).filter(Number.isSafeInteger)),report={schemaVersion:'1.0.0',campaignId:c.lead.campaignId,priorLedgerSha256:e.priorLedgerSha256,priorLedgerBytes:47766,ledgerSha256:current.bytesSha256,ledgerBytes:current.bytes,immutableEightAttemptsResponsesAndTerminalsUnchanged:true,permanentlyHeldTerminalsUnchanged:true,newAttempts:starts.length,newDistinctRequests:new Set(starts.map(r=>r.logicalId)).size,newSettledExactRequests:IDS.filter(id=>current.terminals.has(id)).length,newProvider2xx:responses.filter(r=>r.httpStatus>=200&&r.httpStatus<300).length,newSupplierCountedTerminals:newPublic.length,supplierCountedTerminals:6+newPublic.length,leadAcceptedBeforeB3:3,leadAcceptedAfterB3:3,newLocalSupportCandidates:newPublic.length,locallySupportableCalls:3+newPublic.length,newKnownCredits:known,knownCampaignCredits:8+known,retries:starts.length-new Set(starts.map(r=>r.logicalId)).size,unresolvedReservations:unresolved,unresolvedTerminals,clean:unresolved===0&&unresolvedTerminals===0,latestSafeResponseBalance:remaining,accountRequests:0,localReuseCount:0,priorDiscoveryCountsNotQualification:32,totalAccountWideDecrease:630027-remaining,totalCampaignKnownCredits:8+known,totalAccountWideUnattributedChange:630027-remaining-(8+known),r3AndB3IntervalDecrease:627478-remaining,r3AndB3IntervalKnownCredits:6+known,r3AndB3IntervalUnattributedChange:627478-remaining-(6+known),b3HeaderBalanceDecrease:625974-remaining,b3KnownCredits:known,b3UnattributedHeaderBalanceChange:625974-remaining-known,balanceSource:'SAFE_PROVIDER_RESPONSE_HEADER_NOT_NEW_ACCOUNT_OBSERVATION',causeAssigned:false,publicIndexIdentity:identity(index),requestAuditIdentity:identity(auditResult),exactProviderRequestIdsCaptured:responses.filter(r=>r.providerRequestId).length,primaryMirrorRawEqual:true,AUTHORIZED_TO_ISSUE:false}
 Object.assign(report,{httpAttempts:current.starts.size,provider2xx:[...current.responses.values()].filter(x=>x.httpStatus>=200&&x.httpStatus<300).length,publicIndexRowsAfterLeadAcceptance:3,publicIndexRowsPendingLeadAcceptance:newPublic.length,b2IntervalDecrease:658,b2KnownCredits:2,b2UnattributedIntervalChange:656,reviewerExternalRequests:0,authenticatedCampaignProviderRequests:starts.length,unauthenticatedDocumentationGets:docs.index.unauthenticatedDocumentationGets,browserRuntimeProviderRequests:0});return {current,report,index,audit:auditResult,projections}
}
export function nextFrontier(c,r){
 const allowed=[...c.priorResult.privateProjections,...r.projections],context={...c.a.context,frontierBatch:4,bound:{...c.a.context.bound,plan:{...c.a.context.bound.plan,requests:[...c.a.context.bound.plan.requests,...c.a.b3PriorObjects['PLANS/T1_BATCH2_EXECUTION_PLAN.json'].requests,...c.plans.plan.requests]}}},f=buildFrontier({...c.a,context},r.current,{allPass:allowed.length>=3,privateProjections:allowed,acceptance:r.report}),matrix={...f.matrix,heldCallsExcluded:HELD,leadAcceptedOrNewSupportCandidatesOnly:true,rawIncidentalCandidatesUsed:0,rows:f.matrix.rows.map(x=>({...x,projectionRule:'SIGNED_FLOW_TO_UNSIGNED_TRANSFER_MAGNITUDE'}))},bind={campaignId:c.lead.campaignId,executionContractSha256:CONTRACT_SHA,acceptedB2ArchiveSha256:ARCHIVE_SHA,leadAcceptanceReceiptIdentity:c.lead.hash,correctedPublicIndexIdentity:identity(r.index),requestAuditIdentity:identity(r.audit),candidateMatrixIdentity:identity(matrix),signedFlowCompatibilityProfileIdentity:c.priorResult.profile.hash,observedNullTimeProfileIdentity:c.a.context.profile.hash,balanceAnchor:r.report.latestSafeResponseBalance,protectedReserve:250};let plan=null,reserve=null,policy=null
 if(f.plan){const{hash,...p}=f.plan,{hash:ph,...pol}=f.policy;policy=seal({...pol,...bind,allFourSemanticRetentionRequired:false,perCallSupportableSourceRequired:true});plan=seal({...p,...bind,frontierPolicyIdentity:policy.hash,AUTHORIZED_TO_ISSUE:false});reserve=seal({schemaVersion:'1.0.0',...bind,planIdentity:plan.hash,frontierPolicyIdentity:policy.hash,worstCaseCredits:plan.worstCaseCredits,remainingAfterWorstCase:bind.balanceAnchor-plan.worstCaseCredits,reservePass:bind.balanceAnchor-plan.worstCaseCredits>=250,AUTHORIZED_TO_ISSUE:false})}
 const metrics=transferMetrics(allowed),normalized=allowed.reduce((n,p)=>n+p.admission.resultCount,0),eligible=matrix.rows.filter(x=>x.admitted||x.rejectionCode==='DEFERRED_EXACT_MAXIMUM_64'),viability={schemaVersion:'1.0.0',newLocallySupportableCalls:r.projections.length,qualifyingSourceCalls:allowed.length,acceptedB2BaselineMetrics:{perCallNormalizedRowSum:12,globalDistinctTransferIdentityCount:11,scope:'THREE_FORMAL_LEAD_ACCEPTED_CALLS_PRIOR_TO_B3'},perCallNormalizedRowSum:normalized,globalDistinctTransferIdentityCount:new Set(allowed.flatMap(p=>p.admission.normalizedRecords.map(tuple))).size,duplicateScope:'PER_CALL_NORMALIZATION_NOT_CROSS_CALL_GLOBAL_DUPLICATES',...metrics,completeCandidateRows:matrix.rows.length,meaningfulUnissuedCandidates:eligible.length,branchingFactor:allowed.length?eligible.length/allowed.length:0,coverageCells:[...new Set(r.index.flatMap(x=>x.coverage_cell_ids))],proposedFrontierCandidates:eligible.filter(x=>x.purpose!=='DEAD_END_DISCOVERY').length,deadEndQuestionCandidates:c.plans.plan.requests.filter(x=>x.purpose==='DEAD_END_DISCOVERY').length,namedConsumers:[...new Set(r.index.flatMap(x=>x.consumer_ids))],transactionOnlyFloorAssessment:eligible.length?'BOUNDED_BRANCHING_OBSERVED_FLOOR1024_ROUTE_UNPROVEN':'NO_CURRENT_UNISSUED_USEFUL_BRANCH_OBSERVED_FLOOR1024_ROUTE_UNPROVEN',certaintyClaimed:false,qualificationFloorClaimed:false,fiveCallExperimentNotPopulationProof:true,BATCH4_AUTHORIZED_TO_ISSUE:false,nextRequestsIssued:0,planGenerated:!!plan,candidateMatrixIdentity:identity(matrix),requestAuditIdentity:identity(r.audit),correctedPublicIndexIdentity:identity(r.index)}
 return {matrix,plan,reserve,policy,viability}
}
