import { expect, test } from '@playwright/test'

test('placeholder Euler skeleton is player-paced and completes without provider requests', async ({ page }) => {
  const providerRequests: string[] = []
  page.on('request', (request) => {
    const url = new URL(request.url())
    if (/\/api\/v1\//i.test(url.pathname) || /nansen|alchemy/i.test(url.hostname)) providerRequests.push(url.href)
  })
  await page.goto('/?mission=1')
  const harness = page.getByTestId('euler-mission-harness')
  await expect(harness).toHaveAttribute('data-stage', 'ONBOARDING')
  const dialogue = page.getByTestId('mission-dialogue')
  await expect(dialogue).toHaveAttribute('data-animation-id', 'gesture.explain')
  await expect(dialogue).toHaveAttribute('data-facing', 'LEFT')
  const semanticFigure = page.locator('.semantic-cue-figure')
  await expect(semanticFigure.locator('img').first()).toBeVisible()
  await dialogue.click()
  await dialogue.click()
  await expect(semanticFigure).toHaveAttribute('data-overlay-frame', 'overlays.reaction.question.frame1')
  await page.waitForFunction(() => document.querySelector<HTMLElement>('.semantic-cue-figure')?.dataset.overlayFrame === 'overlays.reaction.question.frame2')
  await dialogue.click()
  await dialogue.click()
  await expect(semanticFigure).toHaveAttribute('data-semantic-id', 'talk.neutral.closed')
  await page.waitForFunction(() => document.querySelector<HTMLElement>('.semantic-cue-figure')?.dataset.semanticId === 'talk.neutral.open')
  await page.getByRole('button', { name: 'MOTION FULL' }).click()
  await expect(page.getByRole('button', { name: 'MOTION REDUCED' })).toHaveAttribute('aria-pressed', 'true')
  for (let index = 0; index < 12; index += 1) await dialogue.click()
  await expect(page.getByText(/PROP recognized/)).toBeVisible()
  await expect(semanticFigure).toHaveAttribute('data-semantic-id', 'talk.neutral.closed')
  await dialogue.click()
  await expect(semanticFigure).toHaveAttribute('data-semantic-id', 'talk.neutral.closed')
  for (let index = 0; index < 3; index += 1) await dialogue.click()
  await expect(harness).toHaveAttribute('data-stage', 'FIRST_RECORD')
  await page.getByRole('button', { name: 'ACQUIRE FIRST BREACH RECORD' }).click()
  await page.getByRole('button', { name: 'READ FIRST BREACH' }).click()
  await page.getByRole('button', { name: 'READ SECOND BREACH' }).click()
  await page.getByRole('button', { name: 'IT STOPPED AT THE FIRST ENGINE' }).click()
  await page.getByRole('button', { name: 'SWEEP FORWARD' }).click()
  await expect(page.getByText('THE FIRST ENGINE WAS NOT THE END. REVISE THE HYPOTHESIS.')).toBeVisible()
  await page.getByRole('button', { name: 'IT JOINED THE SECOND ROUTE' }).click()
  await page.getByRole('button', { name: 'SWEEP FORWARD' }).click()
  await page.getByRole('button', { name: /AMOUNT \/\/ EXACT_EARLY_NET/ }).click()
  await page.getByRole('button', { name: /RECEIVER \/\/ EXACT_MAIN_RECEIVER/ }).click()
  await page.getByRole('button', { name: /LINK \/\/ EXACT_CONVERGENCE/ }).click()
  await expect(harness).toHaveAttribute('data-stage', 'COMPLETE')
  await expect(page.getByText('NO LIVE CALLS DURING PLAY')).toBeVisible()
  expect(providerRequests).toEqual([])
})
