import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {buildFrozenFixture} from '../../src/investigation/fixture'
import {office,activate,button,resolveCandidateRoute} from '../fixtures/s2/browser-helpers'
const scenario=JSON.parse(readFileSync('public/scenarios/euler-2023-false-exit/scenario.json','utf8')) as Parameters<typeof buildFrozenFixture>[0]
const graph=JSON.parse(readFileSync('public/scenarios/euler-2023-false-exit/evidence-graph.json','utf8')) as Parameters<typeof buildFrozenFixture>[1]
const fixture=buildFrozenFixture(scenario,graph)
for(const mode of ['FULLSCREEN_CRT','DOCKED_OVERLAY','PLAIN_LIST'])test('S5-R1 one EXPLORE model and display-only SOURCE in '+mode,async({page})=>{
 await page.context().route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!=='http://127.0.0.1:4173'||route.request().method()!=='GET'||!(u.pathname==='/'||u.pathname==='/favicon.ico'||/^\/(assets|art-packs|artifacts|public|scenarios|content|src|node_modules|@vite|@react-refresh)(\/|$)/.test(u.pathname)))return route.abort('blockedbyclient');return route.continue()})
 await page.goto('/');await expect(page.getByTestId('a0-shell')).toBeVisible()
 await office(page,'KEYBOARD','DIRECT_SOLVER')
 await activate(page,page.getByText('Presentation and accessibility',{exact:true}),'KEYBOARD')
 await page.getByLabel('Terminal presentation').selectOption(mode)
 await activate(page,button(page,'ASK A QUESTION'),'KEYBOARD')
 await activate(page,page.locator('.question-cards article button').first(),'KEYBOARD')
 await activate(page,button(page,'DISPATCH'),'KEYBOARD')
 await expect(page.getByTestId('case-terminal')).toHaveAttribute('data-section','RESULTS')
 await resolveCandidateRoute(page,fixture,'KEYBOARD')
 await activate(page,button(page,'EXPLORE'),'KEYBOARD')
 const sea=page.getByTestId('semantic-evidence-sea');await expect(sea.locator('article')).toHaveCount(25)
 await expect(page.getByRole('searchbox')).toHaveCount(1)
 await expect(sea.getByRole('group',{name:'Local browse controls — no external requests'})).toHaveCount(1)
 await expect(sea.getByLabel('Group records by',{exact:true})).toHaveCount(1)
 await expect(sea.getByRole('button',{name:'Reset local filters',exact:true})).toHaveCount(1)
 await expect(sea.getByRole('status')).toHaveCount(1);await expect(sea.getByRole('status')).toContainText('25 of 25 display records; 7 scoped corpus no-match findings')
 await expect(page.getByTestId('case-corpus')).toHaveCount(0)
 await expect(page.getByLabel('Search discovered records',{exact:true})).toHaveCount(0)
 await expect(page.getByText('Manual filters from known values',{exact:true})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'SHOW MORE CORPUS RECORDS',exact:true})).toHaveCount(0)
 await sea.getByLabel('Result status',{exact:true}).selectOption('bounded-no-match')
 await expect(sea.locator('article')).toHaveCount(7);await expect(sea.getByRole('status')).toContainText('7 of 25')
 await activate(page,sea.getByRole('button',{name:'INSPECT DISPLAY-SAFE SOURCE',exact:true}).first(),'KEYBOARD')
 const source=page.getByTestId('semantic-display-source');await expect(source).toBeVisible()
 await expect(source).toContainText('It cannot fill AMOUNT, RECEIVER or LINK')
 await expect(source).toContainText('CLAIM LIMITS');await expect(source).toContainText('No match in the accepted corpus')
 await expect(source.getByRole('button',{name:/EXACT RECEIPT|FILE|ASSEMBLE|DISPATCH/})).toHaveCount(0)
 await expect(source.getByText('Raw response SHA-256',{exact:true})).toHaveCount(0)
 await expect(page.getByTestId('case-terminal')).toHaveAttribute('data-proof-events','0')
 await activate(page,source.getByRole('button',{name:'BACK TO EVIDENCE SEA',exact:true}),'KEYBOARD')
 await expect(sea.getByRole('status')).toContainText('7 of 25')
 await activate(page,sea.getByRole('button',{name:'Reset local filters',exact:true}),'KEYBOARD')
 await sea.getByLabel('Question Lens',{exact:true}).selectOption('ACTIVITY');await expect(sea.getByRole('status')).toContainText('10 of 25')
 await activate(page,sea.getByRole('button',{name:'INSPECT DISPLAY-SAFE SOURCE',exact:true}).first(),'KEYBOARD')
 await expect(source).toContainText('Contextual display is not an exact Hero receipt')
 await expect(page.getByTestId('case-terminal')).toHaveAttribute('data-proof-events','0')
 await activate(page,source.getByRole('button',{name:'BACK TO EVIDENCE SEA',exact:true}),'KEYBOARD')
 await expect(sea.getByRole('status')).toContainText('10 of 25')
 await activate(page,button(page,'CASE'),'KEYBOARD');await activate(page,button(page,'ASK A QUESTION'),'KEYBOARD');await activate(page,button(page,'DISPATCH'),'KEYBOARD')
 await activate(page,page.locator('.candidate-folder').first().getByRole('button',{name:'SOURCE FOR THIS RESULT',exact:true}),'KEYBOARD')
 await expect(page.getByRole('heading',{name:/PUBLIC-SAFE SOURCE/})).toBeVisible()
 await expect(page.getByText('Raw response SHA-256',{exact:true})).toBeVisible()
 await expect(page.getByTestId('semantic-display-source')).toHaveCount(0)
})
