import { expect, test } from '@playwright/test'
import { activate, button, drainBrowserSpeech, enterTerminalFromWorld, office, resolveCandidateRoute, setup } from '../fixtures/s2/browser-helpers'
import { violatesFrozenBrowserPolicy } from '../fixtures/browser-policy'
test.setTimeout(180_000)

// S9-P1 structural flows: authorization gating, progressive disclosure,
// cabinet unlock, inventory capacity, and network-blocked static play.
test.describe('S9-P1 structural flows', () => {
  test('pre-authorization terminal use reprimands and never opens', async ({ page }) => {
    await setup(page, 91)
    await page.goto('/?skipIntro=1')
    await expect(page.getByTestId('a0-shell')).toBeVisible()
    await page.getByTestId('verb-use').click()
    await page.getByTestId('hotspot-nansen-terminal').click()
    await expect(page.getByTestId('active-sequence')).not.toHaveCount(0)
    await expect(page.getByTestId('case-terminal')).toHaveCount(0)
    for (let guard = 0; guard < 12 && await page.getByTestId('speech-panel').isVisible().catch(() => false); guard++) {
      await page.getByTestId('speech-panel').click()
    }
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-phase', 'START')
    await expect(page.getByTestId('case-terminal')).toHaveCount(0)
  })

  test('authorized terminal opens to the CASE shell with no future sections', async ({ page }) => {
    const data = await setup(page, 92)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    const terminal = page.getByTestId('case-terminal')
    await expect(terminal).toHaveAttribute('data-terminal-stage', '3')
    await expect(page.getByTestId('terminal-section-results')).toHaveCount(0)
    await expect(page.getByTestId('terminal-section-explore')).toHaveCount(0)
    await expect(page.getByTestId('terminal-section-source')).toHaveCount(0)
    await expect(page.getByTestId('terminal-section-ledger')).toHaveCount(0)
    await expect(page.getByTestId('terminal-section-case')).toBeVisible()
    await expect(page.getByTestId('semantic-evidence-sea')).toHaveCount(0)
    expect(await terminal.innerText()).not.toContain('11:38:11')
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('first dispatch unlocks results, source, and ledger but not explore', async ({ page }) => {
    const data = await setup(page, 93)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await activate(page, page.locator('.question-cards article button').first(), 'KEYBOARD')
    await activate(page, button(page, 'DISPATCH'), 'KEYBOARD')
    const terminal = page.getByTestId('case-terminal')
    await expect(terminal).toHaveAttribute('data-section', 'RESULTS')
    await expect(terminal).toHaveAttribute('data-terminal-stage', '4')
    await expect(page.getByTestId('terminal-section-results')).toBeVisible()
    await expect(page.getByTestId('terminal-section-source')).toBeVisible()
    await expect(page.getByTestId('terminal-section-ledger')).toBeVisible()
    await expect(page.getByTestId('terminal-section-explore')).toHaveCount(0)
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('ten-slot inventory fits the maximum set at native scale and 200% zoom', async ({ page }) => {
    await setup(page, 94)
    await page.goto('/?skipIntro=1')
    await expect(page.locator('.inventory-slot')).toHaveCount(10)
    await page.getByTestId('verb-open').click()
    await page.getByTestId('hotspot-miscellaneous-drawer-cabinet').click()
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-misc-drawer', 'OPEN')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await page.getByTestId('verb-pick-up').click()
    await page.getByTestId('hotspot-miscellaneous-catch-all-contents').click()
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.locator('.inventory-slot:not(.empty)')).toHaveCount(5)
    await page.evaluate(() => { document.body.style.zoom = '200%' })
    for (const item of ['inventory-rubber-band', 'inventory-rubiks-cube', 'inventory-sharknado-2-vhs', 'inventory-piggy-bank-intact', 'inventory-small-toolbox-closed']) {
      await expect(page.getByTestId(item)).toBeVisible()
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 2)).toBe(true)
  })

  test('R1 stage 3 asks exactly one guided question with no future cards', async ({ page }) => {
    const data = await setup(page, 96)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expect(page.locator('.question-cards > article')).toHaveCount(1)
    await expect(page.getByRole('button', { name: 'STAGE Which DAI movements match the incident window?', exact: true })).toBeVisible()
    await expect(page.getByText('All discovered Question Cards and four lenses', { exact: true })).toBeVisible()
    const cards = await page.locator('.question-cards').innerText()
    expect(cards).not.toContain('What left the First Engine?')
    expect(cards).not.toContain('COMPARE THESE TWO ROUTES')
    expect(cards).not.toContain('ASK FOR THIS EXACT RECEIPT')
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R1 stage 4 shows results without any exact-receipt path', async ({ page }) => {
    const data = await setup(page, 97)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await activate(page, page.locator('.question-cards article button').first(), 'KEYBOARD')
    await activate(page, button(page, 'DISPATCH'), 'KEYBOARD')
    await expect(page.getByTestId('case-terminal')).toHaveAttribute('data-terminal-stage', '4')
    await expect(page.getByRole('button', { name: 'ASK FOR THIS EXACT RECEIPT', exact: true })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'RELATIONSHIPS: COMPARE THESE TWO ROUTES', exact: true })).toHaveCount(0)
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R1 comparisons alone cannot reach stage 5; candidate route resolves it', async ({ page }) => {
    const data = await setup(page, 98)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await activate(page, page.locator('.question-cards article button').first(), 'KEYBOARD')
    await activate(page, button(page, 'DISPATCH'), 'KEYBOARD')
    await expect(page.getByTestId('case-terminal')).toHaveAttribute('data-terminal-stage', '4')
    await expect(page.getByRole('button', { name: 'COMPARE CANDIDATE', exact: true })).toHaveCount(0)
    await expect(page.getByRole('table', { name: 'Factual comparison — no confidence scores' })).toHaveCount(0)
    await resolveCandidateRoute(page, data.fixture, 'KEYBOARD')
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R1 retired tube language and Mr. Index are absent in every presentation mode', async ({ page }) => {
    const data = await setup(page, 99)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    expect(await page.locator('body').innerText()).not.toMatch(/pneumatic tube|plunger|canister|access strip|physical dispatch/i)
    expect(await page.locator('body').innerText()).not.toContain('Mr. Index')
    await page.getByText('Presentation and accessibility', { exact: true }).click()
    for (const mode of ['DOCKED_OVERLAY', 'PLAIN_LIST', 'FULLSCREEN_CRT'] as const) {
      await page.getByLabel('Terminal presentation').selectOption(mode)
      const terminal = page.getByTestId('case-terminal')
      expect(await terminal.innerText()).not.toMatch(/pneumatic tube|plunger|canister|access strip|physical dispatch/i)
      expect(await terminal.innerText()).not.toContain('Mr. Index')
      expect(await terminal.ariaSnapshot()).not.toContain('Mr. Index')
    }
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R3 note acquisition is not reading: side lead unlocks only at BACK_READ', async ({ page }) => {
    const data = await setup(page, 100)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'KEYBOARD')
    await activate(page, page.getByTestId('verb-open'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-small-toolbox-closed'), 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('inventory-small-toolbox-open-empty')).toBeVisible()
    await expect(page.getByTestId('inventory-hammer')).toBeVisible()
    await expect(page.getByTestId('inventory-nails')).toBeVisible()
    await expect(page.getByTestId('inventory-small-toolbox-closed')).toHaveCount(0)
    await activate(page, page.getByTestId('verb-use'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-hammer'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-piggy-bank-intact'), 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('inventory-fictional-token-note')).toBeVisible()
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await page.getByText('OPEN PERSISTENT CASEBOARD', { exact: true }).click()
    await expect(page.getByText('OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE', { exact: true })).toHaveCount(0)
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'KEYBOARD')
    await activate(page, page.getByTestId('verb-look-at'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-fictional-token-note'), 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'BACK_READ')
    await expect(page.getByTestId('inventory-fictional-token-note')).toBeVisible()
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await page.getByText('OPEN PERSISTENT CASEBOARD', { exact: true }).click()
    await page.getByText('OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE', { exact: true }).click()
    await expect(page.getByTestId('case-terminal')).toContainText('LATE-BOUND TOKEN (integration gate pending)')
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveCount(1)
    await expect(page.getByRole('button', { name: /MOTION/ })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'REDUCED MOTION', exact: true })).toHaveCount(0)
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R1 hidden time does not advance bark eligibility and reset preserves world facts', async ({ page }) => {
    const data = await setup(page, 101)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    const shell = page.getByTestId('a0-shell')
    expect(shell).toHaveCount(0)
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'KEYBOARD')
    const before = await page.getByTestId('a0-shell').getAttribute('data-inactive-seconds')
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }) })
    await page.waitForTimeout(3500)
    const during = await page.getByTestId('a0-shell').getAttribute('data-inactive-seconds')
    expect(during).toBe(before)
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => false }) })
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, page.getByText('ASK THE ARCHIVIST · explanations and recovery', { exact: true }), 'KEYBOARD')
    await activate(page, button(page, 'RESET TO CASE START'), 'KEYBOARD')
    await expect(page.getByTestId('case-terminal')).toHaveAttribute('data-terminal-stage', '3')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expect(page.getByRole('button', { name: 'STAGE Which DAI movements match the incident window?', exact: true })).toBeVisible()
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R1 objective directs to the file before collection and the terminal after', async ({ page }) => {
    const data = await setup(page, 102)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await expect(page.getByTestId('case-terminal')).toBeVisible()
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'KEYBOARD')
    await expect(page.locator('.objective-card')).toContainText('USE THE TERMINAL. BEGIN THE INVESTIGATION.')
    await expect(page.locator('.objective-card')).not.toContainText('FIND THE OFFICIAL CASE FILE.')
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('network-blocked static play makes zero provider calls', async ({ page }) => {
    const external: string[] = []
    page.on('request', (request) => { if (violatesFrozenBrowserPolicy(request.url())) external.push(request.url()) })
    const data = await setup(page, 95)
    data.freeze()
    await office(page, 'KEYBOARD', 'CURIOUS_EXPLORER')
    await expect(page.getByTestId('case-terminal')).toBeVisible()
    expect(external).toEqual([])
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })
})
