import { expect, test } from '@playwright/test'
import { activate, button, drainBrowserSpeech, enterTerminalFromWorld, expandDetails, office, setup } from '../fixtures/s2/browser-helpers'
import { violatesFrozenBrowserPolicy } from '../fixtures/browser-policy'
test.use({ hasTouch: true })
test.setTimeout(180_000)

// S9-P1-R3 Story full-state seam: persistent open-empty toolbox, note-read
// milestone, and BACK_READ-gated optional office-note side lead.
test.describe('S9-P1-R3 toolbox and note-read seam', () => {
  test('R19 toolbox OPEN retains open-empty outputs and repeats cannot duplicate', async ({ page }) => {
    const data = await setup(page, 121)
    data.freeze()
    await office(page, 'MOUSE_TOUCH', 'DIRECT_SOLVER')
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('verb-open'), 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('inventory-small-toolbox-closed'), 'MOUSE_TOUCH')
    await drainBrowserSpeech(page, 'MOUSE_TOUCH')
    await expect(page.getByTestId('inventory-small-toolbox-open-empty')).toBeVisible()
    await expect(page.getByTestId('inventory-hammer')).toBeVisible()
    await expect(page.getByTestId('inventory-nails')).toBeVisible()
    await expect(page.getByTestId('inventory-small-toolbox-closed')).toHaveCount(0)
    await expect(page.locator('.inventory-slot:not(.empty)')).toHaveCount(10)
    await activate(page, page.getByTestId('verb-open'), 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('inventory-small-toolbox-open-empty'), 'MOUSE_TOUCH')
    await drainBrowserSpeech(page, 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('verb-use'), 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('inventory-small-toolbox-open-empty'), 'MOUSE_TOUCH')
    await drainBrowserSpeech(page, 'MOUSE_TOUCH')
    await expect(page.getByTestId('inventory-hammer')).toHaveCount(1)
    await expect(page.getByTestId('inventory-nails')).toHaveCount(1)
    await expect(page.locator('.inventory-slot:not(.empty)')).toHaveCount(10)
    await activate(page, page.getByTestId('verb-look-at'), 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('inventory-small-toolbox-open-empty'), 'MOUSE_TOUCH')
    await drainBrowserSpeech(page, 'MOUSE_TOUCH')
    await expect(page.getByTestId('inventory-small-toolbox-open-empty')).toBeVisible()
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R19 USE path matches OPEN and the ten-item maximum stays reachable at 200% zoom', async ({ page }) => {
    const data = await setup(page, 122)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'KEYBOARD')
    await activate(page, page.getByTestId('verb-use'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-small-toolbox-closed'), 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('inventory-small-toolbox-open-empty')).toBeVisible()
    await expect(page.getByTestId('inventory-hammer')).toBeVisible()
    await expect(page.getByTestId('inventory-nails')).toBeVisible()
    await activate(page, page.getByTestId('verb-use'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-hammer'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-piggy-bank-intact'), 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await activate(page, page.getByTestId('verb-look-at'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-fictional-token-note'), 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'BACK_READ')
    const ten = ['inventory-approved-stamped-terminal-authorization-form', 'inventory-broken-feather-pen', 'inventory-euler-case-file', 'inventory-rubber-band', 'inventory-rubiks-cube', 'inventory-sharknado-2-vhs', 'inventory-small-toolbox-open-empty', 'inventory-hammer', 'inventory-nails', 'inventory-fictional-token-note']
    await expect(page.locator('.inventory-slot:not(.empty)')).toHaveCount(10)
    for (const slot of ten) {
      await expect(page.getByTestId(slot)).toBeVisible()
      await page.getByTestId(slot).focus()
      await expect(page.getByTestId(slot)).toBeFocused()
    }
    await page.evaluate(() => { document.body.style.zoom = '200%' })
    for (const slot of ten) await expect(page.getByTestId(slot)).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 2)).toBe(true)
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R20-R22 smashing without reading exposes no side lead; BACK_READ exposes exactly one', async ({ page }) => {
    const data = await setup(page, 123)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'KEYBOARD')
    await activate(page, page.getByTestId('verb-open'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-small-toolbox-closed'), 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await activate(page, page.getByTestId('verb-use'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-hammer'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-piggy-bank-intact'), 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('inventory-fictional-token-note')).toBeVisible()
    await expect(page.getByTestId('inventory-hammer')).toBeVisible()
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await page.getByText('OPEN PERSISTENT CASEBOARD', { exact: true }).click()
    await expect(page.getByText('OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE', { exact: true })).toHaveCount(0)
    await expect(page.getByTestId('side-lead-panel')).toHaveCount(0)
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'KEYBOARD')
    await activate(page, page.getByTestId('verb-look-at'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-fictional-token-note'), 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'BACK_READ')
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expandDetails(page, 'KEYBOARD', 'OPEN PERSISTENT CASEBOARD')
    await expandDetails(page, 'KEYBOARD', 'OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE')
    await expect(page.getByTestId('side-lead-panel')).toBeVisible()
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveCount(1)
    await page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ }).click()
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveAttribute('aria-pressed', 'true')
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'KEYBOARD')
    await activate(page, page.getByTestId('verb-look-at'), 'KEYBOARD')
    await activate(page, page.getByTestId('inventory-fictional-token-note'), 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expandDetails(page, 'KEYBOARD', 'OPEN PERSISTENT CASEBOARD')
    await expandDetails(page, 'KEYBOARD', 'OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE')
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveCount(1)
    await page.getByText('ASK THE ARCHIVIST · explanations and recovery', { exact: true }).click()
    await activate(page, button(page, 'RESET TO CASE START'), 'KEYBOARD')
    await expect(page.getByTestId('case-terminal')).toHaveAttribute('data-terminal-stage', '3')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expandDetails(page, 'KEYBOARD', 'OPEN PERSISTENT CASEBOARD')
    await expandDetails(page, 'KEYBOARD', 'OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE')
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveCount(1)
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R23 plain-list presentation preserves the seam with zero provider calls', async ({ page }) => {
    const external: string[] = []
    page.on('request', (request) => { if (violatesFrozenBrowserPolicy(request.url())) external.push(request.url()) })
    const data = await setup(page, 124)
    data.freeze()
    await office(page, 'MOUSE_TOUCH', 'DIRECT_SOLVER')
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('verb-open'), 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('inventory-small-toolbox-closed'), 'MOUSE_TOUCH')
    await drainBrowserSpeech(page, 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('verb-use'), 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('inventory-hammer'), 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('inventory-piggy-bank-intact'), 'MOUSE_TOUCH')
    await drainBrowserSpeech(page, 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('verb-look-at'), 'MOUSE_TOUCH')
    await activate(page, page.getByTestId('inventory-fictional-token-note'), 'MOUSE_TOUCH')
    await drainBrowserSpeech(page, 'MOUSE_TOUCH')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'BACK_READ')
    await enterTerminalFromWorld(page, 'MOUSE_TOUCH')
    await page.getByText('Presentation and accessibility', { exact: true }).click()
    await page.getByLabel('Terminal presentation').selectOption('PLAIN_LIST')
    await activate(page, button(page, 'BACK TO CASE'), 'MOUSE_TOUCH')
    await activate(page, button(page, 'ASK A QUESTION'), 'MOUSE_TOUCH')
    await expandDetails(page, 'MOUSE_TOUCH', 'OPEN PERSISTENT CASEBOARD')
    await expandDetails(page, 'MOUSE_TOUCH', 'OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE')
    await expect(page.getByTestId('case-terminal')).toContainText('LATE-BOUND TOKEN (integration gate pending)')
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveCount(1)
    expect(await page.getByTestId('case-terminal').innerText()).not.toMatch(/Powered by Nansen API.*LATE-BOUND|LATE-BOUND.*Powered by Nansen API/)
    expect(external).toEqual([])
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })
})
