import { expect, test, type Page } from '@playwright/test'
import { activate, button, drainBrowserSpeech, enterTerminalFromWorld, expandDetails, office, setup } from '../fixtures/s2/browser-helpers'
import { violatesFrozenBrowserPolicy } from '../fixtures/browser-policy'
test.use({ hasTouch: true })
test.setTimeout(180_000)

// S9-P1-R4 real note-completion contact: BACK_READ fires only at the final
// required acknowledgment of the player-paced reading, in every input path.
async function smashPiggy(page: Page, input: 'MOUSE_TOUCH' | 'KEYBOARD') {
  await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), input)
  await activate(page, page.getByTestId('verb-open'), input)
  await activate(page, page.getByTestId('inventory-small-toolbox-closed'), input)
  await drainBrowserSpeech(page, input)
  await activate(page, page.getByTestId('verb-use'), input)
  await activate(page, page.getByTestId('inventory-hammer'), input)
  await activate(page, page.getByTestId('inventory-piggy-bank-intact'), input)
  await drainBrowserSpeech(page, input)
  await expect(page.getByTestId('inventory-fictional-token-note')).toBeVisible()
  await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
}

async function lookAtNote(page: Page, input: 'MOUSE_TOUCH' | 'KEYBOARD') {
  await activate(page, page.getByTestId('verb-look-at'), input)
  await activate(page, page.getByTestId('inventory-fictional-token-note'), input)
}

async function acknowledge(page: Page, expected: '1' | '2' | 'gone') {
  const panel = page.getByTestId('speech-panel')
  const shell = page.getByTestId('a0-shell')
  await expect(panel).toContainText('final copy')
  for (let attempt = 0; attempt < 8; attempt++) {
    const note = await shell.getAttribute('data-note-read')
    const done = expected === 'gone'
      ? (await panel.count()) === 0 && note === 'BACK_READ'
      : (await panel.count()) > 0 && (await panel.getAttribute('data-line-index')) === expected && note === 'UNREAD'
    if (done) return
    if ((await panel.count()) === 0) break
    await panel.evaluate((element: HTMLButtonElement) => element.click())
    await page.waitForTimeout(300)
  }
  if (expected === 'gone') await expect(panel).toHaveCount(0)
  else await expect(panel).toHaveAttribute('data-line-index', expected)
}

test.describe('S9-P1-R4 note-completion contact', () => {
  test('R4 keyboard paced reading stays UNREAD until the final acknowledgment', async ({ page }) => {
    const data = await setup(page, 131)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await smashPiggy(page, 'KEYBOARD')
    await lookAtNote(page, 'KEYBOARD')
    await expect(page.getByTestId('speech-panel')).toBeVisible()
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    // Paced proof: the first line is still revealing (not instant).
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-talking', 'ROOK')
    const shell = page.getByTestId('a0-shell')
    const settledPress = async () => {
      await expect(shell).toHaveAttribute('data-talking', 'NONE')
      // The speech panel is a focused button: blur first so Space keyup cannot
      // click it into a second advancement. Each press must advance exactly once.
      await page.evaluate(() => { if (document.activeElement instanceof HTMLElement) document.activeElement.blur() })
      await page.keyboard.press('Space')
      await page.waitForTimeout(400)
    }
    await settledPress()
    expect(await shell.getAttribute('data-note-read')).toBe('UNREAD')
    await settledPress()
    expect(await shell.getAttribute('data-note-read')).toBe('UNREAD')
    await expect(page.getByTestId('speech-panel')).toBeVisible()
    await settledPress()
    await expect(page.getByTestId('speech-panel')).toHaveCount(0)
    await expect(shell).toHaveAttribute('data-note-read', 'BACK_READ')
    await expect(page.getByTestId('inventory-fictional-token-note')).toBeVisible()
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expandDetails(page, 'KEYBOARD', 'OPEN PERSISTENT CASEBOARD')
    await expandDetails(page, 'KEYBOARD', 'OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE')
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveCount(1)
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R4 instant text still requires every advancement', async ({ page }) => {
    const data = await setup(page, 132)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await smashPiggy(page, 'KEYBOARD')
    await lookAtNote(page, 'KEYBOARD')
    await acknowledge(page, '1')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await acknowledge(page, '2')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await expect(page.getByTestId('speech-panel')).toBeVisible()
    await acknowledge(page, 'gone')
    await expect(page.getByTestId('speech-panel')).toHaveCount(0)
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'BACK_READ')
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R4 touch path agrees on the staged contact', async ({ page }) => {
    const data = await setup(page, 133)
    data.freeze()
    await office(page, 'MOUSE_TOUCH', 'DIRECT_SOLVER')
    await smashPiggy(page, 'MOUSE_TOUCH')
    await lookAtNote(page, 'MOUSE_TOUCH')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await acknowledge(page, '1')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await acknowledge(page, '2')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await expect(page.getByTestId('speech-panel')).toBeVisible()
    await acknowledge(page, 'gone')
    await expect(page.getByTestId('speech-panel')).toHaveCount(0)
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'BACK_READ')
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R4 plain-list presentation preserves the neutral seam', async ({ page }) => {
    const data = await setup(page, 134)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await smashPiggy(page, 'KEYBOARD')
    await lookAtNote(page, 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'BACK_READ')
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expandDetails(page, 'KEYBOARD', 'OPEN PERSISTENT CASEBOARD')
    await expandDetails(page, 'KEYBOARD', 'OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE')
    await expect(page.getByTestId('case-terminal')).toContainText('LATE-BOUND TOKEN (integration gate pending)')
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveCount(1)
    expect(await page.getByTestId('case-terminal').innerText()).not.toContain('FICTIONAL_OFFICE_NOTE')
    expect(await page.getByTestId('case-terminal').innerText()).not.toContain('No Nansen provenance exists')
    expect(await page.getByTestId('case-terminal').innerText()).toContain('late-bound for a later integration gate')
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R4 in-progress reading keeps the terminal closed and the lead hidden', async ({ page }) => {
    const data = await setup(page, 137)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await smashPiggy(page, 'KEYBOARD')
    await lookAtNote(page, 'KEYBOARD')
    await expect(page.getByTestId('speech-panel')).toBeVisible()
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await expect(button(page, 'OPEN CASE TERMINAL')).toHaveCount(0)
    await expect(page.getByTestId('case-terminal')).toHaveCount(0)
    await page.getByTestId('speech-panel').click()
    await page.waitForTimeout(400)
    await expect(page.getByTestId('speech-panel')).toBeVisible()
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await expect(button(page, 'OPEN CASE TERMINAL')).toHaveCount(0)
    await page.getByTestId('speech-panel').click()
    await page.waitForTimeout(400)
    await expect(page.getByTestId('speech-panel')).toBeVisible()
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await expect(button(page, 'OPEN CASE TERMINAL')).toHaveCount(0)
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R4 reload before completion cannot invent the lead and makes zero provider calls', async ({ page }) => {
    const external: string[] = []
    page.on('request', (request) => { if (violatesFrozenBrowserPolicy(request.url())) external.push(request.url()) })
    const data = await setup(page, 135)
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await smashPiggy(page, 'KEYBOARD')
    await lookAtNote(page, 'KEYBOARD')
    await expect(page.getByTestId('speech-panel')).toBeVisible()
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await page.reload()
    await expect(page.getByTestId('a0-shell')).toBeVisible()
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-phase', 'START')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'UNREAD')
    await expect(page.getByTestId('case-terminal')).toHaveCount(0)
    expect(external).toEqual([])
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })

  test('R4 repeat read, RESET_CASE, and reopen cannot duplicate or lose the lead', async ({ page }) => {
    const data = await setup(page, 136)
    data.freeze()
    await office(page, 'KEYBOARD', 'DIRECT_SOLVER')
    await smashPiggy(page, 'KEYBOARD')
    await lookAtNote(page, 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'BACK_READ')
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expandDetails(page, 'KEYBOARD', 'OPEN PERSISTENT CASEBOARD')
    await expandDetails(page, 'KEYBOARD', 'OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE')
    await page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ }).click()
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveAttribute('aria-pressed', 'true')
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'KEYBOARD')
    await lookAtNote(page, 'KEYBOARD')
    await drainBrowserSpeech(page, 'KEYBOARD')
    await expect(page.getByTestId('a0-shell')).toHaveAttribute('data-note-read', 'BACK_READ')
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expandDetails(page, 'KEYBOARD', 'OPEN PERSISTENT CASEBOARD')
    await expandDetails(page, 'KEYBOARD', 'OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE')
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveCount(1)
    await page.getByText('ASK THE ARCHIVIST · explanations and recovery', { exact: true }).click()
    await activate(page, button(page, 'RESET TO CASE START'), 'KEYBOARD')
    await expect(page.getByTestId('case-terminal')).toHaveAttribute('data-terminal-stage', '3')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expandDetails(page, 'KEYBOARD', 'OPEN PERSISTENT CASEBOARD')
    await expandDetails(page, 'KEYBOARD', 'OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE')
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveCount(1)
    await activate(page, button(page, 'RETURN TO RECORDS OFFICE'), 'KEYBOARD')
    await enterTerminalFromWorld(page, 'KEYBOARD')
    await activate(page, button(page, 'BACK TO CASE'), 'KEYBOARD')
    await activate(page, button(page, 'ASK A QUESTION'), 'KEYBOARD')
    await expandDetails(page, 'KEYBOARD', 'OPEN PERSISTENT CASEBOARD')
    await expandDetails(page, 'KEYBOARD', 'OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE')
    await expect(page.getByTestId('case-terminal').getByRole('button', { name: /LATE-BOUND TOKEN/ })).toHaveCount(1)
    expect(data.requests.filter((request) => request.forbidden)).toEqual([])
  })
})
