import fs from 'node:fs'
import {execFileSync} from 'node:child_process'
import assert from 'node:assert/strict'
import {sha,canonical} from '../nq5-s2/activity.mjs'
import {BASE,TREE,CONTENT,IMPLEMENTATION,compileContent} from './compile-content.mjs'
const out='artifacts/g6p-s4/',put=(n,x)=>{fs.mkdirSync(out+n.slice(0,n.lastIndexOf('/')),{recursive:true});fs.writeFileSync(out+n,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n')},old=n=>execFileSync('git',['show',BASE+':'+n],{maxBuffer:128000000}),read=n=>JSON.parse(fs.readFileSync(n))
assert.equal(execFileSync('git',['rev-parse',BASE+'^{tree}'],{encoding:'utf8'}).trim(),TREE)
const root='public/scenarios/euler-2023-false-exit/',names=['scenario.json','provenance.json','catalog.json','scenario.sha256','world.json','evidence-graph.json','omitted-events.json']
const files=names.map(n=>({file:root+n,beforeSha256:sha(old(root+n)),afterSha256:sha(fs.readFileSync(root+n)),changed:!old(root+n).equals(fs.readFileSync(root+n))}))
assert.deepEqual(files.filter(x=>x.changed).map(x=>x.file),['scenario.json','provenance.json','catalog.json','scenario.sha256'].map(n=>root+n))
const before=JSON.parse(old(root+'scenario.json')),after=read(root+'scenario.json'),expected=structuredClone(before);expected.truthConclusion=['THE FIRST TRAIL JOINED THE SECOND ROUTE.',before.truthConclusion.at(-1)]
assert.equal(canonical(after),canonical(expected))
const provenance=read(root+'provenance.json'),previousProvenance=JSON.parse(old(root+'provenance.json'));previousProvenance.scenarioHash=provenance.scenarioHash
assert.equal(canonical(provenance),canonical(previousProvenance))
const catalog=read(root+'catalog.json'),previousCatalog=JSON.parse(old(root+'catalog.json'));previousCatalog.entries.find(e=>e.id===after.scenarioId).scenarioHash=provenance.scenarioHash
assert.equal(canonical(catalog),canonical(previousCatalog));assert.equal(fs.readFileSync(root+'scenario.sha256','utf8'),provenance.scenarioHash.replace('sha256:','')+'\n')
const crosswalk={status:'PASS',authority:'S4_EXACT_CONCLUSION_COPY_ONLY',files,beforeConclusion:before.truthConclusion,afterConclusion:after.truthConclusion,beforeScenarioIdentity:JSON.parse(old(root+'provenance.json')).scenarioHash,afterScenarioIdentity:provenance.scenarioHash,evidenceChronologyPrecisionGradesBoundariesSolverPreserved:true,graphWorldOmissionsByteIdentical:true,firstFalsifierUtc:'2023-03-13T11:38:11Z',historicalSealedReferenceHashesNotRewritten:true}
put('REPORTS/TRUTH_HASH_CROSSWALK.json',crosswalk)
const laneManifest=read('docs/source/execution-s4/LANE_A_ACCEPTED_PACKAGE/handoff/IMPLEMENTATION_MANIFEST.json'),patchPaths=[...fs.readFileSync('docs/source/execution-s4/LANE_A_ACCEPTED_PACKAGE/handoff/lane-a-exact.patch','utf8').matchAll(/^diff --git a\/(.+) b\/(.+)$/gm)].map(m=>m[1])
assert.equal(patchPaths.length,37)
const sourceManifest=fs.readFileSync('docs/source/execution-s4/LANE_A_ACCEPTED_PACKAGE/MANIFEST.sha256','utf8'),pins=new Map(sourceManifest.trim().split('\n').map(l=>[l.slice(66),l.slice(0,64)]))
const laneFiles=patchPaths.map(file=>{assert.equal(sha(fs.readFileSync(file)),pins.get(file));return {file,sha256:pins.get(file),byteIdenticalToAcceptedLaneA:true}})
const compiled=compileContent();assert.equal(canonical(compiled),canonical(read('src/controller/content/runtime-content.json')))
put('REPORTS/LANE_A_ADMISSION.json',{status:'PASS',patchSha256:sha(fs.readFileSync('docs/source/execution-s4/LANE_A_ACCEPTED_PACKAGE/handoff/lane-a-exact.patch')),additivePaths:37,interfaceIdentity:compiled.interfaceIdentity,implementationIdentity:IMPLEMENTATION,contentIdentity:CONTENT,laneFiles,legacyImplementationManifestUnchanged:true,manifestFiles:laneManifest.files.length})
const frozen='artifacts/g6p-s3/REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json';assert.equal(sha(fs.readFileSync(frozen)),'9a68312148dab31784c7e8221ff7db2bc9f87424e969d1169159aa91df75b90f')
const compatible=read(frozen).compatibility.preservedBytes.map(x=>x.file),exceptions=new Set(['src/app/App.tsx','src/app/CaseTerminalWorkbench.tsx','src/adventure/content.ts',...files.filter(x=>x.changed).map(x=>x.file)])
const preserve=[...compatible.filter(n=>!exceptions.has(n)),frozen,'src/adventure/reducer.ts','src/investigation/fixture.ts','src/investigation/state.ts','src/investigation/query.ts','src/game/compiler/compile.ts',...fs.readdirSync('artifacts/g6p-s2-r1/REPORTS').map(n=>'artifacts/g6p-s2-r1/REPORTS/'+n)]
const preservedFiles=[...new Set(preserve)].map(file=>{assert.ok(old(file).equals(fs.readFileSync(file)),file);return {file,sha256:sha(fs.readFileSync(file))}})
put('REPORTS/PRESERVATION.json',{status:'PASS',reviewedStart:BASE,reviewedTree:TREE,preservedFiles,explicitS4CopyOrIntegrationExceptions:[...exceptions].sort(),frozenCorpusIdentity:'4c9d93c8b9b97503df4580ee72f8d19c7515a9ed29dad54d558cb258bd2c3e60',supplierSelfFrozen:false,MAINFrozenBySeparateReceipt:true,accountingUnchanged:true,runtimeProviderCalls:0,LaneCPathsChanged:0})
put('REPORTS/INTEGRATION_INVENTORY.json',{status:'CONTROLLER_FOUNDATION_PENDING_MAIN_REVIEW',catalogsAccepted:8,authoringEntries:409,compiledEntries:compiled.compiledEntries,optionalIncluded:false,exactLiteralIncluded:false,consumers:{opening:'src/adventure/content.ts officeLines before player-paced queue',stableBeats:'src/adventure/narrative.ts cue construction',usefulRuleCopy:'src/adventure/content.ts after existing reducer item/phase guards',deadEnds:'src/adventure/content.ts officeDeadEnd after reducer useful-rule precedence',publicAlias:'src/app/App.tsx publicSpeaker/display ARIA only',results:'src/app/CaseTerminalWorkbench.tsx zeroResultCopy with actual replay and discovered scope',recovery:'src/app/CaseTerminalWorkbench.tsx recoveryCopy over exact successful legacy announcements',method:'src/app/CaseTerminalWorkbench.tsx methodHintCopy',ledger:'src/app/CaseTerminalWorkbench.tsx bound fixture/provenance metadata unchanged'},controllerAdapter:'src/controller/content/adapter.ts',deferred:['Evidence-bound exact authoring hints and proof dialogue','Optional acting/banter and final density','Lane C/frozen corpus gameplay wiring','Pixel/journey/AT/contrast/release acceptance'],internalId:'archivist',legacyAliasesPreserved:['MR_INDEX','mr-index','mrIndex'],publicName:'Arthur',publicStyling:'Arthur the Archivist',centralReducersUnchanged:true,authoringCatalogRuntimeImport:false,providerRequests:0,packetsSent:false})
console.log(JSON.stringify({status:'PASS',acceptedLaneAdditions:37,compiledEntries:compiled.compiledEntries,truthChangedFiles:4,frozenCorpusDataChanged:false,accountingBytesPreserved:true}))
