import { CANONICAL_SECTIONS, type CaseFixture, type QuestionLens } from './contracts'
import { availableCards, folderStatus, knownRecords, openQuestion, recommendations, threadChecks, threadStatus, visibleClues, type InvestigationState } from './state'
import { canonicalQuery, queryReceipt, querySentence } from './query'
import { evidenceAtlas } from './atlas'

export const LENSES: QuestionLens[] = ['ACTIVITY', 'RELATIONSHIPS', 'STATE', 'RECEIPT']
const CHECKS = ['CHRONOLOGY', 'SOURCE_DESTINATION', 'ASSET_OR_PROVEN_TRANSFORMATION', 'AMOUNT_RELATIONSHIP', 'EXACT_RELATIONSHIP', 'CUTOFF']
const DIMENSIONS = ['TIME', 'DIRECTION', 'ASSET', 'AMOUNT', 'RELATIONSHIP', 'EVIDENCE_GRADE', 'COVERAGE', 'EXACT_RECEIPT_AVAILABILITY']
const acceptance = { status: 'PENDING_LEAD_REVIEW', note: 'Compiled implementation contract; not Lead acceptance, final copy, or art binding.' }

// This projection is the only discovery-bearing input to catalog compilation.
export function visibleInvestigation(fixture: CaseFixture, state: InvestigationState) {
  return { clues: visibleClues(fixture, state), records: knownRecords(fixture, state), recommendations: recommendations(fixture, state), cards: availableCards(fixture, state), atlas: evidenceAtlas(fixture, state) }
}

export function compileRuntimeCatalogs(fixture: CaseFixture, state: InvestigationState) {
  if (fixture.mode !== 'ACCEPTED_FROZEN' || fixture.id !== 'EULER_2023_FALSE_EXIT' || state.fixtureId !== fixture.id) throw new Error('Supplied Euler catalogs cannot assert acceptance of a synthetic scenario.')
  const visible = visibleInvestigation(fixture, state)
  const common = { scenario_id: fixture.id, lead_acceptance: acceptance }
  const cards = visible.cards
  const selectedClue = visible.clues.find((clue) => clue.sourceRecordIds.includes(state.selectedRecordId ?? ''))
  const thread = { id: 'THREAD.FIRST_TRAIL', nodes: visible.records.filter((record) => state.pinned.includes(record.id)).map((record) => ({ record_id: record.id, checks: threadChecks(fixture, state, record) })), gaps: state.exactEventIds.length ? [] : [{ id: 'GAP.CONTINUITY', open_question: openQuestion(fixture, state) }], continuity_checks: CHECKS, working_theory_id: state.workingTheory, status: threadStatus(fixture, state) }
  const folders = (state.result?.folders ?? []).map((folder) => {
    const record = visible.records.find((item) => item.id === folder.recordId)
    if (!record) throw new Error('Undiscovered result cannot enter a catalog.')
    return { id: folder.id, summary: folder.summary, why_matched: folder.whyMatched, evidence_grade: folder.grade, case_status: folderStatus(state, record), may_support: [folder.maySupport], cannot_prove: [folder.cannotProve], next_question_ids: folder.nextQuestionIds, source_record_ids: [folder.recordId], sort_reason: folder.sortReason, public_source_available: true }
  })
  const receipt = queryReceipt(fixture, state.query)
  const clues = {
    ...common, schema_version: '2.0.0',
    question_lenses: LENSES.map((lens) => ({ id: lens, player_question: cards.find((card) => card.lens === lens)?.question ?? `What can the ${lens.toLowerCase()} lens establish?`, purpose: `Bounded ${lens.toLowerCase()} investigation`, primary_data_family_ids: [lens === 'STATE' ? 'profiler/address/historical-balances' : lens === 'RELATIONSHIPS' ? 'profiler/address/counterparties' : lens === 'RECEIPT' ? 'transaction-with-token-transfer-lookup' : 'profiler/address/transactions'], can_establish: [lens === 'RECEIPT' ? 'An independently verified exact event.' : lens === 'STATE' ? 'Bounded corroboration; derived state is not independent evidence.' : 'Observed activity within retrieved scope.'], cannot_establish: [fixture.proof.boundary] })),
    clues: visible.clues.map((clue) => ({ id: clue.id, label: clue.label, role: clue.role, state_model: ['LOCKED', 'DISCOVERED', 'AVAILABLE', 'APPLIED', 'RELATED', 'PINNED', 'ARCHIVED'], value_type: clue.filters.some((filter) => filter.field === 'TRANSACTION') ? 'TRANSACTION_HASH' : clue.category === 'WHEN' ? 'TIME_WINDOW' : clue.category === 'WHAT_MOVED' ? 'TOKEN' : 'OTHER', discovery_source: clue.sourceRecordIds.join(', '), unlock_event: clue.unlockEvent, supported_dimensions: [...new Set(clue.filters.map((filter) => filter.field))], exact_value_source: clue.sourceRecordIds.join(', '), display_value_template: clue.filters.map((filter) => `${filter.field}: ${filter.value}`).join('; '), apply_without_typing: true, non_consumable: true, source_evidence_ids: clue.sourceRecordIds, compatible_question_card_ids: cards.filter((card) => card.prerequisites.includes(clue.id)).map((card) => card.id), world_actions: { look_at: 'Explain discovered values and source.', use_with_terminal: 'STAGE_CLUE', give_to_archivist: 'HINT', use_with_caseboard: 'PIN discovered source record' }, preferred_performance: { intention: 'INSPECT', optional: true, fallback: 'TEXT' } })),
    question_cards: cards.map((card) => ({ id: card.id, stage: card.stage, question_lens: card.lens, question: card.question, why_suggested: card.why, prerequisite_clue_ids: card.prerequisites, filter_effects: card.effects, result_class: card.resultClass, can_establish: [card.mayEstablish], cannot_establish: [card.cannotEstablish], next_question_rule: card.nextRule, data_family_ids: [card.family], recommendation_rank: Math.min(3, Math.max(1, visible.recommendations.findIndex((item) => item.id === card.id) + 1)), lead_promoted: false })),
    query_recipes: cards.map((card) => ({ id: `RECIPE.${card.id.slice(5)}`, class: card.stage === 'VERIFY' ? 'EXACT_VERIFICATION' : card.lens === 'STATE' ? 'STATE_COMPARISON' : card.id === 'CARD.COMPARE_ROUTES' ? 'ROUTE_COMPARISON' : card.stage === 'TEST' ? 'CANDIDATE_TEST' : 'GUIDED', question_lens: card.lens, investigative_question_id: card.questionId, plain_language_question: card.question, minimum_sufficient_clue_ids: card.prerequisites.length ? card.prerequisites : [selectedClue?.id ?? 'CLUE.START'], canonical_filter_ast: canonicalQuery({ lens: card.lens, questionId: card.questionId, filters: card.effects.map((filter) => ({ ...filter, origin: 'QUESTION_CARD', sourceId: card.id })) }), equivalent_input_paths: ['TERMINAL_DISPATCH', 'PHYSICAL_PLUNGER'], dispatch_requirement: 'MANDATORY', success_effect: card.stage === 'VERIFY' ? 'VERIFIES_EXACT' : card.lens === 'STATE' ? 'CORROBORATES' : 'CREATES_CANDIDATES', caseboard_effect: card.stage === 'VERIFY' ? 'CLOSE_THREAD_GAP' : card.lens === 'STATE' ? 'ADD_CORROBORATION' : 'ADD_CANDIDATE', coverage_requirement: 'Retrieved accepted corpus only; complete scoped coverage required for negative claims.', lead_promoted: false })),
  }
  const terminal = {
    ...common, schema_version: '2.0.2', presentation: { modes: ['FULLSCREEN_CRT', 'DOCKED_OVERLAY', 'PLAIN_LIST'], first_run_default: 'FULLSCREEN_CRT', single_state_model: true, single_accessibility_tree: true }, sections: [...CANONICAL_SECTIONS], section_semantics: { ask_location: 'CASE', explore_role: 'CASE_CORPUS_EXPLORATION', ledger_role: 'RESEARCH_LEDGER_AND_CALL_ATLAS', archive_is_canonical_section: false },
    caseboard: { known_facts: visible.records.map((record) => record.id), open_question: { text: openQuestion(fixture, state) }, trace_thread: thread, working_theory: state.workingTheory ? { id: state.workingTheory, fact: false } : null, proof_slots: ['AMOUNT', 'RECEIVER', 'LINK'], rejected_theory: state.rejectedTheory }, question_lenses: LENSES,
    query_tray: { drawers: ['STARTING_POINT', 'WHEN', 'WHAT_MOVED', 'CHECK'], drawers_are_optional_categories: true, case_sentence: querySentence(state.query), technical_ast_available: true, filter_provenance_visible: true, pre_dispatch_query_receipt: { plain_question: querySentence(state.query), active_filters: state.query.filters.map((filter) => `${filter.field}: ${filter.value} (${filter.origin}: ${filter.sourceId})`), question_lens: state.query.lens, coverage_scope: receipt.coverageScope, expected_result_class: receipt.expectedResultClass, no_hidden_filter_mutation: true } },
    query_model: { critical_path_operator: 'AND', canonicalization: JSON.stringify(canonicalQuery(state.query)), query_states: ['BROAD', 'FOCUSED', 'CANDIDATE', 'EXACT'], no_privileged_click_order: true, undo_redo_reset: true, locked_clue_no_leak: true },
    dispatch_model: { runtime_provider_calls: 0, equivalent_paths: ['TERMINAL_DISPATCH', 'PHYSICAL_PLUNGER'], max_mandatory_dispatches: 3, direct_solver_may_use_fewer: true, optional_local_queries_unlimited: true, query_receipt_required_before_dispatch: true },
    result_model: { default_presentation: 'CANDIDATE_FOLDERS', max_foreground_candidates: 3, folders: ['MATCHES', 'SAVED_LEADS', 'RULED_OUT', 'PROOF'], zero_result_classes: ['NO_MATCH_IN_ACCEPTED_CORPUS', 'NEGATIVE_EVIDENCE_SUPPORTED', 'QUERY_OUTSIDE_COVERAGE'], proof_event_idempotent: true, evidence_delta: { previous_count: state.result?.delta.previousCount ?? 0, new_count: state.result?.delta.newCount ?? 0, included_reason: state.result?.delta.includedReason ?? 'No dispatch yet.', excluded_reason_available: true, first_excluding_predicate_available: true } },
    comparison_model: { max_candidates: 2, factual_dimensions: DIMENSIONS, no_confidence_score: true, accessible_table: true },
    accessibility: { input_modes: ['MOUSE_TOUCH', 'KEYBOARD', 'SCREEN_READER'], no_typing_critical_path: true, no_drag_critical_path: true, no_color_only_meaning: true, no_timed_input: true, zoom_percent: 200, focus_restore: true, live_announcements: true, semantic_alternatives: true, query_receipt_announced: true, evidence_delta_announced: true },
    runtime_boundary: { static_keyless: true, provider_calls: 0, private_raw_in_build: false, same_origin_assets_only: true, deterministic_summaries: true },
  }
  const proof = {
    ...common, schema_version: '2.0.0', corpus_metrics: { fixture_mode: fixture.mode, total_records: fixture.records.length, discovered_records: visible.records.length, new_campaign_calls: fixture.ledger.curatedAcceptedCalls },
    route_candidates: folders.map((folder) => ({ id: `ROUTE.${folder.id.slice(7)}`, summary: folder.summary, source_record_ids: folder.source_record_ids, evidence_grade: folder.evidence_grade, initial_case_status: folder.case_status, why_matched: folder.why_matched, may_support: folder.may_support, cannot_prove: folder.cannot_prove, trace_thread_role: folder.evidence_grade === 'CORROBORATING' ? 'CORROBORATION' : state.exactEventIds.includes(`EXACT.${folder.source_record_ids[0]}`) ? 'PROOF' : 'CANDIDATE_LINK', first_test_question_ids: folder.next_question_ids, lead_promoted: false })),
    dead_end_candidates: state.rejectedTheory ? [{ id: 'DEADEND.FALSE_TERMINAL', archetype: 'FALSE_TERMINAL', why_plausible: 'A candidate terminal is not proof that the trail stopped.', player_knowledge_required: [fixture.openingRecordId], source_call_ids: [visible.records.find((record) => record.id === state.rejectedTheory?.firstContradiction)?.provenance.lineage ?? ''], source_record_ids: [state.rejectedTheory.firstContradiction], first_falsifier: { record_id: state.rejectedTheory.firstContradiction, predicate: 'Accepted exact relationship at 11:38:11 UTC.' }, method_lesson: 'Seek an exact continuation before inferring a stop.', claim_boundary: fixture.proof.boundary, lead_promoted: false }] : [],
    hint_candidates: ['METHOD_HINT', 'CASE_HINT', 'DIRECT_HINT'].map((tier) => ({ id: `HINT.${tier}`, tier, trigger: 'Explicit player request; only current discovered state.', text_key: `TODO.LEAD_COPY.${tier}`, no_undiscovered_value: true })),
    success_predicates: visible.records.filter((record) => Object.values(fixture.proof.slots).includes(record.id)).map((record) => ({ id: `PREDICATE.${record.id}`, predicate_class: 'EXACT_PROOF', required_evidence_ids: [record.id], required_evidence_grade: 'EXACT', caseboard_effect: 'File only after independent exact predicate validation.', idempotent: true, claim_boundary: fixture.proof.boundary })),
    final_assembly: { slots: ['AMOUNT', 'RECEIVER', 'LINK'], contextual_may_fill: false, conclusion: fixture.proof.conclusion, conclusion_boundary: fixture.proof.boundary },
  }
  const results = { ...common, schema_version: '1.0.0', candidate_folders: folders, comparison_trays: state.comparison.length === 2 ? [{ id: 'COMPARE.ACTIVE', candidate_folder_ids: state.comparison.map((id) => `FOLDER.${id}`), dimensions: DIMENSIONS, accessible_table: true, next_question_ids: ['QUESTION.EXACT_RECEIPT'] }] : [], trace_threads: [thread] }
  return { clues, terminal, proof, results }
}
