import fs from 'node:fs'
import path from 'node:path'
import assert from 'node:assert/strict'
import {sha} from '../nq5-s2/activity.mjs'
import {clipIdentityDefinition,clipDefinitionSha256,capabilityIdentityDefinition,capabilityContentSha256,canonicalIdentitySerialization} from '../../src/controller/foundation/pixel-identity.mjs'
import {testArtIndex} from '../../tests/fixtures/s5/art-index.ts'
import {validateIntake} from '../../src/controller/foundation/contracts.mjs'
const out=process.argv[2]||'artifacts/g6p-s5-r1/REPORTS',put=(n,x)=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,n),JSON.stringify(x,null,2)+'\n')}
const index=testArtIndex();validateIntake(index)
put('PRESERVATION.json',{...JSON.parse(fs.readFileSync('artifacts/g6p-s5/REPORTS/PRESERVATION.json')),reviewedSourcePrerequisite:'0d39031a746f09f5fd2d984c96585daf3b34a2d8',reviewedSourceTree:'fbf58344223f1e0d95d96b5e9fbd80147e41fb8d',majorS5SubsystemsAcceptedInSubstanceNotPromoted:true,viewportAnd24BeatBlueprintChanges:0,LaneCOwnedEdits:['src/app/corpus-presentation/CorpusPresentation.tsx · optional display-safe SOURCE callback only']})
const clipDefinition=clipIdentityDefinition(index.clips[0],index.assets),capabilityDefinition=capabilityIdentityDefinition(index.capabilities[0],index.assets,index.clips)
assert.equal(sha(canonicalIdentitySerialization(clipDefinition)),clipDefinitionSha256(index.clips[0],index.assets));assert.equal(sha(canonicalIdentitySerialization(capabilityDefinition)),capabilityContentSha256(index.capabilities[0],index.assets,index.clips))
put('IDENTITY_CROSSWALK.json',{status:'COMPUTED_SYNTHETIC_EXAMPLE_NOT_PRINCIPAL_APPROVAL',algorithm:'UTF8_CANONICAL_JSON_SORTED_OBJECT_KEYS_ORDERED_ARRAYS_SHA256',identityVersion:'1.0.0',clipDefinition,clipCanonicalSerialization:canonicalIdentitySerialization(clipDefinition),computedClipSha256:index.clips[0].sha256,excludedClipAttestations:['sha256','approvalReceiptId'],capabilityDefinition,capabilityCanonicalSerialization:canonicalIdentitySerialization(capabilityDefinition),computedCapabilityIdentity:index.capabilities[0].contentIdentity,excludedCapabilityClassification:['id','required','contentIdentity'],requiredDuplicateGate:'Exact independently computed capability content identity; id/required classification excluded so renaming a required realization does not evade detection.',PrincipalApprovalGranted:false,PNGDecodingOrApprovalReceiptAuthentication:false})
put('INPUT_ADMISSION.json',{status:'PASS',inputArchiveSha256:'db120aa0f9e33fb9238817a14989df0cea27265397b4edb753e7838825343395',inputArchiveBytes:13283,safeUniqueRegularMembers:8,suppliedVerifier:'PASS_BEFORE_IMPLEMENTATION',reviewedStart:{commit:'0d39031a746f09f5fd2d984c96585daf3b34a2d8',tree:'fbf58344223f1e0d95d96b5e9fbd80147e41fb8d',parent:'e902652ca4520087041b23ae1969e09c998fd64d'},indexAndTrackedTreeCleanBeforeSourceChanges:true,primaryHeadBefore:'0f52131c9f56f49128e7a413396331917e687a1f',primaryStatusBefore:[' M AGENTS.md'],trustedAgentsBlobBefore:'270516dcb62db311bf184283dbbaada9739d6f26',protectedPrimaryAgentsRead:false,inputs:fs.readdirSync('docs/source/execution-s5-r1/INPUT').sort().map(file=>{const b=fs.readFileSync('docs/source/execution-s5-r1/INPUT/'+file);return{file,bytes:b.length,sha256:sha(b)}})})
put('SINGLE_EXPLORE_CROSSWALK.json',{status:'ONE_CANONICAL_SEMANTIC_BROWSE_MODEL',search:'Search accepted display text',filterAndGroup:'Original admitted Lane C browse(view,query) only',reset:'Reset local filters',count:'Unique semantic records visible of25; bounded-no-match subset of7, not exact Hero fixture or raw event totals',canonicalTotal:25,boundedNoMatch:7,legacyPeerControlsRemoved:['Case Corpus','Search discovered records','Manual filters from known values','EXPLORE.MANUAL','SHOW MORE CORPUS RECORDS','corpusRecords/search/corpusCount local state'],stateOwnership:{semanticBrowse:'Mounted admitted CorpusPresentation maintains exactly one query across modes and SOURCE roundtrip; hidden outside EXPLORE.',displaySelection:'Controller-owned display-only SemanticCard selection bound to exact current fixture reference. Does not dispatch SELECT_RESULT or stage any proof.',exactHero:'Existing shared reducer owns discoveries/QueryReceipt/RESULTS/Caseboard/TraceThread/exactSOURCE/proof; unchanged.'},sourceProvenance:'Display/concept/question/coverage/named-consumer references and claim limits only; no audit body resolution; independently discovered Hero SOURCE stays separate.',LaneCOwnedEdit:{file:'src/app/corpus-presentation/CorpusPresentation.tsx',scope:'Optional onInspect callback + controller-only native button, no model/authority/filter/count change; absent in unchanged lane harness.',regeneratedLaneCPacketRequired:true},minimalExistingBrowserMigrations:[{file:'tests/e2e/nq5-r1-parity.spec.ts',change:'Replace removed Case Corpus visibility locator with admitted semantic sea visibility plus explicit legacy-peer absence; keep original test/case-workflow assertions.'},{file:'tests/fixtures/s2/browser-helpers.ts',change:'Migrate the inherited CURIOUS_EXPLORER visibility locator to admitted semantic sea plus explicit legacy-peer absence. Preserve every original comparison, ledger, proof and return assertion.'}],frozenBlueprintBeats:24,proofEligibleFromSemanticDisplay:false,syntheticCanonicalAuthority:false,presentationModes:['FULLSCREEN_CRT','DOCKED_OVERLAY','PLAIN_LIST'],finalArtTitleDensity:'LATE_BOUND'})
console.log(JSON.stringify({status:'PASS',reports:3,deterministic:true,canonicalSemanticRecords:25,clipIdentity:index.clips[0].sha256,capabilityIdentity:index.capabilities[0].contentIdentity,PrincipalApprovalGranted:false}))
