import fs from 'node:fs'
import assert from 'node:assert/strict'
import {sha} from '../nq5-s2/activity.mjs'
import {verify,EXTRA} from './verify.mjs'
const bind=files=>[...new Set(files)].sort().map(file=>({file,sha256:sha(fs.readFileSync(file))}))
const unit=fs.readFileSync('artifacts/g6p-s5-r1/LOGS/unit-identity-final.log','utf8'),browser=fs.readFileSync('artifacts/g6p-s5-r1/LOGS/browser-single-explore-built.log','utf8')
assert.ok(unit.includes('72 passed')&&unit.includes('EXIT_CODE=0'));assert.ok(browser.includes('3 passed')&&browser.includes('EXIT_CODE=0'))
const preservation=await verify(),common={status:'PASS_CLOSED_TASK_OWNED_FINDINGS',independent:false,genuineBugbot:false,reviewKind:'BOUNDED_DISCLOSED_SAME_AGENT_ADVERSARIAL_FALLBACK',genuineBugbotAvailability:'No callable Bugbot/code-review service found in active tool metadata; no extra task/plugin/subagent/message created to simulate independence.',MAINAcceptanceGranted:false,PrincipalVisualApprovalGranted:false,observedAtUtc:new Date().toISOString(),preservation,
 focusedUnitEvidence:{file:'artifacts/g6p-s5-r1/LOGS/unit-identity-final.log',sha256:sha(unit),tests:72,newIdentityTests:42,existingFoundationTests:30},
 singleExploreBrowserEvidence:{file:'artifacts/g6p-s5-r1/LOGS/browser-single-explore-built.log',sha256:sha(browser),tests:3}}
const review1={...common,checkpoint:1,scope:'Clip/capability computed identities, stale approval inheritance, canonical serialization and referenced realization semantics.',
 checks:['SHA standard/Unicode/multiblock vectors agree with Node crypto','JSON key order canonical; frame/contact/ownership/clip order preserved','Declared sha/approvalReceiptId excluded; every material clip field and referenced geometry/hash/version bound','28 stale-hash material clip mutations each fail computed identity before any stale receipt can confer validity','Capability arbitrary hash/order/content/static/fallback semantics mutations fail','Renamed duplicate required realization fails computed-content duplicate gate','Legitimate changed definition needs new identity and cannot keep old simulated receipt','Synthetic consistency receipts are not actual Principal approval; governed example approvals empty'],
 taskOwnedFindingsClosed:[{finding:'Referenced asset placement metadata could affect realization without changing PNG bytes',correction:'Bind version/kind/canvas/channels/baseline/anchor/bounds/palette/material metadata in frame and static fallback identities; add two tests.'}],
 residuals:['Actual PNG decoding/recipe completeness/approval-provenance authentication and visual fit require future real-archive admission','No production asset/capability/profile or final art binding'],
 implementationBindings:bind(EXTRA.filter(n=>n.startsWith('src/controller/')||n.startsWith('tests/unit/')||n.startsWith('tests/fixtures/')||n.startsWith('artifacts/')))}
const review2={...common,checkpoint:2,scope:'Single EXPLORE grammar, context vs exact Hero authority, immutable preservation, bounded packet and package recovery policy.',
 checks:['Exactly one canonical admitted sea; legacy search/count/filter/pagination markers absent','Optional Lane C renderer callback only; no model or authority changes','Displayed source selection never dispatches SELECT_RESULT or proof staging','Semantic query stays mounted across modes/SOURCE roundtrip; fixture-reference guard prevents stale canonical authority','Hero selection clears context; original Caseboard/RESULTS/SOURCE/proof dispatch paths remain separate','Original parity and inherited curious-journey helper locators migrate to admitted sea with explicit legacy absence; no case/proof assertion removed','Input verifier and both VULNERABLE baselines passed before source changes','Supplied corrected reproducers remain unchanged and their expected-negative exits are asserted','37/74/25/seven/truth/B-F01/B-F02/480x270/24beat exact preservation','Primary path/status only; accepted HEAD remains0f and candidate trusted AGENTS blob matches','New incremental bundle prerequisite must be reviewed unpromoted0d, with no historical merge/ZIP','Both minimum targeted packets PREPARED_NOT_SENT and not full-tree recovery claims'],
 taskOwnedFindingsClosed:[{finding:'Lint found state-clearing UI wrapper in original auto receipt-review effect',correction:'Original external dispatcher used directly for REVIEW_RECEIPT; no rule/proof guard disabled.'},{finding:'Count-template replacement altered embedded corpus hash',correction:'Pre-seal audit restores exact source SHA; no corpus source change.'},{finding:'First final package stopped on inherited curious-journey legacy locator; packaging audit identified stale evidence/screenshot paths',correction:'Migrate only the visibility locator with explicit legacy absence, preserve every proof assertion, include helper in both targeted packets, copy R1 reports and fresh original-path screenshots. Retain first-attempt logs and rerun exact sealed recovery.'}],
 finalDeliveryExtensionRequired:'Exact candidate/tree/diff/bundle/fsck/object privacy, fresh1626 unit and62 browser tests, deterministic report and packet bytes, targeted recovery,12 tamper rejects and ZIP roundtrip/determinism are asserted by final sealed execution and its separate evidence; this checkpoint does not claim independent MAIN acceptance.',
 implementationBindings:bind([...EXTRA.filter(n=>!n.startsWith('src/controller/')&&!n.startsWith('tests/unit/')&&!n.startsWith('tests/fixtures/')&&!n.startsWith('artifacts/')),...fs.readdirSync('scripts/nq5-s5-r1').map(n=>'scripts/nq5-s5-r1/'+n),...['IDENTITY_SPECIFICATION.md','LEAD_NOTES.md','STOPPED_ATTEMPTS.md','BASELINE_CAPTURE_BINDINGS.json'].map(n=>'docs/source/execution-s5-r1/'+n)])}
for(const[n,x]of [['REVIEW_1.json',review1],['REVIEW_2.json',review2]])fs.writeFileSync('artifacts/g6p-s5-r1/REPORTS/'+n,JSON.stringify(x,null,2)+'\n')
console.log(JSON.stringify({status:'PASS',boundedCheckpoints:2,independent:false,genuineBugbot:false,MAINAcceptanceGranted:false,PrincipalVisualApprovalGranted:false}))
