import {identity,validateSchema} from '../nq5/schema.mjs'
import {prepare} from './context.mjs'
import {seal} from './authority.mjs'
import {validateRequest,TGM,COUNTER,CLAIMS} from './admission.mjs'
import {auditSchema} from './audit.mjs'
import {entries} from './model.mjs'
import {preparedPlans} from './prepared.mjs'
// No mutable artifact cache is read here. Trusted public factories plus the
// governed Main-reproduced prelive metadata never certify current durable state.
export function unknownAudit(c){const audit=structuredClone(c.prior.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json']);audit.p2BreadthReview={p1LeadAcceptanceReceiptIdentity:c.receipt.hash,officialSourceIdentity:c.admission.official.identity,planIdentity:c.plans.plan.hash,acceptedIndexIdentity:identity(c.index),historicalAcceptedIndexIdentity:identity(c.prior.objects['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json']),leadAcceptedCount:18,newFormalLeadAcceptances:0};audit.p2Records=c.plans.plan.requests.map(q=>({request:q,requestIdentity:identity(q),coverageIdentity:q.coverageIdentity,policyIdentity:q.publicProjectionPolicyIdentity,auditIdentity:q.auditIdentity,attempts:[],disposition:'UNPROVEN_RUNTIME_STATE',localSupportCandidate:false,runtimeEvidenceProven:false,leadAccepted:false,normalizedSha256:null,resultCount:null,emptyResultRole:null,claimBoundaries:CLAIMS,attribution:'Powered by Nansen API',terminalIdentity:null}));validateSchema('provider',audit,auditSchema(c));return audit}
export function blocked(root){const c=prepare(root),n=preparedPlans(root);c.plans=n.plans;if(n.p1LeadAcceptanceReceiptIdentity!==c.receipt.hash||n.acceptedIndexIdentity!==identity(c.index)||c.plans.plan.officialSourceIdentity!==c.admission.official.identity)throw new Error('P2_UNKNOWN_FACTORY_GOVERNED_METADATA_BINDINGS');for(const q of c.plans.plan.requests)validateRequest(q,c.admission);c.sources=[];c.oldTransferIdentities=[];const audit=unknownAudit(c),report={schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',reason:'P2_CURRENT_DURABLE_EVIDENCE_UNPROVEN',campaignId:c.receipt.campaignId,runtimeEvidenceProven:false,priorVerifiedLedgerSha256:c.receipt.immutableLedgerSha256,priorVerifiedLedgerBytes:c.receipt.immutableLedgerBytes,priorVerifiedAttempts:23,priorVerifiedProvider2xx:23,priorVerifiedSupplierTerminals:21,priorVerifiedKnownCredits:27,leadAcceptedBeforeP2:18,leadAcceptedAfterP2:18,publicAcceptedIndexRows:18,permanentlyHeldSupplierTerminals:3,ledgerSha256:null,ledgerBytes:null,httpAttempts:null,provider2xx:null,supplierCountedTerminals:null,newAttempts:null,newKnownCredits:null,newLocalSupportCandidates:null,newDistinctRequests:null,knownCampaignCredits:null,retries:null,unresolvedReservations:null,unresolvedReservedCredits:null,unresolvedTerminals:null,clean:false,allPrimaryMirrorRawEqual:null,historicalTwentyThreeAttemptsResponsesTerminalsAndMirrorsUnchanged:null,latestSafeResponseBalance:null,protectedReserve:250,accountWideDecrease:null,campaignAttributedCredits:null,unattributedAccountWideChange:null,causeAssigned:false,acceptedPublicIndexIdentity:identity(c.index),requestAuditIdentity:identity(audit),actualPrivateStateAccess:true,actualPrivateStateScope:'POST_REPLAY_ATTEMPTED_CURRENT_STATE_UNPROVEN',credentialAccess:null,privateMutation:null,authenticatedCampaignProviderRequests:null,authenticatedCampaignProviderRequestsByFamily:{[TGM]:null,[COUNTER]:null},unauthenticatedDocumentationGets:c.admission.official.index.unauthenticatedDocumentationGets,accountRequests:0,browserRuntimeProviderRequests:0,P3_AUTHORIZED_TO_ISSUE:false,AUTHORIZED_TO_ISSUE:false},execution={stopReason:report.reason,newAttempts:null,newActualCredits:null,newLocalSupportCandidates:null,unresolvedReservedCredits:null,maximumInFlight:null,canaryRequests:8,canaryMeasurementStatus:'UNPROVEN',noReplacement:true,no65thRequest:true,P3Requests:0},executionEnvelope=seal({schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',reason:report.reason,candidate:c.source.candidate,implementationSha256:c.source.implementationSha256,planIdentity:c.plans.plan.hash,p1LeadAcceptanceReceiptIdentity:c.receipt.hash,currentRuntimeEnvelopeProven:false,AUTHORIZED_TO_ISSUE:false});return entries(c,{audit,report,projections:[],state:null,execution},{post:true,executionEnvelope,status:'BLOCKED_WITH_EVIDENCE'})}
