import fs from 'node:fs'
import path from 'node:path'
import {identity,sha,validateSchema} from '../nq5/schema.mjs'
import {parseExactJson} from '../nq5/exact-json.mjs'
import {loadAccepted} from '../nq5-b1/authority.mjs'
import {configuredCampaignRoots} from '../nq5-r3/genesis.mjs'
import {readMirrored} from '../nq5-b1/store.mjs'
import {assertPrivateAncestry,assertRawInventory} from '../nq5-b1-r3/gate-proof.mjs'
import {OLD_LOCKS,LOCK as P1_LOCK} from '../nq5-p1/context.mjs'
import {accepted as acceptedB4} from '../nq5-p1/authority.mjs'
import {normalize as p1Normalize,tuple,TGM,WINDOW,HASHES} from '../nq5-p1/admission.mjs'
import {signedTransfers} from '../nq5-b1-r3-r2/signed-flow.mjs'
import {temporal,acceptedTruth} from '../nq5-b1-r3/compatibility.mjs'
import {B2_IDS,ISSUE_ORDER} from '../nq5-b3/authority.mjs'
import {accepted,source,cut,digest,seal,LEDGER_SHA,LEDGER_BYTES,BASE_ROWS,LOCK} from './authority.mjs'
import {acceptP1} from './acceptance.mjs'
import {captured} from './docs.mjs'
import {contracts} from './admission.mjs'
import {abstraction,validateAbstraction} from './corpus.mjs'
import {freeze} from './planner.mjs'
import {historicalPlans} from './prepared.mjs'
import {replay} from './ledger.mjs'
import {validateDeployments} from './infrastructure.mjs'
export const BASE_LOCKS=[...OLD_LOCKS,P1_LOCK]
const brands=new WeakMap()
export function historicalEnvelope(c){return {...c.originalEnvelope,executionOrder:[...c.originalEnvelope.executionOrder,...B2_IDS,...ISSUE_ORDER,...c.prior.objects['PLANS/T1_P1_MULTI_FAMILY_PILOT_PLAN.json'].executionOrder]}}
export function ledgerEnvelope(c){return {...historicalEnvelope(c),executionOrder:[...historicalEnvelope(c).executionOrder,...c.plans.plan.executionOrder]}}
export function prepare(root){const prior=accepted(root),a=acceptP1(root,prior),admission=contracts(captured(root),prior),b4=acceptedB4(root),scenarioBytes=fs.readFileSync(path.join(root,'public/scenarios/euler-2023-false-exit/scenario.json'));if(sha(scenarioBytes)!=='a8634ef0b76f3b53d2fa3c30ddb16a2e94aed7f34fd976b9ba2ef84cb4a114c1')throw new Error('P2_ACCEPTED_SCENARIO_CHANGED');const scenario=JSON.parse(scenarioBytes),truth=Object.fromEntries(HASHES.map(h=>{const x=scenario.evidence.find(e=>e.transactionHash===h&&e.grade==='EXACT'&&e.proofGrade==='EXACT_EVENT');if(!x)throw new Error('P2_EXACT_LAYER_SEPARATE');return [h,x.observedAtUtc]})),oldTruth=acceptedTruth(root),corpus=abstraction(admission,a.receipt,sha(scenarioBytes),{signedProfileIdentity:b4.objects['CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json'].hash,observedProfile:b4.objects['CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json']});validateAbstraction(corpus,truth);const originalEnvelope=loadAccepted(root).envelope,roots=configuredCampaignRoots().map(r=>path.join(r,a.receipt.campaignId));assertPrivateAncestry(roots);return {root,prior,b4,...a,admission,truth,oldTruth,corpus,originalEnvelope,roots,source:{candidate:cut(root),implementationSha256:digest(root)}}}
export function historicalSources(c,state){const sources=[],oldAudit=c.prior.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'],p=c.b4.objects['CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json'],o=c.b4.objects['CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json'];
 for(const publicRow of c.prior.objects['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json']){const r=oldAudit.records.find(r=>r.publicCallId===publicRow.public_call_id),body={chain:'ethereum',address:publicRow.coverage_key.subject_id,date:{...WINDOW},pagination:{page:1,per_page:100}},q={family:r?.family,path:r?.path,method:r?.method,body,logicalId:r?.logicalId},t=state.terminals.get(q.logicalId),a=t&&state.responses.get(q.logicalId+'.'+t.attempt);if(!r||q.family!=='profiler/address/transactions'||identity(body)!==publicRow.request_body_sha256||!t||t.disposition!=='SUCCESS_COUNTED'||t.publicRecord.qualification_sequence!==publicRow.supplier_qualification_sequence||!a||a.rawSha256!==publicRow.response_sha256||[2,3,4].includes(t.publicRecord.qualification_sequence))throw new Error('P2_EIGHT_PRIOR_LEAD_SOURCE_SCOPE');const b=readMirrored(c.roots,'raw-b1/'+a.rawName),exact=parseExactJson(b),response=JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(b));validateSchema('provider',response,o.compatibilitySchema);if(response.pagination.page!==1||response.pagination.per_page!==100||typeof response.pagination.is_last_page!=='boolean')throw new Error('P2_LEGACY_PAGINATION');const times=response.data.map(tx=>temporal(tx.block_timestamp,q,c.oldTruth.times[tx.transaction_hash.toLowerCase()])),n=signedTransfers(exact,q,times,p,a.providerRequestId);if(!n.pass||n.normalizedIdentity!==publicRow.normalized_sha256||n.normalizedRecords.length!==publicRow.result_count||t.normalizedSha256!==n.normalizedIdentity)throw new Error('P2_LEGACY_ACCEPTED_NORMALIZED_IDENTITY');sources.push({logicalId:q.logicalId,request:q,normalized:{rows:n.normalizedRecords,resultCount:n.normalizedRecords.length,normalizedSha256:n.normalizedIdentity,pagination:response.pagination},tokenContracts:n.tokenContracts,publicCallId:publicRow.public_call_id,leadAcceptanceOrder:publicRow.lead_acceptance_order,providerRequestId:a.providerRequestId,rawSha256:a.rawSha256})}
 const oldAdmission={tgm:c.prior.objects['CONTRACTS/TGM_TRANSFERS_OFFICIAL_CONTRACT_ADMISSION.json'],counter:c.prior.objects['CONTRACTS/ADDRESS_COUNTERPARTIES_OFFICIAL_CONTRACT_ADMISSION.json']};
 for(const accepted of c.receipt.acceptanceCrosswalk){const r=oldAudit.p1Records.find(r=>r.request.logicalId===accepted.logicalId),q=r.request,t=state.terminals.get(q.logicalId),a=t&&state.responses.get(q.logicalId+'.'+t.attempt);if(!t||t.disposition!=='SUCCESS_COUNTED'||t.auditDisposition!=='PASS'||t.publicRecord.qualification_sequence!==accepted.supplierSequence||t.publicRecord.public_call_id!==accepted.publicCallId||t.hash!==accepted.immutableTerminalIdentity||!a||a.providerRequestId!==accepted.providerRequestId||a.rawSha256!==accepted.rawSha256||a.httpStatus!==200||a.actualCredits!==q.expectedCredits||a.quotedCredits!==q.expectedCredits)throw new Error('P2_TEN_P1_PRIVATE_ACCEPTANCE');const n=p1Normalize(q,readMirrored(c.roots,'raw-b1/'+a.rawName),oldAdmission,c.truth);if(n.normalizedSha256!==accepted.normalizedSha256||n.resultCount!==accepted.resultCount||t.normalizedSha256!==n.normalizedSha256||t.resultCount!==n.resultCount||n.resultCount===0&&(!n.emptyRole||n.pagination.is_last_page!==true))throw new Error('P2_P1_RAW_PAIR_SUPPORT_NOT_REPRODUCED');sources.push({logicalId:q.logicalId,request:q,normalized:n,tokenContracts:q.family===TGM?[q.body.token_address]:[],publicCallId:accepted.publicCallId,leadAcceptanceOrder:accepted.leadAcceptanceOrder,providerRequestId:a.providerRequestId,rawSha256:a.rawSha256,acceptedRole:accepted.role})}
 if(sources.length!==18||new Set(sources.map(s=>s.logicalId)).size!==18)throw new Error('P2_EXACT_EIGHTEEN_ACCEPTED_SOURCES');return sources
}
export const fingerprint=c=>identity({root:c.root,source:c.source,roots:c.roots,originalEnvelope:c.originalEnvelope,priorObjects:c.prior.objects,priorBytes:Object.fromEntries(Object.entries(c.prior.bytes).map(([n,b])=>[n,sha(b)])),b4Objects:c.b4.objects,b4Bytes:Object.fromEntries(Object.entries(c.b4.bytes).map(([n,b])=>[n,sha(b)])),admission:{tgm:c.admission.tgm,counter:c.admission.counter,index:c.admission.official.index,bodies:Object.fromEntries(Object.entries(c.admission.official.bodies).map(([n,b])=>[n,sha(b)]))},receipt:c.receipt,index:c.index,pubSchema:c.pubSchema,corpus:c.corpus,truth:c.truth,oldTruth:c.oldTruth,sources:c.sources,plans:c.plans,baseProof:c.baseProof,oldTransferIdentities:c.oldTransferIdentities,state:{rows:c.state.rows,starts:[...c.state.starts],responses:[...c.state.responses],terminals:[...c.state.terminals],bytes:c.state.bytes,sha:c.state.bytesSha256}})
function inventory(c,{post=false}={}){assertPrivateAncestry(c.roots);const expected=[...BASE_LOCKS,'qualification.jsonl','raw-b1',...(post?[LOCK]:[])].sort().join();for(const r of c.roots)if(fs.readdirSync(r).sort().join()!==expected)throw new Error('P2_PRIVATE_ROOT_INVENTORY');return true}
export function baseline(root){source(root,{validate:true});validateDeployments(root);const c=prepare(root);inventory(c);c.state=replay(c.roots,historicalEnvelope(c),{maximumAddedAttempts:0});if(c.state.bytes!==LEDGER_BYTES||c.state.bytesSha256!==LEDGER_SHA||c.state.rows.length!==BASE_ROWS||c.state.starts.size!==23||c.state.responses.size!==23||c.state.terminals.size!==23)throw new Error('P2_EXACT_TWENTY_THREE_BASELINE');c.sources=historicalSources(c,c.state);c.oldTransferIdentities=[...new Set(c.sources.filter(s=>s.request.family!== 'profiler/address/counterparties').flatMap(s=>s.normalized.rows.map(tuple)))].sort();c.baseProof=seal({schemaVersion:'1.0.0',campaignId:c.receipt.campaignId,p1LeadAcceptanceReceiptIdentity:c.receipt.hash,acceptedP1ArchiveSha256:c.receipt.reviewedArchiveSha256,ledgerSha256:LEDGER_SHA,ledgerBytes:LEDGER_BYTES,ledgerRows:BASE_ROWS,oldLocks:Object.fromEntries(BASE_LOCKS.map(n=>[n,sha(readMirrored(c.roots,n))])),allTwentyThreeRawMirrorsEqual:true,allEighteenLeadAcceptedSemanticsReproduced:true,allTenP1ExactRawNormalizedProviderSupportReproduced:true,oldTransferIdentities:c.oldTransferIdentities,oldPerCallTransferRows:c.sources.filter(s=>s.request.family!== 'profiler/address/counterparties').reduce((n,s)=>n+s.normalized.resultCount,0),oldCounterpartyItems:0,acceptedSources:c.sources.map(s=>({logicalId:s.logicalId,publicCallId:s.publicCallId,leadAcceptanceOrder:s.leadAcceptanceOrder,providerRequestId:s.providerRequestId,rawSha256:s.rawSha256,normalizedSha256:s.normalized.normalizedSha256,resultCount:s.normalized.resultCount})),oldLastLedgerHash:c.state.rows.at(-1).hash});c.plans=freeze(c);brands.set(c,{fingerprint:fingerprint(c),plans:c.plans});return c}
export function assertBaseline(c,{privateState=false,post=false}={}){if(!brands.has(c)||brands.get(c).fingerprint!==fingerprint(c)||brands.get(c).plans!==c.plans||identity(c.source)!==identity({candidate:cut(c.root),implementationSha256:digest(c.root)}))throw new Error('P2_BRANDED_CURRENT_CONTEXT');assertPrivateAncestry(c.roots);const bytes=readMirrored(c.roots,'qualification.jsonl');if(bytes.length<LEDGER_BYTES||sha(bytes.subarray(0,LEDGER_BYTES))!==LEDGER_SHA)throw new Error('P2_PRIOR_LEDGER_PREFIX_CHANGED');for(const[n,h]of Object.entries(c.baseProof.oldLocks))if(sha(readMirrored(c.roots,n))!==h)throw new Error('P2_PRIOR_LOCK_CHANGED');if(privateState){inventory(c,{post});if(bytes.length!==LEDGER_BYTES||sha(bytes)!==LEDGER_SHA)throw new Error('P2_PRELIVE_LEDGER_NOT_UNCHANGED');const fresh=replay(c.roots,ledgerEnvelope(c),{maximumAddedAttempts:0});if(identity(fresh.rows)!==identity(c.state.rows))throw new Error('P2_PRELIVE_MAP_DRIFT');assertRawInventory(c.roots,[...fresh.responses.values()].map(r=>r.rawName))};return true}
export function persistBaseline(c){assertBaseline(c,{privateState:true});const dir=path.join(c.root,'artifacts/g6p-p2');fs.mkdirSync(dir,{recursive:true});const f=path.join(dir,'BASELINE_REVALIDATION.json');if(fs.existsSync(f)){if(identity(JSON.parse(fs.readFileSync(f)))!==identity(c.baseProof))throw new Error('P2_BASELINE_PROOF_NO_REWRITE')}else fs.writeFileSync(f,JSON.stringify(c.baseProof,null,2)+'\n',{flag:'wx',mode:0o600});return c.baseProof}
export function postContext(root,{independentP2Raw=false}={}){validateDeployments(root);const c=prepare(root),f=path.join(root,'artifacts/g6p-p2/BASELINE_REVALIDATION.json');c.baseProof=JSON.parse(fs.readFileSync(f));const{hash,...p}=c.baseProof;if(hash!==identity(p)||p.ledgerSha256!==LEDGER_SHA||p.ledgerBytes!==LEDGER_BYTES||p.p1LeadAcceptanceReceiptIdentity!==c.receipt.hash||!p.allTenP1ExactRawNormalizedProviderSupportReproduced)throw new Error('P2_POST_BASELINE_PROOF');inventory(c,{post:true});for(const[n,h]of Object.entries(p.oldLocks))if(sha(readMirrored(c.roots,n))!==h)throw new Error('P2_POST_PRIOR_LOCK');c.state=replay(c.roots,historicalEnvelope(c),{maximumAddedAttempts:0,prefixOnly:true});c.sources=historicalSources(c,c.state);const actualIds=[...new Set(c.sources.filter(s=>s.request.family!=='profiler/address/counterparties').flatMap(s=>s.normalized.rows.map(tuple)))].sort(),actualSources=c.sources.map(s=>({logicalId:s.logicalId,publicCallId:s.publicCallId,leadAcceptanceOrder:s.leadAcceptanceOrder,providerRequestId:s.providerRequestId,rawSha256:s.rawSha256,normalizedSha256:s.normalized.normalizedSha256,resultCount:s.normalized.resultCount}));if(identity(Object.keys(p.oldLocks).sort())!==identity([...BASE_LOCKS].sort())||identity(actualIds)!==identity(p.oldTransferIdentities)||identity(actualSources)!==identity(p.acceptedSources)||p.oldLastLedgerHash!==c.state.rows.at(-1).hash||p.ledgerRows!==BASE_ROWS||p.acceptedP1ArchiveSha256!==c.receipt.reviewedArchiveSha256||p.oldPerCallTransferRows!==c.sources.filter(s=>s.request.family!=='profiler/address/counterparties').reduce((n,s)=>n+s.normalized.resultCount,0)||p.oldCounterpartyItems!==0||p.allTwentyThreeRawMirrorsEqual!==true||p.allEighteenLeadAcceptedSemanticsReproduced!==true)throw new Error('P2_POST_BASELINE_ACTUAL_REDERIVATION');c.oldTransferIdentities=actualIds;c.plans=historicalPlans(root);c.state=replay(c.roots,ledgerEnvelope(c),{independentP2Raw});return c}
