import {identity} from '../nq5/schema.mjs'
import {seal,CONTRACT_SHA} from './authority.mjs'
import {TGM,COUNTER,HASHES} from '../nq5-p1/admission.mjs'
export const ROLES=['NEW_CONTEXTUAL_IDENTITY','CROSS_VIEW_CORROBORATION','FILTER_DEMONSTRATION','BOUNDED_NO_MATCH_COVERAGE','CANDIDATE_TEST','DEAD_END_TEST','CONTROL','PROVENANCE_RECONCILIATION','QUERY_RECIPE_VALIDATION','REGRESSION_FIXTURE']
export const CONCEPTS=['EXACT_RECEIPT','TRANSFER_EVENT','SUBJECT_ACTIVITY','RELATIONSHIP_SUMMARY','PROVENANCE_RECONCILIATION','CONTEXTUAL_CORROBORATION','CANDIDATE','DEAD_END','CONTROL','FILTER_DEMONSTRATION','BOUNDED_PROVIDER_QUERY_NO_MATCH','COVERAGE_CLOSURE','REGRESSION_FIXTURE']
export const PHASES=[
 {id:'BREACH_OPEN',from:'2023-03-13T08:45:00Z',to:'2023-03-13T09:15:00Z',anchorEvidence:['EXACT_EARLY_NET','EXACT_MAIN_RECEIVER'],teachingPurpose:'Compare initial accepted breach branches with bounded subject/direction queries; distinguish a token haystack from clue-bound receipts.'},
 {id:'ROUTE_DEVELOPMENT',from:'2023-03-13T09:15:00Z',to:'2023-03-13T11:38:10Z',anchorEvidence:['EXACT_MAIN_RECEIVER','EXACT_CONVERGENCE'],teachingPurpose:'Ask about contextual route development before the accepted convergence falsifier, without promoting contextual rows into proof.'},
 {id:'POST_FALSIFIER_TO_CUTOFF',from:'2023-03-13T11:38:11Z',to:'2023-03-13T12:15:00Z',anchorEvidence:['EXACT_CONVERGENCE','ACCEPTED_CASE_CUTOFF'],teachingPurpose:'Compare after-falsifier context with the historical cutoff; an empty provider cell is not evidence of escape or chain absence.'}
].map(p=>({...p,consumers:['CASEBOARD.P2.PHASE.'+p.id,'QUERY_RECEIPT.P2.PHASE.'+p.id,'EVIDENCE_DELTA.P2.PHASE.'+p.id,'TEST.P2.PHASE.'+p.id,'PROVENANCE.P2.PHASE.'+p.id]}))
const LIMITS=['NO_IDENTITY_OWNERSHIP_INTENT_CAUSATION_COMPLETENESS_OR_CHAIN_NEGATIVE_PROOF','NO_CONTEXTUAL_RECORD_PROMOTION_TO_EXACT_PROOF','NO_PROVIDER_TIME_REPLACEMENT_OF_ACCEPTED_EXACT_TIME','NO_RAW_BULK_LABEL_USD_TOKEN_AGGREGATE_PUBLIC_OUTPUT','NO_NEW_FOREGROUND_GAMEPLAY_INTEGRATION_ACCEPTANCE']
const destinations={caseCorpus:true,candidateFolder:true,deadEndControlView:true,SOURCE:true,LEDGER_CALL_ATLAS:true,tests:true,foregroundGameplay:false}
export function abstraction(admission,receipt,truthSha,legacy){const mappings=[
 {family:TGM,endpoint:admission.tgm.path,admissionIdentity:admission.tgm.hash,requestSchemaIdentity:identity(admission.tgm.requestSchema),responseSchemaIdentity:identity(admission.tgm.responseSchema),projectionPolicy:admission.tgm.projectionAllowlist,concepts:['TRANSFER_EVENT','SUBJECT_ACTIVITY','PROVENANCE_RECONCILIATION','CONTEXTUAL_CORROBORATION','FILTER_DEMONSTRATION','BOUNDED_PROVIDER_QUERY_NO_MATCH','COVERAGE_CLOSURE','REGRESSION_FIXTURE'],evidenceGrade:'CONTEXTUAL',temporalClass:'SERVER_FILTERED_UNZONED_OR_PROVIDER_ZONED_CONTEXTUAL',frontierPolicy:'NAMED_NON_HUB_LINEAGE_UTILITY_ONLY_NOT_RAW_ROWS_OR_HAYSTACK_CONTROLS'},
 {family:'profiler/address/transactions',endpoint:'/api/v1/profiler/address/transactions',admissionIdentity:legacy.signedProfileIdentity,compatibilitySchemaIdentity:legacy.observedProfile.compatibilitySchemaIdentity,observedProfileIdentity:legacy.observedProfile.hash,projectionPolicy:['transaction_hash','from_address','to_address','token_address','amount','evidence_grade','temporal_class','accepted_exact_utc','accepted_exact_time_source'],concepts:['SUBJECT_ACTIVITY','CONTEXTUAL_CORROBORATION','CANDIDATE','DEAD_END','CONTROL','REGRESSION_FIXTURE'],evidenceGrade:'CONTEXTUAL',temporalClass:'HISTORICAL_LEAD_OBSERVED_COMPATIBILITY_CONTEXTUAL',frontierPolicy:'HISTORICAL_LEAD_ACCEPTED_NON_HUB_ROW_LINEAGE_ONLY_NO_NEW_ADDRESS_TRANSACTIONS_REQUEST'},
 {family:COUNTER,endpoint:admission.counter.path,admissionIdentity:admission.counter.hash,requestSchemaIdentity:identity(admission.counter.requestSchema),responseSchemaIdentity:identity(admission.counter.responseSchema),projectionPolicy:['counterparty_address','interaction_count'],concepts:['RELATIONSHIP_SUMMARY','CONTROL','BOUNDED_PROVIDER_QUERY_NO_MATCH','COVERAGE_CLOSURE','REGRESSION_FIXTURE'],evidenceGrade:'CONTEXTUAL',temporalClass:'BOUNDED_RELATIONSHIP_AGGREGATE_CONTEXTUAL',frontierPolicy:'NONRECURSIVE_COUNTS_ONLY'},
 {family:'ACCEPTED_EULER_TRUTH',endpoint:'STATIC_ACCEPTED_EXACT_RECEIPTS_NOT_PROVIDER_CALL',admissionIdentity:truthSha,projectionPolicy:['accepted_exact_public_receipt_fields'],concepts:['EXACT_RECEIPT'],evidenceGrade:'EXACT',temporalClass:'SEPARATELY_ACCEPTED_EXACT_UTC_EVENT',frontierPolicy:'ONLY_ACCEPTED_PUBLIC_CASE_SEEDS_NOT_CONTEXTUAL_PROOF_PROMOTION'}];
 const contract=seal({schemaVersion:'1.0.0',executionContractSha256:CONTRACT_SHA,p1LeadAcceptanceReceiptIdentity:receipt.hash,minimumConceptTypes:CONCEPTS,stableUtilityRoles:ROLES,storyPhases:PHASES,endpointMappings:mappings,recordRequiredFields:['endpointFamily','endpointAdmissionIdentity','publicProjectionPolicyIdentity','question','lens','purpose','coverageKey','coverageCells','lineage','consumers','evidenceGrade','temporalClass','mayEstablish','cannotEstablish','frontierAuthority','destinationPermissions'],presentation:{RESULTS_EXPLORE:'ENDPOINT_INDEPENDENT_INVESTIGATION_CONCEPTS',SOURCE:'EXACT_ENDPOINT_SCHEMA_PROVENANCE_CLAIM_LIMITS',LEDGER_CALL_ATLAS:'ACQUISITION_COVERAGE_ACCOUNTING_REQUEST_AUDIT',complementarySchemasForcedIntoIdenticalFields:false,rawBulkPublic:false},claimLimits:LIMITS,exactTruthSeparate:true,integration:'SCHEMA_AND_ACQUISITION_SEMANTICS_ONLY_NOT_FOREGROUND_GAMEPLAY_ACCEPTANCE'});
 const matrix=seal({schemaVersion:'1.0.0',semanticAbstractionIdentity:contract.hash,rows:mappings.map(m=>({...m,destinationPermissions:{...destinations,foregroundGameplay:m.family==='ACCEPTED_EULER_TRUTH'?'EXISTING_ACCEPTED_STATIC_RECEIPT_ONLY_NO_NEW_ADMISSION':false},mayEstablish:m.evidenceGrade==='EXACT'?['EXISTING_ACCEPTED_CASE_RECEIPT_AND_FALSIFIER']:['BOUNDED_CONTEXTUAL_QUERY_VIEW','PREDECLARED_FILTER_COMPARISON_TEST_OR_PROVENANCE'],cannotEstablish:m.evidenceGrade==='EXACT'?['NEW_PROVIDER_CALL_OR_NEW_RECEIPT_ACCEPTANCE']:LIMITS})),acceptedExactHashes:HASHES,allNewProviderConceptsForegroundAccepted:false});return {contract,matrix}}
export function concept(q,n,abstractionIdentity){if(!q.utilityRoles.length||q.utilityRoles.some(r=>!ROLES.includes(r))||!q.consumers.length||!q.lineage.length)throw new Error('P2_CONSUMER_UTILITY_REQUIRED');const empty=!!n?.emptyRole,baseline=q.kind==='HAYSTACK_BASELINE',counter=q.family===COUNTER;const types=empty?['BOUNDED_PROVIDER_QUERY_NO_MATCH','COVERAGE_CLOSURE','FILTER_DEMONSTRATION']:counter?['RELATIONSHIP_SUMMARY','CONTROL']:baseline?['FILTER_DEMONSTRATION','CONTROL']:q.kind==='CONTEXTUAL_CANDIDATE'?[...(q.frontierAuthority===false?['CONTROL']:['CANDIDATE']),'CONTEXTUAL_CORROBORATION']:['TRANSFER_EVENT','SUBJECT_ACTIVITY','FILTER_DEMONSTRATION','CONTEXTUAL_CORROBORATION'];return {conceptId:'CORPUS.'+q.logicalId,semanticAbstractionIdentity:abstractionIdentity,conceptTypes:types,utilityRoles:[...new Set([...q.utilityRoles,...(empty?['BOUNDED_NO_MATCH_COVERAGE']:[])])],endpointFamily:q.family,endpointAdmissionIdentity:q.admissionIdentity,publicProjectionPolicyIdentity:q.publicProjectionPolicyIdentity,question:q.businessQuestion,lens:q.lens,purpose:q.purpose,coverageKey:q.coverageKey,coverageCells:q.coverageCells,lineage:q.lineage,consumers:q.consumers,evidenceGrade:'CONTEXTUAL',temporalClass:counter?'BOUNDED_RELATIONSHIP_AGGREGATE_CONTEXTUAL':'SERVER_FILTERED_UNZONED_OR_PROVIDER_ZONED_CONTEXTUAL',mayEstablish:empty?['PREDECLARED_BOUNDED_PROVIDER_QUERY_NO_MATCH']:['CONTEXTUAL_FILTER_VIEW_OR_CONSUMER_REGRESSION'],cannotEstablish:LIMITS,frontierAuthority:!baseline&&!counter&&q.frontierAuthority!==false,destinationPermissions:{...destinations,candidateFolder:!baseline&&!counter&&q.frontierAuthority!==false,deadEndControlView:baseline||counter||q.kind==='CONTEXTUAL_CANDIDATE'},publicOutputMode:baseline?'SAFE_AGGREGATE_COUNT_COVERAGE_METADATA_ONLY':'ADMITTED_SAFE_CONCEPT_AND_QUERY_METADATA_NO_RAW_BULK',normalizedIdentity:n?.normalizedSha256??null,resultCount:n?.resultCount??null,localSupportStatus:n?'PENDING_LEAD_REVIEW':'FROZEN_UTILITY_NOT_YET_MEASURED',claimBoundaries:LIMITS,attribution:'Powered by Nansen API',gameplayIntegrationAccepted:false}}
export function validateAbstraction(a,truth){if(identity(a.contract.storyPhases)!==identity(PHASES)||identity(a.contract.minimumConceptTypes)!==identity(CONCEPTS)||a.matrix.semanticAbstractionIdentity!==a.contract.hash||PHASES.length!==3||Date.parse(truth[HASHES.find(h=>h.startsWith('0xdae'))])!==Date.parse(PHASES[2].from)||HASHES.filter(h=>h.startsWith('0xc310')||h.startsWith('0x298b')).some(h=>Date.parse(truth[h])<Date.parse(PHASES[0].from)||Date.parse(truth[h])>Date.parse(PHASES[0].to)))throw new Error('P2_EXACT_STORY_PHASE_ANCHORS');return true}
