import fs from 'node:fs'
import path from 'node:path'
import {identity,sha} from '../nq5/schema.mjs'
import {get,PAGES,TERMS} from '../nq5-p1/docs.mjs'
import {assertPrivateAncestry} from '../nq5-b1-r3/gate-proof.mjs'
export const URLS={tgm:PAGES.tgm,counterparties:PAGES.counterparties,pricing:PAGES.pricing,rates:PAGES.rates,coverage:PAGES.coverage,redistribution:PAGES.redistribution,terms:TERMS}
function read(dir,name){assertPrivateAncestry([dir]);const file=path.join(dir,name),s=fs.lstatSync(file);if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1||s.uid!==process.getuid()||s.size>4000000)throw new Error('P2_DOCUMENT_METADATA');const fd=fs.openSync(file,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const b=fs.fstatSync(fd);if(s.ino!==b.ino||s.dev!==b.dev||s.size!==b.size)throw new Error('P2_DOCUMENT_RACE');const bytes=fs.readFileSync(fd),after=fs.fstatSync(fd);if(after.size!==b.size||after.mtimeMs!==b.mtimeMs)throw new Error('P2_DOCUMENT_RACE');return bytes}finally{fs.closeSync(fd)}}
export function captured(root){const dir=path.join(root,'docs/official/p2'),index=JSON.parse(read(dir,'INDEX.json')),encoded=JSON.parse(read(dir,'CAPTURED_DOCUMENT_BYTES.json'));if(encoded.encoding!=='UTF8_JSON_TEXT_EXACT_NO_NEWLINE_TRANSFORM'||index.scope!=='P2_EXACT_PLAN_SPECIFIC_DOCS_NO_SEARCH_NO_NEW_ASK'||index.newClarificationRequests!==0||index.credentialAccess!==false||index.authenticatedProviderRequests!==0||index.snapshots.length!==9||new Set(index.snapshots.map(s=>s.name)).size!==9)throw new Error('P2_DOCUMENT_SCOPE');const bodies={};for(const s of index.snapshots){const b=Buffer.from(encoded.bodies[s.name],'utf8');if(s.filename!==s.name+'.md'||s.sha256!==sha(b)||s.bytes!==b.length||!['index','clarification',...Object.keys(URLS)].includes(s.name)||URLS[s.name]&&URLS[s.name]!==s.url)throw new Error('P2_DOCUMENT_IDENTITY');bodies[s.name]=b};return {index,bodies,identity:identity(index)}}
export async function capture(root,prior){const old=prior.objects['OFFICIAL_DOCS/INDEX.json'],index={schemaVersion:'1.0.0',scope:'P2_EXACT_PLAN_SPECIFIC_DOCS_NO_SEARCH_NO_NEW_ASK',snapshots:[],unauthenticatedDocumentationGets:0,newClarificationRequests:0,clarificationRequests:1,reusedP1ClarificationRequests:1,credentialAccess:false,authenticatedProviderRequests:0,accountRequests:0,browserRuntimeRequests:0,priorP1OfficialSourceIdentity:identity(old),webDocumentationNavigationToolInvocations:0,webDocumentationPageNavigationOperations:0},bodies={};for(const s of old.snapshots){let b=prior.bytes['OFFICIAL_DOCS/'+s.filename],snapshot={...s,retrievalDisposition:'REUSED_BYTE_BOUND_P1_SNAPSHOT'};if(URLS[s.name]&&(Date.now()-Date.parse(s.retrievedAtUtc)>7200000||!Number.isFinite(Date.parse(s.retrievedAtUtc)))){index.unauthenticatedDocumentationGets++;const r=await get(URLS[s.name]);b=r.bytes;snapshot={name:s.name,url:URLS[s.name],retrievedAtUtc:r.retrievedAtUtc,httpStatus:r.httpStatus,filename:s.name+'.md',transport:r.transport,retrievalDisposition:'REFRESHED_EXACT_PLAN_SOURCE_WHEN_OLDER_TWO_HOURS'}}if(!Buffer.isBuffer(b))throw new Error('P2_PRIOR_OFFICIAL_BYTES_REQUIRED');bodies[s.name]=b.toString('utf8');index.snapshots.push({...snapshot,sha256:sha(b),bytes:b.length})};return {index,encoded:{encoding:'UTF8_JSON_TEXT_EXACT_NO_NEWLINE_TRANSFORM',bodies},identity:identity(index)}}
export function fresh(c){const d=captured(c.root);if(d.identity!==c.admission.official.identity)throw new Error('P2_CURRENT_DOCUMENT_BINDING');const required=['tgm','pricing','rates','coverage','redistribution','terms',...(c.admission.counter.status.startsWith('ADMITTED_')?['counterparties']:[])];for(const n of required){const s=d.index.snapshots.find(s=>s.name===n),age=Date.now()-Date.parse(s?.retrievedAtUtc);if(s?.httpStatus!==200||!Number.isFinite(age)||age<0||age>7200000)throw new Error('P2_DOCUMENT_FRESHNESS_REQUIRED')};return true}
