import fs from 'node:fs'
import path from 'node:path'
import {identity,sha,validateSchema} from '../nq5/schema.mjs'
import {readMirrored} from '../nq5-b1/store.mjs'
import {configuredCampaignRoots} from '../nq5-r3/genesis.mjs'
import {normalize} from '../nq5-p1/admission.mjs'
import {accepted,acceptanceRows,cut,digest,seal,source,BASE,TREE,ARCHIVE_SHA,CONTRACT_SHA,LEDGER_SHA,LEDGER_BYTES,LOCK,CORRECTION} from './authority.mjs'
import {assertAcceptanceIdentities} from './acceptance.mjs'
import {replay} from './ledger.mjs'
import {historicalEnvelope,BASE_LOCKS} from './context.mjs'
import {loadAccepted} from '../nq5-b1/authority.mjs'
import {assertPrivateAncestry} from '../nq5-b1-r3/gate-proof.mjs'
import {captured} from './docs.mjs'
import {contracts} from './admission.mjs'
import {abstraction} from './corpus.mjs'
import {accepted as acceptedB4} from '../nq5-p1/authority.mjs'
export const REASON='P2_HANDOFF_IMMUTABLE_SUPPLIER_PUBLIC_ID_CONFLICT'
export const serialize=x=>Buffer.isBuffer(x)?x:Buffer.from(typeof x==='string'?x:JSON.stringify(x,null,2)+'\n')
// A dedicated read-only blocker proof. No authorization, credential, provider
// transport, private writer, plan freeze or P3 issue capability exists here.
export function prove(root){if(fs.existsSync(path.join(root,CORRECTION)))throw new Error('P2_HISTORICAL_BLOCKER_SUPERSEDED_BY_USER_CORRECTION');const prior=accepted(root),rows=acceptanceRows(root),plan=prior.objects['PLANS/T1_P1_MULTI_FAMILY_PILOT_PLAN.json'];let blocked=false;try{assertAcceptanceIdentities(rows,plan)}catch(e){if(e.message!==REASON)throw e;blocked=true}if(!blocked)throw new Error('P2_BLOCKER_NO_LONGER_REPRODUCIBLE');
 const originalEnvelope=loadAccepted(root).envelope,roots=configuredCampaignRoots().map(r=>path.join(r,plan.campaignId)),c={prior,originalEnvelope};assertPrivateAncestry(roots);const inventory=[...BASE_LOCKS,'qualification.jsonl','raw-b1'].sort().join();for(const r of roots)if(fs.readdirSync(r).sort().join()!==inventory)throw new Error('P2_BLOCKER_PRIVATE_INVENTORY');const state=replay(roots,historicalEnvelope(c),{maximumAddedAttempts:0});if(state.bytes!==LEDGER_BYTES||state.bytesSha256!==LEDGER_SHA||state.rows.length!==69||state.starts.size!==23||state.responses.size!==23||state.terminals.size!==23)throw new Error('P2_BLOCKER_EXACT_BASELINE');
 const scenario=JSON.parse(fs.readFileSync(path.join(root,'public/scenarios/euler-2023-false-exit/scenario.json'))),truth=Object.fromEntries(scenario.evidence.filter(e=>e.grade==='EXACT'&&e.proofGrade==='EXACT_EVENT').map(e=>[e.transactionHash,e.observedAtUtc])),oldAdmission={tgm:prior.objects['CONTRACTS/TGM_TRANSFERS_OFFICIAL_CONTRACT_ADMISSION.json'],counter:prior.objects['CONTRACTS/ADDRESS_COUNTERPARTIES_OFFICIAL_CONTRACT_ADMISSION.json']};
 const crosswalk=rows.map(x=>{const record=prior.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'].p1Records.find(r=>r.request.logicalId===x.logicalId),q=record.request,t=state.terminals.get(q.logicalId),r=t&&state.responses.get(q.logicalId+'.'+t.attempt);if(!t||t.disposition!=='SUCCESS_COUNTED'||t.auditDisposition!=='PASS'||!r||r.providerRequestId!==x.providerRequestId||r.rawSha256!==x.rawSha256||r.httpStatus!==200||r.actualCredits!==q.expectedCredits||r.quotedCredits!==q.expectedCredits||t.hash!==record.terminalIdentity)throw new Error('P2_BLOCKER_P1_IDENTITY_SUPPORT');const n=normalize(q,readMirrored(roots,'raw-b1/'+r.rawName),oldAdmission,truth);if(n.normalizedSha256!==x.normalizedSha256||n.resultCount!==x.resultCount||t.normalizedSha256!==n.normalizedSha256||t.resultCount!==n.resultCount||n.resultCount===0&&(!n.emptyRole||!n.pagination.is_last_page))throw new Error('P2_BLOCKER_P1_SEMANTIC_SUPPORT');const actual=t.publicRecord.qualification_sequence;if(actual!==12+plan.executionOrder.indexOf(q.logicalId)||t.publicRecord.public_call_id!=='NQ5-'+String(actual).padStart(6,'0'))throw new Error('P2_BLOCKER_ARCHIVE_LEDGER_ORDER_CONFLICT');return {...x,requestedPublicCallId:x.publicCallId,requestedSupplierSequence:x.supplierSequence,immutablePublicCallId:t.publicRecord.public_call_id,immutableSupplierSequence:actual,immutableTerminalIdentity:t.hash,providerRawNormalizedResultAndCreditsMatch:true,identityConflict:actual!==x.supplierSequence||t.publicRecord.public_call_id!==x.publicCallId,correctionAuthorized:false}});
 if(crosswalk.filter(x=>x.identityConflict).length!==8)throw new Error('P2_BLOCKER_EXACT_EIGHT_CONFLICTS');
 const receipt=seal({schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',reason:REASON,disposition:'P1_BOUNDED_ROLE_ACCEPTANCE_DECLARED_BUT_EXACT_PUBLIC_ID_CROSSWALK_NOT_SEALED',executionContractSha256:CONTRACT_SHA,reviewedArchiveSha256:ARCHIVE_SHA,reviewedCandidate:{commit:BASE,tree:TREE},campaignId:plan.campaignId,p1PlanIdentity:plan.hash,p1RequestAuditIdentity:identity(prior.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json']),requestedLeadAcceptedTotal:18,publishedAcceptedIndexPreservedRows:8,requestedNewRoleAcceptances:10,conflictingIdentityRows:8,acceptanceCrosswalk:crosswalk,ledgerSha256:LEDGER_SHA,ledgerBytes:LEDGER_BYTES,allTwentyThreePrimaryMirrorRawPairsEqual:true,allTenP1SemanticsAndExactHashesReproduced:true,immutableHistoricalSupplierSequencesPreserved:true,newAcceptanceIndexPublished:false,credentialAccess:false,privateMutation:false,newProviderRequests:0,AUTHORIZED_TO_ISSUE:false});
 const official=captured(root),admission=contracts(official,prior),b4=acceptedB4(root),corpus=abstraction(admission,{...receipt,p1RequestAuditIdentity:receipt.p1RequestAuditIdentity},sha(fs.readFileSync(path.join(root,'public/scenarios/euler-2023-false-exit/scenario.json'))),{signedProfileIdentity:b4.objects['CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json'].hash,observedProfile:b4.objects['CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json']});
 const report={schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',reason:REASON,campaignId:plan.campaignId,ledgerSha256:state.bytesSha256,ledgerBytes:state.bytes,ledgerRows:69,httpAttempts:23,provider2xx:23,supplierCountedImmutableTerminals:21,requestedLeadAcceptedTotal:18,publishedAcceptedIndexRows:8,permanentlyHeldSupplierTerminals:3,knownCampaignCredits:27,retries:0,unresolvedReservations:0,unresolvedTerminals:0,newAttempts:0,newKnownCredits:0,newLocalSupportCandidates:0,allPrimaryMirrorRawEqual:true,allTenP1ExactSemanticsReproduced:true,immutableHistoryUnchanged:true,latestSafeResponseBalance:625031,balanceSource:'PRIOR_P1_SAFE_PROVIDER_RESPONSE_HEADER_NO_NEW_ACCOUNT_OBSERVATION',protectedReserve:250,historicalAccountAnchor:630027,accountWideDecrease:4996,campaignAttributedCredits:27,unattributedAccountWideChange:4969,causeAssigned:false,actualPrivateStateAccess:true,credentialAccess:false,privateMutation:false,unauthenticatedDocumentationGets:official.index.unauthenticatedDocumentationGets,newClarificationRequests:0,authenticatedCampaignProviderRequests:0,accountRequests:0,browserRuntimeProviderRequests:0,reviewerExternalRequests:0,p2BatchNotFrozen:true,p3PlanGenerated:false,P3_AUTHORIZED_TO_ISSUE:false,AUTHORIZED_TO_ISSUE:false,gameplayIntegrationAccepted:false,qualificationFloorClaimed:false};
 const index=prior.objects['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'],indexSchema=prior.objects['SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json'];validateSchema('provider',index,indexSchema);const indexBytes=serialize(index),entries={
 'SOURCE_INSTALL/V1_9_0_SOURCE_SYNC_INSTALLATION_REPORT.json':source(root,{validate:true}),
 'RECEIPTS/P1_LEAD_ACCEPTANCE_RECEIPT.json':receipt,
 'CONTRACTS/TGM_TRANSFERS_OFFICIAL_CONTRACT_ADMISSION.json':admission.tgm,
 'CONTRACTS/ADDRESS_COUNTERPARTIES_OFFICIAL_CONTRACT_ADMISSION.json':admission.counter,
 'CONTRACTS/INVESTIGATION_CORPUS_SEMANTIC_ABSTRACTION.json':corpus.contract,
 'EVIDENCE/ENDPOINT_TO_GAME_CONCEPT_MATRIX.json':corpus.matrix,
 'EXECUTION/T1_P2_NARRATIVE_BREADTH_ENVELOPE.json':seal({schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',reason:REASON,candidate:cut(root),implementationSha256:digest(root),executionContractSha256:CONTRACT_SHA,p1LeadAcceptanceReceiptIdentity:receipt.hash,planGenerated:false,credentialAccess:false,AUTHORIZED_TO_ISSUE:false}),
 'REPORTS/T1_P2_EXECUTION_REPORT.json':report,
 'REPORTS/T1_P2_RECONCILIATION_REPORT.json':report,
 'REPORTS/T1_P2_UTILITY_AND_ROUTE_VIABILITY_REPORT.json':{schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',reason:REASON,liveUtilityMeasured:false,supportFraction:null,semanticRolesMeasured:null,phaseCoverageMeasured:null,p2PlanGenerated:false,p3PlanGenerated:false,credibleRemaining1024PathEstablished:false,P3_AUTHORIZED_TO_ISSUE:false,foregroundGameplayAccepted:false},
 'REPORTS/T1_CAMPAIGN_STATE_REDACTED.json':report,
 'SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json':prior.bytes['SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json'],
 'SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json':indexSchema,
 'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':indexBytes,'PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256':sha(indexBytes)+'  NQ5_PUBLIC_CALL_INDEX.json\n',
 'EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':prior.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'],
 'EVIDENCE/P2_LIVE_REQUEST_IDENTITY_MATRIX.json':{schemaVersion:'1.0.0',status:'BLOCKED_BEFORE_PLAN_AND_KEY',requests:[],p1ImmutableIdentityCrosswalk:crosswalk,allP1NormalizedProviderSupportReproduced:true,P2RequestsIssued:0},
 'EVIDENCE/P2_ATTEMPT_CREDIT_COUNT_AND_PROVIDER_ID_RECONCILIATION.json':{...report,p1Requests:crosswalk},
 'EVIDENCE/P2_PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json':{...report,publicIndexFileSha256:sha(indexBytes),acceptedPublicIndexIdentity:identity(index),historicalLeadAcceptedEightBytesPreserved:true,requestedEighteenRowIndexNotPublished:true,privatePathsIncluded:false,rawBodiesIncluded:false},
 'EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json':{schemaVersion:'1.0.0',carriedForwardCount:32,addedCount:1,lessons:[...prior.objects['EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json'].lessons,{id:'P2-L033',name:'Acceptance order is not supplier order',false_success_mechanism:'Using document list order silently renumbers immutable canary-first supplier terminals.',accepted_rule:'Bind every logical request to the preserved terminal public ID and supplier sequence before publishing acceptance.',required_test_or_invariant:'An exact handoff disagreement blocks before receipt, index, plan, key or provider issue.'}]},
 'EVIDENCE/KT_CONTINUITY_DELTA.json':{schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',authority:{acceptedCandidate:{commit:BASE,tree:TREE},acceptedArchiveSha256:ARCHIVE_SHA,executionContractSha256:CONTRACT_SHA,implementationCandidate:cut(root),implementationSha256:digest(root)},counters:report,acceptedHeldCalls:{requestedRoleAcceptances:10,requestedTotal:18,publishedIndex:8,heldSupplierSequences:[2,3,4],unsealedCrosswalk:crosswalk},semanticAbstractionIdentity:corpus.contract.hash,endpointAdmissionIdentities:{tgm:admission.tgm.hash,counterparties:admission.counter.hash},sourceState:source(root),schedule:'UNCHANGED_SOURCE_V1_9_0_TIMES_NO_NEW_DEADLINE_OR_CONTENT_LOCK',assetLane:'OUT_OF_SCOPE_READ_WRITE_STAGE_PACKAGE_NONE',unresolvedDecision:'LEAD_CORRECTION_OF_EIGHT_SUPPLIER_SEQUENCE_AND_PUBLIC_ID_MAPPINGS',falseSuccessLessons:['ACCEPTANCE_ORDER_IS_NOT_IMMUTABLE_SUPPLIER_ORDER','NO_EIGHTEEN_ROW_SUCCESS_PUBLICATION_WHEN_BINDINGS_CONFLICT'],nextExpectedGate:'CORRECT_HANDOFF_IDENTITY_CROSSWALK_THEN_REVALIDATE_P2_PRELIVE_NO_REISSUE_P1'},
 'EVIDENCE/G6P_BACKLOG_DELTA.json':{schemaVersion:'1.0.0',internalHandle:'TRACE//ESCAPE',titleRenameAuthorized:false,publicTitleBrainstormTrigger:'P2_LEAD_REVIEW_OR_ASSET_CAPABILITY_REVIEW_WHICHEVER_FIRST',titleMustPrecedeContentLock:true,territories:['Records Office','case-thread','ledger-archive','trail-route','False Exit'],escapeMechanicClaim:false,assetLaneUnchanged:true},
 'OFFICIAL_DOCS/INDEX.json':official.index};for(const s of official.index.snapshots)entries['OFFICIAL_DOCS/'+s.filename]=official.bodies[s.name];for(const n of ['TGM_TRANSFERS_RESPONSE_COMPATIBILITY.schema.json','ADDRESS_COUNTERPARTIES_PUBLIC_PROJECTION.schema.json'])entries['SCHEMAS/'+n]=fs.readFileSync(path.join(root,'schemas',n));return {entries,report,receipt,status:'BLOCKED_WITH_EVIDENCE',source:{candidate:cut(root),implementationSha256:digest(root)}}}
