import {identity,sha} from '../nq5/schema.mjs'
import {readMirrored} from '../nq5-b1/store.mjs'
import {assertPrivateAncestry,assertRawInventory} from '../nq5-b1-r3/gate-proof.mjs'
import {LEDGER_SHA,LEDGER_BYTES,BASE_ROWS} from './authority.mjs'
import fs from 'node:fs'
import path from 'node:path'
export function replay(roots,e,{maximumAddedAttempts=192,prefixOnly=false,independentP2Raw=false}={}){if(roots.length!==2||roots[0]===roots[1])throw new Error('P2_EXACT_TWO_PRIVATE_ROOTS');assertPrivateAncestry(roots);const whole=readMirrored(roots,'qualification.jsonl');if(whole.length<LEDGER_BYTES||sha(whole.subarray(0,LEDGER_BYTES))!==LEDGER_SHA||!prefixOnly&&whole.at(-1)!==10)throw new Error('P2_IMMUTABLE_PREFIX_OR_CRASH_TAIL');const bytes=prefixOnly?whole.subarray(0,LEDGER_BYTES):whole,rows=new TextDecoder('utf8',{fatal:true}).decode(bytes).trimEnd().split('\n').map(l=>JSON.parse(l)),starts=new Map(),responses=new Map(),terminals=new Map(),rawRecoveryFailures=new Map();let previous=sha(Buffer.alloc(0)),rank=-1;
 for(const[i,r]of rows.entries()){const{hash,...p}=r,k=r.logicalId+'.'+r.attempt,n=e.executionOrder.indexOf(r.logicalId);if(!/^[a-f0-9]{64}$/.test(r.logicalId)||hash!==identity(p)||r.previous!==previous||r.sequence!==i+1||r.envelopeHash!==e.hash||r.campaignId!==e.campaignId||n<0||!Number.isInteger(r.attempt)||r.attempt<1||r.attempt>3)throw new Error('P2_LEDGER_CHAIN_AUTHORITY');previous=hash;
  if(r.kind==='START'){if(starts.has(k)||terminals.has(r.logicalId)||starts.size>=23+maximumAddedAttempts)throw new Error('P2_LEDGER_DUPLICATE_OR_ATTEMPT_CAP');if(r.attempt>1){const a=responses.get(r.logicalId+'.'+(r.attempt-1));if(!a||!e.retryStatuses.includes(a.httpStatus)||a.actualCredits===null)throw new Error('P2_LEDGER_RETRY_AUTHORITY')};starts.set(k,r)}
  else if(r.kind==='RESPONSE'){if(!starts.has(k)||responses.has(k)||terminals.has(r.logicalId)||r.rawName!==r.logicalId+'.'+r.attempt+'.bin'||!Number.isInteger(r.httpStatus)||r.httpStatus<100||r.httpStatus>599||r.actualCredits!==null&&(!Number.isSafeInteger(r.actualCredits)||r.actualCredits<0))throw new Error('P2_LEDGER_RESPONSE_ORDER_OR_SHAPE');try{const b=readMirrored(roots,'raw-b1/'+r.rawName);if(b.length!==r.rawBytes||sha(b)!==r.rawSha256)throw new Error('P2_RAW_BYTES_SHA')}catch(err){if(!independentP2Raw||i<BASE_ROWS)throw err;rawRecoveryFailures.set(r.logicalId,'P2_R1_INDIVIDUAL_RAW_PAIR_UNAVAILABLE_OR_UNREPRODUCIBLE')}responses.set(k,r)}
  else if(r.kind==='TERMINAL'){if(!starts.has(k)||terminals.has(r.logicalId)||n<=rank||!['SUCCESS_COUNTED','TERMINAL_FAILURE'].includes(r.disposition))throw new Error('P2_LEDGER_TERMINAL_ORDER');if(r.disposition==='SUCCESS_COUNTED'&&(!responses.has(k)||!r.publicRecord||r.publicRecord.qualification_sequence!==[...terminals.values()].filter(t=>t.disposition==='SUCCESS_COUNTED').length+1))throw new Error('P2_IMMUTABLE_SUPPLIER_SEQUENCE');rank=n;terminals.set(r.logicalId,r)}else throw new Error('P2_LEDGER_UNKNOWN_KIND')
 }
 if(rows.length<BASE_ROWS||starts.size<23)throw new Error('P2_PRIOR_STATE_MISSING');if(!prefixOnly){const names=[...responses.values()].map(r=>r.rawName);if(!independentP2Raw||!rawRecoveryFailures.size)assertRawInventory(roots,names);else for(const root of roots){const dir=path.join(root,'raw-b1'),actual=fs.readdirSync(dir);if(actual.some(n=>!names.includes(n))||names.some(n=>!actual.includes(n)&&!rawRecoveryFailures.has(n.split('.')[0])))throw new Error('P2_R1_UNRELATED_RAW_INVENTORY_CHANGED');assertRawInventory([root],actual)}}return {rows,starts,responses,terminals,rawRecoveryFailures,bytes:bytes.length,bytesSha256:sha(bytes)}
}
