import fs from 'node:fs'
import path from 'node:path'
import {identity,sha,validateSchema} from '../nq5/schema.mjs'
import {seal,source,LEDGER_SHA,LEDGER_BYTES,CORRECTION_SHA} from './authority.mjs'
import {baseline,persistBaseline,postContext} from './context.mjs'
import {requestAudit,auditSchema} from './audit.mjs'
import {reconcile,utility} from './reconciliation.mjs'
import {nextFrontier} from './frontier.mjs'
import {TGM,COUNTER,CLAIMS} from './admission.mjs'
export {serialize} from './failure.mjs'
import {serialize} from './failure.mjs'
function pending(c){const audit=requestAudit(c,c.state,()=>{throw new Error('P2_UNISSUED_RAW_FORBIDDEN')}),report={schemaVersion:'1.0.0',status:'OFFLINE_GATES_PENDING_NO_ISSUE',campaignId:c.receipt.campaignId,httpAttempts:23,provider2xx:23,supplierCountedTerminals:21,leadAcceptedBeforeP2:18,leadAcceptedAfterP2:18,permanentlyHeldSupplierTerminals:3,newAttempts:0,newDistinctRequests:0,newProvider2xx:0,newLocalSupportCandidates:0,newKnownCredits:0,knownCampaignCredits:27,retries:0,unresolvedReservations:0,unresolvedReservedCredits:0,unresolvedTerminals:0,clean:true,ledgerSha256:LEDGER_SHA,ledgerBytes:LEDGER_BYTES,allPrimaryMirrorRawEqual:true,historicalTwentyThreeAttemptsResponsesTerminalsAndMirrorsUnchanged:true,latestSafeResponseBalance:625031,protectedReserve:250,accountWideDecrease:4996,campaignAttributedCredits:27,unattributedAccountWideChange:4969,causeAssigned:false,balanceSource:'PRIOR_P1_SAFE_RESPONSE_HEADER_NO_NEW_BALANCE_OBSERVATION',publicAcceptedIndexRows:18,publicPendingIndexRows:0,p2PendingLocalCandidateRows:0,acceptedPublicIndexIdentity:identity(c.index),requestAuditIdentity:identity(audit),priorPerCallTransferRowSum:c.baseProof.oldPerCallTransferRows,priorGlobalDistinctTransferIdentityCount:c.oldTransferIdentities.length,newPerCallTransferRowSum:0,newGlobalDistinctTransferIdentityCount:0,allPerCallTransferRowSum:c.baseProof.oldPerCallTransferRows,allGlobalDistinctTransferIdentityCount:c.oldTransferIdentities.length,baselineQueryMatchCountSum:0,baselineTransferTupleRowsPublished:0,counterpartyCountItems:0,actualPrivateStateAccess:true,credentialAccess:false,privateMutation:false,reviewerExternalRequests:0,unauthenticatedDocumentationGets:c.admission.official.index.unauthenticatedDocumentationGets,authenticatedCampaignProviderRequests:0,authenticatedCampaignProviderRequestsByFamily:{[TGM]:0,[COUNTER]:0},accountRequests:0,browserRuntimeProviderRequests:0,AUTHORIZED_TO_ISSUE:false,P3_AUTHORIZED_TO_ISSUE:false},execution={stopReason:null,newAttempts:0,newActualCredits:0,newLocalSupportCandidates:0,unresolvedReservedCredits:0,maximumInFlight:0,canaryRequests:8,noReplacement:true,no65thRequest:true,P3Requests:0};return {audit,report,projections:[],state:c.state,execution}}
export function entries(c,r,{post=false,executionEnvelope,status}={}){validateSchema('provider',r.audit,auditSchema(c));const u=utility(c,r),f=nextFrontier(c,r,u),indexBytes=serialize(c.index),e=post?executionEnvelope:seal({schemaVersion:'1.0.0',status:'OFFLINE_GATES_PENDING_NO_ISSUE',candidate:c.source.candidate,implementationSha256:c.source.implementationSha256,p1LeadAcceptanceReceiptIdentity:c.receipt.hash,officialSourceIdentity:c.admission.official.identity,planIdentity:c.plans.plan.hash,reserveIdentity:c.plans.reserve.hash,frontierPolicyIdentity:c.plans.policy.hash,AUTHORIZED_TO_ISSUE:false}),notes=fs.readFileSync(path.join(c.root,'docs/G6P_NQ5_T1_P2_RESUME_NOTES_FOR_LEAD.md'),'utf8'),oldLessons=c.prior.objects['EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json'].lessons,add=[['Acceptance order is not supplier order','Preserve immutable supplier/public identities; separate Lead order; block conflicting handoff before key access.'],['Correction requires bounded user authority','Retain exact question/approval and all old/new mappings; never alter private historical evidence.'],['Consumer execution makes breadth measurable','Named phase/query/comparison/test/provenance consumers must execute before local support; no count-only utility.'],['Metadata-only change does not waive byte binding','Hold new Counterparties whenever whole controlling bytes change, even if legal body is identical.'],['Haystack match counts are not transfer identities','Publish aggregate count/coverage only; do not count raw zero controls as normalized transfer tuples.'],['Deployment suppression is not case proof','Use byte-bound public deployment sources solely to suppress token/protocol/pool recursion; no provider labels, ownership or intent claim.']];if(oldLessons.length!==32)throw new Error('P2_ALL_THIRTY_TWO_PRIOR_LESSONS_REQUIRED');const utilityReport={schemaVersion:'1.0.0',status:r.report.runtimeEvidenceProven===false?'UNPROVEN_DURABLE_RUNTIME_STATE':post?'MEASURED_LOCAL_SUPPORT_PENDING_LEAD':'NO_LIVE_MEASUREMENT',...u,p3Gate:f.matrix.gate,p3PlanGenerated:!!f.plan,p3FrozenMeaningfulRequests:f.plan?.requests.length??0,P3_AUTHORIZED_TO_ISSUE:false,p3RequestsIssued:0,broaderCorpusUtilityMeasured:post&&r.report.runtimeEvidenceProven!==false,credibleRemaining1024PathEstablished:false,remainingFormalLeadAcceptedFloor:1006,noRawBranchingExtrapolation:true,noGlobalExhaustionOrNegativeProof:true,claimBoundaries:CLAIMS,gameplayIntegrationAccepted:false},values={
 'SOURCE_INSTALL/V1_9_0_SOURCE_SYNC_INSTALLATION_REPORT.json':source(c.root,{validate:true}),
 'RECEIPTS/P1_LEAD_ACCEPTANCE_RECEIPT.json':c.receipt,
 'CONTRACTS/TGM_TRANSFERS_OFFICIAL_CONTRACT_ADMISSION.json':c.admission.tgm,
 'CONTRACTS/ADDRESS_COUNTERPARTIES_OFFICIAL_CONTRACT_ADMISSION.json':c.admission.counter,
 'CONTRACTS/INVESTIGATION_CORPUS_SEMANTIC_ABSTRACTION.json':c.corpus.contract,
 'EVIDENCE/ENDPOINT_TO_GAME_CONCEPT_MATRIX.json':c.corpus.matrix,
 'EXECUTION/T1_P2_NARRATIVE_BREADTH_ENVELOPE.json':e,
 'PLANS/T1_P2_NARRATIVE_BREADTH_PLAN.json':c.plans.plan,
 'PLANS/T1_P2_RESERVE_PLAN.json':c.plans.reserve,
 'PLANS/T1_P2_FRONTIER_POLICY.json':c.plans.policy,
 'EVIDENCE/P2_COMPLETE_CANDIDATE_REJECTION_MATRIX.json':c.plans.matrix,
 'REPORTS/T1_P2_EXECUTION_REPORT.json':{schemaVersion:'1.0.0',status,...r.execution,credentialAccess:r.report.credentialAccess,privateMutation:r.report.privateMutation,issueAuthorizationHistorical:r.report.runtimeEvidenceProven===false?null:post,issueAuthorizationHistoricalStatus:r.report.runtimeEvidenceProven===false?'UNPROVEN_CURRENT_RUNTIME_ENVELOPE':post?'ACTUAL_RECONCILED_HISTORICAL_ENVELOPE':'NO_LIVE_ISSUE',AUTHORIZED_TO_ISSUE:false},
 'REPORTS/T1_P2_RECONCILIATION_REPORT.json':r.report,
 'REPORTS/T1_P2_UTILITY_AND_ROUTE_VIABILITY_REPORT.json':utilityReport,
 'REPORTS/T1_CAMPAIGN_STATE_REDACTED.json':{...r.report,qualificationFloorClaimed:false,finalQualificationClaimed:false,gameplayIntegrationAccepted:false},
 'SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json':auditSchema(c),
 'SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json':c.pubSchema,
 'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':indexBytes,
 'PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256':sha(indexBytes)+'  NQ5_PUBLIC_CALL_INDEX.json\n',
 'EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':r.audit,
 'EVIDENCE/P2_LIVE_REQUEST_IDENTITY_MATRIX.json':{schemaVersion:'1.0.0',planIdentity:c.plans.plan.hash,requests:r.audit.p2Records,semanticConsumerProofs:r.projections.map(p=>p.consumers),formalLeadAccepted:18,newFormalAcceptances:0,allNewSupportPendingLead:true},
 'EVIDENCE/P2_ATTEMPT_CREDIT_COUNT_AND_PROVIDER_ID_RECONCILIATION.json':{...r.report,p1IdentityCrosswalk:c.receipt.acceptanceCrosswalk,newAttemptDetail:r.audit.p2Records.flatMap(p=>p.attempts.map(a=>({logicalId:p.request.logicalId,family:p.request.family,...a})))},
 'EVIDENCE/P2_PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json':{...r.report,publicIndexFileSha256:sha(indexBytes),originalLedgerPrefixSha256:LEDGER_SHA,originalLedgerPrefixBytes:LEDGER_BYTES,approvedIdentityCorrectionSha256:CORRECTION_SHA,historicalPrivateIdentitiesUnchanged:true,rawBodiesIncluded:false,privatePathsIncluded:false},
 'EVIDENCE/P3_CANDIDATE_REJECTION_MATRIX.json':f.matrix,
 'EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json':{schemaVersion:'1.0.0',carriedForwardCount:32,addedCount:add.length,lessons:[...oldLessons,...add.map(([name,accepted_rule],i)=>({id:'P2-L'+String(i+33).padStart(3,'0'),name,false_success_mechanism:'Count, identity representation or unchecked consumer substituted for bounded measured evidence.',accepted_rule,required_test_or_invariant:'P2 correction, schema, consumer, canary, audit and privacy regressions plus actual read-only reconciliation.'}))]},
 'EVIDENCE/KT_CONTINUITY_DELTA.json':{schemaVersion:'1.0.0',status,authority:{executionContractSha256:c.receipt.executionContractSha256,reviewedP1Candidate:c.receipt.reviewedCandidate,reviewedP1ArchiveSha256:c.receipt.reviewedArchiveSha256,approvedIdentityCorrectionSha256:CORRECTION_SHA,implementationCandidate:c.source.candidate,implementationSha256:c.source.implementationSha256},counters:r.report,acceptedHeldCalls:{leadAccepted:18,p1Accepted:10,heldSupplierSequences:[2,3,4],crosswalk:c.receipt.acceptanceCrosswalk,newLocalSupportPendingLead:r.report.newLocalSupportCandidates},semanticAbstractionIdentity:c.corpus.contract.hash,endpointAdmissions:{tgm:c.admission.tgm.hash,counterparties:c.admission.counter.hash,counterpartiesStatus:c.admission.counter.status},sourceState:source(c.root),schedule:{sourceDeadlinesUnchanged:true,pilotMilestoneUtc:'2026-09-17T17:00:00Z',pilotMilestoneElapsed:true,notOverallReleaseDeadline:true,releaseMilestonesNotReset:true},assetLane:'OUT_OF_SCOPE_NO_READ_WRITE_STAGE_OR_PACKAGE',notesForLead:notes,externalLeadMessageSent:false,unresolvedDecisions:['INDEPENDENT_LEAD_P2_REVIEW','SEPARATE_P3_LIVE_AUTHORITY_IF_MEASURED_FREEZE_EXISTS','PUBLIC_TITLE_BRAINSTORM_AT_P2_LEAD_OR_ASSET_CAPABILITY_REVIEW'],falseSuccessLessons:['LEAD_ORDER_IS_NOT_SUPPLIER_SEQUENCE','NEW_LOCAL_SUPPORT_IS_NOT_FORMAL_LEAD_ACCEPTANCE','AGGREGATE_MATCH_COUNT_IS_NOT_TRANSFER_IDENTITY','NO_LEGAL_BODY_CHANGE_DOES_NOT_WAIVE_WHOLE_BYTE_BINDING'],nextExpectedGate:post?'INDEPENDENT_LEAD_P2_REVIEW_NO_P3_ISSUE':'COMPLETE_CURRENT_PRELIVE_GATES_THEN_EXACT_FROZEN_P2'},
 'EVIDENCE/PROJECT_BACKLOG_DELTA.json':{schemaVersion:'1.0.0',internalHandle:'TRACE//ESCAPE',titleRenameAuthorized:false,publicTitleBrainstormTrigger:'P2_LEAD_REVIEW_OR_ASSET_CAPABILITY_REVIEW_WHICHEVER_FIRST',titleMustPrecedeContentLock:true,territories:['Records Office','case-thread','ledger-archive','trail-route','False Exit'],escapeMechanicClaim:false,assetLaneUnchanged:true},
 'OFFICIAL_DOCS/INDEX.json':c.admission.official.index,
 'OFFICIAL_DOCS/PUBLIC_DEPLOYMENT_SUPPRESSION_SOURCES.json':fs.readFileSync(path.join(c.root,'docs/official/p2/PUBLIC_DEPLOYMENT_SUPPRESSION_SOURCES.json'))
 };for(const s of c.admission.official.index.snapshots)values['OFFICIAL_DOCS/'+s.filename]=c.admission.official.bodies[s.name];for(const name of ['TGM_TRANSFERS_RESPONSE_COMPATIBILITY.schema.json','ADDRESS_COUNTERPARTIES_PUBLIC_PROJECTION.schema.json'])values['SCHEMAS/'+name]=fs.readFileSync(path.join(c.root,'schemas',name));if(f.plan){values['PLANS/T1_P3_CANDIDATE_PLAN.json']=f.plan;values['PLANS/T1_P3_RESERVE_PLAN.json']=f.reserve;values['PLANS/T1_P3_FRONTIER_POLICY.json']=f.policy;values['PLANS/T1_P3_MACHINE_PROGRESSION_POLICY.json']=f.progression}return {c,r,u,f,status,entries:values,report:r.report}}
export function derive(root,{post=false,executionEnvelope,execution}={}){const c=post?postContext(root):baseline(root);if(!post)persistBaseline(c);const r=post?reconcile(c,executionEnvelope,execution):pending(c),status=post&&!r.execution.stopReason&&r.report.clean?'DELIVERED_PENDING_LEAD_REVIEW':post?'BLOCKED_WITH_EVIDENCE':'PRELIVE_PENDING';return entries(c,r,{post,executionEnvelope,status})}
