import {identity,sha,freeze as deepFreeze} from '../nq5/schema.mjs'
import {seal,CONTRACT_SHA,LEDGER_SHA,LEDGER_BYTES} from './authority.mjs'
import {TGM,COUNTER,DAI,WINDOW,ADDRESS,validateRequest,CLAIMS} from './admission.mjs'
import {SUBJECTS as P1_SUBJECTS,canonical} from '../nq5-p1/planner.mjs'
import {REGISTRY} from '../nq5-b4-filtered/quality.mjs'
import {TOKENS,INFRASTRUCTURE} from './infrastructure.mjs'
const RISK_CONTROLS=new Set(['0x583c21631c48d442b5c0e605d624f54a0b366c72'])
import {PHASES,ROLES,concept} from './corpus.mjs'
import {selectIncrementalRequests} from './incremental.mjs'
export {canonical}
export const SUBJECTS={...P1_SUBJECTS,SECONDARY:'0xc66dfa84bc1b93df194bd964a41282da65d73c9a'}
export const STRATA=['ACCEPTED_EXACT_HASH_JOIN','INDEPENDENT_LEAD_CALL_REPEAT','SINGLE_SUPPORT_DEAD_END_CONTROL','SCHEMA_VIEW_COMPARISON']
const ZERO='0x'+'0'.repeat(40),uniq=a=>[...new Set(a)].sort(),pagination={page:1,per_page:100},isAdmitted=c=>c.status.startsWith('ADMITTED_')
export function sourceQuality(s){const q=s.request,subject=q.body.address??q.body.filters?.from_address??q.body.filters?.to_address,rows=s.normalized.rows,opposites=new Set(rows.flatMap(r=>r.transaction_hash?[r.from_address,r.to_address].filter(x=>x!==subject):[])),known=subject?REGISTRY[subject]??INFRASTRUCTURE[subject]??TOKENS[subject]??(RISK_CONTROLS.has(subject)?'UNVERIFIED_INFRASTRUCTURE_RISK_CONTROL_NO_RECURSION':null):null,degree=opposites.size;return {logicalId:s.logicalId,family:q.family,subject:subject??'BUNDLED_ACCEPTED_EXACT_HASHES',distinctOpposites:degree,knownPlanningOnlyInfrastructure:known,hubRisk:q.family===COUNTER||q.frontierAuthority===false||!!known||degree>=50||rows.length>=100,recursiveAuthority:q.family!==COUNTER&&q.frontierAuthority!==false&&!known&&degree<50&&rows.length<100,planningOnly:true,providerLabelsUsed:false}}
export function qfactory(c,{id,stage='P2',body,family=TGM,kind,phaseId='FULL_INCIDENT',question,lens,purpose,roles,lineage,teaching,proof,subject,direction,frontier=true,priorNoMatch=false}){const a=family===TGM?c.admission.tgm:c.admission.counter,cell='CELL.'+stage+'.'+id,consumers=['CASE_CORPUS.'+stage+'.'+id,'QUERY_RECEIPT.'+stage+'.'+id,'EVIDENCE_DELTA.'+stage+'.'+id,'CALL_ATLAS.'+stage+'.'+id,'TEST.'+stage+'.'+id,'PROVENANCE.'+stage+'.'+id],q={family,path:'/api/v1/'+family,method:'POST',body,wireBodySha256:sha(Buffer.from(JSON.stringify(body))),kind,phaseId,subjectAddress:subject??body.address??body.filters?.from_address??body.filters?.to_address??'DAI_TOKEN_HAYSTACK',direction:direction??'COUNTS_OR_BASELINE',questionId:'QUESTION.'+stage+'.'+id,businessQuestion:question,lens,purpose,utilityRoles:roles,coverageCells:[cell],coverageKey:{subject_id:subject??body.address??body.filters?.from_address??body.filters?.to_address??'DAI_TOKEN_HAYSTACK',time_window_id:body.date.from+'/'+body.date.to,question_lens:lens,page_or_partition_id:'PAGE.1.'+id},lineage:uniq(lineage),consumers,utilityProof:{storyTeachingPurpose:teaching,deterministicEvidence:proof,distinctFromP1FullWindow:identity(body.date)!==identity(WINDOW)?'EXACT_STORY_PHASE_FILTER_WITH_NAMED_COMPARISON_RECIPE_AND_ACCEPTED_CHRONOLOGY_ANCHOR':'DIFFERENT_UNISSUED_EXACT_SUBJECT_DIRECTION_OR_RELATIONSHIP_CONTROL_BODY',notSolePurpose:['RAW_COUNT','PHASE_PARTITION','FAMILY_DIVERSITY','VISUAL_DENSITY'],consumerExecutionRequiredBeforeLocalSupport:true},emptyResultRule:'BOUNDED_PROVIDER_QUERY_NO_MATCH_PREDECLARED_NOT_CHAIN_NEGATIVE_PROOF',priorBoundedNoMatchHint:priorNoMatch,frontierAuthority:frontier&&kind!=='HAYSTACK_BASELINE'&&family!==COUNTER,publicOutputMode:kind==='HAYSTACK_BASELINE'?'AGGREGATE_COUNT_COVERAGE_ONLY':family===COUNTER?'WALLET_ADDRESS_COUNT_ONLY':'ADMITTED_CONTEXTUAL_CONCEPT_METADATA_NO_RAW_BULK',expectedCredits:a.quotedCredits,worstCaseCredits:a.quotedCredits*3,admissionIdentity:a.hash,publicProjectionPolicyIdentity:identity({family,allowlist:kind==='HAYSTACK_BASELINE'?['query_match_count','page_coverage_metadata']:a.projectionAllowlist,omitted:a.omitted,rawBulk:false,claims:CLAIMS}),claimBoundaries:CLAIMS,stopRule:'FIRST_BREAKER_DRAIN_NO_REPLACEMENT_NO_65TH_NO_REENTRY_NO_P3_ISSUE'};q.logicalId=canonical(q);q.coverageIdentity=identity({cells:q.coverageCells,key:q.coverageKey});q.auditIdentity=identity(q);return q}
export function candidatePool(c){const pool=new Map(),tokens=new Set([DAI,...Object.keys(TOKENS),...c.sources.flatMap(s=>s.tokenContracts??[])]),qualities=c.sources.map(sourceQuality),qm=new Map(qualities.map(q=>[q.logicalId,q]));for(const s of c.sources.filter(s=>s.request.family!==COUNTER)){const subject=s.request.body.address??s.request.body.filters?.from_address??s.request.body.filters?.to_address;for(const r of s.normalized.rows){if(!r.transaction_hash)continue;const addresses=subject?[r.from_address===subject?r.to_address:r.from_address]:[r.from_address,r.to_address];for(const address of addresses){const x=pool.get(address)??{address,sources:new Set(),nonHubSources:new Set(),hashes:new Set(),nonHubHashes:new Set(),exactHashes:new Set(),families:new Set(),inVotes:0,outVotes:0,nonSelf:false};x.sources.add(s.logicalId);x.hashes.add(r.transaction_hash.toLowerCase());x.families.add(s.request.family);if(r.from_address!==r.to_address){x.nonSelf=true;if(qm.get(s.logicalId).recursiveAuthority){x.nonHubSources.add(s.logicalId);x.nonHubHashes.add(r.transaction_hash.toLowerCase());if(Object.hasOwn(c.truth,r.transaction_hash.toLowerCase()))x.exactHashes.add(r.transaction_hash.toLowerCase());if(r.to_address===address)x.outVotes++;if(r.from_address===address)x.inVotes++}}pool.set(address,x)}}}return {pool,tokens,qualities}}
// R1 rejects the former default Cartesian live generator. Historical material is
// recovered separately from the exact reviewed snapshot, never regenerated here.
export function enumerate(c){
 const e=selectIncrementalRequests({candidates:c.incrementalCandidates??[],decisions:c.incrementalDecisions??[],acceptedEvidence:c.acceptedEvidenceFacts??[],unresolvedQuestions:c.predeclaredUnresolvedQuestions??[]})
 return {...e,phaseQ:[],baselineQ:[],counterQ:[],candidateQ:e.requests,matrix:{schemaVersion:'1.0.0',rows:e.rows,completeRows:e.rows.length,currentGate:'P2_R1_NO_NETWORK_REMEDIATION',historical45RequestPlanRejected:true,independentDecisionsRequired:true,AUTHORIZED_TO_ISSUE:false}}
}
export function canary(q){const chosen=[];for(const phase of PHASES){const x=q.find(x=>x.phaseId===phase.id);if(x&&!chosen.includes(x.logicalId))chosen.push(x.logicalId)};for(const x of q){if(chosen.length===8)break;if(!chosen.includes(x.logicalId))chosen.push(x.logicalId)};if(chosen.length!==8)throw new Error('P2_EXACT_EIGHT_REPRESENTATIVE_CANARY');return chosen}
export function validatePlan(){throw new Error('P2_45_PLAN_REJECTED_RETIRED_NO_LIVE_AUTHORITY')}
export function freeze(c){const e=enumerate(c);return deepFreeze({plan:seal({schemaVersion:'1.0.0',requests:e.requests,status:'RESEARCH_CANDIDATES_ONLY_NOT_LIVE_PLAN',frozen:false,AUTHORIZED_TO_ISSUE:false}),matrix:e.matrix,liveReady:false,status:'P2_R1_NO_CURRENT_LIVE_PLAN',P3_AUTHORIZED_TO_ISSUE:false})}
