import fs from 'node:fs'
import path from 'node:path'
import { identity, sha, validateSchema } from '../nq5/schema.mjs'
import { decimalLexeme } from '../nq5/exact-json.mjs'
import { accounting } from '../nq5-b1-r3-r1/evidence.mjs'
import { admit, profile, supportable, CAMPAIGN } from './signed-flow.mjs'
import { CONTRACT_SHA, ARCHIVE_SHA } from './authority.mjs'
export function revalidate(a,state,root){
 const p=profile(a),perCall=[],privateProjections=[],matrixRows=[]
 for(const call of state.calls){const {request:q,start:s,response:r,terminal:t}=call,previous=a.priorPerCall.calls.find(x=>x.logicalId===q.logicalId),oldAudit=a.priorAudit.records.find(x=>x.logicalId===q.logicalId)
  if(!previous||previous.primarySha256!==r.rawSha256||previous.mirrorSha256!==r.rawSha256||previous.oldNormalizedIdentity!==t.normalizedSha256||previous.reproducedOldNormalizedIdentity!==t.normalizedSha256||previous.oldResultCount!==t.resultCount||previous.providerRequestId!==r.providerRequestId||previous.terminal.identity!==t.hash||previous.start.identity!==s.hash||previous.response.identity!==r.hash||oldAudit.normalizedIdentity!==t.normalizedSha256||oldAudit.admittedResultCount!==t.resultCount)throw new Error('R32_IMMUTABLE_PRIOR_IDENTITY_BINDING')
  const admission=admit(a,call,p),supported=supportable(admission,t),semantic=admission.semantic
  if(semantic)matrixRows.push(...semantic.matrix)
  const reason=!admission.safelyAdmissible?admission.firstFailedStage.toUpperCase()+'_REJECTED':admission.normalizedSha256!==t.normalizedSha256||admission.resultCount!==t.resultCount?'IMMUTABLE_NORMALIZED_IDENTITY_OR_RESULT_COUNT_MISMATCH':'PER_CALL_SEMANTICALLY_SUPPORTABLE'
  perCall.push({logicalId:q.logicalId,requestedSubject:q.body.address,requestBodySha256:identity(q.body),providerRequestId:r.providerRequestId,rawBytes:call.raw.length,primarySha256:sha(call.raw),mirrorSha256:sha(call.raw),bytesEqual:true,start:{sequence:s.sequence,identity:s.hash},response:{sequence:r.sequence,identity:r.hash},terminal:{sequence:t.sequence,identity:t.hash,disposition:t.disposition,unchanged:true},observedNullTimeProfileIdentity:a.context.profile.hash,signedFlowCompatibilityProfileIdentity:p.hash,signDirectionMatrixIdentity:semantic?identity(semantic.matrix):null,stats:semantic?.stats??null,oldNormalizedIdentity:t.normalizedSha256,newNormalizedIdentity:admission.normalizedSha256,oldResultCount:t.resultCount,newResultCount:admission.resultCount,normalizedIdentityEqual:t.normalizedSha256===admission.normalizedSha256,resultCountEqual:t.resultCount===admission.resultCount,oldValidationStages:t.validationStages,validationStages:Object.fromEntries(['json','schema','pagination','contextualTemporal','normalization','projection','publicSchema'].map(k=>[k,admission.stages[k]??{status:'NOT_RUN'}])),firstFailedStage:admission.firstFailedStage,existingCountedTerminalSemanticallySupportable:supported,leadAcceptanceCandidate:supported,leadAccepted:false,reason,oldPublicCallId:t.publicRecord.public_call_id,qualificationSequence:t.publicRecord.qualification_sequence,oldCampaignAlias:t.publicRecord.campaign_id,exactCampaignId:CAMPAIGN,immutableAuditRecordIdentity:identity(oldAudit),supplierTerminalAuditIdentity:identity(call.audit),oldPublicRecordIdentity:identity(t.publicRecord),rawBodyIncluded:false,privatePathsIncluded:false})
  // Evidence-only legacy decimal rewrite comparison, never used for projection.
  perCall.at(-1).immutableSupplierDecimalRewriteRows=semantic?semantic.matrix.filter(row=>row.amount_magnitude!==null&&decimalLexeme(row.providerSignedDecimalLexeme).replace(/^-/, '')!==row.amount_magnitude).length:null
  privateProjections.push({logicalId:q.logicalId,request:q,admission,semantic,pagination:semantic?admission.pagination:null,leadAcceptanceCandidate:supported})
 }
 const supported=privateProjections.filter(p=>p.leadAcceptanceCandidate),index=supported.map(p=>p.admission.publicRecord)
 validateSchema('provider',index,JSON.parse(fs.readFileSync(path.join(root,'schemas/NQ5_PUBLIC_CALL_INDEX.schema.json'))))
 if(new Set(index.map(x=>x.public_call_id)).size!==index.length||new Set(index.map(x=>x.qualification_sequence)).size!==index.length)throw new Error('R32_PUBLIC_SEQUENCE_DUPLICATE')
 const indexBytes=Buffer.from(JSON.stringify(index,null,2)+'\n'),signedMatrix={schemaVersion:'1.0.0',signedFlowCompatibilityProfileIdentity:p.hash,observedNullTimeProfileIdentity:a.context.profile.hash,executionContractSha256:CONTRACT_SHA,acceptedR3R1ArchiveSha256:ARCHIVE_SHA,rawTransferRows:matrixRows.length,rows:matrixRows,rowDispositionScope:'NORMALIZATION_ELIGIBILITY_NOT_FINAL_QUALIFICATION_OR_GAMEPLAY_ACCEPTANCE',callDispositions:perCall.map(r=>({logicalId:r.logicalId,leadAcceptanceCandidate:r.leadAcceptanceCandidate,publicCallPublished:r.leadAcceptanceCandidate,reason:r.reason})),rawBodyIncluded:false,labelsPricesUsdValuesIncluded:false,privatePathsIncluded:false},oldIndex=a.objects['REPORTS/T1_B1_R3_RECONCILIATION_REPORT.json'].publicIndex
 for(const r of perCall){r.correctedPublicIndexIdentity=identity(index);r.publicRowPublished=r.leadAcceptanceCandidate;r.correctedPublicRecordIdentity=r.publicRowPublished?identity(index.find(x=>x.public_call_id===r.oldPublicCallId)):null}
 const acceptance={schemaVersion:'1.0.0',status:supported.length?'PER_CALL_CANDIDATES_PENDING_LEAD_REVIEW':'NO_SUPPORTABLE_CALLS',campaignId:CAMPAIGN,executionContractSha256:CONTRACT_SHA,signedFlowCompatibilityProfileIdentity:p.hash,supplierCountedTerminals:4,immutablePrivateLedgerCount:4,locallySemanticallySupportableCalls:supported.length,leadAcceptanceCandidates:supported.length,heldCalls:4-supported.length,correctedDerivedPublicCount:index.length,leadAcceptedCount:0,leadAcceptanceClaimed:false,allFourAtomicRuleSuperseded:true,negativeAmountWholeResponseRuleSuperseded:true,privateTerminalsMutated:false,rawDataMutated:false,newProviderAttempts:0,newCredits:0,batch2FreezeAllowed:supported.length>0,perCallEvidenceIdentity:identity(perCall),signBucketDirectionMatrixIdentity:identity(signedMatrix),correctedPublicIndexIdentity:identity(index),calls:perCall.map(r=>({logicalId:r.logicalId,supplierCounted:true,locallySemanticallySupportable:r.leadAcceptanceCandidate,leadAcceptanceCandidate:r.leadAcceptanceCandidate,held:!r.leadAcceptanceCandidate,oldResultCount:r.oldResultCount,newResultCount:r.newResultCount,reason:r.reason})),scope:'LOCAL_SUPPORT_AND_INDEPENDENT_REVIEW_CANDIDATES_ARE_NOT_FINAL_LEAD_ACCEPTANCE'}
 const crosswalk={schemaVersion:'1.0.0',oldPublicIndexIdentity:identity(oldIndex),correctedPublicIndexIdentity:identity(index),correctedPublicIndexFileSha256:sha(indexBytes),signedFlowCompatibilityProfileIdentity:p.hash,rows:perCall.map(r=>({logicalId:r.logicalId,terminalSequence:r.terminal.sequence,terminalIdentity:r.terminal.identity,providerRequestId:r.providerRequestId,rawSha256:r.primarySha256,qualificationSequence:r.qualificationSequence,publicCallId:r.oldPublicCallId,oldPublicRecordIdentity:r.oldPublicRecordIdentity,oldGenericAlias:r.oldCampaignAlias,exactCampaignId:CAMPAIGN,correctedNormalizedIdentity:r.newNormalizedIdentity,correctedPublicRecordIdentity:r.correctedPublicRecordIdentity,immutableAuditRecordIdentity:r.immutableAuditRecordIdentity,signedFlowCompatibilityProfileIdentity:p.hash,published:r.publicRowPublished,reason:r.reason}))}
 const audit=structuredClone(a.priorAudit)
 audit.r3r2SignedFlowReview={campaignId:CAMPAIGN,signedFlowCompatibilityProfileIdentity:p.hash,leadAcceptanceCandidates:supported.length,heldCalls:4-supported.length,correctedDerivedPublicCount:index.length,leadAcceptedCount:0,perCallEvidenceIdentity:identity(perCall),signBucketDirectionMatrixIdentity:identity(signedMatrix),supplierTerminalRecordsUnchanged:true}
 for(const record of audit.records){const r=perCall.find(x=>x.logicalId===record.logicalId);if(r)record.r3r2SignedFlow={signedFlowCompatibilityProfileIdentity:p.hash,stats:r.stats,signDirectionMatrixIdentity:r.signDirectionMatrixIdentity,immutableTerminalDisposition:'SUCCESS_COUNTED',correctedDerivedDisposition:r.leadAcceptanceCandidate?'LEAD_ACCEPTANCE_CANDIDATE':'HELD_IMMUTABLE_IDENTITY_MISMATCH_OR_SEMANTIC_FAILURE',qualificationValue:r.leadAcceptanceCandidate?'INDEPENDENT_LOCAL_CANDIDATE_NOT_NEW_API_CALL':'SUPPLIER_COUNT_PRESERVED_LEAD_UNACCEPTED',engineeringValue:'EXACT_MIRRORED_RAW_PROVIDER_ID_CREDIT_AND_DURABLE_TERMINAL_CONTINUITY',gameplayProvenanceValue:r.leadAcceptanceCandidate?'BOUNDED_CONTEXTUAL_PROVENANCE_CANDIDATE_NO_GAMEPLAY_INTEGRATION':'DIAGNOSTIC_PROVENANCE_ONLY_NO_FRONTIER_LINEAGE',reason:r.reason,leadAccepted:false}}
 validateSchema('provider',audit,JSON.parse(fs.readFileSync(path.join(root,'schemas/NANSEN_API_REQUEST_AUDIT.schema.json'))))
 const held=perCall.filter(r=>!r.leadAcceptanceCandidate),correction=held.length?{schemaVersion:'1.0.0',proposalOnly:true,AUTHORIZED_TO_MUTATE_PRIVATE_STATE:false,AUTHORIZED_TO_ISSUE:false,campaignId:CAMPAIGN,immutableLedgerSha256:state.privateHashes['qualification.jsonl'],supplierCountsRemainInLedger:4,leadAcceptedCount:0,leadAcceptanceCandidates:supported.length,rows:held.map(r=>({logicalId:r.logicalId,immutableTerminalIdentity:r.terminal.identity,immutableQualificationSequence:r.qualificationSequence,proposedAnnotation:'SUPPLIER_COUNT_PRESERVED_LEAD_RETENTION_UNSUPPORTED',reason:r.reason,oldNormalizedIdentity:r.oldNormalizedIdentity,recomputedNormalizedIdentity:r.newNormalizedIdentity,oldResultCount:r.oldResultCount,recomputedResultCount:r.newResultCount,privateRewriteProposed:false})),nextStep:'LEAD_DISPOSITION_REQUIRED_NO_REISSUE_RETRY_REPLACEMENT_OR_LEDGER_REPAIR'}:null
 return {profile:p,perCall,privateProjections,acceptance,index,indexBytes,crosswalk,audit,signedMatrix,correction,balance:accounting([...state.responses.values()]),supportableCount:supported.length}
}
