import { identity } from '../nq5/schema.mjs'
import { logicalRequest } from '../nq5/planner.mjs'
import { frontier as priorFrontier } from '../nq5-b1-r3-r1/frontier.mjs'
import { seal, ARCHIVE_SHA } from './authority.mjs'
import { RULE, CAMPAIGN } from './signed-flow.mjs'
export function frontier(a,state,result){
 const allTokens=[...new Set(result.privateProjections.flatMap(p=>p.semantic?.tokenContracts??[]))],supported=result.privateProjections.filter(p=>p.leadAcceptanceCandidate).map(p=>({...p,semantic:{...p.semantic,tokenContracts:allTokens}})),base=priorFrontier(a,state,{...result,allPass:supported.length>0,privateProjections:supported}),matrix={...base.matrix,allFourAtomicRuleRequired:false,perCallSupportableSourceRequired:true,durableCallsExamined:result.privateProjections.length,leadAcceptanceCandidateCallsUsed:supported.map(p=>p.logicalId).sort(),heldCallsExcludedBeforeCandidateDerivation:result.privateProjections.filter(p=>!p.leadAcceptanceCandidate).map(p=>({logicalId:p.logicalId,reason:'HELD_CALL_NOT_ACCEPTED_FRONTIER_LINEAGE_UNLESS_INDEPENDENT_ACCEPTED_SEED'})),correctedPublicIndexIdentity:identity(result.index),requestAuditIdentity:identity(result.audit),signedFlowCompatibilityProfileIdentity:result.profile.hash,rows:base.matrix.rows.map(r=>({...r,rejectionCode:r.rejectionCode==='SEMANTIC_ALL_FOUR_RETENTION_GATE_FAILED'?'NO_SUPPORTABLE_CALLS':r.rejectionCode,projectionRule:RULE,projectionScope:'ACCEPTED_NULL_TIME_AND_SIGNED_FLOW_PROFILE_SUBJECT_ONLY_ALLOWLIST',signedFlowCompatibilityProfileIdentity:result.profile.hash}))}
 const binding={campaignId:CAMPAIGN,acceptedR3R1ArchiveSha256:ARCHIVE_SHA,acceptedR3ArchiveSha256:a.r3ArchiveSha256,signedFlowCompatibilityProfileIdentity:result.profile.hash,observedNullTimeProfileIdentity:a.context.profile.hash,candidateMatrixIdentity:identity(matrix),correctedPublicIndexIdentity:identity(result.index),correctedPublicIndexFileSha256:result.crosswalk.correctedPublicIndexFileSha256,requestAuditIdentity:identity(result.audit),semanticAcceptanceIdentity:identity(result.acceptance),balanceAnchor:626632,protectedReserve:250}
 let plan=null,policy=null,reserve=null
 if(base.plan){const {hash:ph,...pol}=base.policy;policy=seal({...pol,...binding,allFourSemanticRetentionRequired:false,perCallSupportableSourceRequired:true});const {hash:bh,...bp}=base.plan,requests=bp.requests.map(r=>{const q={...r,projectionRule:RULE,signedFlowCompatibilityProfileIdentity:result.profile.hash};q.logicalId=logicalRequest(q);return q});plan=seal({...bp,...binding,requests,frontierPolicyIdentity:policy.hash,AUTHORIZED_TO_ISSUE:false});reserve=seal({schemaVersion:'1.0.0',...binding,planIdentity:plan.hash,frontierPolicyIdentity:policy.hash,expectedCredits:plan.expectedCredits,worstCaseCredits:plan.worstCaseCredits,remainingAfterWorstCase:626632-plan.worstCaseCredits,reservePass:626632-plan.worstCaseCredits>=250,AUTHORIZED_TO_ISSUE:false});if(!reserve.reservePass||requests.length>64)throw new Error('R32_RESERVE_OR_MAX64')}
 return {matrix,plan,reserve,policy,report:{...base.report,status:!supported.length?'BLOCKED_NO_SUPPORTABLE_CALLS':plan?'MEANINGFUL_CANDIDATE_FROZEN_NOT_AUTHORIZED':'BLOCKED_ROUTE_SATURATED',completeCandidateMatrixIdentity:identity(matrix),mainTriggerDisposition:matrix.rows.find(r=>r.subjectAddress==='0xb2698c2d99ad2c302a95a8db26b08d17a77cedd4'),leadAcceptanceCandidateCallsUsed:matrix.leadAcceptanceCandidateCallsUsed,heldCallsExcluded:matrix.heldCallsExcludedBeforeCandidateDerivation,planIdentity:plan?.hash??null,reserveIdentity:reserve?.hash??null,frontierPolicyIdentity:policy?.hash??null,correctedPublicIndexIdentity:binding.correctedPublicIndexIdentity,requestAuditIdentity:binding.requestAuditIdentity,routeExhaustionClaimed:false,routeSaturationClaimed:supported.length>0&&!plan}}
}
