#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import { fileURLToPath } from 'node:url'
import { execFileSync, spawn } from 'node:child_process'
import { identity, sha } from '../nq5/schema.mjs'
import { LOCAL_SUITES } from '../nq5-b1/live.mjs'
import { REVIEW_LENSES } from '../nq5-r2/review-identity.mjs'
import { sanitizeLog, pathScan } from '../nq5-b1-r2/privacy.mjs'
import { accepted, digest, cut, BASE, TREE, CONTRACT_SHA, MANIFEST, ARCHIVE_SHA, OUTPUT, REVIEWS } from './authority.mjs'
import { reopen } from '../nq5-b1-r3-r1/readonly.mjs'
import { revalidate } from './evidence.mjs'
import { frontier } from './frontier.mjs'
import { CAMPAIGN } from './signed-flow.mjs'

// Select only operational environment entries. Never inspect a credential entry.
const environment=Object.fromEntries(['PATH','HOME','USER','LOGNAME','SHELL','TMPDIR','LANG','LC_ALL','DISPLAY','XDG_RUNTIME_DIR','PLAYWRIGHT_BROWSERS_PATH','npm_config_cache'].flatMap(k=>process.env[k]===undefined?[]:[[k,process.env[k]]]))
process.env=environment
const root=path.resolve(fileURLToPath(new URL('../..',import.meta.url))),parent=path.dirname(root),local=path.join(root,'artifacts/g6p-b1-r3-r2/local'),childEnv={...environment,PYTHONDONTWRITEBYTECODE:'1',NODE_OPTIONS:'--require '+path.join(root,'scripts/nq5-r2/hold.cjs'),npm_config_update_notifier:'false'}
const serialize=x=>Buffer.isBuffer(x)?x:Buffer.from(typeof x==='string'?x:JSON.stringify(x,null,2)+'\n'),write=(dir,n,x)=>{const f=path.join(dir,n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,serialize(x))},read=n=>JSON.parse(fs.readFileSync(path.join(local,n)))
const run=(cmd,args,cwd=root)=>new Promise((resolve,reject)=>{const p=spawn(cmd,args,{cwd,env:childEnv,stdio:['ignore','pipe','pipe']});let out='';for(const stream of[p.stdout,p.stderr])stream.on('data',b=>{out+=b;if(out.length>64000000)p.kill()});p.on('error',()=>reject(new Error('R32_LOCAL_TOOL_UNAVAILABLE')));p.on('close',code=>{if(code===0)return resolve(out);const e=new Error('R32_LOCAL_TOOL_FAILED');e.safeOutput=out;reject(e)})})
const snapshot=()=>({candidate:cut(root),implementationSha256:digest(root)})
function derive(){
 const starting=snapshot(),a=accepted(root),s=reopen(a),r=revalidate(a,s,root),f=frontier(a,s,r),ending=reopen(a);if(s.identity!==a.priorPrivateStateIdentity||s.identity!==ending.identity||identity(starting)!==identity(snapshot()))throw new Error('R32_SOURCE_OR_PRIVATE_BYTES_CHANGED')
 const status=r.supportableCount>0&&f.plan?'DELIVERED_PENDING_LEAD_REVIEW':'BLOCKED_WITH_EVIDENCE',perCall={schemaVersion:'1.0.0',signedFlowContractSha256:CONTRACT_SHA,acceptedR3R1ArchiveSha256:ARCHIVE_SHA,immutableLedgerSha256:s.privateHashes['qualification.jsonl'],immutableLedgerBytes:32547,primaryMirrorAndPrivateBytesUnchanged:true,readonlyFourResponseAdmission:true,calls:r.perCall},entries={
  'CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json':a.bytes['CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json'],
  'CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json':r.profile,
  'EVIDENCE/R3_SIGN_BUCKET_DIRECTION_MATRIX.json':r.signedMatrix,
  'SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json':fs.readFileSync(path.join(root,'schemas/NANSEN_API_REQUEST_AUDIT.schema.json')),
  'SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json':fs.readFileSync(path.join(root,'schemas/NQ5_PUBLIC_CALL_INDEX.schema.json')),
  'REPORTS/R3_PER_CALL_QUALIFICATION_ACCEPTANCE_REPORT.json':r.acceptance,
  'REPORTS/T1_CAMPAIGN_STATE_REDACTED.json':{schemaVersion:'1.0.0',campaignId:CAMPAIGN,httpAttempts:6,provider2xx:6,supplierCountedTerminals:4,leadAcceptanceCandidates:r.supportableCount,heldCalls:4-r.supportableCount,correctedDerivedPublicCount:r.indexBytes?JSON.parse(r.indexBytes).length:0,leadAcceptedCount:0,knownCampaignCredits:6,newGateAttempts:0,newGateCredits:0,unresolvedReservations:0,retries:0,accountRequestsInThisGate:0,documentationGetsInThisGate:0,browserProviderRequests:0,privateMutation:false,ledgerSha256:s.privateHashes['qualification.jsonl'],ledgerBytes:32547,original2NoncountedUnchanged:true,fourCountedTerminalsUnchanged:true,privateStateIdentity:s.identity,latestResponseBalance:626632,qualificationFloorClaimed:false,gameplayIntegrationClaimed:false},
  'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':r.indexBytes,
  'PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256':sha(r.indexBytes)+'  NQ5_PUBLIC_CALL_INDEX.json\n',
  'EVIDENCE/R3_PER_CALL_SEMANTIC_REVALIDATION.json':perCall,
  'EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':r.audit,
  'EVIDENCE/PUBLIC_INDEX_CAMPAIGN_BINDING_CROSSWALK.json':r.crosswalk,
  'EVIDENCE/ACCOUNT_WIDE_BALANCE_RECONCILIATION.json':r.balance,
  'EVIDENCE/FRONTIER_CANDIDATE_REJECTION_MATRIX.json':f.matrix,
  'EVIDENCE/FRONTIER_UTILITY_AND_ISSUABILITY_REPORT.json':f.report
 }
 if(r.correction)entries['QUALIFICATION_COUNT_CORRECTION_PROPOSAL.json']=r.correction
 if(f.plan){entries['PLANS/T1_BATCH2_CANDIDATE_PLAN.json']=f.plan;entries['PLANS/T1_BATCH2_RESERVE_PLAN.json']=f.reserve;entries['PLANS/T1_BATCH2_FRONTIER_POLICY.json']=f.policy}
 return {status,entries,privateStateIdentity:s.identity,leadAcceptanceCandidates:r.supportableCount,semanticallySupportable:r.supportableCount,candidateCount:f.matrix.candidateCount,batch2PlanGenerated:!!f.plan,sourceSnapshot:starting,accepted:a}
}
function deriveLocal(){const r=derive();for(const[n,x]of Object.entries(r.entries))write(local,n,x);process.stdout.write(JSON.stringify({status:r.status,leadAcceptanceCandidates:r.leadAcceptanceCandidates,semanticallySupportable:r.semanticallySupportable,leadAcceptedCount:0,frontierCandidatesEvaluated:r.candidateCount,batch2PlanGenerated:r.batch2PlanGenerated,providerRequests:0,credentialAccess:false,privateMutation:false})+'\n')}
async function verify(){accepted(root);const start=snapshot(),suites=[],assert=()=>{if(identity(start)!==identity(snapshot()))throw new Error('R32_VERIFICATION_SOURCE_CHANGED')},suite=async(name,cmd,args,cwd=root)=>{assert();process.stdout.write('LOCAL '+name+'\n');let out;try{out=await run(cmd,args,cwd)}catch(e){if(e.safeOutput?.trim())write(local,name+'.log',e.safeOutput);throw e}assert();if(!out.trim())throw new Error('R32_EMPTY_LOG');write(local,name+'.log',out);suites.push({name,status:'PASS',sha256:sha(Buffer.from(out))})}
 const names=['nq5-b1-executor','nq5-b1-r1-remediation','nq5-b1-r2-contracts','nq5-b1-r3-resume','nq5-b1-r3-r1-semantics','nq5-b1-r3-r2-signed-flow']
 await suite('execution-adversarial','node',['node_modules/vitest/vitest.mjs','run',...names.map(n=>'tests/unit/'+n+'.test.mjs'),'--reporter=dot']);await suite('source-validator','python3',['VALIDATE_SOURCE_SET.py'],path.join(root,'docs/source/v1.7.0'));await suite('report-schema-controls','python3',['scripts/test-nq5-report-validation.py']);await suite('typecheck-lint','npm',['run','check']);await suite('acquisition-compile','npm',['run','acquisition:compile']);await suite('unit-regression','node',['node_modules/vitest/vitest.mjs','run','tests/unit',...names.flatMap(n=>['--exclude','tests/unit/'+n+'.test.mjs']),'--reporter=dot']);await suite('acquisition-regression','node',['node_modules/vitest/vitest.mjs','run','tests/acquisition','--reporter=dot']);await suite('browser-accessibility-performance','npm',['run','test:e2e','--','--reporter=line']);await suite('production-build','npm',['run','build']);await suite('browser-boundary','npm',['run','browser-boundary:verify']);await suite('records-office-boundary','npm',['run','g6p:a1:boundary:verify']);await suite('euler-public-pack','npm',['run','g6:pack:verify']);await suite('project-clock-status','npm',['run','project:status']);await suite('history-secret-boundary','node',['scripts/verify-git-secret-history.mjs']);assert();write(local,'VERIFICATION.json',{schemaVersion:'1.0.0',status:'PASS',generatedAtUtc:new Date().toISOString(),...start,suites,credentialAccess:false,actualPrivateStateAccess:false,privateMutation:false,authenticatedNansenProviderRequests:0,unauthenticatedDocumentationGets:0,accountRequests:0,browserProviderRequests:0,networkHold:true,scope:'ISOLATED_LOCAL_REGRESSION_ONLY_LOOPBACK_TEST_SERVER_NOT_PROVIDER_RUNTIME'});process.stdout.write('R32_ALL14_LOCAL_SUITES_PASS\n')
}
function localGate(){const v=read('VERIFICATION.json'),age=Date.now()-Date.parse(v.generatedAtUtc);if(v.status!=='PASS'||identity(v.candidate)!==identity(cut(root))||v.implementationSha256!==digest(root)||!Number.isFinite(age)||age<0||age>86400000||v.suites.length!==14||identity(v.suites.map(s=>s.name).sort())!==identity([...LOCAL_SUITES].sort())||v.credentialAccess!==false||v.actualPrivateStateAccess!==false||v.privateMutation!==false||v.authenticatedNansenProviderRequests!==0||v.unauthenticatedDocumentationGets!==0||v.accountRequests!==0||v.browserProviderRequests!==0||v.networkHold!==true)throw new Error('R32_ALL14_CURRENT_SUITES_REQUIRED');for(const s of v.suites){const b=fs.readFileSync(path.join(local,s.name+'.log'));if(s.status!=='PASS'||!b.toString().trim()||sha(b)!==s.sha256)throw new Error('R32_DIRECT_LOG_IDENTITY')}return v}
function reviewGate(n,checkpoint){const r=JSON.parse(fs.readFileSync(path.join(root,n))),env=childEnv;if(r.status!=='PASS_BOUNDED_NO_CREDENTIAL_SCOPE'||r.checkpoint!==checkpoint||r.implementationSha256!==digest(root)||r.unresolvedAcceptedP0P1!==0||r.credentialAccess!==false||r.actualPrivateStateAccess!==false||r.providerRequests!==0||r.externalDocumentationGets!==0||r.lenses.length!==8||identity(r.lenses.map(l=>l.name).sort())!==identity([...REVIEW_LENSES].sort())||r.lenses.some(l=>l.status!=='PASS_BOUNDED_SCOPE'))throw new Error('R32_TWO_DEDICATED_REVIEWS_REQUIRED');const tree=execFileSync('git',['rev-parse',r.reviewedImplementationCommit+'^{tree}'],{cwd:root,env,encoding:'utf8'}).trim();if(tree!==r.reviewedImplementationTree)throw new Error('R32_REVIEW_TREE');execFileSync('git',['merge-base','--is-ancestor',r.reviewedImplementationCommit,'HEAD'],{cwd:root,env});return r}
const files=dir=>fs.readdirSync(dir).sort().flatMap(n=>{const f=path.join(dir,n),s=fs.lstatSync(f);if(s.isSymbolicLink())throw new Error('R32_ARCHIVE_SYMLINK');return s.isDirectory()?files(f):[f]})
async function deliver(){const v=localGate(),reviews=REVIEWS.map((n,i)=>reviewGate(n,i===0?'R3_R2_REVIEW_A_SIGNED_FLOW':'R3_R2_REVIEW_B_FRONTIER')),r=derive(),candidate=cut(root);if(fs.existsSync(path.join(parent,OUTPUT)))throw new Error('R32_EXISTING_ARCHIVE_PRESERVED');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'trace-b1-r3-r2-delivery-')),delivery=path.join(temp,'delivery');fs.mkdirSync(delivery)
 try{const payload={},bindings=[],put=(n,x)=>{payload[n]=serialize(x);write(delivery,n,payload[n])},putLog=(n,x)=>{const s=sanitizeLog(x,root);if(!s.text.trim())throw new Error('R32_EMPTY_DELIVERY_LOG');put(n,s.text);bindings.push({file:n,sourceSha256:s.sourceSha256,sanitizedSha256:s.sanitizedSha256,otherPathRedactions:s.otherPathRedactions})};for(const[n,x]of Object.entries(r.entries))put(n,x)
 put('README.md','# TRACE//ESCAPE B1-R3-R2\n\n'+r.status+'. Local-only exact signed-flow compatibility and per-call support; no credential, external request, new credit or private write. Supplier4 immutable; local Lead-acceptance candidates'+r.leadAcceptanceCandidates+'; held'+(4-r.leadAcceptanceCandidates)+'; final Lead-accepted count0. Direction requires sent/from or received/to, never sign alone. Exact magnitude removes only one admitted leading minus; signed/bucket/role/profile conversion metadata is explicitly bound in the safe matrix/audit. Zero/incidental rows have no qualification utility; duplicates cannot inflate results. Only independently supportable calls enter the full-campaign corrected index and durable frontier lineage. Batch2 candidate, if present, is smallest meaningful and not authorized to issue. Accounting3395=campaign6+unattributed3389 and R3interval846=campaign4+unattributed842; no cause assigned. Powered by Nansen API. Contextual unzoned activity only, no invented UTC/exact proof/negative evidence/completeness. No floor/final qualification/integration/product/art/narrative/Mission02/hosting/release claim. Stop for Lead review and before every external request.\n')
 put('DELIVERY_MANIFEST.json',{schemaVersion:'1.0.0',status:r.status,candidate,implementationSha256:digest(root),signedFlowContractSha256:CONTRACT_SHA,acceptedR3R1ArchiveSha256:ARCHIVE_SHA,sourceManifestSha256:r.accepted.sourceManifestSha256,immutablePrivateStateIdentity:r.privateStateIdentity,leadAcceptanceCandidates:r.leadAcceptanceCandidates,semanticallySupportableTerminals:r.semanticallySupportable,supplierCounts:4,leadAcceptedCount:0,cumulativeAttempts:6,cumulativeProvider2xx:6,cumulativeKnownCredits:6,newGateAttempts:0,newGateCredits:0,candidateCount:r.candidateCount,batch2PlanGenerated:r.batch2PlanGenerated,AUTHORIZED_TO_ISSUE:false,credentialAccess:false,externalRequests:0,documentationGets:0,accountRequests:0,privateMutation:false,privateBytesPackaged:false,privatePathsPackaged:false,labelsPackaged:false,assetLanePackaged:false})
 put('SOURCE_INSTALL/SIGNED_FLOW_CONTRACT_INSTALLATION_REPORT.json',{schemaVersion:'1.0.0',contractSha256:CONTRACT_SHA,acceptedBaseCommit:BASE,acceptedBaseTree:TREE,acceptedArchiveSha256:ARCHIVE_SHA,unchangedFoundationSourceFiles:64,additiveSourceFiles:1,all65SourceHashesVerified:true,acceptedR3R1FileIdentityChecks:Object.entries(r.accepted.priorFiles).map(([file,b])=>({file,sha256:sha(b),status:'PASS'})),documentationReuse:'EXACT_ACCEPTED_R3_FIVE_LOCAL_BYTES_NO_NEW_RETRIEVAL'})
 put('SOURCE_INSTALL/ACTIVE_SOURCE_MANIFEST.sha256',fs.readFileSync(path.join(root,MANIFEST)));put('EVIDENCE/BUGBOT_SIGNED_FLOW_REVIEW.json',reviews[0]);put('EVIDENCE/BUGBOT_FRONTIER_REVIEW.json',reviews[1]);put('EVIDENCE/REVIEW_FINDINGS_RESOLUTIONS.json',{schemaVersion:'1.0.0',unresolvedAcceptedP0P1:0,reviews,leadFindingsImplemented:['SUBJECT_PARTICIPATION','EXPLICIT_SIGN_BUCKET_MAGNITUDE_COMPATIBILITY_PER_CALL_ACCEPTANCE','DETERMINISTIC_DEDUPLICATION','FULL_CAMPAIGN_BINDING','TOTAL_AND_INTERVAL_ACCOUNTING','COMPLETE_FRONTIER_MATRIX_NO_PADDING'],supplierTerminalsNotRewritten:true});put('EVIDENCE/KNOWN_LIMITATIONS.md','# Known limitations\n\nThis is a narrow Lead-owned observed-provider signed-flow rule, not current OpenAPI signed-semantics admission and not literal negative onchain quantities. Metadata is a bound sidecar; the legacy amount identity field represents exact magnitude without precision/exponent normalization. Supplier4 remain immutable; '+r.leadAcceptanceCandidates+' independently supportable local candidates, '+(4-r.leadAcceptanceCandidates)+' held, final Lead counts0. Identity/count mismatch cannot be repaired or reissued. Correction is a proposal only. Held calls do not supply frontier lineage except independently accepted Euler seeds. Batch2 is candidate-only; no issue. Historical/beta families remain held. Optional nulls unknown/omitted, not zero; unzoned times contextual only. No inferred UTC, negative evidence, completeness or causation. Unattributed account change3389 and interval842 have no assigned cause. Reviewers assess safe derived evidence; only the main read-only gate reopens mirrored private bytes. No credential access, external requests, private writes, qualification-floor, final qualification, gameplay integration, product, art, Mission02, hosting or release acceptance.\n')
 for(const n of LOCAL_SUITES)putLog('VERIFICATION/'+n+'.log',fs.readFileSync(path.join(local,n+'.log')));putLog('VERIFICATION/readonly-semantic-accounting-frontier.log',JSON.stringify({acceptedArchiveSha256:ARCHIVE_SHA,sourceFilesVerified:65,privateStateIdentity:r.privateStateIdentity,immutableLedgerBytes:32547,immutableLedgerSha256:r.entries['REPORTS/T1_CAMPAIGN_STATE_REDACTED.json'].ledgerSha256,readonlyAdmission:true,semanticOutcome:r.entries['REPORTS/R3_PER_CALL_QUALIFICATION_ACCEPTANCE_REPORT.json'],perCallEvidenceIdentity:identity(r.entries['EVIDENCE/R3_PER_CALL_SEMANTIC_REVALIDATION.json']),balance:r.entries['EVIDENCE/ACCOUNT_WIDE_BALANCE_RECONCILIATION.json'],frontierMatrixIdentity:identity(r.entries['EVIDENCE/FRONTIER_CANDIDATE_REJECTION_MATRIX.json']),candidateCount:r.candidateCount,noNewProviderOrCredentialOrPrivateWrite:true},null,2)+'\n')
 const bundle=path.join(delivery,'GIT/trace-escape-complete.bundle');fs.mkdirSync(path.dirname(bundle));await run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD']);const bl=await run('git',['bundle','verify',bundle]),clone=path.join(temp,'clone');await run('git',['clone','--quiet',bundle,clone]);const cg=(...args)=>execFileSync('git',args,{cwd:clone,env:childEnv,encoding:'utf8'}).trim();if(cg('rev-parse','HEAD')!==candidate.commit||cg('rev-parse','HEAD^{tree}')!==candidate.tree)throw new Error('R32_BUNDLE_CLONE_IDENTITY');const fl=await run('git',['fsck','--full','--strict'],clone);putLog('VERIFICATION/bundle-clone-fsck.log',bl+'\nFresh clone '+candidate.commit+' / '+candidate.tree+'; fsck exit0 '+(fl.trim()||'no diagnostics')+'\n');put('GIT/trace-escape-complete.bundle',fs.readFileSync(bundle));put('SOURCE_DIFF.patch',execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:root,env:childEnv,maxBuffer:64000000}));fs.cpSync(path.join(root,'dist'),path.join(clone,'dist'),{recursive:true});putLog('VERIFICATION/fresh-clone-source-build-secret.log',await run('node',[path.join(root,'scripts/scan-prohibitions.mjs'),clone]));putLog('VERIFICATION/fresh-clone-history-secret.log',await run('node',['scripts/verify-git-secret-history.mjs'],clone));putLog('VERIFICATION/redacted-delivery-secret.log',await run('node',[path.join(root,'scripts/scan-prohibitions.mjs'),delivery]));put('EVIDENCE/VERIFICATION_SUMMARY.json',{...v,localActualPrivateStateAccess:false,actualPrivateStateAccess:true,actualPrivateStateAccessScope:'READ_ONLY_EXACT_FOUR_RESPONSES_LEDGER_LOCKS_GENESIS',privateMutation:false,credentialAccess:false,externalRequests:0,documentationGets:0,accountRequests:0,privateStateUnchangedIdentity:r.privateStateIdentity,directEvidence:'VERIFICATION/readonly-semantic-accounting-frontier.log',bundleFreshCloneIdentityVerified:true,deliveryLogBindings:bindings});const scan=pathScan(payload);if(scan.status!=='PASS')throw new Error('R32_ABSOLUTE_PATH_LEAK');put('EVIDENCE/VERIFICATION_SUMMARY.json',{...JSON.parse(payload['EVIDENCE/VERIFICATION_SUMMARY.json']),pathRedactionScan:scan})
 const allowed=new Set(['README.md','DELIVERY_MANIFEST.json','MANIFEST.sha256','GIT/trace-escape-complete.bundle','SOURCE_DIFF.patch','SOURCE_INSTALL/SIGNED_FLOW_CONTRACT_INSTALLATION_REPORT.json','SOURCE_INSTALL/ACTIVE_SOURCE_MANIFEST.sha256','CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json','CONTRACTS/ADDRESS_TRANSACTIONS_SIGNED_FLOW_COMPATIBILITY_PROFILE.json','EVIDENCE/R3_SIGN_BUCKET_DIRECTION_MATRIX.json','SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json','SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json','REPORTS/R3_PER_CALL_QUALIFICATION_ACCEPTANCE_REPORT.json','REPORTS/T1_CAMPAIGN_STATE_REDACTED.json','PUBLIC/NQ5_PUBLIC_CALL_INDEX.json','PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256','PLANS/T1_BATCH2_CANDIDATE_PLAN.json','PLANS/T1_BATCH2_RESERVE_PLAN.json','PLANS/T1_BATCH2_FRONTIER_POLICY.json','EVIDENCE/R3_PER_CALL_SEMANTIC_REVALIDATION.json','EVIDENCE/NANSEN_API_REQUEST_AUDIT.json','EVIDENCE/PUBLIC_INDEX_CAMPAIGN_BINDING_CROSSWALK.json','EVIDENCE/ACCOUNT_WIDE_BALANCE_RECONCILIATION.json','EVIDENCE/FRONTIER_CANDIDATE_REJECTION_MATRIX.json','EVIDENCE/FRONTIER_UTILITY_AND_ISSUABILITY_REPORT.json','EVIDENCE/BUGBOT_SIGNED_FLOW_REVIEW.json','EVIDENCE/BUGBOT_FRONTIER_REVIEW.json','EVIDENCE/VERIFICATION_SUMMARY.json','EVIDENCE/REVIEW_FINDINGS_RESOLUTIONS.json','EVIDENCE/KNOWN_LIMITATIONS.md','QUALIFICATION_COUNT_CORRECTION_PROPOSAL.json']);for(const file of files(delivery)){const n=path.relative(delivery,file);if(!allowed.has(n)&&!/^VERIFICATION\/[a-z-]+\.log$/.test(n))throw new Error('R32_ARCHIVE_ALLOWLIST')}
 put('MANIFEST.sha256',files(delivery).map(f=>sha(fs.readFileSync(f))+'  '+path.relative(delivery,f)).sort().join('\n')+'\n');const final=derive();if(identity(cut(root))!==identity(candidate)||identity(Object.entries(r.entries).map(([n,x])=>[n,sha(serialize(x))]))!==identity(Object.entries(final.entries).map(([n,x])=>[n,sha(serialize(x))])))throw new Error('R32_FINAL_EVIDENCE_CHANGED');const names=files(delivery).map(f=>{fs.utimesSync(f,new Date('2000-01-01T00:00:00Z'),new Date('2000-01-01T00:00:00Z'));return path.relative(delivery,f)}).sort(),z=path.join(temp,'delivery.zip'),rebuilt=path.join(temp,'rebuilt.zip');await run('zip',['-X','-q',z,...names],delivery);await run('zip',['-X','-q',rebuilt,...names],delivery);if(sha(fs.readFileSync(z))!==sha(fs.readFileSync(rebuilt)))throw new Error('R32_ARCHIVE_REBUILD_IDENTITY');await run('unzip',['-t',z]);const extracted=path.join(temp,'extracted');fs.mkdirSync(extracted);await run('unzip',['-q',z,'-d',extracted]);await run('sha256sum',['-c','MANIFEST.sha256'],extracted);const output=path.join(parent,OUTPUT);fs.copyFileSync(z,output,fs.constants.COPYFILE_EXCL);process.stdout.write(JSON.stringify({status:r.status,archive:output,sha256:sha(fs.readFileSync(output)),supplierCounts:4,leadAcceptedCount:0,semanticallySupportable:r.semanticallySupportable,frontierCandidatesEvaluated:r.candidateCount,batch2PlanGenerated:r.batch2PlanGenerated,newProviderAttempts:0,newCredits:0,privateMutation:false})+'\n')
 }finally{fs.rmSync(temp,{recursive:true,force:true})}
}
async function main(){if(process.argv.length!==3)throw new Error('R32_UNSUPPORTED_MODE');switch(process.argv[2]){case'--derive':deriveLocal();break;case'--local':await verify();break;case'--deliver':await deliver();break;default:throw new Error('R32_NO_EXTERNAL_OR_EXECUTION_MODE')}}
main().catch(e=>{process.stderr.write((/^R32_[A-Z0-9_]+$/.test(e.message)?e.message:'R32_FAIL_CLOSED_LOCAL_ONLY')+'; no external request, credential access or private repair.\n');process.exitCode=1})
