import { identity, sha, validateSchema } from '../nq5/schema.mjs'
import { parseExactJson } from '../nq5/exact-json.mjs'
import { amountClass, validAddress, CAMPAIGN, assertCampaignRecord } from '../nq5-b1-r3-r1/semantics.mjs'
import { temporal, profile as observedProfile } from '../nq5-b1-r3/compatibility.mjs'
import { IDS } from '../nq5-b1-r3/authority.mjs'
import { seal, CONTRACT_SHA, ARCHIVE_SHA } from './authority.mjs'
export { CAMPAIGN }
export const RULE='SIGNED_FLOW_TO_UNSIGNED_TRANSFER_MAGNITUDE'
export function profile(a){const c=a.context;return seal({schemaVersion:'1.0.0',leadOwnedObservedProviderRule:true,officialSignedSemanticsAdmission:false,executionContractSha256:CONTRACT_SHA,acceptedR3R1ArchiveSha256:ARCHIVE_SHA,acceptedR3ArchiveSha256:a.r3ArchiveSha256,scope:{method:'POST',path:'/api/v1/profiler/address/transactions',chain:'ethereum',family:'profiler/address/transactions',tokenTransfersOnly:true},observedNullTimeProfileIdentity:c.profile.hash,compatibilitySchemaIdentity:c.profile.compatibilitySchemaIdentity,acceptedTruthSha256:c.truth.sha256,bucketRules:{TOKENS_SENT:'REQUEST_SUBJECT_EQUALS_FROM_CASE_INSENSITIVE',TOKENS_RECEIVED:'REQUEST_SUBJECT_EQUALS_TO_CASE_INSENSITIVE'},normalizationRule:RULE,directionFromSign:false,removeExactlyOneAdmittedLeadingMinus:true,allOtherLexemeBytesUnchanged:true,floatingPointConversion:false,rounding:false,zeroRole:'VALID_RAW_EVENT_EXCLUDED_FROM_THIS_QUALIFICATION_UTILITY',incidentalRowsExcluded:true,bucketContradictionFailsResponse:true,deterministicMagnitudeTransferDeduplication:true,selfTransferAcrossBucketsDeduplicates:true,perLogicalRequestAcceptance:true,immutableTerminalEqualityRequired:true,normalizedIdentityPayload:'EXISTING_ALLOWLIST_AMOUNT_FIELD_IS_EXACT_AMOUNT_MAGNITUDE_NO_METADATA_HASH_MIGRATION',conversionMetadata:'SAFE_PER_ROW_SIGN_BUCKET_DIRECTION_MATRIX_BOUND_TO_NORMALIZED_IDENTITY_AND_PROFILE',excludedRoles:['BALANCE','NATIVE_VALUE','NFT','LABEL','HELD_FAMILY','OTHER_ENDPOINT'],privateRawImmutable:true,labelsPricesUsdValuesOmitted:true,temporalPolicyUnchanged:true,noInferredUtcOrNegativeEvidenceOrCompleteness:true,AUTHORIZED_TO_ISSUE:false})}
export const magnitudeIdentity=r=>identity([r.transaction_hash.toLowerCase(),r.from_address.toLowerCase(),r.to_address.toLowerCase(),r.token_address.toLowerCase(),r.amount])
export function signedTransfers(exact,request,times,p,providerRequestId=null){
 if(request.family!=='profiler/address/transactions'||request.method!=='POST'||request.path!=='/api/v1/profiler/address/transactions'||request.body.chain!=='ethereum'||!validAddress(request.body.address))throw new Error('SIGNED_FLOW_ENDPOINT_SCOPE')
 const subject=request.body.address.toLowerCase(),stats={rawTransactionRecords:exact.data.length,rawTransferRows:0,sentRows:0,receivedRows:0,positiveRows:0,negativeRows:0,zeroRows:0,subjectInvolvedRows:0,incidentalRows:0,fromRows:0,toRows:0,selfRows:0,bucketContradictions:0,eligibleNonzeroRows:0,duplicateRows:0,uniqueAdmittedRows:0},matrix=[],records=[],seen=new Set(),tokens=new Set();let contradiction=false
 for(const[i,tx]of exact.data.entries()){
  if(tx.chain!=='ethereum'||!/^0x[0-9a-f]{64}$/i.test(tx.transaction_hash)||!times[i])throw new Error('SIGNED_FLOW_TRANSACTION_CORE')
  if(![...(tx.tokens_sent??[]),...(tx.tokens_received??[])].length)throw new Error('SIGNED_FLOW_TRANSFER_CORE')
  for(const[bucket,key]of [['TOKENS_SENT','tokens_sent'],['TOKENS_RECEIVED','tokens_received']])for(const t of tx[key]??[]){
   if(t.chain!=='ethereum'||![t.from_address,t.to_address,t.token_address].every(validAddress))throw new Error('SIGNED_FLOW_TRANSFER_CORE')
   const sign=amountClass(t.token_amount),from=t.from_address.toLowerCase()===subject,to=t.to_address.toLowerCase()===subject,role=from&&to?'SELF':from?'FROM':to?'TO':'NONE',involved=from||to,consistent=bucket==='TOKENS_SENT'?from:to,eligible=involved&&consistent&&sign!=='ZERO',magnitude=eligible?(t.token_amount.startsWith('-')?t.token_amount.slice(1):t.token_amount):null
   stats.rawTransferRows++;stats[bucket==='TOKENS_SENT'?'sentRows':'receivedRows']++;stats[sign==='POSITIVE'?'positiveRows':sign==='NEGATIVE'?'negativeRows':'zeroRows']++;stats[involved?'subjectInvolvedRows':'incidentalRows']++;if(role!=='NONE')stats[role==='SELF'?'selfRows':role==='FROM'?'fromRows':'toRows']++
   if(involved&&!consistent){contradiction=true;stats.bucketContradictions++}
   const joined=times[i].exactUtcFromAcceptedTruth,r=eligible?{transaction_hash:tx.transaction_hash,from_address:t.from_address,to_address:t.to_address,token_address:t.token_address,amount:magnitude,evidence_grade:'CONTEXTUAL',temporal_class:times[i].classification,...(joined?{accepted_exact_utc:joined,accepted_exact_time_source:'ACCEPTED_EULER_TRUTH_HASH_JOIN'}:{})}:null,id=r?magnitudeIdentity(r):null,duplicate=eligible&&seen.has(id)
   tokens.add(t.token_address.toLowerCase());if(eligible){stats.eligibleNonzeroRows++;if(duplicate)stats.duplicateRows++;else{seen.add(id);records.push(r)}}
   matrix.push({logicalId:request.logicalId,providerRequestId,transactionHash:tx.transaction_hash,requestedSubject:request.body.address,provider_bucket:bucket,fromAddress:t.from_address,toAddress:t.to_address,tokenAddress:t.token_address,providerSignedDecimalLexeme:t.token_amount,provider_amount_sign:sign,subject_role:role,bucketAddressConsistent:consistent,amount_magnitude:magnitude,duplicateIdentity:id,duplicate,admitted:eligible&&!duplicate,reason:!involved?'INCIDENTAL_NOT_SUBJECT':!consistent?'BUCKET_ADDRESS_CONTRADICTION':sign==='ZERO'?'ZERO_NO_QUALIFICATION_UTILITY':duplicate?'DUPLICATE_CANONICAL_MAGNITUDE_TRANSFER':'ELIGIBLE_NONZERO_SUBJECT_TRANSFER',normalization_rule:eligible?RULE:null,compatibilityProfileIdentity:p.hash})
  }
 }
 const pass=!contradiction&&records.length>0,code=contradiction?'BUCKET_ADDRESS_CONTRADICTION':records.length?'PASS':'NO_UNIQUE_NONZERO_ELIGIBLE_TRANSFER'
 if(!pass)for(const row of matrix)if(row.admitted){row.admitted=false;row.reason='RESPONSE_SEMANTIC_ADMISSION_FAILED'}
 stats.uniqueAdmittedRows=pass?records.length:0
 return {pass,code,stats,matrix,normalizedRecords:pass?records:[],normalizedIdentity:pass?identity(records):null,subjectCandidates:pass?records.map(r=>({...r,amountClass:'POSITIVE'})):[],tokenContracts:[...tokens].sort()}
}
export function admit(a,call,p){
 const c=a.context,q=call.request,row=call.response,raw=call.raw,stages={},fail=(stage,code,semantic=null)=>({safelyAdmissible:false,firstFailedStage:stage,stages:{...stages,[stage]:{status:'FAIL',code}},normalizedRecords:[],normalizedSha256:null,resultCount:0,publicRecord:null,semantic})
 if(identity(p)!==identity(profile(a))||identity(c.profile)!==identity(observedProfile(c.bound,c.oldProfile,c.truth)))throw new Error('R32_PROFILE_DRIFT')
 if(!IDS.includes(q.logicalId)||!c.bound.plan.requests.some(r=>identity(r)===identity(q)))throw new Error('R32_EXACT_FOUR_REQUEST_SCOPE')
 let exact,response;try{if(!Buffer.isBuffer(raw)||sha(raw)!==row.rawSha256||raw.length!==row.rawBytes)throw 0;exact=parseExactJson(raw);response=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(raw));stages.json={status:'PASS'}}catch{return fail('json','RAW_HASH_SIZE_UTF8_OR_DUPLICATE_JSON')}
 try{validateSchema('provider',response,c.profile.compatibilitySchema);stages.schema={status:'PASS',schemaIdentity:c.profile.compatibilitySchemaIdentity}}catch{return fail('schema','EXACT_NULL_TIME_COMPATIBILITY_REJECTED')}
 try{const g=response.pagination;if(g.page!==q.body.pagination.page||g.per_page!==q.body.pagination.per_page||g.page!==1||typeof g.is_last_page!=='boolean'||response.data.length>g.per_page||!g.is_last_page&&!response.data.length)throw 0;stages.pagination={status:'PASS'}}catch{return fail('pagination','EXACT_FROZEN_PAGE_METADATA_REQUIRED')}
 const times=[];try{const seen=new Map();for(const tx of response.data){if(tx.chain!=='ethereum'||!/^0x[0-9a-f]{64}$/i.test(tx.transaction_hash))throw 0;const t=temporal(tx.block_timestamp,q,c.truth.times[tx.transaction_hash.toLowerCase()]),key=tx.transaction_hash.toLowerCase();if(seen.has(key)&&seen.get(key)!==tx.block_timestamp)throw 0;seen.set(key,tx.block_timestamp);times.push(t)}stages.contextualTemporal={status:'PASS',timezoneEstablished:false,acceptedExactHashJoins:times.filter(t=>t.exactUtcFromAcceptedTruth).length}}catch{return fail('contextualTemporal','MALFORMED_OUTSIDE_BOUND_OR_TRUTH_CONFLICT')}
 let semantic;try{semantic=signedTransfers(exact,q,times,p,row.providerRequestId);if(!semantic.pass)return fail('normalization',semantic.code,semantic);stages.normalization={status:'PASS',signedFlowProfileIdentity:p.hash,normalizationRule:RULE,signOnlyDirectionInference:false,exactMagnitudeLexeme:true,zeroAndIncidentalExcluded:true,deterministicDeduplication:true}}catch{return fail('normalization','SIGNED_FLOW_CORE_OR_EXACT_DECIMAL')}
 const normalized=semantic.normalizedRecords
 try{for(const r of normalized){if(amountClass(r.amount)!=='POSITIVE'||Object.keys(r).some(k=>!['transaction_hash','from_address','to_address','token_address','amount','evidence_grade','temporal_class','accepted_exact_utc','accepted_exact_time_source'].includes(k)))throw 0}stages.projection={status:'PASS',allowlistOnly:true,conversionMatrixIdentity:identity(semantic.matrix)}}catch{return fail('projection','MAGNITUDE_PUBLIC_ALLOWLIST_REJECTED',semantic)}
 const prototype=a.objects['REPORTS/T1_B1_R3_RECONCILIATION_REPORT.json'].publicIndex.find(r=>r.request_body_sha256===identity(q.body)),record={...prototype,campaign_id:CAMPAIGN,response_sha256:row.rawSha256,normalized_sha256:semantic.normalizedIdentity,result_count:normalized.length}
 try{if(!prototype||identity(prototype)!==identity(call.terminal.publicRecord))throw 0;assertCampaignRecord(record);validateSchema('public',record);stages.publicSchema={status:'PASS',exactCampaignBinding:true,immutablePublicIdAndSequence:true}}catch{return fail('publicSchema','EXACT_CAMPAIGN_PUBLIC_SCHEMA_REJECTED',semantic)}
 return {safelyAdmissible:true,firstFailedStage:null,stages,normalizedRecords:normalized,normalizedSha256:semantic.normalizedIdentity,resultCount:normalized.length,publicRecord:record,semantic,pagination:exact.pagination}
}
export const supportable=(admission,terminal,bindings=true)=>bindings&&admission.safelyAdmissible&&admission.resultCount>0&&admission.normalizedSha256===terminal.normalizedSha256&&admission.resultCount===terminal.resultCount
