import fs from 'node:fs'
import {sha} from '../nq5-s2/activity.mjs'
import {BASE,TREE,INPUT_SHA} from './constants.mjs'
const out='artifacts/g6p-s4-r1/LANE_A_PREPARED_NOT_SENT/',report='artifacts/g6p-s4-r1/REPORTS/'
fs.mkdirSync(out,{recursive:true})
const files=['src/adventure/sentence.ts','src/adventure/content.ts','src/app/App.tsx','src/controller/content/adapter.ts','src/controller/content/runtime-content.json','scripts/nq5-s4/compile-content.mjs','scripts/nq5-s4-r1/consumers.mjs','tests/unit/s4-r1-remediation.test.ts','tests/e2e/s4-r1-display.spec.ts',report+'TRUTH_HASH_CROSSWALK.json',report+'LANE_A_ADMISSION.json',report+'PRESERVATION.json',report+'CONSUMER_MANIFEST.json']
const contract={status:'PREPARED_NOT_SENT',interface:'TE-IFACE-CONTENT@1.1.0',contentInterfaceIdentity:'7d682d883fc55b80ed3c5ea752ea942d94000942257dd93a3eddc22a66c36903',contentIdentity:'540623c9e7f973f0f1cfa4bd4aa5b27f5150247004a05b61ab3a8791b87e0a2e',implementationIdentity:'84a081161b8b3e147021ad497af0862eaf3d7fe80b92f79de8ebe57e7711b46b',reviewedStart:BASE,reviewedTree:TREE,candidateBinding:'Packaged contract and outer DELIVERY_MANIFEST independently carry identical exact candidate commit/tree/parent.',packetsSent:false,providerRequests:0,corpusGameplayIntegrated:false,optionalBanterIntegrated:false,finalDensityAccepted:false,acceptedAdditions:JSON.parse(fs.readFileSync(report+'LANE_A_ADMISSION.json')).laneFiles,files:files.map(file=>({file,sha256:sha(fs.readFileSync(file))})),regressionTasks:['All command forms use publicObjectName including hover/focus/no verb/GIVE/USE','Character alt, hotspot aria, speech label, dialogue title and Art Lab name all Arthur','Internal IDs, reducer progression and saved-state remain unchanged','Exactly 74 consumed client keys; missing mandatory or unconsumed/injected keys rejected','No accepted theory/proof/exact/deferred/optional/performance/title copy emitted','Truth, crosswalk, 37 authoring files and corpus identity byte-preserved','Zero provider/browser external transport']}
fs.writeFileSync(out+'TARGETED_REGRESSION_CONTRACT.json',JSON.stringify(contract,null,2)+'\n')
fs.writeFileSync(out+'README.md','# Lane A corrected targeted regression — PREPARED_NOT_SENT\n\nSupersedes the S4 packet, which is not transmittable. No lane message or acceptance is implied. Obtain the exact integrated candidate from this packaged contract and outer manifest. Validate the hash-bound source corrections, frozen 37 authoring files and preserved truth/corpus via the required reviewed S4 prerequisite. Run original supplier contracts only in their isolated original-base fixture; separately run S4-R1 command/alt/accessibility browser tests, closed consumer-map adversarial tests and full controller regression/type/schema/build/lint/privacy checks. Accepted theory, proof/conclusion, exact evidence, optional banter, final density, title, art/performance and corpus gameplay remain outside the map. Independent MAIN acceptance and subsequent supplier return are not claimed.\n')
fs.writeFileSync(report+'INPUT_ADMISSION.json',JSON.stringify({status:'PASS',inputZipSha256:INPUT_SHA,members:11,governedHashes:9,archiveBoundExceptions:['MANIFEST.sha256','VERIFY_INPUT.py'],validator:'PASS_IN_COMPLETE_ADMITTED_ROOT',referenceInstallByteIdentical:true,baselineReproducer:'Original supplied code unchanged; FINDINGS with both P1/P2 and exit zero in expect-baseline mode.',stoppedPreflight:'Initial one-exception assumption stopped before extraction; corrected to supplied two explicit exceptions.',credentialAccess:false},null,2)+'\n')
console.log(JSON.stringify({status:'PASS',packet:'PREPARED_NOT_SENT',files:files.length,acceptedAdditions:37,packetsSent:false}))
