import fs from 'node:fs'
import assert from 'node:assert/strict'
import {sha} from '../nq5-s2/activity.mjs'
import {verify,extra,allowedPath} from './verify.mjs'
import {compileContent,compileEntries} from '../nq5-s4/compile-content.mjs'
import {consumerManifest,assertClosedClient} from './consumers.mjs'
assert.equal(verify().status,'PASS')
const map=compileContent(),manifest=consumerManifest(map.dead),source=JSON.parse(fs.readFileSync('content/parallel/narrative/COPY_CATALOG.json')),key='lane_a.opening.1'
const missing=structuredClone(source);missing.entries=missing.entries.filter(e=>e.key!==key);assert.throws(()=>compileEntries(missing,manifest),/MISSING_REQUIRED_CONSUMER_KEY/)
const injected=structuredClone(map);injected.entries['lane_a.theory.accepted']={text:'IT JOINED THE SECOND ROUTE',optional:false};assert.throws(()=>assertClosedClient(injected,manifest),/CLIENT_CONSUMER_KEY_SET/)
const hidden=structuredClone(map);hidden.entries[key].text='IT JOINED THE SECOND ROUTE';assert.throws(()=>assertClosedClient(hidden,manifest),/CLIENT_EXACT_OR_ANSWER_TEXT/)
const pruned=structuredClone(map);delete pruned.entries[key];assert.throws(()=>assertClosedClient(pruned,manifest),/CLIENT_CONSUMER_KEY_SET/)
for(const n of ['src/investigation/semantic-ux/x','src/app/corpus-presentation/x','tests/unit/lane-c/x','tests/e2e/lane-c/x','docs/parallel/lane-c/x','content/parallel/narrative/x','public/scenarios/euler-2023-false-exit/scenario.json'])assert.equal(allowedPath(n),false)
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name])
const files=[...new Set([...walk('scripts/nq5-s4-r1'),...extra.filter(n=>fs.existsSync(n))])].sort(),implementationBindings=files.map(file=>({file,sha256:sha(fs.readFileSync(file))}))
const cases=[{case:'Aria/dialogue Arthur while command sentence remains legacy',evidence:'Nine-verb unit forms and native hover/focus/no-verb/GIVE/USE exact assertions; unchanged supplied fixed-mode reproducer'},{case:'Visual name fixed but alt remains legacy',evidence:'Actual child accessible image and exact Arthur alt asserted in native browser, not wrapper metadata'},{case:'One verb/object bypasses helper',evidence:'Shared publicObjectName before all sentence branches; all nine verbs plus completed-request two-object forms tested'},{case:'Tests incorrectly require alias rename',evidence:'Tests demand unchanged source legacy name, stable target/data-speaker/item IDs and actual request stamping; preserved scenes/reducer/query/state'},{case:'Answer-free claim hides accepted-theory key/text',evidence:'Actual client JSON exact key set and full serialization no-theory-text checks; injected key/text rejection'},{case:'Report pruned but browser JSON still has unused answer',evidence:'Build compiler equality to committed imported JSON and independently hash-pinned packaged client bytes'},{case:'Pruning silently loses mandatory consumer',evidence:'Deleted authoring key fails compilation; deleted emitted mandatory key fails closed-map check'},{case:'Truth/corpus/Lane C/source identity drift',evidence:'Exact preservation report for 37 Lane A files, seven truth files, crosswalk, corpus, receipts and reducers; forbidden path sentinels rejected'}]
for(const [number,scope]of [[1,'Complete public visual/accessibility boundaries and internal compatibility'],[2,'Closed actual-client content set, mandatory pruning and exact preservation/package seams']])fs.writeFileSync('artifacts/g6p-s4-r1/REPORTS/REVIEW_'+number+'.json',JSON.stringify({status:'PASS_CLOSED_TASK_OWNED_FINDINGS',independent:false,reviewer:'MAIN_OWNED_DISCLOSED_FALLBACK',scope,implementationBindings,strongestFalseSuccessChecks:cases,executedClosedMapMutationRejections:4,localFindingCorrections:['S4-R1-P1-01','S4-R1-P2-02'],independentMAINAcceptance:false,providerRequests:0,packetsSent:false,unperformed:['Actual AT/contrast/hardware touch','Final Pixel/full integrated journey','Content lock/release/quota acceptance','Supplier targeted return after MAIN']},null,2)+'\n')
console.log(JSON.stringify({status:'PASS',reviews:2,independent:false,strongestFalseSuccessClasses:8,executedClosedMapMutationRejections:4,implementationFiles:files.length}))
