import fs from 'node:fs'
import {sha} from '../nq5-s2/activity.mjs'
import {verify} from './verify.mjs'
const preservation=await verify(),walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name])
const bind=files=>files.sort().map(file=>({file,sha256:sha(fs.readFileSync(file))}))
const source=[...walk('scripts/nq5-s6'),...walk('docs/source/execution-s6').filter(f=>!f.includes('/INPUT/')),'src/controller/foundation/contracts.mjs','src/controller/foundation/pixel-realization.mjs','src/controller/foundation/pixel-realization.d.mts','src/controller/foundation/pixel-review.mjs','src/controller/foundation/pixel-review.d.mts','tests/unit/s6-realization.test.ts','tests/unit/s6-review.test.ts']
const focused=fs.readFileSync('artifacts/g6p-s6/LOGS/focused-typed-final.log','utf8');if(!focused.includes('108 passed')||!focused.includes('EXIT_CODE=0'))throw Error('S6_FOCUSED_REVIEW_BINDING')
for(const checkpoint of [1,2]){
 const report={status:'PASS_TASK_OWNED_FINDINGS_CLOSED_PENDING_MAIN',checkpoint,independent:false,genuineBugbot:false,reviewKind:'DISCLOSED_SAME_AGENT_BOUNDED_FALLBACK',availability:'No callable Bugbot/code-review service in active metadata; no external task/plugin/message/subagent created.',MAINAcceptanceGranted:false,PrincipalArtApprovalGranted:false,preservation,implementationBindings:bind([...source]),focusedChecks:{tests:108,newS6:36,existing:72,file:'artifacts/g6p-s6/LOGS/focused-typed-final.log',sha256:sha(focused)},reviewLenses:checkpoint===1?['Identity correctness','Security/privacy/no-network','Schema/adversarial rejection','Approval/provenance authority']:['Accepted story/puzzle/count semantics','Accessible fallback/focus/recovery boundaries','Source-scope/exception/preservation','Recovery/determinism/package integrity'],closedFindings:checkpoint===1?['Separate duplicate projection never changes accepted exact approval identities','Event alias first-use ordinals preserve distinct equal-looking owners/props','External self-declared receipts/evidence cannot self-grant approval/admission','Strict envelope path/schema rejects traversal; circular control self-hashes avoided']:['All24 beats and11 office reducer transitions source-derived; STATE0 retained','Catalog/client refs explicitly distinct from actual MissionHarness/recovery/hint playback','First-class pending slouch/fourth-wall and older approval gates preserved; optional density/title/production IDs not selected','User scope exception transparently quoted and exact diff constrained'],residuals:['No production Pixel archive or actual bytes inspected','Archive/PNG decoder, external receipt authentication, visual fit and game integration remain future gates','Full candidate-bound1662 unit/acquisition, build/type/lint, fresh exact recovery and standalone tamper/determinism evidence must complete in final package extension'],sourcePromoted:false}
 fs.writeFileSync('artifacts/g6p-s6/REPORTS/REVIEW_'+checkpoint+'.json',JSON.stringify(report,null,2)+'\n')
}
console.log(JSON.stringify({status:'PASS',boundedReviews:2,reviewLenses:8,independent:false,genuineBugbot:false}))
