import { identity } from '../nq5/schema.mjs'
import { openapi } from './contracts.mjs'
const labelFields=schema=>{const names=new Set();const walk=s=>{if(!s||typeof s!=='object')return;for(const [k,v]of Object.entries(s.properties??{})){if(/label/i.test(k))names.add(k);walk(v)};if(s.items)walk(s.items);for(const s2 of [...(s.anyOf??[]),...(s.oneOf??[])])walk(s2)};walk(schema);return [...names].sort()}
export function fallbackSurvey(corpus){
  const rows=[['backtestingBalances','/api/v1beta1/profiler/address/historical-token-balances'],['backtestingTransactions','/api/v1beta1/profiler/address/historical-transactions']].map(([name,endpoint])=>{
    const source=corpus[name],spec=openapi(source.body,endpoint),labels=labelFields(spec.responseSchema),tx=name.endsWith('Transactions')
    const pricingName=tx?'profiler/address/historical-transactions':'profiler/address/historical-token-balances'
    const htmlRow=[...corpus.pricing.body.matchAll(/<tr>([\s\S]*?)<\/tr>/g)].find(m=>m[1].includes('>'+pricingName+'</td>'))?.[1]
    const priceRow=htmlRow?[...htmlRow.matchAll(/<td[^>]*>([^<]*)<\/td>/g)].map(m=>m[1]):null
    const rateRow=corpus.rates.body.split('\n').find(l=>l.startsWith('| Pro (all paid plans)'))??null
    return {documentationUrl:source.url,documentationSha256:source.sha256,endpointPath:endpoint,method:'POST',requestSchema:spec.requestSchema,responseSchema:spec.responseSchema,requestSchemaIdentity:identity(spec.requestSchema),responseSchemaIdentity:identity(spec.responseSchema),stability:'BETA_SUBJECT_TO_BREAKING_CHANGES',historicalSemantics:{requestField:'as_of_date',requestFormat:'date',documentedDescription:spec.operation.description,timezone:'NOT_ESTABLISHED_FOR_INTRADAY_CUTOFF',snapshotLabel:'NOT_ESTABLISHED_FOR_INTRADAY_CUTOFF',intradayCutoffSafety:'NOT_ADMITTED'},chainCoverage:{schemaEnum:spec.requestSchema.properties.chain.enum,proseChains:['ethereum','base','bnb','solana'],proseSchemaDiscrepancy:spec.requestSchema.properties.chain.enum.includes('mantra')},pricing:{capturedTableRow:priceRow,pricingSha256:corpus.pricing.sha256,exactEndpointCostAdmitted:false},rateLimits:{globalProTableRow:rateRow,rateSha256:corpus.rates.sha256,endpointSpecificRuleEstablished:false},pagination:{requestPerPageSchemaMaximum:1000,responsePaginationSchema:spec.responseSchema.properties.pagination,documentedResultCap:tx?20:null,capVersusPaginationAmbiguityHeld:tx},redistribution:{sourceSha256:corpus.redistribution.sha256,exactBetaEndpointNamed:false,status:'HELD_NO_EXACT_PLAN_SPECIFIC_BETA_PUBLIC_USE_ADMISSION'},privacy:{labelFieldNames:labels,labelsPresent:labels.length>0||tx,labelSchemaCoverage:tx?'UNMODELED_TRANSFER_ITEM_SCHEMA_WITH_PROSE_COUNTERPARTY_LABELS':'NO_LABEL_FIELD_IN_CAPTURED_SCHEMA',allLabelsMustRemainPrivate:true,publicProjectionAdmitted:false},proposalOnly:true,admitted:false,publicCallIndexGenerated:false,AUTHORIZED_TO_ISSUE:false,holdReasons:['BETA','DATE_ONLY_CANNOT_PROVE_INTRADAY_CUTOFF','EXACT_PUBLIC_USE_UNESTABLISHED',...(labels.length||tx?['LABEL_BEARING']:[]),...(tx?['TRANSFER_ITEMS_UNTYPED']:[]),...(tx?['20_RESULT_CAP_PAGINATION_UNRESOLVED']:[])]}
  })
  return {schemaVersion:'1.0.0',scope:'TWO_BOUND_DOCUMENTATION_ONLY_BACKTESTING_PROPOSALS',families:rows,providerCalls:0,credentialsAccessed:false,AUTHORIZED_TO_ISSUE:false}
}
