import fs from 'node:fs'
import path from 'node:path'
import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {createHash} from 'node:crypto'
import scenario from '../../public/scenarios/euler-2023-false-exit/scenario.json' with {type:'json'}
import graph from '../../public/scenarios/euler-2023-false-exit/evidence-graph.json' with {type:'json'}
import corpus from '../../artifacts/g6p-s3/REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json' with {type:'json'}
import blueprint from '../../artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.json' with {type:'json'}
import preservation from '../../artifacts/g6p-s5/REPORTS/PRESERVATION.json' with {type:'json'}
import hintLadder from '../../content/parallel/narrative/HINT_LADDER.json' with {type:'json'}
import acceptedCopy from '../../content/parallel/narrative/COPY_CATALOG.json' with {type:'json'}
import runtime from '../../src/controller/content/runtime-content.json' with {type:'json'}
import {buildFrozenFixture} from '../../src/investigation/fixture.ts'
import {availableCards,createInvestigationState,investigationReducer} from '../../src/investigation/state.ts'
import {dispatchQuery} from '../../src/investigation/query.ts'
import {RECORDS_OFFICE_STEPS,TERMINAL_FIRST_RUN,MISSION_INVARIANTS} from '../../src/controller/mission/choreography.ts'
import {puzzleHintCopy,investigationHintCopy} from '../../src/controller/content/adapter.ts'
const BASE='7503ddcc17f0934d810855dc1562d041e17cf93c',TREE='d6ba329c051705ded62b995f297eb07771f497f0'
const out=process.argv[2]??'artifacts/g6p-s7-r1/REPORTS',sha=b=>createHash('sha256').update(b).digest('hex'),fileSha=f=>sha(fs.readFileSync(f)),put=(n,v)=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,n),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n')}
const git=(...a)=>execFileSync('git',a,{encoding:'utf8',maxBuffer:128000000}).trim()
assert.equal(git('rev-parse',BASE+'^{tree}'),TREE)
const fixture=buildFrozenFixture(scenario,graph)
let access=investigationReducer(fixture,createInvestigationState(fixture),{type:'EARN_ACCESS'})
const two=fixture.records.slice(0,2).map(r=>r.id),variants=[access,{...access,selectedRecordId:fixture.openingRecordId},{...access,comparison:two}]
const cards=[...new Map(variants.flatMap(s=>availableCards(fixture,s)).map(c=>[c.id,c])).values()]
const broad=dispatchQuery(fixture,access.query,null)
const baseline={schemaVersion:'1.0.0',status:'PASS_MINIMAL_CONTROLLER_WIRING_REQUIRED',capturedAgainst:BASE,observationCompletedBeforeProductionEdits:true,recordingNote:'Audit observations came from the accepted base during first admission; the report file was written after exact path predeclaration.',identity:{commit:BASE,tree:TREE,parent:'ca0f1ac5672b303e1dd96a7b488fe0715d64c578'},alreadyImplemented:['11 office interaction rules plus arrival and reread','25-record EXPLORE and seven bounded no-match display views','CASE/RESULTS/EXPLORE/SOURCE/LEDGER','Question Receipt, Evidence Delta, three-folder paging and factual two-result table','wrong theory retention,11:38:11 exact correction,three exact proof slots','three journeys,return/reentry,local source-bound save','keyboard/mouse-touch,instant text,reduced motion,focus return'],implementedButNotCoherentlySurfaced:['single exact12-step logical office contract','accepted METHOD/CASE/DIRECT hints selected by current state'],reportsOnly:['24-beat late-bound blueprint','Pixel logical intentions across every beat'],genuinelyMissing:['controller-enforced office contract crosswalk','runtime use of accepted three-tier hint ladder instead of provisional terminal strings','complete data-sufficiency matrix'],intentionallyLateBound:['production art identity and capability binding','coordinates,anchors,files,clips,frames,facing,mirroring,timing,fit,geometry','public title and final dialogue density'],minimalProductionPaths:JSON.parse(fs.readFileSync('docs/source/execution-s7-r1/PREDECLARED_SCOPE.json')).productionPaths,pixelRequired:false}
put('BASELINE_GAP_AUDIT.json',baseline)
put('RECORDS_OFFICE_INTERACTION_CONTRACT.json',{schemaVersion:'1.0.0',status:'IMPLEMENTED_AND_CONTROLLER_ENFORCED',steps:RECORDS_OFFICE_STEPS,acceptedCopyReferencesResolve:RECORDS_OFFICE_STEPS.every(s=>s.id==='ARRIVAL'||acceptedCopy.entries.some(e=>e.key.startsWith(s.copyPrefix+'.'))),hiddenMandatoryActions:0,itemLossOnFailure:false,arthurSolutionDisclosure:false})
put('TERMINAL_FIRST_RUN_FLOW.json',{schemaVersion:'1.0.0',status:'IMPLEMENTED',sequence:TERMINAL_FIRST_RUN,invariants:MISSION_INVARIANTS,questionCards:cards.map(c=>({id:c.id,lens:c.lens,why:c.why,effects:c.effects,resultClass:c.resultClass,mayEstablish:c.mayEstablish,cannotEstablish:c.cannotEstablish,next:c.nextRule})),broadAcceptedDisplayRecords:corpus.displayRecords.length,broadExactFixtureRecords:broad.recordIds.length,mandatoryDispatchesInReferenceDirectFlow:2})
const common=(item,role,teaching,grade,boundary,discover,filter,classification,sufficient=true)=>({item,storyRole:role,teachingRole:teaching,evidenceGrade:grade,claimBoundary:boundary,discoverableAt:discover,surfacedBy:filter,classification,existingDataSufficient:sufficient})
const semantic=corpus.displayRecords.map(d=>common(d.id,'Bounded accepted context for '+d.questionId,'Demonstrates '+d.lens+' filtering and scoped provenance',d.grade,d.claimBoundaries.join('; '),'EXPLORE and display-safe SOURCE',d.question,'foreground_or_optional_context',true))
const noMatch=corpus.displayRecords.filter(d=>d.zeroResultClass).map(d=>d.id)
const exact=fixture.records.map(x=>common(x.id,x.id===fixture.proof.slots.LINK?'First exact correction and LINK proof':Object.values(fixture.proof.slots).includes(x.id)?'Exact proof input':'Accepted exact/corroborating event context',x.id===fixture.proof.slots.LINK?'Corrects the plausible wrong theory fairly':'Separates exact fixture evidence from contextual display',x.grade,x.claimBoundary,'earned record,branch memory,candidate receipt or exact SOURCE',x.transactionHash,Object.values(fixture.proof.slots).includes(x.id)?'exact_receipt_or_proof':'exact_fixture_context',true))
const cardRows=cards.map(c=>common(c.id,'Foreground bounded question','Explains why/effects/result/limits/next',c.resultClass,c.cannotEstablish,'CASE recommended/all cards',c.effects.map(e=>e.field+' '+e.value).join(' AND '),c.stage==='VERIFY'?'exact_receipt':'foreground_question',true))
const items=[...semantic,...exact,...cardRows,...fixture.clues.map(c=>common(c.id,'Reusable clue','Optional category '+c.category,'DISCOVERED',fixture.proof.boundary,'CASE Query Tray',c.filters.map(f=>f.field+' '+f.value).join(' AND '),'clue',true)),common('THEORY.FIRST_TRAIL_STOPS_AT_FIRST_ENGINE','Intelligent plausible wrong theory','Exact evidence revises rather than resets','HYPOTHESIS',fixture.proof.boundary,'persistent Caseboard','player choice','alternative',true),common('TURNING_POINT.11:38:11Z','First exact contradiction','Fair correction','EXACT',fixture.proof.boundary,'exact receipt','RECEIPT transaction predicate','exact_receipt',true),...(['AMOUNT','RECEIVER','LINK'].map(slot=>common('PROOF.'+slot,'Final bounded proof slot','Only independent exact accepted record can fill','EXACT',fixture.proof.boundary,'persistent Caseboard',fixture.proof.slots[slot],'proof',true))),common('SOURCE','Public-safe exact provenance inspection','Provenance without replacing puzzle','DISPLAY_OR_EXACT',fixture.proof.boundary,'SOURCE section','selected record','provenance',true),common('LEDGER','Acquisition/coverage teaching','Separates calls/views/events','AUDIT',fixture.proof.boundary,'LEDGER section','discovered subjects','provenance',true),...['DIRECT_SOLVER','CURIOUS_EXPLORER','MISTAKEN_INVESTIGATOR'].map(j=>common('JOURNEY.'+j,'Distinct player method',j==='DIRECT_SOLVER'?'Question-to-exact path':j==='CURIOUS_EXPLORER'?'EXPLORE/SOURCE/LEDGER/comparison path':'wrong-theory/revision path','JOURNEY',fixture.proof.boundary,'playable end-to-end',j,'journey',true))]
put('DATA_SUFFICIENCY_MATRIX.json',{schemaVersion:'1.0.0',status:'SUFFICIENT_NO_COLLECTION_NEEDED',corpusIdentity:corpus.identity,semanticRecords:25,boundedNoMatches:noMatch.length,exactFixtureRecords:fixture.records.length,items,questions:{plausibleAmbiguityBeforeClues:{answer:true,evidence:'25 contextual/control/alternative/no-match views versus six exact fixture events; unguided sea is intentionally noisy.'},narrowingExplained:{answer:true,evidence:'Query Receipt origins plus Evidence Delta counts and first excluding predicate.'},intelligentWrongTheory:{answer:true,evidence:'FIRST_TRAIL_STOPS_AT_FIRST_ENGINE corrected by exact11:38:11Z event.'},journeysDistinctByMethod:{answer:true,evidence:'Direct uses bounded questions; curious uses local sea/source/ledger/comparison; mistaken records and revises a theory.'},everyForegroundEarnsPlace:{answer:true,evidence:'Cards/folders each name question,match reason,grade,claim limit and next action.'},sourceLedgerSupportingRoles:{answer:true,evidence:'SOURCE proves provenance; LEDGER teaches coverage/acquisition; CASE remains puzzle interface.'},unsupportedBeat:{answer:false,evidence:'All required story,teaching,provenance,test beats map to accepted local data.'}}})
put('PROSPECTIVE_DATA_GAP_REGISTER.json',{schemaVersion:'1.0.0',status:'EMPTY_LOCAL_DATA_SUFFICIENT',externalRequestsAuthorized:0,proposals:[],reason:'No required player-facing story,teaching,provenance or test beat is unsupported by the accepted local corpus.'})
const hints=hintLadder.ladders.map(l=>({id:l.id,selector:l.selector,tiers:Object.fromEntries(Object.entries(l.tiers).map(([tier,key])=>[tier,{copyKey:key,resolves:acceptedCopy.entries.some(e=>e.key===key)}])),noUndiscoveredValue:l.no_undiscovered_value}))
put('DIALOGUE_AND_HINT_WIRING_REPORT.json',{schemaVersion:'1.0.0',status:'PASS',acceptedCatalogFilesEdited:false,compiled74KeyMapBytesPreserved:Object.keys(runtime.entries).length===74,ladder:hints,runtimeSelectors:['all11 office phases','ACCESS_EARNED','CANDIDATE_DISCOVERED','EXACT_CONVERGENCE_VERIFIED'],provisionalGenericTerminalHintRemoved:true,allReferencesResolve:hints.every(h=>Object.values(h.tiers).every(v=>v.resolves)),optionalBanterProgressionRequired:false,finalDialogueDensity:'LATE_BOUND'})
put('DRAFT_DIALOGUE_OPPORTUNITY_MAP.md','# Draft dialogue opportunity map\n\nStatus: NONBINDING — for later Lead/Lane A review. No text below is runtime authority.\n\n- Arrival breathing room: establish Rook’s blockchain-naive observation; tone dry and player-paced.\n- After stamping: optional Arthur correction of a casual nickname; procedural, never solution-bearing.\n- Broad evidence sea: optional reaction to visual noise; reinforce that context is not proof.\n- First candidate comparison: optional restrained disagreement about method, with no undiscovered value.\n- Wrong theory correction: acknowledge revision as good investigation, not failure.\n- Exact receipt: optional brief reaction after the fact; never carries AMOUNT, RECEIVER or LINK.\n- Return to office: optional one-time chemistry beat; skip-safe and nonprogression.\n\nPublic title and final dialogue density remain LATE_BOUND.\n')
put('PIXEL_LOGICAL_CAPABILITY_HANDOFF.json',{schemaVersion:'1.0.0',status:'LOGICAL_ONLY_ART_INDEPENDENT',beats:blueprint.beats.map(b=>({beatId:b.id,actorIntentions:{rook:b.performance.rook.intention,arthur:b.performance.arthur.intention},logicalPropState:b.props,ownershipTransfer:b.id.includes('take-strip')?'canister_to_inventory':b.id.includes('complete-request')||b.id.includes('stamp-request')?'inventory_replacement':'none_or_existing_reducer',visibleContact:b.id.startsWith('OFFICE.')?'REQUIRED_WHERE_EXISTING_INTERACTION_RULE_REQUIRES_IT':'OPTIONAL',semanticFallback:'STATIC_WITH_SEMANTIC_TEXT',accessibility:'Logical focus destination and instant text; no audio/color/motion-only meaning.',optionalReaction:'LATE_BOUND_NONPROGRESSION'})),productionIdentityBound:false,archiveInspected:false})
const frozen=preservation.laneAFiles.map(f=>({file:f.file,expected:f.sha256,actual:fileSha(f.file)}));assert.ok(frozen.every(f=>f.expected===f.actual))
put('PRESERVATION_AND_NO_EFFECTS.json',{schemaVersion:'1.0.0',status:'PASS',base:BASE,tree:TREE,laneAFiles:frozen.length,laneAFilesExact:true,laneCSourceExact:true,corpusIdentity:corpus.identity,semanticRecords:corpus.conceptCount,boundedNoMatches:noMatch.length,stateDisplayRecords:corpus.displayRecords.filter(d=>d.lens==='STATE'&&!d.zeroResultClass).length,clientMapKeys:Object.keys(runtime.entries).length,clientMapSha256:fileSha('src/controller/content/runtime-content.json'),blueprintSha256:fileSha('artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.json'),title:'LATE_BOUND',dialogueDensity:'LATE_BOUND',productionArtApproved:false,externalRequests:0,credentialAccess:false,pixelArchiveAccess:false,providerCalls:0,laneMessages:0,contentLock:false,release:false,mission02:false})
const bindings=['src/controller/content/adapter.ts','src/controller/mission/choreography.ts','src/adventure/types.ts','src/adventure/reducer.ts','src/investigation/state.ts','tests/unit/s7-r1-mission-choreography.test.ts'].map(file=>({file,sha256:fileSha(file)}))
for(const [n,focus] of [['SELF_REVIEW_PUZZLE.json','Puzzle fairness,teaching rhythm,recovery,hint seam,data sufficiency'],['SELF_REVIEW_SCOPE.json','Scope preservation,art independence,accessibility,packaging,exact-source identity']])put(n,{schemaVersion:'1.0.0',status:'PASS_LOCAL_READ_ONLY_PENDING_MAIN',focus,independent:false,reviewer:'Same-agent disclosed self-review; not independent MAIN acceptance.',bindings,lenses:['fairness and no hidden action','teaching and bounded dispatch rhythm','wrong/repeat/recovery state preservation','accepted copy and no-undiscovered-value hints','data sufficiency and exact/context separation','one-production-scope preservation','art-independent semantics','accessibility/input equivalence/focus','offline/no effects','recoverability and Lead transparency'].map(lens=>({lens,status:'PASS'}))})
console.log(JSON.stringify({status:'PASS_PENDING_MAIN',steps:RECORDS_OFFICE_STEPS.length,semanticRecords:corpus.conceptCount,boundedNoMatches:noMatch.length,cards:cards.length,reports:11,dataGapProposals:0}))
