import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto'
const BASE='7503ddcc17f0934d810855dc1562d041e17cf93c',TREE='d6ba329c051705ded62b995f297eb07771f497f0',NAME='TRACE_ESCAPE_G6P_NQ5_T1_S7_R1_OFFLINE_MISSION_CHOREOGRAPHY_DELIVERY_v1.0.0.zip'
const root=process.cwd(),[pflag,primary,oflag,output]=process.argv.slice(2);assert.equal(pflag,'--primary-reference-root');assert.equal(oflag,'--output-directory')
const sha=b=>createHash('sha256').update(b).digest('hex'),run=(c,a,cwd=root,env=process.env)=>execFileSync(c,a,{cwd,env,encoding:c==='git'||c==='node'?'utf8':undefined,maxBuffer:128000000}),git=(...a)=>String(run('git',a)).trim()
const metadata=()=>({head:String(run('git',['rev-parse','HEAD'],primary)).trim(),status:String(run('git',['status','--porcelain=v1','--untracked-files=no'],primary)).trim()}),before=metadata();assert.deepEqual(before,{head:'0f52131c9f56f49128e7a413396331917e687a1f',status:'M AGENTS.md'})
const candidate={commit:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),parent:git('rev-parse','HEAD^')};assert.equal(candidate.parent,BASE);assert.equal(git('rev-parse',BASE+'^{tree}'),TREE);assert.equal(git('rev-list','--merges',BASE+'..HEAD'),'');assert.equal(git('diff','--name-only','HEAD'),'');assert.equal(git('rev-parse','HEAD:AGENTS.md'),git('rev-parse',BASE+':AGENTS.md'))
const allowed=n=>['src/controller/content/adapter.ts','src/controller/mission/choreography.ts','src/adventure/types.ts','src/adventure/reducer.ts','src/investigation/state.ts','tests/unit/s7-r1-mission-choreography.test.ts'].includes(n)||n.startsWith('scripts/nq5-s7-r1/')||n.startsWith('docs/source/execution-s7-r1/')||n.startsWith('artifacts/g6p-s7-r1/')
const changed=git('diff','--name-only',BASE,'HEAD').split('\n').filter(Boolean);assert.ok(changed.length&&changed.every(allowed))
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'s7-r1-delivery-')),dir=path.join(tmp,'payload'),fresh=path.join(tmp,'fresh');fs.mkdirSync(dir);const members=new Map(),put=(n,v)=>{const b=Buffer.isBuffer(v)?v:Buffer.from(typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');assert.ok(!members.has(n)&&!n.startsWith('/')&&!n.split('/').some(x=>['','..','.'].includes(x)));const f=path.join(dir,n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,b,{flag:'wx'});members.set(n,b)}
const bundle=path.join(tmp,'incremental.bundle');run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD','^'+BASE]);const bb=fs.readFileSync(bundle),diff=execFileSync('git',['diff','--binary',BASE,'HEAD'],{cwd:root,maxBuffer:128000000});put('GIT/trace-escape-s7-r1-incremental.bundle',bb);put('SOURCE_DIFF.patch',diff)
put('EVIDENCE/CHANGED_PATHS.json',{status:'PASS',candidate,base:BASE,linearCommits:[candidate.commit],merges:0,paths:changed.map(file=>({file,sha256:sha(execFileSync('git',['show','HEAD:'+file],{cwd:root,maxBuffer:128000000}))})),productionPaths:changed.filter(x=>x.startsWith('src/'))})
for(const [source,prefix] of [['artifacts/g6p-s7-r1/REPORTS','REPORTS'],['artifacts/g6p-s7-r1/LOGS','LOGS'],['docs/source/execution-s7-r1','SOURCE_INPUT']])for(const f of fs.readdirSync(source,{recursive:true,withFileTypes:true}).filter(e=>e.isFile()).map(e=>path.join(e.parentPath??e.path,e.name)).sort())put(prefix+'/'+path.relative(source,f).split(path.sep).join('/'),fs.readFileSync(f))
const preservation=JSON.parse(fs.readFileSync('artifacts/g6p-s7-r1/REPORTS/PRESERVATION_AND_NO_EFFECTS.json'));assert.equal(preservation.status,'PASS');assert.equal(preservation.externalRequests,0)
const manifest={schemaVersion:'1.0.0',status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',candidate,reviewedBase:BASE,reviewedTree:TREE,productionChanges:changed.filter(x=>x.startsWith('src/')).length,unitAcquisitionTests:2357,browserChecks:19,recordsOfficeSteps:12,semanticDisplayRecords:25,boundedNoMatches:7,exactFixtureRecords:6,dataGapProposals:0,title:'LATE_BOUND',dialogueDensity:'LATE_BOUND',LaneAPASS:false,sourcePromoted:false,productionArtApproved:false,externalRequests:0,credentialAccess:false,pixelArchiveAccess:false,laneMessages:0,bundleSha256:sha(bb),sourceDiffSha256:sha(diff),incrementalPrerequisite:BASE}
put('DELIVERY_MANIFEST.json',manifest);put('00_READ_ME_FIRST.md','S7-R1 DELIVERED_PENDING_MAIN_LEAD_REVIEW. This lean offline bundle recovers one exact linear candidate from prerequisite '+BASE+'. Run node VERIFY_DELIVERY.mjs after safe unique regular extraction. The exact12-step office contract is controller-enforced; accepted state-sensitive hint references replace provisional terminal hints. The data audit distinguishes25 semantic display records/seven bounded no-matches from six exact fixture records and finds no collection gap.2357 unit/acquisition tests and19 browser checks passed. Two stopped attempts and two disclosed same-agent self-reviews are included. No independent MAIN acceptance, source promotion, art approval, title/dialogue binding, Pixel archive inspection, external request, credential access, content lock, release or Mission02. The prepared logical Pixel handoff binds no production identity. Final ZIP SHA-256 is the external trust root; embedded hashes are integrity checks, not a signature.\n')
const expected=JSON.stringify(manifest),privacy=String(fs.readFileSync('scripts/nq5-s1/privacy.mjs')).split('export function privatePathFindings')[1].split('export function currentTreeScan')[0],secret=String(fs.readFileSync('scripts/secret-patterns.mjs')).replace('export function','function')
let verifier=''
const seal=()=>{const names=[...members.keys(),'VERIFY_DELIVERY.mjs','MANIFEST.sha256'].sort(),pins=Object.fromEntries([...members].map(([n,b])=>[n,sha(b)]));verifier="import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';const root=path.dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex'),names="+JSON.stringify(names)+",expected="+expected+",pins="+JSON.stringify(pins)+";"+secret+"\nfunction privatePathFindings"+privacy+"\nconst walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const p=path.join(d,e.name),s=fs.lstatSync(p);if(s.isSymbolicLink()||(!s.isDirectory()&&(!s.isFile()||s.nlink!==1)))throw Error('NONREGULAR');return s.isDirectory()?walk(p):[path.relative(root,p).split(path.sep).join('/')]});if(JSON.stringify(walk(root).sort())!==JSON.stringify(names))throw Error('EXACT_MEMBERS');for(const[n,h]of Object.entries(pins))if(sha(fs.readFileSync(path.join(root,n)))!==h)throw Error('PIN');if(JSON.stringify(JSON.parse(fs.readFileSync(path.join(root,'DELIVERY_MANIFEST.json'))))!==JSON.stringify(expected))throw Error('MANIFEST');const seen=new Set;for(const l of fs.readFileSync(path.join(root,'MANIFEST.sha256'),'utf8').trim().split('\\n')){const h=l.slice(0,64),n=l.slice(66);if(seen.has(n)||sha(fs.readFileSync(path.join(root,n)))!==h)throw Error('HASH');seen.add(n)}if(seen.size!==names.length-1)throw Error('HASH_COUNT');console.log(JSON.stringify({status:'PASS',members:names.length,candidate:expected.candidate,terminalStatus:expected.status}));\n";put('VERIFY_DELIVERY.mjs',verifier);put('MANIFEST.sha256',[...members].sort(([a],[b])=>a.localeCompare(b)).map(([n,b])=>sha(b)+'  '+n).join('\n')+'\n');return names}
const names=seal();run('node',['VERIFY_DELIVERY.mjs'],dir)
fs.mkdirSync(fresh);run('git',['init','--quiet'],fresh);fs.mkdirSync(path.join(fresh,'.git/objects/info'),{recursive:true});fs.writeFileSync(path.join(fresh,'.git/objects/info/alternates'),git('rev-parse','--path-format=absolute','--git-path','objects')+'\n');run('git',['bundle','verify',bundle],fresh);run('git',['fetch','--quiet',bundle,'HEAD:refs/heads/candidate'],fresh);run('git',['checkout','--quiet','candidate'],fresh);assert.equal(String(run('git',['rev-parse','HEAD'],fresh)).trim(),candidate.commit);run('git',['fsck','--full','--strict'],fresh);assert.ok(diff.equals(execFileSync('git',['diff','--binary',BASE,'HEAD'],{cwd:fresh,maxBuffer:128000000})));fs.symlinkSync(path.join(root,'node_modules'),path.join(fresh,'node_modules'),'dir');const env={...process.env,PATH:path.join(root,'node_modules/.bin')+path.delimiter+process.env.PATH,NODE_OPTIONS:'--require '+path.join(root,'scripts/nq5-r2/hold.cjs'),CI:'1',NO_COLOR:'1'};run('node',['--loader','./scripts/nq5-s5/ts-loader.mjs','scripts/nq5-s7-r1/generate.mjs',path.join(tmp,'reports')],fresh,env);run('node',['node_modules/vitest/vitest.mjs','run','tests/unit/s7-r1-mission-choreography.test.ts','--maxWorkers=1'],fresh,env)
for(const n of names)fs.utimesSync(path.join(dir,n),new Date('2000-01-01Z'),new Date('2000-01-01Z'));const z1=path.join(tmp,'one.zip'),z2=path.join(tmp,'two.zip');run('zip',['-X','-q',z1,...names],dir);run('zip',['-X','-q',z2,...names],dir);assert.equal(sha(fs.readFileSync(z1)),sha(fs.readFileSync(z2)));assert.deepEqual(metadata(),before);assert.equal(git('diff','--name-only','HEAD'),'');fs.mkdirSync(output,{recursive:true});const destination=path.join(output,NAME);fs.copyFileSync(z1,destination,fs.constants.COPYFILE_EXCL);console.log(JSON.stringify({status:manifest.status,archive:destination,sha256:sha(fs.readFileSync(destination)),bytes:fs.statSync(destination).size,members:names.length,candidate,freshRecovery:true},null,2))
