import {identity,privacyBoundary} from './activity.mjs'
export const CORPUS_INTERFACE='TE-IFACE-CORPUS@1.0.0-rc1'
export const INPUT_ID='9392b18ee094f8ec8254081607cbd5b9aa4cd23532c3be22f559cbed31f9f2d0'
export const INDEX_ID='867fa4dc45943d64737894f8289d06d1f4e7c9775daa12388df6d0a9657321b1'
export function assertCandidateOnly({freeze=false,activateLaneC=false,runtimeProviderCalls=0}={}){if(freeze!==false||activateLaneC!==false||runtimeProviderCalls!==0)throw Error('S2_RC_HAS_NO_FREEZE_OR_ACTIVATION_AUTHORITY')}
export function compileCorpus(input,{freeze=false,activateLaneC=false,runtimeProviderCalls=0}={}){
 assertCandidateOnly({freeze,activateLaneC,runtimeProviderCalls});privacyBoundary(input)
 const {identity:seal,...payload}=input
 if(seal!==identity(payload)||seal!==INPUT_ID||identity(input.rows)!==INDEX_ID||input.rows.length!==25||input.rawBodiesRead!==false||input.privateStateRead!==false||input.credentialRead!==false)throw Error('S2_CORPUS_EXACT_ADMITTED_INPUT')
 const seen=new Set(),concepts=input.rows.map(row=>{
  if(row.lead_acceptance_status!=='ACCEPTED'||row.raw_payload_published!==false||row.gameplay_integration_accepted!==false||seen.has(row.public_call_id)||!row.business_question||!row.consumer_ids.length)throw Error('S2_CORPUS_ACCEPTANCE_OR_PADDING')
  seen.add(row.public_call_id)
  const source=input.supplements.find(s=>s.publicCallId===row.public_call_id);if(!source||source.providerResponseSha256!==row.response_sha256)throw Error('S2_CORPUS_PROVIDER_BINDING')
  const role=row.result_count===0?'BOUNDED_NO_MATCH':row.purpose_code==='FILTER_DEMONSTRATION'?'FILTER_DEMONSTRATION':row.question_lens==='RELATIONSHIPS'?'RELATIONSHIP_CONTEXT':'ACTIVITY_CONTEXT'
  const concept={conceptRole:role,evidenceGrade:row.evidence_grade,temporalClass:row.temporal_class,question:{id:row.investigative_question_id||row.public_call_id,question:row.business_question,lens:row.question_lens||'ACTIVITY',purpose:row.purpose_code},provenance:{endpoint:row.endpoint_family,publicCallId:row.public_call_id,leadAcceptanceOrder:row.lead_acceptance_order,acceptedPublicRowIdentity:identity(row),requestBodySha256:row.request_body_sha256,providerResponseSha256:row.response_sha256,normalizedSha256:row.normalized_sha256,logicalRequestId:source.logicalRequestId,logicalRequestIdDisposition:source.logicalRequestIdDisposition,providerRequestId:source.providerRequestId,providerRequestIdDisposition:source.providerRequestIdDisposition,auditAttemptIdentity:source.auditAttemptIdentity,acceptedIndexIdentity:INDEX_ID,attribution:row.attribution},coverage:{scope:row.coverage_scope,cellIds:row.coverage_cell_ids||[],key:row.coverage_key||null,status:'PARTIAL_ACCEPTED_RETRIEVED_SCOPE',supportsHistoricalNegative:false},claimBoundaries:[...row.claim_boundaries,'NO_CONTEXTUAL_TO_EXACT_PROMOTION','NO_ACCOUNT_QUOTA_OR_CPP_IN_GAME_CORPUS'],namedConsumers:[...row.consumer_ids].sort(),filterDimensions:['SUBJECT','SOURCE','DESTINATION','ASSET','FROM','TO','MIN_AMOUNT','TRANSACTION','GRADE','KIND','RECORD_SET'],publicPrivateDispositions:{public:'ADMITTED_MINIMAL_CONCEPT_METADATA',rawProviderBody:'PRIVATE_NOT_IMPORTED',providerSchema:'PROVENANCE_ONLY_NOT_CONCEPT_SCHEMA',accountActivity:'EXCLUDED',credentials:'EXCLUDED'},zeroResultClass:row.result_count===0?'NO_MATCH_IN_ACCEPTED_CORPUS':null,observedResultCount:row.result_count,exactTruthAuthority:false,recursiveFrontierAuthority:false,runtimeProviderCalls:0,gameplayIntegrated:false}
  const hash=identity(concept);return {id:'CONCEPT.'+hash,identity:hash,...concept}
 }).sort((a,b)=>a.provenance.publicCallId.localeCompare(b.provenance.publicCallId))
 const result={schemaVersion:'1.0.0-rc1',interface:CORPUS_INTERFACE,status:'CONTROLLER_OWNED_CANDIDATE_NOT_FROZEN',inputIdentity:seal,acceptedIndexIdentity:INDEX_ID,conceptCount:concepts.length,curatedAcceptedCalls:25,newRequests:0,concepts,exactTruthSeparation:{unchanged:true,truthFiles:'ACCEPTED_EULER_FILES_UNMODIFIED',firstExactFalsifier:'EXACT_CONVERGENCE',firstExactFalsifierUtc:'2023-03-13T11:38:11Z',contextualConceptsMayFillProofSlots:false},LaneCActive:false,interfaceFrozen:false,runtimeProviderCalls:0}
 return {...result,identity:identity(result)}
}
export function validateConcept(concept){
 const closed=(o,keys)=>o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).length===keys.length&&Object.keys(o).every(k=>keys.includes(k))
 if(!closed(concept.question,['id','question','lens','purpose'])||!closed(concept.provenance,['endpoint','publicCallId','leadAcceptanceOrder','acceptedPublicRowIdentity','requestBodySha256','providerResponseSha256','normalizedSha256','logicalRequestId','logicalRequestIdDisposition','providerRequestId','providerRequestIdDisposition','auditAttemptIdentity','acceptedIndexIdentity','attribution'])||!closed(concept.coverage,['scope','cellIds','key','status','supportsHistoricalNegative'])||!closed(concept.publicPrivateDispositions,['public','rawProviderBody','providerSchema','accountActivity','credentials']))throw Error('S2_CONCEPT_NESTED_SCHEMA_LEAK')
 if(concept.evidenceGrade!=='CONTEXTUAL'||!['NANSEN_SERVER_FILTERED_UNZONED_BLOCK_TIME_CONTEXTUAL','SERVER_FILTERED_UNZONED_CONTEXTUAL','BOUNDED_RELATIONSHIP_AGGREGATE_CONTEXTUAL','BOUNDED_QUERY_AGGREGATE_CONTEXTUAL'].includes(concept.temporalClass))throw Error('S2_CONTEXTUAL_GRADE_OR_TIME_PROMOTION')
 const keys=['id','identity','conceptRole','evidenceGrade','temporalClass','question','provenance','coverage','claimBoundaries','namedConsumers','filterDimensions','publicPrivateDispositions','zeroResultClass','observedResultCount','exactTruthAuthority','recursiveFrontierAuthority','runtimeProviderCalls','gameplayIntegrated']
 if(Object.keys(concept).length!==keys.length||Object.keys(concept).some(k=>!keys.includes(k))||concept.exactTruthAuthority!==false||concept.recursiveFrontierAuthority!==false||concept.runtimeProviderCalls!==0||concept.gameplayIntegrated!==false||concept.coverage.supportsHistoricalNegative!==false||concept.provenance.acceptedIndexIdentity!==INDEX_ID||!Array.isArray(concept.namedConsumers)||!concept.namedConsumers.length||!concept.claimBoundaries.includes('NO_CONTEXTUAL_TO_EXACT_PROMOTION')||!concept.claimBoundaries.includes('NO_ACCOUNT_QUOTA_OR_CPP_IN_GAME_CORPUS')||!['EXACT','CORROBORATING','CONTEXTUAL'].includes(concept.evidenceGrade)||!['BOUNDED_NO_MATCH','FILTER_DEMONSTRATION','RELATIONSHIP_CONTEXT','ACTIVITY_CONTEXT'].includes(concept.conceptRole))throw Error('S2_CONCEPT_CLOSED_SCHEMA_OR_CLAIM_BOUNDARY')
 if(concept.zeroResultClass!==null&&concept.zeroResultClass!=='NO_MATCH_IN_ACCEPTED_CORPUS')throw Error('S2_NO_NEGATIVE_OVERREACH')
 const {id,identity:h,...p}=concept;if(h!==identity(p)||id!=='CONCEPT.'+h)throw Error('S2_CONCEPT_IDENTITY');privacyBoundary(concept);return true
}
