import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {execFileSync} from 'node:child_process'
import {fileURLToPath} from 'node:url'
import {sha,identity} from './activity.mjs'
import {privatePathFindings} from '../nq5-s1/privacy.mjs'
import {hasSecretLikeValue} from '../secret-patterns.mjs'
import {OFF,admitEntries} from '../nq5-s1/core.mjs'
import {attachPublishedRegressionInputs} from './published-regression-inputs.mjs'
export const OUTPUT='TRACE_ESCAPE_G6P_NQ5_T1_S2_RULE_ALIGNED_REBASE_CPP_EVIDENCE_P1_FIXES_CORPUS_SEAM_DELIVERY_v1.0.0.zip'
const BASE='47f0466e4f6f31ba2583577c4ff747b2dc1dab3b',BASE_TREE='11d9390f547754dc2dfca3d8b5ff19dadb792b40',PARENT='5b31af6e16b8fcb176480cecd640a31ac2056b7d',INPUT_ZIP_SHA='9d95ae70e686f58e3b33cc50fc36fd0dafcff307258d0adb0c8910784526609d'
const reports=['MERIDIAN_ACCOUNT_ACTIVITY_REPORT.json','TE_IFACE_CORPUS_RC1.json','S2_DECISION_RECEIPT.json']
const root=process.cwd(),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'s2-delivery-')),dir=path.join(tmp,'package'),fresh=path.join(tmp,'reconstructed'),objectRoot=path.join(tmp,'pack-audit')
const env={PATH:process.env.PATH,LANG:'C.UTF-8',TZ:'UTC',TMPDIR:os.tmpdir(),NODE_OPTIONS:'--require '+path.join(root,'scripts/nq5-r2/hold.cjs'),CI:'1',NO_COLOR:'1',GIT_TERMINAL_PROMPT:'0',GIT_CONFIG_NOSYSTEM:'1'}
const run=(cmd,args,cwd=root)=>execFileSync(cmd,args,{cwd,env,maxBuffer:128000000,stdio:['pipe','pipe','pipe']}).toString(),git=(...a)=>run('git',a).trim()
const sanitize=t=>t.split(root).join('[CONTROLLER_ROOT]').split(tmp).join('[FRESH_VERIFICATION_ROOT]').split(os.tmpdir()).join('[LOCAL_VERIFICATION_ROOT]').replace(/\u001b\[[0-9;]*m/g,'')
fs.mkdirSync(dir)
const candidate={commit:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),parent:git('rev-parse','HEAD^')}
if(candidate.commit===PARENT||git('rev-parse',BASE+'^{tree}')!==BASE_TREE)throw Error('S2_ANCESTRY_IDENTITY');run('git',['merge-base','--is-ancestor',BASE,candidate.commit]);run('git',['merge-base','--is-ancestor',PARENT,candidate.commit])
if(git('diff','--name-only','HEAD','--','.',':(exclude)AGENTS.md',':(exclude).cursor',':(exclude)ART_PRODUCTION'))throw Error('S2_DIRTY_GOVERNED_TRACKED')
const changed=git('diff','--name-only',BASE,candidate.commit).split('\n')
if(changed.some(n=>n==='AGENTS.md'||n.startsWith('.cursor/')||n.startsWith('ART_PRODUCTION/')||n.startsWith('public/')||/NANSEN_API_KEY\.txt/i.test(n)))throw Error('S2_CHANGED_PATH_SCOPE')
const inherited=new Set(git('diff','--name-only',BASE,PARENT).split('\n'))
const ownedFiles=new Set(['README.md','docs/ARCHITECTURE.md','docs/PROJECT_STATUS.yaml','docs/PROJECT_SCHEDULE.json','package.json','scripts/project-status-lib.mjs','scripts/s2-prefix.config.mjs','scripts/s2-browser.config.mjs','scripts/s2-regression-browser.config.mjs','scripts/s2-current-browser.config.mjs','src/app/CaseTerminalWorkbench.tsx','src/app/ExactIdentifier.tsx','src/investigation/query.ts','src/investigation/state.ts','src/investigation/contracts.ts','src/investigation/fixture.ts','src/investigation/catalog.ts','src/investigation/accounting.ts','tests/unit/project-clock.test.mjs','tests/unit/g6p-a2u.test.ts','tests/unit/s2-controller.test.ts','tests/unit/s2-activity-corpus.test.mjs','tests/unit/s2-prefix.repro.ts','tests/e2e/nq5-r1-parity.spec.ts','tests/e2e/s2-fixes.spec.ts','tests/e2e/s2-prefix.repro.spec.ts','docs/TE_IFACE_CORPUS_1.0.0_RC1.md'])
if(changed.some(n=>!inherited.has(n)&&!ownedFiles.has(n)&&!['docs/source/v1.11.0/','docs/source/execution-s2/','scripts/nq5-s2/','tests/fixtures/s2/','artifacts/g6p-s2/','docs/G6P_NQ5_T1_S2_'].some(p=>n.startsWith(p))))throw Error('S2_CLOSED_CHANGED_PATH_SCOPE')
const payload=new Map(),put=(n,b)=>{if(!n||n.startsWith('/')||n.split('/').includes('..')||n.includes('\\')||payload.has(n))throw Error('S2_PACKAGE_PATH');b=Buffer.isBuffer(b)?b:Buffer.from(typeof b==='string'?b:JSON.stringify(b,null,2)+'\n');fs.mkdirSync(path.dirname(path.join(dir,n)),{recursive:true});fs.writeFileSync(path.join(dir,n),b,{flag:'wx'});payload.set(n,b)}
const log=(n,text)=>put('LOGS/'+n+'.log',sanitize(text))
const bundle=path.join(tmp,'incremental.bundle');run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD','^'+BASE])
const bytes=fs.readFileSync(bundle),boundary=bytes.indexOf(Buffer.from('\n\n'))
if(boundary<0)throw Error('S2_BUNDLE_HEADER');const header=bytes.subarray(0,boundary).toString()
if(!header.includes('-'+BASE+' ')||header.split('\n').filter(l=>l.startsWith('-')).length!==1)throw Error('S2_EXACT_BASE_PREREQUISITE')
fs.mkdirSync(objectRoot);run('git',['init','--quiet'],objectRoot);fs.mkdirSync(path.join(objectRoot,'.git/objects/info'),{recursive:true});fs.writeFileSync(path.join(objectRoot,'.git/objects/info/alternates'),path.join(root,'.git/objects')+'\n')
const indexed=execFileSync('git',['index-pack','--fix-thin','--stdin'],{cwd:objectRoot,env,input:bytes.subarray(boundary+2),maxBuffer:128000000}).toString().trim(),packHash=indexed.split(/\s+/).at(-1),packIndex=path.join(objectRoot,'.git/objects/pack','pack-'+packHash+'.idx')
const objects=run('git',['verify-pack','-v',packIndex],objectRoot).split('\n').filter(l=>/^[a-f0-9]{40} (?:blob|commit|tree|tag) /.test(l)).map(l=>{const[id,type]=l.split(' ');return{id,type}})
if(!objects.length)throw Error('S2_PACK_OBJECTS_EMPTY')
let scanned=0;for(const o of objects){if(!['blob','commit','tag'].includes(o.type))continue;const b=execFileSync('git',['cat-file',o.type,o.id],{cwd:objectRoot,env,maxBuffer:128000000});let text;try{text=new TextDecoder('utf8',{fatal:true}).decode(b)}catch{throw Error('S2_NON_TEXT_NEW_OBJECT')};if(privatePathFindings(text).length||hasSecretLikeValue(text))throw Error('S2_PACKAGED_GIT_OBJECT_PRIVACY');scanned++}
const objectReport={status:'PASS',bundleSha256:sha(bytes),prerequisiteCommit:BASE,objects:objects.length,textObjectsScanned:scanned,objectIds:objects,thinPackDependencyMaterialization:'Indexed with local existing base-object alternates; every object in the reconstructed incremental pack scanned, including any required delta bases.',privatePathFindings:0,secretFindings:0,completeInheritedHistoryPackaged:false,credentialFileOpened:false,networkRequests:0}
put('EVIDENCE/INCREMENTAL_GIT_OBJECT_PRIVACY.json',objectReport);put('GIT/trace-escape-incremental.bundle',bytes)
fs.mkdirSync(fresh);run('git',['init','--quiet'],fresh);fs.mkdirSync(path.join(fresh,'.git/objects/info'),{recursive:true});fs.writeFileSync(path.join(fresh,'.git/objects/info/alternates'),path.join(root,'.git/objects')+'\n')
const bv=run('git',['bundle','verify',bundle],fresh);run('git',['fetch','--quiet','--no-tags',bundle,'HEAD:refs/heads/candidate'],fresh);run('git',['symbolic-ref','HEAD','refs/heads/candidate'],fresh);run('git',['read-tree','HEAD'],fresh)
if(run('git',['rev-parse','HEAD'],fresh).trim()!==candidate.commit||run('git',['rev-parse','HEAD^{tree}'],fresh).trim()!==candidate.tree||run('git',['rev-parse','HEAD^'],fresh).trim()!==candidate.parent)throw Error('S2_RECONSTRUCTED_IDENTITY')
const names=run('git',['ls-files','-z','--','.',':(exclude).cursor',':(exclude)ART_PRODUCTION'],fresh).split('\0').filter(Boolean)
for(const n of names){if(n.startsWith('/')||n.split('/').includes('..'))throw Error('S2_FRESH_PATH');const b=execFileSync('git',['show','HEAD:'+n],{cwd:fresh,env,maxBuffer:128000000});fs.mkdirSync(path.dirname(path.join(fresh,n)),{recursive:true});fs.writeFileSync(path.join(fresh,n),b,{flag:'wx'})}
fs.symlinkSync(path.join(root,'node_modules'),path.join(fresh,'node_modules'),'dir');fs.appendFileSync(path.join(fresh,'.git/info/exclude'),'\nnode_modules\n')
const fsck=run('git',['fsck','--full','--strict'],fresh)
put('EVIDENCE/PUBLISHED_REGRESSION_INPUT_BINDINGS.json',attachPublishedRegressionInputs(root,tmp,env))
const diff=execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:root,env,maxBuffer:128000000}),freshDiff=execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:fresh,env,maxBuffer:128000000});if(!diff.equals(freshDiff))throw Error('S2_EXACT_DIFF_RECONSTRUCTION');put('SOURCE_DIFF.patch',diff)
log('incremental-reconstruction',bv+fsck+'\nExact accepted base prerequisite, candidate/tree/parent, strict fsck, and identical base-to-candidate patch: PASS. Local object alternates used; no complete history copied into delivery.\n')
log('fresh-schema-boundaries',run('node',['scripts/nq5-s2/verify.mjs'],fresh))
const test=run('node',['node_modules/vitest/vitest.mjs','run'],fresh);log('fresh-broad-unit-acquisition',test);const testCount=Number(test.match(/Tests\s+(\d+) passed/)?.[1]);if(!testCount||/\d+ failed/.test(test))throw Error('S2_FRESH_BROAD_TESTS')
log('fresh-typecheck',run('npm',['run','typecheck'],fresh));log('fresh-build',run('npm',['run','build'],fresh));log('fresh-lint',run('npm',['run','lint'],fresh))
for(const n of reports){put('REPORTS/'+n,fs.readFileSync(path.join(root,'artifacts/g6p-s2/REPORTS',n)));put('SCHEMAS/'+n+'.schema.json',fs.readFileSync(path.join(root,'artifacts/g6p-s2/SCHEMAS',n+'.schema.json')))}
put('SCHEMAS/MERIDIAN_ACTIVITY_INPUT.schema.json',fs.readFileSync(path.join(root,'artifacts/g6p-s2/SCHEMAS/MERIDIAN_ACTIVITY_INPUT.schema.json')))
for(const n of fs.readdirSync(path.join(root,'artifacts/g6p-s2/LOGS')).filter(n=>n.endsWith('.log')).sort())put('LOGS/'+n,fs.readFileSync(path.join(root,'artifacts/g6p-s2/LOGS',n)))
const docs={'NOTES_FOR_LEAD.md':'docs/G6P_NQ5_T1_S2_NOTES_FOR_LEAD.md','ACCOUNTING_CONTRACT.md':'docs/G6P_NQ5_T1_S2_ACCOUNTING_CONTRACT.md','CORPUS_INTERFACE_RC1.md':'docs/TE_IFACE_CORPUS_1.0.0_RC1.md','NEXT_PACKETS_NOT_SENT.md':'docs/G6P_NQ5_T1_S2_NEXT_PACKETS_NOT_SENT.md','ORGANIZER_CLARIFICATION_NOT_SENT.md':'docs/G6P_NQ5_T1_S2_ORGANIZER_CLARIFICATION_NOT_SENT.md'}
for(const[n,file]of Object.entries(docs))put('EVIDENCE/'+n,fs.readFileSync(path.join(root,file)))
const prefixFiles=['src/investigation/query.ts','src/app/CaseTerminalWorkbench.tsx'];put('EVIDENCE/PRE_FIX_IDENTITY_BINDINGS.json',{status:'CONFIRMED_ON_UNCHANGED_MAIN_PRODUCTION_CODE_BEFORE_FIX',commit:PARENT,acceptedBase:BASE,files:prefixFiles.map(n=>{const a=execFileSync('git',['show',PARENT+':'+n],{cwd:root,env,maxBuffer:128000000}),b=execFileSync('git',['show',BASE+':'+n],{cwd:root,env,maxBuffer:128000000});if(!a.equals(b))throw Error('S2_PREFIXX_BASE_SOURCE');return{path:n,sha256:sha(a),sameAsExactAcceptedBase:true}}),prefixUnitLog:'LOGS/prefix-unit.log',prefixBrowserLog:'LOGS/prefix-browser-confirmed.log',postFixBrowserLog:'LOGS/browser-fixes-final.log',historicalLaneReportsUnmodified:true})
const prefixLog=fs.readFileSync(path.join(root,'artifacts/g6p-s2/LOGS/prefix-browser-confirmed.log'),'utf8'),browser=fs.readFileSync(path.join(root,'artifacts/g6p-s2/LOGS/browser-fixes-final.log'),'utf8'),broadBrowser=fs.readFileSync(path.join(root,'artifacts/g6p-s2/LOGS/current-browser-final.log'),'utf8'),legacyBrowser=fs.readFileSync(path.join(root,'artifacts/g6p-s2/LOGS/broad-browser.log'),'utf8'),baseBrowser=fs.readFileSync(path.join(root,'artifacts/g6p-s2/LOGS/exact-accepted-base-legacy-browser-confirmed.log'),'utf8')
if(!prefixLog.includes('allFailedExactCopy')||!browser.includes('3 passed')||!broadBrowser.includes('EXIT_CODE=0')||!legacyBrowser.includes('17 failed')||!baseBrowser.includes('11 failed')||!baseBrowser.includes('BASE_COMMIT='+BASE))throw Error('S2_BROWSER_EVIDENCE_UNAVAILABLE_OR_UNEXPLAINED')
const browserCount=Number(broadBrowser.match(/(\d+) passed \(/)?.[1]);if(!browserCount)throw Error('S2_BROWSER_TOTAL')
const receipt=JSON.parse(payload.get('REPORTS/S2_DECISION_RECEIPT.json'))
put('EVIDENCE/MAIN_OWNED_REVIEW.json',{reviewType:'EIGHT_MAIN_OWNED_LENSES_NOT_INDEPENDENT_LEAD_ACCEPTANCE',status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',candidate,acceptedP0P1Remaining:0,controllerP1:{B_F01:'FIXED_CANDIDATE_REPRO_AND_UNIT_BROWSER_EVIDENCE',B_F02:'FIXED_CANDIDATE_NINE_CLIPBOARD_AND_FAILURE_RECOVERY_EVIDENCE'},lenses:['archive/source identity','Git ancestry/reconstruction','contract/authority','direct reproductions/regressions','strongest false-success','provider/credential/private/public boundaries','lean packaging','bounded disposition/next action'],corrections:['transitive overlap graph','estimated source rows isolated from observed requests','nested-schema and grade/time promotion rejection','strict boolean proof seam and exact credit overflow','canonical amount validation in dispatch and direct predicate','shared exact-copy with recoverable feedback'],limitations:['actual AT not executed','numeric contrast not certified','final-art/hardware/touch not accepted','3 optional historical provider/logical ID joins explicitly UNKNOWN','quota unknown; sample unverified','RC not frozen; lanes not activated or integrated'],authorities:OFF})
put('EVIDENCE/VERIFICATION_SUMMARY.json',{status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',candidate,acceptedBase:{commit:BASE,tree:BASE_TREE},freshBroadUnitAcquisitionTests:testCount,priorWorkspaceBroadUnitTests:1438,broadBrowserTests:browserCount,fullLegacyBrowserAttempt:{passed:28,failed:17,status:'FAILED_RETAINED_NOT_ALL_GREEN',unchangedExactBaseJourneyFailures:11,intentionallyRetiredLedgerLabelExpectations:6},exactBaseLegacyComparison:{passed:2,failed:11,status:'PREEXISTING_LEGACY_JOURNEY_MISMATCH_CONFIRMED'},currentBrowserRegression:{passed:browserCount,failed:0,legacyJourneyFilesExcluded:3,labelExpectationsMigrated:6},focusedBrowserTests:3,exactClipboardModeValueChecks:9,clipboardFailureModes:3,preFixReproducerTests:2,typecheck:'PASS',build:'PASS',lint:'PASS',schemas:4,sourceInputMembers:42,unchangedEulerFiles:6,externalApiProbesBlocked:4,strictFsck:'PASS',exactDiffReproduced:true,packagedGitPrivacy:'PASS',completeHistoryIncluded:false,baseDependentRecovery:true,networkRequests:0,credentialAccess:false,privateStateAccess:false,independentLeadReviewPending:true,authorities:OFF})
put('DELIVERY_MANIFEST.json',{schemaVersion:'1.0.0',status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',candidate,acceptedBaseCommit:BASE,acceptedBaseTree:BASE_TREE,incrementalBundleSha256:sha(bytes),incrementalBundlePrerequisite:BASE,sourceDiffSha256:sha(diff),sourceInputArchiveSha256:INPUT_ZIP_SHA,decisionReceiptIdentity:receipt.identity,completeHistoryIncluded:false,baseDependentRecovery:true,curatedAcceptedCalls:25,quotaClaimed:false,interfaceFrozen:false,LaneCActive:false,networkRequests:0,authorities:OFF})
put('CONTRACT/S2_EXECUTION_CONTRACT.txt',fs.readFileSync(path.join(root,'docs/source/execution-s2/CONTRACT/TRACE_ESCAPE_CODEX_G6P_NQ5_T1_S2_RULE_ALIGNED_REBASE_CPP_EVIDENCE_P1_FIXES_CORPUS_SEAM_PROMPT_v1.0.0_2026-09-17.txt')))
put('README.md','# TRACE//ESCAPE — S2 incremental candidate delivery\n\nDELIVERED_PENDING_MAIN_LEAD_REVIEW. Start with EVIDENCE/NOTES_FOR_LEAD.md and VERIFICATION_SUMMARY.json. Official1000 eligible-window account-call proof is separate from curated product evidence; the former1024 curated floor is retired. CPP sample20 requests/32credits is transcription evidence, NOT final quota proof or game data. Current25 curated acceptances and exact Euler truth remain unchanged. Both controller P1 fixes are candidates with direct pre/post evidence. Corpus RC is NOT frozen; all prepared packets are UNSENT. No final AT/contrast/art/release/submission acceptance. Powered by Nansen API.\n\nBASE-DEPENDENT RECOVERY: GIT/trace-escape-incremental.bundle requires accepted commit'+BASE+' and tree'+BASE_TREE+'. It does not contain inherited complete history. SOURCE_DIFF.patch is the exact base-to-candidate patch; candidate commit/tree/parent are in DELIVERY_MANIFEST.json. Local reconstruction used existing Git objects as base prerequisites and passed strict fsck, exact identities/diff, fresh broad tests/typecheck/build/lint and incremental object privacy scan. No privacy exception or rewrite was used.\n\nExtract with a path-safe regular-file ZIP reader, then run node VERIFY_DELIVERY.mjs for exact members/hashes and bounded report assertions. Authenticate the ZIP with the separately supplied SHA-256. To reconstruct, use an existing local Git repository containing the exact accepted base; verify the incremental bundle there, fetch its HEAD into a new candidate ref, verify commit/tree/parent against the manifest and reproduce the patch. Never fetch the base from a network or treat absent history as an empty baseline. The evidence verifier is not independent Lead acceptance.\n\nNo credentials, actual private paths, raw responses, private journals, CPP business payload, dependencies, preview, lane-content/Pixel assets or nested historical ZIP ships. All logs include failed attempts separately; archived pre-fix tests intentionally describe pre-fix behavior and are excluded from post-fix regression. Fresh counts are not inflated by reruns or overlapping suites. No external request, credential resolution or private-state replay occurred.\n')
const allowed=[...payload.keys(),'VERIFY_DELIVERY.mjs','MANIFEST.sha256'].sort()
function verifyDelivery(){
 const fail=n=>{throw Error(n)},read=n=>fs.readFileSync(path.join(root,n)),p=n=>JSON.parse(read(n))
 const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const f=path.join(d,e.name),s=fs.lstatSync(f);if(s.isSymbolicLink()||(!s.isDirectory()&&(!s.isFile()||s.nlink!==1)))fail('S2_NONREGULAR');return s.isDirectory()?walk(f):[path.relative(root,f).split(path.sep).join('/')] }).sort()
 if(JSON.stringify(walk(root))!==JSON.stringify(allowed))fail('S2_EXACT_MEMBERS')
 const seen=new Set(),lines=read('MANIFEST.sha256').toString().trimEnd().split('\n');if(lines.length!==allowed.length-1)fail('S2_HASH_COUNT')
 for(const l of lines){const h=l.slice(0,64),n=l.slice(66);if(!/^[a-f0-9]{64}$/.test(h)||l.slice(64,66)!=='  '||!allowed.includes(n)||n==='MANIFEST.sha256'||seen.has(n)||sha(read(n))!==h)fail('S2_HASH');seen.add(n)}
 const manifest=p('DELIVERY_MANIFEST.json'),v=p('EVIDENCE/VERIFICATION_SUMMARY.json'),a=p('REPORTS/MERIDIAN_ACCOUNT_ACTIVITY_REPORT.json'),c=p('REPORTS/TE_IFACE_CORPUS_RC1.json'),r=p('REPORTS/S2_DECISION_RECEIPT.json'),g=p('EVIDENCE/INCREMENTAL_GIT_OBJECT_PRIVACY.json')
 for(const d of [a,c,r]){const{identity:h,...x}=d;if(h!==identity(x))fail('S2_REPORT_SEAL')}
 if(manifest.status!=='DELIVERED_PENDING_MAIN_LEAD_REVIEW'||manifest.acceptedBaseCommit!==base||manifest.acceptedBaseTree!==baseTree||manifest.candidate.parent!==parent||manifest.completeHistoryIncluded!==false||manifest.baseDependentRecovery!==true||manifest.incrementalBundlePrerequisite!==base||manifest.incrementalBundleSha256!==sha(read('GIT/trace-escape-incremental.bundle'))||manifest.sourceDiffSha256!==sha(read('SOURCE_DIFF.patch'))||manifest.decisionReceiptIdentity!==r.identity||JSON.stringify(manifest.candidate)!==JSON.stringify(v.candidate)||manifest.sourceInputArchiveSha256!==inputZipSha||manifest.curatedAcceptedCalls!==25||manifest.quotaClaimed!==false||manifest.interfaceFrozen!==false||manifest.LaneCActive!==false||manifest.networkRequests!==0)fail('S2_MANIFEST_BINDINGS')
 const head=read('GIT/trace-escape-incremental.bundle').toString('utf8',0,read('GIT/trace-escape-incremental.bundle').indexOf(Buffer.from('\n\n')));if(!head.includes('-'+base+' ')||head.split('\n').filter(x=>x.startsWith('-')).length!==1||!head.includes(manifest.candidate.commit+' HEAD'))fail('S2_BUNDLE_PREREQUISITE')
 if(a.observed.requests!==20||a.observed.successes!==20||a.observed.credits!==32||a.removedRows.length!==1||a.verifiedSuccessfulLowerBound!==0||a.finalQuotaProofEligible!==false||a.quotaMet!==false||a.curatedGameEvidenceRows!==0||a.cppAutomaticallyCounts!==false||c.conceptCount!==25||c.interfaceFrozen!==false||c.LaneCActive!==false||c.runtimeProviderCalls!==0||r.accountReportIdentity!==a.identity||r.corpusCandidateIdentity!==c.identity||r.authorities.network!==false||r.quotaClaimed!==false)fail('S2_NO_FALSE_SUCCESS')
 if(c.interface!=='TE-IFACE-CORPUS@1.0.0-rc1'||c.status!=='CONTROLLER_OWNED_CANDIDATE_NOT_FROZEN'||c.inputIdentity!=='9392b18ee094f8ec8254081607cbd5b9aa4cd23532c3be22f559cbed31f9f2d0'||c.acceptedIndexIdentity!=='867fa4dc45943d64737894f8289d06d1f4e7c9775daa12388df6d0a9657321b1'||c.curatedAcceptedCalls!==25||c.newRequests!==0||c.concepts.length!==25||c.exactTruthSeparation.unchanged!==true||c.exactTruthSeparation.contextualConceptsMayFillProofSlots!==false||c.exactTruthSeparation.firstExactFalsifierUtc!=='2023-03-13T11:38:11Z')fail('S2_RC_BOUNDARIES')
 const ids=new Set(),calls=new Set();let zero=0
 for(const x of c.concepts){const{id,identity:h,...body}=x;if(h!==identity(body)||id!=='CONCEPT.'+h||ids.has(id)||calls.has(x.provenance.publicCallId)||x.evidenceGrade!=='CONTEXTUAL'||x.exactTruthAuthority!==false||x.recursiveFrontierAuthority!==false||x.runtimeProviderCalls!==0||x.gameplayIntegrated!==false||x.coverage.supportsHistoricalNegative!==false||x.provenance.acceptedIndexIdentity!==c.acceptedIndexIdentity||x.publicPrivateDispositions.accountActivity!=='EXCLUDED'||x.publicPrivateDispositions.credentials!=='EXCLUDED'||!x.claimBoundaries.includes('NO_CONTEXTUAL_TO_EXACT_PROMOTION')||!x.claimBoundaries.includes('NO_ACCOUNT_QUOTA_OR_CPP_IN_GAME_CORPUS'))fail('S2_CONCEPT_BOUNDARY');ids.add(id);calls.add(x.provenance.publicCallId);if(x.observedResultCount===0){zero++;if(x.zeroResultClass!=='NO_MATCH_IN_ACCEPTED_CORPUS')fail('S2_NEGATIVE_OVERREACH')}else if(x.zeroResultClass!==null)fail('S2_ZERO_CLASS')}
 if(zero!==7||v.currentBrowserRegression.passed!==34||v.currentBrowserRegression.failed!==0||v.fullLegacyBrowserAttempt.failed!==17||v.fullLegacyBrowserAttempt.unchangedExactBaseJourneyFailures!==11||v.exactBaseLegacyComparison.failed!==11)fail('S2_REGRESSION_DISPOSITION')
 if(g.status!=='PASS'||g.bundleSha256!==manifest.incrementalBundleSha256||g.completeInheritedHistoryPackaged!==false||g.privatePathFindings!==0||g.secretFindings!==0||v.strictFsck!=='PASS'||v.exactDiffReproduced!==true||v.freshBroadUnitAcquisitionTests<1445||v.exactClipboardModeValueChecks!==9||v.networkRequests!==0||v.credentialAccess!==false||v.privateStateAccess!==false)fail('S2_EVIDENCE')
 const visit=x=>{if(!x||typeof x!=='object')return;if(x.authorities&&(JSON.stringify(Object.keys(x.authorities).sort())!==JSON.stringify(Object.keys(off).sort())||Object.keys(off).some(k=>x.authorities[k]!==false)))fail('S2_AUTHORITY');Object.values(x).forEach(visit)}
 for(const n of allowed){if(n.startsWith('GIT/'))continue;const text=read(n).toString();if(privatePathFindings(text).length||hasSecretLikeValue(text))fail('S2_TEXT_PRIVACY');if(n.endsWith('.json')&&!n.startsWith('SCHEMAS/'))visit(JSON.parse(text))}
 console.log(JSON.stringify({status:'PASS',members:allowed.length,hashes:seen.size,terminalStatus:manifest.status,baseDependentRecovery:true,completeHistoryIncluded:false,curatedAcceptedCalls:25,sampleRequests:20,sampleCredits:32,quotaClaimed:false,interfaceFrozen:false,authoritiesOff:true}))
}
const secret=fs.readFileSync(path.join(root,'scripts/secret-patterns.mjs'),'utf8').replace('export function','function'),privacy=fs.readFileSync(path.join(root,'scripts/nq5-s1/privacy.mjs'),'utf8').split('export function privatePathFindings')[1].split('export function currentTreeScan')[0]
put('VERIFY_DELIVERY.mjs',"import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';const root=path.dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex'),canonical="+canonicalFunction()+",identity=x=>sha(canonical(x)),allowed="+JSON.stringify(allowed)+",base="+JSON.stringify(BASE)+",baseTree="+JSON.stringify(BASE_TREE)+",parent="+JSON.stringify(candidate.parent)+",inputZipSha="+JSON.stringify(INPUT_ZIP_SHA)+",off="+JSON.stringify(OFF)+";\n"+secret+'\nfunction privatePathFindings'+privacy+'\n('+verifyDelivery.toString()+')();\n')
for(const[n,b]of payload){if(n.startsWith('GIT/'))continue;if(privatePathFindings(b.toString()).length||hasSecretLikeValue(b.toString()))throw Error('S2_PACKAGE_TEXT_PRIVACY_'+n)}
put('MANIFEST.sha256',[...payload].sort(([a],[b])=>a.localeCompare(b)).map(([n,b])=>sha(b)+'  '+n).join('\n')+'\n')
run('node',['VERIFY_DELIVERY.mjs'],dir)
let adversarialPassed=0
const rehash=()=>fs.writeFileSync(path.join(dir,'MANIFEST.sha256'),allowed.filter(n=>n!=='MANIFEST.sha256').map(n=>sha(fs.readFileSync(path.join(dir,n)))+'  '+n).join('\n')+'\n')
const reject=(name,apply,restore,expected)=>{const originalManifest=fs.readFileSync(path.join(dir,'MANIFEST.sha256'));try{apply();let rejected=false;try{run('node',['VERIFY_DELIVERY.mjs'],dir)}catch(e){if(!String(e.stderr).includes(expected))throw Error('S2_WRONG_ADVERSARIAL_FAILURE_'+name);rejected=true}if(!rejected)throw Error('S2_ADVERSARIAL_FALSE_SUCCESS_'+name);adversarialPassed++}finally{restore();fs.writeFileSync(path.join(dir,'MANIFEST.sha256'),originalManifest)}}
const mutate=(n,change,expected)=>{const original=fs.readFileSync(path.join(dir,n));reject(n,()=>{const x=JSON.parse(original);change(x);fs.writeFileSync(path.join(dir,n),JSON.stringify(x,null,2)+'\n');rehash()},()=>fs.writeFileSync(path.join(dir,n),original),expected)}
const logName='LOGS/browser-fixes-final.log',logBytes=fs.readFileSync(path.join(dir,logName))
reject('changed-byte',()=>fs.appendFileSync(path.join(dir,logName),'CORRUPTION'),()=>fs.writeFileSync(path.join(dir,logName),logBytes),'S2_HASH')
reject('extra-member',()=>fs.writeFileSync(path.join(dir,'EXTRA.txt'),'SYNTHETIC'),()=>fs.unlinkSync(path.join(dir,'EXTRA.txt')),'S2_EXACT_MEMBERS')
reject('missing-member',()=>fs.unlinkSync(path.join(dir,logName)),()=>fs.writeFileSync(path.join(dir,logName),logBytes),'S2_EXACT_MEMBERS')
reject('symlink-member',()=>{fs.unlinkSync(path.join(dir,logName));fs.symlinkSync('../prefix-unit.log',path.join(dir,logName))},()=>{fs.unlinkSync(path.join(dir,logName));fs.writeFileSync(path.join(dir,logName),logBytes)},'S2_NONREGULAR')
mutate('DELIVERY_MANIFEST.json',x=>{x.quotaClaimed=true},'S2_MANIFEST_BINDINGS')
mutate('REPORTS/MERIDIAN_ACCOUNT_ACTIVITY_REPORT.json',x=>{x.quotaMet=true;const{identity:h,...body}=x;x.identity=identity(body)},'S2_NO_FALSE_SUCCESS')
mutate('REPORTS/TE_IFACE_CORPUS_RC1.json',x=>{x.concepts[0].evidenceGrade='EXACT';const{id,identity:h,...body}=x.concepts[0];x.concepts[0].identity=identity(body);x.concepts[0].id='CONCEPT.'+x.concepts[0].identity;const{identity:seal,...report}=x;x.identity=identity(report)},'S2_NO_FALSE_SUCCESS')
if(adversarialPassed!==7)throw Error('S2_ADVERSARIAL_TOTAL');run('node',['VERIFY_DELIVERY.mjs'],dir)
for(const n of allowed)fs.utimesSync(path.join(dir,n),new Date('2000-01-01Z'),new Date('2000-01-01Z'))
const zip=path.join(tmp,'delivery.zip'),repeat=path.join(tmp,'repeat.zip');run('zip',['-X','-q',zip,...allowed],dir);run('zip',['-X','-q',repeat,...allowed],dir);if(sha(fs.readFileSync(zip))!==sha(fs.readFileSync(repeat)))throw Error('S2_ZIP_DETERMINISM')
const metadata=`import zipfile,stat,json,sys\nwith zipfile.ZipFile(sys.argv[1]) as z:\n print(json.dumps([{'name':i.filename,'type':'regular' if not i.is_dir() and stat.S_IFMT(i.external_attr>>16) in (0,stat.S_IFREG) else 'nonregular'} for i in z.infolist()]))`
admitEntries(JSON.parse(run('python3',['-c',metadata,zip])),allowed);const extracted=path.join(tmp,'extracted');fs.mkdirSync(extracted);run('unzip',['-q',zip,'-d',extracted]);run('node',['VERIFY_DELIVERY.mjs'],extracted)
for(const n of allowed)if(!fs.readFileSync(path.join(dir,n)).equals(fs.readFileSync(path.join(extracted,n))))throw Error('S2_BYTE_ROUNDTRIP')
if(git('rev-parse','HEAD')!==candidate.commit||git('rev-parse','HEAD^{tree}')!==candidate.tree)throw Error('S2_CANDIDATE_CHANGED')
const dest=path.join(path.dirname(root),OUTPUT);fs.copyFileSync(zip,dest,fs.constants.COPYFILE_EXCL)
console.log(JSON.stringify({status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',archive:dest,sha256:sha(fs.readFileSync(dest)),bytes:fs.statSync(dest).size,members:allowed.length,freshBroadUnitAcquisitionTests:testCount,broadBrowserTests:browserCount,packageAdversarialRejections:adversarialPassed,exactClipboardChecks:9,candidate,base:BASE,incrementalGitPrivacy:'PASS',completeHistoryIncluded:false,networkRequests:0},null,2))
function canonicalFunction(){return `(x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(canonical).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}')`}
