import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { type CaseFixture, type CaseRecord } from '../investigation/contracts'
import { availableCards, clueState, folderStatus, investigationReducer, knownRecords, openQuestion, queryReceiptKey, recommendations, s13CaseFileGateSatisfied, terminalCapabilities, threadChecks, threadStatus, visibleClues, type InvestigationState, type TerminalCapabilities } from '../investigation/state'
import { canonicalQuery, dispatchQuery, queryReceipt, querySentence, queryValidationIssues } from '../investigation/query'
import type { PerformanceProfile } from '../adventure/performanceCatalog'
import { PerformancePortrait } from './PerformancePortrait'
import { EvidenceAtlas } from './EvidenceAtlas'
import { investigationCue } from '../investigation/cues'
import { zeroResultCopy, recoveryCopy, methodHintCopy, contentText, publicSpeaker, terminalHintMilestone } from '../controller/content/adapter'
import type { SpeechLine } from '../adventure/types'
import { ExactIdentifier } from './ExactIdentifier'
import { AcceptedEvidenceSea } from './AcceptedEvidenceSea'
import { TerminalViewport } from './TerminalViewport'
import { SemanticDisplaySource } from './SemanticDisplaySource'
import type { SemanticCard } from '../investigation/semantic-ux/model'
import { SIDE_LEAD_HIGH_LEVEL_VIEW, SIDE_LEAD_TECHNICAL_VIEW, SIDE_LEAD_TOKENS } from '../investigation/sideLead'
import { selectHeroTerminalSpeech } from './productionCopySelectors'
import { S13CallAtlas, S13CorpusExplorer, S13Prebrief, S13Results, S13Source } from './S13IntegratedCorpus'
import { s13QueryGroupForQuestion, s13QueryGroupSummary } from '../investigation/s13'
import { S16Terminal } from './S16Terminal'

const amountText = (record: CaseRecord) => record.assetAmounts.map(({ amount, asset, unit }) => `${amount} ${asset} (${unit})`).join('; ') || 'No amount in this view'

function BlockingTerminalDialogue({ id, lines, instantText, onLineCurrent, onComplete }: { id: string; lines: readonly SpeechLine[]; instantText: boolean; onLineCurrent: (line: SpeechLine) => void; onComplete: () => void }) {
  const [lineIndex, setLineIndex] = useState(0)
  const [visible, setVisible] = useState(instantText ? lines[0]?.text.length ?? 0 : 0)
  const button = useRef<HTMLButtonElement>(null)
  const reported = useRef(new Set<number>())
  useEffect(() => { button.current?.focus() }, [])
  const line = lines[lineIndex]!
  useEffect(() => { if (!reported.current.has(lineIndex)) { reported.current.add(lineIndex); onLineCurrent(line) } }, [line, lineIndex, onLineCurrent])
  useEffect(() => { if (instantText || visible >= line.text.length) return; const timer = window.setInterval(() => setVisible((value) => Math.min(line.text.length, value + 3)), 100); return () => window.clearInterval(timer) }, [instantText, line.text.length, visible])
  const effectiveVisible = instantText ? line.text.length : visible
  const advance = () => { if (effectiveVisible < line.text.length) { setVisible(line.text.length); return } if (lineIndex + 1 < lines.length) { const next = lineIndex + 1; setLineIndex(next); setVisible(instantText ? lines[next]!.text.length : 0); return } onComplete() }
  return <section className="terminal-dialogue" role="dialog" aria-modal="true" aria-label="Blocking case dialogue" data-testid="terminal-dialogue" data-dialogue-id={id}><button ref={button} aria-label={`${publicSpeaker(line.speaker)}: ${line.text}`} onKeyDown={(event) => { if (event.repeat) event.preventDefault() }} onClick={advance}><strong aria-hidden="true">{publicSpeaker(line.speaker)}</strong><span aria-hidden="true">{line.text.slice(0, effectiveVisible)}</span><small aria-hidden="true">{effectiveVisible < line.text.length ? 'CONFIRM TO REVEAL LINE' : 'CONFIRM TO ADVANCE'}</small></button></section>
}

function Caseboard({ fixture, state, send, caps }: { fixture: CaseFixture; state: InvestigationState; send: React.Dispatch<Parameters<typeof investigationReducer>[2]>; caps: TerminalCapabilities }) {
  const known = knownRecords(fixture, state)
  const [knownCount, setKnownCount] = useState(20)
  return <section aria-label="Persistent Caseboard" className="caseboard">
    <h2>KNOWN FACTS</h2><p>{known.length} known facts; {Math.min(knownCount, known.length)} shown.</p><ul>{known.slice(0, knownCount).map((record) => <li key={record.id}>{caps.sections.includes('SOURCE') ? <button onClick={() => { send({ type: 'SELECT_RESULT', recordId: record.id }); send({ type: 'SECTION', section: 'SOURCE' }) }}>{record.summary}</button> : <span>{record.summary}</span>}<small>{record.grade} — {record.provenance.attribution}</small></li>)}</ul>{knownCount < known.length && <button onClick={() => setKnownCount(knownCount + 20)}>SHOW MORE KNOWN FACTS</button>}
    <button onClick={() => send({ type: 'READ_BRANCH', branch: 'FIRST' })}>READ FIRST BREACH MEMORY</button>{caps.allowSecondMemory && <button onClick={() => send({ type: 'READ_BRANCH', branch: 'SECOND' })}>READ SECOND BREACH MEMORY</button>}
    <h2>TRACE THREAD · {threadStatus(fixture, state)}</h2>
    <p role="status">{state.exactEventIds.length ? '◆ Exact receipt closes the gap.' : '◇ OPEN GAP: did the first trail stop or continue? Candidate fit alone cannot close it.'}</p>
    <table><caption>Trace Thread — accessible record sequence</caption><thead><tr><th>Record</th><th>UTC time</th><th>Grade</th><th>Continuity</th></tr></thead><tbody>{known.filter(({ id }) => state.pinned.includes(id)).map((record) => <tr key={record.id}><th>{record.summary}</th><td>{record.observedAtUtc}</td><td>{record.grade}</td><td><details><summary>Inspect six continuity checks</summary><ul>{threadChecks(fixture, state, record).map((check) => <li key={check.dimension}>{check.dimension}: {check.status}. {check.explanation}</li>)}</ul></details></td></tr>)}</tbody></table>
    {caps.allowTheory && <details><summary>WORKING THEORY — optional and revisable</summary><button aria-pressed={state.workingTheory === 'FIRST_TRAIL_STOPS_AT_FIRST_ENGINE'} onClick={() => send({ type: 'THEORY', theory: 'FIRST_TRAIL_STOPS_AT_FIRST_ENGINE' })}>IT STOPPED AT THE FIRST ENGINE</button><button aria-pressed={state.workingTheory === 'FIRST_TRAIL_JOINS_SECOND_ROUTE'} onClick={() => send({ type: 'THEORY', theory: 'FIRST_TRAIL_JOINS_SECOND_ROUTE' })}>IT JOINED THE SECOND ROUTE</button><button aria-pressed={state.workingTheory === null} onClick={() => send({ type: 'DEFER_THEORY' })}>I NEED AN EXACT RECEIPT BEFORE I FILE A THEORY</button><p>A theory is not a fact.</p></details>}
    {state.rejectedTheory && <article aria-label="Rejected theory"><h3>REJECTED THEORY</h3><p>{state.rejectedTheory.id}</p><p>First discovered contradiction: {known.find(({ id }) => id === state.rejectedTheory?.firstContradiction)?.summary}</p></article>}
    <details open={state.exactEventIds.length > 0}><summary>PROOF SLOTS — AMOUNT / RECEIVER / LINK</summary>{(['AMOUNT', 'RECEIVER', 'LINK'] as const).map((slot) => { const linkBlocked = slot === 'LINK' && (state.assembly.AMOUNT !== fixture.proof.slots.AMOUNT || state.assembly.RECEIVER !== fixture.proof.slots.RECEIVER); return <div key={slot}><strong>{slot}: {state.assembly[slot] ? '◆ EXACT FILED' : '◇ OPEN'}</strong>{Boolean(state.exactEventIds.length && known.some(({ id }) => id === fixture.proof.slots[slot]) && !state.assembly[slot] && !linkBlocked) && <button onClick={() => send({ type: 'ASSEMBLE', slot, recordId: fixture.proof.slots[slot] })}>FILE {slot}</button>}</div> })}<p>AMOUNT and RECEIVER may be filed in either order. LINK closes last. Contextual and corroborating views cannot fill these slots.</p></details>
    {caps.sideLeadVisible && <details><summary>OFFICE-NOTE TOKEN LEAD — OPTIONAL, NOT EULER EVIDENCE</summary><SideLeadPanel state={state} send={send} /></details>}
    {state.complete && <article data-testid="bounded-case-complete"><h2>COMPLETION READY · {fixture.proof.conclusion}</h2><p>{fixture.proof.boundary}</p><small>S13 proof state is complete. Ending dialogue and Mission 02 remain sealed for the later S14 gate.</small></article>}
  </section>
}

function SideLeadPanel({ state, send }: { state: InvestigationState; send: React.Dispatch<Parameters<typeof investigationReducer>[2]> }) {
  return <div data-testid="side-lead-panel"><p><strong>{SIDE_LEAD_HIGH_LEVEL_VIEW.sourceClass}</strong></p><h3>{SIDE_LEAD_HIGH_LEVEL_VIEW.title}</h3>{SIDE_LEAD_HIGH_LEVEL_VIEW.lines.map((text) => <p key={text.slice(0, 24)}>{text}</p>)}<details><summary>Technical-style reading</summary><dl>{SIDE_LEAD_TECHNICAL_VIEW.fields.map(([term, value]) => <div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl></details><div aria-label="Optional token choice">{SIDE_LEAD_TOKENS.map((token) => <button key={token.id} aria-pressed={state.sideLead.selectedTokenId === token.id} onClick={() => send({ type: 'SELECT_SIDE_TOKEN', tokenId: token.id })}>{token.name} · {token.address}</button>)}</div></div>
}

export function CaseTerminalWorkbench(props: { fixture: CaseFixture; state: InvestigationState; send: React.Dispatch<Parameters<typeof investigationReducer>[2]>; onClose: () => void; onCloseCase: () => void; profile?: PerformanceProfile; chromeSrc?: string | null; cursorSrc?: string | null; reviewSurfaces?: boolean }) {
  if (props.fixture.s13) return <S16Terminal fixture={props.fixture} state={props.state} send={props.send} onClose={props.onClose} onCloseCase={props.onCloseCase} chromeSrc={props.chromeSrc ?? null} cursorSrc={props.cursorSrc ?? null}/>
  return <LegacyCaseTerminalWorkbench {...props}/>
}

function LegacyCaseTerminalWorkbench({ fixture, state, send: dispatch, onClose, onCloseCase, profile, chromeSrc = null, cursorSrc = null, reviewSurfaces = false }: { fixture: CaseFixture; state: InvestigationState; send: React.Dispatch<Parameters<typeof investigationReducer>[2]>; onClose: () => void; onCloseCase: () => void; profile?: PerformanceProfile; chromeSrc?: string | null; cursorSrc?: string | null; reviewSurfaces?: boolean }) {
  const reduced = false
  const instantText = false
  const [blockingDialogue, setBlockingDialogue] = useState<{ id: string; lines: SpeechLine[] } | null>(null)
  const [terminalTranscript, setTerminalTranscript] = useState<SpeechLine[]>([])
  const seenDialogue = useRef(new Set<string>())
  const dialogueFocus = useRef<HTMLElement | null>(null)
  const [semanticSource, setSemanticSource] = useState<{fixture: CaseFixture; card: SemanticCard} | null>(null)
  const [closeConfirmation, setCloseConfirmation] = useState(false)
  const closeCaseButton = useRef<HTMLButtonElement>(null)
  const [closeCommitted, setCloseCommitted] = useState(false)
  const semanticForFixture = semanticSource?.fixture === fixture ? semanticSource.card : null
  const send = useCallback((command: Parameters<typeof investigationReducer>[2]) => {
    if (command.type === 'SELECT_RESULT' || command.type === 'RESET_CASE') setSemanticSource(null)
    dispatch(command)
  }, [dispatch])
  const heading = useRef<HTMLHeadingElement>(null)
  const exact = useRef<HTMLElement>(null)
  useEffect(() => { heading.current?.focus() }, [state.section, state.askOpen])
  useEffect(() => { if (state.exactEventIds.length) exact.current?.focus() }, [state.exactEventIds.length])
  const receiptKey = queryReceiptKey(state.query)
  useEffect(() => { if (!fixture.s13 && state.section === 'CASE' && state.askOpen && state.reviewedReceipt !== receiptKey) dispatch({ type: 'REVIEW_RECEIPT' }) }, [fixture.s13, state.section, state.askOpen, state.reviewedReceipt, receiptKey, dispatch])
  const known = knownRecords(fixture, state)
  const recs = recommendations(fixture, state)
  const receipt = queryReceipt(fixture, state.query)
  const s13Group = fixture.s13 ? s13QueryGroupForQuestion(state.query.questionId) : undefined
  const s13Summary = useMemo(() => s13Group && fixture.s13 ? s13QueryGroupSummary(fixture.s13, s13Group) : undefined, [fixture.s13, s13Group])
  const previewCount = useMemo(() => s13Summary ? s13Summary.outputCount : state.access && !queryValidationIssues(state.query).length ? dispatchQuery(fixture, state.query, null).recordIds.length : 'not evaluated — invalid query', [fixture, s13Summary, state.access, state.query])
  const selected = known.find(({ id }) => id === state.selectedRecordId)
  const s13Selected = fixture.s13?.caseCorpus.find(({ recordId }) => recordId === state.s13SelectedRecordId)
  const proofRecord = known.find(({ id }) => state.exactEventIds.includes(`EXACT.${id}`))
  const comparison = state.comparison.map((id) => known.find((record) => record.id === id)!).filter(Boolean)
  const cue = investigationCue(state)
  const caps = terminalCapabilities(fixture, state)
  const effectiveSection = caps.sections.includes(state.section) ? state.section : 'CASE'
  useEffect(() => {
    if (blockingDialogue) return
    const key = fixture.s13 ? null : state.exactConvergenceVerified && !state.exactCorrectionStarted ? 'exactCorrection' : state.workingTheory === 'FIRST_TRAIL_STOPS_AT_FIRST_ENGINE' ? 'wrongTheory' : null
    if (!key || seenDialogue.current.has(key)) return
    seenDialogue.current.add(key)
    const lines = selectHeroTerminalSpeech(key === 'exactCorrection' ? 'THEORY_RESOLUTION' : 'DELTA_2')
    if (key === 'exactCorrection') dispatch({ type: 'ACK_EXACT_CORRECTION' })
    dialogueFocus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null
    setBlockingDialogue({ id: key, lines: [...lines] })
  }, [blockingDialogue, dispatch, fixture.s13, state.exactConvergenceVerified, state.exactCorrectionStarted, state.workingTheory])
  const askCards = <div className="question-cards" aria-label="Recommended Question Cards">{recs.filter((card) => caps.askCardIds.includes(card.id)).map((card) => <article key={card.id}><small>{card.lens} · {card.stage}</small><h3>{card.question}</h3><p>{card.why}</p><button onClick={() => send({ type: 'STAGE_CARD', cardId: card.id })}>STAGE {card.question}</button><details><summary>EXPLAIN THIS · effects and claim boundary</summary><p>Prerequisites: {card.prerequisites.join(', ') || 'Selected discovered result'}</p><p>Exact effects: {card.effects.map(({ field, value }) => `${field} ${value}`).join(' AND ') || 'Compare the two selected records'}</p><p>Returns {card.resultClass}. May establish: {card.mayEstablish}</p><p>Cannot establish: {card.cannotEstablish}</p><p>Next: {card.nextRule}</p><p>Nansen data family: {card.family}</p></details></article>)}</div>
  const s13Stages = s13Summary?.stages ?? []
  const querySurface = <section aria-label="Query Receipt" className="query-receipt" data-testid="pre-dispatch-query-receipt"><h2>QUERY RECEIPT · PRE-DISPATCH REVIEW</h2><p data-testid="case-sentence"><strong>PLAYER QUESTION:</strong> {s13Group?.question ?? querySentence(state.query)}</p><p><strong>ACTIVE LENS:</strong> {receipt.questionLens} · <strong>EXPECTED RESULT CLASS:</strong> {s13Group?.expectedResultClass ?? receipt.expectedResultClass}</p>{receipt.validationIssues.length > 0 && <p role="alert" aria-label="Query validation issue">{receipt.validationIssues.join(' ')}</p>}
    {s13Group && fixture.s13 && <><p><strong>CASE-FILE CLUE ORIGINS:</strong> {[...new Set(s13Stages.flatMap(stage => stage.sourceClueIds))].join(', ') || 'Accepted corpus scope and accepted incident window; no new case fact added'}</p><h3>FILTERS / SUBPREDICATES</h3><ol>{s13Stages.map((stage, index) => <li key={stage.semanticFilterId}>{s13Group.subpredicateLabels[index]} · {stage.previousCount === null ? 'unframed' : stage.previousCount} → {stage.newCount}</li>)}</ol><p><strong>ACCEPTED SEMANTIC SUB-STAGES:</strong> {s13Group.startStage + 1}–{s13Group.endStage}; visible counts {s13Stages.map(stage => stage.newCount).join(' → ')}.</p></>}
    <ul>{state.query.filters.map((filter, index) => <li key={`${filter.field}:${index}`}>{filter.field}: {filter.value}<small>{filter.origin.replaceAll('_', ' ')} · {filter.sourceId}</small><button aria-label={`Remove ${filter.field} filter ${index + 1}`} onClick={() => send({ type: 'REMOVE_FILTER', index })}>REMOVE CHIP</button></li>)}</ul><p><strong>COVERAGE:</strong> {receipt.coverageScope}</p><p>{methodHintCopy()}</p><p><strong>NO HIDDEN FILTER WILL BE ADDED.</strong></p><p aria-label="Match-count funnel">MATCH-COUNT FUNNEL: {s13Summary?.inputCount ?? fixture.records.length} corpus records → {previewCount} matches</p><details><summary>SHOW TECHNICAL QUERY</summary><pre>{JSON.stringify({ questionId: state.query.questionId, ...canonicalQuery(state.query) }, null, 2)}</pre></details>
    {fixture.s13 && state.reviewedReceipt !== receiptKey && <button className="primary" onClick={() => send({ type: 'REVIEW_RECEIPT' })}>REVIEW QUERY RECEIPT</button>}<button className="primary" disabled={fixture.s13 ? state.reviewedReceipt !== receiptKey : false} onClick={() => send({ type: 'DISPATCH', path: 'TERMINAL' })}>DISPATCH</button><details><summary>Query recovery and saved local query</summary><button onClick={() => send({ type: 'UNDO' })} disabled={!state.past.length}>UNDO</button><button onClick={() => send({ type: 'REDO' })} disabled={!state.future.length}>REDO</button><button onClick={() => send({ type: 'RESET_LAST_DISPATCH' })}>RESET TO LAST DISPATCH</button><button onClick={() => send({ type: 'RESET_QUERY' })}>REMOVE ALL CHIPS</button><button onClick={() => send({ type: 'SAVE_QUERY' })}>SAVE LOCAL QUERY</button>{state.savedQueries.map((query, index) => <button key={index} onClick={() => send({ type: 'LOAD_QUERY', index })}>LOAD SAVED QUERY {index + 1} · {query.lens}</button>)}</details></section>
  return <TerminalViewport mode="FULLSCREEN_CRT" chromeSrc={chromeSrc} cursorSrc={cursorSrc} shellState={!state.access ? 'locked' : state.error ? 'bounded-error' : 'active'}><main data-testid="case-terminal" data-section={effectiveSection} data-terminal-stage={caps.stage} data-proof-events={state.exactEventIds.length} data-hint-milestone={terminalHintMilestone(state)} className="case-terminal mode-fullscreen_crt">
    {blockingDialogue && <BlockingTerminalDialogue
      id={blockingDialogue.id}
      lines={blockingDialogue.lines}
      instantText={instantText}
      onLineCurrent={(line) => setTerminalTranscript((entries) => [...entries, line])}
      onComplete={() => { const restore = blockingDialogue.id === 'exactCorrection' ? exact.current : dialogueFocus.current; setBlockingDialogue(null); window.requestAnimationFrame(() => restore?.focus()) }}
    />}
    <header><small>TARKA · {reviewSurfaces ? 'PLACEHOLDER SYSTEMS · ' : ''}{fixture.mode}</small><h1 ref={heading} tabIndex={-1}>CASE TERMINAL · {effectiveSection}</h1><p>Powered by Nansen API · FROZEN HISTORICAL SNAPSHOT · cutoff {fixture.cutoffUtc}</p><button onClick={onClose}>RETURN TO RECORDS OFFICE</button>{reviewSurfaces && <details data-testid="terminal-transcript"><summary>TRANSCRIPT · {terminalTranscript.length} LINES</summary><ol>{terminalTranscript.map((line, index) => <li key={index}><strong>{publicSpeaker(line.speaker)}:</strong> {line.text}</li>)}</ol></details>}</header>
    <nav aria-label="Terminal sections">{caps.sections.map((section) => <button key={section} data-testid={`terminal-section-${section.toLowerCase()}`} aria-current={effectiveSection === section ? 'page' : undefined} onClick={() => { if (section === 'SOURCE' && selected) setSemanticSource(null); send({ type: 'SECTION', section }) }}>{section}</button>)}</nav><button onClick={() => send({ type: 'SECTION', section: 'CASE' })}>BACK TO CASE</button>
    <p className="terminal-live" role="status" aria-live="polite" aria-atomic="true">{recoveryCopy(state.announcement)}</p>{state.error && <p role="alert">{state.error}</p>}
    <details><summary>Optional acting and prop cues — deterministic text fallback</summary><p aria-label="Semantic prop state">{cue.fallback}</p>{profile && <><PerformancePortrait profile={profile} character="rook" request={cue.rook} reduced={reduced}/><PerformancePortrait profile={profile} character="archivist" request={cue.archivist} reduced={reduced}/></>}</details>
    {!state.access ? <section><h2>ACCESS NOT YET EARNED</h2><p>Complete the accepted Records Office puzzle first. No provider call is needed to play.</p></section> : <>
      <section className="active-question"><small>CURRENT OBJECTIVE</small><h2>{fixture.s13 ? s13CaseFileGateSatisfied(fixture, state) ? 'TRACE THE ACCEPTED CORPUS.' : 'COLLECT AND READ THE CASE FILE.' : state.complete ? 'TRUTH RECONSTRUCTED.' : state.exactEventIds.length ? 'BUILD THE BOUNDED CASE.' : 'TEST THE FIRST TRAIL.'}</h2><p><strong>OPEN QUESTION:</strong> {fixture.s13 ? s13CaseFileGateSatisfied(fixture, state) ? 'Which accepted record survives every case-derived predicate?' : 'What aggregate evidence is available before the case facts are known?' : openQuestion(fixture, state)}</p></section>
      {effectiveSection === 'CASE' && fixture.s13 && !s13CaseFileGateSatisfied(fixture, state) && <S13Prebrief runtime={fixture.s13}/>}
      {effectiveSection === 'CASE' && (caps.showQuerySurface ? <section aria-label="Case reasoning">{askCards}<p>DISCOVERED CLUES: {visibleClues(fixture, state).map(({ label }) => label).join('; ')}</p><p>STAGED CASE SENTENCE: {querySentence(state.query)}</p><p>MATCH-COUNT FUNNEL: {s13Summary ? `${s13Summary.inputCount} corpus records → ${s13Summary.outputCount} matches` : `${fixture.records.length} → ${previewCount}`}</p><button className="primary" onClick={() => send({ type: 'ASK_QUESTION' })}>ASK A QUESTION</button><details><summary>OPEN PERSISTENT CASEBOARD</summary><Caseboard fixture={fixture} state={state} send={send} caps={caps}/></details></section> : fixture.s13 ? <section aria-label="Case reasoning"><p>{s13CaseFileGateSatisfied(fixture, state) ? 'Both accepted case-file clues are present. Open EXPLORE to begin the accepted semantic filter path.' : 'The corpus remains at aggregate-only prebrief scope until both accepted case-file clues are present.'}</p>{s13CaseFileGateSatisfied(fixture, state) && <button className="primary" onClick={() => send({ type: 'SECTION', section: 'EXPLORE' })}>OPEN ACCEPTED CORPUS</button>}</section> : <section aria-label="Case reasoning"><p>{selectHeroTerminalSpeech('PREBRIEF_INITIAL').map(line => line.text).join('\n\n')}</p></section>)}
      {effectiveSection === 'CASE' && caps.showQuerySurface && state.askOpen && <section aria-label="ASK workflow inside CASE" data-testid="case-ask-workflow"><details><summary>All discovered Question Cards and four lenses</summary>{availableCards(fixture, state).map((card) => <button key={card.id} onClick={() => send({ type: 'STAGE_CARD', cardId: card.id })}>{card.lens}: {card.question}</button>)}</details><details><summary>Reusable Query Tray — optional categories</summary>{(['STARTING_POINT', 'WHEN', 'WHAT_MOVED', 'CHECK'] as const).map((category) => <section key={category}><h3>{category.replaceAll('_', ' ')}</h3>{visibleClues(fixture, state).filter((clue) => clue.category === category).map((clue) => <article key={clue.id}><h4>{clue.label} · {clueState(fixture, state, clue.id)}</h4><button onClick={() => send({ type: 'STAGE_CLUE', clueId: clue.id })}>USE {clue.label} WITH TERMINAL</button><details><summary>LOOK AT · EXPLAIN THIS</summary><p>{clue.filters.map(({ field, value }) => `${field}: ${value}`).join('; ')}</p><p>Source: {clue.sourceRecordIds.join(', ')}. Non-consumable; reusable. Use as a {clue.category} bound.</p>{clue.displayValue && <p>Token contract: {clue.displayValue}</p>}<button onClick={() => send({ type: 'HINT', tier: 'CASE_HINT' })}>GIVE CLUE TO ARCHIVIST</button></details></article>)}</section>)}</details>{querySurface}</section>}
      {effectiveSection === 'RESULTS' && (fixture.s13 && state.s13FilterStage > 0 && !state.exactEventIds.length ? <S13Results runtime={fixture.s13} stage={state.s13FilterStage} verifiedRecordId={state.s13VerifiedRecordId} comparison={state.s13Comparison} send={send}/> : <section><h2>CANDIDATE FOLDERS</h2>{!state.result ? <p>{contentText('lane_a.recovery.reentry','Build a question inside CASE.')}</p> : <><section aria-label="Evidence Delta"><h3>EVIDENCE DELTA</h3><p>{state.result.delta.previousCount} previous → {state.result.delta.newCount} new matching records.</p><p>{state.result.delta.includedReason}</p><details><summary>First predicate excluding a previously returned candidate</summary>{state.result.delta.excluded.length ? state.result.delta.excluded.map((row) => <p key={row.recordId}>{row.recordId}: {row.firstPredicate}</p>) : <p>No previously returned candidate was excluded.</p>}</details></section>{state.result.zeroClass && <article><h3>{state.result.zeroClass}</h3><p>{zeroResultCopy(fixture,state)}</p></article>}
        {state.result.folders.slice(((state.shown - 3) / 3 % Math.ceil(state.result.folders.length / 3)) * 3, ((state.shown - 3) / 3 % Math.ceil(state.result.folders.length / 3)) * 3 + 3).map((folder) => { const record = known.find(({ id }) => id === folder.recordId)!; return <article className="candidate-folder" key={folder.id} tabIndex={-1} ref={state.exactEventIds.includes(`EXACT.${record.id}`) ? exact : undefined}><h3>{folder.summary}</h3><p>WHY IT MATCHED: {folder.whyMatched.join('; ')}</p><p><strong>{folder.grade === 'EXACT' ? '◆' : folder.grade === 'CORROBORATING' ? '▣' : '◇'} EVIDENCE GRADE: {folder.grade}</strong> — CASE STATUS: {folderStatus(state, record)}</p><details><summary>EXPLAIN THIS · boundaries and source</summary><p>WHAT IT MAY SUPPORT: {folder.maySupport}</p><p>WHAT IT DOES NOT PROVE: {folder.cannotProve}</p><p>SORT REASON: {folder.sortReason}</p><p>{record.observedAtUtc} · {amountText(record)}</p><p>Powered by Nansen API · {record.provenance.endpoint}</p></details><button onClick={() => send({ type: 'PIN', recordId: record.id })}>PIN RESULT SLIP TO CASEBOARD</button><button onClick={() => send({ type: 'SAVE_LEAD', recordId: record.id })}>SAVE LEAD</button>{caps.allowCompare && <button aria-pressed={state.comparison.includes(record.id)} onClick={() => send({ type: 'COMPARE', recordId: record.id })}>COMPARE CANDIDATE</button>}{caps.stage >= 5 && <button onClick={() => { send({ type: 'SELECT_RESULT', recordId: record.id }); send({ type: 'STAGE_CARD', cardId: 'CARD.EXACT_RECEIPT' }) }}>ASK FOR THIS EXACT RECEIPT</button>}<button onClick={() => { send({ type: 'SELECT_RESULT', recordId: record.id }); send({ type: 'STAGE_CARD', cardId: 'CARD.FOLLOW_FORWARD' }) }}>FOLLOW THIS CANDIDATE FORWARD</button><button onClick={() => { send({ type: 'SELECT_RESULT', recordId: record.id }); send({ type: 'SECTION', section: 'SOURCE' }) }}>SOURCE FOR THIS RESULT</button></article> })}
        {state.result.folders.length > 3 && <button onClick={() => send({ type: 'SHOW_MORE' })}>SHOW MORE · NEXT THREE — wraps to the first page</button>}
        {proofRecord && <article aria-label="Archived proof receipt"><h3>◆ EXACT · PROOF RECEIPT ARCHIVED</h3><dl><dt>Destination</dt><dd>{proofRecord.destination}</dd><dt>Recorded UTC</dt><dd>{proofRecord.observedAtUtc}</dd><dt>Provider-precision amount</dt><dd>{amountText(proofRecord)}</dd></dl><p>{fixture.proof.boundary}</p><button onClick={() => send({ type: 'SECTION', section: 'CASE' })}>BUILD THE CASE</button></article>}
      </>}{comparison.length === 2 && caps.allowCompare && <section aria-label="Two-candidate Comparison Tray"><h3>COMPARE THESE TWO ROUTES</h3><table><caption>Factual comparison — no confidence scores</caption><thead><tr><th>Dimension</th>{comparison.map((record) => <th key={record.id}>{record.id}</th>)}</tr></thead><tbody>{[['TIME', (r: CaseRecord) => r.observedAtUtc], ['DIRECTION / RELATIONSHIP', (r: CaseRecord) => `${r.source} → ${r.destination}`], ['ASSET / AMOUNT', amountText], ['EVIDENCE GRADE', (r: CaseRecord) => r.grade], ['COVERAGE', () => `Accepted records only, through ${fixture.cutoffUtc}`], ['EXACT RECEIPT AVAILABILITY', (r: CaseRecord) => r.exactRelationship ? 'Exact event available to verify' : 'Cannot replace exact proof']] .map(([label, fn]) => <tr key={label as string}><th>{label as string}</th>{comparison.map((record) => <td key={record.id}>{(fn as (r: CaseRecord) => string)(record)}</td>)}</tr>)}</tbody></table></section>}</section>)}
      {effectiveSection === 'SOURCE' && s13Selected && fixture.s13 && <S13Source runtime={fixture.s13} record={s13Selected} verified={state.s13VerifiedRecordId === s13Selected.recordId} canVerify={state.s13FilterStage === fixture.s13.evidenceDelta.stages.length} send={send}/>}
      {effectiveSection === 'SOURCE' && selected && !semanticForFixture && !s13Selected && <section><h2>PUBLIC-SAFE SOURCE · {selected.id}</h2><p>{selected.summary}</p><dl>{Object.entries({ 'Full transaction hash': selected.transactionHash, 'Source address': selected.source, 'Destination address': selected.destination, 'Exact UTC': selected.observedAtUtc, 'Provider precision amounts': amountText(selected), 'Nansen data family': selected.provenance.endpoint, 'Raw response SHA-256': selected.provenance.rawSha256, 'Normalized SHA-256': selected.provenance.normalizedSha256, 'Lineage': selected.provenance.lineage, 'Retrieved UTC': selected.provenance.retrievedAtUtc, 'Numeric precision': selected.provenance.precision, 'Evidence grade': selected.grade, 'Derived from': selected.derivedFrom.join(', ') || 'Independent recorded event', 'Claim boundary': selected.claimBoundary }).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{['Full transaction hash', 'Source address', 'Destination address'].includes(label) ? <ExactIdentifier key={`${selected.id}:${label}:${value}`} label={label} value={value} /> : value}</dd></div>)}</dl><p>Powered by Nansen API. Exactness of an event is not proof of identity or intent.</p></section>}
      {caps.sections.includes('EXPLORE') && <div hidden={effectiveSection !== 'EXPLORE'}>{fixture.s13 ? <S13CorpusExplorer runtime={fixture.s13} stage={state.s13FilterStage} verifiedRecordId={state.s13VerifiedRecordId} sideLead={state.sideLead} comparison={state.s13Comparison} send={send}/> : <AcceptedEvidenceSea key={fixture.id} fixture={fixture} mode={state.presentation} onInspect={card => { setSemanticSource({fixture,card}); send({type:'SECTION',section:'SOURCE'}) }}/>}</div>}
      {effectiveSection === 'SOURCE' && semanticForFixture && <SemanticDisplaySource card={semanticForFixture} onReturn={() => send({type:'SECTION',section:'EXPLORE'})}/>}
      {effectiveSection === 'SOURCE' && !selected && !semanticForFixture && !s13Selected && <section aria-label="Source inspection"><p>Select a discovered result to inspect its source.</p></section>}
      {effectiveSection === 'LEDGER' && <section aria-label="Research Ledger" data-testid="research-ledger"><h2>RESEARCH LEDGER — acquisition calls, not blockchain events</h2><p>{fixture.s13 ? `${fixture.s13.metrics.callAtlasReceipts} accepted receipts · ${fixture.s13.metrics.semanticRecords} semantic records · ${fixture.s13.metrics.providerRows} provider rows · credits ${fixture.s13.metrics.credits}` : `${fixture.ledger.attempts} HTTP attempts · ${fixture.ledger.successfulResponses} successful responses · ${fixture.ledger.curatedAcceptedCalls} curated evidence calls · credits ${fixture.ledger.credits ?? 'not acquired in this fixture gate'}`}</p>{!fixture.s13 && <><p>Account-level competition quota evidence is tracked separately in submission provenance, not this case corpus.</p><p>Proof root: {fixture.ledger.proofRoot ?? 'none — no NQ5 campaign issued'}</p></>}<p>{contentText('lane_a.ledger.atlas','Inspect bound source lineage and evidence consumers.')}</p><details><summary>WHY NANSEN HELPED</summary><ul><li>ACTIVITY: organizes historical activity.</li><li>RELATIONSHIPS: prioritizes observed interactions; frequency is not causation.</li><li>STATE: bounded changes may corroborate; a balance change cannot identify its causing transaction.</li><li>RECEIPT: exposes exact records that can test continuity.</li></ul><p>The player performs the interpretation. {fixture.proof.boundary}</p></details></section>}
      {effectiveSection === 'LEDGER' && (fixture.s13 ? <S13CallAtlas runtime={fixture.s13}/> : <EvidenceAtlas fixture={fixture} state={state}/>)}
      {state.complete && <section className="close-case-state" data-testid="s14-close-case-ready"><h2>CASE STATUS<br/>SOLVED</h2><button ref={closeCaseButton} className="primary" onClick={() => setCloseConfirmation(true)}>[ CLOSE CASE ]</button></section>}
      {closeConfirmation && <section className="terminal-dialogue" role="dialog" aria-modal="true" aria-labelledby="close-case-title" data-testid="s14-close-case-confirmation"><h2 id="close-case-title">CLOSE THIS CASE<br/>AND END THE INVESTIGATION?</h2><button autoFocus disabled={closeCommitted} onClick={() => { if (closeCommitted) return; setCloseCommitted(true); onCloseCase() }}>[ CLOSE CASE ]</button><button onClick={() => { setCloseConfirmation(false); window.requestAnimationFrame(() => closeCaseButton.current?.focus()) }}>[ RETURN TO PROOF ]</button></section>}
      <footer><details><summary>ASK THE ARCHIVIST · explanations and recovery</summary>{(['METHOD_HINT', 'CASE_HINT', 'DIRECT_HINT'] as const).map((tier) => <button key={tier} onClick={() => send({ type: 'HINT', tier })}>{tier.replaceAll('_', ' ')}</button>)}<button onClick={() => send({ type: 'RESET_CASE' })}>RESET TO CASE START</button></details><p>Critical clues are non-consumable. No live provider calls during play.</p></footer>
    </>}
  </main></TerminalViewport>
}
