import type { HotspotId, InventoryItemId, PuzzlePhase, VerbId } from '../../adventure/types'
export type InputMode='MOUSE_TOUCH'|'KEYBOARD'
export interface DrawerStepRequirement { drawer: 'caseFileDrawer' | 'miscDrawer'; is: 'OPEN' | 'CLOSED' }
export interface ContactGrantStep { contact: string; addItems: readonly InventoryItemId[] }
export interface OfficeStep {order:number;id:string;phaseBefore:PuzzlePhase|'ANY';phaseAfter:PuzzlePhase|null;verb:VerbId|null;target:HotspotId|null;requiredItem:InventoryItemId|null;removeItems:readonly InventoryItemId[];addItems:readonly InventoryItemId[];handoverContact:string|null;handoverRemove:readonly InventoryItemId[];handoverNextPhase:PuzzlePhase|null;requiresDrawer:DrawerStepRequirement|null;setCaseFileDrawer:'OPEN'|'CLOSED'|null;setMiscDrawer:'OPEN'|'CLOSED'|null;requiresStack:'UNSEARCHED'|'SEARCHED_EULER_REMOVED'|null;requiresMisc:'UNCOLLECTED'|'COLLECTED_GUM_REMAINS'|null;contactGrants:readonly ContactGrantStep[];drawerStateAfterCaseStack:'UNSEARCHED'|'SEARCHED_EULER_REMOVED'|null;drawerStateAfterMisc:'UNCOLLECTED'|'COLLECTED_GUM_REMAINS'|null;objectBefore:string;objectAfter:string;copyPrefix:string;arthurRole:string;focusDestination:string;inputModes:readonly InputMode[];fallback:string;repeat:string;recovery:string}
const modes=['MOUSE_TOUCH','KEYBOARD'] as const
const step=(order:number,id:string,phaseBefore:PuzzlePhase|'ANY',phaseAfter:PuzzlePhase|null,verb:VerbId|null,target:HotspotId|null,requiredItem:InventoryItemId|null,removeItems:readonly InventoryItemId[],addItems:readonly InventoryItemId[],objectBefore:string,objectAfter:string,focusDestination:string,handover?:{contact:string;remove:readonly InventoryItemId[];nextPhase:PuzzlePhase},arthurRole='Procedural method and scope only; never supplies undiscovered case values.'):OfficeStep=>({order,id,phaseBefore,phaseAfter,verb,target,requiredItem,removeItems,addItems,handoverContact:handover?.contact??null,handoverRemove:handover?.remove??[],handoverNextPhase:handover?.nextPhase??null,requiresDrawer:null,setCaseFileDrawer:null,setMiscDrawer:null,requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore,objectAfter,copyPrefix:id==='ARRIVAL'?'lane_a.opening':'lane_a.puzzle.'+id,arthurRole,focusDestination,inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'})
export const RECORDS_OFFICE_STEPS:readonly OfficeStep[]=[
 step(1,'ARRIVAL','START','START',null,null,null,[],[],'authorization arrival','all nine verbs available','request-dispenser'),
 step(2,'take-form','START','FORM_HELD','PICK_UP','blank-authorization-form',null,[],['blank-terminal-authorization-form'],'blank authorization form ready','blank authorization form taken','inventory'),
 step(3,'take-pen','START','PEN_HELD','PICK_UP','pen-stand',null,[],['loose-feather-pen'],'loose pen in inkwell','loose feather pen taken','inventory'),
 step(4,'take-form-2','PEN_HELD','FORM_AND_PEN','PICK_UP','blank-authorization-form',null,[],['blank-terminal-authorization-form'],'blank authorization form ready','blank authorization form taken','inventory'),
 step(5,'take-pen-2','FORM_HELD','FORM_AND_PEN','PICK_UP','pen-stand',null,[],['loose-feather-pen'],'loose pen in inkwell','loose feather pen taken','inventory'),
 step(6,'give-form','FORM_COMPLETED','COMPLETE','GIVE','mr-index','signed-terminal-authorization-form-with-doodles',[],['approved-stamped-terminal-authorization-form'],'signed form with doodles','approved stamped form returned; terminal authorized','inventory',{contact:'CONTACT.FORM_HANDOFF',remove:['signed-terminal-authorization-form-with-doodles'],nextPhase:'FORM_SUBMITTED'},'Arthur performs the explicit procedural review, stamp, and return; authorization is true only at the return contact.'),
 step(7,'reprimand-start','START','START','USE','nansen-terminal',null,[],[],'terminal unauthorized','reprimand played; terminal closed','nansen-terminal'),
 step(8,'reprimand-form-held','FORM_HELD','FORM_HELD','USE','nansen-terminal',null,[],[],'terminal unauthorized','reprimand played; terminal closed','nansen-terminal'),
 step(9,'reprimand-pen-held','PEN_HELD','PEN_HELD','USE','nansen-terminal',null,[],[],'terminal unauthorized','reprimand played; terminal closed','nansen-terminal'),
 step(10,'reprimand-form-and-pen','FORM_AND_PEN','FORM_AND_PEN','USE','nansen-terminal',null,[],[],'terminal unauthorized','reprimand played; terminal closed','nansen-terminal'),
 step(11,'reprimand-form-completed','FORM_COMPLETED','FORM_COMPLETED','USE','nansen-terminal',null,[],[],'terminal unauthorized','reprimand played; terminal closed','nansen-terminal'),
 step(12,'reprimand-form-submitted','FORM_SUBMITTED','FORM_SUBMITTED','USE','nansen-terminal',null,[],[],'terminal unauthorized','reprimand played; terminal closed','nansen-terminal'),
 step(14,'look-case-cabinet','ANY',null,'LOOK_AT','official-case-file-cabinet',null,[],[],'official drawer uninspected','cabinet observed without unlock','official-case-file-cabinet'),
 step(16,'look-drawer','ANY',null,'LOOK_AT','miscellaneous-drawer-cabinet',null,[],[],'misc drawer uninspected','drawer observed without acquisition','miscellaneous-drawer-cabinet'),
 step(17,'combine-form-pen','FORM_AND_PEN','FORM_COMPLETED','USE',null,'blank-terminal-authorization-form',['blank-terminal-authorization-form','loose-feather-pen'],['signed-terminal-authorization-form-with-doodles','broken-feather-pen'],'blank form plus loose pen','signed form with doodles plus broken pen','inventory'),
 step(18,'open-toolbox','ANY',null,'OPEN',null,'small-toolbox-closed',['small-toolbox-closed'],['small-toolbox-open-empty','hammer','nails'],'closed small toolbox','open-empty toolbox retained with hammer and nails','inventory'),
 step(19,'smash-piggy','ANY',null,'USE',null,'hammer',['piggy-bank-intact'],['fictional-token-note'],'intact piggy bank','note item with token lead; hammer retained; note unread','inventory'),
 step(20,'use-toolbox','ANY',null,'USE',null,'small-toolbox-closed',['small-toolbox-closed'],['small-toolbox-open-empty','hammer','nails'],'closed small toolbox','open-empty toolbox retained with hammer and nails','inventory'),
 step(21,'open-toolbox-open','ANY',null,'OPEN',null,'small-toolbox-open-empty',[],[],'open empty toolbox','already open and empty; hammer and nails already out','inventory'),
 step(22,'use-toolbox-open','ANY',null,'USE',null,'small-toolbox-open-empty',[],[],'open empty toolbox','already open and empty; hammer and nails already out','inventory'),
 {order:23,id:'open-case-drawer',phaseBefore:'ANY',phaseAfter:null,verb:'OPEN',target:'official-case-file-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'caseFileDrawer',is:'CLOSED'},setCaseFileDrawer:'OPEN',setMiscDrawer:null,requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'case drawer closed',objectAfter:'case drawer open; contents revealed',copyPrefix:'lane_a.puzzle.open-case-drawer',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'official-case-file-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:24,id:'pull-case-drawer',phaseBefore:'ANY',phaseAfter:null,verb:'PULL',target:'official-case-file-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'caseFileDrawer',is:'CLOSED'},setCaseFileDrawer:'OPEN',setMiscDrawer:null,requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'case drawer closed',objectAfter:'case drawer open; contents revealed',copyPrefix:'lane_a.puzzle.pull-case-drawer',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'official-case-file-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:25,id:'close-case-drawer',phaseBefore:'ANY',phaseAfter:null,verb:'CLOSE',target:'official-case-file-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'caseFileDrawer',is:'OPEN'},setCaseFileDrawer:'CLOSED',setMiscDrawer:null,requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'case drawer open',objectAfter:'case drawer closed; contents hidden',copyPrefix:'lane_a.puzzle.close-case-drawer',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'official-case-file-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:26,id:'push-case-drawer',phaseBefore:'ANY',phaseAfter:null,verb:'PUSH',target:'official-case-file-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'caseFileDrawer',is:'OPEN'},setCaseFileDrawer:'CLOSED',setMiscDrawer:null,requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'case drawer open',objectAfter:'case drawer closed; contents hidden',copyPrefix:'lane_a.puzzle.push-case-drawer',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'official-case-file-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:27,id:'use-case-drawer-open',phaseBefore:'ANY',phaseAfter:null,verb:'USE',target:'official-case-file-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'caseFileDrawer',is:'CLOSED'},setCaseFileDrawer:'OPEN',setMiscDrawer:null,requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'case drawer closed',objectAfter:'case drawer open; contents revealed',copyPrefix:'lane_a.puzzle.use-case-drawer-open',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'official-case-file-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:28,id:'use-case-drawer-shut',phaseBefore:'ANY',phaseAfter:null,verb:'USE',target:'official-case-file-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'caseFileDrawer',is:'OPEN'},setCaseFileDrawer:'CLOSED',setMiscDrawer:null,requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'case drawer open',objectAfter:'case drawer closed; contents hidden',copyPrefix:'lane_a.puzzle.use-case-drawer-shut',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'official-case-file-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:29,id:'look-case-stack',phaseBefore:'ANY',phaseAfter:null,verb:'LOOK_AT',target:'disorderly-stack-of-confidential-files',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'caseFileDrawer',is:'OPEN'},setCaseFileDrawer:null,setMiscDrawer:null,requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'confidential stack revealed',objectAfter:'stack observed without search',copyPrefix:'lane_a.puzzle.look-case-stack',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'disorderly-stack-of-confidential-files',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:30,id:'pickup-case-stack',phaseBefore:'ANY',phaseAfter:null,verb:'PICK_UP',target:'disorderly-stack-of-confidential-files',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'caseFileDrawer',is:'OPEN'},setCaseFileDrawer:null,setMiscDrawer:null,requiresStack:'UNSEARCHED',requiresMisc:null,contactGrants:[{contact:'CONTACT.CASEFILE_COLLECT',addItems:['euler-case-file']}],drawerStateAfterCaseStack:'SEARCHED_EULER_REMOVED',drawerStateAfterMisc:null,objectBefore:'confidential stack unsearched',objectAfter:'Euler file acquired once at rummage contact',copyPrefix:'lane_a.puzzle.pickup-case-stack',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'disorderly-stack-of-confidential-files',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:31,id:'open-misc-drawer',phaseBefore:'ANY',phaseAfter:null,verb:'OPEN',target:'miscellaneous-drawer-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'miscDrawer',is:'CLOSED'},setCaseFileDrawer:null,setMiscDrawer:'OPEN',requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'misc drawer closed',objectAfter:'misc drawer open; contents revealed',copyPrefix:'lane_a.puzzle.open-misc-drawer',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'miscellaneous-drawer-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:32,id:'pull-misc-drawer',phaseBefore:'ANY',phaseAfter:null,verb:'PULL',target:'miscellaneous-drawer-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'miscDrawer',is:'CLOSED'},setCaseFileDrawer:null,setMiscDrawer:'OPEN',requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'misc drawer closed',objectAfter:'misc drawer open; contents revealed',copyPrefix:'lane_a.puzzle.pull-misc-drawer',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'miscellaneous-drawer-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:33,id:'close-misc-drawer',phaseBefore:'ANY',phaseAfter:null,verb:'CLOSE',target:'miscellaneous-drawer-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'miscDrawer',is:'OPEN'},setCaseFileDrawer:null,setMiscDrawer:'CLOSED',requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'misc drawer open',objectAfter:'misc drawer closed; contents hidden',copyPrefix:'lane_a.puzzle.close-misc-drawer',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'miscellaneous-drawer-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:34,id:'push-misc-drawer',phaseBefore:'ANY',phaseAfter:null,verb:'PUSH',target:'miscellaneous-drawer-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'miscDrawer',is:'OPEN'},setCaseFileDrawer:null,setMiscDrawer:'CLOSED',requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'misc drawer open',objectAfter:'misc drawer closed; contents hidden',copyPrefix:'lane_a.puzzle.push-misc-drawer',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'miscellaneous-drawer-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:35,id:'use-misc-drawer-open',phaseBefore:'ANY',phaseAfter:null,verb:'USE',target:'miscellaneous-drawer-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'miscDrawer',is:'CLOSED'},setCaseFileDrawer:null,setMiscDrawer:'OPEN',requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'misc drawer closed',objectAfter:'misc drawer open; contents revealed',copyPrefix:'lane_a.puzzle.use-misc-drawer-open',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'miscellaneous-drawer-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:36,id:'use-misc-drawer-shut',phaseBefore:'ANY',phaseAfter:null,verb:'USE',target:'miscellaneous-drawer-cabinet',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'miscDrawer',is:'OPEN'},setCaseFileDrawer:null,setMiscDrawer:'CLOSED',requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'misc drawer open',objectAfter:'misc drawer closed; contents hidden',copyPrefix:'lane_a.puzzle.use-misc-drawer-shut',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'miscellaneous-drawer-cabinet',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:37,id:'look-misc-contents',phaseBefore:'ANY',phaseAfter:null,verb:'LOOK_AT',target:'miscellaneous-catch-all-contents',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'miscDrawer',is:'OPEN'},setCaseFileDrawer:null,setMiscDrawer:null,requiresStack:null,requiresMisc:null,contactGrants:[],drawerStateAfterCaseStack:null,drawerStateAfterMisc:null,objectBefore:'catch-all contents revealed',objectAfter:'contents observed without acquisition',copyPrefix:'lane_a.puzzle.look-misc-contents',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'miscellaneous-catch-all-contents',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
 {order:38,id:'pickup-misc-contents',phaseBefore:'ANY',phaseAfter:null,verb:'PICK_UP',target:'miscellaneous-catch-all-contents',requiredItem:null,removeItems:[],addItems:[],handoverContact:null,handoverRemove:[],handoverNextPhase:null,requiresDrawer:{drawer:'miscDrawer',is:'OPEN'},setCaseFileDrawer:null,setMiscDrawer:null,requiresStack:null,requiresMisc:'UNCOLLECTED',contactGrants:[{contact:'CONTACT.DRAWER_PICKUP_1',addItems:['rubber-band']},{contact:'CONTACT.DRAWER_PICKUP_2',addItems:['rubiks-cube']},{contact:'CONTACT.DRAWER_PICKUP_3',addItems:['sharknado-2-vhs']},{contact:'CONTACT.DRAWER_PICKUP_4',addItems:['piggy-bank-intact']},{contact:'CONTACT.DRAWER_PICKUP_5',addItems:['small-toolbox-closed']}],drawerStateAfterCaseStack:null,drawerStateAfterMisc:'COLLECTED_GUM_REMAINS',objectBefore:'catch-all contents uncollected',objectAfter:'five items acquired one per reach contact',copyPrefix:'lane_a.puzzle.pickup-misc-contents',arthurRole:'Procedural method and scope only; never supplies undiscovered case values.',focusDestination:'miscellaneous-catch-all-contents',inputModes:modes,fallback:'Instant text and static semantic state; no audio, animation, color, timing, typing or drag required.',repeat:'Safe and idempotent; completed facts, inventory and case state remain.',recovery:'Wrong verb, item or premature action preserves phase and inventory and returns accepted useful feedback.'},
]
export const TERMINAL_FIRST_RUN=[
 {order:1,id:'EARNED_ACCESS',mandatoryDispatch:false,teaches:'Starting clues are reusable; Arthur explains method and scope.'},
 {order:2,id:'BROAD_EVIDENCE_SEA',mandatoryDispatch:false,teaches:'EXPLORE shows all25 accepted display records and seven bounded no-match views.'},
 {order:3,id:'BOUNDED_QUESTION',mandatoryDispatch:false,teaches:'At most three useful cards explain inputs, effects, limits and next question.'},
 {order:4,id:'QUERY_RECEIPT',mandatoryDispatch:false,teaches:'Plain question, origins, lens, coverage and result class; no hidden filter.'},
 {order:5,id:'EVIDENCE_DELTA',mandatoryDispatch:true,teaches:'Previous/new counts and first excluding predicate; at most three folders and fact-only comparison.'},
 {order:6,id:'THEORY_RECOVERY',mandatoryDispatch:false,teaches:'A plausible wrong theory remains visible after exact correction without reset.'},
 {order:7,id:'EXACT_RECEIPT_AND_PROOF',mandatoryDispatch:true,teaches:'Only accepted independent exact evidence fills AMOUNT, RECEIVER and LINK.'},
 {order:8,id:'RETURN_REENTRY',mandatoryDispatch:false,teaches:'Completed case and local discoveries persist; optional banter never gates.'}
] as const
export const MISSION_INVARIANTS={maxMandatoryFirstRunDispatches:3,directMayUseFewer:true,optionalExploreUnlimited:true,externalRequests:0,title:'LATE_BOUND',dialogueDensity:'LATE_BOUND',conclusion:'THE FIRST TRAIL JOINED THE SECOND ROUTE.',firstExactTurningPointUtc:'2023-03-13T11:38:11Z',proofSlots:['AMOUNT','RECEIVER','LINK'] as const}
export function officeStepForPhase(phase:PuzzlePhase){for(let i=RECORDS_OFFICE_STEPS.length-1;i>=0;i--)if(RECORDS_OFFICE_STEPS[i]!.phaseBefore===phase)return RECORDS_OFFICE_STEPS[i]!;return RECORDS_OFFICE_STEPS[0]!}
