import fs from 'node:fs'
import path from 'node:path'
import {execFileSync} from 'node:child_process'
import {identity,sha} from '../nq5/schema.mjs'
import {gitEnv} from '../nq5-b1-r1/gates.mjs'
import {source as historicalSource,cut,digest,seal} from '../nq5-p2/authority.mjs'
export {cut,digest,seal}
export const BASE='cb7f3f6fab508f4aa8313567f8785215f7bd04f5',TREE='a586c46e06bea63b171b69a8f36898685f537ffd',PARENT='728033be8e2f1cd0290ecfb92830925d6a84a31e'
export const ARCHIVE='TRACE_ESCAPE_G6P_NQ5_T1_P2_P1_LEAD_ACCEPTANCE_INVESTIGATION_CORPUS_NARRATIVE_BREADTH_AND_P3_SCALE_FREEZE_DELIVERY_v1.0.1.zip',ARCHIVE_SHA='0835026b9701fa0251c418d90f7b533ad31a3397a6f03112f807f3f5e83f17ae',ARCHIVE_BYTES=52231607
export const CONTRACT='docs/source/execution-p2-r1/54_G6P_NQ5_T1_P2_R1_EXECUTION_CONTRACT.txt',CONTRACT_SHA='a4bcc06e6dd1ed598e5172d4a993bf1a5f7e9bd887468ebc73a5f031d0deee80',MANIFEST='docs/source/ACTIVE_P2_R1_SOURCE_MANIFEST.sha256'
export const DIFF_SHA='e25a08261f0e60162e3c9c3896651c454ccb002485233b29c005157141033e28',LEDGER_SHA='a363106c71c52e1b83838590cfc7a77da8bac8799a55a7ae0164ff2891bb6c88',LEDGER_BYTES=248037,SEMANTIC='b35686538f4cb769d99c60aecd8c4817e283ee75309faff2b66bd021174fbf56'
export const OUTPUT='TRACE_ESCAPE_G6P_NQ5_T1_P2_R1_PARTIAL_ACCEPTANCE_ANTI_CARTESIAN_REMEDIATION_DELIVERY_v1.0.0.zip'
export const REVIEWS=['docs/G6P_NQ5_T1_P2_R1_REVIEW_A_REVIEW.json','docs/G6P_NQ5_T1_P2_R1_REVIEW_B_REVIEW.json']
export const git=(root,...args)=>execFileSync('git',args,{cwd:root,env:gitEnv(),encoding:'utf8',maxBuffer:256000000}).trimEnd()
export function source(root){const old=historicalSource(root,{validate:true}),bytes=fs.readFileSync(path.join(root,CONTRACT)),m=fs.readFileSync(path.join(root,MANIFEST),'utf8');if(sha(bytes)!==CONTRACT_SHA||m!==fs.readFileSync(path.join(root,'docs/source/ACTIVE_P2_CORRECTED_SOURCE_MANIFEST.sha256'),'utf8')+CONTRACT_SHA+'  '+CONTRACT+'\n')throw new Error('P2_R1_ADDITIVE_SOURCE_BINDING');return {...old,governedRepositorySourceFiles:83,r1ExecutionContractSha256:CONTRACT_SHA,r1SourceManifestSha256:sha(Buffer.from(m)),historicalSourceFilesUnchanged:true}}
export function disposition(root){source(root);const text=fs.readFileSync(path.join(root,CONTRACT),'utf8'),pick=(s,key)=>{const m=s.match(new RegExp('^- '+key+': (.+)$','m'));if(!m)throw new Error('P2_R1_EXACT_DISPOSITION_PARSE');return m[1]},acceptances=[...text.matchAll(/ACCEPTANCE ORDER (\d+)\n([\s\S]*?)(?=\nACCEPTANCE ORDER|\nFor all seven)/g)].map(m=>({leadAcceptanceOrder:Number(m[1]),logicalId:pick(m[2],'logical request ID'),role:pick(m[2],'role'),resultCount:Number(pick(m[2],'result count(?: or bounded page-1 match count)?')),providerRequestId:pick(m[2],'provider request ID'),rawSha256:pick(m[2],'raw SHA-256'),normalizedSha256:pick(m[2],'normalized SHA-256'),terminalIdentity:pick(m[2],'terminal identity'),claimBoundary:pick(m[2],'accepted claim boundary')})),holds=[...text.matchAll(/HOLD ([ABC])\n([\s\S]*?)(?=\nHOLD|\nA strict subwindow)/g)].map(m=>({hold:m[1],logicalId:pick(m[2],'logical request ID'),providerRequestId:pick(m[2],'provider request ID'),terminalIdentity:pick(m[2],'terminal identity'),priorAcceptedZeroLogicalId:pick(m[2],'prior accepted full-window same-filter zero logical request')})),states=text.slice(text.indexOf('Record all of these exact disposition states:'),text.indexOf('The overall P2 gate')).split('\n').filter(x=>/^[A-Z][A-Z0-9_]+$/.test(x));if(acceptances.length!==7||holds.length!==3||acceptances.some((r,i)=>r.leadAcceptanceOrder!==19+i)||new Set([...acceptances,...holds].map(r=>r.logicalId)).size!==10||states.length!==17)throw new Error('P2_R1_EXACT_SEVEN_THREE_SEVENTEEN_DISPOSITIONS');return {acceptances,holds,states}}
export function reviewed(root){source(root);if(git(root,'rev-parse',BASE+'^{tree}')!==TREE||git(root,'rev-parse',BASE+'^')!==PARENT)throw new Error('P2_R1_REVIEWED_LINEAGE');git(root,'merge-base','--is-ancestor','a1bf6689b9ba6a3c7077869ee03be1926b2e1c41',BASE);git(root,'merge-base','--is-ancestor',BASE,'HEAD');const z=path.join(path.dirname(root),ARCHIVE),b=fs.readFileSync(z);if(b.length!==ARCHIVE_BYTES||sha(b)!==ARCHIVE_SHA)throw new Error('P2_R1_REVIEWED_ARCHIVE_BYTES');const read=n=>execFileSync('unzip',['-p',z,n],{env:gitEnv(),maxBuffer:256000000}),names=execFileSync('unzip',['-Z1',z],{env:gitEnv(),encoding:'utf8'}).trimEnd().split('\n'),manifest=read('MANIFEST.sha256').toString().trimEnd().split('\n');if(names.length!==70||new Set(names).size!==70||names.some(n=>n.startsWith('/')||n.split('/').some(p=>!p||p==='.'||p==='..')||n.includes('\\'))||manifest.length!==69)throw new Error('P2_R1_REVIEWED_MEMBER_SET');const bytes={};for(const l of manifest){const h=l.slice(0,64),n=l.slice(66);if(!/^[a-f0-9]{64}$/.test(h)||!names.includes(n)||bytes[n])throw new Error('P2_R1_REVIEWED_MANIFEST');const b=read(n);if(sha(b)!==h)throw new Error('P2_R1_REVIEWED_MEMBER_SHA');if(n!=='GIT/trace-escape-complete.bundle'&&n!=='SOURCE_DIFF.patch')bytes[n]=b};const diff=execFileSync('git',['diff','--binary','a1bf6689b9ba6a3c7077869ee03be1926b2e1c41',BASE],{cwd:root,env:gitEnv(),maxBuffer:256000000});if(sha(diff)!==DIFF_SHA||!diff.equals(read('SOURCE_DIFF.patch')))throw new Error('P2_R1_EXACT_SOURCE_DIFF');const objects=Object.fromEntries(Object.entries(bytes).filter(([n])=>n.endsWith('.json')).map(([n,b])=>[n,JSON.parse(b)]));if(objects['CONTRACTS/INVESTIGATION_CORPUS_SEMANTIC_ABSTRACTION.json'].hash!==SEMANTIC||identity(objects['DELIVERY_MANIFEST.json'].candidate)!==identity({commit:BASE,tree:TREE}))throw new Error('P2_R1_REVIEWED_SEMANTIC_CANDIDATE');return {objects,bytes,archiveSha256:ARCHIVE_SHA,archiveBytes:ARCHIVE_BYTES,sourceDiffSha256:DIFF_SHA}}
