import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {spawn,execFileSync} from 'node:child_process'
import {identity,sha} from '../nq5/schema.mjs'
import {readEvidence} from '../nq5-p2/evidence-files.mjs'
import {admitSuiteLogs,assertAdmittedSuiteLogs,sanitizedLogBytes} from '../nq5-p2/logs.mjs'
import {pathScan} from '../nq5-b1-r2/privacy.mjs'
import {derive,serialize} from './model.mjs'
import {localGate,reviewGate,SUITES} from './gates.mjs'
import {BASE,OUTPUT,CONTRACT_SHA,ARCHIVE_SHA,MANIFEST,cut,digest} from './authority.mjs'
import {OFF} from './partial.mjs'
const CORE=['RECEIPTS/P2_LEAD_PARTIAL_ACCEPTANCE_RECEIPT.json','PUBLIC/NQ5_PUBLIC_CALL_INDEX.json','PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256','SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json','EVIDENCE/NANSEN_API_REQUEST_AUDIT.json','SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json','REPORTS/T1_P2_R1_RECONCILIATION_REPORT.json','REPORTS/T1_P2_R1_UTILITY_REPORT.json','REPORTS/T1_CAMPAIGN_STATE_REDACTED.json','EVIDENCE/COMPLETE_CANDIDATE_REJECTION_AND_RETIREMENT_MATRIX.json','EVIDENCE/NO_CREDIBLE_SCALE_PATH_ASSESSMENT.json','EVIDENCE/PRIMARY_MIRROR_LEDGER_INTEGRITY.json','EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json','EVIDENCE/KT_CONTINUITY_DELTA.json','EVIDENCE/SOURCE_UPDATE_REQUIREMENTS_DELTA.json']
const EXTRA=['README.md','DELIVERY_MANIFEST.json','MANIFEST.sha256','VERIFY_DELIVERY.mjs','GIT/trace-escape-complete.bundle','SOURCE_DIFF.patch','SOURCE/ACTIVE_SOURCE_MANIFEST.sha256','EVIDENCE/BUGBOT_P2_R1_REVIEW_A.json','EVIDENCE/BUGBOT_P2_R1_REVIEW_B.json','EVIDENCE/VERIFICATION_SUMMARY.json','EVIDENCE/REVIEW_FINDINGS_RESOLUTIONS.json']
const PACK_LOGS=['bundle-clone-fsck','fresh-clone-current-tree-secret','fresh-clone-history-secret','redacted-delivery-secret','exact-read-only-private-index-reconciliation']
export const ALLOW=[...CORE,...EXTRA,...[...SUITES,...PACK_LOGS].map(n=>'LOGS/'+n+'.log')].sort()
const files=dir=>fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(e=>{if(e.isSymbolicLink())throw new Error('P2_R1_PACKAGE_LINK');const f=path.join(dir,e.name);return e.isDirectory()?files(f):[f]})
function verifyArchive(){
 const hash=b=>createHash('sha256').update(b).digest('hex'),canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}',id=v=>hash(Buffer.from(canonical(v)))
 function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{if(e.isSymbolicLink())throw new Error('DELIVERY_LINK');const f=path.join(d,e.name);return e.isDirectory()?walk(f):[path.relative(root,f)]}).sort()}
 if(JSON.stringify(walk(root))!==JSON.stringify(allowed))throw new Error('DELIVERY_EXACT_ALLOWLIST')
 const read=n=>{if(!allowed.includes(n))throw new Error('DELIVERY_NAME');const f=path.join(root,n),s=fs.lstatSync(f);if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1)throw new Error('DELIVERY_REGULAR_FILE');return fs.readFileSync(f)},lines=read('MANIFEST.sha256').toString().trimEnd().split('\n'),seen=new Set()
 if(lines.length!==allowed.length-1)throw new Error('DELIVERY_HASH_COUNT')
 for(const l of lines){const h=l.slice(0,64),n=l.slice(66);if(!/^[a-f0-9]{64}$/.test(h)||l.slice(64,66)!=='  '||seen.has(n)||n==='MANIFEST.sha256'||!allowed.includes(n)||hash(read(n))!==h)throw new Error('DELIVERY_HASH');seen.add(n)}
 const parse=n=>JSON.parse(read(n)),d=parse('DELIVERY_MANIFEST.json'),index=parse('PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'),receipt=parse('RECEIPTS/P2_LEAD_PARTIAL_ACCEPTANCE_RECEIPT.json'),r=parse('REPORTS/T1_P2_R1_RECONCILIATION_REPORT.json'),audit=parse('EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'),{hash:sealed,...payload}=receipt
 if(sealed!==id(payload)||sealed!==d.partialLeadReceiptIdentity||index.length!==d.formalLeadAccepted||id(index)!==d.acceptedPublicIndexIdentity||id(index.slice(0,18))!==d.priorAcceptedPublicIndexIdentity||new Set(index.map(x=>x.public_call_id)).size!==index.length)throw new Error('DELIVERY_RECEIPT_INDEX')
 if(index.some(x=>x.lead_acceptance_status!=='ACCEPTED'||x.raw_payload_published||x.gameplay_integration_accepted)||[...receipt.historicalPermanentHolds,...receipt.newPermanentHolds].some(h=>index.some(x=>x.public_call_id===h.publicCallId)))throw new Error('DELIVERY_HELD_PENDING_ROW')
 if(!['DELIVERED_PENDING_LEAD_REVIEW','BLOCKED_WITH_EVIDENCE'].includes(d.status)||r.httpAttempts!==47||r.provider2xx!==33||r.supplierCountedTerminals!==31||r.knownCampaignCredits!==37||r.unresolvedReservations!==14||r.unresolvedTerminals!==0||r.newAttempts!==24||r.newProvider2xx!==10||r.p2PlannedNeverIssued!==21||audit.p2Records.flatMap(x=>x.attempts).length!==24)throw new Error('DELIVERY_COUNTS')
 for(const v of[d,receipt,r])for(const k of['AUTHORIZED_TO_ISSUE','P3_AUTHORIZED_TO_ISSUE','LaneC','TE_IFACE_CORPUS_FROZEN','controllerSeamCommit','gameplayIntegrationAccepted'])if(v[k]!==false)throw new Error('DELIVERY_AUTHORITY')
 console.log(JSON.stringify({status:'PASS',files:allowed.length,hashes:seen.size,formalLeadAccepted:index.length,scalePath:'NO_CREDIBLE_SCALE_PATH_YET',newNetworkRequests:0}))
}
export function verifier(){return "import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';\nconst root=path.dirname(fileURLToPath(import.meta.url)),allowed="+JSON.stringify(ALLOW)+";\n("+verifyArchive.toString()+")();\n"}
// Generate outside the wx-only final package; put() admits the verified copy.
export const bundlePath=temp=>path.join(temp,'trace-escape-complete.bundle')
export async function deliver(root,childEnv){
 const v=localGate(root),logs=admitSuiteLogs(v,n=>readEvidence(path.join(root,'artifacts/g6p-p2-r1/local'),n+'.log')),reviews=[0,1].map(i=>reviewGate(root,i)),d=derive(root),candidate=cut(root),implementation=digest(root)
 if(identity(Object.keys(d.entries).sort())!==identity([...CORE].sort()))throw new Error('P2_R1_EXACT_CORE_ALLOWLIST')
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'p2-r1-delivery-')),dir=path.join(temp,'package');fs.mkdirSync(dir);const payload={},bindings=[]
 const run=(cmd,args,cwd=root)=>new Promise((resolve,reject)=>{const p=spawn(cmd,args,{cwd,env:childEnv,stdio:['ignore','pipe','pipe']});let out='';for(const s of[p.stdout,p.stderr])s.on('data',b=>{out+=b;if(out.length>64000000)p.kill()});p.on('error',()=>reject(new Error('P2_R1_PACKAGE_TOOL_UNAVAILABLE')));p.on('close',code=>code===0?resolve(out):reject(new Error('P2_R1_PACKAGE_TOOL_FAILED')))})
 const put=(n,value)=>{if(!ALLOW.includes(n)||payload[n])throw new Error('P2_R1_PACKAGE_NAME');const bytes=serialize(value),file=path.join(dir,n);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,bytes,{flag:'wx'});payload[n]=bytes},log=(n,input)=>{const x=sanitizedLogBytes(Buffer.from(input),root);put('LOGS/'+n+'.log',x.bytes);bindings.push({name:n,sourceSha256:x.sourceSha256,sanitizedSha256:x.sanitizedSha256,otherPathRedactions:x.otherPathRedactions})}
 for(const[n,x]of Object.entries(d.entries))put(n,x)
 put('README.md','# TRACE//ESCAPE — P2-R1\n\n'+d.status+'\n\nBounded no-network partial acceptance and anti-Cartesian remediation. '+d.partial.accepted.length+' exact P2 calls independently accepted in requested Lead order19–25; '+d.partial.held.length+' new supplier terminals permanently held as redundant subwindows. Formal total'+d.partial.index.length+', supplier-counted31, holds'+d.report.permanentlyHeldSupplierTerminals+', known credits37. Individual blockers'+d.partial.individualBlockers.length+'. Fourteen provider-receipt and charge outcomes remain indeterminate;21 never-started calls retired with rejected45-plan. No retry, reissue, replacement, credential, documentation or account request. Semantic concepts preserved in substance, not interface-frozen. NO_CREDIBLE_SCALE_PATH_YET. P3, LaneC, TE-IFACE-CORPUS and controller seam authority false. No game, title, Mission02, release or side-lane acceptance. Complete Lead notes and earlier continuity are in KT. Powered by Nansen API.\n\nExtract then run node VERIFY_DELIVERY.mjs to verify exact members, hashes, receipt/index/accounting and suppressed authorities. Git bundle restores exact candidate. Stop for independent Lead review; no external message sent.\n')
 put('DELIVERY_MANIFEST.json',{schemaVersion:'1.0.0',status:d.status,candidate,implementationSha256:implementation,executionContractSha256:CONTRACT_SHA,reviewedP2ArchiveSha256:ARCHIVE_SHA,partialLeadReceiptIdentity:d.partial.receipt.hash,acceptedPublicIndexIdentity:identity(d.partial.index),priorAcceptedPublicIndexIdentity:d.report.priorAcceptedPublicIndexIdentity,formalLeadAccepted:d.partial.index.length,newFormalLeadAccepted:d.partial.accepted.length,supplierCountedTerminals:31,permanentlyHeldSupplierTerminals:d.report.permanentlyHeldSupplierTerminals,knownCampaignCredits:37,unresolvedReservations:14,neverIssuedRetired:21,newNetworkRequests:0,newProviderRequests:0,newCredits:0,credentialAccess:false,privateMutation:false,externalLeadMessageSent:false,sourceFiles:83,scalePathStatus:'NO_CREDIBLE_SCALE_PATH_YET',rawProviderBodiesPackaged:false,privatePathsPackaged:false,assetLanePackaged:false,...OFF})
 put('SOURCE/ACTIVE_SOURCE_MANIFEST.sha256',fs.readFileSync(path.join(root,MANIFEST)));put('VERIFY_DELIVERY.mjs',verifier());put('EVIDENCE/BUGBOT_P2_R1_REVIEW_A.json',reviews[0]);put('EVIDENCE/BUGBOT_P2_R1_REVIEW_B.json',reviews[1]);put('EVIDENCE/REVIEW_FINDINGS_RESOLUTIONS.json',{schemaVersion:'1.0.0',unresolvedAcceptedP0P1:0,reviews,providerRequestsDuringReviewOrFixes:0,credentialAccess:false,privateMutation:false})
 for(const n of SUITES)log(n,logs[n]);log('exact-read-only-private-index-reconciliation',JSON.stringify({status:d.status==='BLOCKED_WITH_EVIDENCE'?'PARTIAL_INDIVIDUAL_RECOVERY_BLOCKED':'PASS_MAIN_READ_ONLY',ledgerSha256:d.report.ledgerSha256,ledgerBytes:d.report.ledgerBytes,acceptedIndexIdentity:identity(d.partial.index),formalAccepted:d.partial.index.length,all33RawMirrorsVerified:d.entries['EVIDENCE/PRIMARY_MIRROR_LEDGER_INTEGRITY.json'].all33ObservedRawPairsEqualAndHashVerified,currentSupportsReproduced:d.report.currentNewSupportsReproduced,held:d.report.permanentlyHeldSupplierTerminals,reservations:14,providerRequests:0,credentialAccess:false,privateMutation:false})+'\n')
 const bundle=bundlePath(temp),bundleOut=await run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD']),verified=await run('git',['bundle','verify',bundle]),clone=path.join(temp,'clone');await run('git',['clone','--quiet',bundle,clone]);if(identity(cut(clone))!==identity(candidate)||digest(clone)!==implementation)throw new Error('P2_R1_BUNDLE_CLONE_IDENTITY')
 log('bundle-clone-fsck',bundleOut+verified+await run('git',['fsck','--full','--strict'],clone)+'\nExact fresh clone and fsck exit0.\n');put('GIT/trace-escape-complete.bundle',fs.readFileSync(bundle));put('SOURCE_DIFF.patch',execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:root,env:childEnv,maxBuffer:256000000}))
 log('fresh-clone-current-tree-secret',await run('node',[path.join(root,'scripts/scan-prohibitions.mjs'),clone]));log('fresh-clone-history-secret',await run('node',['scripts/verify-git-secret-history.mjs'],clone));log('redacted-delivery-secret',await run('node',[path.join(root,'scripts/scan-prohibitions.mjs'),dir]))
 const scan=pathScan(payload);if(scan.status!=='PASS')throw new Error('P2_R1_PACKAGE_PATH_LEAK')
 put('EVIDENCE/VERIFICATION_SUMMARY.json',{...v,deliveryLogBindings:bindings,pathRedactionScan:scan,bundleFreshCloneExact:true,bundleFsck:'PASS',mainReadOnlyPrivateReplay:true,rawProviderBytesPackaged:false,currentGateExternalRequests:0,providerRequests:0,credentialAccess:false,privateMutation:false})
 const hashes=files(dir).map(f=>sha(fs.readFileSync(f))+'  '+path.relative(dir,f)).sort();put('MANIFEST.sha256',hashes.join('\n')+'\n')
 const names=files(dir).map(f=>path.relative(dir,f)).sort();if(identity(names)!==identity(ALLOW))throw new Error('P2_R1_EXACT_FINAL_MEMBER_SET')
 const before=Object.entries(d.entries).map(([n,x])=>[n,sha(serialize(x))]),check=()=>{if(identity(localGate(root))!==identity(v)||reviews.some((x,i)=>identity(reviewGate(root,i))!==identity(x))||identity(cut(root))!==identity(candidate)||digest(root)!==implementation)throw new Error('P2_R1_FINAL_CERTIFICATE_OR_SOURCE_CHANGED');assertAdmittedSuiteLogs(v,logs,n=>readEvidence(path.join(root,'artifacts/g6p-p2-r1/local'),n+'.log'))}
 check();for(const f of files(dir))fs.utimesSync(f,new Date('2000-01-01T00:00:00Z'),new Date('2000-01-01T00:00:00Z'))
 const zip=path.join(temp,'delivery.zip'),rebuilt=path.join(temp,'rebuilt.zip');await run('zip',['-X','-q',zip,...names],dir);await run('zip',['-X','-q',rebuilt,...names],dir);if(sha(fs.readFileSync(zip))!==sha(fs.readFileSync(rebuilt)))throw new Error('P2_R1_NONDETERMINISTIC_ARCHIVE')
 await run('unzip',['-t',zip]);const extracted=path.join(temp,'extracted');fs.mkdirSync(extracted);await run('unzip',['-q',zip,'-d',extracted]);await run('sha256sum',['-c','MANIFEST.sha256'],extracted);await run('node',['VERIFY_DELIVERY.mjs'],extracted)
 const final=derive(root);if(identity(Object.entries(final.entries).map(([n,x])=>[n,sha(serialize(x))]))!==identity(before))throw new Error('P2_R1_FINAL_READ_ONLY_EVIDENCE_CHANGED');check()
 const output=path.join(path.dirname(root),OUTPUT);fs.copyFileSync(zip,output,fs.constants.COPYFILE_EXCL);return {status:d.status,archive:output,sha256:sha(fs.readFileSync(output)),members:names.length,formalLeadAccepted:d.partial.index.length,newAccepted:d.partial.accepted.length,newHolds:d.partial.held.length,newNetworkRequests:0,scalePath:'NO_CREDIBLE_SCALE_PATH_YET',...OFF}
}
