import {identity,validateSchema} from '../nq5/schema.mjs'
import {seal,BASE,TREE,PARENT,ARCHIVE_SHA,CONTRACT_SHA,LEDGER_SHA,LEDGER_BYTES,SEMANTIC} from './authority.mjs'
import {dominance,DOMINATED} from '../nq5-p2/incremental.mjs'
export const OFF={AUTHORIZED_TO_ISSUE:false,P3_AUTHORIZED_TO_ISSUE:false,gameplayIntegrationAccepted:false,LaneC:false,TE_IFACE_CORPUS_FROZEN:false,controllerSeamCommit:false}
export function acceptedFacts(c){return c.sources.map(s=>({logicalId:s.logicalId,request:s.request,resultCount:s.normalized.resultCount,isLastPage:s.normalized.pagination?.is_last_page===true,formallyAccepted:true}))}
export function recoverCall(expected,c,r,{hold=false,facts=acceptedFacts(c)}={}){
 const p=r.projections.find(p=>p.request.logicalId===expected.logicalId),t=p?.terminal,row=p?.response,q=p?.request,n=p?.normalized
 if(!p||t.disposition!=='SUCCESS_COUNTED'||t.auditDisposition!=='PASS'||t.hash!==expected.terminalIdentity||row.httpStatus!==200||row.providerRequestId!==expected.providerRequestId||row.actualCredits!==1||row.quotedCredits!==1||row.headers['x-request-id']!==row.providerRequestId)throw new Error('P2_R1_EXACT_INDIVIDUAL_IMMUTABLE_CALL_NOT_RECOVERED')
 if(!hold&&(row.rawSha256!==expected.rawSha256||n.normalizedSha256!==expected.normalizedSha256||n.resultCount!==expected.resultCount))throw new Error('P2_R1_INDIVIDUAL_RAW_NORMALIZED_COUNT_MISMATCH')
 const sequence=t.publicRecord.qualification_sequence,publicCallId=t.publicRecord.public_call_id
 if(!Number.isSafeInteger(sequence)||sequence<22||sequence>31||publicCallId!=='NQ5-'+String(sequence).padStart(6,'0')||t.publicRecord.request_body_sha256!==identity(q.body)||t.publicRecord.response_sha256!==row.rawSha256||t.publicRecord.normalized_sha256!==n.normalizedSha256||t.publicRecord.result_count!==n.resultCount)throw new Error('P2_R1_SUPPLIER_PUBLIC_REQUEST_IDENTITY_MISMATCH')
 const old=hold?dominance(q,facts):null
 if(hold&&(n.resultCount!==0||!old||old.logicalId!==expected.priorAcceptedZeroLogicalId))throw new Error('P2_R1_HOLD_PRIOR_EVIDENCE_DOMINANCE_NOT_PROVEN')
 return {...expected,supplierSequence:sequence,publicCallId,immutableTerminalIdentity:t.hash,requestIdentity:identity(q),requestBodySha256:identity(q.body),requestWireBodySha256:q.wireBodySha256,rawSha256:row.rawSha256,normalizedSha256:n.normalizedSha256,resultCount:n.resultCount,knownCredits:row.actualCredits,sourcePublicRecordIdentity:identity(t.publicRecord),consumerExecutionIdentity:t.publicRecord.consumer_execution_identity,disposition:hold?'PERMANENTLY_LEAD_HELD':'FORMALLY_LEAD_ACCEPTED',holdReason:hold?DOMINATED:null,priorEvidenceDominance:hold?{logicalId:old.logicalId,resultCount:0,accepted:true,exactEndpointFilterPageMatch:true,encompassingWindow:old.request.body.date}:null,...OFF}
}
export function compilePartial(c,r,lead,priorArchive){
 const accepted=[],held=[],individualBlockers=[]
 for(const e of lead.acceptances){try{accepted.push(recoverCall(e,c,r))}catch(err){individualBlockers.push({logicalId:e.logicalId,requestedLeadAcceptanceOrder:e.leadAcceptanceOrder,status:'BLOCKED_WITH_EVIDENCE',reason:err.message,...OFF})}}
 for(const e of lead.holds){try{held.push(recoverCall(e,c,r,{hold:true}))}catch(err){individualBlockers.push({logicalId:e.logicalId,requestedDisposition:'PERMANENTLY_LEAD_HELD',status:'BLOCKED_WITH_EVIDENCE',reason:err.message,...OFF})}}
 const before=priorArchive.objects['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json']
 if(before.length!==18||identity(before)!==identity(c.index))throw new Error('P2_R1_OLD_EIGHTEEN_INDEX_MISMATCH')
 const oldHeld=[...c.state.terminals.values()].filter(t=>[2,3,4].includes(t.publicRecord?.qualification_sequence)).map(t=>({logicalId:t.logicalId,supplierSequence:t.publicRecord.qualification_sequence,publicCallId:t.publicRecord.public_call_id,immutableTerminalIdentity:t.hash,disposition:'HISTORICAL_PERMANENTLY_LEAD_HELD',privateTerminalUnchanged:true}))
 if(oldHeld.length!==3)throw new Error('P2_R1_THREE_HISTORICAL_HOLDS_NOT_RECOVERED')
 const receipt=seal({schemaVersion:'1.0.0',dispositionStates:lead.states,dispositionSource:'EXACT_USER_SUPPLIED_R1_HANDOFF_REQUESTED_WORKFLOW',reviewedArchiveSha256:ARCHIVE_SHA,reviewedCandidate:{commit:BASE,tree:TREE},reviewedDirectParent:PARENT,executionContractSha256:CONTRACT_SHA,historicalP2ExecutionContractSha256:c.receipt.executionContractSha256,campaignId:c.receipt.campaignId,ledgerSha256:LEDGER_SHA,ledgerBytes:LEDGER_BYTES,r1SourceManifestIdentity:c.r1Source.r1SourceManifestSha256,sourceManifestIdentity:priorArchive.objects['DELIVERY_MANIFEST.json'].sourceManifestSha256,historicalPlanIdentity:c.plans.plan.hash,historicalAuditIdentity:r.report.requestAuditIdentity,publicIndexBeforeIdentity:identity(before),semanticAbstractionIdentity:SEMANTIC,acceptances:accepted,newPermanentHolds:held,historicalPermanentHolds:oldHeld,individualBlockers,requestedFormalLeadTotal:25,formalLeadAcceptedBefore:18,newFormalLeadAccepted:accepted.length,formalLeadAcceptedAfter:18+accepted.length,supplierCountedTerminals:31,permanentlyHeldSupplierTerminals:oldHeld.length+held.length,knownCampaignCredits:37,privateHistoryUnchanged:true,independentPerCallDisposition:true,newProviderRequests:0,credentialAccess:false,accountRequests:0,externalDocumentationGets:0,...OFF})
 const added=accepted.map(a=>{const q=r.projections.find(p=>p.request.logicalId===a.logicalId).request;return {schema_version:'5.1.0',campaign_id:receipt.campaignId,authorization_id:before[0].authorization_id,public_call_id:a.publicCallId,qualification_sequence:a.supplierSequence,supplier_qualification_sequence:a.supplierSequence,tranche_id:'T1',endpoint_family:q.family,business_question:q.businessQuestion,purpose_code:q.purpose,consumer_ids:q.consumers,request_body_sha256:a.requestBodySha256,response_sha256:a.rawSha256,normalized_sha256:a.normalizedSha256,result_count:a.resultCount,route_disposition:'BOUNDED_ACTIVITY',evidence_grade:'CONTEXTUAL',temporal_class:q.kind==='HAYSTACK_BASELINE'?'BOUNDED_QUERY_AGGREGATE_CONTEXTUAL':'SERVER_FILTERED_UNZONED_CONTEXTUAL',coverage_scope:q.body.date.from+' through '+q.body.date.to+'; PAGE.1; '+a.claimBoundary,selection_lineage_summary:q.lineage,coverage_cell_ids:q.coverageCells,coverage_key:q.coverageKey,raw_payload_published:false,attribution:'Powered by Nansen API',investigative_question_id:q.questionId,question_lens:q.lens,lead_acceptance_status:'ACCEPTED',lead_acceptance_order:a.leadAcceptanceOrder,acceptance_role:a.role,lead_acceptance_receipt_identity:receipt.hash,claim_boundaries:[a.claimBoundary,'NO_EXACT_PROOF_IDENTITY_OWNERSHIP_INTENT_CAUSATION_COMPLETENESS_CHAIN_NEGATIVE_OR_FOREGROUND_GAMEPLAY','EXACT_EULER_TRUTH_SEPARATE'],gameplay_integration_accepted:false,frontier_authority_accepted:false,exact_proof_accepted:false}})
 const index=[...structuredClone(before),...added],schema=structuredClone(c.pubSchema);schema.minItems=index.length;schema.maxItems=index.length;schema.items.properties.acceptance_role={type:'string',enum:[...new Set(index.map(r=>r.acceptance_role).filter(x=>typeof x==='string'))]};schema.items.properties.temporal_class={type:'string',enum:[...new Set(index.map(r=>r.temporal_class).filter(x=>typeof x==='string'))]};schema.items.properties.purpose_code={enum:[...new Set(index.map(r=>r.purpose_code).filter(x=>typeof x==='string'))]};schema.items.properties.frontier_authority_accepted={const:false};schema.items.properties.exact_proof_accepted={const:false}
 if(identity(index.slice(0,18))!==identity(before)||new Set(index.map(x=>x.public_call_id)).size!==index.length||index.some(x=>[...oldHeld,...held].some(h=>h.publicCallId===x.public_call_id)))throw new Error('P2_R1_INDEX_IMMUTABLE_HELD_EXCLUSION')
 validateSchema('provider',index,schema)
 return {receipt,index,indexSchema:schema,accepted,held,individualBlockers,status:individualBlockers.length?'BLOCKED_WITH_EVIDENCE':'DELIVERED_PENDING_LEAD_REVIEW'}
}
