import fs from 'node:fs'
import path from 'node:path'
import { identity, sha, validateSchema } from '../nq5/schema.mjs'
import { parseExactJson, decimalLexeme } from '../nq5/exact-json.mjs'
import { admit, temporal } from '../nq5-b1-r3/compatibility.mjs'
import { strictTransfers, CAMPAIGN } from './semantics.mjs'
import { CONTRACT_SHA } from './authority.mjs'

// Evidence-only reproduction of the accepted supplier identity. Never returned
// to the executor or used to admit/count a request under the corrected rules.
function legacyProjection(exact,times){return exact.data.flatMap((tx,i)=>[...(tx.tokens_sent??[]),...(tx.tokens_received??[])].map(t=>({transaction_hash:tx.transaction_hash,from_address:t.from_address,to_address:t.to_address,token_address:t.token_address,amount:decimalLexeme(t.token_amount).replace(/^-/,''),evidence_grade:'CONTEXTUAL',temporal_class:times[i].classification,...(times[i].exactUtcFromAcceptedTruth?{accepted_exact_utc:times[i].exactUtcFromAcceptedTruth,accepted_exact_time_source:'ACCEPTED_EULER_TRUTH_HASH_JOIN'}:{})})))}
export function retention({semanticPass,stats,oldIdentity,newIdentity,oldCount,newCount,bindingsPass}){return semanticPass&&bindingsPass&&stats.uniqueAdmittedRows>0&&stats.incidentalRows===0&&stats.duplicateRows===0&&stats.zeroRows===0&&stats.negativeRows===0&&oldIdentity===newIdentity&&oldCount===newCount}
export function accounting(responses){const latest=Math.min(...responses.map(r=>r.remainingCredits).filter(Number.isSafeInteger)),known=responses.reduce((n,r)=>n+r.actualCredits,0),r3=responses.filter(r=>r.sequence>6).reduce((n,r)=>n+r.actualCredits,0);if(latest!==626632||known!==6||r3!==4)throw new Error('R31_BALANCE_ANCHOR_OR_CREDIT_DRIFT');return{schemaVersion:'1.0.0',historicalAccountAnchor:630027,afterOriginalB1Pair:627478,latestR3ResponseBalance:latest,totalAccountWideDecrease:630027-latest,cumulativeKnownCampaignCredits:known,totalUnattributedAccountWideChange:{value:630027-latest-known,classification:'UNATTRIBUTED_ACCOUNT_WIDE_CHANGE'},r3IntervalAccountWideDecrease:627478-latest,r3KnownCampaignCredits:r3,additionalUnattributedR3IntervalChange:{value:627478-latest-r3,classification:'UNATTRIBUTED_ACCOUNT_WIDE_CHANGE'},causeAssigned:false,accountRequestsInThisGate:0,protectedReserve:250,headroomAboveReserve:latest-250,evidenceSource:'IMMUTABLE_ACCEPTED_RESPONSE_CREDIT_HEADERS_NO_ACCOUNT_REQUEST'}}
export function revalidate(a,state,root){
 const c=a.context,perCall=[],privateProjections=[]
 for(const call of state.calls){const {request:q,start:s,response:r,terminal:t,audit:oldAudit,raw}=call,exact=parseExactJson(raw),times=exact.data.map(tx=>temporal(tx.block_timestamp,q,c.truth.times[tx.transaction_hash.toLowerCase()])),semantic=strictTransfers(exact,q,times),oldRows=legacyProjection(exact,times),oldIdentity=identity(oldRows),newAdmission=admit(c.bound,q,raw,r,t.publicRecord.qualification_sequence,c.profile,c.oldProfile,c.truth),oldRecord=t.publicRecord
  if(oldIdentity!==t.normalizedSha256||oldRows.length!==t.resultCount||identity(oldRecord)!==identity(a.objects['REPORTS/T1_B1_R3_RECONCILIATION_REPORT.json'].publicIndex.find(p=>p.public_call_id===oldRecord.public_call_id))||oldRecord.normalized_sha256!==oldIdentity||oldAudit.publicCallId!==oldRecord.public_call_id||oldAudit.qualificationSequence!==oldRecord.qualification_sequence)throw new Error('R31_OLD_IDENTITY_REPRODUCTION_MISMATCH')
  const support=retention({semanticPass:newAdmission.safelyAdmissible,stats:semantic.stats,oldIdentity,newIdentity:newAdmission.normalizedSha256??null,oldCount:t.resultCount,newCount:newAdmission.resultCount,bindingsPass:true})
  perCall.push({logicalId:q.logicalId,requestedSubject:q.body.address,requestBodySha256:identity(q.body),providerRequestId:r.providerRequestId,rawBytes:raw.length,primarySha256:sha(raw),mirrorSha256:sha(raw),bytesEqual:true,start:{sequence:s.sequence,identity:s.hash},response:{sequence:r.sequence,identity:r.hash},terminal:{sequence:t.sequence,identity:t.hash,disposition:t.disposition,unchanged:true},compatibilityProfileIdentity:c.profile.hash,stats:semantic.stats,oldNormalizedIdentity:t.normalizedSha256,reproducedOldNormalizedIdentity:oldIdentity,newNormalizedIdentity:newAdmission.normalizedSha256??null,oldResultCount:t.resultCount,newResultCount:newAdmission.resultCount,normalizedIdentityEqual:t.normalizedSha256===newAdmission.normalizedSha256,resultCountEqual:t.resultCount===newAdmission.resultCount,oldValidationStages:t.validationStages,validationStages:Object.fromEntries(['json','schema','pagination','contextualTemporal','normalization','projection','publicSchema'].map(k=>[k,newAdmission.stages[k]??{status:'NOT_RUN'}])),firstFailedStage:newAdmission.firstFailedStage,semanticCode:semantic.code,existingCountedTerminalSemanticallySupportable:support,oldPublicCallId:oldRecord.public_call_id,oldPublicRecordIdentity:identity(oldRecord),oldCampaignAlias:oldRecord.campaign_id,exactCampaignId:CAMPAIGN,rawBodyIncluded:false,privatePathsIncluded:false})
  privateProjections.push({logicalId:q.logicalId,request:q,admission:newAdmission,semantic,pagination:exact.pagination})
 }
 const allPass=perCall.length===4&&perCall.every(r=>r.existingCountedTerminalSemanticallySupportable),index=allPass?privateProjections.map(p=>p.admission.publicRecord):[],indexSchema=JSON.parse(fs.readFileSync(path.join(root,'schemas/NQ5_PUBLIC_CALL_INDEX.schema.json')));validateSchema('provider',index,indexSchema)
 const indexBytes=Buffer.from(JSON.stringify(index,null,2)+'\n'),oldIndex=a.objects['REPORTS/T1_B1_R3_RECONCILIATION_REPORT.json'].publicIndex;if(identity(oldIndex)!=='5966cef5c65aeac80eba499546a0de871050fc6ff91bd0bbce8fbc4b79597948')throw new Error('R31_OLD_PUBLIC_INDEX_IDENTITY')
 for(const row of perCall){row.oldPublicIndexIdentity=identity(oldIndex);row.correctedPublicIndexIdentity=identity(index);row.publicRowPublished=allPass;row.campaignBindingDisposition=allPass?'EXACT_FULL_CAMPAIGN_CORRECTED':'OLD_GENERIC_ALIAS_IMMUTABLE_CORRECTED_PUBLICATION_WITHHELD'}
 const crosswalk={schemaVersion:'1.0.0',status:allPass?'CORRECTED_EXACT_CAMPAIGN_INDEX_DERIVED':'WITHHELD_SEMANTIC_GATE_FAILED_EMPTY_INDEX',oldPublicIndexIdentity:identity(oldIndex),correctedPublicIndexIdentity:identity(index),correctedPublicIndexFileSha256:sha(indexBytes),rows:perCall.map(r=>({logicalId:r.logicalId,terminalSequence:r.terminal.sequence,terminalIdentity:r.terminal.identity,providerRequestId:r.providerRequestId,rawSha256:r.primarySha256,qualificationSequence:oldIndex.find(p=>p.public_call_id===r.oldPublicCallId).qualification_sequence,oldPublicCallId:r.oldPublicCallId,oldPublicRecordIdentity:r.oldPublicRecordIdentity,oldGenericAlias:r.oldCampaignAlias,exactCampaignId:CAMPAIGN,correctedPublicRowIdentity:allPass?identity(index.find(p=>p.public_call_id===r.oldPublicCallId)):null,published:allPass,reason:allPass?'EXACT_CAMPAIGN_BINDING_CORRECTED_WITHOUT_PRIVATE_MUTATION':'ALL_FOUR_RETENTION_REQUIRED_SEMANTIC_HOLD'}))}
 const acceptance={schemaVersion:'1.0.0',status:allPass?'SEMANTIC_RETENTION_PASS_PENDING_LEAD_REVIEW':'SEMANTIC_RETENTION_FAILED',semanticContractSha256:CONTRACT_SHA,campaignId:CAMPAIGN,supplierCountedTerminals:4,semanticallySupportableTerminals:perCall.filter(r=>r.existingCountedTerminalSemanticallySupportable).length,allFourRetentionPass:allPass,leadAcceptedCount:0,leadAcceptanceClaimed:false,privateTerminalsMutated:false,rawDataMutated:false,newProviderAttempts:0,newCredits:0,batch2FreezeAllowed:allPass,perCallEvidenceIdentity:identity(perCall),correctedPublicIndexIdentity:identity(index),scope:'CLIENT_SEMANTIC_SUPPORT_IS_NOT_LEAD_ACCEPTANCE'}
 const audit=structuredClone(a.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json']);audit.r3r1SemanticReview={campaignId:CAMPAIGN,allFourRetentionPass:allPass,leadAcceptedCount:0,perCallEvidenceIdentity:identity(perCall),supplierTerminalRecordsUnchanged:true};for(const r of audit.records){const check=perCall.find(p=>p.logicalId===r.logicalId);if(check)r.r3r1CountHold={supplierTerminalDisposition:'SUCCESS_COUNTED',semanticallySupportable:check.existingCountedTerminalSemanticallySupportable,leadAccepted:false,qualificationValueDisposition:'HELD_PENDING_LEAD_SEMANTIC_REVIEW'}}validateSchema('provider',audit,JSON.parse(fs.readFileSync(path.join(root,'schemas/NANSEN_API_REQUEST_AUDIT.schema.json'))))
 const correction=allPass?null:{schemaVersion:'1.0.0',proposalOnly:true,AUTHORIZED_TO_MUTATE_PRIVATE_STATE:false,AUTHORIZED_TO_ISSUE:false,campaignId:CAMPAIGN,immutableLedgerSha256:state.privateHashes['qualification.jsonl'],supplierCountsRemainInLedger:4,leadAcceptedCount:0,allFourRetentionRequired:true,rows:perCall.map(r=>({logicalId:r.logicalId,immutableTerminalIdentity:r.terminal.identity,immutableQualificationSequence:oldIndex.find(p=>p.public_call_id===r.oldPublicCallId).qualification_sequence,semanticallySupportable:r.existingCountedTerminalSemanticallySupportable,proposedAnnotation:r.existingCountedTerminalSemanticallySupportable?'SUPPORTABLE_BUT_HELD_BY_ALL_FOUR_GATE':'QUALIFICATION_COUNT_RETENTION_UNSUPPORTED',reason:r.semanticCode,oldNormalizedIdentity:r.oldNormalizedIdentity,recomputedNormalizedIdentity:r.newNormalizedIdentity,oldResultCount:r.oldResultCount,recomputedResultCount:r.newResultCount,privateRewriteProposed:false})),nextStep:'LEAD_DISPOSITION_REQUIRED_NO_REISSUE_RETRY_REPLACEMENT_OR_LEDGER_REPAIR'}
 return {allPass,perCall,privateProjections,acceptance,index,indexBytes,crosswalk,audit,correction,balance:accounting([...state.responses.values()])}
}
