import { identity } from '../nq5/schema.mjs'
import { logicalRequest } from '../nq5/planner.mjs'
import { validAddress } from './semantics.mjs'
import { seal } from './authority.mjs'

const ZERO='0x'+'0'.repeat(40),DAI='0x6b175474e89094c44da98b954eedeac495271d0f'
export function frontier(a,state,result){
 const c=a.context,batch=c.frontierBatch??2,pool=new Map(),tokenContracts=new Set([DAI,...result.privateProjections.flatMap(p=>p.semantic.tokenContracts)]),issued=new Set([...state.starts.values()].map(s=>c.bound.plan.requests.find(r=>r.logicalId===s.logicalId)).filter(q=>q.family==='profiler/address/transactions').map(q=>identity({path:q.path,body:q.body}))),subjectIssued=new Set([...state.starts.values()].map(s=>c.bound.plan.requests.find(r=>r.logicalId===s.logicalId)).filter(q=>q.family==='profiler/address/transactions').map(q=>q.body.address.toLowerCase()))
 const add=(address,page,kind,priority,lineage,logicalIds=[],hashes=[],positive=true)=>{const subject=typeof address==='string'?address.toLowerCase():address,key=String(subject)+'/'+page;let row=pool.get(key);if(!row){row={subject,page,sources:[],logicalIds:new Set(),transactionHashes:new Set(),priority,positiveLineage:false};pool.set(key,row)}row.priority=Math.min(row.priority,priority);row.sources.push({kind,lineage});logicalIds.forEach(id=>row.logicalIds.add(id));hashes.forEach(h=>row.transactionHashes.add(h.toLowerCase()));row.positiveLineage||=positive}
 for(const address of c.truth.seedAddresses)add(address,1,subjectIssued.has(address)?'ACCEPTED_SEED_ALREADY_ISSUED':'UNUSED_ACCEPTED_EULER_SEED',1,['ACCEPTED_EULER_TRUTH.'+c.truth.sha256])
 const opposite=new Map()
 for(const p of result.privateProjections){const subject=p.request.body.address.toLowerCase();for(const row of p.semantic.subjectCandidates){const from=row.from_address.toLowerCase(),to=row.to_address.toLowerCase(),other=from===subject?to:from,positive=row.amountClass==='POSITIVE',lineage=['DURABLE_SUBJECT_TRANSFER.'+p.logicalId,'TRANSFER_IDENTITY.'+identity([row.transaction_hash.toLowerCase(),from,to,row.token_address.toLowerCase(),row.amount])];add(other,1,'OPPOSITE_SIDE_SUBJECT_COUNTERPARTY',2,lineage,[p.logicalId],[row.transaction_hash],positive);if(c.truth.times[row.transaction_hash.toLowerCase()])add(other,1,'ACCEPTED_EXACT_EULER_HASH_JOIN',3,[...lineage,'ACCEPTED_EXACT_HASH.'+row.transaction_hash.toLowerCase()],[p.logicalId],[row.transaction_hash],positive);if(positive&&other!==subject){const ids=opposite.get(other)??new Set();ids.add(p.logicalId);opposite.set(other,ids)}}
  if(p.pagination.is_last_page===false)add(subject,2,'EXACT_DURABLE_NONLAST_PAGE',5,['DURABLE_PAGINATION.'+p.logicalId],[p.logicalId],[],p.admission.safelyAdmissible)
 }
 for(const[address,ids]of opposite)if(ids.size>1)add(address,1,'INDEPENDENTLY_REPEATED_ACROSS_SUBJECT_RESPONSES',4,[...ids].sort().map(id=>'DURABLE_RESPONSE.'+id),[...ids],[],true)
 const rows=[...pool.values()].sort((x,y)=>x.priority-y.priority||String(x.subject).localeCompare(String(y.subject))||x.page-y.page).map(row=>{
  const original=row.page===2?result.privateProjections.find(p=>p.request.body.address.toLowerCase()===row.subject)?.request:c.plans.plan.requests[0],body=structuredClone(original.body);body.address=row.subject;body.pagination.page=row.page
  const equivalenceIdentity=identity({path:original.path,body}),alreadyEquivalent=issued.has(equivalenceIdentity),selfOnly=row.sources.every(s=>s.kind==='OPPOSITE_SIDE_SUBJECT_COUNTERPARTY'||s.kind==='ACCEPTED_EXACT_EULER_HASH_JOIN')&&row.logicalIds.size>0&&[...row.logicalIds].every(id=>result.privateProjections.find(p=>p.logicalId===id).request.body.address.toLowerCase()===row.subject)
  let rejection=!validAddress(row.subject)?'INVALID_ADDRESS':row.subject===ZERO?'ZERO_ADDRESS':tokenContracts.has(row.subject)?'TOKEN_CONTRACT_EXCLUDED':selfOnly?'SELF_ONLY_COUNTERPARTY':alreadyEquivalent?'ALREADY_ISSUED_EQUIVALENT_CANONICAL_REQUEST':!row.positiveLineage?'NONPOSITIVE_ONLY_UNSUPPORTED_LINEAGE':!result.allPass?'SEMANTIC_ALL_FOUR_RETENTION_GATE_FAILED':null
  const safe=validAddress(row.subject)&&row.subject!==ZERO&&!tokenContracts.has(row.subject)&&row.positiveLineage
  const question='QUESTION.T1.B'+batch+'.ACTIVITY.INCIDENT.'+row.subject,coverageKey={subject_id:row.subject,time_window_id:body.date.from+'/'+body.date.to,question_lens:'ACTIVITY',page_or_partition_id:'PAGE.'+row.page},consumers=['TEST.T1.B'+batch+'.SUBJECT_ACTIVITY','PROVENANCE.T1.B'+batch+'.SUBJECT_LINEAGE'],marginalUtility=row.sources.some(s=>s.kind==='UNUSED_ACCEPTED_EULER_SEED')?'Test unqueried accepted Euler seed activity in the unchanged incident window; Main Trigger included.':row.page===2?'Continue exact durable non-last page for the same bounded activity question.':'Test opposite-side route-candidate activity from unique subject-involved transfers; contextual discovery, not exact proof or completeness.'
  const request={family:original.family,path:original.path,method:original.method,contractHash:original.contractHash,publicProjectionPolicy:structuredClone(original.publicProjectionPolicy),frontierProof:{kind:row.sources.some(s=>s.kind==='UNUSED_ACCEPTED_EULER_SEED'||s.kind==='ACCEPTED_SEED_ALREADY_ISSUED')?'ACCEPTED_PUBLIC_SAFE_SEED':'DURABLE_SUBJECT_COUNTERPARTY',subjectAddress:row.subject,acceptedTruthSha256:c.truth.sha256,supportingLogicalIds:[...row.logicalIds].sort(),supportingTransactionHashes:[...row.transactionHashes].sort()},candidateRole:row.sources.some(s=>s.kind==='UNUSED_ACCEPTED_EULER_SEED')?'UNUSED_ACCEPTED_SEED_ACTIVITY':'DURABLE_COUNTERPARTY_ACTIVITY',body,sequence:1,questionId:question,lens:'ACTIVITY',purpose:row.page===2?'PAGINATION_COMPLETENESS':'ANCHOR_ACTIVITY_PAGE',businessQuestion:'Which subject-involved contextual activity facts for '+row.subject+' in the exact accepted incident window add route-candidate coverage?',consumers,coverageKey,coverageCells:['CELL.'+identity(coverageKey)],lineage:row.sources.flatMap(s=>s.lineage).sort(),novelty:marginalUtility,partition:{page:row.page,exactDurableNextPage:row.page===2},stopRule:'Stop on any schema/privacy/subject/nonpositive/raw/identity/accounting/reserve drift or marginal-utility saturation. No exact proof, negative evidence, completeness or later-page inference.',expectedCredits:1,worstCaseCredits:3};request.logicalId=logicalRequest(request)
  return {candidateIdentity:identity({subject:row.subject,page:row.page,sources:row.sources}),subjectAddress:row.subject,page:row.page,sourceKinds:[...new Set(row.sources.map(s=>s.kind))],sourceLineage:row.sources,supportingLogicalIds:[...row.logicalIds].sort(),supportingTransactionHashes:[...row.transactionHashes].sort(),publicSafe:safe,publicSafetyReason:safe?'ACCEPTED_PUBLIC_SAFE_SEED_OR_ALLOWLISTED_SUBJECT_TRANSFER_ADDRESS_NOT_LABEL':'INVALID_ZERO_TOKEN_OR_NONPOSITIVE_ONLY_LINEAGE',questionId:question,questionLens:'ACTIVITY',purpose:request.purpose,coverageKey,coverageCell:request.coverageCells[0],namedConsumers:consumers,gameplayConsumerAdmissionClaimed:false,expectedCredits:1,worstCaseCredits:3,stopRule:request.stopRule,marginalUtility,equivalenceIdentity,alreadyIssuedEquivalent:alreadyEquivalent,duplicateSourcesMerged:row.sources.length-1,admitted:!rejection,rejectionCode:rejection,request}
 })
 // One highest-priority useful candidate is the smallest meaningful batch.
 // Every other evaluated candidate remains explicit; never pad toward a count.
 let selected=false;for(const r of rows)if(r.admitted){if(selected){r.admitted=false;r.rejectionCode='DEFERRED_SMALLEST_MEANINGFUL_BATCH'}else selected=true}
 const publicRows=rows.map(({request,...row})=>row),matrix={schemaVersion:'1.0.0',semanticRetentionPassed:result.allPass,allAcceptedSeedAddressesEvaluated:c.truth.seedAddresses.length,acceptedSeedAddresses:[...c.truth.seedAddresses].sort(),durableCallsEvaluated:result.privateProjections.length,rawIncidentalCandidatesUsed:0,candidateCount:rows.length,admittedCount:rows.filter(r=>r.admitted).length,mainTriggerEvaluated:rows.some(r=>r.subjectAddress==='0xb2698c2d99ad2c302a95a8db26b08d17a77cedd4'),rows:publicRows,exactTruthSha256:c.truth.sha256,completeEnumerationNotAnEmptyRouteClaim:true}
 const requests=rows.filter(r=>r.admitted).map(r=>r.request);if(requests.length>64)throw new Error('R31_FRONTIER_MAX64')
 const policy=seal({schemaVersion:'1.0.0',maximumRequests:64,minimumRequests:0,candidateOnly:true,AUTHORIZED_TO_ISSUE:false,family:'profiler/address/transactions',chain:'ethereum',sourcePriority:['UNUSED_ACCEPTED_SEEDS','OPPOSITE_SUBJECT_COUNTERPARTIES','ACCEPTED_EXACT_HASH_JOINS','INDEPENDENT_REPEATS','EXACT_NONLAST_PAGINATION'],noFixedPageCeiling:true,noMicroWindows:true,noEquivalentRequests:true,noCountPadding:true,labelsExcluded:true,heldFamiliesExcluded:true,allFourSemanticRetentionRequired:true,candidateMatrixIdentity:identity(matrix)})
 const plan=result.allPass&&requests.length?seal({schemaVersion:'1.0.0',candidateOnly:true,AUTHORIZED_TO_ISSUE:false,requests,expectedCredits:requests.length,worstCaseCredits:requests.length*3,frontierPolicyIdentity:policy.hash,candidateMatrixIdentity:identity(matrix),acceptedR3ArchiveSha256:a.archiveSha256,compatibilityProfileIdentity:c.profile.hash,semanticAcceptanceIdentity:identity(result.acceptance)}):null,reserve=plan?seal({schemaVersion:'1.0.0',planIdentity:plan.hash,balanceAnchor:626632,protectedReserve:250,expectedCredits:plan.expectedCredits,worstCaseCredits:plan.worstCaseCredits,remainingAfterWorstCase:626632-plan.worstCaseCredits,reservePass:626632-plan.worstCaseCredits>=250,AUTHORIZED_TO_ISSUE:false}):null
 return {matrix,plan,reserve,policy:plan?policy:null,report:{schemaVersion:'1.0.0',status:!result.allPass?'BLOCKED_SEMANTIC_COUNT_RETENTION':plan?'MEANINGFUL_CANDIDATE_FROZEN_NOT_AUTHORIZED':'BLOCKED_ROUTE_EXHAUSTED',completeCandidateMatrixIdentity:identity(matrix),candidateCount:rows.length,proposedRequests:plan?.requests.length??0,batch2PlanGenerated:!!plan,nextRequestsIssued:0,AUTHORIZED_TO_ISSUE:false,mainTriggerDisposition:publicRows.find(r=>r.subjectAddress==='0xb2698c2d99ad2c302a95a8db26b08d17a77cedd4'),routeExhaustionClaimed:result.allPass&&!plan}}
}
