import { identity } from '../nq5/schema.mjs'
import { IDS, AUTH, CONTRACT_SHA, seal } from './authority.mjs'
import { claimMatrix } from './evidence.mjs'

// Explicit evidence failure, never a reconciliation success or live capability.
// Counters are zero only with direct pre-issue control-flow proof; otherwise null.
export function blockedReports(c,blocker,{envelope=null,docs=null,replay=null}={}){
 const knownNoIssue=blocker.knownNoNewProviderActivity===true,n=knownNoIssue?0:null
 const report={schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',authorizationId:AUTH,executionContractSha256:CONTRACT_SHA,compatibilityProfileIdentity:c.profile.hash,planIdentity:c.plans.plan.hash,envelopeIdentity:envelope?.hash??null,blocker,clean:false,newAttempts:n,newProvider2xx:n,newCounted:n,newKnownActualCredits:n,cumulativeAttempts:knownNoIssue?2:null,cumulativeCounted:knownNoIssue?0:null,cumulativeKnownActualCredits:knownNoIssue?2:null,unresolvedReservations:knownNoIssue?0:null,unresolvedTerminals:knownNoIssue?0:null,ledgerSha256:null,ledgerBytes:null,publicIndexIdentity:null,credentialResolvedAtRuntime:blocker.credentialResolvedAtRuntime??null,unauthenticatedDocumentationGets:docs?.unauthenticatedDocumentationGets??blocker.documentationGetsKnown??null,authenticatedNansenProviderRequests:n,accountRequests:0,browserRuntimeRequests:0,historicalCalls:0,nextFrontierCalls:0,qualificationFloorClaimed:false,gameplayIntegrationClaimed:false,observedDriftNotice:c.profile.observedDriftNotice,privateStateRepaired:false,durableStateAdmission:'NOT_ESTABLISHED_FAIL_CLOSED',auditCompleteness:'ACCEPTED_R2_HISTORICAL_SNAPSHOT_ONLY_NEW_STATE_NOT_ASSERTED'}
 const safeEnvelope=envelope??seal({schemaVersion:'1.0.0',authorizationId:AUTH,executionContractSha256:CONTRACT_SHA,planIdentity:c.plans.plan.hash,compatibilityProfileIdentity:c.profile.hash,executionOrder:IDS,AUTHORIZED_TO_ISSUE:false,liveAdmitted:false,blocker})
 const entries={'CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json':c.profile,'EXECUTION/T1_B1_R3_RESUME_ENVELOPE.json':safeEnvelope,'PLANS/T1_B1_R3_TRANSACTION_ONLY_PLAN.json':c.plans.plan,'PLANS/T1_B1_R3_RESERVE_PLAN.json':c.plans.reserve,'REPORTS/T1_B1_R3_EXECUTION_REPORT.json':report,'REPORTS/T1_B1_R3_RECONCILIATION_REPORT.json':report,'REPORTS/T1_B1_R3_UTILITY_REPORT.json':{schemaVersion:'1.0.0',qualificationValue:'UNVERIFIED_NOT_CLAIMED',engineeringValue:'FAIL_CLOSED_BLOCKER_EVIDENCE',gameplayConsumerValue:'NO_INTEGRATION_CLAIM',documentationProvenanceValue:'ACCEPTED_R2_PINNED_BYTES_AND_AVAILABLE_R3_DOCS',newRequestUtility:null},'REPORTS/T1_CAMPAIGN_STATE_REDACTED.json':{...report,campaignId:c.bound.envelope.campaignId,originalRequestCount:15,historicalUnissuedHeld:9,originalConsumedNoncountedAtAcceptedR2:2,remainingLiveAuthority:0,originalUnattributedAccountWideChange:2547},'SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json':c.auditSchema,'EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':{...c.accepted.audit,auditScope:'HISTORICAL_ACCEPTED_R2_ONLY_NEW_STATE_UNVERIFIED'},'EVIDENCE/PRESERVED_TRANSACTION_COMPATIBILITY_REPLAY.json':replay??{schemaVersion:'1.0.0',status:'NOT_VERIFIED',rawOpened:false,publicCallId:null,retroactiveQualificationCounted:false,blocker},'EVIDENCE/COMPATIBILITY_CLAIM_BOUNDARY_MATRIX.json':claimMatrix,'EVIDENCE/LIVE_REQUEST_IDENTITY_MATRIX.json':{schemaVersion:'1.0.0',rows:c.plans.plan.requests.map(r=>({logicalId:r.logicalId,originalRowIdentity:identity(r),bodyHash:identity(r.body),question:r.questionId,lens:r.lens,purpose:r.purpose,consumers:r.consumers,coverageKey:r.coverageKey,providerActivity:n}))},'EVIDENCE/ATTEMPT_CREDIT_COUNT_AND_PROVIDER_ID_RECONCILIATION.json':{...report,priorProviderIdLimitation:'NOT_CAPTURED_BY_B1_TRANSPORT_V1',newProviderRequestIds:null},'EVIDENCE/PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json':{...report,publicIndex:null},'OFFICIAL_DOCS/INDEX.json':docs??{schemaVersion:'1.0.0',status:'NOT_RETRIEVED_OR_NOT_VERIFIED',snapshots:[],unauthenticatedDocumentationGets:report.unauthenticatedDocumentationGets,authenticatedNansenProviderRequests:n,accountRequests:0,browserRuntimeRequests:0}}
 return {entries,status:report.status,readiness:report,proof:{report},frontier:null}
}
