import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import { identity, sha, validateSchema } from '../nq5/schema.mjs'
import { parseExactJson } from '../nq5/exact-json.mjs'
import { strictTransfers, assertCampaignRecord } from '../nq5-b1-r3-r1/semantics.mjs'
import { proposalBound } from '../nq5-b1-r2/replay.mjs'
import { AUTH as PUBLIC_AUTH } from '../nq5/planner.mjs'
import { AUTH, BASE, IDS, CONTRACT_SHA, PINS, seal } from './authority.mjs'

export const TEMPORAL='NANSEN_SERVER_FILTERED_UNZONED_BLOCK_TIME_CONTEXTUAL'
export const DRIFT='Provider returned optional price_usd/value_usd nulls contrary to captured OpenAPI; TRACE//ESCAPE omitted optional enrichment rather than inventing values. Lead-owned client compatibility, not official schema or timezone admission.'
export const TRUTH='public/scenarios/euler-2023-false-exit/evidence-graph.json'
export function acceptedTruth(root){const bytes=fs.readFileSync(path.join(root,TRUTH)),old=execFileSync('git',['show',BASE+':'+TRUTH],{cwd:root});if(!bytes.equals(old))throw new Error('R3_ACCEPTED_TRUTH_CHANGED');const graph=JSON.parse(bytes),times={};if(graph.cutoffUtc!=='2023-03-13T12:15:00Z')throw new Error('R3_TRUTH_CUTOFF');for(const e of graph.events){if(!/^0x[0-9a-f]{64}$/i.test(e.transactionHash)||!utc(e.observedAtUtc))throw new Error('R3_TRUTH_EVENT');const k=e.transactionHash.toLowerCase();if(times[k]&&times[k]!==e.observedAtUtc)throw new Error('R3_TRUTH_TIME_CONFLICT');times[k]=e.observedAtUtc}return {sha256:sha(bytes),times,seedAddresses:graph.entities.filter(e=>e.address).map(e=>e.address.toLowerCase())}}
export function profile(bound,old,truth){
 if(old.hash!==PINS['CONTRACTS/ADDRESS_TRANSACTIONS_NULL_COMPATIBILITY_PROFILE.json'][1]||old.clarificationSha256!=='e190c366119b7493a7ce68af505d797fb2aba5a2994291bfe32f765fac4b8597')throw new Error('R3_EXACT_R2_PROFILE_REQUIRED')
 const derived=proposalBound(bound,old).admission.contracts.find(c=>c.family===old.family)
 return seal({schemaVersion:'1.0.0',authorizationId:AUTH,executionContractSha256:CONTRACT_SHA,scope:{family:old.family,path:'/api/v1/profiler/address/transactions',method:'POST',chain:'ethereum'},leadDisposition:'OBSERVED_PROVIDER_TRANSACTION_COMPATIBILITY_LEAD_ADMITTED',officialAdmission:false,publishedRequestSchemaIdentity:old.requestSchemaIdentity,publishedResponseSchemaIdentity:old.responseSchemaIdentity,officialEndpointSha256:old.endpointSha256,r2NegativeClarificationSha256:old.clarificationSha256,r2ProfileIdentity:old.hash,compatibilitySchema:derived.responseSchema,compatibilitySchemaIdentity:identity(derived.responseSchema),affectedNullableFields:old.affectedFields,nullMeans:'UNAVAILABLE_OR_UNKNOWN_NOT_ZERO',enrichmentOmitted:true,imputation:false,labelsStripped:true,unknownFieldsRejected:true,rawImmutable:true,temporalClass:TEMPORAL,timezoneEstablished:false,negativeEvidence:false,exactProofSlot:false,cutoffCompleteness:false,causation:false,acceptedTruthSha256:truth.sha256,observedDriftNotice:DRIFT})
}

const hash=v=>typeof v==='string'&&/^0x[0-9a-f]{64}$/i.test(v)
function components(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$/.test(v))return false;const [y,m,d,h,n,s]=v.split(/[-T:]/).map(Number);const date=new Date(Date.UTC(y,m-1,d,h,n,s));return y>=1000&&date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d&&h<24&&n<60&&s<60}
export const utc=v=>typeof v==='string'&&v.endsWith('Z')&&components(v.slice(0,-1))
export function temporal(time,request,truth){
 if(!utc(request.body.date.from)||!utc(request.body.date.to)||request.body.date.from>request.body.date.to||request.body.date.to>'2023-03-13T12:15:00Z')throw new Error('R3_EXPLICIT_UTC_REQUEST_BOUNDS_REQUIRED')
 const nominal=utc(time)?time.slice(0,-1):components(time)?time:null
 if(!nominal||nominal<request.body.date.from.slice(0,-1)||nominal>request.body.date.to.slice(0,-1)||nominal>'2023-03-13T12:15:00')throw new Error('R3_CONTEXTUAL_TIME_OUT_OF_BOUNDS_OR_MALFORMED')
 if(truth&&nominal!==truth.slice(0,-1))throw new Error('R3_ACCEPTED_EXACT_HASH_TIME_CONFLICT')
 return {classification:utc(time)?'EXPLICIT_UTC_RESPONSE_WITHIN_REQUEST':TEMPORAL,exactUtcFromAcceptedTruth:truth??null,timezoneInferred:false}
}
const normalizedSchema={type:'array',items:{type:'object',additionalProperties:false,required:['transaction_hash','from_address','to_address','token_address','amount','evidence_grade','temporal_class'],properties:{transaction_hash:{type:'string',pattern:'^0x[0-9a-fA-F]{64}$'},from_address:{type:'string',pattern:'^0x[0-9a-fA-F]{40}$'},to_address:{type:'string',pattern:'^0x[0-9a-fA-F]{40}$'},token_address:{type:'string',pattern:'^0x[0-9a-fA-F]{40}$'},amount:{type:'string',pattern:'^(0|[1-9][0-9]*)([.][0-9]+)?([eE][+-]?[0-9]+)?$'},evidence_grade:{const:'CONTEXTUAL'},temporal_class:{enum:[TEMPORAL,'EXPLICIT_UTC_RESPONSE_WITHIN_REQUEST']},accepted_exact_utc:{type:'string',format:'date-time'},accepted_exact_time_source:{const:'ACCEPTED_EULER_TRUTH_HASH_JOIN'}}}}
export function admit(bound,request,raw,row,sequence,p,old,truth,{replayOnly=false}={}){
 if(identity(p)!==identity(profile(bound,old,truth))||p.acceptedTruthSha256!==truth.sha256)throw new Error('R3_PROFILE_DRIFT')
 if(!bound.plan.requests.some(r=>identity(r)===identity(request))||request.family!==p.scope.family||request.method!==p.scope.method||request.path!==p.scope.path||request.body.chain!=='ethereum'||(!replayOnly&&!IDS.includes(request.logicalId)))throw new Error('R3_EXACT_TRANSACTION_REQUEST_REQUIRED')
 const stages={},fail=(stage,code)=>({safelyAdmissible:false,firstFailedStage:stage,stages:{...stages,[stage]:{status:'FAIL',code}},publicRecord:null,normalizedRecords:[],resultCount:0})
 let response,exact;try{if(!Buffer.isBuffer(raw)||sha(raw)!==row.rawSha256||raw.length!==row.rawBytes)throw 0;exact=parseExactJson(raw);response=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(raw));stages.json={status:'PASS'}}catch{return fail('json','RAW_HASH_SIZE_UTF8_OR_DUPLICATE_JSON')}
 try{validateSchema('provider',response,p.compatibilitySchema);stages.schema={status:'PASS',schemaIdentity:p.compatibilitySchemaIdentity}}catch{return fail('schema','EXACT_NARROW_COMPATIBILITY_REJECTED')}
 try{const q=response.pagination;if(q.page!==request.body.pagination.page||q.per_page!==request.body.pagination.per_page||q.page!==1||typeof q.is_last_page!=='boolean'||response.data.length>q.per_page||!q.is_last_page&&!response.data.length)throw 0;stages.pagination={status:'PASS'}}catch{return fail('pagination','EXACT_FROZEN_PAGE_METADATA_REQUIRED')}
 const times=[];try{const seen=new Map();for(const r of response.data){if(!hash(r.transaction_hash)||r.chain!=='ethereum')throw 0;const t=temporal(r.block_timestamp,request,truth.times[r.transaction_hash.toLowerCase()]);const k=r.transaction_hash.toLowerCase();if(seen.has(k)&&seen.get(k)!==r.block_timestamp)throw 0;seen.set(k,r.block_timestamp);times.push(t)}stages.contextualTemporal={status:'PASS',classification:TEMPORAL,timezoneEstablished:false,acceptedExactHashJoins:times.filter(t=>t.exactUtcFromAcceptedTruth).length}}catch{return fail('contextualTemporal','MALFORMED_OUTSIDE_BOUND_CUTOFF_OR_ACCEPTED_TRUTH_CONFLICT')}
 let normalized,semantic;try{semantic=strictTransfers(exact,request,times);if(!semantic.pass)return {...fail('normalization',semantic.code),semanticStats:semantic.stats};normalized=semantic.normalizedRecords;stages.normalization={status:'PASS',nullImputed:false,enrichmentFieldsExported:0,labelsExported:0,originalRawTimestampExported:false,subjectParticipation:true,exactSignedLexemePreserved:true,strictlyPositive:true,deterministicDeduplication:true}}catch{return fail('normalization','STRICT_TRANSFER_CORE_OR_EXACT_DECIMAL')}
 try{validateSchema('provider',normalized,normalizedSchema);stages.projection={status:'PASS',allowlistOnly:true}}catch{return fail('projection','NORMALIZED_PUBLIC_ALLOWLIST_SCHEMA')}
 const publicRecord=normalized.length?{schema_version:'5.0.1',campaign_id:bound.envelope.campaignId,authorization_id:PUBLIC_AUTH,public_call_id:`NQ5-${String(sequence).padStart(6,'0')}`,qualification_sequence:sequence,tranche_id:'T1',endpoint_family:request.family,business_question:request.businessQuestion,purpose_code:request.purpose,consumer_ids:request.consumers,request_body_sha256:identity(request.body),response_sha256:row.rawSha256,normalized_sha256:identity(normalized),result_count:normalized.length,route_disposition:'BOUNDED_ACTIVITY',evidence_grade:'CONTEXTUAL',temporal_class:TEMPORAL,coverage_scope:`${request.body.date.from} through ${request.body.date.to}; server-filtered PAGE.1 contextual candidate discovery only; no exact UTC, negative evidence or cutoff completeness`,selection_lineage_summary:request.lineage,coverage_cell_ids:request.coverageCells,coverage_key:request.coverageKey,raw_payload_published:false,attribution:'Powered by Nansen API',investigative_question_id:request.questionId,question_lens:request.lens}:null
 try{if(publicRecord){assertCampaignRecord(publicRecord,bound.envelope.campaignId);validateSchema('public',publicRecord)}stages.publicSchema={status:'PASS',exactCampaignBinding:true}}catch{return fail('publicSchema','PUBLIC_CALL_INDEX_SCHEMA')}
 return {safelyAdmissible:true,firstFailedStage:null,stages,publicRecord:replayOnly?null:publicRecord,normalizedRecords:normalized,normalizedSha256:identity(normalized),resultCount:normalized.length,pagination:{page:response.pagination.page,isLastPage:response.pagination.is_last_page},nullEnrichmentFieldsObserved:response.data.flatMap(r=>[...(r.tokens_sent??[]),...(r.tokens_received??[])]).reduce((n,t)=>n+['price_usd','value_usd'].filter(k=>t[k]===null).length,0),semanticStats:semantic.stats,qualificationCountedFromReplay:false}
}
export function plans(bound,p){const requests=IDS.map(id=>{const r=bound.plan.requests.find(r=>r.logicalId===id);if(!r||r.family!==p.scope.family||r.expectedCredits!==1||r.worstCaseCredits!==3||r.body.pagination.page!==1)throw new Error('R3_FOUR_ORIGINAL_ROWS_REQUIRED');return r});const plan=seal({schemaVersion:'1.0.0',authorizationId:AUTH,executionContractSha256:CONTRACT_SHA,campaignId:bound.envelope.campaignId,originalPlanIdentity:bound.plan.hash,compatibilityProfileIdentity:p.hash,frozen:true,AUTHORIZED_TO_ISSUE:false,authority:'CONDITIONAL_ON_ALL_PRELIVE_GATES',requests,expectedCredits:4,worstCaseCredits:12,maximumAdditionalAttempts:12,maximumCumulativeAttempts:14,maximumCumulativeCredits:14,canaryIds:IDS.slice(0,2),remainingIds:IDS.slice(2),historicalDisposition:'PARKED_OFF_CRITICAL_PATH',newRequests:0,replacements:0});const reserve=seal({schemaVersion:'1.0.0',planIdentity:plan.hash,latestSafeAnchor:627478,protectedReserve:250,additionalWorstCaseCredits:12,remainingAfterWorstCase:627466,reserveHeadroom:627216,expectedAdditionalCredits:4,priorCredits:2,maximumCumulativeCredits:14,unattributedAccountWideChange:2547,accountRequests:0});return {plan,reserve}}
