import { identity, sha, validateSchema } from '../nq5/schema.mjs'
import { readMirrored } from '../nq5-b1/store.mjs'
import { CONSUMED } from '../nq5-b1-r1/checkpoint.mjs'
import { logicalRequest } from '../nq5/planner.mjs'
import { AUTH, CONTRACT_SHA, IDS, seal } from './authority.mjs'
import { admit, TEMPORAL, DRIFT } from './compatibility.mjs'

export function audit(context,proof,{rawForResponse=row=>readMirrored(context.roots,'raw-b1/'+row.rawName)}={}){
 const {bound,accepted,profile,plans,oldProfile,truth}=context,current=proof.current
 const records=accepted.audit.records.map(original=>{
  const r=structuredClone(original),id=r.logicalId,request=bound.plan.requests.find(q=>q.logicalId===id),counted=current.terminals.get(id)?.disposition==='SUCCESS_COUNTED',old=CONSUMED.includes(id),eligible=IDS.includes(id)
  const disposition=old?'CONSUMED_IMMUTABLE_NONCOUNTED':!eligible?'PARKED_HISTORICAL_OFF_CRITICAL_PATH':counted?'ISSUED_TERMINAL_COUNTED':current.starts.has(id+'.1')?'ISSUED_NONCOUNTED_BREAKER':proof.report.newAttempts?'NOT_ISSUED_BREAKER':'ELIGIBLE_CONDITIONAL_FOUR_ONLY'
  r.r3ContractReview={authorizationId:AUTH,compatibilityProfileIdentity:profile.hash,planIdentity:plans.plan.hash,publishedRequestSchemaIdentity:profile.publishedRequestSchemaIdentity,publishedResponseSchemaIdentity:profile.publishedResponseSchemaIdentity,officialEndpointSha256:profile.officialEndpointSha256,r2NegativeClarificationSha256:profile.r2NegativeClarificationSha256,observedDriftNotice:DRIFT,disposition,document_provenance_value:'CAPTURED_OFFICIAL_SCHEMA_AND_NEGATIVE_CLARIFICATION_WITH_LEAD_COMPATIBILITY_DRIFT_DISCLOSURE',contextualOnly:true,retroactiveCount:false}
  if(!eligible)return r
  const terminal=current.terminals.get(id),starts=[...current.starts.values()].filter(s=>s.logicalId===id)
  r.authorizationId=AUTH;r.executionContractSha256=CONTRACT_SHA;r.issued=starts.length>0;r.issueDisposition=starts.length?'ISSUED_R3':'NOT_ISSUED_BREAKER'
  r.attempts=starts.map(start=>{const response=current.responses.get(id+'.'+start.attempt),raw=response?rawForResponse(response):null,a=response?.httpStatus===200?admit(bound,request,raw,response,terminal?.publicRecord?.qualification_sequence??1,profile,oldProfile,truth,{replayOnly:true}):null
   return{attemptNumber:start.attempt,attemptIdentity:start.hash,startSequence:start.sequence,responseSequence:response?.sequence??null,terminalSequence:terminal?.attempt===start.attempt?terminal.sequence:null,issuedAtUtc:start.issuedAtUtc,completedAtUtc:response?.completedAtUtc??null,completedTimestampDisposition:response?'CAPTURED':'NO_RESPONSE',latencyMs:response?.latencyMs??null,httpStatus:response?.httpStatus??null,provider_request_id:response?.providerRequestId??null,providerRequestIdDisposition:response?response.providerRequestId?'CAPTURED':'MISSING_FUTURE_REQUEST_ID':'NO_RESPONSE',safeHeaders:response?.headers??{},quotedCredits:response?.quotedCredits??null,actualCredits:response?.actualCredits??null,remainingCredits:response?.remainingCredits??null,rawBytes:response?.rawBytes??null,primarySha256:response?.rawSha256??null,mirrorSha256:response?.rawSha256??null,bytesEqual:!!response,responseSchemaIdentity:profile.publishedResponseSchemaIdentity,validation:null,r3Validation:{...a?.stages,requestAudit:{status:terminal?.attempt===start.attempt?terminal.auditDisposition??'NOT_RUN':'NOT_RUN'}}}
  })
  Object.assign(r,{terminalDisposition:terminal?.disposition??null,qualificationCounted:counted,qualificationSequence:counted?terminal.publicRecord.qualification_sequence:null,exclusionReason:counted?null:terminal?.reason??(starts.length?'UNRESOLVED_START':'NO_ISSUE_AFTER_BREAKER_OR_PRELIVE_HOLD'),publicCallId:counted?terminal.publicRecord.public_call_id:null,normalizedIdentity:counted?terminal.normalizedSha256:null,admittedResultCount:counted?terminal.resultCount:null,qualification_value:counted?'ADMITTED_BOUNDED_EVIDENCE':'ZERO_NOT_COUNTED',engineering_value:starts.length?['AUTHENTICATED_TRANSPORT','CONCURRENCY_OBSERVATION','DURABLE_PRIMARY_MIRROR_STORAGE','BILLING_RATE_HEADER_OBSERVATION',...(!counted?['VALIDATION_MISMATCH_DIAGNOSIS']:[])]:[],gameplay_consumer_value:counted?'ADMITTED_BOUNDED_EVIDENCE_NOT_INTEGRATION_ACCEPTANCE':'NO_ADMITTED_GAMEPLAY_EVIDENCE_FROM_B1_V1',competition_evidence_value:counted?'SAFE_ADMITTED_QUALIFICATION_AUDIT':starts.length?'SAFE_ENGINEERING_AUDIT_ONLY':'PLAN_ONLY_NOT_ISSUED'})
  return r
 })
 const result={...accepted.audit,authorizationId:AUTH,records};validateSchema('provider',result,context.auditSchema)
 for(const r of result.records.filter(r=>!IDS.includes(r.logicalId))){const {r3ContractReview,...unchanged}=r;if(identity(unchanged)!==identity(accepted.audit.records.find(o=>o.logicalId===r.logicalId)))throw new Error('R3_OLD_OR_HELD_AUDIT_MUTATION')}
 if(result.records.length!==15||result.records.filter(r=>r.qualificationCounted).length!==proof.report.newCounted||result.records.flatMap(r=>r.attempts).length!==proof.report.cumulativeAttempts)throw new Error('R3_AUDIT_INVENTORY_COUNT')
 return result
}
export function prospectiveAudit(context,store,terminal){const current=store.currentForAudit(),terminals=new Map(current.terminals);terminals.set(terminal.logicalId,{...terminal,sequence:current.rows.length+1});const newCounted=[...terminals.values()].filter(t=>t.disposition==='SUCCESS_COUNTED').length;return audit(context,{current:{...current,terminals},report:{newCounted,cumulativeAttempts:current.starts.size,newAttempts:current.starts.size-2}},{rawForResponse:row=>store.raw(row)})}
export function safeReplay(context){const id=CONSUMED[1],request=context.bound.plan.requests.find(r=>r.logicalId===id),row=context.prior.responses.get(id+'.1'),raw=readMirrored(context.roots,'raw-b1/'+row.rawName),a=admit(context.bound,request,raw,row,1,context.profile,context.oldProfile,context.truth,{replayOnly:true});return{schemaVersion:'1.0.0',logicalId:id,rawBytes:raw.length,primarySha256:sha(raw),mirrorSha256:sha(raw),bytesEqual:true,profileIdentity:context.profile.hash,originalTerminal:'ISSUED_TERMINAL_NONCOUNTED',originalTerminalUnchanged:true,retroactiveQualificationCounted:false,publicCallId:null,rawTimestampUnchanged:true,rawBodyIncluded:false,privatePathsIncluded:false,safelyAdmissible:a.safelyAdmissible,firstFailedStage:a.firstFailedStage,stages:a.stages,admittedContextualTransferCount:a.resultCount,nullEnrichmentFieldsObserved:a.nullEnrichmentFieldsObserved??0,normalizedIdentity:a.normalizedSha256??null,observedDriftNotice:DRIFT}}
export function nextFrontier(context,proof){
 if(!proof.report.clean||proof.report.newCounted!==4||proof.publicIndex.length!==4)return null
 const requests=[],dedupe=new Set()
 for(const projection of proof.projections){if(projection.pagination.isLastPage)continue;const original=context.bound.plan.requests.find(r=>r.logicalId===projection.logicalId);if(!context.truth.seedAddresses.includes(original.body.address.toLowerCase())||!projection.rows.length||!original.consumers.every(c=>/^(CASEBOARD|TEST|COVERAGE)\./.test(c)))continue
  const r=structuredClone(original);r.body.pagination.page=2;const equivalent=identity({path:r.path,body:r.body});if(dedupe.has(equivalent))continue;dedupe.add(equivalent);r.sequence=requests.length+1;r.coverageKey.page_or_partition_id='PAGE.2';r.coverageCells=['CELL.'+identity(r.coverageKey)];r.partition={page:2,admittedOnlyByDurablePreviousPage:true};r.lineage=[...original.lineage,'DURABLE_COUNTED_REQUEST.'+original.logicalId];r.frontierProof={kind:'DURABLE_NEXT_PAGE_METADATA',priorLogicalId:original.logicalId,priorPublicCallId:proof.publicIndex.find(p=>p.request_body_sha256===identity(original.body))?.public_call_id,priorLedgerSha256:proof.report.ledgerSha256,page:1,isLastPage:false,priorNormalizedRowCount:projection.rows.length,marginalUtility:'Continue this same named ACTIVITY question for the named test/coverage/Caseboard consumers; contextual discovery only, never exact proof or negative completeness.'};r.novelty=r.frontierProof.marginalUtility;r.publicProjectionPolicy={compatibilityProfileIdentity:context.profile.hash,temporalClass:TEMPORAL,rawTimestampExport:false,nullEnrichmentExport:false,exactUtcOnlyAcceptedTruthHashJoin:true,attribution:'Powered by Nansen API'};r.logicalId=logicalRequest(r);requests.push(r)
 }
 if(requests.length>4||requests.some(r=>IDS.includes(r.logicalId)||r.body.pagination.page!==2))throw new Error('R3_FRONTIER_PADDING_OR_DUPLICATE')
 const remaining=Math.min(627478,...[...proof.current.responses.values()].map(r=>r.remainingCredits).filter(Number.isSafeInteger)),worst=requests.length*3
 const policy=seal({schemaVersion:'1.0.0',family:'profiler/address/transactions',chain:'ethereum',maximumProposedRequests:256,minimumRequests:0,noFixedPageCeiling:true,noMicroWindows:true,noEquivalentFilters:true,noHeldFamilies:true,newSubjects:0,publicSafeSeedAndDurableLineageOnly:true,contextualOnly:true,stopOnMarginalUtilitySaturation:true,issuedInR3:false})
 const plan=seal({schemaVersion:'1.0.0',candidateOnly:true,AUTHORIZED_TO_ISSUE:false,profileIdentity:context.profile.hash,priorReconciliationIdentity:identity(proof.report),policyIdentity:policy.hash,frozen:true,requests,expectedCredits:requests.length,worstCaseCredits:worst})
 const reserve=seal({schemaVersion:'1.0.0',planIdentity:plan.hash,anchor:remaining,protectedReserve:250,worstCaseCredits:worst,remainingAfterWorstCase:remaining-worst,reservePass:remaining-worst>=250,AUTHORIZED_TO_ISSUE:false})
 return {plan,reserve,policy,report:{schemaVersion:'1.0.0',allFourCounted:true,proposalCount:requests.length,reason:requests.length?'DURABLE_NONLAST_PAGE_WITH_NAMED_MARGINAL_UTILITY':'NO_MEANINGFUL_UNISSUED_PAGE_PROVEN_FROM_DURABLE_RESULTS',newSubjectProposals:0,heldFamilies:0,nextRequestsIssued:0,planIdentity:plan.hash,reserveIdentity:reserve.hash,policyIdentity:policy.hash}}
}
export const claimMatrix={schemaVersion:'1.0.0',observedDriftNotice:DRIFT,temporalClass:TEMPORAL,allowed:['CONTEXTUAL_ACTIVITY','CANDIDATE_DISCOVERY','EXACT_TIME_ONLY_SEPARATELY_ACCEPTED_EULER_HASH_JOIN'],forbidden:['INFERRED_UTC','APPENDED_Z','NEGATIVE_EVIDENCE','CUTOFF_COMPLETENESS','CAUSATION','EXACT_PROOF_SLOT','ZERO_IMPUTATION','RETROACTIVE_COUNT','HISTORICAL_OR_BETA_ISSUE'],rawTimestampPublished:false,labelsPublished:false,gameplayIntegrationAccepted:false}
