import fs from 'node:fs'
import path from 'node:path'
import https from 'node:https'
import { randomUUID } from 'node:crypto'
import { identity, sha } from '../nq5/schema.mjs'
import { BatchStore, replay, readMirrored } from '../nq5-b1/store.mjs'
import { RateGate, retryAfter } from '../nq5-b1/dispatcher.mjs'
import { captureSafeHeaders } from '../nq5-b1-r1/headers.mjs'
import { CONSUMED, LEDGER_SHA } from '../nq5-b1-r1/checkpoint.mjs'
import { AUTH, CONTRACT_SHA, IDS, seal } from './authority.mjs'
import { admit } from './compatibility.mjs'
import { assertLiveContext } from './gate-proof.mjs'
import { audit, prospectiveAudit } from './evidence.mjs'

export const LOCK='B1_R3_RESUME_LOCK.json'
const admitted=new WeakSet()
const constructedStores=new WeakMap()
export function authorizeContext(context,evidence){
 if(evidence.localPass!==true||evidence.reviewPass!==true||evidence.docsPass!==true||evidence.replayPass!==true||context.prior.bytesSha256!==LEDGER_SHA||context.prior.bytes!==4659||context.prior.starts.size!==2||context.prior.responses.size!==2||context.prior.terminals.size!==2||identity([...context.prior.terminals.keys()].sort())!==identity([...CONSUMED].sort())||[...context.prior.terminals.values()].some(r=>r.disposition!=='TERMINAL_FAILURE')||context.prior.rows.some(r=>r.kind==='TERMINAL'&&r.disposition!=='TERMINAL_FAILURE'))throw new Error('R3_COMPLETE_PRELIVE_GATES_REQUIRED')
 admitted.add(context);return context
}
export function resumeEnvelope(context,candidate,digest,docs){return seal({schemaVersion:'1.0.0',authorizationId:AUTH,executionContractSha256:CONTRACT_SHA,campaignId:context.bound.envelope.campaignId,priorEnvelopeIdentity:context.bound.envelope.hash,priorLedgerSha256:LEDGER_SHA,priorLedgerBytes:4659,originalLockSha256:context.diagnostic.originalLockSha256,candidate,implementationSha256:digest,planIdentity:context.plans.plan.hash,reserveIdentity:context.plans.reserve.hash,compatibilityProfileIdentity:context.profile.hash,officialSourceIdentity:identity(docs),consumedIds:CONSUMED,executionOrder:IDS,maximumAdditionalAttempts:12,maximumAdditionalCredits:12,maximumCumulativeAttempts:14,maximumCumulativeCredits:14,protectedReserve:250,latestSafeAnchor:627478,maximumConcurrency:2,retryStatuses:context.bound.envelope.retryStatuses,maximumAttemptsPerId:3,invocationLockFailIfExists:true,providerRequestIdRequiredForCount:true,heldFamiliesIssued:false,nextFrontierIssued:false})}
function exclusive(file,bytes){const fd=fs.openSync(file,fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_EXCL|fs.constants.O_NOFOLLOW,0o600);try{fs.writeFileSync(fd,bytes);fs.fsyncSync(fd)}finally{fs.closeSync(fd)}const d=fs.openSync(path.dirname(file),fs.constants.O_RDONLY|fs.constants.O_DIRECTORY|fs.constants.O_NOFOLLOW);try{fs.fsyncSync(d)}finally{fs.closeSync(d)}}
export class ResumeStore {
 constructor(context,envelope){
  if(!admitted.has(context))throw new Error('R3_PRIVATE_WRITE_GATE_REQUIRED')
  const proof=assertLiveContext(context)
  if(identity(envelope)!==identity(resumeEnvelope(context,proof.candidate,proof.implementationSha256,proof.docs.index)))throw new Error('R3_EXACT_RESUME_ENVELOPE_REQUIRED')
  const current=replay(context.roots,context.bound.envelope);if(current.bytesSha256!==LEDGER_SHA||current.bytes!==4659||identity(current.rows)!==identity(context.prior.rows))throw new Error('R3_BASELINE_CHANGED')
  this.roots=context.roots;this.envelope=context.bound.envelope;this.resumeEnvelope=envelope;this.rows=[...current.rows];this.failed=false;this.context=context
  const lock={resumeEnvelopeHash:envelope.hash,campaignId:envelope.campaignId,invocationId:randomUUID(),candidate:envelope.candidate,implementationSha256:envelope.implementationSha256}
  try{for(const root of this.roots)exclusive(path.join(root,LOCK),Buffer.from(JSON.stringify(lock)+'\n'));readMirrored(this.roots,LOCK)}catch{this.failed=true;throw new Error('R3_EXCLUSIVE_RESUME_LOCK_FAILED_NO_REPAIR')}
  constructedStores.set(this,{context,lockIdentity:identity(lock),envelopeIdentity:identity(envelope),roots:[...this.roots]})
 }
 append(payload){if(!IDS.includes(payload.logicalId)||CONSUMED.includes(payload.logicalId))throw new Error('R3_CONSUMED_OR_UNAUTHORIZED_ID');const row={...payload,resumeEnvelopeHash:this.resumeEnvelope.hash,authorizationId:AUTH,executionContractSha256:CONTRACT_SHA,planIdentity:this.context.plans.plan.hash,compatibilityProfileIdentity:this.context.profile.hash,observedDriftNotice:this.context.profile.observedDriftNotice};return BatchStore.prototype.append.call(this,row)}
 persist(...args){if(!IDS.includes(args[0]))throw new Error('R3_UNAUTHORIZED_RAW_WRITE');return BatchStore.prototype.persist.apply(this,args)}
 raw(row){return readMirrored(this.roots,'raw-b1/'+row.rawName)}
 currentForAudit(){return replay(this.roots,this.envelope)}
}
export function reconcile(context,envelope){
 const {bound,roots,profile,oldProfile,truth}=context,current=replay(roots,bound.envelope),bytes=readMirrored(roots,'qualification.jsonl')
 if(bytes.length<4659||sha(bytes.subarray(0,4659))!==LEDGER_SHA||identity(current.rows.slice(0,context.prior.rows.length))!==identity(context.prior.rows))throw new Error('R3_ORIGINAL_HISTORY_CHANGED')
 const originalLock=readMirrored(roots,'B1_EXECUTION_LOCK.json');if(sha(originalLock)!==context.diagnostic.originalLockSha256)throw new Error('R3_ORIGINAL_LOCK_CHANGED')
 for(const n of ['genesis.json','GENESIS_COMMIT.json'])if(sha(readMirrored(roots,n))!==context.originalStateHashes[n])throw new Error('R3_GENESIS_CHANGED')
 const added=current.rows.slice(context.prior.rows.length),starts=added.filter(r=>r.kind==='START'),responses=added.filter(r=>r.kind==='RESPONSE'),terminals=added.filter(r=>r.kind==='TERMINAL')
 if(starts.length>12||current.starts.size>14||starts.some(r=>!IDS.includes(r.logicalId))||added.some(r=>r.resumeEnvelopeHash!==envelope.hash||r.authorizationId!==AUTH||r.executionContractSha256!==CONTRACT_SHA||r.planIdentity!==context.plans.plan.hash||r.compatibilityProfileIdentity!==profile.hash||r.observedDriftNotice!==profile.observedDriftNotice))throw new Error('R3_ADDED_AUTHORITY_CAPACITY_OR_PROFILE_DRIFT')
 if(starts.some(s=>s.requestBodySha256!==identity(bound.plan.requests.find(r=>r.logicalId===s.logicalId).body)||s.reservedCredits!==1||!Number.isFinite(Date.parse(s.issuedAtUtc)))||responses.some(r=>identity(captureSafeHeaders(r.headers))!==identity(r.headers)||r.providerRequestId!==(r.headers['x-request-id']??null)||!Number.isFinite(Date.parse(r.completedAtUtc))||!Number.isSafeInteger(r.latencyMs)||r.latencyMs<0))throw new Error('R3_REQUEST_AUDIT_IDENTITY')
 if(added.length){const lock=JSON.parse(readMirrored(roots,LOCK));if(lock.resumeEnvelopeHash!==envelope.hash||lock.campaignId!==envelope.campaignId||identity(lock.candidate)!==identity(envelope.candidate)||lock.implementationSha256!==envelope.implementationSha256||typeof lock.invocationId!=='string')throw new Error('R3_RESUME_LOCK_IDENTITY')}
 const expectedRaw=[...current.responses.values()].map(r=>r.rawName).sort().join();for(const root of roots)if(fs.readdirSync(path.join(root,'raw-b1')).sort().join()!==expectedRaw)throw new Error('R3_ORPHAN_RAW_STOP_NO_REPAIR')
 let counted=0;const projections=[],publicIndex=[]
 for(const terminal of terminals){const request=bound.plan.requests.find(r=>r.logicalId===terminal.logicalId),response=current.responses.get(terminal.logicalId+'.'+terminal.attempt);if(terminal.disposition==='SUCCESS_COUNTED'){
   if(terminal.auditDisposition!=='PASS'||!response||!response.providerRequestId||response.providerRequestId!==response.headers['x-request-id']||response.actualCredits!==1||response.quotedCredits!==1||!Number.isSafeInteger(response.remainingCredits)||response.remainingCredits<250||response.httpStatus!==200)throw new Error('R3_COUNT_ACCOUNTING_OR_PROVIDER_ID')
   const a=admit(bound,request,readMirrored(roots,'raw-b1/'+response.rawName),response,counted+1,profile,oldProfile,truth);if(!a.safelyAdmissible||!a.resultCount||identity(a.publicRecord)!==identity(terminal.publicRecord)||identity(a.stages)!==identity(terminal.validationStages)||a.normalizedSha256!==terminal.normalizedSha256||a.resultCount!==terminal.resultCount)throw new Error('R3_COUNT_DURABLE_REDERIVATION')
   counted++;projections.push({logicalId:request.logicalId,rows:a.normalizedRecords,pagination:a.pagination});publicIndex.push(a.publicRecord)
  }else if(terminal.publicRecord!==null)throw new Error('R3_NONCOUNTED_PUBLIC_ID')
 }
 const knownCredits=responses.reduce((n,r)=>n+(r.actualCredits??0),0),unresolved=starts.filter(s=>!current.responses.has(s.logicalId+'.'+s.attempt)||current.responses.get(s.logicalId+'.'+s.attempt).actualCredits===null).length,unresolvedTerminals=starts.filter(s=>!current.terminals.has(s.logicalId)).length
 if(knownCredits>12||knownCredits+2>14)throw new Error('R3_CREDIT_CAP')
 return {current,projections,publicIndex,report:{schemaVersion:'1.0.0',ledgerSha256:current.bytesSha256,ledgerBytes:current.bytes,originalPrefixUnchanged:true,original2NoncountedUnchanged:true,originalLockUnchanged:true,genesisUnchanged:true,dualRawBytesEqual:true,newAttempts:starts.length,newProvider2xx:responses.filter(r=>r.httpStatus>=200&&r.httpStatus<300).length,newCounted:counted,newKnownActualCredits:knownCredits,cumulativeAttempts:current.starts.size,cumulativeCounted:counted,cumulativeKnownActualCredits:knownCredits+2,unresolvedReservations:unresolved,unresolvedTerminals,clean:unresolved===0&&unresolvedTerminals===0,exactProviderRequestIdsCaptured:responses.filter(r=>r.providerRequestId).length,publicIndexIdentity:identity(publicIndex),privatePathsIncluded:false,rawBodiesIncluded:false,accountRequests:0}}
}
export class Executor {
 constructor({context,store,transport,rate=new RateGate(),now=Date.now,sleep=ms=>new Promise(r=>setTimeout(r,ms)),random=Math.random,signal,reconcileState=reconcile}){if(!admitted.has(context)||store.context!==context||store.rows.length!==context.prior.rows.length)throw new Error('R3_EXECUTION_PROOF_REQUIRED');if(constructedStores.has(store)&&reconcileState!==reconcile)throw new Error('R3_LIVE_RECONCILIATION_OVERRIDE_FORBIDDEN');Object.assign(this,{context,store,transport,rate,now,sleep,random,signal,reconcileState});this.stopReason=null;this.started=new Set();this.completed=new Map();this.attempts=0;this.credits=0;this.reserved=0;this.remaining=627478;this.inFlight=0;this.maxInFlight=0;this.commitRank=0;this.counted=0;this.writerFailed=false;this.running=false}
 stop(code){this.stopReason??=code}
 flush(){while(!this.writerFailed&&this.commitRank<IDS.length){const id=IDS[this.commitRank],result=this.completed.get(id);if(!result)break;const request=this.context.bound.plan.requests.find(r=>r.logicalId===id);let a
   try{if(!result.failure&&result.response)a=admit(this.context.bound,request,this.store.raw(result.response),result.response,this.counted+1,this.context.profile,this.context.oldProfile,this.context.truth);if(a&&!a.safelyAdmissible)result.failure='R3_'+a.firstFailedStage.toUpperCase()+'_REJECTED';if(a&&!a.resultCount)result.failure??='R3_EMPTY_NOT_NEGATIVE_EVIDENCE';let counted=!!a?.safelyAdmissible&&a.resultCount>0&&!result.failure;const t={kind:'TERMINAL',logicalId:id,attempt:result.attempt,disposition:counted?'SUCCESS_COUNTED':'TERMINAL_FAILURE',reason:counted?null:result.failure??'R3_UNRESOLVED_ATTEMPT',publicRecord:counted?a.publicRecord:null,validationStages:a?.stages??{},normalizedSha256:counted?a.normalizedSha256:null,resultCount:counted?a.resultCount:0};if(counted){t.auditDisposition='PASS';try{prospectiveAudit(this.context,this.store,t)}catch{counted=false;Object.assign(t,{disposition:'TERMINAL_FAILURE',reason:'R3_AUDIT_BEFORE_COUNT_REJECTED',publicRecord:null,normalizedSha256:null,resultCount:0,auditDisposition:'FAIL'})}}else t.auditDisposition='NOT_RUN';this.store.append(t);if(counted)this.counted++;else this.stop(t.reason);this.commitRank++}catch{this.writerFailed=true;this.stop('R3_DURABLE_VALIDATION_OR_TERMINAL_WRITE_FAILED')}
  }}
 async issue(id){if(!IDS.includes(id)||this.started.has(id)||this.context.prior.starts.has(id+'.1'))throw new Error('R3_REISSUE_OR_UNAUTHORIZED');this.started.add(id);const request=this.context.bound.plan.requests.find(r=>r.logicalId===id);let result={attempt:0,response:null,failure:null}
  for(let attempt=1;attempt<=3;attempt++){try{
   if(!await this.rate.acquire(()=>!!this.stopReason||this.signal?.aborted))break;if(this.stopReason||this.signal?.aborted)break
   if(this.attempts>=12||this.credits+this.reserved+1>12||this.remaining-this.reserved-1<250||this.inFlight>=2)throw new Error('R3_CAPACITY');this.attempts++;this.reserved++;result.attempt=attempt
   this.store.append({kind:'START',logicalId:id,attempt,requestBodySha256:identity(request.body),issuedAtUtc:new Date(this.now()).toISOString(),reservedCredits:1});this.inFlight++;this.maxInFlight=Math.max(this.maxInFlight,this.inFlight);const began=this.now();let received
   try{received=await this.transport(request,{connectTimeoutMs:5000,totalTimeoutMs:30000})}catch{result.failure='R3_TRANSPORT_INDETERMINATE';this.stop(result.failure);break}finally{this.inFlight--}
   if(!received||!Buffer.isBuffer(received.bytes)||!Number.isInteger(received.status))throw new Error('R3_TRANSPORT_SHAPE');const headers=captureSafeHeaders(received.headers),storage=this.store.persist(id,attempt,received.bytes),number=n=>/^\d+$/.test(headers[n]??'')&&Number.isSafeInteger(Number(headers[n]))?Number(headers[n]):null,cost=number('x-nansen-credits-used'),quoted=number('x-nansen-credits-cost'),remaining=number('x-nansen-credits-remaining')
   const row=this.store.append({kind:'RESPONSE',logicalId:id,attempt,httpStatus:received.status,quotedCredits:quoted,actualCredits:cost,remainingCredits:remaining,headers,...storage,latencyMs:Math.max(0,this.now()-began),completedAtUtc:new Date(this.now()).toISOString(),providerRequestId:headers['x-request-id']??null});result.response=row
   if(cost!==null){this.reserved--;this.credits+=cost}if(remaining!==null)this.remaining=Math.min(this.remaining,remaining);this.rate.headers(headers,received.status)
   if(cost===null||quoted===null||cost>1||quoted>1||remaining===null||this.credits+this.reserved>12||this.remaining-this.reserved<250||!row.providerRequestId||received.status===200&&(cost!==1||quoted!==1)){result.failure='R3_CREDIT_RESERVE_OR_PROVIDER_ID_BREAKER';this.stop(result.failure);break}
   if(received.status===200){const a=admit(this.context.bound,request,this.store.raw(row),row,1,this.context.profile,this.context.oldProfile,this.context.truth);if(!a.safelyAdmissible||!a.resultCount){result.failure=!a.safelyAdmissible?'R3_'+a.firstFailedStage.toUpperCase()+'_REJECTED':'R3_EMPTY_NOT_NEGATIVE_EVIDENCE';this.stop(result.failure)}break}
   if(!this.context.bound.envelope.retryStatuses.includes(received.status)||attempt===3){result.failure='R3_HTTP_TERMINAL_BREAKER';this.stop(result.failure);break}
   const wait=Math.max(retryAfter(headers,this.now()),Math.floor(this.random()*1000*2**(attempt-1)));if(wait>60000)throw new Error('R3_RETRY_WAIT');let left=wait;while(left>0&&!this.stopReason&&!this.signal?.aborted){const step=Math.min(100,left);await this.sleep(step);left-=step}
  }catch{result.failure='R3_STORAGE_RATE_CAPACITY_OR_HEADER_BREAKER';this.stop(result.failure);break}}
  if(result.attempt){this.completed.set(id,result);this.flush()}
 }
 async run(){if(this.running)throw new Error('R3_INVOCATION_REPEATED');this.running=true;const abort=()=>this.stop('R3_CANCELLED');this.signal?.addEventListener('abort',abort,{once:true});try{if(this.signal?.aborted)abort();await Promise.all(IDS.slice(0,2).map(id=>this.issue(id)));this.flush();const proof=this.reconcileState(this.context,this.store.resumeEnvelope);if(!this.stopReason&&proof.report.clean&&proof.report.newCounted===2){try{audit(this.context,proof,{rawForResponse:row=>this.store.raw(row)})}catch{this.stop('R3_CANARY_COMPLETE_AUDIT_BREAKER')}}if(!this.stopReason&&proof.report.clean&&proof.report.newCounted===2&&this.counted===2&&this.reserved===0){await Promise.all(IDS.slice(2).map(id=>this.issue(id)));this.flush()}else this.stop(this.stopReason??'R3_CANARY_RECONCILIATION_BREAKER');return{stopReason:this.stopReason,newAttempts:this.attempts,newActualCredits:this.credits,newCounted:this.counted,unresolvedReservations:this.reserved,maximumInFlight:this.maxInFlight}}finally{this.signal?.removeEventListener('abort',abort)}}
}
// Runtime only, after the gate closure supplies an admitted, locked context.
export function liveTransport(context,store,{environmentCredential=()=>process.env.NANSEN_API_KEY}={}){
 const proof=constructedStores.get(store)
 if(!admitted.has(context)||!proof||proof.context!==context||store.context!==context||store.failed||identity(proof.roots)!==identity(store.roots)||identity(store.resumeEnvelope)!==proof.envelopeIdentity)throw new Error('R3_CREDENTIAL_GATE_REQUIRED')
 assertLiveContext(context,{locked:true})
 if(identity(JSON.parse(readMirrored(proof.roots,LOCK)))!==proof.lockIdentity)throw new Error('R3_RESUME_LOCK_IDENTITY')
 let key=environmentCredential()
 if(!key){const found=[],dir=path.join(path.dirname(context.root),'sources');const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){if(e.isSymbolicLink())continue;const f=path.join(d,e.name);if(e.isDirectory())walk(f);else if(e.isFile()&&/(?:^|[-_ ])NANSEN_API_KEY\.txt$/.test(e.name))found.push(f)}};if(fs.existsSync(dir))walk(dir);if(found.length!==1)throw new Error('R3_APPROVED_CREDENTIAL_UNAVAILABLE_PAUSE');const stat=fs.lstatSync(found[0]);if(stat.isSymbolicLink()||!stat.isFile()||stat.size>4096)throw new Error('R3_APPROVED_CREDENTIAL_UNAVAILABLE_PAUSE');const fd=fs.openSync(found[0],fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{key=fs.readFileSync(fd,'utf8').trim()}finally{fs.closeSync(fd)}}
 if(typeof key!=='string'||key.length<8||key.length>4096||/[^\x21-\x7e]/.test(key))throw new Error('R3_APPROVED_CREDENTIAL_UNAVAILABLE_PAUSE')
 return (request,timeouts)=>new Promise((resolve,reject)=>{if(!IDS.includes(request.logicalId)||!context.bound.plan.requests.some(r=>identity(r)===identity(request)))return reject(new Error('R3_PROVIDER_REQUEST_NOT_FROZEN'));let settled=false,connectTimer,totalTimer;const fail=()=>{if(settled)return;settled=true;clearTimeout(connectTimer);clearTimeout(totalTimer);req.destroy();reject(new Error('R3_PROVIDER_TRANSPORT_FAILED'))};const req=https.request({hostname:'api.nansen.ai',port:443,path:'/api/v1/profiler/address/transactions',method:'POST',agent:false,headers:{apikey:key,'content-type':'application/json',accept:'application/json'}},res=>{clearTimeout(connectTimer);let length=0;const chunks=[];res.on('data',b=>{length+=b.length;if(length>32000000)return fail();chunks.push(b)});res.on('error',fail);res.on('aborted',fail);res.on('end',()=>{if(settled)return;const bytes=Buffer.concat(chunks);if(bytes.includes(Buffer.from(key))||Object.values(res.headers).some(v=>String(v).includes(key)))return fail();let headers;try{headers=captureSafeHeaders(res.headers,key)}catch{return fail()}settled=true;clearTimeout(totalTimer);resolve({status:res.statusCode,bytes,headers})})});req.on('socket',s=>s.once('secureConnect',()=>clearTimeout(connectTimer)));req.on('error',fail);connectTimer=setTimeout(fail,5000);totalTimer=setTimeout(fail,Math.min(60000,Math.max(30000,timeouts.totalTimeoutMs)));req.end(JSON.stringify(request.body))})
}
