#!/usr/bin/env node
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync, spawn } from 'node:child_process'
import { identity, sha } from '../nq5/schema.mjs'
import { git } from '../nq5-b1-r2/gates.mjs'
import { LOCAL_SUITES } from '../nq5-b1/live.mjs'
import { localGate as localEvidenceGate, reviewGate as dedicatedReviewGate, admitPreLive } from './gate-proof.mjs'
import { blockedReports } from './blocked.mjs'
import { sanitizeLog, pathScan } from '../nq5-b1-r2/privacy.mjs'
import { BASE, TREE, CONTRACT_SHA, ARCHIVE_SHA, OUTPUT, AUTH, digest, cut, seal } from './authority.mjs'
import { publicContext, privateContext } from './context.mjs'
import { freshness, recheckFresh, readCapturedDocs } from './docs.mjs'
import { safeReplay, audit, nextFrontier, claimMatrix } from './evidence.mjs'
import { authorizeContext, resumeEnvelope, ResumeStore, Executor, liveTransport, reconcile } from './executor.mjs'

const originalEnvironment=process.env,environment=Object.fromEntries(['PATH','HOME','USER','LOGNAME','SHELL','TMPDIR','LANG','LC_ALL','DISPLAY','XDG_RUNTIME_DIR','PLAYWRIGHT_BROWSERS_PATH','npm_config_cache'].flatMap(n=>originalEnvironment[n]===undefined?[]:[[n,originalEnvironment[n]]]))
process.env=environment
const root=path.resolve(fileURLToPath(new URL('../..',import.meta.url))),parent=path.dirname(root),local=path.join(root,'artifacts/g6p-b1-r3/local'),preReview='docs/G6P_NQ5_T1_B1_R3_PRELIVE_REVIEW.json',postReview='docs/G6P_NQ5_T1_B1_R3_POSTLIVE_REVIEW.json'
const childEnv={...environment,PYTHONDONTWRITEBYTECODE:'1',NODE_OPTIONS:'--require '+path.join(root,'scripts/nq5-r2/hold.cjs'),npm_config_update_notifier:'false'}
const serialize=v=>Buffer.isBuffer(v)?v:Buffer.from(typeof v==='string'?v:JSON.stringify(v,null,2)+'\n')
const write=(dir,name,v,exclusive=false)=>{const f=path.join(dir,name);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,serialize(v),exclusive?{flag:'wx'}:{})}
const read=name=>JSON.parse(fs.readFileSync(path.join(local,name)))
const run=(command,args,cwd=root)=>new Promise((resolve,reject)=>{const c=spawn(command,args,{cwd,env:childEnv,stdio:['ignore','pipe','pipe']});let output='';for(const stream of [c.stdout,c.stderr])stream.on('data',b=>{output+=b;if(output.length>64000000)c.kill()});c.on('error',()=>reject(new Error('R3_LOCAL_TOOL_UNAVAILABLE')));c.on('close',code=>code===0?resolve(output):reject(new Error('R3_LOCAL_SUITE_FAILED')))})
const files=dir=>fs.readdirSync(dir).sort().flatMap(n=>{const f=path.join(dir,n),s=fs.lstatSync(f);if(s.isSymbolicLink())throw new Error('R3_PAYLOAD_SYMLINK');return s.isDirectory()?files(f):[f]})
const snapshot=()=>({candidate:cut(root),implementationSha256:digest(root)})
function reviewGate(name,options){return dedicatedReviewGate(root,name,options)}
function localGate(){return localEvidenceGate(root)}
function prepare(){const c=publicContext(root);write(local,'CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json',c.profile);write(local,'PLANS/T1_B1_R3_TRANSACTION_ONLY_PLAN.json',c.plans.plan);write(local,'PLANS/T1_B1_R3_RESERVE_PLAN.json',c.plans.reserve);process.stdout.write('R3_EXACT_FOUR_PLAN_FROZEN_CONDITIONAL_NO_PROVIDER_NO_KEY\n')}
async function verify(){publicContext(root);const starting=snapshot(),suites=[];const assert=()=>{if(identity(starting)!==identity(snapshot()))throw new Error('R3_VERIFICATION_SOURCE_CHANGED')};const suite=async(name,cmd,args,cwd=root)=>{assert();process.stdout.write('LOCAL '+name+'\n');const output=await run(cmd,args,cwd);assert();if(!output.trim())throw new Error('R3_EMPTY_SUITE_LOG');write(local,name+'.log',output);suites.push({name,status:'PASS',sha256:sha(Buffer.from(output))})}
 await suite('execution-adversarial','node',['node_modules/vitest/vitest.mjs','run','tests/unit/nq5-b1-executor.test.mjs','tests/unit/nq5-b1-r1-remediation.test.mjs','tests/unit/nq5-b1-r2-contracts.test.mjs','tests/unit/nq5-b1-r3-resume.test.mjs','--reporter=dot'])
 await suite('source-validator','python3',['VALIDATE_SOURCE_SET.py'],path.join(root,'docs/source/v1.7.0'));await suite('report-schema-controls','python3',['scripts/test-nq5-report-validation.py']);await suite('typecheck-lint','npm',['run','check']);await suite('acquisition-compile','npm',['run','acquisition:compile'])
 await suite('unit-regression','node',['node_modules/vitest/vitest.mjs','run','tests/unit',...['nq5-b1-executor','nq5-b1-r1-remediation','nq5-b1-r2-contracts','nq5-b1-r3-resume'].flatMap(n=>['--exclude','tests/unit/'+n+'.test.mjs']),'--reporter=dot']);await suite('acquisition-regression','node',['node_modules/vitest/vitest.mjs','run','tests/acquisition','--reporter=dot']);await suite('browser-accessibility-performance','npm',['run','test:e2e','--','--reporter=line']);await suite('production-build','npm',['run','build']);await suite('browser-boundary','npm',['run','browser-boundary:verify']);await suite('records-office-boundary','npm',['run','g6p:a1:boundary:verify']);await suite('euler-public-pack','npm',['run','g6:pack:verify']);await suite('project-clock-status','npm',['run','project:status']);await suite('history-secret-boundary','node',['scripts/verify-git-secret-history.mjs']);assert();write(local,'VERIFICATION.json',{schemaVersion:'1.0.0',status:'PASS',generatedAtUtc:new Date().toISOString(),...starting,suites,credentialAccess:false,actualPrivateStateAccess:false,authenticatedNansenProviderRequests:0,unauthenticatedDocumentationGets:0,accountRequests:0,browserRuntimeRequests:0,networkHold:true,scope:'ISOLATED_LOCAL_REGRESSION_RUN_ONLY_NOT_R3_DOCUMENTATION_TOTAL'});process.stdout.write('R3_COMPLETE_LOCAL_REGRESSION_PASS\n')
}
function replayOnly(){const c=privateContext(root),r=safeReplay(c);write(local,'EVIDENCE/PRESERVED_TRANSACTION_COMPATIBILITY_REPLAY.json',r);process.stdout.write(JSON.stringify({safelyAdmissible:r.safelyAdmissible,firstFailedStage:r.firstFailedStage,contextualTransfers:r.admittedContextualTransferCount,originalCounted:false,providerRequests:0,credentialAccess:false})+'\n')}
let executionPhase='LOCAL_GATES'
async function execute(){
 localGate();reviewGate(preReview);const starting=snapshot();executionPhase='DOCUMENT_FRESHNESS';const docs=await freshness(root);executionPhase='PRIVATE_ADMISSION';const context=admitPreLive(root,docs),r=safeReplay(context);if(!r.safelyAdmissible||!r.admittedContextualTransferCount)throw new Error('R3_PRESERVED_REPLAY_BLOCKER');if(identity(starting)!==identity(snapshot()))throw new Error('R3_SOURCE_CHANGED_BEFORE_CREDENTIAL');recheckFresh(root,docs)
 const envelope=resumeEnvelope(context,starting.candidate,starting.implementationSha256,docs.index);write(local,'EXECUTION/T1_B1_R3_RESUME_ENVELOPE.json',envelope,true);write(local,'EVIDENCE/PRESERVED_TRANSACTION_COMPATIBILITY_REPLAY.json',r)
 authorizeContext(context,{localPass:true,reviewPass:true,docsPass:true,replayPass:true});executionPhase='RESUME_LOCK';const store=new ResumeStore(context,envelope);recheckFresh(root,docs);if(identity(starting)!==identity(snapshot()))throw new Error('R3_SOURCE_CHANGED_AFTER_LOCK');executionPhase='CREDENTIAL_RESOLUTION';const transport=liveTransport(context,store,{environmentCredential:()=>originalEnvironment.NANSEN_API_KEY}),controller=new AbortController(),cancel=()=>controller.abort();process.once('SIGINT',cancel);process.once('SIGTERM',cancel)
 executionPhase='EXECUTION';try{const result=await new Executor({context,store,transport,signal:controller.signal}).run();write(local,'EXECUTION_RECEIPT.json',{schemaVersion:'1.0.0',envelopeIdentity:envelope.hash,credentialResolvedAtRuntime:true,...result});process.stdout.write(JSON.stringify(result)+'\n')}finally{process.removeListener('SIGINT',cancel);process.removeListener('SIGTERM',cancel)}
 executionPhase='RECONCILIATION';reconcileLocal()
}
function reconciled(){const context=privateContext(root,{postLive:true}),envelope=read('EXECUTION/T1_B1_R3_RESUME_ENVELOPE.json'),{hash,...p}=envelope;if(identity(p)!==hash||envelope.implementationSha256!==digest(root)||envelope.compatibilityProfileIdentity!==context.profile.hash||envelope.planIdentity!==context.plans.plan.hash||envelope.reserveIdentity!==context.plans.reserve.hash||envelope.priorLedgerSha256!==context.prior.bytesSha256)throw new Error('R3_EXECUTION_ENVELOPE_IDENTITY');git(root,'merge-base','--is-ancestor',envelope.candidate.commit,'HEAD');if(git(root,'rev-parse',envelope.candidate.commit+'^{tree}')!==envelope.candidate.tree)throw new Error('R3_EXECUTION_TREE_IDENTITY');const proof=reconcile(context,envelope),a=audit(context,proof),frontier=nextFrontier(context,proof);return {context,envelope,proof,a,frontier}}
function reconciledReports(){const {context:c,envelope,proof,a,frontier}=reconciled(),capturedDocs=readCapturedDocs(root),docs=capturedDocs.index,r=safeReplay(c),receipt=fs.existsSync(path.join(local,'EXECUTION_RECEIPT.json'))?read('EXECUTION_RECEIPT.json'):null,status=proof.report.clean&&proof.report.newCounted===4?'DELIVERED_PENDING_LEAD_REVIEW':'BLOCKED_WITH_EVIDENCE',readiness={schemaVersion:'1.0.0',status,authorizationId:AUTH,executionContractSha256:CONTRACT_SHA,compatibilityProfileIdentity:c.profile.hash,planIdentity:c.plans.plan.hash,envelopeIdentity:envelope.hash,...proof.report,executionReceipt:receipt,unauthenticatedDocumentationGets:docs.unauthenticatedDocumentationGets,authenticatedNansenProviderRequests:proof.report.newAttempts,accountRequests:0,browserRuntimeRequests:0,historicalCalls:0,nextFrontierCalls:0,creditUseIndeterminate:proof.report.unresolvedReservations>0,qualificationFloorClaimed:false,gameplayIntegrationClaimed:false,observedDriftNotice:c.profile.observedDriftNotice}
 const entries={'CONTRACTS/ADDRESS_TRANSACTIONS_OBSERVED_COMPATIBILITY_PROFILE.json':c.profile,'EXECUTION/T1_B1_R3_RESUME_ENVELOPE.json':envelope,'PLANS/T1_B1_R3_TRANSACTION_ONLY_PLAN.json':c.plans.plan,'PLANS/T1_B1_R3_RESERVE_PLAN.json':c.plans.reserve,'REPORTS/T1_B1_R3_EXECUTION_REPORT.json':readiness,'REPORTS/T1_B1_R3_RECONCILIATION_REPORT.json':{...proof.report,publicIndex:proof.publicIndex,normalizedResultIdentities:proof.projections.map(p=>({logicalId:p.logicalId,normalizedIdentity:identity(p.rows),resultCount:p.rows.length})),original2PublicCallIds:null},'REPORTS/T1_B1_R3_UTILITY_REPORT.json':{schemaVersion:'1.0.0',byRequest:a.records.map(r=>({logicalId:r.logicalId,question:r.investigativeQuestionId,lens:r.questionLens,purpose:r.purposeCode,consumerIds:r.consumerIds,qualificationValue:r.qualification_value,engineeringValue:r.engineering_value,gameplayConsumerValue:r.gameplay_consumer_value,documentationProvenanceValue:r.r3ContractReview.document_provenance_value,resultCount:r.admittedResultCount})),integrationAccepted:false},'REPORTS/T1_CAMPAIGN_STATE_REDACTED.json':{...proof.report,campaignId:c.bound.envelope.campaignId,originalRequestCount:15,historicalUnissuedHeld:9,originalConsumedNoncounted:2,remainingLiveAuthority:0,additionalBatchesIssued:0,originalUnattributedAccountWideChange:2547},'SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json':fs.readFileSync(path.join(root,'schemas/NANSEN_API_REQUEST_AUDIT.schema.json')),'EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':a,'EVIDENCE/PRESERVED_TRANSACTION_COMPATIBILITY_REPLAY.json':r,'EVIDENCE/COMPATIBILITY_CLAIM_BOUNDARY_MATRIX.json':claimMatrix,'EVIDENCE/LIVE_REQUEST_IDENTITY_MATRIX.json':{schemaVersion:'1.0.0',rows:c.plans.plan.requests.map(q=>({logicalId:q.logicalId,bodyHash:identity(q.body),originalRowIdentity:identity(q),profileIdentity:c.profile.hash,question:q.questionId,lens:q.lens,purpose:q.purpose,consumers:q.consumers,lineage:q.lineage,coverageKey:q.coverageKey,coverageCells:q.coverageCells,stopRule:q.stopRule,expectedCredits:q.expectedCredits,worstCaseCredits:q.worstCaseCredits}))},'EVIDENCE/ATTEMPT_CREDIT_COUNT_AND_PROVIDER_ID_RECONCILIATION.json':{...proof.report,priorProviderRequestIds:[null,null],priorProviderIdLimitation:'NOT_CAPTURED_BY_B1_TRANSPORT_V1',newProviderRequestIds:a.records.filter(r=>c.plans.plan.requests.some(q=>q.logicalId===r.logicalId)).flatMap(r=>r.attempts.map(t=>({logicalId:r.logicalId,attempt:t.attemptNumber,provider_request_id:t.provider_request_id,actualCredits:t.actualCredits,httpStatus:t.httpStatus}))),latestResponseRemaining:Math.min(627478,...[...proof.current.responses.values()].map(r=>r.remainingCredits).filter(Number.isSafeInteger)),historicalUnattributedDecrease:2547},'EVIDENCE/PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json':{...proof.report,publicIndex:proof.publicIndex},'OFFICIAL_DOCS/INDEX.json':docs}
 for(const row of docs.snapshots)if(!row.reusedR2)entries['OFFICIAL_DOCS/'+row.filename]=capturedDocs.bodies[row.name]
 if(frontier){entries['PLANS/T1_NEXT_FRONTIER_CANDIDATE_PLAN.json']=frontier.plan;entries['PLANS/T1_NEXT_FRONTIER_RESERVE_PLAN.json']=frontier.reserve;entries['PLANS/T1_NEXT_FRONTIER_POLICY.json']=frontier.policy;entries['EVIDENCE/NEXT_FRONTIER_UTILITY_AND_ISSUABILITY_REPORT.json']=frontier.report}
 return {entries,status,readiness,proof,frontier}
}
function reports(){
 const blockerFile=path.join(local,'R3_BLOCKER.json');if(!fs.existsSync(blockerFile)){try{return reconciledReports()}catch(error){const code=/^R3_[A-Z0-9_]+$/.test(error.message)?error.message:'R3_DURABLE_STATE_UNRECONCILED';write(local,'R3_BLOCKER.json',{schemaVersion:'1.0.0',code,phase:'RECONCILIATION',knownNoNewProviderActivity:false,credentialResolvedAtRuntime:null,privateRepair:false},true)}}
 const context=publicContext(root),blocker=read('R3_BLOCKER.json'),maybe=n=>fs.existsSync(path.join(local,n))?read(n):null;let captured=null;try{captured=readCapturedDocs(root)}catch{}const result=blockedReports(context,blocker,{envelope:maybe('EXECUTION/T1_B1_R3_RESUME_ENVELOPE.json'),docs:captured?.index??null,replay:maybe('EVIDENCE/PRESERVED_TRANSACTION_COMPATIBILITY_REPLAY.json')});if(captured)for(const row of captured.index.snapshots)if(!row.reusedR2)result.entries['OFFICIAL_DOCS/'+row.filename]=captured.bodies[row.name];return result
}
async function safeExecute(){
 if(fs.existsSync(path.join(local,'R3_BLOCKER.json'))||fs.existsSync(path.join(local,'EXECUTION/T1_B1_R3_RESUME_ENVELOPE.json')))throw new Error('R3_INVOCATION_CONSUMED_NO_REENTRY')
 try{await execute()}catch(error){const code=/^R3_[A-Z0-9_]+$/.test(error.message)?error.message:'R3_EXECUTION_OR_DURABLE_STATE_FAILURE',phase=executionPhase,mayHaveIssued=['EXECUTION','RECONCILIATION'].includes(phase);write(local,'R3_BLOCKER.json',{schemaVersion:'1.0.0',code,phase,knownNoNewProviderActivity:!mayHaveIssued,credentialResolvedAtRuntime:phase==='CREDENTIAL_RESOLUTION'?null:mayHaveIssued?true:false,documentationGetsKnown:phase==='LOCAL_GATES'?0:null,privateRepair:false},true);reconcileLocal();throw new Error(code)}
}
function reconcileLocal(){const r=reports();for(const[n,v]of Object.entries(r.entries))if(!n.startsWith('OFFICIAL_DOCS/'))write(local,n,v);process.stdout.write(JSON.stringify({status:r.status,newCounted:r.proof.report.newCounted,newAttempts:r.proof.report.newAttempts,newCredits:r.proof.report.newKnownActualCredits,clean:r.proof.report.clean,nextFrontierProposals:r.frontier?.plan.requests.length??null})+'\n')}
async function deliver(){const v=localGate(),pre=reviewGate(preReview,{blockedAllowed:fs.existsSync(path.join(local,'R3_BLOCKER.json'))}),post=reviewGate(postReview,{blockedAllowed:fs.existsSync(path.join(local,'R3_BLOCKER.json'))}),candidate=cut(root),report=reports();if(fs.existsSync(path.join(parent,OUTPUT)))throw new Error('R3_EXISTING_ARCHIVE_PRESERVED');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'trace-b1-r3-delivery-')),delivery=path.join(temp,'delivery');fs.mkdirSync(delivery)
 try{const payload={},bindings=[],put=(n,x)=>{payload[n]=serialize(x);write(delivery,n,payload[n])},putLog=(n,b)=>{const s=sanitizeLog(b,root);if(!s.text.trim())throw new Error('R3_EMPTY_DELIVERY_LOG');put(n,s.text);bindings.push({file:n,sourceSha256:s.sourceSha256,sanitizedSha256:s.sanitizedSha256,otherPathRedactions:s.otherPathRedactions})};for(const[n,x]of Object.entries(report.entries))put(n,x)
 put('README.md','# TRACE//ESCAPE B1-R3\n\n'+report.status+'. Exact four-transaction-only Lead compatibility resume; historical and beta families parked. Count only durable schema/contextual-time/projection/audit/accounting successes. Optional enrichment nulls contradict captured OpenAPI and are omitted, never zero-imputed. Unzoned timestamps are contextual only; no invented UTC, negative evidence, cutoff completeness or exact proof. Powered by Nansen API. Original2 remain immutable noncounted. No historical, account, Alchemy, next-frontier or runtime browser provider calls. Stop for Lead review; no floor, final qualification, product/art/narrative/Mission02/hosting/release acceptance.\n')
 put('DELIVERY_MANIFEST.json',{...report.readiness,candidate,implementationSha256:digest(root),reviewedR2ArchiveSha256:ARCHIVE_SHA,privateBytesPackaged:false,privatePathsPackaged:false,credentialsPackaged:false,assetLanePackaged:false})
 put('SOURCE_INSTALL/EXECUTION_CONTRACT_INSTALLATION_REPORT.json',{schemaVersion:'1.0.0',contractSha256:CONTRACT_SHA,priorAcceptedCommit:BASE,priorAcceptedTree:TREE,priorAcceptedArchiveSha256:ARCHIVE_SHA,unchangedFoundationFiles:62,additiveFiles:1,activeSourceManifestSha256:sha(fs.readFileSync(path.join(root,'docs/source/ACTIVE_B1_R3_SOURCE_MANIFEST.sha256')))})
 put('SOURCE_INSTALL/ACTIVE_SOURCE_MANIFEST.sha256',fs.readFileSync(path.join(root,'docs/source/ACTIVE_B1_R3_SOURCE_MANIFEST.sha256')))
 put('EVIDENCE/BUGBOT_PRELIVE_REVIEW.json',pre);put('EVIDENCE/BUGBOT_POSTLIVE_REVIEW.json',post);put('EVIDENCE/REVIEW_FINDINGS_RESOLUTIONS.json',{schemaVersion:'1.0.0',prelive:pre,postlive:post,unresolvedAcceptedP0P1:0})
 put('EVIDENCE/KNOWN_LIMITATIONS.md','# Bounded compatibility\n\nLead-owned client compatibility is not official null or timezone semantics. Contextual activity is not an exact proof, completeness, negative-evidence or causation claim. Exact time can only join accepted Euler truth by matching transaction hash/components. Raw timestamps and labels remain private. Original2 failures cannot count or be reissued. Historical/beta families stay parked. The old2547 account-wide decrease remains unattributed; any additional response-balance drift is account-wide, not attributed to this campaign. Exact provider response request IDs are required for every new counted call. Qualification successes are not gameplay integration acceptance or the1024 floor. Next frontier, if present, is candidate-only and unissued.\n\nDocumentation GETs, authenticated provider starts, account requests and browser-runtime requests are reported separately; isolated regression-run zeros do not describe documentation totals. Both dedicated reviews bind the same implementation digest and included ancestor commit/tree. Supplier logs are sanitized; governed Git/source literals remain unchanged.\n')
 for(const n of LOCAL_SUITES)putLog('VERIFICATION/'+n+'.log',fs.readFileSync(path.join(local,n+'.log')))
 putLog('VERIFICATION/live-reconciliation-evidence.log','PASS exact accepted R2 archive and nine pinned members;63 additive source files.\nPASS exact four original frozen plan identities / compatibility '+report.readiness.compatibilityProfileIdentity+' / plan '+report.readiness.planIdentity+' / envelope '+report.readiness.envelopeIdentity+'.\nPASS durable reconciliation disposition (PASS only when clean=true); original accepted R2 prefix identity4659; ledger '+report.proof.report.ledgerSha256+'.\nRECONCILIATION '+JSON.stringify(report.proof.report)+'\nDOCUMENTATION '+JSON.stringify({unauthenticatedDocumentationGets:report.readiness.unauthenticatedDocumentationGets,authenticatedNansenProviderRequests:report.readiness.authenticatedNansenProviderRequests,accountRequests:0,browserRuntimeRequests:0})+'\n')
 const bundle=path.join(delivery,'GIT/trace-escape-complete.bundle');fs.mkdirSync(path.dirname(bundle));await run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD']);const bundleLog=await run('git',['bundle','verify',bundle]),clone=path.join(temp,'clone');await run('git',['clone','--quiet',bundle,clone]);const cg=(...args)=>execFileSync('git',args,{cwd:clone,env:childEnv,encoding:'utf8'}).trimEnd();if(cg('rev-parse','HEAD')!==candidate.commit||cg('rev-parse','HEAD^{tree}')!==candidate.tree)throw new Error('R3_BUNDLE_CLONE_IDENTITY');const fsck=await run('git',['fsck','--full','--strict'],clone);putLog('VERIFICATION/bundle-clone-fsck.log',bundleLog+'\nclone '+candidate.commit+' / '+candidate.tree+'; fsck exit0 '+(fsck.trim()||'no diagnostics')+'\n');put('GIT/trace-escape-complete.bundle',fs.readFileSync(bundle));put('SOURCE_DIFF.patch',execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:root,env:childEnv,maxBuffer:64000000}));fs.cpSync(path.join(root,'dist'),path.join(clone,'dist'),{recursive:true});putLog('VERIFICATION/fresh-clone-source-build-secret.log',await run('node',[path.join(root,'scripts/scan-prohibitions.mjs'),clone]));putLog('VERIFICATION/fresh-clone-history-secret.log',await run('node',['scripts/verify-git-secret-history.mjs'],clone));putLog('VERIFICATION/redacted-delivery-secret.log',await run('node',[path.join(root,'scripts/scan-prohibitions.mjs'),delivery]));const {credentialAccess,actualPrivateStateAccess,networkHold,...localVerification}=v;put('EVIDENCE/VERIFICATION_SUMMARY.json',{...localVerification,localCredentialAccess:credentialAccess,localActualPrivateStateAccess:actualPrivateStateAccess,localNetworkHold:networkHold,actualPrivateStateAccess:report.proof.report.clean?true:null,credentialResolvedAtRuntime:report.readiness.executionReceipt?.credentialResolvedAtRuntime??null,scope:'FINAL_CANDIDATE_LOCAL_SUITES_PLUS_R3_DOCUMENTATION_AND_DURABLE_LIVE_RECONCILIATION',unauthenticatedDocumentationGets:report.readiness.unauthenticatedDocumentationGets,authenticatedNansenProviderRequests:report.readiness.authenticatedNansenProviderRequests,accountRequests:0,browserRuntimeRequests:0,localSuitesNetworkHold:true,privateWriteScope:report.proof.report.clean?'EXACT_AUTHORIZED_RESUME_LOCK_CHAIN_AND_MIRRORED_RAW_ONLY':'NOT_ASSERTED_WHEN_DURABLE_RECONCILIATION_UNESTABLISHED',credentialPackaged:false,bundleFreshCloneIdentityVerified:true,liveReconciliationIdentity:identity(report.proof.report),deliveryLogBindings:bindings})
 const scan=pathScan(payload);if(scan.status!=='PASS')throw new Error('R3_DELIVERY_ABSOLUTE_PATH_LEAK');put('EVIDENCE/VERIFICATION_SUMMARY.json',{...JSON.parse(payload['EVIDENCE/VERIFICATION_SUMMARY.json']),pathRedactionScan:scan})
 const allowed=new Set([...Object.keys(report.entries),'README.md','DELIVERY_MANIFEST.json','MANIFEST.sha256','GIT/trace-escape-complete.bundle','SOURCE_DIFF.patch','SOURCE_INSTALL/EXECUTION_CONTRACT_INSTALLATION_REPORT.json','SOURCE_INSTALL/ACTIVE_SOURCE_MANIFEST.sha256','EVIDENCE/BUGBOT_PRELIVE_REVIEW.json','EVIDENCE/BUGBOT_POSTLIVE_REVIEW.json','EVIDENCE/REVIEW_FINDINGS_RESOLUTIONS.json','EVIDENCE/KNOWN_LIMITATIONS.md','EVIDENCE/VERIFICATION_SUMMARY.json']);for(const f of files(delivery)){const n=path.relative(delivery,f);if(!allowed.has(n)&&!/^VERIFICATION\/[a-z-]+\.log$/.test(n))throw new Error('R3_PAYLOAD_INVENTORY')}
 put('MANIFEST.sha256',files(delivery).map(f=>sha(fs.readFileSync(f))+'  '+path.relative(delivery,f)).sort().join('\n')+'\n');if(identity(cut(root))!==identity(candidate)||identity(Object.entries(reports().entries).map(([n,x])=>[n,sha(serialize(x))]))!==identity(Object.entries(report.entries).map(([n,x])=>[n,sha(serialize(x))])))throw new Error('R3_FINAL_SOURCE_OR_PRIVATE_STATE_CHANGED');const names=files(delivery).map(f=>{fs.utimesSync(f,new Date('2000-01-01T00:00:00Z'),new Date('2000-01-01T00:00:00Z'));return path.relative(delivery,f)}).sort(),zip=path.join(temp,'delivery.zip'),rebuilt=path.join(temp,'rebuilt.zip');await run('zip',['-X','-q',zip,...names],delivery);await run('zip',['-X','-q',rebuilt,...names],delivery);if(sha(fs.readFileSync(zip))!==sha(fs.readFileSync(rebuilt)))throw new Error('R3_REBUILD_IDENTITY');await run('unzip',['-t',zip]);const extracted=path.join(temp,'extracted');fs.mkdirSync(extracted);await run('unzip',['-q',zip,'-d',extracted]);await run('sha256sum',['-c','MANIFEST.sha256'],extracted);const output=path.join(parent,OUTPUT);fs.copyFileSync(zip,output,fs.constants.COPYFILE_EXCL);process.stdout.write(JSON.stringify({status:report.status,archive:output,sha256:sha(fs.readFileSync(output)),newCounted:report.proof.report.newCounted,newAttempts:report.proof.report.newAttempts,newCredits:report.proof.report.newKnownActualCredits,nextFrontierProposed:report.frontier?.plan.requests.length??null})+'\n')
 }finally{fs.rmSync(temp,{recursive:true,force:true})}
}
async function main(){if(process.argv.length!==3)throw new Error('R3_UNSUPPORTED_MODE');switch(process.argv[2]){case'--prepare':prepare();break;case'--local':await verify();break;case'--replay':replayOnly();break;case'--execute':await safeExecute();break;case'--reconcile':reconcileLocal();break;case'--deliver':await deliver();break;default:throw new Error('R3_UNSUPPORTED_MODE')}}
main().catch(error=>{process.stderr.write((/^R3_[A-Z0-9_]+$/.test(error.message)?error.message:'R3_FAIL_CLOSED_UNCLASSIFIED')+'; no external retry, replacement, private repair or authority expansion.\n');process.exitCode=1})
