import fs from 'node:fs'
import path from 'node:path'
import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {sha} from '../nq5-s2/activity.mjs'
import * as seam from '../../src/investigation/corpus-seam/authority.mjs'
import {runAuthorityAdversarial} from './adversarial.mjs'
export const START='38c673f7d031e19d8bd8574658ef876109b6fa7c',TREE='febbb347c47be02cac9469953ac64fd6ab01bce8'
const read=n=>JSON.parse(fs.readFileSync(n)),out='artifacts/g6p-s3-r1/',put=(n,x)=>{fs.mkdirSync(path.dirname(out+n),{recursive:true});fs.writeFileSync(out+n,typeof x==='string'||Buffer.isBuffer(x)?x:JSON.stringify(x,null,2)+'\n')}
assert.equal(execFileSync('git',['rev-parse',START+'^{tree}'],{encoding:'utf8'}).trim(),TREE)
const finalPath='artifacts/g6p-s3/REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json',candidate=read(finalPath),fixture=read('artifacts/g6p-s3/REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json'),launch=read('artifacts/g6p-s3/REPORTS/LANE_C_LAUNCH_CONTRACT.json')
assert.ok(fs.readFileSync(finalPath).equals(execFileSync('git',['show',START+':'+finalPath])))
await seam.admitFrozenCorpusCandidate(candidate)
const preservationFiles=[...candidate.compatibility.preservedBytes.map(x=>x.file),finalPath,'artifacts/g6p-s3/REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json','artifacts/g6p-s3/REPORTS/LANE_C_LAUNCH_CONTRACT.json','scripts/nq5-s2/activity.mjs','scripts/nq5-s2/import.mjs','scripts/nq5-s2/schema.mjs',...fs.readdirSync('artifacts/g6p-s2-r1/REPORTS').map(n=>'artifacts/g6p-s2-r1/REPORTS/'+n)]
const files=preservationFiles.map(file=>{const b=fs.readFileSync(file);assert.ok(b.equals(execFileSync('git',['show',START+':'+file])));return {file,sha256:sha(b),bytes:b.length,byteIdenticalToReviewedStart:true}})
put('REPORTS/ACCEPTED_BYTE_IDENTITIES.json',{status:'PASS',reviewedStartCommit:START,reviewedStartTree:TREE,interfaceIdentity:seam.CORPUS_INTERFACE_IDENTITY,files,acceptedAccountingSemanticsUnchanged:true,unchangedEulerFiles:6})
put('REPORTS/AUTHORITY_RESEALED_CHECKS.json',await runAuthorityAdversarial(seam,candidate,fixture))
put('REPORTS/SEAM_INVENTORY.json',{status:'REMEDIATED_PENDING_MAIN_REVIEW',finding:'S3-R1-P1-01',interfaceIdentity:seam.CORPUS_INTERFACE_IDENTITY,core:'src/investigation/corpus-seam/authority.mjs',typedFacade:'src/investigation/corpus-seam/contracts.ts',declaration:'src/investigation/corpus-seam/authority.d.mts',fullCandidateAdmission:'admitFrozenCorpusCandidate',admittedValue:'Opaque private WeakMap-backed token; full JSON snapshot deeply frozen before member access; no caller-owned mutation or raw list authority.',canonicalRecords:'Exact pinned full-candidate SHA256 and exact concept/display/audit membership, plus nested coverage/consumer uniqueness and local seal.',subset:'Accepted display IDs selected only from admitted candidate; raw lists and forged/cloned/synthetic tokens reject.',synthetic:'Separate noncanonical nonhistorical nonproof admission/selection; cannot join canonical corpus.',displaySurfaces:['CASE','RESULTS','EXPLORE'],auditSurfaces:['SOURCE','LEDGER'],concepts:25,boundedNoMatch:7,dataCandidateChanged:false,interfaceFrozen:false,LaneCActive:false,gameplayIntegrated:false,runtimeProviderCalls:0})
put('REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json',fs.readFileSync(finalPath))
put('REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json',fs.readFileSync('artifacts/g6p-s3/REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json'))
put('REPORTS/LANE_C_LAUNCH_CONTRACT.json',fs.readFileSync('artifacts/g6p-s3/REPORTS/LANE_C_LAUNCH_CONTRACT.json'))
const lane='LANE_C_PREPARED_NOT_SENT/'
for(const n of ['TE_IFACE_CORPUS_FINAL_CANDIDATE.json','SYNTHETIC_SEMANTIC_FIXTURE.json','LANE_C_LAUNCH_CONTRACT.json'])put(lane+n,fs.readFileSync(out+'REPORTS/'+n))
for(const[n,p]of [['authority.mjs','src/investigation/corpus-seam/authority.mjs'],['authority.d.mts','src/investigation/corpus-seam/authority.d.mts'],['contracts.ts','src/investigation/corpus-seam/contracts.ts'],['RESEALED_COMPATIBILITY_CHECKS.mjs','scripts/nq5-s3-r1/adversarial.mjs'],['COMPATIBILITY_TEST.ts','tests/unit/s3-corpus-seam.test.ts'],['AUTHORITY_TEST.mjs','tests/unit/s3-r1-authority.test.mjs']])put(lane+n,fs.readFileSync(p))
for(const n of ['ORIENTATION_FIRST.txt','ACTIVATION_SECOND_BLOCKED.txt'])put(lane+n,fs.readFileSync('artifacts/g6p-s3/LANE_C_PREPARED_NOT_SENT/'+n,'utf8')+'\nS3-R1 corrected seam: accepted controller base remains 60c613d. Exact remediation start '+START+' /tree '+TREE+' is unpromoted. Outer delivery manifest binds the later exact remediation candidate. Complete-candidate admission at pinned '+seam.CORPUS_INTERFACE_IDENTITY+' is mechanical membership only, NOT a freeze receipt. Use admitted-candidate ID selection; never raw canonical records. Synthetic tokens are separate. Packet remains UNSENT; explicit later MAIN freeze/activation disposition required.\n')
put(lane+'00_READ_ME_FIRST.md','PREPARED_NOT_SENT. Run node VERIFY_LANE_C.mjs with only Node stdlib/native WebCrypto. It imports the actual shipped browser authority core, admits the full pinned candidate, verifies all nine synthetic roles and three legitimate subset modes, and executes every resealed rejection check independently of manifest content pinning. Typed facade/declarations and dependency-backed Vitest source snapshots are references for the enclosing exact candidate repository. No private source, provider, account, key or network access. Opaque admission does not freeze the interface or grant activation. Charter, narrow additive owned paths, prohibitions and lane-local KT are unchanged. Outer delivery manifest is definitive for exact later candidate commit/tree/parent; reviewed start remains unpromoted.\n')
const names=fs.readdirSync(out+lane).filter(n=>!['MANIFEST.sha256','VERIFY_LANE_C.mjs'].includes(n)).sort()
const hashes=Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(out+lane+n))]))
put(lane+'VERIFY_LANE_C.mjs',`import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';const root=path.dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex'),expected=${JSON.stringify(hashes)},names=fs.readdirSync(root).sort(),allowed=[...Object.keys(expected),'VERIFY_LANE_C.mjs','MANIFEST.sha256'].sort();if(JSON.stringify(names)!==JSON.stringify(allowed))throw Error('LANE_MEMBERS');const seen=new Set();for(const l of fs.readFileSync(path.join(root,'MANIFEST.sha256'),'utf8').trim().split('\\n')){const h=l.slice(0,64),n=l.slice(66),s=fs.lstatSync(path.join(root,n));if(!/^[a-f0-9]{64}$/.test(h)||l.slice(64,66)!=='  '||!allowed.includes(n)||n==='MANIFEST.sha256'||seen.has(n)||!s.isFile()||s.isSymbolicLink()||s.nlink!==1||sha(fs.readFileSync(path.join(root,n)))!==h)throw Error('LANE_HASH');seen.add(n)}if(seen.size!==allowed.length-1)throw Error('LANE_HASH_COUNT');const j=n=>JSON.parse(fs.readFileSync(path.join(root,n))),candidate=j('TE_IFACE_CORPUS_FINAL_CANDIDATE.json'),launch=j('LANE_C_LAUNCH_CONTRACT.json');for(const[n,h]of Object.entries(expected))if(n!=='TE_IFACE_CORPUS_FINAL_CANDIDATE.json'&&sha(fs.readFileSync(path.join(root,n)))!==h)throw Error('LANE_PINNED_CONTENT');const seam=await import('./authority.mjs'),{runAuthorityAdversarial}=await import('./RESEALED_COMPATIBILITY_CHECKS.mjs');await seam.admitFrozenCorpusCandidate(candidate);const checks=await runAuthorityAdversarial(seam,candidate,j('SYNTHETIC_SEMANTIC_FIXTURE.json'));for(const[n,h]of Object.entries(expected))if(sha(fs.readFileSync(path.join(root,n)))!==h)throw Error('LANE_PINNED_CONTENT');if(launch.status!=='PREPARED_NOT_SENT'||launch.interfaceFrozen!==false||launch.LaneCActive!==false||launch.packetsSent!==false||launch.interfaceIdentity!==seam.CORPUS_INTERFACE_IDENTITY)throw Error('LANE_AUTHORITY');console.log(JSON.stringify({status:'PASS_PREPARATION_ONLY',pinnedFullCandidateAdmission:true,resealedFalseSuccessRejections:checks.resealedFalseSuccessRejections,legitimateSubsetModes:checks.legitimateSubsetModes,interfaceFrozen:false,LaneCActive:false,packetsSent:false}));\n`)
put(lane+'MANIFEST.sha256',[...names,'VERIFY_LANE_C.mjs'].sort().map(n=>sha(fs.readFileSync(out+lane+n))+'  '+n).join('\n')+'\n')
console.log(JSON.stringify({status:'REMEDIATED_PENDING_MAIN_REVIEW',interfaceIdentity:seam.CORPUS_INTERFACE_IDENTITY,dataCandidateChanged:false,resealedChecks:read(out+'REPORTS/AUTHORITY_RESEALED_CHECKS.json').resealedFalseSuccessRejections,packetsSent:false,LaneCActive:false}))
