import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {execFileSync} from 'node:child_process'
import {fileURLToPath} from 'node:url'
import {sha,identity} from '../nq5-s2/activity.mjs'
import {privatePathFindings} from '../nq5-s1/privacy.mjs'
import {hasSecretLikeValue} from '../secret-patterns.mjs'
import {OFF,admitEntries} from '../nq5-s1/core.mjs'
import {attachPublishedRegressionInputs} from '../nq5-s2/published-regression-inputs.mjs'
export const OUTPUT='TRACE_ESCAPE_G6P_NQ5_T1_S3_R1_FROZEN_CORPUS_AUTHORITY_BINDING_REMEDIATION_DELIVERY_v1.0.0.zip'
const BASE='38c673f7d031e19d8bd8574658ef876109b6fa7c',BASE_TREE='febbb347c47be02cac9469953ac64fd6ab01bce8',PARENT='38c673f7d031e19d8bd8574658ef876109b6fa7c',INPUT_ZIP_SHA='c9266029f32eebe47f1317357fb5d020753951e5af97ec92414dcca0e1ed7ace'
const root=process.cwd(),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'s2-delivery-')),dir=path.join(tmp,'package'),fresh=path.join(tmp,'reconstructed'),objectRoot=path.join(tmp,'pack-audit')
const env={PATH:process.env.PATH,LANG:'C.UTF-8',TZ:'UTC',TMPDIR:os.tmpdir(),NODE_OPTIONS:'--require '+path.join(root,'scripts/nq5-r2/hold.cjs'),CI:'1',NO_COLOR:'1',GIT_TERMINAL_PROMPT:'0',GIT_CONFIG_NOSYSTEM:'1'}
const run=(cmd,args,cwd=root)=>{try{return execFileSync(cmd,args,{cwd,env,maxBuffer:128000000,stdio:['pipe','pipe','pipe']}).toString()}catch(e){const d=path.join(root,'artifacts/g6p-s3-r1/LOGS');fs.mkdirSync(d,{recursive:true});let i=1;while(fs.existsSync(path.join(d,'package-stopped-'+i+'.log')))i++;fs.writeFileSync(path.join(d,'package-stopped-'+i+'.log'),sanitize((e.stdout||'').toString()+(e.stderr||'').toString())+'\nEXIT_CODE='+e.status+'\n');throw Error('S3_PACKAGE_STOPPED_'+cmd)}} ,git=(...a)=>run('git',a).trim()
const sanitize=t=>t.split(root).join('[CONTROLLER_ROOT]').split(tmp).join('[FRESH_VERIFICATION_ROOT]').split(os.tmpdir()).join('[LOCAL_VERIFICATION_ROOT]').replace(/\u001b\[[0-9;]*m/g,'')
fs.mkdirSync(dir)
const candidate={commit:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),parent:git('rev-parse','HEAD^')}
if(candidate.commit===PARENT||git('rev-parse',BASE+'^{tree}')!==BASE_TREE)throw Error('S3_ANCESTRY_IDENTITY');run('git',['merge-base','--is-ancestor',BASE,candidate.commit]);run('git',['merge-base','--is-ancestor',PARENT,candidate.commit])
if(git('rev-list','--merges',BASE+'..'+candidate.commit))throw Error('S3_R1_MERGE_FORBIDDEN')
if(git('diff','--name-only','HEAD','--','.',':(exclude)AGENTS.md',':(exclude).cursor',':(exclude)ART_PRODUCTION'))throw Error('S3_DIRTY_GOVERNED_TRACKED')
const changed=git('diff','--name-only',BASE,candidate.commit).split('\n')
if(changed.some(n=>n==='AGENTS.md'||n.startsWith('.cursor/')||n.startsWith('ART_PRODUCTION/')||n.startsWith('public/')||/NANSEN_API_KEY\.txt/i.test(n)))throw Error('S3_CHANGED_PATH_SCOPE')
const ownedFiles=new Set(['scripts/s3-r1-browser.config.mjs','tests/unit/s3-r1-authority.test.mjs','tests/e2e/s3-r1-authority.spec.ts','docs/PROJECT_STATUS.yaml','docs/PROJECT_SCHEDULE.json','tests/unit/project-clock.test.mjs','docs/G6P_NQ5_T1_S3_R1_NOTES_FOR_LEAD.md','scripts/s3-browser.config.mjs','scripts/s3-current-browser.config.mjs','tests/unit/s3-corpus-seam.test.ts','tests/unit/s3-lane-b-contract.test.ts','tests/unit/s3-lane-b-query.test.ts','tests/e2e/s3-guard.spec.ts','tests/e2e/s3-semantics.spec.ts'])
if(changed.some(n=>!ownedFiles.has(n)&&!['docs/source/execution-s3-r1/','scripts/nq5-s3-r1/','artifacts/g6p-s3-r1/','src/investigation/corpus-seam/'].some(p=>n.startsWith(p))))throw Error('S3_CLOSED_CHANGED_PATH_SCOPE')
const payload=new Map(),put=(n,b)=>{if(!n||n.startsWith('/')||n.split('/').includes('..')||n.includes('\\')||payload.has(n))throw Error('S3_PACKAGE_PATH');b=Buffer.isBuffer(b)?b:Buffer.from(typeof b==='string'?b:JSON.stringify(b,null,2)+'\n');fs.mkdirSync(path.dirname(path.join(dir,n)),{recursive:true});fs.writeFileSync(path.join(dir,n),b,{flag:'wx'});payload.set(n,b)}
const log=(n,text)=>put('LOGS/'+n+'.log',sanitize(text))
const bundle=path.join(tmp,'incremental.bundle');run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD','^'+BASE])
const bytes=fs.readFileSync(bundle),boundary=bytes.indexOf(Buffer.from('\n\n'))
if(boundary<0)throw Error('S3_BUNDLE_HEADER');const header=bytes.subarray(0,boundary).toString()
if(!header.includes('-'+BASE+' ')||header.split('\n').filter(l=>l.startsWith('-')).length!==1)throw Error('S3_EXACT_BASE_PREREQUISITE')
fs.mkdirSync(objectRoot);run('git',['init','--quiet'],objectRoot);fs.mkdirSync(path.join(objectRoot,'.git/objects/info'),{recursive:true});fs.writeFileSync(path.join(objectRoot,'.git/objects/info/alternates'),path.join(root,'.git/objects')+'\n')
const indexed=execFileSync('git',['index-pack','--fix-thin','--stdin'],{cwd:objectRoot,env,input:bytes.subarray(boundary+2),maxBuffer:128000000}).toString().trim(),packHash=indexed.split(/\s+/).at(-1),packIndex=path.join(objectRoot,'.git/objects/pack','pack-'+packHash+'.idx')
const objects=run('git',['verify-pack','-v',packIndex],objectRoot).split('\n').filter(l=>/^[a-f0-9]{40} (?:blob|commit|tree|tag) /.test(l)).map(l=>{const[id,type]=l.split(' ');return{id,type}})
if(!objects.length)throw Error('S3_PACK_OBJECTS_EMPTY')
let scanned=0;for(const o of objects){if(!['blob','commit','tag'].includes(o.type))continue;const b=execFileSync('git',['cat-file',o.type,o.id],{cwd:objectRoot,env,maxBuffer:128000000});let text;try{text=new TextDecoder('utf8',{fatal:true}).decode(b)}catch{throw Error('S3_NON_TEXT_NEW_OBJECT')};if(privatePathFindings(text).length||hasSecretLikeValue(text))throw Error('S3_PACKAGED_GIT_OBJECT_PRIVACY');scanned++}
const objectReport={status:'PASS',bundleSha256:sha(bytes),prerequisiteCommit:BASE,objects:objects.length,textObjectsScanned:scanned,objectIds:objects,thinPackDependencyMaterialization:'Indexed with local existing base-object alternates; every object in the reconstructed incremental pack scanned, including any required delta bases.',privatePathFindings:0,secretFindings:0,completeInheritedHistoryPackaged:false,credentialFileOpened:false,networkRequests:0}
put('EVIDENCE/INCREMENTAL_GIT_OBJECT_PRIVACY.json',objectReport);put('GIT/trace-escape-incremental.bundle',bytes)
fs.mkdirSync(fresh);run('git',['init','--quiet'],fresh);fs.mkdirSync(path.join(fresh,'.git/objects/info'),{recursive:true});fs.writeFileSync(path.join(fresh,'.git/objects/info/alternates'),path.join(root,'.git/objects')+'\n')
const bv=run('git',['bundle','verify',bundle],fresh);run('git',['fetch','--quiet','--no-tags',bundle,'HEAD:refs/heads/candidate'],fresh);run('git',['symbolic-ref','HEAD','refs/heads/candidate'],fresh);run('git',['read-tree','HEAD'],fresh)
if(run('git',['rev-parse','HEAD'],fresh).trim()!==candidate.commit||run('git',['rev-parse','HEAD^{tree}'],fresh).trim()!==candidate.tree||run('git',['rev-parse','HEAD^'],fresh).trim()!==candidate.parent)throw Error('S3_RECONSTRUCTED_IDENTITY')
const names=run('git',['ls-files','-z','--','.',':(exclude).cursor',':(exclude)ART_PRODUCTION'],fresh).split('\0').filter(Boolean)
const modes=new Map(run('git',['ls-files','--stage','-z','--','.',':(exclude).cursor',':(exclude)ART_PRODUCTION'],fresh).split('\0').filter(Boolean).map(l=>[l.slice(l.indexOf('\t')+1),l.slice(0,6)]))
for(const n of names){if(n.startsWith('/')||n.split('/').includes('..')||!['100644','100755'].includes(modes.get(n)))throw Error('S3_FRESH_PATH_MODE');const b=execFileSync('git',['show','HEAD:'+n],{cwd:fresh,env,maxBuffer:128000000});fs.mkdirSync(path.dirname(path.join(fresh,n)),{recursive:true});fs.writeFileSync(path.join(fresh,n),b,{flag:'wx',mode:modes.get(n)==='100755'?0o755:0o644})}
fs.symlinkSync(path.join(root,'node_modules'),path.join(fresh,'node_modules'),'dir');fs.appendFileSync(path.join(fresh,'.git/info/exclude'),'\nnode_modules\n')
const fsck=run('git',['fsck','--full','--strict'],fresh)
put('EVIDENCE/PUBLISHED_REGRESSION_INPUT_BINDINGS.json',attachPublishedRegressionInputs(root,tmp,env))
const diff=execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:root,env,maxBuffer:128000000}),freshDiff=execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:fresh,env,maxBuffer:128000000});if(!diff.equals(freshDiff))throw Error('S3_EXACT_DIFF_RECONSTRUCTION');put('SOURCE_DIFF.patch',diff)
log('incremental-reconstruction',bv+fsck+'\nExact reviewed unpromoted S3 prerequisite, candidate/tree/parent, strict fsck, and identical base-to-candidate patch: PASS. Local object alternates used; no complete history copied into delivery.\n')
log('fresh-schema-boundaries',run('node',['scripts/nq5-s3-r1/verify.mjs'],fresh))
log('fresh-main-reproducer',run('node',['scripts/nq5-s3-r1/main-reproducer.mjs'],fresh));log('fresh-no-network',run('node',['scripts/nq5-s3-r1/no-network.mjs'],fresh));log('fresh-json-schemas',run('python3',['scripts/nq5-s3-r1/schema-check.py'],fresh))
const test=run('node',['node_modules/vitest/vitest.mjs','run','--maxWorkers=4'],fresh);log('fresh-broad-unit-acquisition',test)
const testCount=Number(test.match(/Tests\s+(\d+) passed/)?.[1]);if(testCount!==1498||/\d+ failed/.test(test))throw Error('S3_FRESH_BROAD_TESTS')
log('fresh-typecheck',run('npm',['run','typecheck'],fresh));log('fresh-build',run('npm',['run','build'],fresh));log('fresh-lint',run('npm',['run','lint'],fresh))
log('fresh-browser-boundary',run('node',['scripts/verify-browser-boundary.mjs'],fresh))
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)])
for(const n of ['ACCEPTED_BYTE_IDENTITIES.json.schema.json','TE_IFACE_CORPUS_FINAL_CANDIDATE.json.schema.json','SYNTHETIC_SEMANTIC_FIXTURE.json.schema.json','LANE_C_LAUNCH_CONTRACT.json.schema.json'])put('SCHEMAS/'+n,fs.readFileSync(path.join(root,'artifacts/g6p-s3/SCHEMAS',n)))
for(const n of walk(path.join(root,'artifacts/g6p-s3-r1')).sort()){const rel=path.relative(path.join(root,'artifacts/g6p-s3-r1'),n).split(path.sep).join('/');put(rel,fs.readFileSync(n))}
for(const n of walk(path.join(root,'docs/source/execution-s3-r1')).sort())put('SOURCE_INPUT/'+path.relative(path.join(root,'docs/source/execution-s3-r1'),n).split(path.sep).join('/'),fs.readFileSync(n))
put('EVIDENCE/NOTES_FOR_LEAD.md',fs.readFileSync(path.join(root,'docs/G6P_NQ5_T1_S3_R1_NOTES_FOR_LEAD.md')))
for(const n of changed.filter(n=>/^(src|scripts|tests)\//.test(n)))put('CONTROLLER_SEAM_AND_TESTS/'+n,fs.readFileSync(path.join(root,n)))
const readReport=n=>JSON.parse(payload.get('REPORTS/'+n)),final=readReport('TE_IFACE_CORPUS_FINAL_CANDIDATE.json'),launch=readReport('LANE_C_LAUNCH_CONTRACT.json')
const requireLog=(n,count)=>{const text=payload.get('LOGS/'+n+'.log')?.toString();if(!text||!text.includes(count+' passed')||!text.includes('EXIT_CODE=0')||/\d+ failed/.test(text))throw Error('S3_BROWSER_REQUIRED_'+n)}
requireLog('browser-current',34);requireLog('browser-fixes-corrected',3);requireLog('browser-s3',3);requireLog('browser-authority',1)
for(const n of ['REVIEW_1.json','REVIEW_2.json']){const x=readReport(n);if(x.status!=='PASS_CLOSED_TASK_OWNED_FINDINGS'||x.independent!==false)throw Error('S3_REVIEWS_REQUIRED');for(const f of x.implementationBindings)if(sha(fs.readFileSync(path.join(root,f.file)))!==f.sha256)throw Error('S3_REVIEW_STALE')}
put('EVIDENCE/VERIFICATION_SUMMARY.json',{status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',candidate,reviewedStart:{commit:BASE,tree:BASE_TREE},freshBroadUnitAcquisitionTests:testCount,currentBrowserTests:34,focusedS2BrowserTests:3,focusedS3BrowserTests:3,exactClipboardChecks:9,focusedCountsNotAddedToBroadTotal:true,schemas:4,semanticFalseSuccessRejections:54,authorityBrowserTests:1,actualMainReproducerRejections:9,packetResealedCandidateRejections:6,legitimateSubsetModes:3,unchangedProductionFiles:final.compatibility.preservedBytes.length,unchangedEulerFiles:6,interfaceIdentity:final.identity,interfaceFrozen:false,LaneCActive:false,packetsSent:false,networkRequests:0,credentialAccess:false,privateStateAccess:false,quotaClaimed:false,strictFsck:'PASS',exactDiffReproduced:true,incrementalGitPrivacy:'PASS',baseDependentRecovery:true,completeHistoryIncluded:false,twoReviews:'MAIN_OWNED_DISCLOSED_FALLBACK_NOT_INDEPENDENT_ACCEPTANCE',legacyBrowser:'Historical S2 28 pass /17 fail (11 retired journey plus 6 retired qualification labels). Current excludes capture.spec.ts, cold-open.spec.ts, g5-hero.spec.ts; not rerun or claimed passing.',authorities:OFF})
put('DELIVERY_MANIFEST.json',{schemaVersion:'1.0.0',status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',candidate,reviewedStartCommit:BASE,reviewedStartTree:BASE_TREE,incrementalBundlePrerequisite:BASE,incrementalBundleSha256:sha(bytes),sourceDiffSha256:sha(diff),sourceInputArchiveSha256:INPUT_ZIP_SHA,acceptedControllerBase:'60c613d292099edb464210b9f03e07d6415c220e',interface:final.interface,interfaceIdentity:final.identity,candidatePromoted:false,interfaceFrozen:false,LaneCActive:false,packetsSent:false,runtimeProviderCalls:0,quotaClaimed:false,completeHistoryIncluded:false,baseDependentRecovery:true,authorities:OFF})
put('EVIDENCE/PACKAGE_POLICY_CHECKS.json',{status:'PASS_CONDITIONAL_ON_CHECKED_EXECUTION',rejections:10,cases:['changed byte','extra member','missing member','symlink','resealed freeze','resealed activation','resealed display provider leakage','resealed audit stripping','resealed lane owned-path escalation','rehashed manifest identity substitution']})
put('00_READ_ME_FIRST.md','S3: DELIVERED_PENDING_MAIN_LEAD_REVIEW. Final-version corpus candidate is READY_FOR_MAIN_FREEZE, NOT frozen. Lane C preparation UNSENT/inactive. No external request, credentials or private bodies. Verify ZIP SHA then safely extract unique regular path-safe members and run node VERIFY_DELIVERY.mjs. Accepted controller base remains 60c613d292099edb464210b9f03e07d6415c220e (unpromoted). Incremental Git bundle requires exact reviewed unpromoted S3 commit '+BASE+' /tree '+BASE_TREE+' already available locally. No complete inherited history or nested historical ZIP ships. Verify/fetch into separate local candidate ref, compare candidate commit/tree/parent and byte-identical SOURCE_DIFF.patch, run strict fsck. Do not fetch history/dependencies online. Full rerun requires installed locked dependencies and eight hash-bound published local redacted regression inputs; binding evidence is included, not their ZIPs. SOURCE_INPUT is a selective read-only reference install, not a complete replay root for original validator; recovery binary and rejected overlays are excluded. The unchanged final candidate has 25 concepts, 25 exact mapped display members, 25 audit references and seven bounded no-matches. Admission pins its identity, not MAIN freeze. See EVIDENCE/NOTES_FOR_LEAD.md and direct logs for stopped attempts, historical baseline failures and limitations. LANE_C_PREPARED_NOT_SENT is a directory packet with its own validator/manifest; it proves preparation only and exact candidate is bound by this outer manifest. Stop for independent MAIN review and exact-interface freeze.\n')
const expectedHashes=Object.fromEntries([...payload].filter(([n])=>n!=='DELIVERY_MANIFEST.json').map(([n,b])=>[n,sha(b)]))
const allowed=[...payload.keys(),'VERIFY_DELIVERY.mjs','MANIFEST.sha256'].sort()
function verifyDelivery(){
 const fail=n=>{throw Error(n)},read=n=>fs.readFileSync(path.join(root,n)),json=n=>JSON.parse(read(n))
 const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const p=path.join(d,e.name),s=fs.lstatSync(p);if(s.isSymbolicLink()||(!s.isDirectory()&&(!s.isFile()||s.nlink!==1)))fail('S3_NONREGULAR');return s.isDirectory()?walk(p):[path.relative(root,p).split(path.sep).join('/')] }).sort()
 if(JSON.stringify(walk(root))!==JSON.stringify(allowed))fail('S3_EXACT_MEMBERS')
 const seen=new Set(),lines=read('MANIFEST.sha256').toString().trimEnd().split('\n');if(lines.length!==allowed.length-1)fail('S3_HASH_COUNT')
 for(const l of lines){const h=l.slice(0,64),n=l.slice(66);if(!/^[a-f0-9]{64}$/.test(h)||l.slice(64,66)!=='  '||!allowed.includes(n)||n==='MANIFEST.sha256'||seen.has(n)||sha(read(n))!==h)fail('S3_HASH');seen.add(n)}
 for(const[n,h]of Object.entries(expectedHashes))if(sha(read(n))!==h)fail('S3_PINNED_SEMANTIC_SOURCE_LANE_BINDING')
 const m=json('DELIVERY_MANIFEST.json'),v=json('EVIDENCE/VERIFICATION_SUMMARY.json'),f=json('REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json'),c=json('REPORTS/LANE_C_LAUNCH_CONTRACT.json'),g=json('EVIDENCE/INCREMENTAL_GIT_OBJECT_PRIVACY.json')
 if(m.acceptedControllerBase!=='60c613d292099edb464210b9f03e07d6415c220e'||m.status!=='DELIVERED_PENDING_MAIN_LEAD_REVIEW'||m.reviewedStartCommit!==base||m.reviewedStartTree!==baseTree||JSON.stringify(m.candidate)!==JSON.stringify(candidate)||JSON.stringify(v.candidate)!==JSON.stringify(candidate)||m.interfaceIdentity!==interfaceIdentity||m.interface!=='TE-IFACE-CORPUS@1.0.0'||m.candidatePromoted!==false||m.interfaceFrozen!==false||m.LaneCActive!==false||m.packetsSent!==false||m.runtimeProviderCalls!==0||m.quotaClaimed!==false||m.completeHistoryIncluded!==false||m.baseDependentRecovery!==true||m.incrementalBundlePrerequisite!==base||m.incrementalBundleSha256!==sha(read('GIT/trace-escape-incremental.bundle'))||m.sourceDiffSha256!==sha(read('SOURCE_DIFF.patch'))||m.sourceInputArchiveSha256!==inputZipSha)fail('S3_MANIFEST_BINDINGS')
 const b=read('GIT/trace-escape-incremental.bundle'),header=b.toString('utf8',0,b.indexOf(Buffer.from('\n\n')));if(!header.includes('-'+base+' ')||header.split('\n').filter(x=>x.startsWith('-')).length!==1||!header.includes(candidate.commit+' HEAD'))fail('S3_BUNDLE_PREREQUISITE')
 for(const x of [f,c,json('REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json')]){const{identity:h,...body}=x;if(identity(body)!==h)fail('S3_SEAL')}
 if(f.identity!==interfaceIdentity||f.concepts.length!==25||new Set(f.concepts.map(x=>x.id)).size!==25||f.displayRecords.length!==25||f.displayRecords.filter(x=>x.zeroResultClass).length!==7||f.interfaceFrozen!==false||f.LaneCActive!==false||f.runtimeProviderCalls!==0||c.interfaceIdentity!==interfaceIdentity||c.packetsSent!==false)fail('S3_NO_FALSE_SUCCESS')
 if(v.freshBroadUnitAcquisitionTests<1498||v.semanticFalseSuccessRejections!==54||v.authorityBrowserTests!==1||v.actualMainReproducerRejections!==9||v.currentBrowserTests!==34||v.focusedS2BrowserTests!==3||v.focusedS3BrowserTests!==3||v.strictFsck!=='PASS'||v.exactDiffReproduced!==true||v.networkRequests!==0||v.credentialAccess!==false||v.privateStateAccess!==false||g.status!=='PASS'||g.bundleSha256!==m.incrementalBundleSha256||g.prerequisiteCommit!==base||g.privatePathFindings!==0||g.secretFindings!==0)fail('S3_EVIDENCE')
 for(const n of allowed){if(n.startsWith('GIT/'))continue;const text=read(n).toString();if(privatePathFindings(text).length||hasSecretLikeValue(text))fail('S3_PRIVACY');if(['DELIVERY_MANIFEST.json','EVIDENCE/VERIFICATION_SUMMARY.json'].includes(n)){const x=JSON.parse(text);if(JSON.stringify(Object.keys(x.authorities).sort())!==JSON.stringify(Object.keys(off).sort())||Object.values(x.authorities).some(v=>v!==false))fail('S3_AUTHORITY')}}
 console.log(JSON.stringify({status:'PASS',members:allowed.length,hashes:seen.size,interfaceIdentity,interfaceFrozen:false,LaneCActive:false,baseDependentRecovery:true,candidate,terminalStatus:m.status}))
}
const secret=fs.readFileSync(path.join(root,'scripts/secret-patterns.mjs'),'utf8').replace('export function','function'),privacy=fs.readFileSync(path.join(root,'scripts/nq5-s1/privacy.mjs'),'utf8').split('export function privatePathFindings')[1].split('export function currentTreeScan')[0]
put('VERIFY_DELIVERY.mjs',"import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';const root=path.dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex'),canonical="+canonicalFunction()+",identity=x=>sha(canonical(x)),allowed="+JSON.stringify(allowed)+",base="+JSON.stringify(BASE)+",baseTree="+JSON.stringify(BASE_TREE)+",candidate="+JSON.stringify(candidate)+",inputZipSha="+JSON.stringify(INPUT_ZIP_SHA)+",interfaceIdentity="+JSON.stringify(final.identity)+",expectedHashes="+JSON.stringify(expectedHashes)+",off="+JSON.stringify(OFF)+";\n"+secret+'\nfunction privatePathFindings'+privacy+'\n('+verifyDelivery.toString()+')();\n')
for(const[n,b]of payload){if(n.startsWith('GIT/'))continue;if(privatePathFindings(b.toString()).length||hasSecretLikeValue(b.toString()))throw Error('S3_PACKAGE_PRIVACY_'+n)}
put('MANIFEST.sha256',[...payload].sort(([a],[b])=>a.localeCompare(b)).map(([n,b])=>sha(b)+'  '+n).join('\n')+'\n')
run('node',['VERIFY_DELIVERY.mjs'],dir)
let rejected=0
const rehash=()=>fs.writeFileSync(path.join(dir,'MANIFEST.sha256'),allowed.filter(n=>n!=='MANIFEST.sha256').map(n=>sha(fs.readFileSync(path.join(dir,n)))+'  '+n).join('\n')+'\n')
const reject=(name,apply,restore,expected)=>{const original=fs.readFileSync(path.join(dir,'MANIFEST.sha256'));try{apply();let stopped=false;try{execFileSync('node',['VERIFY_DELIVERY.mjs'],{cwd:dir,env,stdio:['pipe','pipe','pipe']})}catch(e){if(!String(e.stderr).includes(expected))throw Error('S3_WRONG_REJECTION_'+name);stopped=true}if(!stopped)throw Error('S3_FALSE_SUCCESS_'+name);rejected++}finally{restore();fs.writeFileSync(path.join(dir,'MANIFEST.sha256'),original)}}
const mutate=(n,change,expected)=>{const original=fs.readFileSync(path.join(dir,n));reject(n,()=>{const x=JSON.parse(original);change(x);if(x.identity){const{identity:h,...body}=x;x.identity=identity(body)}fs.writeFileSync(path.join(dir,n),JSON.stringify(x,null,2)+'\n');rehash()},()=>fs.writeFileSync(path.join(dir,n),original),expected)}
const logName='LOGS/browser-fixes-corrected.log',original=fs.readFileSync(path.join(dir,logName))
reject('byte',()=>fs.appendFileSync(path.join(dir,logName),'CORRUPTION'),()=>fs.writeFileSync(path.join(dir,logName),original),'S3_HASH')
reject('extra',()=>fs.writeFileSync(path.join(dir,'EXTRA.txt'),'SYNTHETIC'),()=>fs.unlinkSync(path.join(dir,'EXTRA.txt')),'S3_EXACT_MEMBERS')
reject('missing',()=>fs.unlinkSync(path.join(dir,logName)),()=>fs.writeFileSync(path.join(dir,logName),original),'S3_EXACT_MEMBERS')
reject('symlink',()=>{fs.unlinkSync(path.join(dir,logName));fs.symlinkSync('synthetic-target',path.join(dir,logName))},()=>{fs.unlinkSync(path.join(dir,logName));fs.writeFileSync(path.join(dir,logName),original)},'S3_NONREGULAR')
mutate('REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json',x=>{x.interfaceFrozen=true},'S3_PINNED')
mutate('REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json',x=>{x.LaneCActive=true},'S3_PINNED')
mutate('REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json',x=>{x.displayRecords[0].endpoint='SYNTHETIC'},'S3_PINNED')
mutate('REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json',x=>{delete x.auditReferences[0].provenance},'S3_PINNED')
mutate('LANE_C_PREPARED_NOT_SENT/LANE_C_LAUNCH_CONTRACT.json',x=>{x.ownedPaths.push('src/investigation/')},'S3_PINNED')
mutate('DELIVERY_MANIFEST.json',x=>{x.interfaceIdentity='0'.repeat(64)},'S3_MANIFEST_BINDINGS')
if(rejected!==10)throw Error('S3_REJECTION_TOTAL');run('node',['VERIFY_DELIVERY.mjs'],dir)
for(const n of allowed)fs.utimesSync(path.join(dir,n),new Date('2000-01-01Z'),new Date('2000-01-01Z'))
const zip=path.join(tmp,'delivery.zip'),repeat=path.join(tmp,'repeat.zip');run('zip',['-X','-q',zip,...allowed],dir);run('zip',['-X','-q',repeat,...allowed],dir);if(sha(fs.readFileSync(zip))!==sha(fs.readFileSync(repeat)))throw Error('S3_ZIP_DETERMINISM')
const metadata="import zipfile,stat,json,sys\nwith zipfile.ZipFile(sys.argv[1]) as z:\n print(json.dumps([{'name':i.filename,'type':'regular' if not i.is_dir() and stat.S_IFMT(i.external_attr>>16) in (0,stat.S_IFREG) else 'nonregular'} for i in z.infolist()]))"
admitEntries(JSON.parse(run('python3',['-c',metadata,zip])),allowed);const extracted=path.join(tmp,'extracted');fs.mkdirSync(extracted);run('unzip',['-q',zip,'-d',extracted]);const verification=run('node',['VERIFY_DELIVERY.mjs'],extracted)
run('node',['LANE_C_PREPARED_NOT_SENT/VERIFY_LANE_C.mjs'],extracted)
for(const n of allowed)if(!fs.readFileSync(path.join(dir,n)).equals(fs.readFileSync(path.join(extracted,n))))throw Error('S3_ROUNDTRIP')
if(git('rev-parse','HEAD')!==candidate.commit||git('rev-parse','HEAD^{tree}')!==candidate.tree)throw Error('S3_CANDIDATE_CHANGED')
const dest=path.join(path.dirname(root),OUTPUT);fs.copyFileSync(zip,dest,fs.constants.COPYFILE_EXCL)
console.log(JSON.stringify({status:'DELIVERED_PENDING_MAIN_LEAD_REVIEW',archive:dest,sha256:sha(fs.readFileSync(dest)),bytes:fs.statSync(dest).size,members:allowed.length,freshBroadUnitAcquisitionTests:testCount,currentBrowserTests:34,focusedS2BrowserTests:3,focusedS3BrowserTests:3,packageAdversarialRejections:rejected,candidate,interfaceIdentity:final.identity,interfaceFrozen:false,LaneCActive:false,networkRequests:0,finalArchiveVerification:JSON.parse(verification)},null,2))
function canonicalFunction(){return "(x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(canonical).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}')"}
