import fs from 'node:fs'
import path from 'node:path'
import {execFileSync} from 'node:child_process'
import {BASE,BASE_TREE,PRIOR_SHA,SOURCE_SHA,identity,sha,sealed,safeName,installTargets} from './core.mjs'
const root=process.cwd(),prior=process.argv[2],source=process.argv[3]
if(!prior||!source)throw Error('S1_EXACT_LOCAL_ARCHIVES_REQUIRED')
function zipCheck(file,expected,count){
 if(sha(fs.readFileSync(file))!==expected)throw Error('S1_ARCHIVE_IDENTITY')
 const code=`import zipfile,stat,hashlib,json,sys\nwith zipfile.ZipFile(sys.argv[1]) as z:\n ns=z.namelist();assert len(ns)==int(sys.argv[2]) and len(set(ns))==len(ns)\n for i in z.infolist():\n  assert not i.is_dir() and not i.filename.startswith('/') and '..' not in i.filename.split('/') and '\\\\' not in i.filename\n  assert stat.S_IFMT(i.external_attr>>16) in (0,stat.S_IFREG)\n seen=set()\n for l in z.read('MANIFEST.sha256').decode().splitlines():\n  h,n=l.split('  ',1);assert n in ns and n not in seen and n!='MANIFEST.sha256';seen.add(n);assert hashlib.sha256(z.read(n)).hexdigest()==h\n assert seen==set(ns)-{'MANIFEST.sha256'}\n print(json.dumps(ns))`
 const names=JSON.parse(execFileSync('python3',['-c',code,file,String(count)],{encoding:'utf8',maxBuffer:1000000}));if(names.some(n=>!safeName(n)))throw Error('S1_ARCHIVE_PATH');return names
}
const pn=zipCheck(prior,PRIOR_SHA,47),sn=zipCheck(source,SOURCE_SHA,17)
const zipRead=(f,n)=>execFileSync('unzip',['-p',f,n],{maxBuffer:64000000})
for(const [n,target]of sn.map((n,i)=>[n,installTargets(sn)[i]]))if(!zipRead(source,n).equals(fs.readFileSync(path.join(root,target))))throw Error('S1_SOURCE_INSTALL_BYTE_IDENTITY')
const p=n=>{if(!pn.includes(n))throw Error('S1_PUBLIC_MEMBER');return JSON.parse(zipRead(prior,n))}
const index=p('PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'),receipt=p('RECEIPTS/P2_LEAD_PARTIAL_ACCEPTANCE_RECEIPT.json'),matrix=p('EVIDENCE/COMPLETE_CANDIDATE_REJECTION_AND_RETIREMENT_MATRIX.json'),assessment=p('EVIDENCE/NO_CREDIBLE_SCALE_PATH_ASSESSMENT.json')
if(index.length!==25||identity(index)!=='867fa4dc45943d64737894f8289d06d1f4e7c9775daa12388df6d0a9657321b1')throw Error('S1_ACCEPTED_INDEX')
const {hash,...rp}=receipt;if(identity(rp)!==hash||hash!=='4e1d6f38d1fbb9cedc0bfd7ffd4532dfcf243af558bd3e0dde9d8afa4fd15e19')throw Error('S1_RECEIPT')
if(index.some(x=>x.lead_acceptance_status!=='ACCEPTED'||x.raw_payload_published||x.gameplay_integration_accepted))throw Error('S1_INDEX_AUTHORITY')
const git=(...a)=>execFileSync('git',a,{encoding:'utf8'}).trim();if(git('rev-parse',BASE+'^{tree}')!==BASE_TREE||git('rev-parse',BASE+'^')!=='aa9f5c97433ae45f08c08995f09e9ab122f32b77')throw Error('S1_ACCEPTED_GIT')
if(sha(zipRead(prior,'SOURCE_DIFF.patch'))!=='9ab8eaea1b1e8476495a3d865340fb5dcc225b47c33613943586a62c4f7025d3')throw Error('S1_PRIOR_DIFF')
const pick=(x,keys)=>Object.fromEntries(keys.filter(k=>x[k]!==undefined).map(k=>[k,x[k]]))
const holds=[...receipt.historicalPermanentHolds,...receipt.newPermanentHolds].map(x=>pick(x,['logicalId','publicCallId','immutableTerminalIdentity','disposition','holdReason','priorEvidenceDominance']))
const unknown=matrix.all45Requests.filter(x=>x.leadReviewDisposition==='PROVIDER_RECEIPT_AND_CHARGE_INDETERMINATE').map(x=>({...pick(x,['logicalId','requestIdentity']),providerReceipt:'UNKNOWN',charge:'UNKNOWN',futureInventory:false}))
const retired=matrix.all45Requests.filter(x=>x.neverIssuedRetired).map(x=>({...pick(x,['logicalId','requestIdentity']),status:'RETIRED_NEVER_ISSUED',futureInventory:false}))
if(holds.length!==6||unknown.length!==14||retired.length!==21||assessment.independentlyJustifiedFutureInventory!==0)throw Error('S1_PUBLIC_COUNTS')
const preparedBytes=fs.readFileSync('docs/G6P_NQ5_T1_P2_PREPARED_PUBLIC_METADATA.json');if(sha(preparedBytes)!=='166e5d9a03fbdf121d8cd4c01d6e15f41b854184151a6dfe7e0e157c14ab3020')throw Error('S1_RETAINED_CONTRACT_METADATA')
const prepared=JSON.parse(preparedBytes),dir='public/scenarios/euler-2023-false-exit/',truthFiles=['scenario.json','evidence-graph.json','world.json','provenance.json','catalog.json','scenario.sha256'].map(n=>({file:dir+n,sha256:sha(fs.readFileSync(dir+n))})),graph=JSON.parse(fs.readFileSync(dir+'evidence-graph.json'))
if(truthFiles[1].sha256!=='765d408b7e4aa57a35e2f70d4d712e8b0187d11c3100e08cf35abe0028b324bc')throw Error('S1_EXACT_TRUTH')
const historical=matrix.historicalP3CandidateMatrix.rows.map(x=>({subject:x.subjectAddress||x.request?.subjectAddress,logicalId:x.request?.logicalId||null,question:x.request?.businessQuestion||null,historicalAdmitted:x.admitted,reason:x.rejectionCode,lineage:x.request?.lineage||x.lineage||[],futureAuthority:false})).map(x=>JSON.parse(JSON.stringify(x)))
const input=sealed({schemaVersion:'1.0.0',acceptedBase:{commit:BASE,tree:BASE_TREE,directParent:git('rev-parse',BASE+'^'),priorArchiveSha256:PRIOR_SHA,priorArchiveBytes:fs.statSync(prior).size,priorArchiveMembers:47,priorManifestEntries:46,publicIndexIdentity:identity(index),partialReceiptIdentity:hash,campaignId:receipt.campaignId},acceptedRows:index.map(x=>({...pick(x,['public_call_id','endpoint_family','business_question','consumer_ids','normalized_sha256','result_count','evidence_grade','temporal_class','coverage_scope','lead_acceptance_order']),acceptedRowIdentity:identity(x),futureInventory:false})),holds,unknownReservations:unknown,retiredRequests:retired,truth:{files:truthFiles,cutoffUtc:graph.cutoffUtc,entities:graph.entities,events:graph.events,relationships:graph.relationships,proofDependencies:graph.proofDependencies,firstFalsifier:graph.firstFalsifier,gaps:graph.gaps,evidence:graph.evidence.map(x=>pick(x,['id','grade','proofGrade','independenceGroup','derivedFromEvidenceIds','independentForProof','temporalClass','normalizedSha256','claim','transactionHash','facts','uncertainty']))},source:{archiveSha256:SOURCE_SHA,files:sn.map(n=>({file:'docs/source/v1.10.0/'+n,sha256:sha(zipRead(source,n))})),transientAuthority:'04_CURRENT_OPERATIONS.md',installedOnlyInCurrentEpoch:true},retainedContracts:{publicMetadataSha256:sha(preparedBytes),historicalOnly:true,semanticAbstractionIdentity:receipt.semanticAbstractionIdentity,admissionIdentities:prepared.plans.plan.admissionIdentities,policyIdentity:prepared.plans.policy.hash,requestProjectionIdentities:[...new Set(prepared.plans.plan.requests.map(x=>x.publicProjectionPolicyIdentity))].sort()},historicalReview:{rejectedPlanRequests:45,comparisonMatrixRows:matrix.historicalCandidateMatrix.rows.length,historicalNextInventory:matrix.historicalP3CandidateMatrix.nextInventory,currentJustifiedFutureInventory:assessment.independentlyJustifiedFutureInventory,nextPhaseRows:historical},counters:{httpStarts:47,observed2xx:33,supplierTerminals:31,formalLeadAccepted:25,held:6,knownCampaignCredits:37,retries:0,indeterminateStarts:14,unresolvedTerminals:0,neverIssuedRetired:21,acceptedPublicRows:25,pendingPublicRows:0,floorClaimed:false,gameplayIntegrationAccepted:false},accessBoundary:{onlyAcceptedPublishedEvidence:true,privateLedgerNotOpened:true,privateStoresNotOpened:true,outcomesNotInferred:true,credentialNotResolved:true,oldAccountAndReserveFieldsNotCopied:true}})
process.stdout.write(JSON.stringify(input,null,2)+'\n')
