import fs from 'node:fs'
import {OFF,STATUS,TERMINAL,RESEARCH_DISPOSITION,CONTRACT_SHA,identity,sha,sealed,checkSeal,falsifiable} from './core.mjs'
export const INPUT='docs/G6P_NQ5_T1_S1_PUBLIC_EVIDENCE_INPUT.json'
export const INPUT_ID='d26594de1e0eced7e1d5729cb10858077e46777ab87eefab4e3f2c0c4d191815'
export function readInput(){const x=JSON.parse(fs.readFileSync(INPUT));checkSeal(x);if(x.identity!==INPUT_ID)throw Error('S1_ACCEPTED_PUBLIC_INPUT_CHANGED');for(const f of [...x.source.files,...x.truth.files])if(sha(fs.readFileSync(f.file))!==f.sha256)throw Error('S1_GOVERNED_FILE_CHANGED');return x}
const delta=(consumer,behavior,tests)=>({consumer,behavior,before:'UNRESOLVED',tests})
const routeDelta=delta('RESEARCH_LEDGER.BOUNDED_ROUTE_CHECK','BOUNDED_ROUTE_CHECK',[{input:{match:true},expected:'CORROBORATED'},{input:{boundedEmpty:true},expected:'PROVIDER_NO_MATCH'}])
const stateDelta=delta('RESEARCH_LEDGER.INDEPENDENT_STATE_CHECK','INDEPENDENT_STATE_CHECK',[{input:{bucketExact:true,matches:true},expected:'CORROBORATED'},{input:{bucketExact:true,matches:false},expected:'CONTRADICTED'},{input:{bucketExact:false},expected:'UNRESOLVED'}])
const corpusDelta=delta('REGRESSION_CORPUS.INDEPENDENT_CONTROL','CORPUS_REGRESSION_CONTROL',[{input:{schemaCompatible:true},expected:'FIXTURE_SUPPORTED'},{input:{schemaCompatible:false},expected:'FIXTURE_HELD'}])
const ruleDelta=delta('MAIN_SCOPE_DECISION.REQUIREMENT_INTERPRETATION','RULE_SCOPE_DECISION',[{input:{corpusAllowed:true},expected:'CONSIDER_BOUNDED_CORPUS'},{input:{countMandatory:false},expected:'REQUEST_INTERNAL_POLICY_DECISION'},{input:{countMandatory:true,corpusAllowed:false},expected:'REMAIN_CLOSED'}])
function observation(n,question,prerequisites,reason,category,family,deltaValue=routeDelta,status=STATUS[4]){
 return {id:'S1.O'+String(n).padStart(3,'0'),questionId:'QUESTION.S1.'+String(n).padStart(3,'0'),question,acceptedEvidencePrerequisites:prerequisites,whyNotAnswerableLocally:reason,prospectiveFamily:family,semanticRole:category,consumerDelta:deltaValue,deltaIsProspectiveNotRuntimeIntegrated:true,claimBoundary:'Bounded public-safe provider view or rule interpretation only; no identity, human control, intent, chain absence, completeness, exact-time promotion, or new Hero proof.',equivalenceKey:'S1.OBSERVATION.'+String(n).padStart(3,'0'),dominanceKeys:prerequisites,stopRule:'No issue in S1. For any later admitted observation stop after its smallest supported bundled query; ambiguous scope, semantic mismatch, redundancy or protected-history overlap holds it without replacement.',status,reviewDisposition:category,authorities:OFF}
}
export function registry(x){
 const proof=x.truth.firstFalsifier,idx=x.acceptedBase.publicIndexIdentity,hold=x.holds.filter(h=>h.priorEvidenceDominance),ret=x.retiredRequests.map(r=>r.logicalId)
 const a=[
 observation(1,'Does the transaction-derived early state supply another independent observation?',['EXACT_EARLY_NET','STATE_EARLY_ENGINE'],'Answer is local: same normalized identity and independence group; another rendering cannot add independent proof.','LOCALLY_DERIVABLE','tgm/transfers',stateDelta),
 observation(2,'Do the two accepted routes converge at the Receiving Vault?',['EXACT_MAIN_RECEIVER',proof],'Answer is local in accepted relationships and proof dependencies; do not recollect a solved exact question.','LOCALLY_DERIVABLE','tgm/transfers'),
 observation(3,'Can accepted chronology alone construct before-falsifier and after-falsifier teaching views?',[proof,idx],'Chronology and disclosure are local; contextual provider times do not replace accepted exact UTC. A new phase label is not a new provider observation.','LOCALLY_DERIVABLE','tgm/transfers'),
 ...hold.map((h,i)=>observation(4+i,'Does held subwindow '+h.publicCallId+' add evidence beyond its accepted encompassing zero?',[h.priorEvidenceDominance.logicalId,h.logicalId],'Local Lead receipt proves exact endpoint, filter and page match with encompassing accepted zero; reject narrower zero while retaining bounded no-match limits.','DOMINATED','tgm/transfers')),
 observation(7,'Would a new consumer suffix make an already accepted subject/window/direction view distinct?',[idx],'Provider evidence and behavior are unchanged. Renaming consumer or cell cannot close another unresolved question.','EQUIVALENT','tgm/transfers'),
 observation(8,'Should the three already accepted exact DAI hashes be reissued as separate reconciliation calls?',['EXACT_EARLY_NET','EXACT_MAIN_RECEIVER',proof],'Exact facts already local; even a genuinely missing reconciliation would bundle the supported hashes instead of fragmenting calls.','BUNDLED','tgm/transfers'),
 observation(9,'May the accepted infrastructure-risk contextual control seed route breadth?',['NQ5-000026',idx],'Local accepted claim boundary is nonrecursive. Fan-out is not an unsolved route observation or identity evidence.','HUB_SUPPRESSED','tgm/transfers'),
 observation(10,'Does the historical a0b3 IN phase proposal justify current future inventory?',['NQ5-000029','HISTORICAL_NEXT_PHASE_MATRIX',...ret.filter(r=>r==='6586eb9297d0664224df41264e31efd49e5f20350a48bb145564ad2d931594e7')],'Historical one-row nextInventory did not survive R1 request-specific review. Supporting call is now accepted, but summary counts do not expose new normalized transfer facts or an executed incremental comparison. The subject also overlaps a retired query; no replacement or phase narrowing to rescue it. Reconsideration needs separate accepted public facts and genuinely different behavior, not this proposal.','RETIRED_OVERLAP_AND_UNPROVEN_DELTA','tgm/transfers'),
 observation(11,'Can the missing POST_FALSIFIER acceptance cell justify a subject/phase/direction grid?',[idx,proof],'Missing acceptance is not an investigative observation. Phase coverage requirement alone cannot supply new evidence or independent consumer behavior.','PADDING','tgm/transfers'),
 observation(12,'Do additional token haystack pages improve the accepted aggregate filter demonstration?',['NQ5-000025',idx],'Page-1 aggregate role already exists; no accepted next-page question or minimal public consumer delta is registered. Do not use row volume as frontier authority.','PADDING','tgm/transfers'),
 observation(13,'Does adding another relationship family count without a missing relationship question?',[idx],'The retained Counterparties contract and existing controls do not establish a new question. New current controlling bytes are held; historical admission is not automatic re-admission.','PADDING','profiler/address/counterparties'),
 observation(14,'Can banter, visuals, marketing counts or archive density justify more provider calls?',[idx],'All presentation effects are local or optional and do not change an investigative consumer. Arthur binding is preserved, not used as acquisition purpose.','PADDING',null),
 observation(15,'Can fourteen unknown starts or six holds be converted into future inventory?',[idx,...x.unknownReservations.map(r=>r.logicalId)],'Outcome is not locally knowable and remains UNKNOWN; neither account movement nor inference, retry, reuse, replacement or reissue is admissible. This is protected accounting history, not another acquisition question.','PROTECTED_UNKNOWN_HISTORY',null),
 observation(16,'Can an independently sampled historical DAI state at First Engine test the transaction-derived state without pretending a bucket is an exact receipt?',['EXACT_EARLY_NET','STATE_EARLY_ENGINE','clean-early-engine-balance-sequence'],'Current evidence is transaction-derived, not an independent state sample. Parked Historical Balances requires explicit bucket and timestamp semantics, public redistribution and exact input compatibility; no contract is inferred.','INDEPENDENT_STATE','profiler/address/historical-balances',stateDelta,STATUS[1]),
 observation(17,'Can one separately admitted historical public-safe case supply an independent signed-flow or bounded-empty regression control absent from Euler, without another playable mission?',[idx,'ACCEPTED_REGRESSION_CONSUMER_SEMANTICS'],'No additional case truth, bounded window, qualified receipt lineage or nonduplicated control behavior is accepted. A case name alone is insufficient. Future gate must choose at most one case and one demonstrably missing behavior before any finite inventory.','REGRESSION_CONTROL','PLAN_SPECIFIC_FAMILY_NOT_YET_SELECTED',corpusDelta,STATUS[2]),
 observation(18,'Is 1,024 an external mandatory count, and are independently useful non-Hero corpus cases admissible for competition qualification?',['D014','R009','R018','06_COMPETITION_RELEASE_AND_SUBMISSION.md'],'Local source establishes an internal 1,024 floor, not an independently verified current external rule quotation or organizer interpretation. No external rules are fetched in S1; clarification cannot silently lower internal policy.','RULE_SCOPE_DECISION',null,ruleDelta,STATUS[3])
 ]
 if(a.length!==18||new Set(a.map(o=>o.id)).size!==18||a.some(o=>!falsifiable(o.consumerDelta)))throw Error('S1_REGISTRY')
 return a
}
export function bounds(observations){
 const counts={registeredObservations:observations.length,acceptedCurrentScope:0,rejected:0,locallyDerivable:0,dominated:0,equivalent:0,bundled:0,hubSuppressed:0,genuinelyUnresolved:0}
 for(const o of observations){if(o.status===STATUS[0])counts.acceptedCurrentScope++;else if(o.status===STATUS[4])counts.rejected++;else counts.genuinelyUnresolved++;const k={LOCALLY_DERIVABLE:'locallyDerivable',DOMINATED:'dominated',EQUIVALENT:'equivalent',BUNDLED:'bundled',HUB_SUPPRESSED:'hubSuppressed'}[o.reviewDisposition];if(k)counts[k]++}
 return {counts,conservativeAdditionalInventory:counts.acceptedCurrentScope,maximumDefensibleAdditionalInventory:counts.acceptedCurrentScope,theoreticalAllConceivableEulerUpperBound:null,theoreticalBoundStatus:'UNKNOWN_NOT_A_GLOBAL_EXHAUSTION_PROOF',expectedProviderSuccess:null,eventualLeadAcceptance:null,assumptions:['Closed audited domain is the accepted public question baseline plus these18 observations and historical comparison matrices, not all possible chain activity.','No private normalized tuples were inspected. Hashes, result counts and generated consumers cannot establish additional independently meaningful behavior.','Retained plan-specific contracts are historical; no current refresh, authority or missing-family admission occurred.','No held, unknown, retired, retry, replacement, durable reuse or raw hub fan-out contributes future inventory.','Maximum-defensible means currently evidenced, request-specific future work in this reviewed domain; it is not a numerical bound on every question someone might later discover.','Any new independent evidence or semantics changes the reviewed domain and requires a new bounded gate.'],categoryCountsAreNonAdditiveToRejected:true,requestInventoryIsNotProviderSuccess:true,providerSuccessIsNotLeadAcceptance:true}
}
export function options(){return [
 {id:'ONE_MISSING_FAMILY',productRole:'Research Ledger independent-state check; Euler remains the only Hero.',newAuthority:['MAIN exact family-research gate','Current public-safe schema and bucket/UTC interpretation','Explicit plan-specific redistribution and consumer acceptance'],sourceChanges:['03 policy only if semantics change','04 operations and12 integrity after independent acceptance'],prerequisites:['S1.O016','No negative-row publication','Independent historical state observation and bounded bucket provenance'],inventoryMechanism:'One named independent-state observation; bundle supported samples needed for that question. Stop when resolved or ambiguous; no address/time grid.',notPadding:'A real independent state sample could corroborate or contradict a transaction-derived view. Endpoint diversity itself adds nothing.',risks:['Bucket timestamps cannot become exact event times','Negative or unexplained rows held','Minimal attributed public projection only','Potential family pricing and redistribution unknown until separately authorized research'],engineeringBurden:'MEDIUM_BOUNDED_ONE_ADAPTER_AND_COMPATIBILITY_PROFILE',reviewBurden:'HIGH_SEMANTIC_AMBIGUITY_ONE_OBSERVATION',providerCost:'UNKNOWN_NO_QUOTE_OR_RESERVATION_IN_S1',schedule:'No demonstrated route to999. Historical ambiguity threatens fixed T1 due; do not open broad framework work.',rejectIf:['Semantics remain ambiguous','Observation locally derivable','Contract not publicly redistributable','Family selected to increase diversity or count']},
 {id:'BOUNDED_MULTI_CASE_CORPUS',productRole:'Case Corpus, Research Ledger, Call Atlas, provenance and nonduplicated regression/dead-end/control fixtures; no second playable mission.',newAuthority:['Principal and MAIN explicit corpus-scope decision','At most one additional case in first no-issue admission study','Case-specific accepted public truth and exact endpoint contracts','Independent observation and behavior-delta review before any subsequent plan'],sourceChanges:['02 boundaries for non-Hero corpus if admitted','03 qualification case-scope authority','05 requirement interpretation only by MAIN','04 and12 after acceptance'],prerequisites:['S1.O017','Current official redistribution and temporal rules later','Public receipts and bounded historical window','Existing stable regression consumer with a missing behavior'],inventoryMechanism:'Enumerate missing independent behaviors first; join each to one accepted case fact, minimal compatible query and stop rule; collapse local derivability, equivalent views, dominated windows, hash bundles and hubs. Report actual surviving count, even zero, before selecting another case.',notPadding:'A new case must exercise a previously unsupported response or investigative discrimination; a case name, extra addresses or copied consumer suffixes supply no utility.',risks:['Unaccepted incident identity or intent claims','Redistribution may differ by family','Corpus scale may bury exact Hero truth','Repeated control behaviors across cases may be equivalent','Costs and support rate unmeasured'],engineeringBurden:'HIGH_BOUNDED_FIRST_CASE_THEN_REDECIDE',reviewBurden:'HIGH_CASE_TRUTH_AND_PER_OBSERVATION_PROVENANCE',providerCost:'UNKNOWN_BEFORE_FINITE_INVENTORY_AND_PRICING',schedule:'Most plausible breadth mechanism if internal floor stands, but not yet credible for999 or fixed T1 dates. Preserve RED and fixed freeze; admit no automatic number of cases.',rejectIf:['No genuinely missing behavior','Names or grids drive count','Implicit Mission02 or foreground expansion','Finite independently useful inventory cannot be shown','Review or engineering displaces mandatory Hero/release path']},
 {id:'EXACT_RULE_CLARIFICATION',productRole:'Truthful MAIN scope and qualification decision; no player-facing changes.',newAuthority:['Principal/MAIN authorize one exact later rule-evidence gate','Any internal floor revision requires separate explicit Principal/MAIN decision'],sourceChanges:['No stable policy changes during S1','Later05/03 changes only if explicitly approved','04 and12 record reviewed disposition'],prerequisites:['S1.O018','Exact current official competition rule quotation, URL, retrieval date and version','Organizer written interpretation if text ambiguous','Explicit distinction between external rule and internal D014'],inventoryMechanism:'Rule clarification creates zero qualification requests. It determines whether multi-case research is appropriate, or whether an internal policy decision is needed.',notPadding:'It resolves a real acceptance-scope ambiguity without fabricating a single API success or lowering meaning standards.',risks:['Organizer clarification may arrive late or not resolve ambiguity','External permissiveness does not amend internal floor','Never claim rule compliance from chat or inherited local paraphrase'],engineeringBurden:'LOW_NO_ACQUISITION_ADAPTER',reviewBurden:'LOW_BOUNDED_AUTHORITY_AND_QUOTATION_REVIEW',providerCost:'ZERO_PROVIDER_REQUESTS_FOR_RULE_DECISION',schedule:'Smallest next gate under RED. No deadline or buffer reset. If unresolved, no speculative scale approval.',rejectIf:['Unsupported rule paraphrase','Silent internal-floor reduction','Treating clarification itself as acquisition success']},
 {id:'CLARIFICATION_THEN_BOUNDED_CORPUS',productRole:'One Euler Hero plus independently useful non-Hero evidence corpus, conditional on rules and explicit internal policy.',newAuthority:['EXACT_RULE_CLARIFICATION first','Explicit MAIN corpus decision only if appropriate','BOUNDED_MULTI_CASE_CORPUS no-issue first-case study','Optional ONE_MISSING_FAMILY only for an evidenced missing behavior, never as a prerequisite by default'],sourceChanges:['Only conditionally approved domain changes listed in preceding options','04 and12 each accepted transition'],prerequisites:['S1.O018 beforeS1.O017','Finite observation-driven first-case inventory','Current contract and pricing refresh only in a later explicitly authorized gate','Later independent acceptance and explicit live contract remain separate'],inventoryMechanism:'Serial decision dependencies, not a product of case×family×phase×direction. Add only observations that survive independent semantic review; no promised999.',notPadding:'Each dependency can fail with zero inventory and stop the strategy; no target shapes cases or requests.',risks:['Combined review and engineering exceeds remaining fixed schedule','Unknown privacy/public allowance','Unmeasured provider support and Lead acceptance'],engineeringBurden:'LOW_FIRST_DECISION_HIGH_CONDITIONAL_CORPUS',reviewBurden:'LOW_FIRST_GATE_HIGH_CONDITIONAL_CASE_REVIEW',providerCost:'UNKNOWN_CONDITIONAL_NOT_AUTHORIZED',schedule:'Preferred strategic sequence, not a delivery forecast. RED remains; current scope lacks a credible path to internal qualification floor.',rejectIf:['Any dependency skipped','Invented call/success forecast','Authority inferred from this recommendation','No finite credible path after first-case study']}
 ].map(x=>({...x,authorities:OFF}))}
export function derive(){
 const input=readInput(),rows=registry(input),upper=bounds(rows),common={schemaVersion:'1.0.0',gate:'G6P-NQ5-T1-S1',executionContractSha256:CONTRACT_SHA,publicInputIdentity:input.identity,authorities:OFF},make=(kind,body)=>sealed({...common,kind,...body})
 // Remove the captured seal before resealing the expanded baseline.
 const cleanInput=structuredClone(input);delete cleanInput.identity
 const b=make('ACCEPTED_EVIDENCE_AND_QUESTION_BASELINE',{...cleanInput,existingConsumers:[...new Set(input.acceptedRows.flatMap(x=>x.consumer_ids))].sort(),stableProspectiveConsumers:[routeDelta.consumer,stateDelta.consumer,corpusDelta.consumer,ruleDelta.consumer],locallyDerivableFacts:['STATE_EARLY_ENGINE shares normalized identity and independence group with EXACT_EARLY_NET.','Exact convergence receiver, amount and UTC are already in accepted Hero truth.','Before/after falsifier presentation can be derived from accepted chronology.','Contextual count and hash metadata do not expose all782 normalized transfer tuples or establish complete chain history.'],endpointSemantics:[{family:'tgm/transfers',status:'RETAINED_PLAN_SPECIFIC_ONLY',scope:'Ethereum, exact DAI, bounded dates and page1; exact hashes bundled; minimal contextual projection; no labels or unrestricted recursion.'},{family:'profiler/address/transactions',status:'BOUNDED_CONTROLS_ONLY_RECURSIVE_SATURATION_LOCAL',scope:'Signed provider flow and unzoned times preserved; no filter weakening.'},{family:'profiler/address/counterparties',status:'P1_RETAINED_CONDITIONAL_CURRENT_CONTROLLING_BYTES_HELD',scope:'Address input, group_by wallet, counts and admitted addresses only; no label/entity inference.'}],laneA:{disposition:'ACCEPTED_FOR_CONTROLLER_INTEGRATION_QUEUE',evidenceMode:'SOURCE04_ATTESTATION_ONLY_ARCHIVE_NOT_OPENED',archiveSha256:'ee19252a736ae96b213b9c878cb2e0c0b4bee7e9e1340ad9097b71a6e8c2cc63',bytes:344392,members:44,baseCommit:'a1bf6689b9ba6a3c7077869ee03be1926b2e1c41',candidateCommit:'f56e806e80b100245d7b5c4686786b477f2f98d8',candidateTree:'616f54cca2d30a54148d3f442840f8ff3694b48b',interface:'TE-IFACE-CONTENT@1.1.0',interfaceSha256:'7d682d883fc55b80ed3c5ea752ea942d94000942257dd93a3eddc22a66c36903',implementationSha256:'84a081161b8b3e147021ad497af0862eaf3d7fe80b92f79de8ebe57e7711b46b',contentSha256:'540623c9e7f973f0f1cfa4bd4aa5b27f5150247004a05b61ab3a8791b87e0a2e',runtimeWiringAccepted:false,finalDialogueAccepted:false,corpusBindingsAccepted:false,accessibilityIntegrationAccepted:false,journeysAccepted:false,publicName:'Arthur',internalIdentity:'archivist'}})
 const r=make('UNRESOLVED_OBSERVATION_REGISTRY',{baselineIdentity:b.identity,observations:rows})
 const u=make('CURRENT_EULER_REQUEST_SPACE_UPPER_BOUND',{baselineIdentity:b.identity,registryIdentity:r.identity,...upper,historicalAcceptedRequests:25,historicalHoldsExcluded:6,historicalUnknownExcluded:14,historicalRetiredExcluded:21,historicalOneNextProposalRejected:true,remaining999ReachableWithinReviewedCurrentScope:false,currentScopeCredibleScalePath:false,targetUsedOnlyForReportingAfterBound:true})
 const o=make('SCALE_PATH_OPTIONS_AND_DECISION',{registryIdentity:r.identity,options:options(),primary:'EXACT_RULE_CLARIFICATION',fallback:'BOUNDED_MULTI_CASE_CORPUS',conditionalSequence:'CLARIFICATION_THEN_BOUNDED_CORPUS',oneHeroPreserved:true,Mission02Deferred:true,scheduleHealth:'RED',noNewDeadlineForecast:true})
 const m=make('REQUEST_SPECIFIC_CANDIDATE_MATRIX',{registryIdentity:r.identity,boundsIdentity:u.identity,candidates:[],rejectedComparison:{historicalCartesianPlanRequests:45,historicalComparisonRows:421,historicalNextPhaseRows:6,historicalNextInventory:1,currentAcceptedInventory:0},inventoryIsNotFrozenPlan:true,livePlanCreated:false,reservationsCreated:0})
 const receipt=make('S1_DECISION_RECEIPT',{terminalStatus:TERMINAL,researchDisposition:RESEARCH_DISPOSITION,packagingBlocker:'Complete recoverable Git history contains inherited private absolute paths. Protected history is not rewritten, policy is not weakened, and the complete bundle is withheld from delivery pending explicit MAIN disposition.',mandatoryCompleteBundleIncluded:false,packagingContractFulfilled:false,baselineIdentity:b.identity,registryIdentity:r.identity,boundsIdentity:u.identity,optionsIdentity:o.identity,candidateMatrixIdentity:m.identity,defensibleAdditionalInventory:u.maximumDefensibleAdditionalInventory,globalTheoreticalUpperBound:null,primaryRecommendation:o.primary,fallback:o.fallback,formalLeadAcceptedStill:25,remainingFormalAcceptances:999,qualificationFloorClaimed:false,crediblePathToFloor:false,nextGateNotIssued:true,externalMessageSent:false,privateCampaignMutableStateNotAccessed:true,nextHumanDecision:'MAIN_EXPLICIT_HISTORY_PACKAGING_DISPOSITION',oneHeroPreserved:true,Mission02Deferred:true,scheduleHealth:'RED'})
 return Object.fromEntries([b,r,u,o,m,receipt].map(v=>[v.kind+'.json',v]))
}
export function schemaOf(x,key=''){
 if(key==='authorities')return {type:'object',additionalProperties:false,required:Object.keys(OFF),properties:Object.fromEntries(Object.keys(OFF).map(k=>[k,{const:false}]))}
 if(x===null)return {type:'null'}
 if(Array.isArray(x)){const shapes=[...new Map(x.map(v=>{const s=schemaOf(v);return[identity(s),s]})).values()];return {type:'array',items:shapes.length===0?false:shapes.length===1?shapes[0]:{anyOf:shapes}}}
 if(typeof x==='object')return {type:'object',additionalProperties:false,required:Object.keys(x),properties:Object.fromEntries(Object.entries(x).map(([k,v])=>[k,schemaOf(v,k)]))}
 if(key==='identity'||key==='sha256'||key.endsWith('Identity')&&/^[a-f0-9]{64}$/.test(x))return {type:'string',pattern:'^[a-f0-9]{64}$'}
 if(key==='status'&&STATUS.includes(x))return {enum:STATUS}
 if(key==='terminalStatus')return {enum:[RESEARCH_DISPOSITION,'CREDIBLE_REQUEST_SPECIFIC_PATH_WITHIN_CURRENT_ACCEPTED_SCOPE','BLOCKED_WITH_EVIDENCE']}
 if(typeof x==='number')return {type:Number.isInteger(x)?'integer':'number',minimum:0}
 return {type:typeof x,...(typeof x==='string'?{minLength:1}:{})}
}
if(process.argv[1]?.endsWith('/model.mjs')){const all=derive(),name=process.argv[2];if(name==='names')console.log(JSON.stringify(Object.keys(all)));else if(name?.startsWith('schema:'))console.log(JSON.stringify(schemaOf(all[name.slice(7)]),null,2));else if(all[name])console.log(JSON.stringify(all[name],null,2));else throw Error('S1_EXPLICIT_OUTPUT_REQUIRED')}
