import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {execFileSync} from 'node:child_process'
import {fileURLToPath} from 'node:url'
import {OFF,BASE,BASE_TREE,CONTRACT_SHA,TERMINAL,identity,sha,admitEntries} from './core.mjs'
import {derive} from './model.mjs'
import {currentTreeScan,historyPrivatePathScan,privatePathFindings} from './privacy.mjs'
import {hasSecretLikeValue} from '../secret-patterns.mjs'
export const OUTPUT='TRACE_ESCAPE_G6P_NQ5_T1_S1_REQUEST_SPECIFIC_SCALE_PATH_RESEARCH_AND_SCOPE_DECISION_DELIVERY_v1.0.0.zip'
const reportNames=['ACCEPTED_EVIDENCE_AND_QUESTION_BASELINE.json','UNRESOLVED_OBSERVATION_REGISTRY.json','CURRENT_EULER_REQUEST_SPACE_UPPER_BOUND.json','SCALE_PATH_OPTIONS_AND_DECISION.json','REQUEST_SPECIFIC_CANDIDATE_MATRIX.json','S1_DECISION_RECEIPT.json']
const suites=['source-manifest-validator','s1-schema-crosswalk','s1-adversarial','focused-qualification-regression','report-validation-regression','current-tree-boundary','history-secret-boundary','history-private-path-boundary','bundle-clone-fsck-diff']
export const ALLOW=[...reportNames.map(n=>'REPORTS/'+n),...reportNames.map(n=>'SCHEMAS/'+n+'.schema.json'),'README.md','CONTRACT/S1_EXECUTION_CONTRACT.txt','EVIDENCE/VERIFICATION_SUMMARY.json','EVIDENCE/MAIN_OWNED_REVIEW.json','EVIDENCE/NOTES_FOR_LEAD.md','S1_STRATEGIC_RECOMMENDATION.md','DELIVERY_MANIFEST.json','GIT/trace-escape-complete.bundle','SOURCE_DIFF.patch','VERIFY_DELIVERY.mjs','MANIFEST.sha256',...suites.map(n=>'LOGS/'+n+'.log')].filter(n=>TERMINAL!=='BLOCKED_WITH_EVIDENCE'||n!=='GIT/trace-escape-complete.bundle').sort()
function verifyDirectory(){
 const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const f=path.join(d,e.name),s=fs.lstatSync(f);if(s.isSymbolicLink())throw Error('S1_PACKAGE_LINK');if(s.isDirectory())return walk(f);if(!s.isFile()||s.nlink!==1)throw Error('S1_PACKAGE_REGULAR');return[path.relative(root,f)]}).sort()
 if(JSON.stringify(walk(root))!==JSON.stringify(allowed))throw Error('S1_PACKAGE_EXACT_ALLOWLIST')
 const read=n=>fs.readFileSync(path.join(root,n)),p=n=>JSON.parse(read(n)),lines=read('MANIFEST.sha256').toString().trimEnd().split('\n'),seen=new Set()
 if(lines.length!==allowed.length-1)throw Error('S1_PACKAGE_HASH_COUNT')
 for(const l of lines){const h=l.slice(0,64),n=l.slice(66);if(!/^[a-f0-9]{64}$/.test(h)||l.slice(64,66)!=='  '||!allowed.includes(n)||n==='MANIFEST.sha256'||seen.has(n)||hash(read(n))!==h)throw Error('S1_PACKAGE_HASH');seen.add(n)}
 const docs=names.map(n=>p('REPORTS/'+n)),by=Object.fromEntries(docs.map(d=>[d.kind,d]));for(const d of docs){const {identity:h,...payload}=d;if(h!==id(payload))throw Error('S1_DOCUMENT_SEAL')}
 const b=by.ACCEPTED_EVIDENCE_AND_QUESTION_BASELINE,r=by.UNRESOLVED_OBSERVATION_REGISTRY,u=by.CURRENT_EULER_REQUEST_SPACE_UPPER_BOUND,m=by.REQUEST_SPECIFIC_CANDIDATE_MATRIX,s=by.SCALE_PATH_OPTIONS_AND_DECISION,d=by.S1_DECISION_RECEIPT,manifest=p('DELIVERY_MANIFEST.json'),v=p('EVIDENCE/VERIFICATION_SUMMARY.json')
 if(b.acceptedBase.commit!==base||b.acceptedBase.tree!==baseTree||b.acceptedRows.length!==25||b.holds.length!==6||b.unknownReservations.length!==14||b.retiredRequests.length!==21||b.unknownReservations.some(x=>x.providerReceipt!=='UNKNOWN'||x.charge!=='UNKNOWN'))throw Error('S1_BASELINE')
 const actual={registeredObservations:r.observations.length,acceptedCurrentScope:r.observations.filter(o=>o.status==='SUPPORTABLE_WITH_CURRENT_SCOPE').length,rejected:r.observations.filter(o=>o.status==='REJECTED_DERIVABLE_OR_PADDING').length,genuinelyUnresolved:r.observations.filter(o=>!['SUPPORTABLE_WITH_CURRENT_SCOPE','REJECTED_DERIVABLE_OR_PADDING'].includes(o.status)).length}
 if(Object.entries(actual).some(([k,n])=>u.counts[k]!==n)||m.candidates.length!==actual.acceptedCurrentScope||u.maximumDefensibleAdditionalInventory!==m.candidates.length||d.defensibleAdditionalInventory!==m.candidates.length)throw Error('S1_BOUND_COUNTS')
 if(r.baselineIdentity!==b.identity||u.baselineIdentity!==b.identity||u.registryIdentity!==r.identity||m.registryIdentity!==r.identity||m.boundsIdentity!==u.identity||d.baselineIdentity!==b.identity||d.registryIdentity!==r.identity||d.boundsIdentity!==u.identity||d.optionsIdentity!==s.identity||d.candidateMatrixIdentity!==m.identity||d.terminalStatus!==terminal||u.theoreticalAllConceivableEulerUpperBound!==null||u.expectedProviderSuccess!==null||u.eventualLeadAcceptance!==null)throw Error('S1_CROSSWALKS')
 function visit(x){if(!x||typeof x!=='object')return;if(x.authorities&&id(x.authorities)!==id(off))throw Error('S1_AUTHORITY');Object.values(x).forEach(visit)}
 docs.forEach(visit);visit(manifest);visit(v)
 if(hash(read('CONTRACT/S1_EXECUTION_CONTRACT.txt'))!==contractHash||hash(read('SOURCE_DIFF.patch'))!==manifest.sourceDiffSha256||manifest.completeBundleIncluded!==false||manifest.bundleSha256!==null||allowed.includes('GIT/trace-escape-complete.bundle')||manifest.decisionReceiptIdentity!==d.identity||manifest.candidate.commit!==v.candidate.commit||manifest.candidate.tree!==v.candidate.tree)throw Error('S1_EXACT_BINDINGS')
 if(v.status!=='BLOCKED_WITH_EVIDENCE'||v.packagingContractFulfilled!==false||v.completeBundleWithheld!==true||v.historyPrivatePathScan.status!=='FAIL_INHERITED_PRIVATE_ABSOLUTE_PATHS'||v.freshCloneFsck!=='PASS'||v.diffReproduced!==true||v.currentGateExternalRequests!==0||v.privateStateAccess!==false||v.credentialAccess!==false||v.totalTests!==v.s1Tests+v.focusedTests+v.reportValidationTests)throw Error('S1_VERIFICATION_BINDINGS')
 console.log(JSON.stringify({status:'PASS',members:allowed.length,governedHashes:seen.size,terminalStatus:d.terminalStatus,futureInventory:m.candidates.length,formalLeadAccepted:25,totalTests:v.totalTests,allAuthoritiesFalse:true}))
}
export function verifier(){return "import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';const root=path.dirname(fileURLToPath(import.meta.url)),hash=x=>createHash('sha256').update(x).digest('hex'),canonical=x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(canonical).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}',id=x=>hash(Buffer.from(canonical(x))),allowed="+JSON.stringify(ALLOW)+",names="+JSON.stringify(reportNames)+",off="+JSON.stringify(OFF)+",base="+JSON.stringify(BASE)+",baseTree="+JSON.stringify(BASE_TREE)+",contractHash="+JSON.stringify(CONTRACT_SHA)+",terminal="+JSON.stringify(TERMINAL)+";\n("+verifyDirectory.toString()+")();\n"}
export async function packageDelivery(root){
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'s1-final-')),dir=path.join(tmp,'package'),clone=path.join(tmp,'clone'),bundle=path.join(tmp,'trace-escape-complete.bundle');fs.mkdirSync(dir)
 const hold=path.join(root,'scripts/nq5-r2/hold.cjs'),env={PATH:process.env.PATH,TMPDIR:os.tmpdir(),LANG:'C.UTF-8',TZ:'UTC',NODE_OPTIONS:'--require '+hold},run=(cmd,args,cwd=root)=>execFileSync(cmd,args,{cwd,env,maxBuffer:128000000}).toString(),git=(...a)=>run('git',a).trim()
 const candidate={commit:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),directParent:git('rev-parse','HEAD^')};if(candidate.directParent!==BASE)throw Error('S1_DIRECT_CHILD_REQUIRED')
 const changed=git('diff','--name-only',BASE,'HEAD').split('\n');if(changed.some(n=>!/^scripts\/nq5-s1\/|^artifacts\/g6p-s1\/|^docs\/G6P_NQ5_T1_S1_|^docs\/source\/(?:v1\.10\.0|execution-s1)\//.test(n)))throw Error('S1_CHANGED_PATH_SCOPE')
 const dirty=git('diff','--name-only','HEAD','--','.',':(exclude)AGENTS.md',':(exclude).cursor',':(exclude)ART_PRODUCTION');if(dirty)throw Error('S1_DIRTY_GOVERNED_TRACKED_SOURCE')
 const payload={},put=(n,b)=>{if(!ALLOW.includes(n)||payload[n])throw Error('S1_PACKAGE_NAME');const bytes=Buffer.isBuffer(b)?b:Buffer.from(typeof b==='string'?b:JSON.stringify(b,null,2)+'\n');fs.mkdirSync(path.dirname(path.join(dir,n)),{recursive:true});fs.writeFileSync(path.join(dir,n),bytes,{flag:'wx'});payload[n]=bytes},sanitize=t=>t.split(root).join('[CONTROLLER_ROOT]').split(tmp).join('[FRESH_VERIFICATION_ROOT]').replace(/file:\/\/\[([^\]]+)\]/g,'[$1]'),log=(n,t)=>put('LOGS/'+n+'.log',sanitize(t))
 run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD']);const bv=run('git',['bundle','verify',bundle]);run('git',['clone','--quiet',bundle,clone]);const fsck=run('git',['fsck','--full','--strict'],clone)
 if(run('git',['rev-parse','HEAD'],clone).trim()!==candidate.commit||run('git',['rev-parse','HEAD^{tree}'],clone).trim()!==candidate.tree)throw Error('S1_CLONE_IDENTITY')
 const diff=execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:root,env,maxBuffer:128000000}),freshDiff=execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:clone,env,maxBuffer:128000000});if(!diff.equals(freshDiff))throw Error('S1_DIFF_REPRODUCTION')
 log('bundle-clone-fsck-diff',bv+fsck+'\nFresh clone exact commit/tree, strict fsck exit0 and byte-identical source diff PASS.\n');if(ALLOW.includes('GIT/trace-escape-complete.bundle'))put('GIT/trace-escape-complete.bundle',fs.readFileSync(bundle));put('SOURCE_DIFF.patch',diff)
 const sourceDir=path.join(clone,'docs/source/v1.10.0');log('source-manifest-validator',run('sha256sum',['-c','MANIFEST.sha256'],sourceDir)+run('python3',['_TOOLS/VALIDATE_SOURCE_PACK.py'],sourceDir))
 log('s1-schema-crosswalk',run('node',['scripts/nq5-s1/verify.mjs'],clone))
 const tap=run('node',['--test','scripts/nq5-s1/test.mjs'],clone),s1Tests=Number(tap.match(/# tests (\d+)/)?.[1]);if(!s1Tests||!tap.includes('# fail 0'))throw Error('S1_TEST_TOTAL');log('s1-adversarial',tap)
 const deps=path.join(root,'node_modules');if(!fs.existsSync(deps))throw Error('S1_LOCAL_FOCUSED_DEPENDENCIES_ABSENT')
 fs.symlinkSync(deps,path.join(clone,'node_modules'),'dir');fs.appendFileSync(path.join(clone,'.git/info/exclude'),'\nnode_modules\n')
 const focus=run('node',['node_modules/vitest/vitest.mjs','run','tests/unit/nq5-p2-identity.test.mjs','tests/acquisition/evidence.test.ts','tests/unit/nq5-r2-secret-patterns.test.mjs','--reporter=json'],clone),fr=JSON.parse(focus),focusedTests=fr.numPassedTests;if(fr.success!==true||!Number.isInteger(focusedTests)||focusedTests<1||fr.numFailedTests!==0||fr.numTotalTests!==focusedTests)throw Error('S1_FOCUSED_TEST_TOTAL');log('focused-qualification-regression',JSON.stringify({status:'PASS',passedTests:focusedTests,failedTests:fr.numFailedTests,testFiles:fr.testResults.length,sourceReportSha256:sha(focus),suites:fr.testResults.map(x=>({name:path.relative(clone,x.name),status:x.status}))})+'\n')
 const report=run('python3',['scripts/test-nq5-report-validation.py'],clone),rr=JSON.parse(report),reportValidationTests=rr.case_count;if(rr.status!=='PASS'||!Number.isInteger(reportValidationTests)||reportValidationTests<1||rr.credential_resolution_attempted||rr.provider_calls_issued!==0)throw Error('S1_REPORT_REGRESSION');log('report-validation-regression',JSON.stringify({status:rr.status,syntheticTestOnly:rr.synthetic_test_only,cases:reportValidationTests,credentialResolution:false,providerRequests:0,resultLogSha256:sha(report)})+'\n')
 const ct=currentTreeScan(clone);log('current-tree-boundary',JSON.stringify(ct)+'\n');log('history-secret-boundary',run('node',['scripts/verify-git-secret-history.mjs'],clone));const hp=historyPrivatePathScan(clone);if(hp.status!=='FAIL_INHERITED_PRIVATE_ABSOLUTE_PATHS'||TERMINAL!=='BLOCKED_WITH_EVIDENCE')throw Error('S1_BLOCKER_NOT_REPRODUCED');log('history-private-path-boundary',JSON.stringify(hp)+'\n')
 for(const n of reportNames){put('REPORTS/'+n,fs.readFileSync(path.join(clone,'artifacts/g6p-s1/REPORTS',n)));put('SCHEMAS/'+n+'.schema.json',fs.readFileSync(path.join(clone,'artifacts/g6p-s1/SCHEMAS',n+'.schema.json')))}
 put('CONTRACT/S1_EXECUTION_CONTRACT.txt',fs.readFileSync(path.join(clone,'docs/source/execution-s1/S1_EXECUTION_CONTRACT.txt')));put('S1_STRATEGIC_RECOMMENDATION.md',fs.readFileSync(path.join(clone,'docs/G6P_NQ5_T1_S1_STRATEGIC_RECOMMENDATION.md')));put('EVIDENCE/NOTES_FOR_LEAD.md',fs.readFileSync(path.join(clone,'docs/G6P_NQ5_T1_S1_NOTES_FOR_LEAD.md')))
 const totalTests=s1Tests+focusedTests+reportValidationTests
 put('EVIDENCE/MAIN_OWNED_REVIEW.json',{schemaVersion:'1.0.0',reviewType:'MAIN_OWNED_NOT_INDEPENDENT_LEAD_ACCEPTANCE',candidate,disposition:'BLOCKED_REQUIRED_HISTORY_PACKAGING_DISPOSITION',reviewedLenses:['Exact archive/Git/source installation','Request-specific semantic utility and historical overlap','Strongest plausible count-shaped false success','Private state and public projection','Target-independent bounds and honest unknowns','Schedule and scope decisions','Lean delivery boundaries'],unresolvedAcceptedP0P1:1,blocker:'Inherited private absolute paths prevent mandatory complete bundle delivery under the current no-exception contract.',semanticLimitation:'No private normalized tuple replay; theoretical global Euler upper bound remains UNKNOWN. Reviewed registry is not an automated utility oracle.',materialStoppedAttempts:'See NOTES_FOR_LEAD; schema and fixture-classification stops retained.',authorities:OFF})
 put('EVIDENCE/VERIFICATION_SUMMARY.json',{schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',packagingContractFulfilled:false,completeBundleWithheld:true,focusedArchiveDependentSuite:'NOT_RUN_IN_FRESH_ROOT_REQUIRES_EXTERNAL_HISTORICAL_DELIVERY_FIXTURES_NOT_MOUNTED',candidate,freshRootNetworkGuard:'External fetch/HTTP/DNS/socket hold preloaded for all Node children; only local validators and Git tools run, no fetch/package installation.',s1Tests,focusedTests,reportValidationTests,totalTests,schemas:6,sourceMembers:17,sourceManifestEntries:16,stableFileIdentityChecks:3,freshCloneFsck:'PASS',completeBundleVerified:true,diffReproduced:true,sourceDiffSha256:sha(diff),currentTreeScan:ct,historyPrivatePathScan:hp,currentGateExternalRequests:0,privateStateAccess:false,credentialAccess:false,existingFocusedRegressionsOnly:true,noProviderSuccessForecast:true,allConceivableBoundUnknown:true,independentLeadReviewPending:true,authorities:OFF})
 put('DELIVERY_MANIFEST.json',{schemaVersion:'1.0.0',status:'BLOCKED_PENDING_EXPLICIT_MAIN_HISTORY_PACKAGING_DISPOSITION',completeBundleIncluded:false,packagingContractFulfilled:false,candidate,acceptedBaseCommit:BASE,acceptedBaseTree:BASE_TREE,executionContractSha256:CONTRACT_SHA,sourceDiffSha256:sha(diff),bundleSha256:null,decisionReceiptIdentity:derive()['S1_DECISION_RECEIPT.json'].identity,terminalStatus:TERMINAL,defensibleAdditionalInventory:0,formalLeadAccepted:25,totalTests,networkRequests:0,privateStateAccess:false,credentialAccess:false,rawBodiesPackaged:false,privateLedgerPackaged:false,sideLanePayloadsPackaged:false,authorities:OFF})
 put('README.md','# TRACE//ESCAPE — S1 blocked evidence package\n\n'+TERMINAL+'\n\nResearch disposition: CURRENT_SCOPE_INSUFFICIENT_BOUNDED_EXPANSION_DECISION_REQUIRED. Defensible additional inventory0 in the audited public-evidence domain; global theoretical bound UNKNOWN. Formal Lead accepted remains25. Primary research recommendation: exact rule clarification; conditional fallback is a one-additional-case no-issue corpus study preserving one Euler Hero.\n\nMANDATORY COMPLETE GIT BUNDLE WITHHELD. The accepted inherited history contains actual private absolute paths in old source, synthetic acquisition verification records and logs. The credential-file path is not the credential; no key file was opened or hashed. No private path strings or historical ledger bodies are copied into this package. The exact complete bundle was verified locally and used for fresh-clone/fsck checks, but is not delivered. No history rewrite or policy exception was assumed. This ZIP is blocked diagnostic evidence, NOT a fulfilled recovery/package contract or completed S1 gate.\n\nExtract safely and run node VERIFY_DELIVERY.mjs to verify the blocked package, hashes, identities, source diff and suppressed authorities. Current S1 code, tests and exact source installation are in SOURCE_DIFF.patch against accepted base47f0466, not a replacement for the withheld full recovery bundle. Reports, schemas, MAIN-owned notes and the strategic recommendation remain reviewable. No historical delivery ZIP, side-lane payload, raw provider body, private campaign state or credential ships. All network and live effects remain zero; no follow-on gate is issued. Powered by Nansen API.\n\nHUMAN ACTION: MAIN must decide whether unchanged accepted Git history may be included as an explicit packaging exception, or supply an approved sanitized recoverable history. No unilateral history rewrite is proposed or performed. Resolve that packaging decision before authorizing any next gate.\n')
 put('VERIFY_DELIVERY.mjs',verifier())
 for(const[n,b]of Object.entries(payload)){if(n.startsWith('GIT/')||n==='SOURCE_DIFF.patch')continue;const text=b.toString();if(hasSecretLikeValue(text)||privatePathFindings(text).length||/(?:\/(?:tmp|private|workspace|mnt|var\/tmp)\/[A-Za-z0-9._-]+|[A-Za-z]:\\\\)/.test(text))throw Error('S1_DELIVERY_TEXT_BOUNDARY')}
 put('MANIFEST.sha256',Object.entries(payload).sort(([a],[b])=>a.localeCompare(b)).map(([n,b])=>sha(b)+'  '+n).join('\n')+'\n')
 run('node',['VERIFY_DELIVERY.mjs'],dir)
 for(const n of ALLOW)fs.utimesSync(path.join(dir,n),new Date('2000-01-01Z'),new Date('2000-01-01Z'))
 const zip=path.join(tmp,'delivery.zip'),other=path.join(tmp,'repeat.zip');run('zip',['-X','-q',zip,...ALLOW],dir);run('zip',['-X','-q',other,...ALLOW],dir);if(sha(fs.readFileSync(zip))!==sha(fs.readFileSync(other)))throw Error('S1_ZIP_NONDETERMINISTIC')
 const metadata=`import zipfile,stat,json,sys\nwith zipfile.ZipFile(sys.argv[1]) as z:\n entries=[{'name':i.filename,'type':'regular' if not i.is_dir() and stat.S_IFMT(i.external_attr>>16) in (0,stat.S_IFREG) else 'nonregular'} for i in z.infolist()]\n print(json.dumps(entries))`
 admitEntries(JSON.parse(run('python3',['-c',metadata,zip])),ALLOW);const extracted=path.join(tmp,'extracted');fs.mkdirSync(extracted);run('unzip',['-q',zip,'-d',extracted]);run('node',['VERIFY_DELIVERY.mjs'],extracted)
 for(const n of ALLOW)if(!fs.readFileSync(path.join(dir,n)).equals(fs.readFileSync(path.join(extracted,n))))throw Error('S1_BYTE_ROUND_TRIP')
 if(git('rev-parse','HEAD')!==candidate.commit||git('rev-parse','HEAD^{tree}')!==candidate.tree)throw Error('S1_FINAL_CANDIDATE_CHANGED')
 const dest=path.join(path.dirname(root),OUTPUT);fs.copyFileSync(zip,dest,fs.constants.COPYFILE_EXCL)
 return {status:TERMINAL,completeBundleIncluded:false,packagingContractFulfilled:false,historyPrivatePathFindings:hp.privatePathFindings,candidate,archive:dest,sha256:sha(fs.readFileSync(zip)),bytes:fs.statSync(zip).size,members:ALLOW.length,manifestEntries:ALLOW.length-1,s1Tests,focusedTests,reportValidationTests,totalTests,futureInventory:0,authorities:OFF}
}
if(process.argv[1]===fileURLToPath(import.meta.url))console.log(JSON.stringify(await packageDelivery(process.cwd()),null,2))
