import {test} from 'node:test'
import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import fs from 'node:fs'
import {OFF,STATUS,evaluate,inventory,installTargets,safeName,identity,checkSeal,falsifiable,admitEntries} from './core.mjs'
import {derive,registry,bounds,readInput,schemaOf} from './model.mjs'
import {validateSchema} from '../nq5/schema.mjs'
import {privatePathFindings,historyPrivatePathScan} from './privacy.mjs'
import {ALLOW,verifier} from './package.mjs'
const clone=structuredClone
function fixture(){
 const delta={consumer:'REGRESSION_CORPUS.INDEPENDENT_CONTROL',behavior:'CORPUS_REGRESSION_CONTROL',before:'UNRESOLVED',tests:[{input:{schemaCompatible:true},expected:'FIXTURE_SUPPORTED'},{input:{schemaCompatible:false},expected:'FIXTURE_HELD'}]}
 const o={key:'independent-response-control',question:'Does one independent response exercise the missing signed-flow control?',family:'synthetic-public-safe-family',delta,prerequisites:['accepted-public-truth'],equivalenceKey:'independent-response-control',role:'REGRESSION_CONTROL',subject:'synthetic-subject',status:STATUS[0],hashes:[]}
 const c={id:'synthetic-1',observationKey:o.key,question:o.question,family:o.family,delta:clone(delta),origin:'FUTURE',authorities:OFF,hashes:[]},context={registry:{[o.key]:o},evidence:['accepted-public-truth'],consumers:[delta.consumer],derivable:[],retired:[],hubs:[],dominated:[],admittedFamilies:[o.family],acceptedZeroCoverage:[]}
 return {o,c,context}
}
test('honest zero is valid and positive synthetic observation remains research-only',()=>{const f=fixture();assert.equal(inventory([],f.context).maximumDefensible,0);assert.equal(evaluate(f.c,f.context),'RESEARCH_INVENTORY_ONLY');assert.equal(inventory([f.c],f.context).maximumDefensible,1);assert.ok(falsifiable(f.o.delta))})
test('unique IDs do not admit Cartesian subjects phases and directions',()=>{const f=fixture(),grid=[];for(const s of['A','B','C'])for(const p of['BEFORE','DURING','AFTER'])for(const d of['IN','OUT'])grid.push({...f.c,id:s+p+d,observationKey:s+p+d,meaningful:true,noPadding:true});assert.equal(inventory(grid,f.context).accepted.length,0);assert.equal(inventory(grid,f.context).rejected.length,18)})
test('generated consumers cannot replace a falsifiable registered behavior delta',()=>{const f=fixture();f.c.delta.consumer='GENERATED.CONSUMER.000999';assert.equal(evaluate(f.c,f.context),'UNREGISTERED_OBSERVATION_OR_DELTA')})
test('self-declared noPadding or meaningful booleans do not alter result',()=>{const f=fixture();f.c.observationKey='not-registered';const x=evaluate(f.c,f.context);f.c.noPadding=true;f.c.meaningful=true;assert.equal(evaluate(f.c,f.context),x)})
test('phase partitions without new evidence are locally derivable',()=>{const f=fixture();f.context.derivable.push(f.o.key);f.c.phase='NEW_PHASE';assert.equal(evaluate(f.c,f.context),'LOCALLY_DERIVABLE')})
test('an exact-filter-page encompassing zero dominates a narrower zero without asserted candidate booleans',()=>{const f=fixture();Object.assign(f.o,{filterIdentity:'subject+direction+token',page:1,window:{from:'2023-03-13T09:00:00Z',to:'2023-03-13T09:10:00Z'}});f.context.acceptedZeroCoverage=[{filterIdentity:f.o.filterIdentity,page:1,from:'2023-03-13T08:45:00Z',to:'2023-03-13T12:15:00Z'}];assert.equal(evaluate(f.c,f.context),'DOMINATED_PRIOR_EVIDENCE');f.context.acceptedZeroCoverage[0].page=2;assert.equal(evaluate(f.c,f.context),'RESEARCH_INVENTORY_ONLY')})
test('supported exact-hash reconciliation must bundle the complete reviewed hash set',()=>{const f=fixture();f.o.hashes=['synthetic-hash-A','synthetic-hash-B'];f.c.hashes=['synthetic-hash-A'];assert.equal(evaluate(f.c,f.context),'EXACT_HASH_FRAGMENTATION');f.c.hashes=[...f.o.hashes].reverse();assert.equal(evaluate(f.c,f.context),'RESEARCH_INVENTORY_ONLY')})
test('accepted normalized answers do not become future requests',()=>{const f=fixture();f.context.derivable=[f.o.key];assert.equal(inventory([f.c],f.context).maximumDefensible,0)})
test('hub fan-out cannot become route breadth',()=>{const f=fixture();f.o.role='ROUTE_BREADTH';f.context.hubs=[f.o.subject];assert.equal(evaluate(f.c,f.context),'HUB_SUPPRESSED')})
test('lexical names and request ordering do not change inventory bound',()=>{const f=fixture(),a=[{...f.c,id:'ZZZ'},{...f.c,id:'AAA'}];assert.equal(inventory(a,f.context).maximumDefensible,1);assert.equal(inventory(a.reverse(),f.context).maximumDefensible,1)})
test('family diversity without a reviewed observation is not utility',()=>{const f=fixture();f.c.family='different-family';assert.equal(evaluate(f.c,f.context),'UNREGISTERED_OBSERVATION_OR_DELTA')})
test('case name alone is not question or behavior evidence',()=>{const f=fixture();f.c.observationKey='PUBLIC_SAFE_CASE_NAME';f.c.caseName='Euler';assert.equal(inventory([f.c],f.context).accepted.length,0)})
for(const role of['BANTER','VISUAL_FILL','MARKETING_COUNT','ARCHIVE_DENSITY'])test(role+' is not acquisition purpose',()=>{const f=fixture();f.o.role=role;assert.equal(evaluate(f.c,f.context),'NON_INVESTIGATIVE_PURPOSE')})
for(const origin of['HELD','UNKNOWN','RETIRED','RETRY','DURABLE_REUSE'])test(origin+' stays excluded from future inventory',()=>{const f=fixture();f.c.origin=origin;assert.equal(evaluate(f.c,f.context),'HISTORICAL_NOT_FUTURE');f.c.origin='FUTURE';f.context.retired=[f.o.key];assert.equal(evaluate(f.c,f.context),'HISTORICAL_NOT_FUTURE')})
test('foreground contextual volume cannot dilute exact Hero proof',()=>{const f=fixture();f.o.role='FOREGROUND_CONTEXT_PROOF';assert.equal(evaluate(f.c,f.context),'CONTEXT_CANNOT_BECOME_EXACT_PROOF')})
for(const flag of['frozenPlan','livePlan'])test(flag+' misrepresentation is rejected',()=>{const f=fixture();f.c[flag]=true;assert.equal(evaluate(f.c,f.context),'LIVE_MISREPRESENTATION')})
for(const k of Object.keys(OFF))test('authority '+k+' cannot be true',()=>{const f=fixture();f.c.authorities={...OFF,[k]:true};assert.equal(evaluate(f.c,f.context),'LIVE_MISREPRESENTATION')})
test('same output for varied targets: bound function has no target input',()=>{const rows=registry(readInput()),expected=identity(bounds(rows));for(const target of[0,25,999,1024,999999])assert.equal(identity(bounds(rows,target)),expected);assert.equal(bounds(rows).maximumDefensibleAdditionalInventory,0);assert.equal(bounds(rows).theoreticalAllConceivableEulerUpperBound,null)})
test('all real prospective deltas execute discriminating pure branches, not new runtime integration',()=>{for(const o of registry(readInput()))assert.ok(falsifiable(o.consumerDelta));const f=fixture();f.o.delta.tests=[{input:{schemaCompatible:true},expected:'FIXTURE_SUPPORTED'},{input:{schemaCompatible:true},expected:'FIXTURE_SUPPORTED'}];f.c.delta=clone(f.o.delta);assert.equal(evaluate(f.c,f.context),'NO_FALSIFIABLE_CONSUMER')})
test('missing accepted prerequisite is a hold, not an accepted observation',()=>{const f=fixture();f.context.evidence=[];assert.equal(evaluate(f.c,f.context),'MISSING_ACCEPTED_PREREQUISITE')})
test('new-family observation is genuine unresolved work but not current inventory',()=>{const f=fixture();f.o.status=STATUS[1];assert.equal(evaluate(f.c,f.context),'OUTSIDE_CURRENT_SCOPE')})
test('equivalent requests collapse irrespective of IDs and count declarations',()=>{const f=fixture();const a=inventory([f.c,{...f.c,id:'new-id',noPadding:true}],f.context);assert.equal(a.accepted.length,1);assert.equal(a.rejected[0].reason,'EQUIVALENT')})
for(const bad of['../v1.9.0/file.md','/absolute/file','a/../../history','a\\b','a/./b','..'])test('source install blocks unsafe member '+bad,()=>assert.throws(()=>installTargets([bad])))
for(const epoch of['v1.9.0','v1.7.0','../v1.9.0'])test('historical epoch '+epoch+' cannot be targeted',()=>assert.throws(()=>installTargets(['04_CURRENT_OPERATIONS.md'],epoch)))
test('source target set is current epoch only and duplicate paths rejected',()=>{const input=readInput(),names=input.source.files.map(x=>x.file.replace('docs/source/v1.10.0/',''));assert.ok(installTargets(names).every(x=>x.startsWith('docs/source/v1.10.0/')));assert.throws(()=>installTargets(['x','x']));assert.equal(safeName('a/../b'),false)})
test('source and current decision snapshots are deterministic and seals verify',()=>{const a=derive(),b=derive();assert.equal(identity(a),identity(b));for(const v of Object.values(a))assert.ok(checkSeal(v));const v=clone(a['S1_DECISION_RECEIPT.json']);v.defensibleAdditionalInventory=999;assert.throws(()=>checkSeal(v))})
test('six schemas admit generated documents and reject live authority, unknown fields and fabricated candidates',()=>{for(const[n,v]of Object.entries(derive())){const s=schemaOf(v);assert.ok(validateSchema(n,v,s));for(const mutate of[x=>x.authorities.network=true,x=>x.extraUnauthorizedField=true]){const x=clone(v);mutate(x);assert.throws(()=>validateSchema(n,x,s))}}const all=derive(),n='REQUEST_SPECIFIC_CANDIDATE_MATRIX.json',x=clone(all[n]);x.candidates=[{inventedConsumer:'CASE.999'}];assert.throws(()=>validateSchema(n,x,schemaOf(all[n])))})
test('S1 captures only explicit accepted public evidence and has no private-state invocation',()=>{const s=fs.readFileSync(new URL('./capture.mjs',import.meta.url),'utf8');assert.doesNotMatch(s,/resolveCredential|process\.env|\.derive\(|rawFor|readState|postContext/);assert.ok(s.includes("p('PUBLIC/NQ5_PUBLIC_CALL_INDEX.json')"))})
test('privacy classifier exempts exact public fixture literals, not new user paths or extended fixture suffixes',()=>{const prefix='/'+['home','synthetic','private'].join('/');assert.equal(privatePathFindings(prefix).length,0);assert.equal(privatePathFindings(prefix+'/real-new-file').length,1);assert.equal(privatePathFindings('/'+['home','actual-user','project','data'].join('/')).length,1);assert.equal(privatePathFindings('repository/workspace;').length,0)})
test('standalone delivery verifier parses without provider or state access',()=>assert.doesNotThrow(()=>execFileSync('node',['--input-type=module','--check'],{input:verifier(),env:{PATH:process.env.PATH}})))
test('archive exact allowlist rejects extra, missing, duplicate, traversal and nonregular entries',()=>{const entries=ALLOW.map(name=>({name,type:'regular'}));assert.ok(admitEntries(entries,ALLOW));for(const mutation of[x=>x.push({name:'extra.txt',type:'regular'}),x=>x.pop(),x=>x[1]=clone(x[0]),x=>x[0].name='../escape',x=>x[0].type='symlink',x=>x[0].type='directory',x=>x[0].type='device']){const x=clone(entries);mutation(x);assert.throws(()=>admitEntries(x,ALLOW))}})
test('inherited history paths remain a real failing gate, not a synthetic-fixture exemption',()=>{const h=historyPrivatePathScan(process.cwd());assert.equal(h.status,'FAIL_INHERITED_PRIVATE_ABSOLUTE_PATHS');assert.equal(h.privatePathFindings,31);assert.equal(h.distinctPrivatePathLiterals,8);assert.equal(h.findings.length,11);assert.equal(h.credentialFileOpened,false);assert.equal(h.privateFilesystemTargetsOpened,false)})
test('blocked delivery withholds the mandatory recovery bundle and does not claim contract completion',()=>{assert.equal(ALLOW.includes('GIT/trace-escape-complete.bundle'),false);const d=derive()['S1_DECISION_RECEIPT.json'];assert.equal(d.terminalStatus,'BLOCKED_WITH_EVIDENCE');assert.equal(d.mandatoryCompleteBundleIncluded,false);assert.equal(d.packagingContractFulfilled,false);assert.equal(d.researchDisposition,'CURRENT_SCOPE_INSUFFICIENT_BOUNDED_EXPANSION_DECISION_REQUIRED')})
test('network probes fetch, HTTP, DNS and raw socket throw before external issue',()=>{const script=`const assert=require('node:assert/strict');for(const fn of[()=>fetch('https://example.invalid'),()=>require('node:http').get('http://example.invalid'),()=>require('node:dns').lookup('example.invalid',()=>{}),()=>require('node:net').connect({host:'203.0.113.1',port:443})])assert.throws(fn,/network hold/);console.log('FOUR_EXTERNAL_PROBES_BLOCKED_BEFORE_ISSUE')`;const out=execFileSync('node',['--require','./scripts/nq5-r2/hold.cjs','-e',script],{env:{PATH:process.env.PATH},encoding:'utf8'});assert.match(out,/FOUR_EXTERNAL_PROBES_BLOCKED_BEFORE_ISSUE/)})
