import fs from 'node:fs'
import path from 'node:path'
import assert from 'node:assert/strict'
import {spawnSync} from 'node:child_process'
import {canonicalFixture,controllerCorpus} from '../../src/controller/corpus/input.ts'
import {buildFrozenFixture,syntheticFixture} from '../../src/investigation/fixture.ts'
import {createInvestigationState,investigationReducer,restoreInvestigation,exportLocalSave} from '../../src/investigation/state.ts'
import {admitFrozenCorpusCandidate,admitSyntheticCorpusFixture} from '../../src/investigation/corpus-seam/authority.mjs'
import {createCanonicalView,createSyntheticView} from '../../src/investigation/semantic-ux/model.ts'
const read=n=>JSON.parse(fs.readFileSync(n)),out=process.argv.slice(2).find(a=>!a.startsWith('--'))||'artifacts/g6p-s6-r1/REPORTS'
fs.mkdirSync(out,{recursive:true});const put=(n,v)=>fs.writeFileSync(path.join(out,n),JSON.stringify(v,null,2)+'\n')
const b=spawnSync('node',['docs/source/execution-s6-r1/INPUT/REPRODUCE_BASELINE.mjs'],{encoding:'utf8',env:{PATH:process.env.PATH,NODE_OPTIONS:'--require '+path.resolve('scripts/nq5-r2/hold.cjs')}})
assert.equal(b.status,0);const baseline=JSON.parse(b.stdout);assert.equal(baseline.status,'REPRODUCED_PREMATURE_PIXEL_BINDING');assert.equal(baseline.blueprintBeats,24);assert.equal(baseline.fixedFacing,48);assert.equal(baseline.requiredVisualCapability,24);assert.equal(baseline.matrixFixedFacing,48);put('BASELINE.json',baseline)
const hero=buildFrozenFixture(read('public/scenarios/euler-2023-false-exit/scenario.json'),read('public/scenarios/euler-2023-false-exit/evidence-graph.json')),synthetic=syntheticFixture(hero)
function solve(f){let s=createInvestigationState(f);for(const c of [{type:'EARN_ACCESS'},{type:'STAGE_CARD',cardId:'CARD.WHAT_LEFT'},{type:'REVIEW_RECEIPT'},{type:'DISPATCH',path:'TERMINAL'},{type:'SELECT_RESULT',recordId:f.proof.slots.LINK},{type:'STAGE_CARD',cardId:'CARD.EXACT_RECEIPT'},{type:'REVIEW_RECEIPT'},{type:'DISPATCH',path:'TERMINAL'},{type:'READ_BRANCH',branch:'SECOND'},...['AMOUNT','RECEIVER','LINK'].map(slot=>({type:'ASSEMBLE',slot,recordId:f.proof.slots[slot]}))])s=investigationReducer(f,s,c);assert.equal(s.complete,true);return s}
const completed=solve(synthetic),canonical=solve(hero),foreign={...completed,complete:false,assembly:{}}
let crossed=foreign;for(const slot of ['AMOUNT','RECEIVER','LINK'])crossed=investigationReducer(hero,crossed,{type:'ASSEMBLE',slot,recordId:synthetic.proof.slots[slot]})
const restored=restoreInvestigation(hero,exportLocalSave(completed));assert.equal(restored.complete,false);assert.deepEqual(restored.exactEventIds,[])
const spoof=structuredClone(synthetic);spoof.id=hero.id;spoof.mode='ACCEPTED_FROZEN';assert.equal(canonicalFixture(spoof),false)
let spoofRejected=false;try{await controllerCorpus(spoof)}catch{spoofRejected=true}assert.equal(spoofRejected,true)
const c=await admitFrozenCorpusCandidate(read('artifacts/g6p-s3/REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json')),s=await admitSyntheticCorpusFixture(read('artifacts/g6p-s3/REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json'))
async function rejects(fn){try{await fn();return false}catch{return true}}
const syntheticTokenAsCanonical=await rejects(()=>createCanonicalView(s)),canonicalTokenAsSynthetic=await rejects(()=>createSyntheticView(c));assert.equal(syntheticTokenAsCanonical,true);assert.equal(canonicalTokenAsSynthetic,true)
let displayIdsRejected=0;const example=read('artifacts/g6p-s3/REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json');for(const r of example.records){let h=investigationReducer(hero,createInvestigationState(hero),{type:'EARN_ACCESS'});const before=JSON.stringify({assembly:h.assembly,exact:h.exactEventIds,complete:h.complete});for(const slot of ['AMOUNT','RECEIVER','LINK'])h=investigationReducer(hero,h,{type:'ASSEMBLE',slot,recordId:r.id});assert.equal(JSON.stringify({assembly:h.assembly,exact:h.exactEventIds,complete:h.complete}),before);displayIdsRejected++}
const reproduced=crossed.complete&&crossed.fixtureId===synthetic.id&&crossed.announcement.startsWith(hero.proof.conclusion)
assert.equal(reproduced,true)
const report={schemaVersion:'1.0.0',status:'REPRODUCED_DIRECT_REDUCER_CROSS_FIXTURE_NO_PUBLIC_EXPLOIT_ESTABLISHED',reviewedStart:'04e1f3337f576496018929a05b8a65cf6ebf4d99',syntheticFixtureId:synthetic.id,HeroFixtureId:hero.id,canonicalFixtureSpoofRejected:spoofRejected,syntheticAdmissionTokenAsCanonicalRejected:syntheticTokenAsCanonical,canonicalAdmissionTokenAsSyntheticRejected:canonicalTokenAsSynthetic,syntheticDisplayRecordSlotProbesRejected:displayIdsRejected*3,syntheticSelfCalibration:{complete:completed.complete,conclusion:synthetic.proof.conclusion,canonicalFixture:false},HeroPositiveControl:{complete:canonical.complete,fixtureId:canonical.fixtureId},normalSaveCrossFixture:{complete:restored.complete,exactEventIds:restored.exactEventIds,rejected:true},directReducerCrossFixture:{inputFixtureId:foreign.fixtureId,outputFixtureId:crossed.fixtureId,fixtureArgument:hero.id,syntheticExactEventIds:foreign.exactEventIds,assemblyBefore:foreign.assembly,assemblyAfter:crossed.assembly,complete:crossed.complete,announcement:crossed.announcement,sharedRecordIdentifiers:synthetic.records.every(r=>hero.records.some(h=>h.id===r.id)),guardRejected:false},limitation:'Reproduced by explicitly passing foreign nonshipping synthetic state directly to the exported reducer. State remains tagged synthetic; normal restore rejects the different fixtureId. No shipping UI ingress, save bypass, accepted truth mutation or public exploit demonstrated.',requiredAdditionalSource:'src/investigation/state.ts',allowedInCurrentGate:false,productionFixApplied:false,stop:'MAIN review required before production source scope expansion.'}
put('SYNTHETIC_NO_BRIDGE_DIAGNOSTIC.json',report)
put('GATE_STATUS.json',{status:'BLOCKED_WITH_EVIDENCE',reason:'Direct cross-fixture reducer accepts inherited synthetic proof state and emits Hero completion; production correction requires out-of-scope file.',requiredMAINReview:true,blueprintRemediationCompleted:false,correctedReportsGenerated:false,syntheticScopeDecisionInstalled:true,canonicalPublicBridgeSafetyCertified:false,LaneAPacketPrepared:false,LaneAPacketSent:false,LaneCPacketPrepared:false,sourcePromoted:false,productionArtApproved:false,externalRequests:0,credentialAccess:false})
console.log(JSON.stringify({status:report.status,baseline:baseline.status,guardRejected:false,normalSaveCrossFixtureRejected:true,productionFixApplied:false}))
if(process.argv.includes('--assert-no-bridge')){assert.equal(crossed.complete,false,'S6_R1_SYNTHETIC_STATE_MUST_NOT_COMPLETE_HERO_REDUCER')}
