import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {sha} from '../nq5-s2/activity.mjs'
import {privatePathFindings} from '../nq5-s1/privacy.mjs'
import {hasSecretLikeValue} from '../secret-patterns.mjs'
import {attachPublishedRegressionInputs} from '../nq5-s2/published-regression-inputs.mjs'
import {laneContractFixture} from '../nq5-s5/lane-fixture.mjs'
import {BASE,TREE,allowed} from './verify.mjs'
const NAME='TRACE_ESCAPE_G6P_NQ5_T1_S6_R1_LATE_BOUND_PIXEL_BLUEPRINT_AND_LANE_A_RECONTRACT_DELIVERY_v1.0.0.zip',PRIMARY='0f52131c9f56f49128e7a413396331917e687a1f'
const root=process.cwd(),[flag,primary,outFlag,output]=process.argv.slice(2);assert.equal(flag,'--primary-reference-root');assert.equal(outFlag,'--output-directory');assert.ok(primary&&output&&root!==primary&&root!==output)
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'s6-delivery-')),fresh=path.join(tmp,'recovered'),dir=path.join(tmp,'package'),audit=path.join(tmp,'object-audit')
const env={PATH:process.env.PATH,LANG:'C.UTF-8',TZ:'UTC',TMPDIR:os.tmpdir(),CI:'1',NO_COLOR:'1',GIT_TERMINAL_PROMPT:'0',GIT_CONFIG_NOSYSTEM:'1',NODE_OPTIONS:'--require '+path.join(root,'scripts/nq5-r2/hold.cjs')}
const sanitize=t=>t.split(root).join('[IMPLEMENTATION_ROOT]').split(primary).join('[PRIMARY_REFERENCE_ROOT]').split(tmp).join('[FRESH_VERIFICATION_ROOT]').split(os.tmpdir()).join('[LOCAL_VERIFICATION_ROOT]').replace(/\u001b\[[0-9;]*m/g,'')
const run=(cmd,args,cwd=root,e=env)=>{try{return execFileSync(cmd,args,{cwd,env:e,maxBuffer:128000000,stdio:['pipe','pipe','pipe']}).toString()}catch(err){let n=1;const d=path.join(root,'artifacts/g6p-s6-r1/LOGS');while(fs.existsSync(path.join(d,'package-stopped-'+n+'.log')))n++;fs.writeFileSync(path.join(d,'package-stopped-'+n+'.log'),sanitize((err.stdout||'').toString()+(err.stderr||'').toString())+'\nEXIT_CODE='+err.status+'\n');throw Error('S6_PACKAGE_STOPPED_'+cmd)}}
const git=(...a)=>run('git',a).trim(),metadata=()=>({head:run('git',['rev-parse','HEAD'],primary).trim(),status:run('git',['status','--porcelain=v1','--untracked-files=no'],primary).trim()})
const before=metadata();assert.deepEqual(before,{head:PRIMARY,status:'M AGENTS.md'})
const candidate={commit:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),parent:git('rev-parse','HEAD^')};assert.equal(git('rev-parse',BASE+'^{tree}'),TREE);assert.equal(git('rev-list','--merges',BASE+'..HEAD'),'');assert.equal(git('diff','--name-only','HEAD','--','.',':(exclude).cursor',':(exclude)ART_PRODUCTION'),'')
const changed=git('diff','--name-only',BASE,candidate.commit).split('\n').filter(Boolean);assert.ok(changed.length&&changed.every(allowed));const agentsBlob=git('rev-parse',BASE+':AGENTS.md');assert.equal(git('rev-parse','HEAD:AGENTS.md'),agentsBlob)
fs.mkdirSync(dir);const payload=new Map(),put=(name,value)=>{assert.ok(name&&!name.startsWith('/')&&!name.includes('\\')&&!name.split('/').some(p=>['','..','.'].includes(p))&&!payload.has(name));const b=Buffer.isBuffer(value)?value:Buffer.from(typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');fs.mkdirSync(path.dirname(path.join(dir,name)),{recursive:true});fs.writeFileSync(path.join(dir,name),b,{flag:'wx'});payload.set(name,b)}
const log=(name,text)=>put('FRESH_LOGS/'+name+'.log',sanitize(text)+'\nEXIT_CODE=0\n'),objects=git('rev-parse','--path-format=absolute','--git-path','objects')
const init=d=>{fs.mkdirSync(d);run('git',['init','--quiet'],d);fs.mkdirSync(path.join(d,'.git/objects/info'),{recursive:true});fs.writeFileSync(path.join(d,'.git/objects/info/alternates'),objects+'\n')}
const bundle=path.join(tmp,'incremental.bundle');run('git',['-c','pack.threads=1','bundle','create',bundle,'HEAD','^'+BASE]);const bb=fs.readFileSync(bundle),boundary=bb.indexOf(Buffer.from('\n\n')),header=bb.subarray(0,boundary).toString();assert.ok(boundary>0&&header.includes('-'+BASE+' ')&&header.includes(candidate.commit+' HEAD'));assert.equal(header.split('\n').filter(l=>l.startsWith('-')).length,1)
init(audit);const pack=execFileSync('git',['index-pack','--fix-thin','--stdin'],{cwd:audit,env,input:bb.subarray(boundary+2),maxBuffer:128000000}).toString().trim().split(/\s+/).at(-1)
const newObjects=run('git',['verify-pack','-v',path.join(audit,'.git/objects/pack/pack-'+pack+'.idx')],audit).split('\n').filter(l=>/^[a-f0-9]{40} (blob|commit|tree|tag) /.test(l)).map(l=>{const[id,type]=l.split(' ');return{id,type}})
for(const o of newObjects.filter(o=>['blob','commit','tag'].includes(o.type))){const b=execFileSync('git',['cat-file',o.type,o.id],{cwd:audit,env,maxBuffer:128000000}),t=new TextDecoder('utf8',{fatal:true}).decode(b);assert.equal(privatePathFindings(t).length,0);assert.equal(hasSecretLikeValue(t),false)}
put('GIT/trace-escape-incremental.bundle',bb);put('EVIDENCE/GIT_OBJECT_PRIVACY.json',{status:'PASS',newObjects:newObjects.length,privatePathFindings:0,secretFindings:0,newNontextObjects:0,completeHistoryIncluded:false,protectedPrimaryBytesOpened:false})
init(fresh);log('bundle-verify',run('git',['bundle','verify',bundle],fresh));run('git',['fetch','--quiet','--no-tags',bundle,'HEAD:refs/heads/candidate'],fresh);run('git',['symbolic-ref','HEAD','refs/heads/candidate'],fresh);run('git',['read-tree','HEAD'],fresh)
for(const[expr,value]of [['HEAD',candidate.commit],['HEAD^{tree}',candidate.tree],['HEAD^',candidate.parent]])assert.equal(run('git',['rev-parse',expr],fresh).trim(),value)
for(const entry of run('git',['ls-files','--stage','-z','--','.',':(exclude).cursor',':(exclude)ART_PRODUCTION'],fresh).split('\0').filter(Boolean)){const name=entry.slice(entry.indexOf('\t')+1),mode=entry.slice(0,6);assert.ok(['100644','100755'].includes(mode)&&!name.startsWith('/')&&!name.split('/').includes('..'));const b=execFileSync('git',['show','HEAD:'+name],{cwd:fresh,env,maxBuffer:128000000});fs.mkdirSync(path.dirname(path.join(fresh,name)),{recursive:true});fs.writeFileSync(path.join(fresh,name),b,{flag:'wx',mode:mode==='100755'?0o755:0o644})}
fs.symlinkSync(path.join(root,'node_modules'),path.join(fresh,'node_modules'),'dir');fs.appendFileSync(path.join(fresh,'.git/info/exclude'),'\nnode_modules\n');log('git-fsck',run('git',['fsck','--full','--strict'],fresh))
const diff=execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:root,env,maxBuffer:128000000});assert.ok(diff.equals(execFileSync('git',['diff','--binary',BASE,candidate.commit],{cwd:fresh,env,maxBuffer:128000000})));put('SOURCE_DIFF.patch',diff)
const reference=path.join(tmp,'published-reference'),replay=path.join(tmp,'published-input-links');fs.mkdirSync(reference);fs.mkdirSync(replay)
const publishedFiles=['scripts/nq5-b1/authority.mjs','scripts/nq5-b1-r1/checkpoint.mjs','scripts/nq5-b1-r2/gates.mjs','scripts/nq5-b1-r3/authority.mjs','scripts/nq5-b1-r3-r1/authority.mjs','scripts/nq5-b1-r3-r2/authority.mjs','scripts/nq5-b2/authority.mjs','scripts/nq5-b3/authority.mjs']
for(const file of publishedFiles){const b=fs.readFileSync(path.join(fresh,file));fs.mkdirSync(path.dirname(path.join(reference,file)),{recursive:true});fs.writeFileSync(path.join(reference,file),b);const text=b.toString(),n=file==='scripts/nq5-b1/authority.mjs'?'TRACE_ESCAPE_G6P_A2U_R3_R1_FRONTIER_POLICY_IDENTITY_REMEDIATION_DELIVERY_v1.0.0.zip':text.match(/\b(?:B1_ARCHIVE|R1_ARCHIVE|ARCHIVE)\s*=\s*'([^']+)'/)?.[1];assert.ok(n&&/^TRACE_ESCAPE_[A-Za-z0-9_.]+\.zip$/.test(n));const source=path.join(path.dirname(primary),n);assert.ok(fs.lstatSync(source).isFile()&&!fs.lstatSync(source).isSymbolicLink());fs.copyFileSync(source,path.join(tmp,n),fs.constants.COPYFILE_EXCL)}
put('EVIDENCE/PUBLISHED_REGRESSION_BINDINGS.json',{...attachPublishedRegressionInputs(reference,replay,env),sourcePinsReadFromRecoveredCandidate:true,primaryWorktreeFilesRead:false,publishedRedactedArchivesCopiedIntoIsolatedTemp:true})
console.log('S6 exact incremental recovery, new-object privacy and source diff PASS; fresh regressions starting.')
for(const[name,args]of [['source',['--loader','./scripts/nq5-s5/ts-loader.mjs','scripts/nq5-s6-r1/verify.mjs']],['no-network',['scripts/nq5-s3-r1/no-network.mjs']],['scenario',['scripts/g5-pack.mjs','verify']],['diagnostic',['--loader','./scripts/nq5-s5/ts-loader.mjs','scripts/nq5-s6-r1/diagnostic.mjs']]])log(name,run('node',args,fresh))
log('original-input',run('node',['VERIFY_INPUT.mjs'],path.join(fresh,'docs/source/execution-s6-r1/INPUT')));log('future-schema',run('python3',['scripts/nq5-s6/schema-check.py'],fresh));log('preserved-schemas',run('python3',['scripts/nq5-s3-r1/schema-check.py'],fresh))
const fixture=laneContractFixture(fresh),unitEnv={...env,S4_LANE_CONTRACT_ROOT:fixture.root,NODE_OPTIONS:env.NODE_OPTIONS+' --import '+path.join(fresh,'scripts/nq5-s4/lane-test-scope.mjs')}
const unit=run('node',['node_modules/vitest/vitest.mjs','run','--maxWorkers=4'],fresh,unitEnv);log('broad-unit-acquisition',unit);const tests=Number(unit.match(/Tests\s+(\d+) passed/)?.[1]);assert.equal(tests,1662);assert.ok(!/\d+ failed/.test(unit));console.log('S6 fresh1662 broad unit/acquisition PASS; final build and deterministic generation starting.')
for(const task of ['typecheck','build','lint'])log(task,run('npm',['run',task],fresh));log('browser-boundary',run('node',['scripts/verify-browser-boundary.mjs'],fresh))
const invariantArgs=['--loader','./scripts/nq5-s5/ts-loader.mjs','scripts/nq5-s6-r1/diagnostic.mjs','--assert-no-bridge'];let invariantRejected=false;try{execFileSync('node',invariantArgs,{cwd:fresh,env,stdio:['pipe','pipe','pipe']})}catch(e){assert.equal(e.status,1);assert.ok(String(e.stderr).includes('S6_R1_SYNTHETIC_STATE_MUST_NOT_COMPLETE_HERO_REDUCER'));put('FRESH_LOGS/known-no-bridge-invariant-failure.log',sanitize(String(e.stdout)+String(e.stderr))+'\nEXIT_CODE=1\n');invariantRejected=true}assert.equal(invariantRejected,true)
const one=path.join(tmp,'generation-one'),two=path.join(tmp,'generation-two');for(const d of [one,two])run('node',['--loader','./scripts/nq5-s5/ts-loader.mjs','scripts/nq5-s6-r1/diagnostic.mjs',d],fresh)
const generated=fs.readdirSync(one).sort();for(const name of generated){const b=fs.readFileSync(path.join(one,name));assert.ok(b.equals(fs.readFileSync(path.join(two,name)))&&b.equals(fs.readFileSync(path.join(fresh,'artifacts/g6p-s6-r1/REPORTS',name))))}
put('EVIDENCE/DETERMINISM.json',{status:'PASS',candidate,reports:generated.map(file=>({file,sha256:sha(fs.readFileSync(path.join(one,file)))})),cleanIndependentOutputRoots:2,goldenSourceReportsEqual:true,correctedBlueprintReportsGenerated:false,diagnosticEvidenceOnly:true})
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)])
for(const[d,prefix]of [['artifacts/g6p-s6-r1',''],['docs/source/execution-s6-r1','SOURCE_INPUT/'],['artifacts/g6p-s6/REPORTS','PRESERVED_S6_REPORTS/']])for(const file of walk(path.join(root,d)).sort())put(prefix+path.relative(path.join(root,d),file).split(path.sep).join('/'),fs.readFileSync(file))
for(const name of changed.filter(n=>/^(src|scripts|tests)\//.test(n)))put('INTEGRATED_SOURCE/'+name,execFileSync('git',['show',candidate.commit+':'+name],{cwd:root,env,maxBuffer:128000000}))
for(const name of ['REVIEW_1.json','REVIEW_2.json']){const v=JSON.parse(payload.get('REPORTS/'+name));assert.equal(v.independent,false);assert.equal(v.genuineBugbot,false);for(const b of v.implementationBindings)assert.equal(sha(fs.readFileSync(path.join(root,b.file))),b.sha256)}
put('PRESERVED_S5_REPORTS/MVP_BLUEPRINT.json',fs.readFileSync(path.join(root,'artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.json')));put('PRESERVED_S5_REPORTS/MVP_BLUEPRINT.md',fs.readFileSync(path.join(root,'artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.md')))
const after=metadata();assert.deepEqual(after,before);assert.equal(run('git',['diff','--name-only','HEAD','--','.',':(exclude).cursor',':(exclude)ART_PRODUCTION'],fresh).trim(),'')
put('EVIDENCE/PROTECTED_PRIMARY.json',{status:'PASS',before,after,modifiedPrimaryAgentsRead:false,modifiedPrimaryAgentsHashed:false,modifiedPrimaryAgentsDiffedCopiedStagedCommittedResetStashedPackaged:false,trustedBaseAgentsBlob:agentsBlob,trustedCandidateAgentsBlob:git('rev-parse','HEAD:AGENTS.md'),implementationRetainedForMAIN:true})
put('EVIDENCE/FINAL_REVIEW_EXTENSION.json',{status:'BLOCKED_WITH_EVIDENCE_PENDING_MAIN',independent:false,genuineBugbot:false,candidate,freshUnitAcquisitionTests:tests,focusedChecksNotAddedAgain:true,exactRecovery:true,strictFsck:true,determinism:true,productionArtApproved:false,futureArchiveDecoderOrAuthenticatorClaimed:false,networkRequests:0,laneMessages:0,credentialAccess:false})
put('EVIDENCE/CHANGED_PATHS.json',{candidate,prerequisite:BASE,linearCommits:git('rev-list','--reverse',BASE+'..HEAD').split('\n'),merges:0,paths:changed.map(file=>({file,sha256:sha(execFileSync('git',['show',candidate.commit+':'+file],{cwd:root,env,maxBuffer:128000000}))})),sourceScope:'EVIDENCE_ONLY_NO_PRODUCTION_SOURCE_CHANGE'})
const manifest={schemaVersion:'1.0.0',status:'BLOCKED_WITH_EVIDENCE',candidate,reviewedBase:BASE,reviewedTree:TREE,sourceInputSha256:'85721af866250423e3d21a6d26628a1032b95f96095db90e68b5d960f6683186',acceptedBaseStill:'f74a569c959158b25f56c10cc07c625c202f43cc',evidenceOnlyCandidate:true,blueprintP1Closed:false,syntheticBridgeInvariantPassed:false,LaneAPacketPrepared:false,LaneCPacketPrepared:false,knownInvariantFailureRetained:true,productionSourceChanges:0,bundleSha256:sha(bb),sourceDiffSha256:sha(diff),incrementalPrerequisite:BASE,completeHistoryIncluded:false,fullUnitAcquisitionTests:tests,semanticRecords:25,boundedNoMatches:7,STATERecords:0,beats:24,clientEntries:74,LaneAFiles:37,sourcePromoted:false,productionArtApproved:false,contentLocked:false,releaseApproved:false,archiveReviewTemplate:'PREPARED_NOT_SENT',providerRequests:0,accountRequests:0,networkRequests:0,credentialAccess:false,laneMessages:0}
put('DELIVERY_MANIFEST.json',manifest);put('00_READ_ME_FIRST.md','S6-R1 BLOCKED_WITH_EVIDENCE. NOT completed remediation, acceptance or promotion. Evidence-only candidate; primary and production source unchanged. Exact incremental recovery requires reviewed current S6 '+BASE+' locally, which itself remains unpromoted. Accepted base still f74a569c959158b25f56c10cc07c625c202f43cc. Run node VERIFY_DELIVERY.mjs after safe unique regular member extraction. Baseline blueprint P1 remains OPEN, no corrected reports or Lane A replacement packet prepared. New direct reducer diagnostic reproduces synthetic foreign state accepted with Hero fixture; state remains tagged synthetic and normal save restoration rejects it, so no shipping UI exploit established. Known no-bridge assertion FAILURE retained verbatim with true exit 1. MAIN must decide origin-guard source scope (src/investigation/state.ts) or evidenced invariant interpretation. Exact MAIN synthetic scope decision installed, not a safety certification.1662 broad existing tests rerun on recovered unchanged production source; they do not waive the failing new invariant. Preserved S5/S6 reports are clearly marked historical unchanged evidence. No new browser-suite rerun claimed: no rendered/gameplay source changed. Two same-agent bounded evidence checks, not Bugbot or independent MAIN acceptance. No Pixel archive inspected, credential access or external/lane/network actions. Stop for MAIN.\n')
function verifyDelivery(){
 const fail=code=>{throw Error(code)},read=n=>fs.readFileSync(path.join(root,n)),walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const p=path.join(d,e.name),s=fs.lstatSync(p);if(s.isSymbolicLink()||(!s.isDirectory()&&(!s.isFile()||s.nlink!==1)))fail('S6_NONREGULAR');return s.isDirectory()?walk(p):[path.relative(root,p).split(path.sep).join('/')] }).sort()
 if(JSON.stringify(walk(root))!==JSON.stringify(allowedMembers))fail('S6_EXACT_MEMBERS')
 const seen=new Set();for(const line of read('MANIFEST.sha256').toString().trimEnd().split('\n')){const h=line.slice(0,64),n=line.slice(66);if(!/^[a-f0-9]{64}$/.test(h)||line.slice(64,66)!=='  '||n==='MANIFEST.sha256'||seen.has(n)||!allowedMembers.includes(n)||sha(read(n))!==h)fail('S6_HASH');seen.add(n)}if(seen.size!==allowedMembers.length-1)fail('S6_HASH_COUNT')
 for(const[n,h]of Object.entries(pins))if(sha(read(n))!==h)fail('S6_PINNED_BINDING')
 if(JSON.stringify(JSON.parse(read('DELIVERY_MANIFEST.json')))!==JSON.stringify(manifest))fail('S6_MANIFEST_BINDING')
 const b=read('GIT/trace-escape-incremental.bundle'),h=b.subarray(0,b.indexOf(Buffer.from('\n\n'))).toString();if(!h.includes('-'+manifest.reviewedBase+' ')||h.split('\n').filter(x=>x.startsWith('-')).length!==1||!h.includes(manifest.candidate.commit+' HEAD')||sha(b)!==manifest.bundleSha256||sha(read('SOURCE_DIFF.patch'))!==manifest.sourceDiffSha256)fail('S6_GIT_BINDING')
 for(const n of allowedMembers){if(n==='GIT/trace-escape-incremental.bundle')continue;let t;try{t=new TextDecoder('utf8',{fatal:true}).decode(read(n))}catch{fail('S6_NON_TEXT')};if(privatePathFindings(t).length||hasSecretLikeValue(t))fail('S6_PRIVACY')}
 console.log(JSON.stringify({status:'PASS',members:allowedMembers.length,hashes:seen.size,candidate:manifest.candidate,terminalStatus:manifest.status,productionArtApproved:false,reviewTemplate:'PREPARED_NOT_SENT'}))
}
const secret=fs.readFileSync(path.join(root,'scripts/secret-patterns.mjs'),'utf8').replace('export function','function'),privacy=fs.readFileSync(path.join(root,'scripts/nq5-s1/privacy.mjs'),'utf8').split('export function privatePathFindings')[1].split('export function currentTreeScan')[0]
const seal=()=>{for(const n of ['VERIFY_DELIVERY.mjs','MANIFEST.sha256']){payload.delete(n);if(fs.existsSync(path.join(dir,n)))fs.unlinkSync(path.join(dir,n))}const pins=Object.fromEntries([...payload].filter(([n])=>n!=='DELIVERY_MANIFEST.json').map(([n,b])=>[n,sha(b)])),allowedMembers=[...payload.keys(),'VERIFY_DELIVERY.mjs','MANIFEST.sha256'].sort();put('VERIFY_DELIVERY.mjs',"import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';const root=path.dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex'),allowedMembers="+JSON.stringify(allowedMembers)+",pins="+JSON.stringify(pins)+",manifest="+JSON.stringify(manifest)+";\n"+secret+'\nfunction privatePathFindings'+privacy+'\n('+verifyDelivery.toString()+')();\n');for(const[n,b]of payload)if(n!=='GIT/trace-escape-incremental.bundle'){const text=b.toString();assert.equal(privatePathFindings(text).length,0,n);assert.equal(hasSecretLikeValue(text),false,n)}put('MANIFEST.sha256',[...payload].sort(([a],[b])=>a<b?-1:1).map(([n,b])=>sha(b)+'  '+n).join('\n')+'\n');run('node',['VERIFY_DELIVERY.mjs'],dir);return allowedMembers}
const tamper=members=>{const results=[],reject=(name,apply,restore,code)=>{const hashes=fs.readFileSync(path.join(dir,'MANIFEST.sha256'));try{apply();let rejected=false;try{execFileSync('node',['VERIFY_DELIVERY.mjs'],{cwd:dir,env,stdio:['pipe','pipe','pipe']})}catch(e){assert.ok(String(e.stderr).includes(code));rejected=true}assert.ok(rejected);results.push({name,status:'REJECTED',code})}finally{restore();fs.writeFileSync(path.join(dir,'MANIFEST.sha256'),hashes)}}
 const rehash=()=>fs.writeFileSync(path.join(dir,'MANIFEST.sha256'),members.filter(n=>n!=='MANIFEST.sha256').map(n=>sha(fs.readFileSync(path.join(dir,n)))+'  '+n).join('\n')+'\n'),name='FRESH_LOGS/typecheck.log',file=path.join(dir,name),original=fs.readFileSync(file)
 reject('byte tamper',()=>fs.appendFileSync(file,'BAD'),()=>fs.writeFileSync(file,original),'S6_HASH');reject('extra',()=>fs.writeFileSync(path.join(dir,'EXTRA.txt'),'TEST'),()=>fs.unlinkSync(path.join(dir,'EXTRA.txt')),'S6_EXACT_MEMBERS');reject('missing',()=>fs.unlinkSync(file),()=>fs.writeFileSync(file,original),'S6_EXACT_MEMBERS');reject('symlink',()=>{fs.unlinkSync(file);fs.symlinkSync('synthetic',file)},()=>{fs.unlinkSync(file);fs.writeFileSync(file,original)},'S6_NONREGULAR');reject('hardlink',()=>fs.linkSync(file,path.join(dir,'EXTRA.txt')),()=>fs.unlinkSync(path.join(dir,'EXTRA.txt')),'S6_NONREGULAR')
 for(const[n,label]of [['REPORTS/SYNTHETIC_NO_BRIDGE_DIAGNOSTIC.json','diagnostic'],['REPORTS/GATE_STATUS.json','blocked gate'],['REPORTS/SYNTHETIC_AUTHORITY_SCOPE_DECISION.json','authority contract'],['SOURCE_INPUT/EXECUTION_CONTRACT.txt','scope authorization'],['EVIDENCE/PROTECTED_PRIMARY.json','protected-file claim'],['INTEGRATED_SOURCE/scripts/nq5-s6-r1/diagnostic.mjs','weakened diagnostic'],['DELIVERY_MANIFEST.json','candidate substitution']]){const p=path.join(dir,n),b=fs.readFileSync(p);reject('rehashed '+label,()=>{if(n.endsWith('.json')){const x=JSON.parse(b);if(label==='candidate substitution')x.candidate.tree='0'.repeat(40);else x.tampered=true;fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n')}else fs.writeFileSync(p,Buffer.concat([b,Buffer.from('ALTERED')]));rehash()},()=>fs.writeFileSync(p,b),n==='DELIVERY_MANIFEST.json'?'S6_MANIFEST_BINDING':'S6_PINNED_BINDING')}
 assert.equal(results.length,12);run('node',['VERIFY_DELIVERY.mjs'],dir);return results}
let members=seal();const cases=tamper(members);put('EVIDENCE/PACKAGE_TAMPER.json',{status:'PASS',rejections:cases.length,cases,trustRoot:'Final ZIP SHA obtained independently; embedded verifier/manifest are integrity checks, not a digital signature or MAIN acceptance.'});members=seal();tamper(members)
for(const n of members)fs.utimesSync(path.join(dir,n),new Date('2000-01-01Z'),new Date('2000-01-01Z'))
const zip=path.join(tmp,'delivery.zip'),repeat=path.join(tmp,'repeat.zip');run('zip',['-X','-q',zip,...members],dir);run('zip',['-X','-q',repeat,...members],dir);assert.equal(sha(fs.readFileSync(zip)),sha(fs.readFileSync(repeat)))
const check="import zipfile,stat,json,sys\nwith zipfile.ZipFile(sys.argv[1]) as z:\n names=[i.filename for i in z.infolist()];assert len(names)==len(set(names))\n for i in z.infolist():\n  assert not i.is_dir() and stat.S_IFMT(i.external_attr>>16) in (0,stat.S_IFREG) and not i.filename.startswith('/') and '\\\\' not in i.filename and all(p not in ('','..','.') for p in i.filename.split('/'))\n print(json.dumps(sorted(names)))";assert.deepEqual(JSON.parse(run('python3',['-c',check,zip])),members)
const extracted=path.join(tmp,'extracted');fs.mkdirSync(extracted);run('unzip',['-q',zip,'-d',extracted]);const final=JSON.parse(run('node',['VERIFY_DELIVERY.mjs'],extracted));for(const n of members)assert.ok(fs.readFileSync(path.join(dir,n)).equals(fs.readFileSync(path.join(extracted,n))))
assert.equal(git('rev-parse','HEAD'),candidate.commit);assert.equal(git('rev-parse','HEAD^{tree}'),candidate.tree);assert.deepEqual(metadata(),before);fs.mkdirSync(output,{recursive:true});const destination=path.join(output,NAME);fs.copyFileSync(zip,destination,fs.constants.COPYFILE_EXCL)
console.log(JSON.stringify({status:manifest.status,archive:destination,sha256:sha(fs.readFileSync(destination)),bytes:fs.statSync(destination).size,members:members.length,candidate,freshUnitAcquisitionTests:tests,deterministicReports:generated.length,packageTamperRejections:12,finalVerification:final},null,2))
