import fs from 'node:fs'
import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {sha,canonical} from '../nq5-s2/activity.mjs'
import {privatePathFindings} from '../nq5-s1/privacy.mjs'
import {hasSecretLikeValue} from '../secret-patterns.mjs'
import {deriveBlueprint,validatePreArchiveBeat} from '../../src/controller/foundation/blueprint.ts'
export const BASE='9dd7ecaa2ae53dd3d6fa758b5b738b9bd620afb1',TREE='14381033526114416f1569b787a33e660b707da0'
export const allowed=n=>['src/investigation/state.ts','src/investigation/fixture.ts','src/controller/foundation/blueprint.ts','artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.json','artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.md'].includes(n)||/^tests\/unit\/s6-r1-[A-Za-z0-9.-]+$/.test(n)||['scripts/nq5-s6/','scripts/nq5-s6-r1/','artifacts/g6p-s6/','artifacts/g6p-s6-r1/','docs/source/execution-s6-r1/'].some(p=>n.startsWith(p))
const git=(...args)=>execFileSync('git',args,{encoding:'utf8',maxBuffer:128000000}).trim()
export async function verify(){
 assert.equal(git('rev-parse',BASE+'^{tree}'),TREE);execFileSync('git',['merge-base','--is-ancestor',BASE,'HEAD']);assert.equal(git('rev-list','--merges',BASE+'..HEAD'),'')
 const changes=git('diff','--name-only',BASE,'--','.',':(exclude).cursor',':(exclude)ART_PRODUCTION').split('\n').filter(Boolean);assert.ok(changes.every(allowed),'RES1_EXHAUSTIVE_SOURCE_SCOPE')
 assert.equal(git('rev-parse','HEAD:AGENTS.md'),git('rev-parse',BASE+':AGENTS.md'));assert.equal(git('diff',BASE,'HEAD','--','AGENTS.md'),'')
 const exceptions=['src/investigation/state.ts','src/investigation/fixture.ts'],p=JSON.parse(fs.readFileSync('artifacts/g6p-s5/REPORTS/PRESERVATION.json'));for(const f of [...p.preservedFiles,...p.laneAFiles].filter(f=>!exceptions.includes(f.file)))assert.equal(sha(fs.readFileSync(f.file)),f.sha256,f.file);assert.equal(p.laneAFiles.length,37)
 assert.equal(sha(fs.readFileSync('src/controller/content/runtime-content.json')),'57f27ecfef64f9c149f2f80bdb1efffbc629d79fd5f6a76e21c0e943c5c95bfc');assert.equal(Object.keys(JSON.parse(fs.readFileSync('src/controller/content/runtime-content.json')).entries).length,74)
 for(const file of ['src/controller/foundation/contracts.mjs','src/controller/foundation/pixel-identity.mjs','src/controller/foundation/pixel-identity.d.mts','src/controller/foundation/pixel-realization.mjs','src/controller/foundation/pixel-realization.d.mts','src/controller/foundation/pixel-review.mjs','src/controller/foundation/pixel-review.d.mts','src/investigation/query.ts','src/investigation/corpus-seam/authority.mjs','src/controller/corpus/input.ts','src/app/CaseTerminalWorkbench.tsx','src/app/App.tsx','src/controller/foundation/useIntegerViewportScale.ts'])assert.ok(fs.readFileSync(file).equals(execFileSync('git',['show',BASE+':'+file])),'PRESERVED_SOURCE '+file)
 for(const file of git('ls-tree','-r','--name-only',BASE,'--','scripts/nq5-s6-r1','artifacts/g6p-s6-r1','docs/source/execution-s6-r1').split('\n').filter(Boolean))assert.ok(fs.readFileSync(file).equals(execFileSync('git',['show',BASE+':'+file])),'HISTORICAL_R1_EVIDENCE_RETAINED '+file)
 const bp=await deriveBlueprint();assert.equal(canonical(bp),canonical(JSON.parse(fs.readFileSync('artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.json'))));bp.beats.forEach(validatePreArchiveBeat);assert.equal(bp.beats.length,24);assert.equal(bp.semanticTotal,25);assert.equal(bp.boundedNoMatches,7);assert.equal(bp.beats.find(b=>b.id==='LENS.STATE').acceptedCorpus.after.count,0)
 const matrix=JSON.parse(fs.readFileSync('artifacts/g6p-s6/REPORTS/MVP_REQUIREMENT_MATRIX.json'));for(const beat of matrix.beats){validatePreArchiveBeat(beat.acceptedBeat);assert.equal(canonical(beat.acceptedBeat),canonical(bp.beats.find(b=>b.id===beat.id)));assert.equal(beat.performance.rook.facing,'LATE_BOUND');assert.equal(beat.performance.arthur.facing,'LATE_BOUND')}
 assert.ok(fs.readFileSync('artifacts/g6p-s6-r1/RES1/REPORTS/SYNTHETIC_AUTHORITY_SCOPE_DECISION.json').equals(fs.readFileSync('docs/source/execution-s6-r1/INPUT/SYNTHETIC_AUTHORITY_SCOPE_DECISION.json')),'EXACT_MAIN_SYNTHETIC_SCOPE')
 const result=JSON.parse(fs.readFileSync('artifacts/g6p-s6-r1/RES1/REPORTS/BRIDGE_REPRODUCER_CLOSED.json'));assert.equal(result.directForeignStateCompletedHero,false);assert.equal(result.relabeledSyntheticSaveCompletedHero,false);assert.equal(result.syntheticAndHeroRecordIdsOverlap,false);assert.equal(result.syntheticPositiveComplete,true);assert.equal(result.heroPositiveComplete,true)
 const plan=JSON.parse(fs.readFileSync('artifacts/g6p-s6-r1/RES1/REPORTS/NONAUTHORITATIVE_VISUAL_IDEAS.json'));assert.equal(plan.requiredCapabilityContract,false);assert.equal(plan.runtimeConsumptionAllowed,false)
 const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name]);for(const file of [...changes.filter(n=>fs.existsSync(n)),...walk('artifacts/g6p-s6-r1/RES1'),...walk('scripts/nq5-s6-r1'),...walk('docs/source/execution-s6-r1/RES1')]){const s=fs.lstatSync(file);assert.ok(s.isFile()&&!s.isSymbolicLink());const text=fs.readFileSync(file,'utf8');assert.equal(privatePathFindings(text).length,0,file);assert.equal(hasSecretLikeValue(text),false,file)}
 return {status:'PASS_PENDING_MAIN_INDEPENDENT_REVIEW',reviewedStart:BASE,reviewedTree:TREE,productionSourcePaths:['src/investigation/state.ts','src/investigation/fixture.ts','src/controller/foundation/blueprint.ts'],blueprintP1Closed:true,syntheticOriginBridgesClosed:true,legacyIDOnlySaves:'FAIL_CLOSED_RESET',staticSaveCryptographicallyTamperProof:false,LaneAFiles:37,clientEntries:74,canonicalRecords:25,boundedNoMatches:7,STATERecords:0,beats:24,exactHeroTruthChanged:false,corpusAndLaneCSourceChanged:false,sourcePromoted:false,productionArtApproved:false,externalNetworkRequests:0}
}
if(process.argv[1]?.endsWith('/res1-verify.mjs'))console.log(JSON.stringify(await verify()))
