import fs from 'node:fs'
import {sha} from '../nq5-s2/activity.mjs'
import {verify} from './res1-verify.mjs'
const preservation=await verify(),walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name])
const source=[...walk('scripts/nq5-s6-r1').filter(f=>f.includes('/res1-')||f.includes('/browser/')),...walk('docs/source/execution-s6-r1/RES1').filter(f=>!f.includes('/INPUT/')),'scripts/nq5-s6/generate.mjs','src/investigation/state.ts','src/investigation/fixture.ts','src/controller/foundation/blueprint.ts','tests/unit/s6-r1-origin-boundary.test.ts','tests/unit/s6-r1-blueprint.test.ts']
const focus='artifacts/g6p-s6-r1/RES1/LOGS/focused-final.log',text=fs.readFileSync(focus,'utf8');if(!text.includes('244 passed')||!text.includes('EXIT_CODE=0'))throw Error('FOCUSED_FINAL_BINDING')
for(const checkpoint of [1,2]){
 const review={status:'PASS_TASK_OWNED_FINDINGS_CLOSED_PENDING_MAIN',gate:'S6-R1-RES1',checkpoint,independent:false,genuineBugbot:false,reviewKind:'DISCLOSED_SAME_AGENT_BOUNDED_FALLBACK',MAINAcceptanceGranted:false,PrincipalArtApprovalGranted:false,preservation,implementationBindings:source.sort().map(file=>({file,sha256:sha(fs.readFileSync(file))})),focusedChecks:{file:focus,sha256:sha(text),tests:244,newRES1:106,existing:138,notCountedTwice:true},reviewLenses:checkpoint===1?['Origin/replay correctness','Security/privacy/no-network','Closed schemas and adversarial rejection','Synthetic/public and Pixel approval authority']:['Beat/count/story/proof semantics','Accessible deterministic text/static recovery','Exact source scope and protected/history preservation','Recovery/determinism/packet/package integrity'],closedFindings:checkpoint===1?['Foreign reducer state returns clean fixture before application/history append','Both MAIN reproduced bridges close; positive own-origin cases preserved','Synthetic record/event/proof references remapped; even all-field metadata relabel saves cannot prove Hero','Client-visible marker not cryptographic saving; old ID-only saves reset fail-closed']:['All24 beats/count/proof content unchanged except forbidden Pixel metadata','LATE_BOUND facing and closed no clip/frame/anchor/timing/mirroring/fit contract with static text fallback','Descriptive art prose retained only nonauthoritative planning; S6 future intake sources unchanged','Lane A37/client74/truth/corpus/Lane C/viewport and original R1 evidence retained'],residuals:['Exact whole-candidate fresh broad1768/build/type/lint/browser12/determinism18/strict-fsck/tamper12 complete in final package extension','Actual Pixel archive decode/authentication/fit/Principal approval/MAIN admission remain future gates','Independent MAIN review and actual dedicated Lane A dispatch remain unperformed','Actual AT/numeric contrast/cross-browser/OS/final-art accessibility qualification pending'],sourcePromoted:false,laneMessages:0,networkRequests:0}
 const bytes=JSON.stringify(review,null,2)+'\n';fs.writeFileSync('artifacts/g6p-s6-r1/RES1/REPORTS/REVIEW_'+checkpoint+'.json',bytes);fs.writeFileSync('artifacts/g6p-s6/REPORTS/REVIEW_'+checkpoint+'.json',bytes)
}
console.log(JSON.stringify({status:'PASS_PENDING_MAIN',sameAgentCheckpoints:2,reviewLenses:8,independent:false,genuineBugbot:false}))
