import fs from 'node:fs'
import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {sha} from '../nq5-s2/activity.mjs'
import {BASE} from './res2-verify.mjs'
export function buildLaneAPacket(root,candidate,put){
 const git=(...a)=>execFileSync('git',a,{cwd:root,maxBuffer:128000000}),prefix='LANE_A_PREPARED_NOT_SENT/',preservation=JSON.parse(fs.readFileSync(root+'/artifacts/g6p-s5/REPORTS/PRESERVATION.json'))
 const selected=['src/investigation/state.ts','src/investigation/fixture.ts','src/controller/foundation/blueprint.ts','tests/unit/s6-r1-res2-atomic.test.ts','tests/unit/s6-r1-res2-blueprint.test.ts',...['generate.mjs','verify.mjs','record.mjs','browser.config.mjs','atomic.spec.ts'].map(n=>'scripts/nq5-s6-r1/res2-'+n),...['ORIGIN_BOUNDARY_CLOSURE.json','REPRODUCER_CLOSED.json','BLUEPRINT_AUTHORITY_CLOSURE.json','PRESERVATION.json','MAIN_SCOPE_DECISION.json','BASELINE_OPEN.json'].map(n=>'artifacts/g6p-s6-r1/RES2/REPORTS/'+n),'docs/source/execution-s6-r1/RES2/INPUT/REPRODUCE_REOPENED_P1S.mjs','docs/source/execution-s6-r1/RES2/INPUT/EXPECTED_CLOSURE_CONTRACT.json','docs/source/execution-s6-r1/RES2/INPUT/MAIN_SCOPE_DECISION.json'].sort()
 const files=selected.filter(n=>git('diff','--name-only',BASE,candidate.commit,'--',n).length),patch=git('diff','--binary',BASE,candidate.commit,'--',...files),source=files.map(file=>({file,sha256:sha(git('show',candidate.commit+':'+file))}))
 assert.equal(source.length,files.length);const bytes=new Map(),add=(name,value)=>{const b=Buffer.isBuffer(value)?value:Buffer.from(typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');bytes.set(name,b);put(prefix+name,b)}
 for(const f of source)add('SOURCE/'+f.file,git('show',candidate.commit+':'+f.file));add('TARGETED_RECOVERY.patch',patch)
 const unchanged=['artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.json','artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.md','artifacts/g6p-s6/REPORTS/MVP_REQUIREMENT_MATRIX.json','package.json','package-lock.json','src/controller/content/runtime-content.json','src/investigation/query.ts','src/controller/corpus/input.ts','src/investigation/corpus-seam/authority.mjs','artifacts/g6p-s3/REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json','artifacts/g6p-s3/REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json','public/scenarios/euler-2023-false-exit/scenario.json','public/scenarios/euler-2023-false-exit/evidence-graph.json']
 const prerequisites=[...preservation.laneAFiles.map(f=>({file:f.file,sha256:f.sha256})),...unchanged.map(file=>({file,sha256:sha(git('show',BASE+':'+file))}))];for(const f of prerequisites)assert.equal(sha(git('show',candidate.commit+':'+f.file)),f.sha256)
 const contract={schemaVersion:'1.0.0',lane:'A',gate:'S6-R1-RES2_REPLACEMENT_TARGETED_REGRESSION',status:'PREPARED_NOT_SENT',packetsSent:false,providerRequests:0,candidate,requiresPrerequisiteCommit:BASE,requiresPrerequisiteTree:'0395c6b556fa6b710dd2dc3d1644f3cc67e5d5c7',reviewedBaseIsAuthoritativeForThisGate:true,sourcePromoted:false,recoveryScope:'Exact targeted source/report/test subset, not full candidate tree. Whole delivery bundle recovers exact candidate with local prerequisite.',acceptedLaneAAdditionsPreserved:37,TE_IFACE_CONTENT:{id:'TE-IFACE-CONTENT',version:'1.1.0',file:'docs/parallel/lane-a/TE_IFACE_CONTENT_v1.1.0.json',sha256:'a0852fd6d4baae5f1bcf8afbd0688f775d0c11655ab5a30ca3ce3b1610ae4f81',canonicalSha256:'7d682d883fc55b80ed3c5ea752ea942d94000942257dd93a3eddc22a66c36903',changed:false},compiledClientEntriesPreserved:74,canonicalSemanticRecords:25,boundedNoMatches:7,STATERecords:0,semanticContextIsExactProof:false,blueprintSha256:sha(git('show',candidate.commit+':artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.json')),matrixSha256:sha(git('show',candidate.commit+':artifacts/g6p-s6/REPORTS/MVP_REQUIREMENT_MATRIX.json')),syntheticScopeSha256:sha(git('show',candidate.commit+':artifacts/g6p-s6-r1/RES2/REPORTS/MAIN_SCOPE_DECISION.json')),originEvidenceSha256:sha(git('show',candidate.commit+':artifacts/g6p-s6-r1/RES2/REPORTS/ORIGIN_BOUNDARY_CLOSURE.json')),prerequisites,files:source,patchSha256:sha(patch),commands:['npm run typecheck','npm run build','node node_modules/vitest/vitest.mjs run tests/unit/s6-r1-res2-atomic.test.ts tests/unit/s6-r1-res2-blueprint.test.ts tests/unit/s6-r1-origin-boundary.test.ts tests/unit/s6-r1-blueprint.test.ts tests/unit/s5-foundation.test.ts tests/unit/s5-r1-identity.test.ts --maxWorkers=4','node --require ./scripts/nq5-r2/hold.cjs --loader ./scripts/nq5-s5/ts-loader.mjs docs/source/execution-s6-r1/RES2/INPUT/REPRODUCE_REOPENED_P1S.mjs . --expect-closed','node node_modules/@playwright/test/cli.js test --config scripts/s5-r1-existing-browser.config.mjs'],instructions:'MAIN independent review first. Use existing dedicated Lane A task/workspace only when MAIN dispatches this contract; no supplier dispatch. Separate clean local exact prerequisite, verify prerequisite bytes, apply patch, compare source hashes. Use installed dependencies only. No Lane A edits or art/provider/credential/network authority. Origin replay marker is not cryptographic save protection.'}
 add('TARGETED_REGRESSION_CONTRACT.json',contract);add('README.md','Lane A PREPARED_NOT_SENT. Exact corrected candidate and minimum targeted recovery subset. No message or task dispatched; not MAIN acceptance. Verify every prerequisite, patch and source SHA; full candidate recovery requires delivery incremental bundle. Synthetic fixture self-calibration permitted only isolated nonshipping; no Hero bridge.24 semantic beats; production facing/clips/frames/anchors/timing/fit LATE_BOUND. Lane A37 and content interface1.1.0 unchanged. Stop for independent MAIN.\n')
 const pins=Object.fromEntries([...bytes].map(([n,b])=>[n,sha(b)])),verify="import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';const root=path.dirname(fileURLToPath(import.meta.url)),pins="+JSON.stringify(pins)+",expected="+JSON.stringify(contract)+";const sha=b=>createHash('sha256').update(b).digest('hex'),walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const p=path.join(d,e.name),s=fs.lstatSync(p);if(s.isSymbolicLink()||(!s.isDirectory()&&(!s.isFile()||s.nlink!==1)))throw Error('PACKET_NONREGULAR');return s.isDirectory()?walk(p):[path.relative(root,p).split(path.sep).join('/')]});if(JSON.stringify(walk(root).sort())!==JSON.stringify([...Object.keys(pins),'VERIFY_PACKET.mjs'].sort()))throw Error('PACKET_EXACT_MEMBERS');for(const[n,h]of Object.entries(pins))if(sha(fs.readFileSync(path.join(root,n)))!==h)throw Error('PACKET_PIN');const c=JSON.parse(fs.readFileSync(path.join(root,'TARGETED_REGRESSION_CONTRACT.json')));if(JSON.stringify(c)!==JSON.stringify(expected)||c.status!=='PREPARED_NOT_SENT'||c.packetsSent!==false)throw Error('PACKET_AUTHORITY');console.log(JSON.stringify({status:'PASS',packetStatus:c.status,candidate:c.candidate,sourceFiles:c.files.length,recovery:'TARGETED_SUBSET_ONLY'}));\n"
 put(prefix+'VERIFY_PACKET.mjs',verify)
 return {contract,patch,source,prefix}
}
