import fs from 'node:fs'
import {sha} from '../nq5-s2/activity.mjs'
import {BASE,TREE,INPUT_SHA} from './constants.mjs'
const out='artifacts/g6p-s4-r2/LANE_A_PREPARED_NOT_SENT/',report='artifacts/g6p-s4-r2/REPORTS/';fs.mkdirSync(out,{recursive:true})
const files=['src/app/PerformancePortrait.tsx','src/app/MissionHarness.tsx','src/app/App.tsx','src/controller/content/adapter.ts','src/controller/content/runtime-content.json','tests/unit/s4-r2-surfaces.test.ts','tests/e2e/s4-r2-surfaces.spec.ts',report+'TRUTH_HASH_CROSSWALK.json',report+'LANE_A_ADMISSION.json',report+'PRESERVATION.json',report+'CONSUMER_MANIFEST.json']
const contract={status:'PREPARED_NOT_SENT',interface:'TE-IFACE-CONTENT@1.1.0',contentInterfaceIdentity:'7d682d883fc55b80ed3c5ea752ea942d94000942257dd93a3eddc22a66c36903',contentIdentity:'540623c9e7f973f0f1cfa4bd4aa5b27f5150247004a05b61ab3a8791b87e0a2e',implementationIdentity:'84a081161b8b3e147021ad497af0862eaf3d7fe80b92f79de8ebe57e7711b46b',reviewedStart:BASE,reviewedTree:TREE,candidateBinding:'Packaged contract and outer DELIVERY_MANIFEST independently carry identical exact candidate commit/tree/parent.',packetsSent:false,providerRequests:0,corpusGameplayIntegrated:false,optionalBanterIntegrated:false,finalDensityAccepted:false,acceptedAdditions:JSON.parse(fs.readFileSync(report+'LANE_A_ADMISSION.json')).laneFiles,files:files.map(file=>({file,sha256:sha(fs.readFileSync(file))})),regressionTasks:['Retain accepted S4-R1 primary office/command/dialogue mapping checks','Ordinary Terminal optional performance archivist image alt bears Arthur; no stale public-name-unbound claim','Art Lab animation preview and all 12 archivist performance intentions use Arthur while internal-ID headings remain qualified','Mission Harness all archivist cues and full/reduced semantic alts use Arthur; optional missing-asset accessible fallback does too','Body plus accessibility snapshots exclude historical public names/raw standalone identity labels/stale language; grammatical role phrases and qualified internal/art IDs remain allowed','Internal IDs, assets, reducer progression and legacy saves remain unchanged','Exactly 74 client keys and same accepted SHA; mandatory missing/extra/injected answer keys fail closed','Truth/crosswalk/all 37 authoring files/frozen corpus/controller fixes byte-preserved; Lane C untouched','Zero external transport/credential access/lane messages']}
fs.writeFileSync(out+'TARGETED_REGRESSION_CONTRACT.json',JSON.stringify(contract,null,2)+'\n')
fs.writeFileSync(out+'README.md','# Lane A residual public-surface regression — PREPARED_NOT_SENT\n\nSupersedes prior unsent preparation only; nothing is transmittable before MAIN review. No message or supplier acceptance. Candidate commit/tree/parent are bound by packaged contract and outer manifest. New controller-owned source checks cover optional ordinary Terminal performance, Art Lab animation/all performance intentions, Mission Harness full/reduced/all cues, missing-asset accessible fallback and body/accessibility leak audit. Preserve prior office mapping checks and exact 74-key map SHA. Original immutable supplier tests run in their original-base fixture, not reinterpreted as integrated ownership. All 37 supplier additions remain unchanged and hash-bound; truth/frozen corpus/controller fixes are preserved. No theory/proof/exact/optional/title/final-density/performance-authoring copy is admitted. Lane C C1 queue receipt is reference-only; no integration or message. Stop for MAIN acceptance.\n')
fs.writeFileSync(report+'INPUT_ADMISSION.json',JSON.stringify({status:'PASS',inputZipSha256:INPUT_SHA,members:12,governedHashes:10,archiveBoundExceptions:['MANIFEST.sha256','VERIFY_INPUT.py'],validator:'PASS_IN_COMPLETE_ADMITTED_ROOT',referenceInstallByteIdentical:true,baselineReproducer:'Unchanged supplied code; FINDINGS with five manifestations and expect-baseline exit zero before source edits',credentialAccess:false},null,2)+'\n')
console.log(JSON.stringify({status:'PASS',packet:'PREPARED_NOT_SENT',files:files.length,acceptedAdditions:37,packetsSent:false}))
