import {identity,sha,freeze as deepFreeze,validateSchema} from '../nq5/schema.mjs'
import {parseExactJson} from '../nq5/exact-json.mjs'
import {CLARIFICATION} from './docs.mjs'
import {seal,CONTRACT_SHA} from './authority.mjs'
export const TGM='tgm/transfers',COUNTER='profiler/address/counterparties',DAI='0x6b175474e89094c44da98b954eedeac495271d0f'
export const WINDOW={from:'2023-03-13T08:45:00Z',to:'2023-03-13T12:15:00Z'}
export const HASHES=['0xc310a0affe2169d1f6feec1c63dbc7f7c62a887fa48795d327d4d2da2d6b111d','0x298bde3f9e53f7a5d870f7f5d56ee2f5e41fa25e6eb5e74611ac97025405db55','0xdae809e4a1ddf77c39d44a4acfe6165bedbc19a385c4b241242cc9bd582a80b9'].sort()
export const ADDRESS=/^0x[a-f0-9]{40}$/,HASH=/^0x[a-f0-9]{64}$/
export const CLAIMS=['CONTEXTUAL_PROVIDER_QUERY_ONLY','NO_CHAIN_COMPLETENESS_OR_NEGATIVE_PROOF','NO_IDENTITY_OWNERSHIP_INTENT_CAUSATION_OR_COORDINATION','NO_GAMEPLAY_INTEGRATION_OR_FORMAL_LEAD_ACCEPTANCE','NO_RAW_OR_BULK_PUBLIC_OUTPUT']
export function openapi(body){const blocks=[...body.toString('utf8').matchAll(/```json\n([\s\S]*?)\n```/g)].map(m=>JSON.parse(m[1]));const o=blocks.find(o=>o.openapi==='3.1.0'&&o.paths&&o.components);if(!o)throw new Error('P1_CURRENT_OPENAPI_REQUIRED');return o}
function rooted(o,n,{strict=true}={}){const schemas=structuredClone(o.components.schemas);if(strict)for(const s of Object.values(schemas))if(s.type==='object')s.additionalProperties=false;return {...schemas[n],components:{schemas}}}
const proof=(d,name)=>{const s=d.index.snapshots.find(s=>s.name===name);if(!s||s.httpStatus!==200||!s.bytes||!d.bodies[name])throw new Error('P1_REQUIRED_CURRENT_DOCUMENT');return {...s}}
export function contracts(d){
 // Secondary-family failure never invalidates independently proved TGM admission.
 for(const n of ['tgm','pricing','rates','coverage','redistribution','terms'])proof(d,n);
 const t=openapi(d.bodies.tgm),pricing=d.bodies.pricing.toString(),rates=d.bodies.rates.toString(),coverage=d.bodies.coverage.toString(),redistribution=d.bodies.redistribution.toString(),terms=d.bodies.terms.toString();
 const price=f=>{const escaped=f.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),m=new RegExp('<tr><td[^>]*>'+escaped+'</td><td[^>]*>([0-9]+)</td><td[^>]*>([0-9]+)</td></tr>').exec(pricing);if(!m||m[1]!==m[2])throw new Error('P1_EXACT_FAMILY_PRICING');return Number(m[1])};
 const tp=t.paths['/api/v1/'+TGM]?.post,filters=t.components.schemas.TGMTransfersFilters?.properties;
 if(!tp||!t.components.schemas.TGMTransfersChain.enum.includes('ethereum')||!['transaction_hash','from_address','to_address'].every(n=>filters[n]?.anyOf.some(x=>x.type==='string')&&filters[n].anyOf.some(x=>x.type==='array'))||!/ERC-20 tokens/.test(t.components.schemas.TGMTransfersRequest.description)||!coverage.includes('30 Jul 2015')||!coverage.includes('Historical data')||!rates.includes('75 requests')||!rates.includes('1,500 requests')||!rates.includes('15 requests')||!rates.includes('300 requests'))throw new Error('P1_PLAN_SPECIFIC_SUPPORT');
 if(!/\| tgm\/transfers\s*\| ✅ Allowed\s*\| Attribution required/.test(redistribution)||!redistribution.includes('Powered by Nansen API')||!terms.includes('raw or substantially unmodified')||!terms.includes('except where expressly permitted in our Data Redistribution Guidelines'))throw new Error('P1_PUBLIC_POLICY_NOT_ADMITTED');
 const common={schemaVersion:'1.0.0',executionContractSha256:CONTRACT_SHA,officialSourceIdentity:d.identity,chain:'ethereum',tokenAddress:DAI,window:WINDOW,page:1,perPage:100,attribution:'Powered by Nansen API',claims:CLAIMS,rawBulkOutputAllowed:false,unknownPrivateFieldsAllowed:false,smartMoneyOrLabelFiltersAllowed:false,gameplayIntegrationAccepted:false,ratePolicy:{unknownPlanUsesFreeLimits:true,freeSecond:15,freeMinute:300,proSecond:75,proMinute:1500,headroom:0.8,localTargetSecond:20,localTargetMinute:1200,noEndpointSpecificLimitForTheseFamilies:true,headersAndRetryAfterOverrideDownward:true},proofs:Object.fromEntries(['pricing','rates','coverage','redistribution','terms'].map(n=>[n,proof(d,n)]))};
 const tgm=seal({...common,family:TGM,path:'/api/v1/'+TGM,status:'ADMITTED_EXACT_P1_SCOPE',endpoint:proof(d,'tgm'),quotedCredits:price(TGM),requestSchema:rooted(t,'TGMTransfersRequest'),responseSchema:rooted(t,'TGMTransfersResponse'),projectionAllowlist:['transaction_hash','from_address','to_address','token_address','amount','evidence_grade','temporal_class','accepted_exact_time_reference'],omitted:['from_address_label','to_address_label','transfer_value_usd','transaction_type'],amountRule:'EXACT_UNSIGNED_NONZERO_JSON_NUMBER_DECIMAL_LEXEME_NO_EXPONENT_NO_ROUNDING_NO_USD_IMPUTATION',timeRule:'UNZONED_REMAINS_CONTEXTUAL_ACCEPTED_TRUTH_JOIN_IS_SEPARATE',historicalCoverage:'ETHEREUM_FROM_2015_07_30_NO_STRICTER_TGM_RETENTION_BOUND_DOCUMENTED',daiSupport:'FROZEN_ACCEPTED_DAI_ERC20_IDENTITY_JOIN_NOT_TOKEN_DISCOVERY'});
 let c=null,cost=null,resolved=false,assessment='HELD: secondary endpoint, price, coverage or exact affirmative policy proof is unavailable, changed or ambiguous; independently admitted TGM remains available.';
 const counterSnapshot=d.index.snapshots.find(s=>s.name==='counterparties')??null,clarificationSnapshot=d.index.snapshots.find(s=>s.name==='clarification')??null;
 try{
  proof(d,'counterparties');proof(d,'clarification');c=openapi(d.bodies.counterparties);cost=price(COUNTER);
  const bound=n=>{const s=d.index.snapshots.find(s=>s.name===n),b=d.bodies[n];return s&&b&&s.httpStatus===200&&s.sha256===sha(b)&&s.bytes===b.length};
  // Exact reviewed affirmative answer+controlling guide; no keyword grammar can
  // admit a changed, contradictory, truncated, source-free or generic answer.
  resolved=bound('counterparties')&&bound('clarification')&&bound('redistribution')&&d.index.clarificationRequests===1&&d.index.snapshots.filter(s=>s.name==='clarification').length===1&&clarificationSnapshot.url===CLARIFICATION&&sha(d.bodies.clarification)==='d5af5b57498cbbf9687cfe6a116deff5edd5cb19cd1945d5da9709fdeb06178c'&&sha(d.bodies.redistribution)==='8256159894b2c098d752c65c6efa2ef85641bedf1e7da02bc3e5434752739324'&&!!c.paths['/api/v1/'+COUNTER]?.post&&c.components.schemas.ProfilerChain.enum.includes('ethereum')&&c.components.schemas.GroupBy.enum.includes('wallet')&&c.components.schemas.SourceInput.enum.includes('Tokens')&&cost===5;
  if(resolved)assessment='ADMITTED: exact reviewed complete official affirmative plural-path answer, its current guide and endpoint citations, wallet address/count and required attribution are byte-bound. Optional aggregates are not admitted. Any answer or controlling-guide change holds this family for another exact review.';
 }catch{resolved=false}
 const counter=seal({...common,tokenAddress:null,tokenScope:'ALL_ETHEREUM_ERC20_INTERACTION_COUNTS_NOT_DAI_FILTERED',family:COUNTER,path:'/api/v1/'+COUNTER,status:resolved?'ADMITTED_EXACT_P1_WALLET_ADDRESS_COUNT_ONLY':'COUNTERPARTIES_HELD_PUBLIC_POLICY_AMBIGUOUS',endpoint:counterSnapshot,clarification:clarificationSnapshot,clarificationAssessment:assessment,reviewedClarificationSha256:'d5af5b57498cbbf9687cfe6a116deff5edd5cb19cd1945d5da9709fdeb06178c',quotedCredits:resolved?cost:null,requestSchema:resolved?rooted(c,'ProfilerAddressCounterpartiesRequest'):null,responseSchema:resolved?rooted(c,'ProfilerAddressCounterpartiesResponse'):null,projectionAllowlist:['counterparty_address','interaction_count'],omitted:['counterparty_address_label','total_volume_usd','volume_in_usd','volume_out_usd','tokens_info','entity_name'],groupBy:'wallet',sourceInput:'Tokens',aggregateSemanticsAdmitted:false,tokenAggregateSemanticsAdmitted:false,recursiveFrontierAuthority:false});
 if(tgm.quotedCredits!==1)throw new Error('P1_CREDIT_COST_CHANGED_REVIEW_REQUIRED');return {tgm,counter,official:d}
}
const requestCache=new WeakMap(),normalizationCache=new WeakMap()
export function validateRequest(q,admission){let cache=requestCache.get(admission);if(!cache)requestCache.set(admission,cache=new Map());const cacheKey=identity([q,admission.tgm,admission.counter]);if(cache.has(cacheKey))return cache.get(cacheKey);const a=q.family===TGM?admission.tgm:q.family===COUNTER?admission.counter:null;if(!a||!a.status.startsWith('ADMITTED_')||q.path!==a.path||q.method!=='POST'||identity(q.body.date)!==identity(WINDOW)||q.body.chain!=='ethereum'||identity(q.body.pagination)!==identity({page:1,per_page:100}))throw new Error('P1_EXACT_REQUEST_SCOPE');validateSchema('provider',q.body,a.requestSchema);if(q.family===TGM){if(q.body.token_address!==DAI||Object.keys(q.body).some(k=>!['chain','token_address','date','pagination','filters'].includes(k))||Object.keys(q.body.filters).length!==1)throw new Error('P1_TGM_EXACT_FILTERS');const[[n,v]]=Object.entries(q.body.filters);if(!['transaction_hash','from_address','to_address'].includes(n))throw new Error('P1_NO_LABEL_SMART_MONEY_FILTER');if(n==='transaction_hash'){if(identity(v)!==identity(HASHES))throw new Error('P1_HASH_BUNDLE_NOT_FRAGMENTED')}else if(!ADDRESS.test(v))throw new Error('P1_DIRECTION_SUBJECT')}else if(Object.keys(q.body).some(k=>!['chain','address','date','pagination','source_input','group_by','order_by'].includes(k))||!ADDRESS.test(q.body.address)||q.body.group_by!=='wallet'||q.body.source_input!=='Tokens'||identity(q.body.order_by)!==identity([{field:'interaction_count',direction:'DESC'}]))throw new Error('P1_COUNTER_WALLET_SCOPE');cache.set(cacheKey,a);return a}
const magnitude=x=>{if(typeof x!=='string'||x.length>100||!/^(?:0|[1-9]\d*)(?:\.\d{1,18})?$/.test(x)||!/[1-9]/.test(x))throw new Error('P1_EXACT_AMOUNT_REQUIRED');return x}
export const tuple=r=>identity([r.transaction_hash.toLowerCase(),r.from_address.toLowerCase(),r.to_address.toLowerCase(),r.token_address.toLowerCase(),r.amount])
export function normalize(q,raw,a,truth){if(!Buffer.isBuffer(raw))throw new Error('P1_RAW_BYTES');let cache=normalizationCache.get(a);if(!cache)normalizationCache.set(a,cache=new Map());const key=identity([q,a.tgm,a.counter,sha(raw),truth]);if(cache.has(key))return cache.get(key);const n=deepFreeze(normalizeUncached(q,raw,a,truth));if(cache.size>=128)cache.clear();cache.set(key,n);return n}
function normalizeUncached(q,raw,a,truth){const contract=validateRequest(q,a);if(!Buffer.isBuffer(raw)||raw.length>32000000)throw new Error('P1_RAW_BYTES');const exact=parseExactJson(raw),response=JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(raw));validateSchema('provider',response,contract.responseSchema);const p=response.pagination;if(p.page!==1||p.per_page!==100||typeof p.is_last_page!=='boolean'||response.data.length>100||!p.is_last_page&&!response.data.length)throw new Error('P1_PAGINATION');const rows=[],seen=new Set(),hashes=new Set(),stamps=new Map();for(let i=0;i<response.data.length;i++){const r=response.data[i],e=exact.data[i];let row;if(q.family===TGM){const h=r.transaction_hash.toLowerCase(),from=r.from_address.toLowerCase(),to=r.to_address.toLowerCase();if(!HASH.test(h)||!ADDRESS.test(from)||!ADDRESS.test(to)||!r.block_timestamp||typeof r.transfer_amount!=='number')throw new Error('P1_TRANSFER_CORE');const[[filter,subject]]=Object.entries(q.body.filters);if(filter==='transaction_hash'&&!subject.includes(h)||filter==='from_address'&&from!==subject||filter==='to_address'&&to!==subject)throw new Error('P1_FILTER_PARTICIPATION');const stamp=r.block_timestamp;if(!/^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})?$/.test(stamp))throw new Error('P1_CONTEXT_TIME');const zoned=/(?:Z|[+-]\d{2}:\d{2})$/.test(stamp),calendar=stamp.slice(0,19).replace(' ','T');if(calendar.slice(0,10)!=='2023-03-13'||!Number.isFinite(Date.parse(calendar+'Z'))||new Date(Date.parse(calendar+'Z')).toISOString().slice(0,19)!==calendar)throw new Error('P1_CONTEXT_DATE');if(stamps.has(h)&&stamps.get(h)!==stamp)throw new Error('P1_CONFLICTING_TRANSFER_TIMESTAMPS');stamps.set(h,stamp);if(zoned){const time=Date.parse(stamp.replace(' ','T'));if(!Number.isFinite(time)||time<Date.parse(WINDOW.from)||time>Date.parse(WINDOW.to))throw new Error('P1_ZONED_WINDOW');if(truth[h]&&time!==Date.parse(truth[h]))throw new Error('P1_TRUTH_TIME_CONFLICT')};row={transaction_hash:h,from_address:from,to_address:to,token_address:DAI,amount:magnitude(e.transfer_amount),evidence_grade:'CONTEXTUAL',temporal_class:zoned?'PROVIDER_ZONED_CONTEXTUAL':'SERVER_FILTERED_UNZONED_CONTEXTUAL'};if(truth[h])row.accepted_exact_time_reference={transaction_hash:h,utc:truth[h],source:'SEPARATELY_ACCEPTED_EULER_TRUTH_NOT_PROVIDER_TIME_INFERENCE'};hashes.add(h)}else{const address=r.counterparty_address.toLowerCase();if(!ADDRESS.test(address)||!Number.isSafeInteger(r.interaction_count)||r.interaction_count<1||address===q.body.address||address==='0x'+'0'.repeat(40)||address===DAI)throw new Error('P1_COUNTER_CORE');row={counterparty_address:address,interaction_count:r.interaction_count}}const id=q.family===TGM?tuple(row):identity(row);if(q.family===COUNTER&&rows.some(x=>x.counterparty_address===row.counterparty_address)&&!seen.has(id))throw new Error('P1_CONFLICTING_COUNTERPARTY');if(!seen.has(id)){seen.add(id);rows.push(row)}}
 if(q.family===TGM&&q.body.filters.transaction_hash&&HASHES.some(h=>!hashes.has(h)))throw new Error('P1_REQUIRED_HASH_RECONCILIATION_MISSING');const emptyRole=!rows.length&&p.is_last_page&&q.emptyResultRule==='BOUNDED_PROVIDER_COVERAGE_CLOSURE_NOT_NEGATIVE_PROOF';if(!rows.length&&!emptyRole)throw new Error('P1_EMPTY_UTILITY_NOT_ADMITTED');return {rows,resultCount:rows.length,normalizedSha256:identity(rows),pagination:p,emptyRole,claimBoundaries:CLAIMS,attribution:'Powered by Nansen API',recursiveFrontierAuthority:false,contextual:true,rawRecords:response.data.length,duplicateRows:response.data.length-rows.length}}
