import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {execFileSync} from 'node:child_process'
import {sha,identity} from '../nq5/schema.mjs'
import {gitEnv,instructions} from '../nq5-b1-r1/gates.mjs'
import {cut,digest,seal} from '../nq5-b4-filtered/authority.mjs'
export {cut,digest,seal}
export const BASE='4fb843eeafb750afef978f53f6169e5a890db629',TREE='4d3d7d297314729b9f994f7ca7b37819ffa13735',PARENT='b29d0ee215a55d1b1ab4710d4a0013d86affae74'
export const ARCHIVE='TRACE_ESCAPE_G6P_NQ5_T1_B3_R1_LEAD_ACCEPTANCE_FRONTIER_QUALITY_AND_FILTERED_BATCH4_EXECUTION_DELIVERY_v1.0.0.zip',ARCHIVE_SHA='ad405b74f09f1eed5aeec1f95a4e6831eebecf38a2f077312266d094f344a4a9'
export const OUTPUT='TRACE_ESCAPE_G6P_NQ5_T1_P1_TRANSACTION_FRONTIER_SATURATION_TGM_COUNTERPARTIES_PILOT_AND_SCALE_FREEZE_DELIVERY_v1.0.0.zip'
export const AUTH='LEAD-NQ5-T1-P1-BOUNDED-MULTI-FAMILY-PILOT-001',CONTRACT='docs/source/v1.9.0/P1_CONTRACT.txt',CONTRACT_SHA='22d9c3be3ace6a8ba94f9bf89a64649e4af423c245a37329efda7838c1e60ccb',MANIFEST='docs/source/ACTIVE_P1_SOURCE_MANIFEST.sha256'
export const REVIEWS=['docs/G6P_NQ5_T1_P1_PRELIVE_REVIEW.json','docs/G6P_NQ5_T1_P1_POSTLIVE_REVIEW.json']
export const REJECTIONS={HUB_ONLY_RECURSIVE_LINEAGE_SUPPRESSED:352,ALREADY_ISSUED_EQUIVALENT_CANONICAL_REQUEST:12,INFRASTRUCTURE_CONTROL_WITHOUT_CASE_SPECIFIC_NON_HUB_LINEAGE:6,B4_EXACT_PAGE1_ONLY:3,TOKEN_CONTRACT_EXCLUDED:2,SINGLE_SUPPORT_REQUIRES_TWO_DISTINCT_NON_HUB_TRANSACTIONS:1,ZERO_ADDRESS:1}
export const UNCHANGED=['01_PRODUCT_NARRATIVE_AND_ART_AUTHORITY.md','02_TECHNICAL_ARCHITECTURE_AND_DATA_BOUNDARIES.md','06_COMPETITION_RELEASE_AND_SUBMISSION.md','07_PUBLIC_SAFE_EULER_CASE_TRUTH.md','08_GAME_CONTRACTS_AND_SCHEMAS.json','10_REVIEW_SOURCE_AND_PROJECT_PROTOCOL.md']
export const external=()=>path.join(os.homedir(),'Downloads','TRACE_ESCAPE_PROJECT_SOURCE_PACK_v1.8.1_2026-09-16')
const git=(root,...a)=>execFileSync('git',a,{cwd:root,env:gitEnv(),encoding:'utf8',maxBuffer:256000000}).trimEnd()
export function historicalDigest(root){const names=git(root,'ls-tree','-r','--name-only',BASE).split('\n').filter(n=>n&&!/^(?:\.cursor\/|ART_PRODUCTION\/|artifacts\/)/.test(n)&&!/^docs\/G6P.*_REVIEW\.json$/.test(n)).sort();return identity(names.map(n=>[n,sha(execFileSync('git',['show',BASE+':'+n],{cwd:root,env:gitEnv(),maxBuffer:256000000}))]))}
export function source(root,{validate=false}={}){const text=fs.readFileSync(path.join(root,MANIFEST),'utf8'),lines=text.trimEnd().split('\n');if(lines.length!==80||!text.startsWith(fs.readFileSync(path.join(root,'docs/source/ACTIVE_B4_FILTERED_SOURCE_MANIFEST.sha256'),'utf8'))||sha(fs.readFileSync(path.join(root,CONTRACT)))!==CONTRACT_SHA)throw new Error('P1_SOURCE_AUTHORITY');for(const l of lines){const[h,n]=l.split('  ');if(sha(fs.readFileSync(path.join(root,n)))!==h)throw new Error('P1_SOURCE_HASH')};const dir=path.join(root,'docs/source/v1.9.0'),integrity=JSON.parse(fs.readFileSync(path.join(dir,'12_INTEGRITY.json'))),references=integrity.permanent_file_hashes.filter(r=>UNCHANGED.includes(r.filename));if(references.length!==6)throw new Error('P1_SIX_REFERENCE_FILES');for(const r of integrity.permanent_file_hashes){const file=path.join(UNCHANGED.includes(r.filename)?external():dir,r.filename),s=fs.lstatSync(file);if(!s.isFile()||s.isSymbolicLink())throw new Error('P1_HOT_SOURCE_METADATA');const b=fs.readFileSync(file);if(sha(b)!==r.sha256||b.length!==r.bytes)throw new Error('P1_HOT_SOURCE_IDENTITY')}
 let validation='PASS_EXACT_HASH_BINDINGS_VALIDATOR_NOT_RUN';if(validate){const temp=fs.mkdtempSync(path.join(os.tmpdir(),'trace-p1-source-validation-'));try{for(const r of integrity.permanent_file_hashes)fs.symlinkSync(path.join(UNCHANGED.includes(r.filename)?external():dir,r.filename),path.join(temp,r.filename));fs.symlinkSync(path.join(dir,'12_INTEGRITY.json'),path.join(temp,'12_INTEGRITY.json'));fs.mkdirSync(path.join(temp,'_TOOLS'));fs.symlinkSync(path.join(dir,'_TOOLS/VALIDATE_SOURCE_PACK.py'),path.join(temp,'_TOOLS/VALIDATE_SOURCE_PACK.py'));validation=JSON.parse(execFileSync('python3',[path.join(dir,'_TOOLS/VALIDATE_SOURCE_PACK.py'),temp],{env:{...gitEnv(),PYTHONDONTWRITEBYTECODE:'1'},encoding:'utf8'})).status}finally{fs.rmSync(temp,{recursive:true,force:true})}}
 instructions(root);return {schemaVersion:'1.0.0',status:validation,sourcePackVersion:'1.9.0',governedRepositorySourceFiles:80,replacementFilesInstalled:7,unchangedHotFilesReadOnlyReferences:6,unchangedHotFileBindings:references,noUnchangedFilesCopied:true,noSyncedProjectFilesModified:true,sourceManifestSha256:sha(Buffer.from(text)),executionContractSha256:CONTRACT_SHA}}
export function accepted(root){source(root);if(git(root,'rev-parse',BASE+'^{tree}')!==TREE||git(root,'rev-parse',BASE+'^')!==PARENT||historicalDigest(root)!=='c74335dd5caa3dbd3e6f6e80ea0636fbec428439b5f6c1af64922082a4926240')throw new Error('P1_B4_GIT_CUT');git(root,'merge-base','--is-ancestor',BASE,'HEAD');const archive=path.join(path.dirname(root),ARCHIVE);if(sha(fs.readFileSync(archive))!==ARCHIVE_SHA)throw new Error('P1_B4_ARCHIVE');const read=n=>execFileSync('unzip',['-p',archive,n],{env:gitEnv(),maxBuffer:256000000}),names=execFileSync('unzip',['-Z1',archive],{env:gitEnv(),encoding:'utf8'}).trimEnd().split('\n'),manifest=read('MANIFEST.sha256').toString().trimEnd().split('\n'),bytes={};if(names.length!==54||new Set(names).size!==54||manifest.length!==53)throw new Error('P1_B4_MEMBER_SET');for(const l of manifest){const h=l.slice(0,64),n=l.slice(66),b=read(n);if(!names.includes(n)||sha(b)!==h)throw new Error('P1_B4_MEMBER_HASH');if(n!=='GIT/trace-escape-complete.bundle'&&n!=='SOURCE_DIFF.patch')bytes[n]=b};const objects=Object.fromEntries(Object.entries(bytes).filter(([n])=>n.endsWith('.json')).map(([n,b])=>[n,JSON.parse(b)])),d=objects['DELIVERY_MANIFEST.json'];if(identity(d.candidate)!==identity({commit:BASE,tree:TREE})||d.status!=='BLOCKED_WITH_EVIDENCE'||d.leadAcceptedAfterB4!==8||d.newAttempts!==0||d.newKnownCredits!==0||d.privateMutation!==false||d.credentialAccess!==false)throw new Error('P1_B4_HOLD');const pins={'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':'a84d60054d6893e4f1c72a61c5ff005145e8512b87bb4dcadff1d98b2ed8c8a4','EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':'0069da99152f01852ffd15d862604ceb6c54b39174228e5fc0cb10842b72fe32','EVIDENCE/BATCH4_FILTERED_CANDIDATE_REJECTION_MATRIX.json':'fe83962a5f5b1e38c81063cd152bef98b99ec239060d221fc045d148e823d6f6'};for(const[n,h]of Object.entries(pins))if(identity(objects[n])!==h)throw new Error('P1_B4_DERIVED_IDENTITY');return {objects,bytes}}
