import fs from 'node:fs'
import path from 'node:path'
import {identity,sha,validateSchema} from '../nq5/schema.mjs'
import {baseline as b4Baseline} from '../nq5-b4-filtered/context.mjs'
import {loadAccepted} from '../nq5-b1/authority.mjs'
import {configuredCampaignRoots} from '../nq5-r3/genesis.mjs'
import {readMirrored,replay} from '../nq5-b1/store.mjs'
import {assertPrivateAncestry,assertRawInventory} from '../nq5-b1-r3/gate-proof.mjs'
import {B2_IDS,ISSUE_ORDER} from '../nq5-b3/authority.mjs'
import {accepted,cut,digest,source,seal} from './authority.mjs'
import {admittedCaptured as readCaptured} from './docs.mjs'
import {contracts,HASHES,tuple} from './admission.mjs'
import {acceptedProjection,saturation,freeze,canonical,validatePlan} from './planner.mjs'
export const LOCK='T1_P1_MULTI_FAMILY_EXECUTION_LOCK.json',LEDGER_SHA='3b4261db069e68ab6a257ac23857cd9011ec72bab5ec14834cdabc70e9a222f2'
export const OLD_LOCKS=['B1_EXECUTION_LOCK.json','B1_R3_RESUME_LOCK.json','T1_B2_EXECUTION_LOCK.json','T1_B3_EXECUTION_LOCK.json','GENESIS_COMMIT.json','genesis.json']
const proofs=new WeakMap()
export const contextFingerprint=c=>identity({root:c.root,source:c.source,prior:{objects:c.prior.objects,bytes:Object.fromEntries(Object.entries(c.prior.bytes).map(([n,b])=>[n,sha(b)]))},pubSchema:c.pubSchema,oldTransferIdentities:c.oldTransferIdentities??null,baselineState:c.state?{rows:c.state.rows,starts:[...c.state.starts],responses:[...c.state.responses],terminals:[...c.state.terminals],bytes:c.state.bytes,bytesSha256:c.state.bytesSha256}:null,official:{index:c.admission.official.index,bodies:Object.fromEntries(Object.entries(c.admission.official.bodies).map(([n,b])=>[n,sha(b)]))},admission:[identity(c.admission.tgm),identity(c.admission.counter),c.admission.official.identity],index:identity(c.index),receipt:identity(c.receipt),plans:[identity(c.plans.plan),identity(c.plans.reserve),identity(c.plans.policy)],state: c.baselineProof?identity(c.baselineProof):null,roots:c.roots,originalEnvelope:c.originalEnvelope,truth:c.truth})
export function prepare(root){const prior=accepted(root),docs=readCaptured(root),admission=contracts(docs),ops=JSON.parse(fs.readFileSync(path.join(root,'docs/source/v1.9.0/09_OPERATIONAL_CONTRACTS_AND_REGISTERS.json'))),pubSchema={type:'array',minItems:8,maxItems:8,uniqueItems:true,items:ops.documents.find(d=>d.filename==='19_NQ5_PUBLIC_CALL_INDEX.schema.json').document},index=acceptedProjection(prior.objects['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'],pubSchema.items);validateSchema('provider',index,pubSchema);const receipt=saturation(prior,identity(index)),plans=freeze(admission,receipt,index,prior.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json']),bytes=fs.readFileSync(path.join(root,'public/scenarios/euler-2023-false-exit/scenario.json')),scenario=JSON.parse(bytes);if(sha(bytes)!=='a8634ef0b76f3b53d2fa3c30ddb16a2e94aed7f34fd976b9ba2ef84cb4a114c1')throw new Error('P1_ACCEPTED_TRUTH_SOURCE');const times=Object.fromEntries(HASHES.map(h=>{const row=scenario.evidence.find(e=>e.transactionHash===h&&e.grade==='EXACT'&&e.proofGrade==='EXACT_EVENT');if(!row)throw new Error('P1_EXACT_TRUTH_HASH_JOIN');return [h,row.observedAtUtc]}));return {root,prior,admission,index,pubSchema,receipt,plans,truth:times,source:{candidate:cut(root),implementationSha256:digest(root)}}}
export function ledgerEnvelope(c){return {...c.originalEnvelope,executionOrder:[...c.originalEnvelope.executionOrder,...B2_IDS,...ISSUE_ORDER,...c.plans.plan.executionOrder]}}
export function baseline(root){source(root,{validate:true});const c=prepare(root),old=b4Baseline(root);c.roots=old.prior.state.roots;c.originalEnvelope=old.prior.a.context.bound.envelope;c.state=old.r.current;c.oldTransferIdentities=[...new Set(old.sources.flatMap(p=>p.admission.normalizedRecords.map(tuple)))].sort();validatePlan(c.plans.plan.requests,c.admission,[...c.state.starts.values()].map(s=>{const old=oldRequest(c,s.logicalId);return old?canonical(old):s.logicalId}));const locks=Object.fromEntries(OLD_LOCKS.map(n=>[n,sha(readMirrored(c.roots,n))]));c.baselineProof=seal({schemaVersion:'1.0.0',campaignId:c.receipt.campaignId,ledgerSha256:LEDGER_SHA,ledgerBytes:87416,ledgerRows:39,oldGlobalDistinctIdentitySha256:identity(c.oldTransferIdentities),oldPerCallNormalizedRowSum:780,oldGlobalDistinctTransferIdentityCount:772,allThirteenRawMirrorsAndSemanticsRevalidated:true,b4SaturationReceiptIdentity:c.receipt.hash,oldLocks:locks,oldLastLedgerHash:c.state.rows.at(-1).hash,historicalAcceptedIndexIdentity:identity(c.prior.objects['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json']),attemptHashesAndProviderIds:[...c.state.responses.values()].map(r=>({logicalId:r.logicalId,attempt:r.attempt,providerRequestId:r.providerRequestId??null,httpStatus:r.httpStatus,actualCredits:r.actualCredits,rawSha256:r.rawSha256,rawBytes:r.rawBytes}))});proofs.set(c,contextFingerprint(c));return c}
function oldRequest(c,id){const a=c.prior.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'];const r=a.records.find(r=>r.logicalId===id);return r?.canonicalRequest??null}
export function assertBaseline(c,{privateState=false}={}){if(!proofs.has(c)||proofs.get(c)!==contextFingerprint(c)||identity(c.source)!==identity({candidate:cut(c.root),implementationSha256:digest(c.root)}))throw new Error('P1_BRANDED_CURRENT_BASELINE_REQUIRED');assertPrivateAncestry(c.roots);if(privateState){const expected=[...OLD_LOCKS,'qualification.jsonl','raw-b1'].sort().join();for(const root of c.roots)if(fs.readdirSync(root).sort().join()!==expected)throw new Error('P1_PRELIVE_PRIVATE_INVENTORY_CHANGED');const b=readMirrored(c.roots,'qualification.jsonl');if(b.length!==87416||sha(b)!==LEDGER_SHA)throw new Error('P1_PRELIVE_PRIVATE_BASELINE_CHANGED');for(const[n,h]of Object.entries(c.baselineProof.oldLocks))if(sha(readMirrored(c.roots,n))!==h)throw new Error('P1_PRIOR_LOCK_CHANGED');const fresh=replay(c.roots,ledgerEnvelope(c));assertRawInventory(c.roots,[...fresh.responses.values()].map(r=>r.rawName));if(identity(fresh.rows)!==identity(c.state.rows)||fresh.starts.size!==13||fresh.terminals.size!==13)throw new Error('P1_UNRESOLVED_BASELINE')}return true}
export function persistBaseline(c){assertBaseline(c,{privateState:true});const identities=path.join(c.root,'artifacts/g6p-p1/BASELINE_TRANSFER_IDENTITIES.json');fs.mkdirSync(path.dirname(identities),{recursive:true});if(fs.existsSync(identities)){if(identity(JSON.parse(fs.readFileSync(identities)))!==c.baselineProof.oldGlobalDistinctIdentitySha256)throw new Error('P1_BASELINE_IDENTITIES_CHANGED')}else fs.writeFileSync(identities,JSON.stringify(c.oldTransferIdentities)+'\n',{flag:'wx'});const f=path.join(c.root,'artifacts/g6p-p1/BASELINE_REVALIDATION.json');fs.mkdirSync(path.dirname(f),{recursive:true});if(fs.existsSync(f)){if(identity(JSON.parse(fs.readFileSync(f)))!==identity(c.baselineProof))throw new Error('P1_BASELINE_RECORD_NO_REWRITE')}else fs.writeFileSync(f,JSON.stringify(c.baselineProof,null,2)+'\n',{flag:'wx'})}
export function postContext(root){const c=prepare(root);c.roots=configuredCampaignRoots().map(r=>path.join(r,c.receipt.campaignId));assertPrivateAncestry(c.roots);c.originalEnvelope=loadAccepted(root).envelope;c.baselineProof=JSON.parse(fs.readFileSync(path.join(root,'artifacts/g6p-p1/BASELINE_REVALIDATION.json')));const{hash,...payload}=c.baselineProof;if(hash!==identity(payload)||payload.b4SaturationReceiptIdentity!==c.receipt.hash||payload.ledgerSha256!==LEDGER_SHA||payload.ledgerBytes!==87416||payload.allThirteenRawMirrorsAndSemanticsRevalidated!==true)throw new Error('P1_EXACT_BASELINE_PROOF');const bytes=readMirrored(c.roots,'qualification.jsonl');if(bytes.length<87416||sha(bytes.subarray(0,87416))!==LEDGER_SHA)throw new Error('P1_HISTORICAL_LEDGER_CHANGED');for(const[n,h]of Object.entries(payload.oldLocks))if(sha(readMirrored(c.roots,n))!==h)throw new Error('P1_HISTORICAL_LOCK_CHANGED');c.state=replay(c.roots,ledgerEnvelope(c));assertRawInventory(c.roots,[...c.state.responses.values()].map(r=>r.rawName));return c}
