import fs from 'node:fs'
import path from 'node:path'
import https from 'node:https'
import {sha,identity} from '../nq5/schema.mjs'
export const PAGES=Object.freeze({index:'https://docs.nansen.ai/llms.txt',tgm:'https://docs.nansen.ai/api/token-god-mode/token-transfers.md',counterparties:'https://docs.nansen.ai/api/profiler/address-counterparties.md',pricing:'https://docs.nansen.ai/getting-started/credits.md',rates:'https://docs.nansen.ai/getting-started/rate-limits.md',coverage:'https://docs.nansen.ai/api/data-coverage.md',redistribution:'https://docs.nansen.ai/guides/redistribution-guide.md'})
export const QUESTION='Does the redistribution allowance for profiler/address/counterparty apply to POST /api/v1/profiler/address/counterparties? If yes, state the exact public fields and attribution requirements for group_by=wallet results and cite the controlling current documentation.'
export const CLARIFICATION=PAGES.redistribution+'?ask='+encodeURIComponent(QUESTION)
export const TERMS='https://nansen.ai/legal/api'
export function admittedCaptured(root){const d=readCaptured(root),dir=path.join(root,'docs/official/p1'),index=JSON.parse(fs.readFileSync(path.join(dir,'INDEX.json'))),encoded=JSON.parse(fs.readFileSync(path.join(dir,'CAPTURED_DOCUMENT_BYTES.json')));if(encoded.encoding!=='UTF8_JSON_TEXT_EXACT_NO_NEWLINE_TRANSFORM'||identity(index)!==d.identity)throw new Error('P1_GOVERNED_CURRENT_DOCUMENT_INDEX');for(const s of index.snapshots){const b=Buffer.from(encoded.bodies[s.name],'utf8');if(!b.equals(d.bodies[s.name])||sha(b)!==s.sha256||b.length!==s.bytes)throw new Error('P1_GOVERNED_DOCUMENT_BYTES')}return d}
export function permitted(url,terms){if(Object.values(PAGES).includes(url)||url===CLARIFICATION||url===TERMS)return true;return typeof terms==='string'&&url===terms&&/^https:\/\/(?:www\.)?nansen\.ai\/[a-z0-9/-]*api[a-z0-9/-]*terms[a-z0-9/-]*$/.test(url)}
export async function captureTerms(root){const d=readCaptured(root);if(d.index.snapshots.some(s=>s.name==='terms'))throw new Error('P1_TERMS_NO_REENTRY');const r=await get(TERMS),dir=path.join(root,'artifacts/g6p-p1/docs');fs.writeFileSync(path.join(dir,'terms.md'),r.bytes,{flag:'wx'});d.index.unauthenticatedDocumentationGets++;d.index.snapshots.push({name:'terms',url:TERMS,retrievedAtUtc:r.retrievedAtUtc,httpStatus:r.httpStatus,bytes:r.bytes.length,sha256:sha(r.bytes),filename:'terms.md',transport:r.transport,discovery:'Redistribution guide links general terms; API SERVICES section links this controlling API supplement.'});delete d.index.termsStatus;d.index.webNavigation={toolInvocations:4,pageNavigationOperations:5,includesFailedRedistributionNavigation:true,exactUnderlyingHttpGetCountAvailable:false,scope:'BOUNDED_SAME_CURRENT_DOCUMENTS_AND_CONTROLLING_TERMS_PATH_DISCOVERY_NO_SEARCH',authenticatedRequests:0};fs.writeFileSync(path.join(dir,'INDEX.json'),JSON.stringify(d.index,null,2)+'\n');process.stdout.write('P1_DOC terms status '+r.httpStatus+' bytes '+r.bytes.length+' sha256 '+sha(r.bytes)+'\n');return readCaptured(root)}
export function get(url,terms){if(!permitted(url,terms))throw new Error('P1_UNAUTHORIZED_DOCUMENT_URL');return new Promise(resolve=>{let settled=false;const finish=(httpStatus,bytes,transport)=>{if(settled)return;settled=true;clearTimeout(timer);resolve({httpStatus,bytes,transport,retrievedAtUtc:new Date().toISOString()})},req=https.get(url,{agent:false,headers:{Accept:'text/markdown,text/plain;q=0.9','User-Agent':'TRACE-ESCAPE-P1-bounded-documentation'}},res=>{const chunks=[];let size=0;res.on('data',b=>{size+=b.length;if(size>4000000){req.destroy();return}chunks.push(b)});res.on('end',()=>finish(res.statusCode,Buffer.concat(chunks),'UNAUTHENTICATED_HTTPS_GET_NO_REDIRECT'));res.on('error',()=>finish(null,Buffer.alloc(0),'RETRIEVAL_UNAVAILABLE'));res.on('aborted',()=>finish(null,Buffer.alloc(0),'RETRIEVAL_UNAVAILABLE'))});const timer=setTimeout(()=>req.destroy(),30000);req.on('error',()=>finish(null,Buffer.alloc(0),'RETRIEVAL_UNAVAILABLE'))})}
export async function capture(root){const dir=path.join(root,'artifacts/g6p-p1/docs');if(fs.existsSync(dir))throw new Error('P1_DOCUMENT_CAPTURE_NO_REENTRY');fs.mkdirSync(dir,{recursive:true});const index={schemaVersion:'1.0.0',scope:'P1_BOUNDED_OFFICIAL_DOCUMENTS',snapshots:[],unauthenticatedDocumentationGets:0,clarificationRequests:0,credentialAccess:false,authenticatedProviderRequests:0,accountRequests:0,browserRuntimeRequests:0},bodies={};const put=async(name,url,terms)=>{index.unauthenticatedDocumentationGets++;if(name==='clarification')index.clarificationRequests++;const r=await get(url,terms),filename=name+'.md';fs.writeFileSync(path.join(dir,filename),r.bytes,{flag:'wx'});bodies[name]=r.bytes.toString('utf8');index.snapshots.push({name,url,retrievedAtUtc:r.retrievedAtUtc,httpStatus:r.httpStatus,bytes:r.bytes.length,sha256:sha(r.bytes),filename,transport:r.transport});fs.writeFileSync(path.join(dir,'INDEX.json'),JSON.stringify(index,null,2)+'\n');process.stdout.write('P1_DOC '+name+' status '+r.httpStatus+' bytes '+r.bytes.length+' sha256 '+sha(r.bytes)+'\n')};for(const[name,url]of Object.entries(PAGES))await put(name,url);const links=[...bodies.redistribution.matchAll(/https:\/\/(?:www\.)?nansen\.ai\/[a-z0-9/-]*api[a-z0-9/-]*terms[a-z0-9/-]*/g)].map(m=>m[0]);const terms=[...new Set(links)].find(url=>permitted(url,url));if(terms)await put('terms',terms,terms);else{index.termsStatus='NO_IDENTIFIABLE_CONTROLLING_API_TERMS_LINK';fs.writeFileSync(path.join(dir,'INDEX.json'),JSON.stringify(index,null,2)+'\n')};await put('clarification',CLARIFICATION);return readCaptured(root)}
export function readCaptured(root){const dir=path.join(root,'artifacts/g6p-p1/docs'),read=n=>{for(const d of [root,path.join(root,'artifacts'),path.join(root,'artifacts/g6p-p1'),dir]){const m=fs.lstatSync(d);if(!m.isDirectory()||m.isSymbolicLink()||m.uid!==process.getuid())throw new Error('P1_DOCUMENT_DIRECTORY_METADATA')};const f=path.join(dir,n),s=fs.lstatSync(f);if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1||s.uid!==process.getuid()||s.size>4000000)throw new Error('P1_DOCUMENT_FILE_METADATA');const fd=fs.openSync(f,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const opened=fs.fstatSync(fd);if(opened.dev!==s.dev||opened.ino!==s.ino||opened.size!==s.size)throw new Error('P1_DOCUMENT_FILE_RACE');const b=fs.readFileSync(fd),after=fs.fstatSync(fd);if(after.size!==opened.size||after.mtimeMs!==opened.mtimeMs)throw new Error('P1_DOCUMENT_FILE_RACE');return b}finally{fs.closeSync(fd)}},index=JSON.parse(read('INDEX.json')),bodies={};if(index.clarificationRequests!==1||index.snapshots.filter(s=>s.name==='clarification').length!==1)throw new Error('P1_EXACTLY_ONE_CLARIFICATION');for(const s of index.snapshots){if(!/^[a-z]+\.md$/.test(s.filename)||s.filename!==s.name+'.md'||!permitted(s.url,index.snapshots.find(s=>s.name==='terms')?.url))throw new Error('P1_DOCUMENT_SCOPE');const b=read(s.filename);if(sha(b)!==s.sha256||b.length!==s.bytes)throw new Error('P1_DOCUMENT_HASH');bodies[s.name]=b}return {index,bodies,identity:identity(index)}}
