import fs from 'node:fs'
import path from 'node:path'
import {identity,sha,validateSchema} from '../nq5/schema.mjs'
import {seal,source} from './authority.mjs'
import {baseline,persistBaseline,postContext,LEDGER_SHA} from './context.mjs'
import {requestAudit,auditSchema,attemptRecord} from './audit.mjs'
import {reconcile,utility,nextFrontier} from './reconciliation.mjs'
import {TGM,COUNTER,CLAIMS} from './admission.mjs'
export const serialize=x=>Buffer.isBuffer(x)?x:Buffer.from(typeof x==='string'?x:JSON.stringify(x,null,2)+'\n')
export function lessons(root){const o=JSON.parse(fs.readFileSync(path.join(root,'docs/source/v1.9.0/09_OPERATIONAL_CONTRACTS_AND_REGISTERS.json'))),old=o.documents.find(d=>d.filename==='QUALIFICATION_LESSONS_REGISTER.json').document.lessons,add=[['Truthful saturation triggers a pivot','Never weaken filters to manufacture count.','377 exact B4 rejection rows and zero B4 ordinary requests remain sealed.'],['Diversification follows measured exhaustion','Do not reopen ordinary Address Transactions recursion.','Only exact current TGM and conditionally admitted Counterparties enter the pilot.'],['Bundle exact-hash reconciliation','One bounded question is one three-hash request.','One sorted three-hash canonical identity; no single-hash fragmentation.'],['Diversity is not utility','A family badge cannot supply a question or consumer.','Ten named questions with distinct purpose, coverage, empty role and consumers.'],['Redistribution is path-specific','Generic allowances cannot silently admit a plural path.','Exactly one official clarification; ambiguous Counterparties stays held.'],['Raw and bulk remain private','Redistributable does not mean public raw export.','Audit metadata only; strips labels, free text, USD and unadmitted aggregates.'],['Scale starts after representative support','Do not extrapolate branching or prepopulate later batches.','Four durable canary calls;75% support/two gains/non-saturated non-hub utility; P2 never issues.']];if(old.length!==25)throw new Error('P1_ALL_TWENTY_FIVE_LESSONS_REQUIRED');return {schemaVersion:'1.0.0',sourceEpoch:'1.9.0',carriedForwardCount:25,addedCount:7,lessons:[...old,...add.map(([name,accepted_rule,required_test_or_invariant],i)=>({id:'P1-L'+String(i+26).padStart(3,'0'),name,false_success_mechanism:'Count or claim substituted for measured useful evidence.',accepted_rule,required_test_or_invariant}))]}}
function pending(c){const audit=requestAudit(c,c.state,()=>{throw new Error('P1_NOT_ISSUED_RAW_FORBIDDEN')}),report={schemaVersion:'1.0.0',status:'OFFLINE_GATES_PENDING_NO_ISSUE',campaignId:c.receipt.campaignId,httpAttempts:13,provider2xx:13,supplierCountedTerminals:11,leadAcceptedBeforeP1:8,leadAcceptedAfterP1:8,permanentlyHeldSupplierTerminals:3,newAttempts:0,newDistinctRequests:0,newLocalSupportCandidates:0,newKnownCredits:0,knownCampaignCredits:13,retries:0,unresolvedReservations:0,unresolvedTerminals:0,clean:true,ledgerSha256:LEDGER_SHA,ledgerBytes:87416,allPrimaryMirrorRawEqual:true,historicalThirteenAttemptsResponsesTerminalsAndMirrorsUnchanged:true,latestSafeResponseBalance:625707,protectedReserve:250,accountWideDecrease:4320,campaignAttributedCredits:13,unattributedAccountWideChange:4307,causeAssigned:false,publicAcceptedIndexRows:8,publicPendingIndexRows:0,p1PendingLocalCandidateRows:0,acceptedPublicIndexIdentity:identity(c.index),requestAuditIdentity:identity(audit),actualPrivateStateAccess:true,credentialAccess:false,privateMutation:false,reviewerExternalRequests:0,unauthenticatedDocumentationGets:c.admission.official.index.unauthenticatedDocumentationGets,webDocumentationNavigationToolInvocations:4,webDocumentationPageNavigationOperations:5,webNavigationUnderlyingHttpGetCount:null,authenticatedCampaignProviderRequests:0,authenticatedCampaignProviderRequestsByFamily:{[TGM]:0,[COUNTER]:0},accountRequests:0,browserRuntimeProviderRequests:0,AUTHORIZED_TO_ISSUE:false,P2_AUTHORIZED_TO_ISSUE:false},execution={stopReason:null,newAttempts:0,newActualCredits:0,newLocalSupportCandidates:0,unresolvedReservedCredits:0,maximumInFlight:0,canaryRequests:4,noReplacement:true,noThirteenthRequest:true,P2Requests:0};return {audit,report,projections:[],state:c.state,execution}}
export function derive(root,{post=false,executionEnvelope,execution}={}){const c=post?postContext(root):baseline(root);if(!post)persistBaseline(c);const r=post?reconcile(c,executionEnvelope,execution):pending(c);validateSchema('provider',r.audit,auditSchema(c));const u=utility(c,r),f=nextFrontier(c,r,u),status=post&&!r.execution.stopReason&&r.report.clean?'DELIVERED_PENDING_LEAD_REVIEW':post?'BLOCKED_WITH_EVIDENCE':'PRELIVE_PENDING',indexBytes=serialize(c.index),e=post?executionEnvelope:seal({schemaVersion:'1.0.0',status:'OFFLINE_GATES_PENDING_NO_ISSUE',candidate:c.source.candidate,implementationSha256:c.source.implementationSha256,b4SaturationReceiptIdentity:c.receipt.hash,officialSourceIdentity:c.admission.official.identity,planIdentity:c.plans.plan.hash,reserveIdentity:c.plans.reserve.hash,frontierPolicyIdentity:c.plans.policy.hash,AUTHORIZED_TO_ISSUE:false}),utilityReport={schemaVersion:'1.0.0',status:post?'MEASURED_PILOT_LOCAL_SUPPORT_PENDING_LEAD':'NO_LIVE_MEASUREMENT_YET',...u,completeP2CandidateRows:f.matrix.completeCandidateRows,p2FrozenMeaningfulRequests:f.plan?.requests.length??0,p2Gate:f.matrix.gate,p2PlanGenerated:!!f.plan,P2_AUTHORIZED_TO_ISSUE:false,p2RequestsIssued:0,transactionFamilySaturationPreserved:true,sourceClassesPlanningOnly:true,providerLabelsUsed:false,credibleRemaining1024PathEstablished:false,remainingLeadAcceptedFloor:1016,routeViabilityAssessment:post?(f.plan?'PILOT_SHOWS_A_BOUNDED_MEANINGFUL_UNISSUED_NON_HUB_NEXT_STEP_NOT_A_VALIDATED_1024_PATH':'PILOT_HAS_NO_ADMITTED_NON_SATURATED_SCALE_PLAN_UNDER_CURRENT_GATES'):'NO_PROVIDER_MEASUREMENT_NO_SCALE_OR_FLOOR_PROJECTION',noRawBranchingExtrapolation:true,noGlobalExhaustionOrNegativeProof:true,claimBoundaries:CLAIMS,gameplayIntegrationAccepted:false},entries={
 'SOURCE_INSTALL/V1_9_0_SOURCE_SYNC_INSTALLATION_REPORT.json':source(root,{validate:true}),
 'RECEIPTS/B4_FRONTIER_SATURATION_ACCEPTANCE_RECEIPT.json':c.receipt,
 'CONTRACTS/TGM_TRANSFERS_OFFICIAL_CONTRACT_ADMISSION.json':c.admission.tgm,
 'SCHEMAS/TGM_TRANSFERS_RESPONSE_COMPATIBILITY.schema.json':fs.readFileSync(path.join(root,'schemas/TGM_TRANSFERS_RESPONSE_COMPATIBILITY.schema.json')),
 'EXECUTION/T1_P1_MULTI_FAMILY_PILOT_ENVELOPE.json':e,
 'PLANS/T1_P1_MULTI_FAMILY_PILOT_PLAN.json':c.plans.plan,'PLANS/T1_P1_RESERVE_PLAN.json':c.plans.reserve,'PLANS/T1_P1_FRONTIER_POLICY.json':c.plans.policy,
 'REPORTS/T1_P1_EXECUTION_REPORT.json':{schemaVersion:'1.0.0',status,...r.execution,credentialResolutionAttempted:post,credentialAccess:post,privateMutation:post,...Object.fromEntries(Object.entries(r.report).filter(([k])=>/Requests|Gets|Navigation/.test(k))),issueAuthorizationHistorical:post,AUTHORIZED_TO_ISSUE:false},
 'REPORTS/T1_P1_RECONCILIATION_REPORT.json':r.report,'REPORTS/T1_P1_UTILITY_AND_ROUTE_VIABILITY_REPORT.json':utilityReport,
 'REPORTS/T1_CAMPAIGN_STATE_REDACTED.json':{...r.report,qualificationFloorClaimed:false,gameplayIntegrationAccepted:false,finalQualificationClaimed:false},
 'SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json':auditSchema(c),'SCHEMAS/NQ5_PUBLIC_CALL_INDEX.schema.json':c.pubSchema,
 'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':indexBytes,'PUBLIC/NQ5_PUBLIC_CALL_INDEX.sha256':sha(indexBytes)+'  NQ5_PUBLIC_CALL_INDEX.json\n',
 'EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':r.audit,
 'EVIDENCE/P1_LIVE_REQUEST_IDENTITY_MATRIX.json':{schemaVersion:'1.0.0',planIdentity:c.plans.plan.hash,requests:r.audit.p1Records,canonicalRequestIdsIndependentlyRecomputed:true,formalLeadAcceptanceNew:0},
 'EVIDENCE/P1_ATTEMPT_CREDIT_COUNT_AND_PROVIDER_ID_RECONCILIATION.json':{...r.report,priorAttempts:c.baselineProof.attemptHashesAndProviderIds,newAttemptsDetail:r.audit.p1Records.flatMap(q=>q.attempts.map(a=>({logicalId:q.request.logicalId,family:q.request.family,...a})))},
 'EVIDENCE/P1_PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json':{...r.report,publicIndexFileSha256:sha(indexBytes),originalLedgerPrefixSha256:LEDGER_SHA,originalLedgerPrefixBytes:87416,acceptedIndexRepresentationMigrationOnly:true,historicalPublicRecordsAndSequencesImmutable:true,permanentlyHeldCallsExcluded:true,rawBodiesIncluded:false,privatePathsIncluded:false},
 'EVIDENCE/P2_CANDIDATE_REJECTION_MATRIX.json':f.matrix,
 'EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json':lessons(root),
 'OFFICIAL_DOCS/INDEX.json':c.admission.official.index
 };for(const s of c.admission.official.index.snapshots)entries['OFFICIAL_DOCS/'+s.filename]=c.admission.official.bodies[s.name];if(c.admission.counter.status.startsWith('ADMITTED_')){entries['CONTRACTS/ADDRESS_COUNTERPARTIES_OFFICIAL_CONTRACT_ADMISSION.json']=c.admission.counter;entries['SCHEMAS/ADDRESS_COUNTERPARTIES_PUBLIC_PROJECTION.schema.json']=fs.readFileSync(path.join(root,'schemas/ADDRESS_COUNTERPARTIES_PUBLIC_PROJECTION.schema.json'))}if(f.plan){entries['PLANS/T1_P2_CANDIDATE_PLAN.json']=f.plan;entries['PLANS/T1_P2_RESERVE_PLAN.json']=f.reserve;entries['PLANS/T1_P2_FRONTIER_POLICY.json']=f.policy}return {c,r,u,f,entries,status,report:r.report}}
