import fs from 'node:fs'
import { describe, it, expect } from 'vitest'
import { identity,validateSchema } from '../../scripts/nq5/schema.mjs'
import { logicalRequest } from '../../scripts/nq5/planner.mjs'
import { classify,quality,REGISTRY } from '../../scripts/nq5-b4-filtered/quality.mjs'
import { enumerate,admissionGate } from '../../scripts/nq5-b4-filtered/planner.mjs'
import { seal } from '../../scripts/nq5-b4-filtered/authority.mjs'
import { lessons } from '../../scripts/nq5-b4-filtered/lessons.mjs'
import { pathScan } from '../../scripts/nq5-b1-r2/privacy.mjs'
const address=n=>'0x'+n.toString(16).padStart(40,'0'),hash=n=>'0x'+n.toString(16).padStart(64,'0'),token=address(999),truth={seedAddresses:[],times:{},sha256:identity('truth')},lead={hash:identity('lead')}
const template={family:'profiler/address/transactions',method:'POST',path:'/api/v1/profiler/address/transactions',contractHash:identity('contract'),publicProjectionPolicy:{},body:{address:address(1),chain:'ethereum',date:{from:'2023-03-13T08:45:00Z',to:'2023-03-13T12:15:00Z'},pagination:{page:1,per_page:100}}}
const record=(from,to,n)=>({transaction_hash:hash(n),from_address:from,to_address:to,token_address:token,amount:'1'})
function source(n,rows,pagination={is_last_page:true}){const body={...template.body,address:address(n)};return {logicalId:identity('source'+n),request:{...template,body},admission:{resultCount:rows.length,normalizedRecords:rows},semantic:{tokenContracts:[token],stats:{rawTransactionRecords:rows.length}},pagination}}
const build=(sources,options={})=>enumerate({sources,truth,issuedRequests:[],template,qualityReport:quality(sources,options.truth??truth,lead),...options})
describe('filtered B4 read-only admission',()=>{
 it('single transaction is not sufficient bounded utility',()=>{const p=source(1,[record(address(1),address(2),1)]),f=build([p]);expect(f.requests).toHaveLength(0);expect(f.matrix.rows[0].rejectionCode).toBe('SINGLE_SUPPORT_REQUIRES_TWO_DISTINCT_NON_HUB_TRANSACTIONS')})
 it('two distinct transactions support candidate-specific dead-end purpose',()=>{const f=build([source(1,[record(address(1),address(2),1),record(address(1),address(2),2)])]);expect(f.requests[0].lens).toBe('RELATIONSHIPS');expect(f.requests[0].purpose).toBe('DEAD_END_DISCOVERY');expect(f.requests[0].consumers.some(c=>c.startsWith('DEADEND.TEST'))).toBe(true)})
 it('two rows of one transaction do not pass the distinct transaction rule',()=>{const rows=[record(address(1),address(2),1),{...record(address(1),address(2),1),amount:'2'}];expect(build([source(1,rows)]).requests).toHaveLength(0)})
 it('independent non-hub repeats retain flow role',()=>{const f=build([source(1,[record(address(1),address(3),1)]),source(2,[record(address(2),address(3),2)])]);expect(f.requests[0].purpose).toBe('FLOW_DIRECTION_QUERY');expect(f.requests[0].lens).toBe('RELATIONSHIPS')})
 it('one supporting request repeated does not become independent support',()=>{const f=build([source(1,[record(address(1),address(2),1),record(address(1),address(2),1)])]);expect(f.requests).toHaveLength(0)})
 it('unused accepted seed has activity anchor metadata',()=>{const t={...truth,seedAddresses:[address(4)]},f=build([],{truth:t});expect(f.requests[0].purpose).toBe('ANCHOR_ACTIVITY_PAGE');expect(f.requests[0].consumers[0]).toContain('SEED.CONTEXT.TEST')})
 it('exact accepted hash preserves receipt/thread metadata',()=>{const t={...truth,times:{[hash(1)]:'accepted'}},f=build([source(1,[record(address(1),address(2),1)])],{truth:t});expect(f.requests[0].purpose).toBe('TRACE_THREAD_LINK_TEST');expect(f.requests[0].lens).toBe('RECEIPT')})
 it('ordinary caps count every contributing source',()=>{const rows=[];for(let n=10;n<16;n++)rows.push(record(address(1),address(n),n),record(address(1),address(n),n+100));const f=build([source(1,rows)]);expect(f.requests).toHaveLength(4);expect(f.matrix.rows.filter(r=>r.rejectionCode==='DEFERRED_SOURCE_FANOUT_CAP_4')).toHaveLength(2)})
 it('known source classes suppress recursion even when low volume',()=>{for(const s of Object.keys(REGISTRY)){const p=source(1,[record(s,address(2),1)]);p.request.body.address=s;const c=classify(p,truth);expect(c.recursiveFrontierAuthority).toBe(false);expect(c.boundedControlValue).toBe(true);expect(c.playerFacingLabel).toBe(false)}})
 it('unique admitted row threshold suppresses unclassified hub',()=>{const p=source(1,Array.from({length:100},(_,i)=>record(address(1),address(2),i+1)));expect(classify(p,truth).sourceQualityClass).toBe('HIGH_DEGREE_UNCLASSIFIED_HUB_CONTROL')})
 it('opposite degree threshold independently suppresses hub',()=>{const p=source(1,Array.from({length:50},(_,i)=>record(address(1),address(i+2),i+1)));expect(classify(p,truth).recursiveFrontierAuthority).toBe(false)})
 it('saturated noncase page suppresses low-normalized result',()=>{const p=source(1,[record(address(1),address(2),1)]);p.semantic.stats.rawTransactionRecords=100;expect(classify(p,truth).recursiveFrontierAuthority).toBe(false)})
 it('accepted seed linkage avoids only saturation rule, not degree threshold',()=>{const p=source(1,[record(address(1),address(2),1)]);p.semantic.stats.rawTransactionRecords=100;expect(classify(p,{...truth,seedAddresses:[address(1)]}).recursiveFrontierAuthority).toBe(true);p.admission.normalizedRecords=Array.from({length:100},(_,i)=>record(address(1),address(2),i+1));expect(classify(p,{...truth,seedAddresses:[address(1)]}).recursiveFrontierAuthority).toBe(false)})
 it('hub-only candidates are retained but rejected',()=>{const p=source(1,Array.from({length:100},(_,i)=>record(address(1),address(i+2),i+1))),f=build([p]);expect(f.requests).toHaveLength(0);expect(f.matrix.rows).toHaveLength(100);expect(f.matrix.rows.every(r=>r.rejectionCode==='HUB_ONLY_RECURSIVE_LINEAGE_SUPPRESSED')).toBe(true)})
 it('exact truth linkage is a distinct case basis even from a hub',()=>{const rows=Array.from({length:100},(_,i)=>record(address(1),address(i+2),i+1)),t={...truth,times:{[hash(1)]:'accepted'}},f=build([source(1,rows)],{truth:t});expect(f.requests).toHaveLength(1);expect(f.requests[0].purpose).toBe('TRACE_THREAD_LINK_TEST')})
 it('hub support does not manufacture independent non-hub repetition',()=>{const hub=source(1,Array.from({length:100},(_,i)=>record(address(1),address(i+2),i+1))),non=source(200,[record(address(200),address(2),999)]);expect(build([hub,non]).requests).toHaveLength(0)})
 it('known destination is never an ordinary route',()=>{const s=Object.keys(REGISTRY)[4],f=build([source(1,[record(address(1),s,1),record(address(1),s,2)])]);expect(f.requests[0].purpose).toBe('NEGATIVE_CONTROL');expect(f.requests[0].consumers.some(c=>c.includes('ROUTE'))).toBe(false);expect(f.matrix.ordinaryAdmittedCount).toBe(0)})
 it('at most two named infrastructure controls, not padded',()=>{const rs=Object.keys(REGISTRY).slice(4,7).flatMap((s,i)=>[record(address(1),s,i+1),record(address(1),s,i+100)]),f=build([source(1,rs)]);expect(f.requests).toHaveLength(2);expect(f.matrix.infrastructureControlAdmittedCount).toBe(2)})
 it('hub-only known destination lacks ordinary/control case basis',()=>{const s=Object.keys(REGISTRY)[4],p=source(1,Array.from({length:100},(_,i)=>record(address(1),s,i+1))),f=build([p]);expect(f.requests).toHaveLength(0)})
 it('later exact durable page is evaluated but not live B4 page1',()=>{const f=build([source(1,[record(address(1),address(2),1)],{is_last_page:false})]);expect(f.matrix.rows.find(r=>r.page===2).rejectionCode).toBe('B4_EXACT_PAGE1_ONLY')})
 it('no later page without exact durable non-last evidence',()=>{expect(build([source(1,[record(address(1),address(2),1)],{is_last_page:true})]).matrix.rows.every(r=>r.page===1)).toBe(true)})
 it('equivalent issued requests cannot issue regardless of new purpose',()=>{const p=source(1,[record(address(1),address(2),1),record(address(1),address(2),2)]),issued={...template,body:{...template.body,address:address(2)}};expect(build([p],{issuedRequests:[issued]}).requests).toHaveLength(0)})
 it('zero and token-contract candidates are retained with exact rejection',()=>{const t={...truth,seedAddresses:[address(0),token]},f=build([source(1,[])],{truth:t});expect(new Set(f.matrix.rows.map(r=>r.rejectionCode))).toEqual(new Set(['ZERO_ADDRESS','TOKEN_CONTRACT_EXCLUDED']))})
 it('invalid seeds fail public safety',()=>{const f=build([],{truth:{...truth,seedAddresses:['invalid']}});expect(f.matrix.rows[0].rejectionCode).toBe('INVALID_ADDRESS')})
 it('incidental normalized row cannot supply lineage',()=>{expect(()=>build([source(1,[record(address(3),address(4),1)])])).toThrow('B4_INCIDENTAL_LINEAGE')})
 it('each lineage/TX/transfer ID and metadata set is candidate-specific',()=>{const rs=[record(address(1),address(2),1),record(address(1),address(2),2),record(address(1),address(3),3),record(address(1),address(3),4)],f=build([source(1,rs)]);for(const q of f.requests){expect(new Set(q.lineage).size).toBe(q.lineage.length);expect(q.lineage.filter(l=>l.startsWith('DURABLE_SUBJECT_TRANSFER.'))).toHaveLength(1);expect(logicalRequest(q)).toBe(q.logicalId);expect(q.coverageCells[0]).toBe('CELL.'+identity(q.coverageKey));expect(q.consumers.every(c=>c===q.coverageCells[0]||c.includes(q.body.address))).toBe(true)}expect(new Set(f.requests.map(q=>q.questionId)).size).toBe(2)})
 it('degree is never a utility reward',()=>{const p=source(1,[record(address(1),address(2),1),record(address(1),address(2),2)]),f=build([p]);expect(f.matrix.rows[0].utilityRank.sourceDegreeRisk).toBe(1);expect(f.matrix.rows[0].utilityRank).not.toHaveProperty('rawRowReward')})
 it('gate rejects old packaged64 plan even with canonical ids',()=>{const plan=seal({requests:[],frontierPolicyIdentity:'bad'}),policy=seal({maximumRequests:64});expect(()=>admissionGate(plan,policy)).toThrow('B4_FILTERED_PLAN_SEAL_OR_POLICY')})
 it('valid empty frontier fails four-ordinary threshold without padding',()=>{const policy=seal({maximumRequests:16,maximumPerSource:4,maximumInfrastructureControls:2,old64RequestPlanRejected:true}),plan=seal({requests:[],ordinaryMeaningfulCandidates:0,frontierPolicyIdentity:policy.hash});expect(admissionGate(plan,policy).pass).toBe(false);expect(admissionGate(plan,policy).AUTHORIZED_TO_ISSUE).toBe(false)})
 it('lessons preserve27 plus8 with active B3 state historical',()=>{const l=lessons();expect(l.rows).toHaveLength(35);expect(l.rows.some(r=>r.classification==='CURRENT_OPERATIONAL_STATE')).toBe(false)})
 it('all public lesson prose passes the unchanged absolute-path scanner',()=>{const payload={'EVIDENCE/QUALIFICATION_LESSONS_LEARNED_DELTA.json':Buffer.from(JSON.stringify(lessons(),null,2)+'\n')};const scan=pathScan(payload);expect(scan.status).toBe('PASS');expect(scan.absoluteFilesystemPathFindings).toBe(0)})
 it('public accepted schema rejects planning class leakage',()=>{const s=JSON.parse(fs.readFileSync('schemas/NQ5_PUBLIC_CALL_INDEX_B4_ACCEPTED.schema.json'));expect(s.items.additionalProperties).toBe(false);expect(s.items.properties).not.toHaveProperty('planningOnlyClassification');expect(s.items.properties.lead_acceptance_status.const).toBe('LEAD_ACCEPTED');expect(s.items.required).toContain('lead_acceptance_receipt_sha256')})
 it('audit schema keeps previous schemas unchanged and narrows acceptance branch',()=>{const old=JSON.parse(fs.readFileSync('schemas/NANSEN_API_REQUEST_AUDIT.schema.json')),s=JSON.parse(fs.readFileSync('schemas/NANSEN_API_REQUEST_AUDIT_B4_ACCEPTED.schema.json'));expect(old.$defs).not.toHaveProperty('b3LeadAcceptedAuditRecord');expect(s.$defs.b3LeadAcceptedAuditRecord.properties.signedFlowReview.properties.leadAccepted.const).toBe(true);expect(s.properties.b4FilteredAcceptanceReview.properties.leadAcceptedCount.const).toBe(8)})
 it('driver has no credential/transport runtime surface',()=>{const b=fs.readFileSync('scripts/nq5-b4-filtered/run.mjs','utf8');expect(b).not.toContain('liveTransport');expect(b).not.toContain('NANSEN_API_KEY');expect(b).not.toContain('new Store');expect(b).toContain('derive(root)')})
 it('an invented four-ordinary counter cannot admit an empty plan',()=>{const policy=seal({maximumRequests:16,maximumPerSource:4,maximumInfrastructureControls:2,old64RequestPlanRejected:true}),plan=seal({requests:[],ordinaryMeaningfulCandidates:4,frontierPolicyIdentity:policy.hash});expect(()=>admissionGate(plan,policy)).toThrow('B4_ORDINARY_COUNT_OR_DUPLICATE_DRIFT')})
})
