import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import { beforeAll, afterAll, afterEach, describe, expect, it, vi } from 'vitest'
import { buildFrozenFixture } from '../../src/investigation/fixture'
import { accountReport } from '../fixtures/nq5-offline.mjs'
import { ACTIVE_R3, validateR3Source, R3_SOURCE_MANIFEST_SHA256 } from '../../scripts/nq5-r3/authority.mjs'
import { buildContractAdmission, loadOfficialSnapshot, assertContractAdmission, redistributionDecision, rejectUnsafePublicProjection, FAMILIES } from '../../scripts/nq5-r3/contracts.mjs'
import { createCampaignGenesis, resumeCampaignGenesis, proveCampaignAbsent, assertGenesis, newCampaignId, EMPTY_JOURNAL_SHA256 } from '../../scripts/nq5-r3/genesis.mjs'
import { freezeGenesisBatch, assertFrozenIdentity, serializedSha256, validateOfflineReport, validateFinalPrecall, REQUIRED_GATES } from '../../scripts/nq5-r3/checkpoint.mjs'
import { identity, sha } from '../../scripts/nq5/schema.mjs'
const temporary = [], root = process.cwd(), base = 'public/scenarios/euler-2023-false-exit/'
const fixture = buildFrozenFixture(JSON.parse(fs.readFileSync(base+'scenario.json')),JSON.parse(fs.readFileSync(base+'evidence-graph.json')))
const account = accountReport(630027)
const context = {candidateCommit:'1'.repeat(40),candidateTree:'2'.repeat(40),sourceIdentity:identity(ACTIVE_R3),accountObservationIdentity:'3'.repeat(64),accountReportSha256:serializedSha256(account)}
// Offline immutable R3 captures: fix Date only, never live policy or timers.
beforeAll(()=>{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-09-17T12:00:00Z'))})
afterAll(()=>vi.useRealTimers())
afterEach(()=>{for(const location of temporary.splice(0)) fs.rmSync(location,{recursive:true,force:true})})
function roots() { const location = fs.mkdtempSync(path.join(os.tmpdir(),'trace-r3-synthetic-')); temporary.push(location); return ['primary','mirror'].map(name=>{const file=path.join(location,name);fs.mkdirSync(file,{mode:0o700});return file}) }
const admission = () => buildContractAdmission(loadOfficialSnapshot(root),'PRO')
describe('R3 read-only committed baseline revalidation — synthetic roots only',()=>{
  const committed=()=>{const candidateCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),candidateTree=execFileSync('git',['rev-parse','HEAD^{tree}'],{encoding:'utf8'}).trim();return {...context,candidateCommit,candidateTree}}
  it('reopens the same baseline without changing any private bytes or resetting its creation identity',()=>{
    const configured=roots(),id=newCampaignId(),binding=committed(),first=createCampaignGenesis(configured,id,binding)
    const before=configured.flatMap(location=>['genesis.json','GENESIS_COMMIT.json','qualification.jsonl'].map(name=>fs.readFileSync(path.join(location,id,name))))
    const receipt=resumeCampaignGenesis(configured,id,binding,binding,root,first.primaryGenesisSha256)
    expect(receipt.creationNotRepeated).toBe(true);expect(receipt.privateArtifactsModified).toBe(false);expect(receipt.creationCandidateCommit).toBe(binding.candidateCommit);expect(assertGenesis(receipt,binding).counted).toBe(0)
    const after=configured.flatMap(location=>['genesis.json','GENESIS_COMMIT.json','qualification.jsonl'].map(name=>fs.readFileSync(path.join(location,id,name))))
    expect(after.every((bytes,i)=>bytes.equals(before[i]))).toBe(true);expect(()=>assertGenesis(structuredClone(receipt),binding)).toThrow()
  })
  it.each(['hash','tree','observation','extra-baseline','missing-mirror','changed-journal'])('fails closed for %s without creating or repairing private artifacts',mutation=>{
    const configured=roots(),id=newCampaignId(),binding=committed(),first=createCampaignGenesis(configured,id,binding),current={...binding}
    let hash=first.primaryGenesisSha256
    if(mutation==='hash')hash='0'.repeat(64)
    if(mutation==='tree')current.candidateTree='2'.repeat(40)
    if(mutation==='observation')current.accountObservationIdentity='4'.repeat(64)
    if(mutation==='extra-baseline')fs.mkdirSync(path.join(configured[0],newCampaignId()),{mode:0o700})
    if(mutation==='missing-mirror')fs.renameSync(path.join(configured[1],id),path.join(configured[1],'held-incomplete'))
    if(mutation==='changed-journal')fs.appendFileSync(path.join(configured[0],id,'qualification.jsonl'),'SYNTHETIC_CORRUPTION')
    const before=configured.map(location=>fs.readdirSync(location).sort())
    expect(()=>resumeCampaignGenesis(configured,id,binding,current,root,hash)).toThrow();expect(configured.map(location=>fs.readdirSync(location).sort())).toEqual(before)
  })
  it('accepts an allowed descendant cut, then rejects extra baselines, unrelated changes and original creation-code changes',()=>{
    const location=fs.mkdtempSync(path.join(os.tmpdir(),'trace-r3-lineage-'));temporary.push(location)
    const git=(...args)=>execFileSync('git',args,{cwd:location,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim()
    git('init');fs.mkdirSync(path.join(location,'scripts/nq5-r3'),{recursive:true})
    const original=execFileSync('git',['show','41be40d234c7a7f31d9167294dafa5cf8a3e94a5:scripts/nq5-r3/genesis.mjs'],{cwd:root,encoding:'utf8'})
    fs.writeFileSync(path.join(location,'scripts/nq5-r3/genesis.mjs'),original)
    const commit=()=>{git('add','scripts');git('-c','user.name=Synthetic Review','-c','user.email=synthetic@example.invalid','commit','-m','Synthetic lineage');return {...context,candidateCommit:git('rev-parse','HEAD'),candidateTree:git('rev-parse','HEAD^{tree}')}}
    const creation=commit(),configured=roots(),id=newCampaignId(),first=createCampaignGenesis(configured,id,creation)
    fs.writeFileSync(path.join(location,'scripts/secret-patterns.mjs'),'// Synthetic allowed scanner fix\n');const current=commit()
    const receipt=resumeCampaignGenesis(configured,id,creation,current,location,first.primaryGenesisSha256);expect(assertGenesis(receipt,current).counted).toBe(0);expect(receipt.creationCandidateCommit).not.toBe(receipt.candidateCommit)
    fs.mkdirSync(path.join(configured[0],newCampaignId()),{mode:0o700});expect(()=>assertGenesis(receipt,current)).toThrow()
    fs.writeFileSync(path.join(location,'scripts/protected-change.mjs'),'// Synthetic unrelated change\n');const unrelated=commit();expect(()=>resumeCampaignGenesis(configured,id,creation,unrelated,location,first.primaryGenesisSha256)).toThrow('unrelated')
    fs.unlinkSync(path.join(location,'scripts/protected-change.mjs'));fs.writeFileSync(path.join(location,'scripts/nq5-r3/genesis.mjs'),original.replace('function exclusiveFile(', 'function alteredExclusiveFile('));const changed=commit();expect(()=>resumeCampaignGenesis(configured,id,creation,changed,location,first.primaryGenesisSha256)).toThrow('creation/validation')
  })
})
describe('R3 exact additive authority and public-only official contract admission',()=>{
  it('retains the production 24-hour snapshot freshness rejection',()=>{
    try{
      expect(()=>loadOfficialSnapshot(root)).not.toThrow()
      vi.setSystemTime(new Date('2026-09-17T20:53:25.239Z'))
      expect(()=>loadOfficialSnapshot(root)).toThrow('Invalid documentation provenance or freshness.')
    }finally{vi.setSystemTime(new Date('2026-09-17T12:00:00Z'))}
  })
  it('adds nine exact supplied files/five authorities without replacing43 foundation files',()=>{const source=validateR3Source(root);expect(source.additiveFiles).toBe(9);expect(source.unchangedFoundationFiles).toBe(43);expect(source.replacedFiles).toBe(0);expect(source.precedence[1]).toContain('1.7.2')})
  it('parses all four endpoint schemas including lookup in the shared transactions bytes; excludes both unclarified families',()=>{const value=admission();expect(value.requiredSnapshotComplete).toBe(true);expect(value.records.every(record=>record.endpointSchemaVerified)).toBe(true);expect(value.contracts.map(row=>row.family).sort()).toEqual([FAMILIES.transactions,FAMILIES['historical-balances']].sort());expect(value.records.filter(row=>!row.qualificationCountedEligible).every(row=>!row.publicCallIndexEligible && row.contractHash === null)).toBe(true);expect(value.records.find(row=>row.family===FAMILIES.lookup).sources.endpoint.bodySha256).toBe(value.records[0].sources.endpoint.bodySha256);expect(value.records.find(row=>row.family===FAMILIES.counterparties).credits).toBe(5)})
  it.each(['omitted','singular','ambiguous','unavailable','without-source','contradictory'])('never treats %s clarification as public permission',kind=>{const rules=kind === 'singular' ? [{family:'profiler/address/counterparty',requirement:'Attribution required'}]:[];const answer={httpStatus:200,capturedSourceRule:{family:FAMILIES.counterparties,status:'Allowed'}};if(kind === 'ambiguous') answer.ambiguous=true;if(kind === 'unavailable') answer.httpStatus=503;if(kind === 'without-source') answer.generatedWithoutExactPositiveSource=true;if(kind === 'contradictory') answer.contradictory=true;if(['omitted','singular'].includes(kind)) delete answer.capturedSourceRule;expect(redistributionDecision(FAMILIES.counterparties,rules,answer).disposition).toBe('NOT_PUBLICLY_ADMITTED_FOR_T1');expect(redistributionDecision(FAMILIES.lookup,[],null).disposition).toBe('NOT_PUBLICLY_ADMITTED_FOR_T1')})
  it('rejects forged/serialized snapshot and admission proof',()=>{expect(()=>buildContractAdmission(structuredClone(loadOfficialSnapshot(root)))).toThrow();expect(()=>assertContractAdmission(structuredClone(admission()))).toThrow()})
  it.each(['unknown','label','account','credential','private_header','raw_body'])('rejects extra %s fields from public projection',key=>{const row={token_address:'0x'+'1'.repeat(40),balance:'1.000000000000000001',block_timestamp:'2023-03-13T11:38:11Z'};expect(rejectUnsafePublicProjection(FAMILIES['historical-balances'],row)).toBe(true);expect(()=>rejectUnsafePublicProjection(FAMILIES['historical-balances'],{...row,[key]:'SYNTHETIC_PRIVATE_SENTINEL'})).toThrow()})
  it('rejects credential-like values, nested objects, inexact numbers and invalid addresses',()=>{const row={token_address:'0x'+'1'.repeat(40),balance:'1',block_timestamp:'2023-03-13T11:38:11Z'};for(const mutation of [{balance:1},{balance:{raw:'private'}},{token_address:'Bearer synthetic_fixture_value'},{block_timestamp:'credential=synthetic_fixture_value'}]) expect(()=>rejectUnsafePublicProjection(FAMILIES['historical-balances'],{...row,...mutation})).toThrow()})
})
describe('R3 exclusively created, mirrored, durable campaign genesis — synthetic roots only',()=>{
  it('exclusively creates restrictive zero-byte append-only journals and mirrored committed genesis; reopens and proves separate accounting',()=>{const configured=roots(),id=newCampaignId(),receipt=createCampaignGenesis(configured,id,context),history=assertGenesis(receipt,context);expect(receipt.campaignId).toBe(id);expect(receipt.journalSha256).toBe(sha(Buffer.alloc(0)));expect(receipt.journalSha256).toBe(EMPTY_JOURNAL_SHA256);expect(history.logicalIds).toEqual([]);expect(receipt.t1).toEqual({attempts:0,countedSuccesses:0,actualCreditDelta:0,projectedCredits:0});expect(receipt.priorDiscovery.attempts).toBe(32);expect(receipt.priorDiscovery.credits).toBe(37);expect(receipt.consumedAccount.attempts).toBe(1);expect(receipt.privatePathsIncluded).toBe(false);expect(JSON.stringify(receipt)).not.toContain(configured[0]);expect(fs.statSync(path.join(configured[0],id)).mode&0o777).toBe(0o700);expect(fs.statSync(path.join(configured[0],id,'qualification.jsonl')).mode&0o777).toBe(0o600)})
  it('rejects ID collision in either configured root without changing previous bytes',()=>{for(const which of [0,1]){const configured=roots(),id=newCampaignId();fs.mkdirSync(path.join(configured[which],id),{mode:0o700});fs.writeFileSync(path.join(configured[which],id,'qualification.jsonl'),'prior history',{mode:0o600});expect(()=>createCampaignGenesis(configured,id,context)).toThrow();expect(fs.readFileSync(path.join(configured[which],id,'qualification.jsonl'),'utf8')).toBe('prior history');expect(fs.existsSync(path.join(configured[1-which],id))).toBe(false)}})
  it('does not escape an existing or partial baseline by choosing a different campaign ID',()=>{const configured=roots(),receipt=createCampaignGenesis(configured,newCampaignId(),context);expect(()=>createCampaignGenesis(configured,newCampaignId(),context)).toThrow();expect(assertGenesis(receipt,context).logicalIds).toEqual([])})
  it.each(['missing','symlink','overlap','same','insecure','unexpected-entry','indeterminate-search'])('fails closed for %s configured roots',kind=>{const configured=roots(),id=newCampaignId();if(kind==='missing') configured[1]+='/absent';if(kind==='symlink'){const link=configured[1]+'-link';fs.symlinkSync(configured[1],link);configured[1]=link}if(kind==='same') configured[1]=configured[0];if(kind==='overlap'){configured[1]=path.join(configured[0],'nested');fs.mkdirSync(configured[1],{mode:0o700})}if(kind==='insecure') fs.chmodSync(configured[1],0o755);if(kind==='unexpected-entry') fs.symlinkSync('/unavailable-synthetic-target',path.join(configured[1],'journal'));if(kind==='indeterminate-search') for(let i=0;i<10001;i++)fs.writeFileSync(path.join(configured[1],String(i)),Buffer.alloc(0));expect(()=>proveCampaignAbsent(configured,id)).toThrow();expect(fs.existsSync(path.join(configured[0],id))).toBe(false)})
  it.each(['journal','genesis','commit','permissions','unexpected-journal','context','serialized','prior-relabel'])('rejects %s corruption/mismatch without repairing/resetting',kind=>{const configured=roots(),id=newCampaignId(),receipt=createCampaignGenesis(configured,id,context);let proof=receipt,binding=context;if(kind==='journal')fs.appendFileSync(path.join(configured[0],id,'qualification.jsonl'),'history');if(kind==='genesis')fs.appendFileSync(path.join(configured[1],id,'genesis.json'),'x');if(kind==='commit')fs.appendFileSync(path.join(configured[0],id,'GENESIS_COMMIT.json'),'x');if(kind==='permissions')fs.chmodSync(path.join(configured[1],id,'genesis.json'),0o644);if(kind==='unexpected-journal')fs.writeFileSync(path.join(configured[1],id,'unexpected.jsonl'),'history');if(kind==='context')binding={...context,candidateCommit:'4'.repeat(40)};if(kind==='serialized')proof=structuredClone(receipt);if(kind==='prior-relabel'){const file=path.join(configured[0],id,'genesis.json'),record=JSON.parse(fs.readFileSync(file));record.t1.attempts=32;fs.writeFileSync(file,JSON.stringify(record));}const bytes=fs.readFileSync(path.join(configured[0],id,'qualification.jsonl'));expect(()=>assertGenesis(proof,binding)).toThrow();expect(fs.readFileSync(path.join(configured[0],id,'qualification.jsonl'))).toEqual(bytes)})
})
describe('R3 page1-only next frozen batch and semantically truthful reports',()=>{
  it('freezes fifteen meaningful admitted accepted-seed requests after verified exclusive genesis, with no padding/speculative reserve',()=>{const configured=roots(),receipt=createCampaignGenesis(configured,newCampaignId(),context),value=freezeGenesisBatch(fixture,admission(),account,receipt,context);expect(value.plan.frozen).toBe(true);expect(value.plan.requests).toHaveLength(15);expect(value.plan.requests.every(row=>row.partition.page===1 && row.body.pagination.page===1 && row.frontierProof.kind==='ACCEPTED_SEED' && row.publicProjectionPolicy.unknownPublicFields==='REJECT' && row.consumers.length && row.coverageCells.length && row.lineage.length)).toBe(true);expect(new Set(value.plan.requests.map(row=>row.logicalId)).size).toBe(15);expect(value.plan.expectedCredits).toBe(15);expect(value.plan.worstCaseCredits).toBe(45);expect(value.reserve.requests).toEqual([]);expect(value.report.remainingAfterWorstCaseAndProtectedReserve).toBe(629732);expect(value.report.floorReached).toBe(false);expect(value.plan.qualificationCallsAllowed).toBe(false)})
  it('rejects missing/serialized genesis, unknown initial state, wrong observed account and missing admission',()=>{const configured=roots(),receipt=createCampaignGenesis(configured,newCampaignId(),context),proof=admission();for(const args of [[proof,account,null,context],[proof,account,structuredClone(receipt),context],[structuredClone(proof),account,receipt,context],[proof,accountReport(250),receipt,context]])expect(()=>freezeGenesisBatch(fixture,...args)).toThrow()})
  it('rejects an unfrozen serialized plan mislabeled by frozen_t1_plan_sha256',()=>{const plan={frozen:false,requests:[]},report={t1_plan_sha256:serializedSha256(plan),t1_plan_frozen:false,t1_plan_status:'UNFROZEN_NOT_ISSUABLE'};expect(()=>assertFrozenIdentity(report,plan)).not.toThrow();expect(()=>assertFrozenIdentity({...report,frozen_t1_plan_sha256:serializedSha256(plan)},plan)).toThrow();expect(()=>assertFrozenIdentity({...report,t1_plan_frozen:true},plan)).toThrow();expect(()=>assertFrozenIdentity({...report,t1_plan_status:'FROZEN_NEXT_BATCH'},plan)).toThrow()})
  it('offline PASS never reauthorizes the consumed account attempt and rejects unknown/private report fields',()=>{const report={schema_version:'1.1.0',status:'PASS_OFFLINE_GATES_ONLY',active_gate:'G6P-A2U-R3',generated_at_utc:new Date().toISOString(),candidate_commit:context.candidateCommit,candidate_tree:context.candidateTree,parent_authorization_id:'LEAD-NQ5-UNIFIED-CASEBOARD-UTILITY-001',active_source_identity:context.sourceIdentity,mandatory_offline_gates:Object.fromEntries(REQUIRED_GATES.map(key=>[key,'PASS'])),blockers:[],credential_access:false,provider_calls:0,AUTHORIZED_TO_ISSUE_ACCOUNT_PREFLIGHT:false,account_attempt_consumed:1,additional_account_attempts_authorized:0,scope:'CURRENT_OFFLINE_GATES_ONLY_NO_NEW_ACCOUNT_AUTHORITY'};expect(validateOfflineReport(report)).toBe(true);expect(()=>validateOfflineReport({...report,AUTHORIZED_TO_ISSUE_ACCOUNT_PREFLIGHT:true})).toThrow();expect(()=>validateOfflineReport({...report,private_headers:{}})).toThrow();expect(()=>validateOfflineReport({...report,mandatory_offline_gates:{}})).toThrow()})
  it('authorizes only the verified actual frozen serialization with every current gate, while execution remains held',()=>{
    const reviewed=JSON.parse(fs.readFileSync('tests/fixtures/nq5-r3-reviewed-observation.json')),binding={...context,accountReportSha256:serializedSha256(reviewed.account),accountObservationIdentity:reviewed.reuse.originalTerminalIdentity}
    const configured=roots(),genesis=createCampaignGenesis(configured,newCampaignId(),binding),contracts=admission(),{plan,reserve,policy}=freezeGenesisBatch(fixture,contracts,reviewed.account,genesis,binding)
    const report={schema_version:'1.2.0',status:'DELIVERED_PENDING_LEAD_REVIEW',active_gate:'G6P-A2U-R3',generated_at_utc:new Date().toISOString(),candidate_commit:binding.candidateCommit,candidate_tree:binding.candidateTree,active_source_identity:binding.sourceIdentity,active_source_manifest_sha256:R3_SOURCE_MANIFEST_SHA256,AUTHORIZED_TO_ISSUE:true,AUTHORIZED_TO_ISSUE_ACCOUNT_PREFLIGHT:false,additional_account_attempts:0,historical_account_attempts_consumed:1,qualification_attempts:0,qualification_counted:0,provider_calls_in_r3:0,credential_access_in_r3:false,checkpoint_hold:true,qualification_execution_allowed:false,original_account_report_sha256:binding.accountReportSha256,account_observation_reuse_receipt_sha256:serializedSha256(reviewed.reuse),campaign_genesis_receipt_sha256:serializedSha256(genesis),official_contract_admission_sha256:serializedSha256(contracts),t1_plan_sha256:serializedSha256(plan),t1_plan_frozen:true,t1_plan_status:'FROZEN_NEXT_BATCH',reserve_plan_sha256:serializedSha256(reserve),offline_report_sha256:'c'.repeat(64),available_credits:630027,protected_reserve_credits:250,gates:Object.fromEntries(REQUIRED_GATES.map(key=>[key,'PASS'])),blockers:[],campaign_id:genesis.campaignId,frontier_policy_sha256:serializedSha256(policy),frontier_policy_canonical_identity:policy.hash,frontier_policy_identity_verified:true}
    const offline={schema_version:'1.1.0',status:'PASS_OFFLINE_GATES_ONLY',active_gate:'G6P-A2U-R3',generated_at_utc:report.generated_at_utc,candidate_commit:binding.candidateCommit,candidate_tree:binding.candidateTree,parent_authorization_id:'LEAD-NQ5-UNIFIED-CASEBOARD-UTILITY-001',active_source_identity:binding.sourceIdentity,mandatory_offline_gates:report.gates,blockers:[],credential_access:false,provider_calls:0,AUTHORIZED_TO_ISSUE_ACCOUNT_PREFLIGHT:false,account_attempt_consumed:1,additional_account_attempts_authorized:0,scope:'CURRENT_OFFLINE_GATES_ONLY_NO_NEW_ACCOUNT_AUTHORITY'}
    report.offline_report_sha256=serializedSha256(offline);const evidence={offlineReport:offline,accountReuseReceipt:reviewed.reuse,frontierPolicy:policy,frontierPolicyBytes:Buffer.from(JSON.stringify(policy,null,2)+'\n')}
    expect(validateFinalPrecall(report,plan,reserve,evidence)).toBe(true);expect(()=>validateFinalPrecall(report,plan,reserve)).toThrow()
    for(const mutation of [{gates:{}},{gates:{...report.gates,campaign_genesis:'NOT_VERIFIED'}},{candidate_commit:'4'.repeat(40)},{available_credits:630026},{AUTHORIZED_TO_ISSUE_ACCOUNT_PREFLIGHT:true},{qualification_execution_allowed:true},{qualification_attempts:1},{credential_access_in_r3:true},{provider_calls_in_r3:1},{private_headers:{}},{t1_plan_frozen:false},{t1_plan_status:'UNFROZEN_NOT_ISSUABLE'},{campaign_genesis_receipt_sha256:'d'.repeat(64)},{active_source_manifest_sha256:'0'.repeat(64)},{account_observation_reuse_receipt_sha256:'0'.repeat(64)}])expect(()=>validateFinalPrecall({...report,...mutation},plan,reserve,evidence)).toThrow()
    expect(()=>validateFinalPrecall(report,structuredClone(plan),reserve,evidence)).toThrow();expect(()=>validateFinalPrecall(report,plan,{...reserve,protectedReserveCredits:0},evidence)).toThrow()
    const blockers=[{id:'UNVERIFIED',summary:'Missing verified proof.',evidence_refs:['REPORTS/T1_CAMPAIGN_GENESIS_RECEIPT.json']}],badOffline={...offline,status:'BLOCKED_WITH_EVIDENCE',mandatory_offline_gates:{...offline.mandatory_offline_gates,secret_scans:'FAIL'},blockers}
    expect(validateOfflineReport(badOffline)).toBe(true)
    expect(()=>validateFinalPrecall({...report,offline_report_sha256:serializedSha256(badOffline)},plan,reserve,{...evidence,offlineReport:badOffline})).toThrow()
    const blocked={...report,status:'BLOCKED_WITH_EVIDENCE',AUTHORIZED_TO_ISSUE:false,gates:badOffline.mandatory_offline_gates,blockers,offline_report_sha256:serializedSha256(badOffline)},blockedEvidence={...evidence,offlineReport:badOffline}
    expect(validateFinalPrecall(blocked,plan,reserve,blockedEvidence)).toBe(true);expect(()=>validateFinalPrecall({...blocked,blockers:[{...blockers[0],summary:'Bearer synthetic_fixture_value'}]},plan,reserve,blockedEvidence)).toThrow()
    const alteredReuse={...reviewed.reuse,originalAttemptsConsumed:0};expect(()=>validateFinalPrecall({...report,account_observation_reuse_receipt_sha256:serializedSha256(alteredReuse)},plan,reserve,{...evidence,accountReuseReceipt:alteredReuse})).toThrow()
  })
})
