import fs from 'node:fs'
import { beforeAll, describe, expect, it } from 'vitest'
import { bindAccepted } from '../../scripts/nq5-b1/authority.mjs'
import { identity, sha, validateSchema } from '../../scripts/nq5/schema.mjs'
import { parseExactJson } from '../../scripts/nq5/exact-json.mjs'
import { strictTransfers, amountClass, transferIdentity, assertCampaignRecord, CAMPAIGN } from '../../scripts/nq5-b1-r3-r1/semantics.mjs'
import { retention, accounting } from '../../scripts/nq5-b1-r3-r1/evidence.mjs'
import { frontier } from '../../scripts/nq5-b1-r3-r1/frontier.mjs'
import { acceptedTruth, profile, plans, TEMPORAL, admit } from '../../scripts/nq5-b1-r3/compatibility.mjs'
import { priorEvidence, IDS } from '../../scripts/nq5-b1-r3/authority.mjs'
import { fileURLToPath } from 'node:url'
const root=fileURLToPath(new URL('../..',import.meta.url)),S='0x'+'1'.repeat(40),O='0x'+'2'.repeat(40),T='0x'+'3'.repeat(40),H='0x'+'4'.repeat(64),times=[{classification:TEMPORAL,exactUtcFromAcceptedTruth:null}],q={body:{address:S}}
const transfer=(amount='2',from=S,to=O,token=T)=>({token_amount:amount,from_address:from,to_address:to,token_address:token,chain:'ethereum'})
const exact=(rows)=>({data:[{transaction_hash:H,tokens_sent:rows,tokens_received:[]}]})
const check=rows=>strictTransfers(exact(rows),q,times)
let bound,truth,old,p
beforeAll(()=>{bound=bindAccepted(JSON.parse(fs.readFileSync(new URL('../fixtures/nq5-b1-accepted-public.json',import.meta.url))));truth=acceptedTruth(root);old=JSON.parse(priorEvidence(root).bytes['CONTRACTS/ADDRESS_TRANSACTIONS_NULL_COMPATIBILITY_PROFILE.json']);p=profile(bound,old,truth)},30000)
describe('R3-R1 exact subject/amount/unique-transfer controls, isolated synthetic only',()=>{
 it.each(['from','to','mixedCase','self'])('admits requested-subject participation %s',kind=>{const r=kind==='to'?transfer('2',O,S):kind==='mixedCase'?transfer('2',S.toUpperCase(),O):kind==='self'?transfer('2',S,S):transfer();expect(check([r]).pass).toBe(true);expect(check([r]).stats.uniqueAdmittedRows).toBe(1)})
 it('excludes incidental rows rather than using another transfer in the same transaction',()=>{const r=check([transfer(),transfer('3',O,T)]);expect(r.pass).toBe(true);expect(r.stats).toMatchObject({rawTransferRows:2,subjectInvolvedRows:1,incidentalRows:1,uniqueAdmittedRows:1});expect(r.normalizedRecords).toHaveLength(1)})
 it.each(['allIncidental','tokenContractConfusion','labelConfusion'])('rejects false participation %s',kind=>{const row=transfer('2',O,T,kind==='tokenContractConfusion'?S:T);if(kind==='labelConfusion')row.from_address_label=S;const r=check([row]);expect(r.pass).toBe(false);expect(r.code).toBe('NO_UNIQUE_POSITIVE_SUBJECT_TRANSFER');expect(r.normalizedRecords).toEqual([])})
 it('requires exact from/to, not a substring',()=>{expect(check([transfer('2',O,T)]).stats.subjectInvolvedRows).toBe(0)})
 it('handles multiple transfers deterministically without mutating private input',()=>{const x=exact([transfer(),transfer('3',S,T),transfer('4',O,T)]),before=identity(x),r=strictTransfers(x,q,times);expect(r.normalizedRecords.map(r=>r.amount)).toEqual(['2','3']);expect(identity(x)).toBe(before);expect(identity(strictTransfers(x,q,times))).toBe(identity(r))})
 it.each(['1','1.0','1.000000000000000001','0.000000000000000001','2e3','2E+3','2e-3'])('preserves strictly-positive exact lexeme %s',lexeme=>{const r=check([transfer(lexeme)]);expect(r.pass).toBe(true);expect(r.normalizedRecords[0].amount).toBe(lexeme)})
 it.each(['0','0.0','-0','0e100','-0.000'])('zero never projects %s',lexeme=>{const r=check([transfer(lexeme)]);expect(r.pass).toBe(false);expect(r.stats.zeroRows).toBe(1);expect(r.normalizedRecords).toEqual([])})
 it.each(['-1','-1.0','-0.000000000000000001','-2e-3'])('negative never becomes positive %s',lexeme=>{const r=check([transfer(lexeme)]);expect(r.pass).toBe(false);expect(r.stats.negativeRows).toBe(1);expect(r.normalizedRecords).toEqual([])})
 it.each(['+2','01','NaN','Infinity','','2.','2e','2e1001'])('rejects malformed or unbounded exact decimal %s',lexeme=>expect(()=>amountClass(lexeme)).toThrow())
 it('fails the entire response for nonpositive incidental or subject rows',()=>{for(const r of [transfer('-2'),transfer('0',O,T)]){const a=check([transfer(),r]);expect(a.pass).toBe(false);expect(a.stats.uniqueAdmittedRows).toBe(0)}})
 it('deduplicates canonical tx/from/to/token/exact-amount identity case-insensitively',()=>{const r=check([transfer(),transfer('2',S.toUpperCase(),O.toUpperCase())]);expect(r.pass).toBe(true);expect(r.stats.duplicateRows).toBe(1);expect(r.stats.uniqueAdmittedRows).toBe(1)})
 it('never merges a distinct transaction, token, side or exact amount',()=>{const a=check([transfer(),transfer('2.0'),transfer('3'),transfer('2',S,T),transfer('2',S,O,O)]);expect(a.normalizedRecords).toHaveLength(5);const b=structuredClone(a.normalizedRecords[0]);b.transaction_hash='0x'+'5'.repeat(64);expect(transferIdentity(b)).not.toBe(transferIdentity(a.normalizedRecords[0]))})
 it('raw JSON numeric precision and signed lexemes are retained before semantic checks',()=>{const x=parseExactJson(Buffer.from('{"data":[{"transaction_hash":"'+H+'","tokens_sent":[{"token_amount":1.000000000000000001,"from_address":"'+S+'","to_address":"'+O+'","token_address":"'+T+'","chain":"ethereum"}],"tokens_received":[]}]}'));expect(strictTransfers(x,q,times).normalizedRecords[0].amount).toBe('1.000000000000000001')})
 it('future actual admission rejects unrelated rows and preserves exponent/trailing-zero lexemes',()=>{const request=bound.plan.requests.find(r=>r.logicalId===IDS[0]);for(const amount of ['2.0','2e3','-2','0']){const tx={transaction_hash:H,chain:'ethereum',source_type:'SYNTHETIC',method:'transfer',block_timestamp:request.body.date.from.slice(0,-1),tokens_sent:[{...transfer(amount,request.body.address),token_symbol:'SYNTHETIC',price_usd:null,value_usd:null}],tokens_received:[]},raw=Buffer.from(JSON.stringify({pagination:{page:1,per_page:100,is_last_page:true},data:[tx]}).replace('"token_amount":"'+amount+'"','"token_amount":'+amount)),a=admit(bound,request,raw,{rawSha256:sha(raw),rawBytes:raw.length},1,p,old,truth);expect(a.safelyAdmissible).toBe(!amount.startsWith('-')&&amount!=='0');if(a.safelyAdmissible){expect(a.normalizedRecords[0].amount).toBe(amount);expect(a.publicRecord.campaign_id).toBe(CAMPAIGN);expect(JSON.stringify(a)).not.toMatch(/price_usd|value_usd/)}}})
})
describe('count retention/campaign and complete accounting',()=>{
 const base=()=>({semanticPass:true,stats:{uniqueAdmittedRows:1,incidentalRows:0,duplicateRows:0,zeroRows:0,negativeRows:0},oldIdentity:'same',newIdentity:'same',oldCount:1,newCount:1,bindingsPass:true})
 it('retains support only with unchanged exact identity and count',()=>expect(retention(base())).toBe(true))
 it.each(['subject','incidental','duplicate','zero','negative','identity','count','binding'])('rejects retention failure %s',kind=>{const x=base();if(kind==='subject')x.stats.uniqueAdmittedRows=0;if(kind==='incidental')x.stats.incidentalRows=1;if(kind==='duplicate')x.stats.duplicateRows=1;if(kind==='zero')x.stats.zeroRows=1;if(kind==='negative')x.stats.negativeRows=1;if(kind==='identity')x.newIdentity='different';if(kind==='count')x.newCount=2;if(kind==='binding')x.bindingsPass=false;expect(retention(x)).toBe(false)})
 it('a generic or other campaign cannot pass the campaign semantic validator',()=>{expect(()=>assertCampaignRecord({campaign_id:'NQ5'})).toThrow();expect(()=>assertCampaignRecord({campaign_id:'another'})).toThrow();expect(assertCampaignRecord({campaign_id:CAMPAIGN})).toBe(true)})
 it('the public-index schema rejects the generic alias even though historical foundation allowed it',()=>{const schema=JSON.parse(fs.readFileSync(new URL('../../schemas/NQ5_PUBLIC_CALL_INDEX.schema.json',import.meta.url)));expect(schema.items.properties.campaign_id.const).toBe(CAMPAIGN);expect(validateSchema('provider',[],schema)).toBe(true);expect(()=>validateSchema('provider',[{campaign_id:'NQ5'}],schema)).toThrow()})
 it('reconciles total3395 and interval846 without attributing3389 or842',()=>{const rows=Array.from({length:6},(_,i)=>({sequence:i<2?i+3:i+7,actualCredits:1,remainingCredits:i===5?626632:627478})),a=accounting(rows);expect(a.totalAccountWideDecrease).toBe(3395);expect(a.cumulativeKnownCampaignCredits).toBe(6);expect(a.totalUnattributedAccountWideChange).toEqual({value:3389,classification:'UNATTRIBUTED_ACCOUNT_WIDE_CHANGE'});expect(a.r3IntervalAccountWideDecrease).toBe(846);expect(a.r3KnownCampaignCredits).toBe(4);expect(a.additionalUnattributedR3IntervalChange.value).toBe(842);expect(a.causeAssigned).toBe(false)})
 it('fails changed/missing balance or credits instead of refreshing an account',()=>{expect(()=>accounting([{sequence:7,actualCredits:1,remainingCredits:626631}])).toThrow();expect(()=>accounting([{sequence:7,actualCredits:1,remainingCredits:null}])).toThrow()})
})
function frontierFixture(allPass=true,last=true){const requests=IDS.map(id=>bound.plan.requests.find(q=>q.logicalId===id)),c={bound,truth,plans:plans(bound,p),profile:p},state={starts:new Map([...requests,bound.plan.requests.find(q=>q.logicalId==='0adc6faa92c8411b7ee6834c8c71734de4999f9c5a9443b522f5ca435808dd35')].map(q=>[q.logicalId,{logicalId:q.logicalId}]))},result={allPass,acceptance:{allFourRetentionPass:allPass},privateProjections:requests.map(q=>({logicalId:q.logicalId,request:q,semantic:strictTransfers(exact([transfer('2',q.body.address,O)]),q,times),admission:{safelyAdmissible:true},pagination:{is_last_page:last}}))};return{a:{context:c,archiveSha256:'a'.repeat(64)},state,result}}
describe('complete seed/counterparty/hash/repeat/pagination frontier, never issue',()=>{
 it('evaluates all7 seeds including Main Trigger; smallest meaningful plan has one row',()=>{const x=frontierFixture(),f=frontier(x.a,x.state,x.result);expect(f.matrix.allAcceptedSeedAddressesEvaluated).toBe(7);expect(f.matrix.mainTriggerEvaluated).toBe(true);expect(f.plan.requests).toHaveLength(1);expect(f.plan.requests[0].body.address).toBe('0xb2698c2d99ad2c302a95a8db26b08d17a77cedd4');expect(f.plan.AUTHORIZED_TO_ISSUE).toBe(false);expect(f.policy.maximumRequests).toBe(64);expect(f.reserve.balanceAnchor).toBe(626632)})
 it('semantic failure still enumerates candidates/Main Trigger but creates no plan/reserve/policy',()=>{const x=frontierFixture(false),f=frontier(x.a,x.state,x.result);expect(f.plan).toBeNull();expect(f.reserve).toBeNull();expect(f.policy).toBeNull();expect(f.report.mainTriggerDisposition.rejectionCode).toBe('SEMANTIC_ALL_FOUR_RETENTION_GATE_FAILED');expect(f.report.routeExhaustionClaimed).toBe(false)})
 it('rejects DAI and already-issued equivalents explicitly',()=>{const x=frontierFixture(),f=frontier(x.a,x.state,x.result);expect(f.matrix.rows.find(r=>r.subjectAddress==='0x6b175474e89094c44da98b954eedeac495271d0f').rejectionCode).toBe('TOKEN_CONTRACT_EXCLUDED');expect(f.matrix.rows.find(r=>r.subjectAddress===x.result.privateProjections[0].request.body.address).rejectionCode).toBe('ALREADY_ISSUED_EQUIVALENT_CANONICAL_REQUEST')})
 it('merges repeated counterparties without utility inflation and records independent repeat source',()=>{const x=frontierFixture(),f=frontier(x.a,x.state,x.result),r=f.matrix.rows.find(r=>r.subjectAddress===O);expect(r.sourceKinds).toContain('INDEPENDENTLY_REPEATED_ACROSS_SUBJECT_RESPONSES');expect(r.supportingLogicalIds).toHaveLength(4);expect(f.matrix.rows.filter(r=>r.subjectAddress===O)).toHaveLength(1)})
 it('includes only exact non-last pagination and no invented later page',()=>{const x=frontierFixture(true,false),f=frontier(x.a,x.state,x.result);expect(f.matrix.rows.filter(r=>r.page===2)).toHaveLength(4);expect(f.matrix.rows.some(r=>r.page>2)).toBe(false);expect(f.policy.noFixedPageCeiling).toBe(true);const y=frontierFixture();expect(frontier(y.a,y.state,y.result).matrix.rows.some(r=>r.page===2)).toBe(false)})
 it('rejects zero, token and nonpositive-only counterparties; no incidental derivation',()=>{const x=frontierFixture();x.result.privateProjections[0].semantic=strictTransfers(exact([transfer('2',x.result.privateProjections[0].request.body.address,'0x'+'0'.repeat(40)),transfer('-2',x.result.privateProjections[0].request.body.address,'0x'+'9'.repeat(40)),transfer('2',T,'0x'+'8'.repeat(40))]),x.result.privateProjections[0].request,times);const f=frontier(x.a,x.state,x.result);expect(f.matrix.rows.find(r=>r.subjectAddress==='0x'+'0'.repeat(40)).rejectionCode).toBe('ZERO_ADDRESS');expect(f.matrix.rows.find(r=>r.subjectAddress==='0x'+'9'.repeat(40)).rejectionCode).toBe('NONPOSITIVE_ONLY_UNSUPPORTED_LINEAGE');expect(f.matrix.rows.some(r=>r.subjectAddress==='0x'+'8'.repeat(40))).toBe(false)})
 it('complete matrix and freeze are deterministic and do not alter input',()=>{const x=frontierFixture(),before=identity(x.result.privateProjections);expect(identity(frontier(x.a,x.state,x.result))).toBe(identity(frontier(x.a,x.state,x.result)));expect(identity(x.result.privateProjections)).toBe(before)})
})
