import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {describe,it,expect,vi} from 'vitest'
vi.setConfig({testTimeout:120000})
import {identity,sha,freeze as deepFreeze} from '../../scripts/nq5/schema.mjs'
import {captured} from '../../scripts/nq5-p2/docs.mjs'
import {contracts,TGM,DAI,normalize,validateRequest} from '../../scripts/nq5-p2/admission.mjs'
import {freeze,enumerate,validatePlan,SUBJECTS,canonical} from '../../scripts/nq5-p2/planner.mjs'
import {preparedPlans} from '../../scripts/nq5-p2/prepared.mjs'
import {PHASES,abstraction} from '../../scripts/nq5-p2/corpus.mjs'
import {consume} from '../../scripts/nq5-p2/consumers.mjs'
import {createSyntheticExecutor,resolveCredential,Store,Executor,validateCanary,claimStart} from '../../scripts/nq5-p2/executor.mjs'
import {requestAudit} from '../../scripts/nq5-p2/audit.mjs'
import {safeEvidenceName,readEvidence} from '../../scripts/nq5-p2/evidence-files.mjs'
import {sanitizedLogBytes,admitSuiteLogs,assertAdmittedSuiteLogs} from '../../scripts/nq5-p2/logs.mjs'
import {pinnedPost} from '../../scripts/nq5-p2/post.mjs'
import {unknownAudit} from '../../scripts/nq5-p2/blocked.mjs'
import {utility,transferIdentityCounts} from '../../scripts/nq5-p2/reconciliation.mjs'
import {keccak,poolAddress,TOKENS,INFRASTRUCTURE} from '../../scripts/nq5-p2/infrastructure.mjs'
import {reconcileAcceptanceRows} from '../../scripts/nq5-p2/acceptance.mjs'
import {acceptanceRows} from '../../scripts/nq5-p2/authority.mjs'
const root=new URL('../..',import.meta.url).pathname,old=JSON.parse(fs.readFileSync(new URL('../../docs/official/p1/INDEX.json',import.meta.url))),A=contracts(captured(root),{objects:{'OFFICIAL_DOCS/INDEX.json':old}}),raw=x=>Buffer.from(JSON.stringify(x)),clone=x=>structuredClone(x),hash=i=>'0x'+String(i).padStart(64,'0'),addr=i=>'0x'+String(i).padStart(40,'0'),response=data=>({data,pagination:{page:1,per_page:100,is_last_page:true}})
function context(){const prior={objects:{'EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':{records:[]},'PLANS/T1_P1_MULTI_FAMILY_PILOT_PLAN.json':{requests:[]},'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':[]}},c={admission:A,prior,receipt:{hash:'a'.repeat(64),campaignId:'SYNTHETIC_P2_NO_PRIVATE_ROOTS'},index:[],truth:{},sources:[1,2].map(i=>({logicalId:'SYNTHETIC_ACCEPTED_SOURCE_'+i,request:{family:TGM,body:{filters:{from_address:SUBJECTS.FIRST}}},normalized:{rows:[1,2,3,4].map(j=>({transaction_hash:hash(i*10+j),from_address:SUBJECTS.FIRST,to_address:addr(j),token_address:DAI,amount:'1'}))},tokenContracts:[DAI]})),source:{},state:{rows:Array.from({length:69},()=>({kind:'SYNTHETIC_HISTORICAL'}))}};c.corpus=abstraction(A,c.receipt,'b'.repeat(64),{signedProfileIdentity:'c'.repeat(64),observedProfile:{compatibilitySchemaIdentity:'d'.repeat(64),hash:'e'.repeat(64)}});c.plans=deepFreeze(clone(preparedPlans(root).plans));return c}
function data(q){const from=q.body.filters?.from_address??addr(8),to=q.body.filters?.to_address??addr(9);return response([{block_timestamp:q.body.date.from,transaction_hash:hash(99),from_address:from,to_address:to,transfer_amount:1,from_address_label:'PRIVATE_SYNTHETIC_LABEL',to_address_label:'PRIVATE_SYNTHETIC_LABEL',transfer_value_usd:1,transaction_type:'PRIVATE_SYNTHETIC_TEXT'}])}
function pipeline(modify=r=>r){const c=context(),rows=[...c.state.rows],bodies=new Map(),state=()=>{const starts=new Map(),responses=new Map(),terminals=new Map();for(const r of rows.slice(69))(r.kind==='START'?starts:r.kind==='RESPONSE'?responses:terminals).set(r.kind==='TERMINAL'?r.logicalId:r.logicalId+'.'+r.attempt,r);return {rows,starts,responses,terminals}},store={syntheticOnly:true,context:c,append(x){const r={...x,hash:identity(x)};rows.push(r);return r},persist(id,attempt,b){const rawName=id+'.'+attempt+'.bin';bodies.set(rawName,Buffer.from(b));return {rawName,rawBytes:b.length,rawSha256:sha(b)}},raw:r=>bodies.get(r.rawName),current:state};let calls=0;const transport=async q=>{const call=++calls;if(!c.plans.plan.canaryLogicalIds.includes(q.logicalId))validateCanary(c,state(),r=>store.raw(r));await Promise.resolve();return modify({status:200,bytes:raw(data(q)),headers:{'x-request-id':'SYNTHETIC-P2-'+call,'x-nansen-credits-used':'1','x-nansen-credits-cost':'1','x-nansen-credits-remaining':'625000'}},q,call)},executor=createSyntheticExecutor({context:c,store,transport,rate:{acquire:async stopped=>!stopped(),headers:()=>{}},sleep:async()=>{},random:()=>0});return {c,store,state,executor}}
describe('P2 immutable user-approved correction with metadata parity',()=>{
 it('captures admitted suite bytes and rejects mutation before publication',()=>{const b=Buffer.from('SYNTHETIC PASS\n'),v={suites:[{name:'SYNTHETIC',sha256:sha(b)}]},logs=admitSuiteLogs(v,()=>b);expect(assertAdmittedSuiteLogs(v,logs,()=>b)).toBe(true);expect(()=>admitSuiteLogs(v,()=>Buffer.from('CHANGED'))).toThrow();expect(()=>assertAdmittedSuiteLogs(v,logs,()=>Buffer.from('CHANGED'))).toThrow();b[0]=0;expect(logs.SYNTHETIC[0]).not.toBe(0)})
 it('accepts only the actual frozen plan request and captured exact wire bytes',()=>{const c=context(),q=c.plans.plan.requests[0],p=pinnedPost(q,c.plans.plan.requests);expect(p.path).toBe(q.path);expect(sha(p.bodyBytes)).toBe(q.wireBodySha256);expect(()=>pinnedPost(clone(q),c.plans.plan.requests)).toThrow();let reads=0;const proxy=new Proxy(q,{get(target,k){reads++;return k==='path'?'/api/v1/account':target[k]}});expect(()=>pinnedPost(proxy,c.plans.plan.requests)).toThrow();expect(reads).toBe(0);expect(()=>q.body.chain='base').toThrow()})
 it('regenerates historical audit from trusted source rather than mutable cached metadata',()=>{const c=context();c.prior.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'].p1Records=[{normalizedSha256:'TRUSTED_SYNTHETIC_SOURCE'}];c.prior.bytes={'SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json':Buffer.from(JSON.stringify({type:'object',required:['records'],properties:{records:{type:'array'},p1Records:{type:'array'}}}))};const untrusted={p1Records:[{normalizedSha256:'TAMPERED_CACHE'}],AUTHORIZED_TO_ISSUE:true},a=unknownAudit(c);expect(a.p1Records[0].normalizedSha256).toBe('TRUSTED_SYNTHETIC_SOURCE');expect(a.p2Records.every(r=>r.resultCount===null&&!r.runtimeEvidenceProven)).toBe(true);expect(a).not.toHaveProperty('AUTHORIZED_TO_ISSUE');expect(untrusted.AUTHORIZED_TO_ISSUE).toBe(true);const code=fs.readFileSync(new URL('../../scripts/nq5-p2/blocked.mjs',import.meta.url),'utf8');expect(code).not.toContain('ENTRY_NAMES');expect(code).not.toContain('readFileSync')})
 it('rejects protected/cache traversal names before any file read',()=>{for(const n of ['../sources/secret.txt','PUBLIC/../../sources/secret.txt','/tmp/secret.txt','PUBLIC/file/secret.txt','ART_PRODUCTION/file.txt','.cursor/file.txt','..'])expect(safeEvidenceName(n)).toBe(false);expect(safeEvidenceName('ENTRY_NAMES.json')).toBe(true);expect(safeEvidenceName('PUBLIC/NQ5_PUBLIC_CALL_INDEX.json')).toBe(true)})
 it('rejects cache symlink/hardlink files in an isolated public fixture',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'p2-public-cache-fixture-'));try{fs.writeFileSync(path.join(d,'SAFE.json'),'{}');expect(readEvidence(d,'SAFE.json').toString()).toBe('{}');fs.symlinkSync(path.join(d,'SAFE.json'),path.join(d,'LINK.json'));expect(()=>readEvidence(d,'LINK.json')).toThrow();fs.linkSync(path.join(d,'SAFE.json'),path.join(d,'HARD.json'));expect(()=>readEvidence(d,'HARD.json')).toThrow();expect(()=>readEvidence(d,'../SAFE.json')).toThrow('P2_EVIDENCE_MEMBER_SCOPE')}finally{fs.rmSync(d,{recursive:true,force:true})}})
 it('exports exactly sanitized log bytes with matching hashes, not the wrapper object',()=>{const r=sanitizedLogBytes('Synthetic suite passed at /tmp/synthetic-fixture and /home/synthetic-fixture\n','SYNTHETIC_WORKSPACE');expect(Buffer.isBuffer(r.bytes)).toBe(true);expect(sha(r.bytes)).toBe(r.sanitizedSha256);expect(r.bytes.toString()).not.toContain('/tmp/');expect(r.bytes.toString()).not.toContain('/home/');expect(r.otherPathRedactions).toBe(2)})
 const note=JSON.parse(fs.readFileSync(new URL('../../docs/source/execution-p2/53_USER_APPROVED_P1_IDENTITY_CROSSWALK_CORRECTION.json',import.meta.url))),rows=acceptanceRows(root),order=[...note.crosswalk].sort((a,b)=>a.preservedSupplierSequence-b.preservedSupplierSequence).map(x=>x.logicalId),plan={executionOrder:order};
 it('corrects exactly eight identity pairs and preserves ten Lead orders and original requests',()=>{const x=reconcileAcceptanceRows(rows,plan,note);expect(x.filter(r=>r.identityCorrected)).toHaveLength(8);expect(x.map(r=>r.leadAcceptanceOrder)).toEqual([9,10,11,12,13,14,15,16,17,18]);expect(x.every(r=>r.immutableTerminalIdentity&&r.originalRequestedPublicCallId)).toBe(true)})
 for(const field of ['providerRequestId','rawSha256','normalizedSha256','resultCount','role','lens','purpose','leadAcceptanceOrder'])it('rejects unauthorized '+field+' changes',()=>{const x=clone(note);x.crosswalk[0][field]='DAMAGED';expect(()=>reconcileAcceptanceRows(rows,plan,x)).toThrow()})
 it('rejects missing, duplicate, ledger-mutation and bypass approval',()=>{for(const change of [x=>x.crosswalk.pop(),x=>x.crosswalk[1]=x.crosswalk[0],x=>x.scope.modifyPrivateLedgerOrHistoricalTerminals=true,x=>x.scope.bypassAnyP2PreliveGate=true]){const x=clone(note);change(x);expect(()=>reconcileAcceptanceRows(rows,plan,x)).toThrow()}})
})
describe('P2 historical-only transport fixtures, consumer boundaries and public deployment suppression',()=>{
 it('rejects current live admission of preserved45 historical fixtures with Counterparties held',()=>{const c=context();expect(()=>validatePlan(c)).toThrow('P2_45_PLAN_REJECTED_RETIRED_NO_LIVE_AUTHORITY');expect(freeze(c).liveReady).toBe(false);expect(enumerate(c).requests).toHaveLength(0);expect(c.plans.plan.requests).toHaveLength(45);expect(c.plans.plan.expectedCredits).toBe(45);expect(c.plans.plan.worstCaseCredits).toBe(135);expect(c.plans.plan.canaryLogicalIds).toHaveLength(8);expect(c.plans.plan.AUTHORIZED_TO_ISSUE).toBe(false);expect(A.counter.status).toMatch(/^COUNTERPARTIES_HELD/)})
 it('preserves36 historical phase directions,3 baseline controls and6 candidates without current admission',()=>{const c=context(),qs=c.plans.plan.requests;expect(qs.filter(q=>q.kind==='ACCEPTED_SUBJECT_PHASE')).toHaveLength(36);expect(qs.filter(q=>q.kind==='HAYSTACK_BASELINE')).toHaveLength(3);expect(qs.filter(q=>q.kind==='CONTEXTUAL_CANDIDATE')).toHaveLength(6);expect(new Set(qs.map(canonical)).size).toBe(45)})
 it('binds canonical Keccak vectors and known Uniswap pool CREATE2 equality',()=>{expect(keccak(Buffer.alloc(0))).toBe('c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470');expect(keccak(Buffer.from('abc'))).toBe('4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45');expect(poolAddress(DAI,'0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',500)).toBe('0x6c6bc977e13df9b0de53b251522280bb72383700');expect(TOKENS['0x028171bca77440897b824ca71d1c56cac55b68a3']).toBeTruthy();expect(INFRASTRUCTURE['0x27182842e098f60e3d576794a5bffb0777e025d3']).toBeTruthy()})
 it('executes six named pure consumers with no label/raw bulk or gameplay acceptance',()=>{const c=context(),q=c.plans.plan.requests[0],n=normalize(q,raw(data(q)),A,{}),p=consume(c,q,n,{providerRequestId:'SYNTHETIC',rawSha256:'a'.repeat(64),actualCredits:1});expect(p.consumerRecords).toHaveLength(6);expect(p.foregroundGameplayIntegration).toBe(false);expect(JSON.stringify(p)).not.toContain('PRIVATE_SYNTHETIC_LABEL')})
 it('publishes only aggregate metadata for baseline including raw-schema zero controls',()=>{const c=context(),q=c.plans.plan.requests.find(q=>q.kind==='HAYSTACK_BASELINE'),x=data(q);x.data[0].transfer_amount=0;const n=normalize(q,raw(x),A,{});expect(n.rows).toEqual([]);expect(n.aggregate.query_match_count).toBe(1);expect(n.aggregateOnly).toBe(true);expect(n.recursiveFrontierAuthority).toBe(false);expect(JSON.stringify(n)).not.toContain(hash(99))})
 it('does not relax ordinary zero/negative/exponent/null/string amount gates',()=>{const q=context().plans.plan.requests[0];for(const v of ['0','-1','1e2','null','"1"']){const b=raw(data(q)).toString().replace('"transfer_amount":1','"transfer_amount":'+v);expect(()=>normalize(q,Buffer.from(b),A,{})).toThrow()}})
 it('rejects unbounded empty/nonlast, mismatched direction, timestamp and page2',()=>{const q=context().plans.plan.requests[0];for(const modify of [x=>{x.data=[];x.pagination.is_last_page=false},x=>x.data[0].from_address=addr(7),x=>x.data[0].block_timestamp='2023-03-13T12:16:00Z',x=>x.pagination.page=2]){const x=data(q);modify(x);expect(()=>normalize(q,raw(x),A,{})).toThrow()}})
 it('requires all three story phases and both directions in the exact eight canary',()=>{const c=context(),qs=c.plans.plan.requests.filter(q=>c.plans.plan.canaryLogicalIds.includes(q.logicalId));expect(new Set(qs.map(q=>q.phaseId)).size).toBeGreaterThanOrEqual(3);expect(qs.some(q=>q.direction==='IN')).toBe(true);expect(qs.some(q=>q.direction==='OUT')).toBe(true);expect(qs.some(q=>q.kind==='CONTEXTUAL_CANDIDATE')).toBe(true)})
 it('cannot resolve credentials, write private locks or inject production adapters before all gates',()=>{expect(()=>resolveCredential({})).toThrow('P2_CREDENTIAL_GATE_REQUIRED');expect(()=>new Store({},{})).toThrow('P2_PRIVATE_WRITE_GATE_REQUIRED');expect(()=>new Executor({context:{},store:{},transport:()=>{}})).toThrow();expect(()=>createSyntheticExecutor({context:{roots:[]},store:{syntheticOnly:true}})).toThrow()})
 it('rejects held/new families, page2, label filters and changed consumers',()=>{const c=context(),q=c.plans.plan.requests[0];for(const modify of [q=>q.family='profiler/address/transactions',q=>q.body.pagination.page=2,q=>q.body.filters={label:'PRIVATE'},q=>q.consumers=[]]){const x=clone(q);modify(x);expect(()=>{validateRequest(x,A);consume(c,x,normalize(x,raw(data(x)),A,{}),{providerRequestId:'SYNTHETIC',rawSha256:'a'.repeat(64)})}).toThrow()}})
})
describe('P2 synthetic exact eight canary and frozen remainder',()=>{
 it('retains durable START-only attempts as nullable evidence, not unissued or zero results',()=>{const c=context(),[q,q2,q3]=c.plans.plan.requests,start=q=>({logicalId:q.logicalId,attempt:1,hash:'a'.repeat(64),issuedAtUtc:'2026-09-17T12:00:00Z',requestBodySha256:identity(q.body),requestWireBodySha256:q.wireBodySha256,reservedCredits:q.expectedCredits}),s=start(q),s2=start(q2),state={starts:new Map([[q.logicalId+'.1',s],[q2.logicalId+'.1',s2]]),responses:new Map(),terminals:new Map([[q2.logicalId,{logicalId:q2.logicalId,disposition:'TERMINAL_FAILURE',hash:'b'.repeat(64)}]])},a=requestAudit(c,state,()=>{throw new Error('NO_RAW_EXPECTED')});expect(a.p2Records.flatMap(r=>r.attempts)).toHaveLength(2);expect(a.p2Records[0]).toMatchObject({disposition:'STARTED_UNRESOLVED',resultCount:null,localSupportCandidate:false});expect(a.p2Records[1]).toMatchObject({disposition:'TERMINAL_FAILURE',resultCount:null,localSupportCandidate:false});expect(a.p2Records[2]).toMatchObject({disposition:'NOT_ISSUED',resultCount:null,attempts:[]});expect(a.p2Records[0].attempts[0]).toMatchObject({durableStartIdentity:s.hash,durableIssueIntent:true,responseObserved:false,providerReceiptStatus:'UNPROVEN_WITHOUT_DURABLE_RESPONSE',httpStatus:null,providerRequestId:null,actualCredits:null,quotedCredits:null,remainingCredits:null,rawSha256:null,rawBytes:null,safeHeaders:{}});c.oldTransferIdentities=[];const u=utility(c,{projections:[],audit:a,report:{newDistinctRequests:2,authenticatedCampaignProviderRequestsByFamily:{[TGM]:2,'profiler/address/counterparties':0}}});expect(u.phases.find(p=>p.phaseId===q.phaseId).issued).toBe(2);s.requestWireBodySha256='0'.repeat(64);expect(()=>requestAudit(c,state,()=>{})).toThrow('P2_AUDIT_DURABLE_START_BINDING')})
 it('rejects response-only audit evidence without a bound durable START',()=>{const c=context(),q=c.plans.plan.requests[0];expect(()=>requestAudit(c,{starts:new Map(),responses:new Map([[q.logicalId+'.1',{logicalId:q.logicalId,attempt:1}]]),terminals:new Map()},()=>{})).toThrow('P2_AUDIT_RESPONSE_WITHOUT_START')})
 it('distinguishes within-batch distinct tuples from novel global identities',()=>{const c=context(),q=c.plans.plan.requests[0],n=normalize(q,raw(data(q)),A,{}),fresh=transferIdentityCounts([],n.rows),repeat=transferIdentityCounts(n.rows.map(r=>identity([r.transaction_hash,r.from_address,r.to_address,r.token_address,r.amount])),n.rows);expect(fresh.newBatchDistinctTransferIdentityCount).toBe(1);expect(fresh.newGlobalDistinctTransferIdentityCount).toBe(1);expect(repeat.newBatchDistinctTransferIdentityCount).toBe(1);expect(repeat.newGlobalDistinctTransferIdentityCount).toBe(0);expect(repeat.allGlobalDistinctTransferIdentityCount).toBe(1)})
 it('leaves unknown-runtime family gains null rather than a measured zero',()=>{const c=context();c.oldTransferIdentities=[];const u=utility(c,{projections:[],audit:{p2Records:[]},report:{runtimeEvidenceProven:false,newDistinctRequests:null,authenticatedCampaignProviderRequestsByFamily:{[TGM]:null,'profiler/address/counterparties':null}}});expect(u.families.every(f=>f.issued===null&&f.locallySupported===null&&f.meaningfulConsumerGains===null)).toBe(true);expect(u.phases.every(p=>p.issued===null&&p.locallySupported===null)).toBe(true)})
 it('durably supports45 historical transport fixtures with no new formal acceptance, remainder ceiling16',async()=>{const p=pipeline(),r=await p.executor.run();expect(r.stopReason).toBe(null);expect(r.newAttempts).toBe(45);expect(r.newActualCredits).toBe(45);expect(r.newLocalSupportCandidates).toBe(45);expect(r.maximumInFlight).toBeLessThanOrEqual(16);expect(r.canaryRequests).toBe(8);expect([...p.state().terminals.values()].every(t=>t.publicRecord.lead_acceptance_status==='PENDING_LEAD_REVIEW')).toBe(true);expect(requestAudit(p.c,p.state(),r=>p.store.raw(r)).p2BreadthReview.leadAcceptedCount).toBe(18)})
 it('stops new issue on first schema breaker while draining independent canary successes',async()=>{const p=pipeline((r,q,i)=>i===1?{...r,bytes:raw({data:[],pagination:{page:2,per_page:100,is_last_page:true}})}:r),r=await p.executor.run();expect(r.stopReason).toMatch(/BREAKER/);expect(r.newAttempts).toBe(8);expect(r.newLocalSupportCandidates).toBe(7);expect(p.state().terminals.size).toBe(8)})
 it('holds unknown credits rather than claiming zero and never starts remainder',async()=>{const p=pipeline((r,q,i)=>i===1?{...r,headers:Object.fromEntries(Object.entries(r.headers).filter(([k])=>k!=='x-nansen-credits-used'))}:r),r=await p.executor.run();expect(r.newAttempts).toBe(8);expect(r.newActualCredits).toBe(7);expect(r.unresolvedReservedCredits).toBe(1);expect(r.stopReason).toMatch(/CREDIT/)})
 for(const status of [302,401,403,400])it('does not follow or retry status'+status,async()=>{const p=pipeline(r=>({...r,status})),r=await p.executor.run();expect(r.newAttempts).toBe(8);expect(r.newLocalSupportCandidates).toBe(0)})
 it('retries429 once only under same logical/body identity and exact credit controls',async()=>{const seen=new Set(),p=pipeline((r,q)=>{if(seen.has(q.logicalId))return r;seen.add(q.logicalId);return {...r,status:429,headers:{...r.headers,'x-nansen-credits-used':'0','retry-after':'0'}}}),r=await p.executor.run();expect(r.stopReason).toBe(null);expect(r.newAttempts).toBe(90);expect(r.newActualCredits).toBe(45);expect(r.newLocalSupportCandidates).toBe(45)})
 it('requires exact durable canary support and forbids repeat invocation',async()=>{const p=pipeline();await p.executor.run();const s=p.state();s.terminals.delete(p.c.plans.plan.canaryLogicalIds[0]);expect(()=>validateCanary(p.c,s,r=>p.store.raw(r))).toThrow();await expect(p.executor.run()).rejects.toThrow('P2_INVOCATION_REPEATED')})
})
