import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import { execFileSync } from 'node:child_process'
import { identity, sha, validateSchema } from '../../scripts/nq5/schema.mjs'
import { parseExactJson } from '../../scripts/nq5/exact-json.mjs'
import { signedTransfers, magnitudeIdentity, supportable, profile, admit, RULE, CAMPAIGN } from '../../scripts/nq5-b1-r3-r2/signed-flow.mjs'
import { frontier } from '../../scripts/nq5-b1-r3-r2/frontier.mjs'
import { accepted, seal, CONTRACT_SHA } from '../../scripts/nq5-b1-r3-r2/authority.mjs'
import { pathScan } from '../../scripts/nq5-b1-r2/privacy.mjs'
const root=process.cwd(),sub='0x'+'a'.repeat(40),other='0x'+'b'.repeat(40),token='0x'+'c'.repeat(40),hash='0x'+'d'.repeat(64),p={hash:'1'.repeat(64)},q={logicalId:'2'.repeat(64),family:'profiler/address/transactions',method:'POST',path:'/api/v1/profiler/address/transactions',body:{chain:'ethereum',address:sub,date:{from:'2023-03-13T00:00:00Z',to:'2023-03-13T12:15:00Z'},pagination:{page:1,per_page:100}}},times=[{classification:'NANSEN_SERVER_FILTERED_UNZONED_BLOCK_TIME_CONTEXTUAL',exactUtcFromAcceptedTruth:null}]
const transfer=(amount='1',extra={})=>({chain:'ethereum',from_address:sub,to_address:other,token_address:token,token_amount:amount,...extra}),tx=(sent=[transfer()],received=[],extra={})=>({chain:'ethereum',transaction_hash:hash,tokens_sent:sent,tokens_received:received,...extra}),run=(data=[tx()],request=q)=>signedTransfers({data},request,data.map(()=>times[0]),p,'provider-safe')
describe('R3-R2 explicit signed-flow conversion',()=>{
 for(const bucket of ['TOKENS_SENT','TOKENS_RECEIVED'])for(const amount of ['1','-1','1.0','-1.0','2e3','-2e3','1E-9','-1E-9','123456789012345678901234567890.1234567890123456789','-0.000000000000000000000001'])it(bucket+' preserves magnitude '+amount,()=>{
  const t=transfer(amount,bucket==='TOKENS_RECEIVED'?{from_address:other,to_address:sub}:{}),r=run([bucket==='TOKENS_SENT'?tx([t]):tx([],[t])])
  expect(r.pass).toBe(true);expect(r.normalizedRecords[0].amount).toBe(amount.startsWith('-')?amount.slice(1):amount);expect(r.matrix[0]).toMatchObject({providerSignedDecimalLexeme:amount,provider_bucket:bucket,normalization_rule:RULE,compatibilityProfileIdentity:p.hash,admitted:true,subject_role:bucket==='TOKENS_SENT'?'FROM':'TO'});expect(r.matrix[0].provider_amount_sign).toBe(amount.startsWith('-')?'NEGATIVE':'POSITIVE')
 })
 for(const zero of ['0','-0','0.0','-0.0','0e9','-0E-9'])it('zero '+zero+' excluded without rejecting nonzero sibling',()=>{const r=run([tx([transfer(zero),transfer('-2')])]);expect(r.pass).toBe(true);expect(r.stats.zeroRows).toBe(1);expect(r.normalizedRecords).toHaveLength(1);expect(r.matrix[0]).toMatchObject({admitted:false,reason:'ZERO_NO_QUALIFICATION_UTILITY',amount_magnitude:null})})
 it('zero-only request has no qualification utility',()=>{expect(run([tx([transfer('-0')])])).toMatchObject({pass:false,code:'NO_UNIQUE_NONZERO_ELIGIBLE_TRANSFER',stats:{uniqueAdmittedRows:0}})})
 for(const malformed of ['--1','+1','01','1.','.1','NaN','Infinity','1e','1 2','1e1001','-1e1001',null,1])it('malformed/unbounded '+String(malformed)+' fails closed',()=>expect(()=>run([tx([transfer(malformed)])])).toThrow())
 it('exact JSON precision, exponent and trailing zero lexemes survive',()=>{const b=Buffer.from('{"data":[{"chain":"ethereum","transaction_hash":"'+hash+'","tokens_sent":[{"chain":"ethereum","from_address":"'+sub+'","to_address":"'+other+'","token_address":"'+token+'","token_amount":-12345678901234567890.1200e-2}],"tokens_received":[]}]}'),r=signedTransfers(parseExactJson(b),q,times,p);expect(r.normalizedRecords[0].amount).toBe('12345678901234567890.1200e-2');expect(r.matrix[0].providerSignedDecimalLexeme).toBe('-12345678901234567890.1200e-2')})
 for(const sent of [true,false])it('wrong '+(sent?'sent':'received')+' bucket/address contradicts even with valid sibling',()=>{const wrong=transfer('-2',sent?{from_address:other,to_address:sub}:{}),r=run([sent?tx([transfer(),wrong]):tx([transfer()],[wrong])]);expect(r).toMatchObject({pass:false,code:'BUCKET_ADDRESS_CONTRADICTION',stats:{bucketContradictions:1,uniqueAdmittedRows:0}});expect(r.matrix.every(x=>!x.admitted)).toBe(true)})
 it('sign alone never creates direction',()=>{expect(run([tx([],[transfer('-2')])]).pass).toBe(false);expect(run([tx([transfer('2')])]).pass).toBe(true);expect(run([tx([],[transfer('-2',{from_address:other,to_address:sub})])]).pass).toBe(true)})
 it('mixed-case subject and row addresses match',()=>{const r=run([tx([transfer('-2',{from_address:sub.toUpperCase()})])],{...q,body:{...q.body,address:sub}});expect(r.pass).toBe(true)})
 it('incidental rows excluded from utility, projection and candidates',()=>{const r=run([tx([transfer('-2'),transfer('-3',{from_address:other,to_address:token})])]);expect(r).toMatchObject({pass:true,stats:{incidentalRows:1,uniqueAdmittedRows:1}});expect(r.subjectCandidates).toHaveLength(1);expect(r.matrix[1]).toMatchObject({subject_role:'NONE',reason:'INCIDENTAL_NOT_SUBJECT',admitted:false})})
 it('all incidental including token-contract confusion cannot pass',()=>{const r=run([tx([transfer('-3',{from_address:other,to_address:token,token_address:sub})])]);expect(r.pass).toBe(false)})
 it('label equal to requested address cannot imply participation',()=>{expect(run([tx([transfer('-3',{from_address:other,to_address:token,from_address_label:sub})])]).pass).toBe(false)})
 it('self-transfer across buckets/signs deduplicates one canonical magnitude transfer',()=>{const r=run([tx([transfer('-2',{to_address:sub})],[transfer('2',{to_address:sub})])]);expect(r.stats).toMatchObject({selfRows:2,duplicateRows:1,uniqueAdmittedRows:1});expect(r.matrix[0].subject_role).toBe('SELF');expect(r.matrix[1].duplicateIdentity).toBe(r.matrix[0].duplicateIdentity)})
 it('case-insensitive duplicate identity does not inflate rows',()=>{const r=run([tx([transfer('-2'),transfer('2',{from_address:sub.toUpperCase(),to_address:other.toUpperCase(),token_address:token.toUpperCase()})])]);expect(r.stats).toMatchObject({eligibleNonzeroRows:2,duplicateRows:1,uniqueAdmittedRows:1})})
 it('different exact magnitude lexemes remain distinct, not decimal-rewritten',()=>{expect(run([tx([transfer('-2'),transfer('2.0'),transfer('2e0')])]).stats.uniqueAdmittedRows).toBe(3)})
 it('different hashes, sides and token addresses remain distinct',()=>{const r=run([tx([transfer('-2'),transfer('-2',{token_address:other})]),tx([transfer('-2')],[],{transaction_hash:'0x'+'e'.repeat(64)})]);expect(r.stats.uniqueAdmittedRows).toBe(3)})
 it('raw arrays never mutated or copied into normalized projection',()=>{const x={data:[tx([transfer('-2',{price_usd:null,from_address_label:'PRIVATE_LABEL'})])]},before=structuredClone(x),r=signedTransfers(x,q,times,p);expect(x).toEqual(before);expect(JSON.stringify(r.normalizedRecords)).not.toMatch(/PRIVATE_LABEL|price_usd|tokens_sent|token_amount/);expect(JSON.stringify(r.matrix)).not.toMatch(/PRIVATE_LABEL|price_usd/)})
 for(const bad of [{method:'GET'},{path:'/other'},{family:'historical-balances'},{body:{...q.body,chain:'solana'}}])it('endpoint role scope '+JSON.stringify(bad)+' rejected',()=>expect(()=>run([tx()],{...q,...bad})).toThrow())
 for(const bad of [{chain:'solana'},{from_address:'invalid'},{to_address:null},{token_address:null},{token_amount:undefined}])it('missing/incompatible core '+JSON.stringify(bad)+' rejected',()=>expect(()=>run([tx([transfer('-2',bad)])])).toThrow())
 it('no transfer core fails',()=>expect(()=>run([tx([],[])])).toThrow())
 it('empty response cannot count',()=>expect(run([]).pass).toBe(false))
 it('accepted exact truth time join preserved without invented UTC',()=>{const r=signedTransfers({data:[tx()]},q,[{...times[0],exactUtcFromAcceptedTruth:'2023-03-13T10:00:00Z'}],p);expect(r.normalizedRecords[0]).toMatchObject({accepted_exact_utc:'2023-03-13T10:00:00Z',accepted_exact_time_source:'ACCEPTED_EULER_TRUTH_HASH_JOIN'})})
})
describe('per-call immutable equality, schema and frontier',()=>{
 it('delivery prose templates pass unchanged strict path scan; real synthetic absolute paths still fail',()=>{const source=fs.readFileSync('scripts/nq5-b1-r3-r2/run.mjs','utf8'),readme=source.slice(source.indexOf(" put('README.md'"),source.indexOf("\n put('DELIVERY_MANIFEST.json'")),limits=source.slice(source.indexOf("put('EVIDENCE/KNOWN_LIMITATIONS.md'"),source.indexOf('\n for(const n of LOCAL_SUITES)'));expect(readme.length).toBeGreaterThan(100);expect(limits.length).toBeGreaterThan(100);expect(pathScan({'README.md':readme,'EVIDENCE/KNOWN_LIMITATIONS.md':limits}).status).toBe('PASS');expect(pathScan({'synthetic':'/tmp/synthetic-only'}).status).toBe('FAIL')})
 const good={safelyAdmissible:true,resultCount:1,normalizedSha256:'f'.repeat(64)},terminal={resultCount:1,normalizedSha256:'f'.repeat(64)}
 it('one independent good call remains candidate despite another failed call',()=>{expect([good,{...good,safelyAdmissible:false}].map(a=>supportable(a,terminal))).toEqual([true,false])})
 for(const change of [{resultCount:0},{resultCount:2},{normalizedSha256:'e'.repeat(64)},{safelyAdmissible:false}])it('immutable mismatch '+JSON.stringify(change)+' held',()=>expect(supportable({...good,...change},terminal)).toBe(false))
 it('raw/provider/audit binding failure holds call',()=>expect(supportable(good,terminal,false)).toBe(false))
 it('negative magnitude conversion matches existing payload without hidden sign semantics',()=>{const r=run([tx([transfer('-2')])]),expected={transaction_hash:hash,from_address:sub,to_address:other,token_address:token,amount:'2',evidence_grade:'CONTEXTUAL',temporal_class:times[0].classification};expect(r.normalizedIdentity).toBe(identity([expected]));expect(r.matrix[0].normalization_rule).toBe(RULE)})
 it('generic campaign index remains schema-invalid; empty and exact supportable index allowed',()=>{const schema=JSON.parse(fs.readFileSync('schemas/NQ5_PUBLIC_CALL_INDEX.schema.json')),z='../TRACE_ESCAPE_G6P_NQ5_T1_B1_R3_TRANSACTION_COMPATIBILITY_FOUR_REQUEST_RESUME_AND_NEXT_FRONTIER_DELIVERY_v1.0.0.zip',o=JSON.parse(execFileSync('unzip',['-p',z,'REPORTS/T1_B1_R3_RECONCILIATION_REPORT.json'])).publicIndex[0];expect(()=>validateSchema('provider',[o],schema)).toThrow();expect(()=>validateSchema('provider',[{...o,campaign_id:CAMPAIGN}],schema)).not.toThrow();expect(()=>validateSchema('provider',[],schema)).not.toThrow()})
 const a=accepted(root),pf=profile(a),original=a.context.plans.plan.requests[0],old=a.objects['REPORTS/T1_B1_R3_RECONCILIATION_REPORT.json'].publicIndex[0]
 const call=amount=>{const b=Buffer.from(JSON.stringify({data:[{chain:'ethereum',source_type:'SYNTHETIC',method:'transfer',transaction_hash:hash,block_timestamp:original.body.date.from.slice(0,-1),tokens_sent:[{chain:'ethereum',token_symbol:'SYNTHETIC',from_address:original.body.address,to_address:other,token_address:token,token_amount:1,price_usd:null,value_usd:null}],tokens_received:[]}],pagination:{page:1,per_page:100,is_last_page:true}}).replace('"token_amount":1','"token_amount":'+amount));return {request:original,raw:b,response:{rawSha256:sha(b),rawBytes:b.length,providerRequestId:'synthetic-safe'},terminal:{publicRecord:old}}}
 it('profile sealed, exact scope and Lead observed nonofficial admission',()=>{const {hash:h,...payload}=pf;expect(identity(payload)).toBe(h);expect(pf).toMatchObject({executionContractSha256:CONTRACT_SHA,officialSignedSemanticsAdmission:false,directionFromSign:false,perLogicalRequestAcceptance:true,AUTHORIZED_TO_ISSUE:false})})
 for(const amount of ['-2.0','2e3','-1.000000000000000000001'])it('full guarded admission exact '+amount,()=>{const r=admit(a,call(amount),pf);expect(r.safelyAdmissible).toBe(true);expect(r.normalizedRecords[0].amount).toBe(amount.startsWith('-')?amount.slice(1):amount);expect(r.publicRecord.campaign_id).toBe(CAMPAIGN)})
 it('raw hash mismatch fails before semantics',()=>{const x=call('-2');x.response.rawSha256='0'.repeat(64);expect(admit(a,x,pf).firstFailedStage).toBe('json')})
 it('profile drift rejected',()=>expect(()=>admit(a,call('-2'),{...pf,directionFromSign:true})).toThrow())
 it('unknown field and incompatible optional null remain strict',()=>{const x=call('-2');x.raw=Buffer.from(x.raw.toString().replace('"chain":"ethereum"','"unsafe":true,"chain":"ethereum"'));x.response={...x.response,rawSha256:sha(x.raw),rawBytes:x.raw.length};expect(admit(a,x,pf).firstFailedStage).toBe('schema')})
 const fakeState={starts:new Map()},proj=(address,id,supported,receiver=other,last=true)=>({logicalId:id,leadAcceptanceCandidate:supported,request:{...original,logicalId:id,body:{...original.body,address}},admission:{safelyAdmissible:true},pagination:{is_last_page:last},semantic:{tokenContracts:[token],subjectCandidates:[{transaction_hash:hash,from_address:address,to_address:receiver,token_address:token,amount:'2',amountClass:'POSITIVE'}]}}),fakeResult=projections=>({privateProjections:projections,profile:pf,index:[],crosswalk:{correctedPublicIndexFileSha256:sha(Buffer.from('[]'))},audit:{records:[]},acceptance:{leadAcceptanceCandidates:projections.filter(p=>p.leadAcceptanceCandidate).length}})
 it('held-only counterparty excluded before derivation; accepted MainTrigger can freeze smallest candidate',()=>{const held='0x'+'1'.repeat(40),r=frontier(a,fakeState,fakeResult([proj(sub,'safe',true),proj(other,'held',false,held)]));expect(r.matrix.rows.some(x=>x.subjectAddress===held)).toBe(false);expect(r.matrix.heldCallsExcludedBeforeCandidateDerivation).toEqual([{logicalId:'held',reason:'HELD_CALL_NOT_ACCEPTED_FRONTIER_LINEAGE_UNLESS_INDEPENDENT_ACCEPTED_SEED'}]);expect(r.plan.requests).toHaveLength(1);expect(r.plan.AUTHORIZED_TO_ISSUE).toBe(false);expect(r.reserve).toMatchObject({balanceAnchor:626632,protectedReserve:250,reservePass:true})})
 it('independent accepted seed remains enumerated when observed only in held call',()=>{const trigger='0xb2698c2d99ad2c302a95a8db26b08d17a77cedd4',r=frontier(a,fakeState,fakeResult([proj(sub,'held',false,trigger)]));expect(r.plan).toBeNull();expect(r.matrix.rows.find(x=>x.subjectAddress===trigger).rejectionCode).toBe('NO_SUPPORTABLE_CALLS')})
 it('repeat lineage only from independent supportable calls',()=>{const r=frontier(a,fakeState,fakeResult([proj(sub,'a',true),proj(token,'b',true),proj(other,'held',false)])),row=r.matrix.rows.find(x=>x.subjectAddress===other);expect(row.sourceKinds).toContain('INDEPENDENTLY_REPEATED_ACROSS_SUBJECT_RESPONSES');expect(row.supportingLogicalIds).toEqual(['a','b'])})
 it('exact nonlast page only, no fixed page enumeration',()=>{const r=frontier(a,fakeState,fakeResult([proj(sub,'a',true,other,false),proj(token,'held',false,other,false)]));expect(r.matrix.rows.some(x=>x.subjectAddress===sub&&x.page===2)).toBe(true);expect(r.matrix.rows.some(x=>x.subjectAddress===token&&x.page===2)).toBe(false);expect(r.matrix.rows.every(x=>x.page<=2)).toBe(true);expect(r.policy.noFixedPageCeiling).toBe(true)})
 it('plan/reserve/policy bind corrected index/audit/matrix/signed profile and no authority',()=>{const r=frontier(a,fakeState,fakeResult([proj(sub,'a',true)]));for(const x of [r.plan,r.reserve,r.policy]){const {hash:h,...payload}=x;expect(identity(payload)).toBe(h);expect(x).toMatchObject({AUTHORIZED_TO_ISSUE:false,candidateMatrixIdentity:identity(r.matrix),signedFlowCompatibilityProfileIdentity:pf.hash,correctedPublicIndexIdentity:identity([]),requestAuditIdentity:identity({records:[]}),balanceAnchor:626632,protectedReserve:250})}expect(r.plan.requests.length).toBeLessThanOrEqual(64);expect(r.policy.minimumRequests).toBe(0)})
 it('frontier deterministic and input immutable',()=>{const x=fakeResult([proj(sub,'a',true)]),before=structuredClone(x),one=frontier(a,fakeState,x),two=frontier(a,fakeState,x);expect(one).toEqual(two);expect(x).toEqual(before)})
})
