import fs from 'node:fs'
import {execFileSync} from 'node:child_process'
import {describe,it,expect,vi} from 'vitest'
vi.setConfig({testTimeout:30000})
import {identity,sha} from '../../scripts/nq5/schema.mjs'
import {selectIncrementalRequests,incrementalDecision,dominance,DOMINATED} from '../../scripts/nq5-p2/incremental.mjs'
import {enumerate,freeze,validatePlan} from '../../scripts/nq5-p2/planner.mjs'
import {authorize,resolveCredential} from '../../scripts/nq5-p2/executor.mjs'
import {preparedPlans} from '../../scripts/nq5-p2/prepared.mjs'
import {nextFrontier} from '../../scripts/nq5-p2/frontier.mjs'
import {source,disposition} from '../../scripts/nq5-p2-r1/authority.mjs'
import {derive,finalizeIndependentReplay} from '../../scripts/nq5-p2-r1/model.mjs'
import {recoverProjections} from '../../scripts/nq5-p2/recovery.mjs'
import {supportRecord,requestAudit} from '../../scripts/nq5-p2/audit.mjs'
import {contracts,normalize} from '../../scripts/nq5-p2/admission.mjs'
import {captured} from '../../scripts/nq5-p2/docs.mjs'
import {pathScan} from '../../scripts/nq5-b1-r2/privacy.mjs'
import {verifier,bundlePath} from '../../scripts/nq5-p2-r1/delivery.mjs'
import {compilePartial,recoverCall} from '../../scripts/nq5-p2-r1/partial.mjs'
const root=new URL('../..',import.meta.url).pathname,clone=x=>structuredClone(x),snapshot=preparedPlans(root),phase=snapshot.plans.plan.requests.filter(q=>q.kind==='ACCEPTED_SUBJECT_PHASE'),q=phase[0]
const full={...clone(q),body:{...clone(q.body),date:{from:'2023-03-13T08:45:00Z',to:'2023-03-13T12:15:00Z'}}},fact={logicalId:'accepted-zero',request:full,resultCount:0,isLastPage:true,formallyAccepted:true}
function justification(request=q,facts=[{...fact,resultCount:3}]){const question={id:'SPECIFIC_UNRESOLVED_COUNT_CONTRAST',status:'PREDECLARED_UNRESOLVED',requestLogicalId:request.logicalId,observationKey:identity(request.body),kind:'BOUNDED_COUNT_CONTRAST',text:'Are the three full-window matches distributed outside the initial breach comparison?',localDerivationLimit:'Full-window3 provides no exact supported count at the breach filter.',expectedDistinctSemanticDelta:'Add an observed breach-count versus accepted full-window3 contrast.'},decision={type:'REQUEST_SPECIFIC_INCREMENTAL_UTILITY',logicalId:request.logicalId,requestIdentity:identity(request),questionId:question.id,priorAcceptedEvidenceLogicalIds:['accepted-zero'],acceptedEvidenceIdentity:identity(facts),absentObservationKey:identity(request.body),localDerivationRejection:'EXACT_OBSERVATION_ABSENT_AND_NOT_LOCALLY_DERIVABLE',unresolvedInvestigativeQuestion:question.text,existingEvidenceCannotAnswer:question.localDerivationLimit,downstreamBehavior:{consumerId:request.consumers[0],behavior:'COMPARE_SUPPORTED_COUNTS_AT_EXACT_FILTERS',before:'EXACT_COMPARISON_NOT_SUPPORTED',after:'ADD_BOUNDED_SUPPORTED_COMPARISON',observationKey:identity(request.body),expectedDistinctSemanticDelta:question.expectedDistinctSemanticDelta},boundedStopRule:'NO_ISSUE_WITHOUT_SEPARATE_REVIEW_AND_AUTHORITY_FIRST_BREAKER_NO_REPLACEMENT'};return {facts,question,decision}}
function partialFixture(){const lead=disposition(root),qs=new Map(snapshot.plans.plan.requests.map(q=>[q.logicalId,q])),sources=lead.holds.map(h=>({logicalId:h.priorAcceptedZeroLogicalId,request:{...clone(qs.get(h.logicalId)),body:{...clone(qs.get(h.logicalId).body),date:{from:'2023-03-13T08:45:00Z',to:'2023-03-13T12:15:00Z'}}},normalized:{resultCount:0,pagination:{is_last_page:true}}})).filter((x,i,a)=>a.findIndex(y=>y.logicalId===x.logicalId)===i),index=Array.from({length:18},(_,i)=>({public_call_id:'SYNTHETIC_OLD_'+i,lead_acceptance_order:i+1,authorization_id:'SYNTHETIC_ONLY'})),c={r1Source:source(root),receipt:{executionContractSha256:'a'.repeat(64),campaignId:'SYNTHETIC_ONLY'},sources,index,pubSchema:{type:'array',items:{type:'object',properties:{acceptance_role:{type:'string'},temporal_class:{type:'string'}}}},plans:snapshot.plans,state:{terminals:new Map([2,3,4].map(n=>[String(n),{logicalId:String(n),hash:'b'.repeat(64),publicRecord:{qualification_sequence:n,public_call_id:'SYNTHETIC_HELD_'+n}}]))}},r={report:{requestAuditIdentity:'c'.repeat(64)},projections:[...lead.acceptances,...lead.holds].map((x,i)=>{const request=qs.get(x.logicalId),normalized={resultCount:x.resultCount??0,normalizedSha256:x.normalizedSha256??'4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945'},response={httpStatus:200,providerRequestId:x.providerRequestId,actualCredits:1,quotedCredits:1,headers:{'x-request-id':x.providerRequestId},rawSha256:x.rawSha256??'d751e140bcfb7a7aedfa43575f658c02290326d722ea97f3582af1029513c15b'},terminal={disposition:'SUCCESS_COUNTED',auditDisposition:'PASS',hash:x.terminalIdentity,publicRecord:{qualification_sequence:22+i,public_call_id:'NQ5-'+String(22+i).padStart(6,'0'),request_body_sha256:identity(request.body),response_sha256:response.rawSha256,normalized_sha256:normalized.normalizedSha256,result_count:normalized.resultCount,consumer_execution_identity:'d'.repeat(64)}};return {request,normalized,response,terminal}})},prior={objects:{'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':clone(index),'DELIVERY_MANIFEST.json':{sourceManifestSha256:'e'.repeat(64)}}};return {c,r,lead,prior}}
describe('R1 anti-Cartesian admission and prior evidence dominance',()=>{
 it('rejects all36 templated lattice cells despite unique IDs, questions and six consumers',()=>{expect(phase).toHaveLength(36);expect(new Set(phase.map(q=>q.logicalId)).size).toBe(36);expect(selectIncrementalRequests({candidates:phase}).requests).toHaveLength(0)})
 it('does not admit a phase partition alone',()=>expect(incrementalDecision(q,null,[]).admitted).toBe(false))
 it('ignores self-asserted noPadding as admission evidence',()=>expect(selectIncrementalRequests({candidates:[{...q,noPadding:true}]}).requests).toHaveLength(0))
 it('rejects templated business questions and generated consumer IDs without unresolved delta',()=>expect(incrementalDecision({...q,businessQuestion:'How does SUBJECT in PHASE compare?',consumers:['GENERATED.CONSUMER']},{noPadding:true},[]).admitted).toBe(false))
 it('proves exact prior bounded full-window zero dominance',()=>{expect(dominance(q,[fact]).logicalId).toBe('accepted-zero');expect(incrementalDecision(q,null,[fact]).rejectionCode).toBe(DOMINATED)})
 it('does not turn provider bounded no-match into chain-negative evidence',()=>{expect(dominance(q,[{...fact,isLastPage:false}])).toBe(null);expect(dominance(q,[{...fact,formallyAccepted:false}])).toBe(null);expect(dominance(q,[{...fact,resultCount:1}])).toBe(null)})
 it('requires exact endpoint, filter, page and encompassing window for dominance',()=>{for(const change of [x=>x.path='/different',x=>x.body.pagination.page=2,x=>x.body.filters={to_address:q.subjectAddress},x=>x.body.date.from='2023-03-13T09:00:00Z']){const x=clone(full);change(x);expect(dominance(q,[{...fact,request:x}])).toBe(null)}})
 it('admits only a separately bound falsifiable unresolved count contrast as research metadata, never issue authority',()=>{const {facts,question,decision}=justification();const a=incrementalDecision(q,decision,facts,[question]);expect(a.admitted).toBe(true);expect(a.AUTHORIZED_TO_ISSUE).toBe(false)})
 it('rejects changed observation, evidence, consumer behavior or stop rule',()=>{for(const change of [d=>d.requestIdentity='f'.repeat(64),d=>d.acceptedEvidenceIdentity='f'.repeat(64),d=>d.absentObservationKey='f'.repeat(64),d=>d.downstreamBehavior.after='GENERATED_ID_ONLY',d=>d.downstreamBehavior.consumerId='UNKNOWN',d=>d.boundedStopRule='RESCUE']){const {facts,question,decision}=justification();change(decision);expect(incrementalDecision(q,decision,facts,[question]).admitted).toBe(false)}})
 it('does not allow a generic contrast to rescue dominated zeros',()=>{const {question,decision}=justification(q,[fact]);expect(incrementalDecision(q,decision,[fact],[question]).rejectionCode).toBe(DOMINATED)})
 it('has no current default inventory, live-ready freeze, authorization or credential-read path',()=>{expect(enumerate({}).requests).toEqual([]);expect(freeze({}).liveReady).toBe(false);expect(()=>validatePlan({})).toThrow();expect(()=>authorize({})).toThrow();expect(()=>resolveCredential({})).toThrow();const code=fs.readFileSync(new URL('../../scripts/nq5-p2/executor.mjs',import.meta.url),'utf8');expect(code).not.toContain('process.env.NANSEN_API_KEY');expect(code).not.toContain('NANSEN_API_KEY.txt')})
 it('keeps P3 and LaneC false even for synthetic perfect local support without new authority',()=>{const f=nextFrontier({}, {report:{clean:true},execution:{stopReason:null}}, {roles:['a','b','c'],supportFraction:1});expect(f.plan).toBe(null);expect(f.matrix.gate.pass).toBe(false);expect(f.matrix.LaneC).toBe(false);expect(f.matrix.controllerSeamCommit).toBe(false)})
 it('blocks external HTTP, DNS and socket APIs in a credential-free remediation process',()=>{const script="const dns=require('node:dns'),net=require('node:net'),https=require('node:https');let n=0;for(const f of[()=>fetch('https://example.invalid'),()=>dns.lookup('example.invalid',()=>{}),()=>net.connect({host:'example.invalid',port:443}),()=>https.get('https://example.invalid')]){try{f()}catch{n++}}if(n!==4)process.exit(1);console.log('FOUR_EXTERNAL_APIS_BLOCKED')";const out=execFileSync('node',['--require',new URL('../../scripts/nq5-r2/hold.cjs',import.meta.url).pathname,'-e',script],{env:{PATH:process.env.PATH},encoding:'utf8'});expect(out).toContain('FOUR_EXTERNAL_APIS_BLOCKED')})
})
describe('R1 per-call partial acceptance remains independent and private history immutable',()=>{
 it('binds seven orders19–25 and three holds while preserving old18 rows and all private fixtures',()=>{const f=partialFixture(),before=JSON.stringify([f,[...f.c.state.terminals]]),out=compilePartial(f.c,f.r,f.lead,f.prior);expect(out.index).toHaveLength(25);expect(out.receipt.newFormalLeadAccepted).toBe(7);expect(out.receipt.permanentlyHeldSupplierTerminals).toBe(6);expect(out.index.slice(0,18)).toEqual(f.c.index);expect(out.index.slice(18).map(r=>r.lead_acceptance_order)).toEqual([19,20,21,22,23,24,25]);expect(JSON.stringify([f,[...f.c.state.terminals]])).toBe(before);expect(out.receipt.P3_AUTHORIZED_TO_ISSUE).toBe(false)})
 it('blocks one mismatched identity without erasing six independent acceptances',()=>{const f=partialFixture();f.lead.acceptances[0].providerRequestId='INCORRECT';const out=compilePartial(f.c,f.r,f.lead,f.prior);expect(out.accepted).toHaveLength(6);expect(out.held).toHaveLength(3);expect(out.index).toHaveLength(24);expect(out.individualBlockers).toHaveLength(1);expect(out.status).toBe('BLOCKED_WITH_EVIDENCE')})
 it('never substitutes public identity or renumbers immutable supplier qualification',()=>{const f=partialFixture();f.r.projections[0].terminal.publicRecord.public_call_id='NQ5-999999';expect(()=>recoverCall(f.lead.acceptances[0],f.c,f.r)).toThrow();expect(compilePartial(f.c,f.r,f.lead,f.prior).accepted).toHaveLength(6)})
 it('excludes held and unknown/unissued requests, no pending accepted-index rows',()=>{const f=partialFixture(),out=compilePartial(f.c,f.r,f.lead,f.prior);expect(out.index.slice(18).every(r=>r.lead_acceptance_status==='ACCEPTED'&&r.attribution==='Powered by Nansen API'&&!r.raw_payload_published)).toBe(true);for(const h of out.held)expect(out.index.some(r=>r.public_call_id===h.publicCallId)).toBe(false)})
})

describe('R1 report and archive entry-point parser regression',()=>{it('imports reporting safely and parses the standalone verifier without executing private replay',()=>{expect(typeof derive).toBe('function');expect(()=>execFileSync('node',['--input-type=module','--check'],{input:verifier(),env:{PATH:process.env.PATH}})).not.toThrow()})})

describe('R1 bundle generation admission regression',()=>{it('generates outside the exclusive-write package target so verified copy cannot collide',()=>{const temp='/tmp/SYNTHETIC_R1_DELIVERY_ONLY';expect(bundlePath(temp)).toBe(temp+'/trace-escape-complete.bundle');expect(bundlePath(temp)).not.toBe(temp+'/package/GIT/trace-escape-complete.bundle');const code=fs.readFileSync(new URL('../../scripts/nq5-p2-r1/delivery.mjs',import.meta.url),'utf8');expect(code).toContain('const bundle=bundlePath(temp)');expect(code).toContain("put('GIT/trace-escape-complete.bundle',fs.readFileSync(bundle))")})})

describe('R1 public continuity notes path boundary',()=>{it('admits actual Lead notes in the unchanged public KT path scanner without exemptions',()=>{const notes=fs.readFileSync(new URL('../../docs/G6P_NQ5_T1_P2_R1_NOTES_FOR_LEAD.md',import.meta.url),'utf8');expect(pathScan({'EVIDENCE/KT_CONTINUITY_DELTA.json':Buffer.from(JSON.stringify({notesForLead:notes}))})).toMatchObject({status:'PASS',absoluteFilesystemPathFindings:0})})})

describe('R1 finite public-purpose compatibility',()=>{it('admits only exact compiled accepted-purpose codes when older index schema enum excludes P2 concepts',()=>{const f=partialFixture();f.c.pubSchema.items.properties.purpose_code={enum:['FLOW_DIRECTION_QUERY']};const out=compilePartial(f.c,f.r,f.lead,f.prior);expect(out.index).toHaveLength(25);expect(out.indexSchema.items.properties.purpose_code.enum).toContain('FILTER_DEMONSTRATION');expect(out.indexSchema.items.properties.purpose_code.enum).toContain('HAYSTACK_BASELINE_FILTER_DEMONSTRATION');expect(out.indexSchema.items.properties.purpose_code.enum).not.toContain('ARBITRARY_PURPOSE')})})

function replayFixture(){
 const f=partialFixture(),c=f.c,state=c.state,bodies=new Map(),qs=new Map(c.plans.plan.requests.map(q=>[q.logicalId,q]))
 c.admission=contracts(captured(root),{objects:{'OFFICIAL_DOCS/INDEX.json':JSON.parse(fs.readFileSync(new URL('../../docs/official/p1/INDEX.json',import.meta.url)))}});c.truth={};c.corpus={contract:{hash:'a'.repeat(64)}};c.receipt.hash='b'.repeat(64);c.prior={objects:{'EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':{records:[]},'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':clone(c.index)}}
 for(const s of c.sources)s.normalized.rows=[]
 state.starts=new Map();state.responses=new Map();state.rawRecoveryFailures=new Map()
 const terminals=f.r.projections.map((p,i)=>{
  const q=p.request,id=q.logicalId,row={...p.response,logicalId:id,attempt:1,rawName:id+'.1.bin',remainingCredits:622270},bytes=Buffer.from(JSON.stringify({data:[],pagination:{page:1,per_page:100,is_last_page:true}}))
  row.rawSha256=sha(bytes);row.rawBytes=bytes.length;const n=normalize(q,bytes,c.admission,c.truth),t={...p.terminal,logicalId:id,attempt:1,normalizedSha256:n.normalizedSha256,resultCount:n.resultCount,publicRecord:supportRecord(c,q,row,n,22+i)}
  state.starts.set(id+'.1',{logicalId:id,attempt:1,hash:'c'.repeat(64),issuedAtUtc:'2026-09-17T22:00:00Z',requestBodySha256:identity(q.body),requestWireBodySha256:q.wireBodySha256,reservedCredits:1});state.responses.set(id+'.1',row);state.terminals.set(id,t);bodies.set(row.rawName,bytes)
  const expected=[...f.lead.acceptances,...f.lead.holds].find(x=>x.logicalId===id);expected.rawSha256=row.rawSha256;expected.normalizedSha256=n.normalizedSha256;expected.resultCount=0
  return t
 })
 f.prior.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json']=requestAudit(c,state,r=>bodies.get(r.rawName))
 function run(rawFor){const recovery=recoverProjections(c,state,terminals,qs,rawFor,{independent:true}),audit=requestAudit(c,state,rawFor,undefined,recovery),r={recovery,projections:recovery.projections,audit,report:{requestAuditIdentity:identity(audit)}};return {out:finalizeIndependentReplay(c,r,f.lead,f.prior),r}}
 return {...f,state,bodies,run}
}
describe('R1 full per-call replay-to-disposition orchestration',()=>{
 for(let i=0;i<7;i++)it('isolates unavailable accepted body '+(19+i)+' while preserving six supplier identities and all observed charge facts',()=>{
  const f=replayFixture(),id=f.lead.acceptances[i].logicalId,before=JSON.stringify([...f.state.terminals]),{out,r}=f.run(row=>{if(row.logicalId===id)throw new Error('SYNTHETIC_UNAVAILABLE_BODY');return f.bodies.get(row.rawName)})
  expect(out.accepted).toHaveLength(6);expect(out.held).toHaveLength(3);expect(out.index).toHaveLength(24);expect(out.individualBlockers).toHaveLength(1);expect(out.individualBlockers[0].logicalId).toBe(id);expect(out.status).toBe('BLOCKED_WITH_EVIDENCE');expect(r.recovery.counted).toBe(10);expect([...f.state.responses.values()].reduce((n,x)=>n+x.actualCredits,0)).toBe(10);expect(r.audit.p2Records.find(p=>p.request.logicalId===id)).toMatchObject({runtimeEvidenceProven:false,localSupportCandidate:false,resultCount:null});expect(JSON.stringify([...f.state.terminals])).toBe(before);expect(out.accepted.map(x=>x.supplierSequence)).toEqual([22,23,24,25,26,27,28].filter(x=>x!==22+i))
 })
 it('isolates a raw hash mismatch or earlier dual-store unavailability without renumbering',()=>{for(const mode of ['HASH_MISMATCH','RAW_PAIR_UNAVAILABLE']){const f=replayFixture(),id=f.lead.acceptances[0].logicalId;if(mode==='RAW_PAIR_UNAVAILABLE')f.state.rawRecoveryFailures.set(id,'FINITE_BOUNDED_RAW_UNAVAILABLE');const {out}=f.run(row=>row.logicalId===id?Buffer.from('{}'):f.bodies.get(row.rawName));expect(out.accepted).toHaveLength(6);expect(out.held).toHaveLength(3);expect(out.status).toBe('BLOCKED_WITH_EVIDENCE')}})
 it('keeps shared durable metadata mismatches globally fatal and enables independent mode only in the R1 orchestration',()=>{const f=replayFixture(),id=f.lead.acceptances[0].logicalId;f.prior.objects['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'].p2BreadthReview.planIdentity='d'.repeat(64);expect(()=>f.run(row=>{if(row.logicalId===id)throw new Error('UNAVAILABLE');return f.bodies.get(row.rawName)})).toThrow('P2_R1_CURRENT_DURABLE_AUDIT_ARCHIVE_MISMATCH');const code=fs.readFileSync(new URL('../../scripts/nq5-p2-r1/model.mjs',import.meta.url),'utf8');expect(code).toContain('postContext(root,{independentP2Raw:true})');expect(code).toContain('reconcile(c,e,execution,{independentP2Raw:true})')})
})
