import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import { identity, sha, validateSchema } from '../../scripts/nq5/schema.mjs'
import { logicalRequest } from '../../scripts/nq5/planner.mjs'
import { publicBaseline, unknownCounters, historicalBlocked } from '../../scripts/nq5-b3/blocked.mjs'
import { validateSpecific, compareUtility, tuple, utility } from '../../scripts/nq5-b3/planner.mjs'
import { IDS, ISSUE_ORDER, HELD, REVIEWS } from '../../scripts/nq5-b3/authority.mjs'
import { admit } from '../../scripts/nq5-b3/admission.mjs'
import { audit } from '../../scripts/nq5-b3/audit.mjs'
import { authorize, Store, liveTransport, createSyntheticExecutor, validateCanary, assertCapabilityPolicy, claimStart } from '../../scripts/nq5-b3/executor.mjs'
import { deliveryStatus, transferMetrics } from '../../scripts/nq5-b3/reconciliation.mjs'
import { frontier } from '../../scripts/nq5-b3/frontier.mjs'
import { lessons } from '../../scripts/nq5-b3/lessons.mjs'
const c=publicBaseline(process.cwd()),q=c.plans.plan.requests,schema=JSON.parse(fs.readFileSync('schemas/NANSEN_API_REQUEST_AUDIT.schema.json')),hash='0x'+'d'.repeat(64),other='0x'+'b'.repeat(40),token='0x'+'c'.repeat(40)
const bytes=(r,amount='-2.0')=>Buffer.from(JSON.stringify({data:[{chain:'ethereum',source_type:'SYNTHETIC',method:'transfer',transaction_hash:hash,block_timestamp:'2023-03-13T09:00:00',tokens_sent:[{chain:'ethereum',token_symbol:'SYNTHETIC',from_address:r.body.address,to_address:other,token_address:token,token_amount:1,price_usd:null,value_usd:null}],tokens_received:[]}],pagination:{page:1,per_page:100,is_last_page:true}}).replace('"token_amount":1','"token_amount":'+amount))
const row=b=>({rawSha256:sha(b),rawBytes:b.length,providerRequestId:'synthetic-safe'})
function synthetic(statuses=[200,200,200,200,200],fault=null){const cc={...c,state:{rows:[],starts:new Map(),responses:new Map(),terminals:new Map()}},s=cc.state,raw=new Map(),seen=[],events=[];let active=0,max=0;const store={syntheticOnly:true,context:cc,rows:s.rows,append(p){if(fault==='terminal'&&p.kind==='TERMINAL')throw Error('SYNTHETIC_STORAGE_FAILURE');const r={...p,sequence:s.rows.length+1,hash:identity({...p,sequence:s.rows.length+1})};s.rows.push(r);(r.kind==='START'?s.starts:r.kind==='RESPONSE'?s.responses:s.terminals).set(r.kind==='TERMINAL'?r.logicalId:r.logicalId+'.'+r.attempt,r);events.push(r.kind+'.'+r.logicalId);return r},persist(id,attempt,b){if(fault==='raw')throw Error('SYNTHETIC_RAW_FAILURE');const n=id+'.'+attempt+'.bin';raw.set(n,b);return {rawName:n,rawSha256:sha(b),rawBytes:b.length}},raw(r){return raw.get(r.rawName)},current(){return s}},transport=async r=>{const i=IDS.indexOf(r.logicalId);seen.push(r.logicalId);active++;max=Math.max(max,active);await new Promise(resolve=>setTimeout(resolve,i===0?15:2));active--;const headers={'x-request-id':'synthetic-'+i,'x-nansen-credits-cost':'1','x-nansen-credits-used':'1','x-nansen-credits-remaining':'625960'};if(fault==='provider')delete headers['x-request-id'];if(fault==='cost')headers['x-nansen-credits-used']='2';return {status:statuses[i],bytes:bytes(r,fault==='zero'?'0':'-2.0'),headers}};const executor=createSyntheticExecutor({context:cc,store,transport,rate:{acquire:async()=>true,headers:()=>{}},sleep:async()=>{},random:()=>0});return {cc,store,seen,events,executor,get max(){return max}}}
describe('B3 safe public acceptance and exact representative plan',()=>{
 it('three formal acceptances keep supplier sequences distinct',()=>{expect(c.lead.leadAcceptedSuccesses).toBe(3);expect(c.lead.supplierCountedTerminals).toBe(6);expect(c.lead.acceptanceCrosswalk.map(x=>[x.immutableSupplierSequence,x.leadAcceptanceOrder])).toEqual([[1,1],[5,2],[6,3]]);expect(c.lead.oldOneRequestBatch3PlanDisposition).toContain('REJECTED')})
 it('exact five canonical IDs, stated order and credits independently recompute',()=>{expect(q.map(logicalRequest)).toEqual(IDS);expect(validateSpecific(q)).toBe(true);expect(c.plans.plan.expectedCredits).toBe(5);expect(c.plans.plan.worstCaseCredits).toBe(15);expect(c.plans.reserve.remainingAfterWorstCase).toBe(625959);expect(c.plans.plan.AUTHORIZED_TO_ISSUE).toBe(false)})
 for(const type of ['singleton','sixth','page2','held','sequence','duplicate','consumer','lens','purpose','proof','cell','address','integration'])it('rejects '+type,()=>{const x=structuredClone(q);if(type==='singleton')x.splice(1);if(type==='sixth')x.push(x[0]);if(type==='page2')x[0].body.pagination.page=2;if(type==='held')x[0].lineage.push(HELD[0]);if(type==='sequence')x[0].sequence=2;if(type==='duplicate')x[0].lineage.push(x[0].lineage[0]);if(type==='consumer')x[0].consumers=[];if(type==='lens')x[0].lens='ACTIVITY';if(type==='purpose')x[0].purpose='DEAD_END_DISCOVERY';if(type==='proof')x[0].frontierProof.candidateMatrixRowIdentity=q[1].frontierProof.candidateMatrixRowIdentity;if(type==='cell')x[0].coverageCells=['CELL.'+'0'.repeat(64)];if(type==='address')x[0].body.address=other;if(type==='integration')x[0].foregroundGameplayIntegrationAccepted=true;expect(()=>validateSpecific(x)).toThrow()})
 it('logical lineage once per support; each transaction/transfer once',()=>{for(const r of q){expect(r.lineage.length).toBe(new Set(r.lineage).size);expect(r.lineage.filter(v=>v.startsWith('DURABLE_SUBJECT_TRANSFER.')).length).toBe(r.frontierProof.supportingLogicalIds.length);expect(r.frontierProof.supportingTransactionHashes.length).toBe(new Set(r.frontierProof.supportingTransactionHashes).size)}})
 it('utility beats a lexical winner',()=>{const a={subjectAddress:'0xaaaa',page:1,sourceKinds:[],supportingLogicalIds:['x'],supportingTransactionHashes:['x'],namedConsumers:['c'],alreadyIssuedEquivalent:false},b={...a,subjectAddress:'0xffff',supportingTransactionHashes:['x','y','z']};expect([a,b].sort(compareUtility)[0]).toBe(b)})
 it('public reconstruction cannot authorize, write or resolve a credential',()=>{expect(()=>authorize(c,{docs:{}})).toThrow();expect(()=>new Store(c,{})).toThrow();expect(()=>liveTransport(c,{})).toThrow()})
 it('22 complete audit records explicitly mark accepted calls',()=>{const a=audit(c,c.state,()=>{throw Error('NO_RAW_READ')});expect(a.records.length).toBe(22);expect(a.records.filter(r=>r.formalLeadAcceptance?.leadAccepted).length).toBe(3);expect(a.records.filter(r=>r.batchId==='B3').every(r=>r.signedFlowReview.leadAccepted===false)).toBe(true);expect(()=>validateSchema('provider',a,schema)).not.toThrow()})
 it('held record cannot acquire formal acceptance',()=>{const a=audit(c,c.state,()=>{}),r=a.records.find(r=>r.logicalId===HELD[0]);r.formalLeadAcceptance=structuredClone(a.records.find(r=>r.formalLeadAcceptance).formalLeadAcceptance);expect(()=>validateSchema('provider',a,schema)).toThrow()})
})
describe('B3 conditional ramp and durable independent count',()=>{
 it('canary2 then remaining3 with dispatch-order terminals and max3',async()=>{const x=synthetic(),r=await x.executor.run();expect(x.seen).toEqual(ISSUE_ORDER);expect([...x.store.current().terminals.keys()]).toEqual(ISSUE_ORDER);expect(r.newAttempts).toBe(5);expect(r.newLocalSupportCandidates).toBe(5);expect(r.maximumInFlight).toBe(3);expect(x.max).toBe(3);const firstRemaining=x.events.findIndex(v=>v==='START.'+IDS[1]);expect(x.events.indexOf('TERMINAL.'+IDS[0])).toBeLessThan(firstRemaining);expect(x.events.indexOf('TERMINAL.'+IDS[3])).toBeLessThan(firstRemaining);expect(r.unresolvedReservations).toBe(0)},30000)
 for(const fault of ['raw','terminal','provider','cost','zero'])it('canary '+fault+' stops before any remaining request',async()=>{const x=synthetic(undefined,fault),r=await x.executor.run();expect(x.seen.length).toBeLessThanOrEqual(2);expect(x.seen.every(id=>[IDS[0],IDS[3]].includes(id))).toBe(true);expect(r.stopReason).toBeTruthy()})
 it('independent in-flight success survives failed canary but ramp is held',async()=>{const x=synthetic([400,200,200,200,200]),r=await x.executor.run();expect(r.newAttempts).toBe(2);expect(r.newLocalSupportCandidates).toBe(1);expect(x.seen).toEqual(ISSUE_ORDER.slice(0,2))})
 it('one invocation cannot be repeated',async()=>{const x=synthetic();await x.executor.run();await expect(x.executor.run()).rejects.toThrow()},30000)
 it('remaining call cannot start before ramp',async()=>{const x=synthetic();await expect(x.executor.issue(IDS[1])).rejects.toThrow('B3_DISPATCH_PHASE');expect(x.seen).toEqual([])})
 it('missing canary terminal cannot approve ramp',()=>expect(()=>validateCanary(c,c.state,()=>{})).toThrow())
 for(const flag of ['storeBranded','transportBranded'])it('production refuses missing '+flag,()=>expect(()=>assertCapabilityPolicy({production:true,storeBranded:true,transportBranded:true,injectedAdapters:false,[flag]:false})).toThrow())
 it('synthetic store cannot acquire real private roots',()=>{const x=synthetic();x.store.roots=['SYNTHETIC'];expect(()=>createSyntheticExecutor({context:x.cc,store:x.store,transport:async()=>{}})).toThrow()})
})
describe('B3 semantic and evidence corrections',()=>{
 it('purpose utility explicitly scores the actual question code',()=>{const r={subjectAddress:other,page:1,sourceKinds:[],supportingLogicalIds:[],supportingTransactionHashes:[],namedConsumers:['c'],alreadyIssuedEquivalent:false};expect(utility({...r,purpose:'FLOW_DIRECTION_QUERY'}).purposeValue).toBe(3);expect(utility({...r,purpose:'DEAD_END_DISCOVERY'}).purposeValue).toBe(1)})
 it('local evidence and reviewer drift recheck precede first private write and key access',()=>{const s=fs.readFileSync('scripts/nq5-b3/executor.mjs','utf8');expect(s).toContain('assertBaseline(c,{verifyPrivate:true});sourceCurrent(c);localGate(c.root);reviewGate(c.root,0);p.recheckDocs(p.docs);');expect(s).toContain('assertBaseline(c,{verifyPrivate:true,locked:true});sourceCurrent(c);localGate(c.root);reviewGate(c.root,0);p.recheckDocs(p.docs);')})
 for(const i of [0,1,2,3,4])for(const amount of ['-2.0','-1.000000000000000000001','2e3'])it('call'+i+' exact '+amount,()=>{const b=bytes(q[i],amount),a=admit(c,q[i],b,row(b),7+i);expect(a.safelyAdmissible).toBe(true);expect(a.normalizedRecords[0].amount).toBe(amount.replace(/^-/,''));expect(a.publicRecord.question_lens).toBe('RELATIONSHIPS')})
 it('global tuple identity is separate from per-call row sum',()=>{const r={transaction_hash:hash,from_address:other,to_address:q[0].body.address,token_address:token,amount:'2.0'},p=[r,r];expect(p.length).toBe(2);expect(new Set(p.map(tuple)).size).toBe(1)})
 it('partial five or over15 attempts cannot deliver',()=>{const r={clean:true,newDistinctRequests:5,newSettledExactRequests:5,newAttempts:5};expect(deliveryStatus(r,{stopReason:null})).toBe('DELIVERED_PENDING_LEAD_REVIEW');for(const x of [{clean:false},{newDistinctRequests:4},{newSettledExactRequests:4},{newAttempts:16}])expect(deliveryStatus({...r,...x},{stopReason:null})).toBe('BLOCKED_WITH_EVIDENCE')})
 it('rolling lessons preserve19 plus8',()=>expect(lessons().rows).toHaveLength(27))
 it('marks the inherited two-call operation as historical B2, not current B3 authority',()=>{const rows=lessons().rows;expect(rows.find(r=>r.findingId==='BOUNDED_TRUTHFUL_PATH').classification).toBe('HISTORICAL_B2_OPERATIONAL_STATE');expect(rows.find(r=>r.findingId==='MATURE_BOUNDED_BATCHES').classification).toBe('CURRENT_OPERATIONAL_STATE')})
 it('unknown durable counters are null, never fabricated0',()=>{const u=unknownCounters();expect(u.newAttempts).toBeNull();expect(u.supplierCountedTerminals).toBeNull();expect(u.newFactsAdmitted).toBe(false)})
 it('B4 has all meaningful rows, no singleton deferral and never issue authority',()=>{const source=fs.readFileSync('scripts/nq5-b3/frontier.mjs','utf8');expect(source).not.toContain('DEFERRED_SMALLEST_MEANINGFUL_BATCH');expect(source).toContain('DEFERRED_EXACT_MAXIMUM_64');expect(source).toContain('rows.sort(compareUtility)');expect(source).toContain('AUTHORIZED_TO_ISSUE:false')})
})
