import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {describe,it,expect,vi} from 'vitest'
import {identity,sha} from '../../scripts/nq5/schema.mjs'
import {AUTH,CONTRACT_SHA} from '../../scripts/nq5-p1/authority.mjs'
import {contracts,TGM,COUNTER,DAI,HASHES,normalize,validateRequest} from '../../scripts/nq5-p1/admission.mjs'
import {requests,validatePlan,canonical,freeze,SUBJECTS} from '../../scripts/nq5-p1/planner.mjs'
import {QUESTION,CLARIFICATION,PAGES,permitted} from '../../scripts/nq5-p1/docs.mjs'
import {claimStart,Store,resolveCredential,createSyntheticExecutor,Executor,validateCanary} from '../../scripts/nq5-p1/executor.mjs'
import {requestAudit,supportRecord} from '../../scripts/nq5-p1/audit.mjs'
import {nextFrontier} from '../../scripts/nq5-p1/reconciliation.mjs'
import {contextFingerprint} from '../../scripts/nq5-p1/context.mjs'
import {blockedEntries} from '../../scripts/nq5-p1/blocked.mjs'
import {assertPrivateAncestry} from '../../scripts/nq5-b1-r3/gate-proof.mjs'
import {pathScan} from '../../scripts/nq5-b1-r2/privacy.mjs'
const index=JSON.parse(fs.readFileSync(new URL('../../docs/official/p1/INDEX.json',import.meta.url))),bytes=JSON.parse(fs.readFileSync(new URL('../../docs/official/p1/CAPTURED_DOCUMENT_BYTES.json',import.meta.url))),official={index,bodies:Object.fromEntries(Object.entries(bytes.bodies).map(([n,t])=>[n,Buffer.from(t)])),identity:identity(index)},A=contracts(official),Q=requests(A),truth=Object.fromEntries(HASHES.map(h=>[h,h.startsWith('0xc310')?'2023-03-13T08:50:59Z':h.startsWith('0x298b')?'2023-03-13T09:12:23Z':'2023-03-13T11:38:11Z'])),q=Q.find(q=>q.body.filters?.from_address===SUBJECTS.FIRST)
const transfer=(h=HASHES[0],from=SUBJECTS.FIRST,to=SUBJECTS.VAULT)=>({block_timestamp:'2023-03-13T11:38:11',transaction_hash:h,from_address:from,to_address:to,transfer_amount:1,from_address_label:'SYNTHETIC_LABEL_SENTINEL',to_address_label:'SYNTHETIC_LABEL_SENTINEL',transfer_value_usd:2,transaction_type:'UNADMITTED_FREE_TEXT'})
const response=(rows=[transfer()])=>({data:rows,pagination:{page:1,per_page:100,is_last_page:true}}),raw=x=>Buffer.from(JSON.stringify(x)),clone=x=>structuredClone(x),counterQ=Q.find(q=>q.family===COUNTER)
const n=x=>normalize(q,raw(x),A,truth)
describe('P1 exact current document and smallest multi-family pilot admission',()=>{
 it('binds both current family paths, rate limits and one-credit/five-credit pricing',()=>{expect(A.tgm.status).toMatch(/^ADMITTED/);expect(A.counter.status).toMatch(/^ADMITTED/);expect(A.tgm.quotedCredits).toBe(1);expect(A.counter.quotedCredits).toBe(5)})
 it('asks exactly the one controlling singular/plural question',()=>{expect(index.clarificationRequests).toBe(1);expect(index.snapshots.find(s=>s.name==='clarification').url).toBe(CLARIFICATION);expect(CLARIFICATION).toContain(encodeURIComponent(QUESTION))})
 it('rejects provider, account, labels, arbitrary docs and changed clarification URLs',()=>{for(const url of ['https://api.nansen.ai/api/v1/account','https://docs.nansen.ai/api/profiler/address-labels.md',PAGES.tgm+'?ask=other'])expect(permitted(url)).toBe(false)})
 it('requires exact successful required official snapshots',()=>{const d=clone(official);d.bodies=official.bodies;d.index.snapshots.find(s=>s.name==='terms').httpStatus=404;expect(()=>contracts(d)).toThrow()})
 it('holds ambiguous secondary policy without blocking nine TGM questions',()=>{const d={...official,bodies:{...official.bodies,clarification:Buffer.from('Generic unsupported answer')}};const a=contracts(d);expect(a.counter.status).toBe('COUNTERPARTIES_HELD_PUBLIC_POLICY_AMBIGUOUS');expect(requests(a)).toHaveLength(9);validatePlan(requests(a),a)})
 it('freezes ten independently named questions at14/42credit bounds without padding',()=>{validatePlan(Q,A);const p=freeze(A,{hash:'a'.repeat(64),campaignId:'SYNTHETIC_NO_PRIVATE_ROOTS'},[],{});expect(p.plan.requests).toHaveLength(10);expect(p.plan.expectedCredits).toBe(14);expect(p.plan.worstCaseCredits).toBe(42);expect(p.plan.AUTHORIZED_TO_ISSUE).toBe(false);expect(p.plan.canaryLogicalIds).toHaveLength(4)})
 it('bundles all three exact hashes once and rejects fragmentation',()=>{expect(Q.filter(q=>q.body.filters?.transaction_hash)).toHaveLength(1);const x=clone(Q[0]);x.body.filters.transaction_hash=[HASHES[0]];expect(()=>validateRequest(x,A)).toThrow()})
 it('requires the exact9TGM+1Counter question/coverage/lineage/consumer set',()=>{expect(new Set(Q.map(q=>q.questionId)).size).toBe(10);expect(new Set(Q.flatMap(q=>q.coverageCells)).size).toBe(10);const x=clone(Q);x[1].consumers=Q[2].consumers;expect(()=>validatePlan(x,A)).toThrow()})
 it('rejects canonical duplicates and historical equivalence',()=>{expect(()=>validatePlan(Q,A,[canonical(Q[0])])).toThrow();expect(()=>validatePlan([...Q,Q[0]],A)).toThrow()})
 it('rejects Address Transactions, historical and general endpoint fallback',()=>{for(const family of ['profiler/address/transactions','profiler/address/historical-balances','transaction-with-token-transfer-lookup'])expect(()=>validateRequest({...q,family,path:'/api/v1/'+family},A)).toThrow()})
 it('rejects label, smartmoney, USD and entity-name filters',()=>{for(const key of ['only_smart_money','from_address_label','transfer_value_usd','entity_name']){const x=clone(q);x.body.filters={[key]:true};expect(()=>validateRequest(x,A)).toThrow()}})
 it('restricts secondary requests to wallet/address/Tokens and a named count consumer',()=>{for(const[k,v]of [['group_by','entity'],['source_input','ETH'],['entity_name','SYNTHETIC_NAME']]){const x=clone(counterQ);x.body[k]=v;expect(()=>validateRequest(x,A)).toThrow()}})
 it('rejects altered date, token, chain, pagination and unknown request fields',()=>{for(const mutate of [x=>x.body.chain='base',x=>x.body.token_address=SUBJECTS.MAIN,x=>x.body.pagination.page=2,x=>x.body.date.from='2023-03-13T00:00:00Z',x=>x.body.private_path='SYNTHETIC']){const x=clone(q);mutate(x);expect(()=>validateRequest(x,A)).toThrow()}})
})
describe('P1 complete no-issue frontier quality gates',()=>{
 const address='0x'+'1'.repeat(40),context={admission:A,plans:freeze(A,{hash:'a'.repeat(64),campaignId:'SYNTHETIC_NO_PRIVATE_ROOTS'},[],{}),receipt:{hash:'a'.repeat(64),campaignId:'SYNTHETIC_NO_PRIVATE_ROOTS'},index:[]},projection=(id,hashes,subject=SUBJECTS.FIRST)=>({logicalId:id,request:{family:TGM,body:{filters:{from_address:subject}}},normalized:{rows:hashes.map(h=>({transaction_hash:h,from_address:subject,to_address:address}))}}),result=p=>({projections:p,report:{clean:true,latestSafeResponseBalance:625707},execution:{stopReason:null},audit:{}}),utilities=rows=>({perCall:rows,gains:[{coverage:'A'},{coverage:'B'}],supportFraction:1});
 it('cannot combine one non-hub transaction with hub-only support to admit an ordinary subject',()=>{const f=nextFrontier(context,result([projection('NONHUB',[HASHES[0]]),projection('HUB',[HASHES[1]])]),utilities([{logicalId:'NONHUB',recursiveFrontierAuthority:true},{logicalId:'HUB',recursiveFrontierAuthority:false}]));expect(f.plan).toBe(null);expect(f.matrix.rows.filter(r=>r.body.filters.from_address===address||r.body.filters.to_address===address).every(r=>r.rejectionCode==='TWO_DISTINCT_NON_HUB_TRANSACTIONS_REQUIRED')).toBe(true)})
 it('freezes only bounded two-transaction non-hub directions with issue false and source cap4',()=>{const f=nextFrontier(context,result([projection('NONHUB',HASHES)]),utilities([{logicalId:'NONHUB',recursiveFrontierAuthority:true}]));expect(f.plan.requests).toHaveLength(2);expect(f.plan.AUTHORIZED_TO_ISSUE).toBe(false);expect(f.matrix.ordinarySourceCap).toBe(4);expect(f.plan.requests.every(q=>q.supportTransactionHashes.length===3&&q.lineage.length===1)).toBe(true)})
 it('retains complete rejection rows but no P2 plan under an accounting breaker',()=>{const r=result([projection('NONHUB',HASHES)]);r.report.clean=false;const f=nextFrontier(context,r,utilities([{logicalId:'NONHUB',recursiveFrontierAuthority:true}]));expect(f.plan).toBe(null);expect(f.matrix.completeCandidateRows).toBeGreaterThan(0);expect(f.matrix.meaningfulCandidates).toBe(0)})
 it('charges the source cap against every supporting parent, not a single allocation alias',()=>{const addresses=[1,2,3,4].map(i=>'0x'+String(i).repeat(40)),p=(id,subject,h)=>({logicalId:id,request:{family:TGM,body:{filters:{from_address:subject}}},normalized:{rows:addresses.map(to=>({transaction_hash:h,from_address:subject,to_address:to}))}}),f=nextFrontier(context,result([p('A',SUBJECTS.FIRST,HASHES[0]),p('B',SUBJECTS.MAIN,HASHES[1])]),utilities([{logicalId:'A',recursiveFrontierAuthority:true},{logicalId:'B',recursiveFrontierAuthority:true}]));expect(f.plan.requests).toHaveLength(4);for(const id of ['A','B'])expect(f.plan.requests.filter(q=>q.lineage.includes(id))).toHaveLength(4);expect(f.matrix.rows.filter(q=>q.rejectionCode==='ORDINARY_NON_HUB_SOURCE_CAP_FOUR')).toHaveLength(4)})
 it('never uses self-only transfers to introduce a missing accepted-seed direction',()=>{const p=projection('SELF',HASHES,SUBJECTS.EARLY);p.normalized.rows.forEach(r=>r.to_address=r.from_address);const f=nextFrontier(context,result([p]),utilities([{logicalId:'SELF',recursiveFrontierAuthority:true}]));expect(f.plan).toBe(null);expect(f.matrix.rows.every(q=>q.rejectionCode==='SELF_ONLY_SUPPORT_EXCLUDED')).toBe(true)})
})
describe('P1 review falsifiers and honest blocked evidence',()=>{
 it('holds a contradictory affirmative-looking answer even when its snapshot is self-consistently rehashed',()=>{const text='Yes. POST /api/v1/profiler/address/counterparties group_by counterparty_address interaction_count Powered by Nansen API /api/profiler/address-counterparties.md /guides/redistribution-guide.md\nHowever, public redistribution of these fields is prohibited. The preceding quoted claim is false.',d={...official,index:clone(index),bodies:{...official.bodies,clarification:Buffer.from(text)}};Object.assign(d.index.snapshots.find(s=>s.name==='clarification'),{sha256:sha(d.bodies.clarification),bytes:d.bodies.clarification.length});const a=contracts(d);expect(a.counter.status).toMatch(/^COUNTERPARTIES_HELD/);expect(a.tgm.status).toMatch(/^ADMITTED/);expect(requests(a)).toHaveLength(9)})
 it('isolates missing,404,malformed or unpriced secondary documents without blocking TGM',()=>{for(const name of ['clarification','counterparties'])for(const kind of ['404','missing','malformed']){const d={...official,index:clone(index),bodies:{...official.bodies}};if(kind==='404')d.index.snapshots.find(s=>s.name===name).httpStatus=404;else if(kind==='missing')delete d.bodies[name];else d.bodies[name]=Buffer.from('Malformed secondary evidence');const a=contracts(d);expect(a.tgm.status).toMatch(/^ADMITTED/);expect(a.counter.status).toMatch(/^COUNTERPARTIES_HELD/);validatePlan(requests(a),a)}},120000)
 it('pins every cached historical object, raw-source byte, schema, tuple list and state map',()=>{const p=syntheticPipeline(),c=p.c;c.root='SYNTHETIC_NON_PRIVATE_ROOT';c.source={candidate:{commit:'a'.repeat(40),tree:'b'.repeat(40)},implementationSha256:'c'.repeat(64)};c.roots=[];c.originalEnvelope={};c.pubSchema={};c.oldTransferIdentities=[];c.prior.bytes={SAFE:Buffer.from('ONE')};Object.assign(c.state,{starts:new Map(),responses:new Map(),terminals:new Map(),bytes:0,bytesSha256:sha(Buffer.alloc(0))});const before=contextFingerprint(c);for(const mutate of [x=>x.prior.objects['PUBLIC/NQ5_PUBLIC_CALL_INDEX.json'].push({sentinel:1}),x=>x.prior.bytes.SAFE=Buffer.from('TWO'),x=>x.pubSchema.relaxed=true,x=>x.oldTransferIdentities.push('d'.repeat(64)),x=>x.state.starts.set('SYNTHETIC',{attempt:1})]){const copy=clone(c);mutate(copy);expect(contextFingerprint(copy)).not.toBe(before)}})
 it('rejects ancestor symlink substitution before private boundaries in an isolated directory fixture',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'p1-synthetic-ancestry-'));try{const parent=path.join(tmp,'parent'),moved=path.join(tmp,'moved'),root=path.join(parent,'root');fs.mkdirSync(root,{recursive:true,mode:0o700});expect(assertPrivateAncestry([root])).toBe(true);fs.renameSync(parent,moved);fs.symlinkSync(moved,parent,'dir');expect(()=>assertPrivateAncestry([root])).toThrow('R3_PRIVATE_ANCESTRY_CHANGED')}finally{fs.rmSync(tmp,{recursive:true,force:true})}})
 it('emits complete bounded unknown-state output without opening or repairing current durable storage',()=>{const p=syntheticPipeline(),c=p.c;c.source={candidate:{commit:'a'.repeat(40),tree:'b'.repeat(40)},implementationSha256:'c'.repeat(64)};c.pubSchema={type:'array'};c.prior.bytes={'SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json':Buffer.from(JSON.stringify({type:'object',additionalProperties:false,required:['records'],properties:{records:{type:'array'}}}))};const d=blockedEntries(c);expect(d.status).toBe('BLOCKED_WITH_EVIDENCE');expect(d.report.newAttempts).toBe(null);expect(d.report.newKnownCredits).toBe(null);expect(d.report.allPrimaryMirrorRawEqual).toBe(null);expect(d.f.plan).toBe(null);expect(d.r.audit.p1Records).toHaveLength(10);expect(d.r.audit.p1Records.every(r=>r.disposition==='UNPROVEN_RUNTIME_STATE'&&!r.runtimeEvidenceProven&&r.resultCount===null)).toBe(true);for(const n of ['REPORTS/T1_P1_EXECUTION_REPORT.json','REPORTS/T1_P1_RECONCILIATION_REPORT.json','PUBLIC/NQ5_PUBLIC_CALL_INDEX.json','EVIDENCE/P1_LIVE_REQUEST_IDENTITY_MATRIX.json','SCHEMAS/NANSEN_API_REQUEST_AUDIT.schema.json'])expect(d.entries).toHaveProperty(n);expect(d.entries['EXECUTION/T1_P1_MULTI_FAMILY_PILOT_ENVELOPE.json'].AUTHORIZED_TO_ISSUE).toBe(false)})
})
describe('P1 endpoint-specific normalization, privacy and claim boundaries',()=>{
 it('strips labels, free text type and USD without imputation',()=>{const r=n(response());expect(r.rows[0]).not.toHaveProperty('from_address_label');expect(JSON.stringify(r)).not.toContain('SYNTHETIC_LABEL_SENTINEL');expect(r.rows[0]).not.toHaveProperty('transfer_value_usd');expect(r.rows[0]).not.toHaveProperty('transaction_type');expect(r.contextual).toBe(true)})
 it('retains original exact high-precision amount lexemes',()=>{const b=raw(response()).toString().replace('"transfer_amount":1','"transfer_amount":8877507.348306697');expect(normalize(q,Buffer.from(b),A,truth).rows[0].amount).toBe('8877507.348306697')})
 it('rejects null, strings, zero, negative and exponent core amounts',()=>{for(const value of ['null','"1"','0','-1','1e3']){const b=raw(response()).toString().replace('"transfer_amount":1','"transfer_amount":'+value);expect(()=>normalize(q,Buffer.from(b),A,truth)).toThrow()}})
 it('rejects unknown and private fields at root and transfer',()=>{for(const x of [{...response(),private_data:true},response([{...transfer(),['api'+'key']:['SYNTHETIC','NOT','A','KEY'].join('_')}]),response([{...transfer(),smart_money:true}])])expect(()=>n(x)).toThrow()})
 it('rejects duplicate JSON keys and malformed UTF8',()=>{expect(()=>normalize(q,Buffer.from('{"data":[],"data":[]}'),A,truth)).toThrow();expect(()=>normalize(q,Buffer.from([0xff]),A,truth)).toThrow()})
 it('requires exact outgoing subject participation and hash-filter membership',()=>{expect(()=>n(response([transfer(HASHES[0],SUBJECTS.MAIN)]))).toThrow();const rows=HASHES.map(h=>transfer(h));rows[0].transaction_hash='0x'+'f'.repeat(64);expect(()=>normalize(Q[0],raw(response(rows)),A,truth)).toThrow()})
 it('requires all three exact hashes in the bundled reconciliation response',()=>{expect(()=>normalize(Q[0],raw(response([transfer()])),A,truth)).toThrow();expect(normalize(Q[0],raw(response(HASHES.map(h=>transfer(h)))),A,truth).rows).toHaveLength(3)})
 it('keeps offsetless provider times contextual and accepted truth joins separate',()=>{const h=HASHES.find(h=>h.startsWith('0xdae'));const r=n(response([transfer(h)]));expect(r.rows[0].temporal_class).toBe('SERVER_FILTERED_UNZONED_CONTEXTUAL');expect(r.rows[0].evidence_grade).toBe('CONTEXTUAL');expect(r.rows[0].accepted_exact_time_reference.utc).toBe('2023-03-13T11:38:11Z');expect(r.rows[0]).not.toHaveProperty('block_timestamp')})
 it('rejects zoned window violations and accepted exact-time conflicts',()=>{for(const stamp of ['2023-03-13T12:16:00Z','2023-03-13T09:00:00Z','bad'])expect(()=>n(response([{...transfer(HASHES.find(h=>h.startsWith('0xdae'))),block_timestamp:stamp}]))).toThrow()})
 it('deduplicates identical transfer tuples but never inflates frontier authority',()=>{const r=n(response([transfer(),transfer()]));expect(r.rows).toHaveLength(1);expect(r.duplicateRows).toBe(1);expect(r.recursiveFrontierAuthority).toBe(false)})
 it('admits only predeclared fully paginated empty provider-query closure without negative proof',()=>{const r=n(response([]));expect(r.emptyRole).toBe(true);expect(r.claimBoundaries).toContain('NO_CHAIN_COMPLETENESS_OR_NEGATIVE_PROOF');const x=response([]);x.pagination.is_last_page=false;expect(()=>n(x)).toThrow()})
 it('rejects page/perpage drift and overbounded responses',()=>{for(const x of [{...response(),pagination:{page:2,per_page:100,is_last_page:true}},response(Array.from({length:101},()=>transfer()))])expect(()=>n(x)).toThrow()})
 it('projects only secondary address/count while stripping labels/token names and volumes',()=>{const x=response([{counterparty_address:SUBJECTS.FIRST,interaction_count:2,counterparty_address_label:['SYNTHETIC_LABEL_SENTINEL'],total_volume_usd:4,tokens_info:[{token_address:DAI,token_symbol:'SYNTHETIC_SYMBOL',token_name:'SYNTHETIC_NAME',num_transfer:'2'}]}]);const r=normalize(counterQ,raw(x),A,truth);expect(r.rows).toEqual([{counterparty_address:SUBJECTS.FIRST,interaction_count:2}])})
 it('rejects secondary unknowns, conflicting counts, unsafe integers, zero/token/self address',()=>{for(const rows of [[{counterparty_address:SUBJECTS.FIRST,interaction_count:2,private_data:true}],[{counterparty_address:SUBJECTS.FIRST,interaction_count:2},{counterparty_address:SUBJECTS.FIRST,interaction_count:3}],[{counterparty_address:DAI,interaction_count:2}],[{counterparty_address:SUBJECTS.MAIN,interaction_count:2}],[{counterparty_address:SUBJECTS.FIRST,interaction_count:1e20}]])expect(()=>normalize(counterQ,raw(response(rows)),A,truth)).toThrow()})
 it('requires prelive capability before credentials, private lock or injectable executor',()=>{expect(()=>resolveCredential({})).toThrow('P1_CREDENTIAL_GATE_REQUIRED');expect(()=>new Store({},{})).toThrow('P1_PRIVATE_WRITE_GATE_REQUIRED');expect(()=>new Executor({context:{},store:{},transport:()=>{}})).toThrow();expect(()=>createSyntheticExecutor({context:{roots:[]},store:{syntheticOnly:true},transport:()=>{}})).toThrow()})
 it('keeps strict absolute-path rejection unchanged',()=>{expect(pathScan({'safe.json':JSON.stringify({rules:'no credential access, documentation refresh, or private writes when blocked'})}).status).toBe('PASS');expect(pathScan({'unsafe.json':'/tmp/synthetic-only'}).status).toBe('FAIL')})
})
function syntheticPipeline(modifier=x=>x){
 const plans=freeze(A,{hash:'a'.repeat(64),campaignId:'SYNTHETIC_NO_PRIVATE_ROOTS'},[],{}),c={admission:A,plans,receipt:{hash:'a'.repeat(64),campaignId:'SYNTHETIC_NO_PRIVATE_ROOTS'},index:[],prior:{objects:{'EVIDENCE/NANSEN_API_REQUEST_AUDIT.json':{records:[]},'PUBLIC/NQ5_PUBLIC_CALL_INDEX.json':[]}},truth,state:{rows:Array.from({length:39},()=>({kind:'SYNTHETIC_HISTORICAL'}))}},rows=[...c.state.rows],bodies=new Map(),state=()=>{const starts=new Map(),responses=new Map(),terminals=new Map();for(const r of rows.slice(39))(r.kind==='START'?starts:r.kind==='RESPONSE'?responses:terminals).set(r.kind==='TERMINAL'?r.logicalId:r.logicalId+'.'+r.attempt,r);return {rows,starts,responses,terminals}},store={syntheticOnly:true,context:c,append(x){const r={...x,hash:identity(x)};rows.push(r);return r},persist(id,attempt,bytes){const rawName=id+'.'+attempt+'.bin';bodies.set(rawName,Buffer.from(bytes));return {rawName,rawSha256:identity([...bytes]),rawBytes:bytes.length}},raw(r){return bodies.get(r.rawName)},current:state};
 // Exact raw SHA uses the production hash primitive; no actual files or roots.
 store.persist=(id,attempt,bytes)=>{const rawName=id+'.'+attempt+'.bin';bodies.set(rawName,Buffer.from(bytes));return {rawName,rawSha256:sha(bytes),rawBytes:bytes.length}};
 let calls=0;const transport=async request=>{calls++;if(!c.plans.plan.canaryLogicalIds.includes(request.logicalId))validateCanary(c,state(),r=>store.raw(r));const data=request.family===COUNTER?[{counterparty_address:SUBJECTS.FIRST,interaction_count:2}]:request.body.filters.transaction_hash?HASHES.map(h=>transfer(h)):request.body.filters.from_address?[transfer(HASHES[0],request.body.filters.from_address,SUBJECTS.VAULT===request.body.filters.from_address?SUBJECTS.FIRST:SUBJECTS.VAULT)]:[transfer(HASHES[0],SUBJECTS.EARLY,request.body.filters.to_address)];await Promise.resolve();return modifier({status:200,bytes:raw(response(data)),headers:{'x-request-id':'SYNTHETIC-P1-'+calls,'x-nansen-credits-used':String(request.expectedCredits),'x-nansen-credits-cost':String(request.expectedCredits),'x-nansen-credits-remaining':'625000'}},request,calls)};
 const executor=createSyntheticExecutor({context:c,store,transport,rate:{acquire:async stopped=>!stopped(),headers:()=>{}},sleep:async()=>{},random:()=>0});return {executor,c,store,state,get calls(){return calls}}
}
describe('P1 synthetic durable execution and accounting controls',()=>{vi.setConfig({testTimeout:120000});
 it('settles the four-family-representative canary before the remaining six, independently supports ten calls',async()=>{const p=syntheticPipeline(),r=await p.executor.run();expect(r.stopReason).toBe(null);expect(r.newAttempts).toBe(10);expect(r.newActualCredits).toBe(14);expect(r.newLocalSupportCandidates).toBe(10);expect(r.maximumInFlight).toBeLessThanOrEqual(8);expect([...p.state().terminals.values()].every(t=>t.publicRecord.lead_acceptance_status==='PENDING_LEAD_REVIEW')).toBe(true)})
 it('drains independent issued successes on a schema breaker without remaining/new replacement issue',async()=>{let first=true;const p=syntheticPipeline((r,q)=>{if(first&&q.family===COUNTER){first=false;return {...r,bytes:raw({data:[],pagination:{page:2,per_page:100,is_last_page:true}})}}return r});const r=await p.executor.run();expect(r.stopReason).toMatch(/BREAKER/);expect(r.newAttempts).toBe(4);expect(r.newLocalSupportCandidates).toBe(3);expect(p.state().terminals.size).toBe(4)})
 it('stops on unknown credit and keeps reservation uncertainty separate from known charges',async()=>{const p=syntheticPipeline((r,q)=>q.family===COUNTER?{...r,headers:{...r.headers,'x-nansen-credits-used':undefined}}:r),r=await p.executor.run();expect(r.stopReason).not.toBe(null);expect(r.newAttempts).toBe(4);expect(r.unresolvedReservedCredits).toBe(5);expect(r.newActualCredits).toBe(3)})
 it('never follows HTTP redirects, retries auth or changes the frozen plan',async()=>{const p=syntheticPipeline(r=>({...r,status:302})),r=await p.executor.run();expect(r.newAttempts).toBe(4);expect(r.newLocalSupportCandidates).toBe(0);expect(r.stopReason).toBe('P1_HTTP_TERMINAL_BREAKER')})
 it('allows admitted retry statuses only, retains logical uniqueness and3attempt bounds',async()=>{const attempts=new Map(),p=syntheticPipeline((r,q)=>{const n=(attempts.get(q.logicalId)??0)+1;attempts.set(q.logicalId,n);return n===1?{...r,status:429,headers:{...r.headers,'x-nansen-credits-used':'0','retry-after':'0'}}:r}),r=await p.executor.run();expect(r.stopReason).toBe(null);expect(r.newAttempts).toBe(20);expect(r.newLocalSupportCandidates).toBe(10);expect(r.newActualCredits).toBe(14);expect(p.state().terminals.size).toBe(10)})
 it('requires all four durable canary terminals and exact normalized identities',async()=>{const p=syntheticPipeline();await p.executor.run();const s=p.state();s.terminals.delete(p.c.plans.plan.canaryLogicalIds[0]);expect(()=>validateCanary(p.c,s,r=>p.store.raw(r))).toThrow()})
 it('rejects repeated execution invocation and reissue',async()=>{const p=syntheticPipeline();await p.executor.run();await expect(p.executor.run()).rejects.toThrow('P1_INVOCATION_REPEATED');await expect(p.executor.issue(Q[0].logicalId)).rejects.toThrow()})
 it('reports complete purpose/coverage/policy/provenance audit with no formal acceptance claim',async()=>{const p=syntheticPipeline();await p.executor.run();const a=requestAudit(p.c,p.state(),r=>p.store.raw(r));expect(a.p1Records).toHaveLength(10);expect(a.p1Records.every(r=>r.localSupportCandidate&&r.leadAccepted===false&&r.attempts[0].providerRequestId)).toBe(true);expect(a.p1PilotReview.newFormalLeadAcceptances).toBe(0)})
 it('requires durable exact sealed START and prevents a second claim before HTTP',()=>{const e={exactLogicalIds:[q.logicalId],hash:'b'.repeat(64),planIdentity:'c'.repeat(64),b4SaturationReceiptIdentity:'d'.repeat(64),canaryLogicalIds:[q.logicalId],retryStatuses:[429]},s={kind:'START',logicalId:q.logicalId,attempt:1,requestBodySha256:identity(q.body),sealedRequestIdentity:identity(q),reservedCredits:1,endpointAdmissionIdentity:q.admissionIdentity,publicProjectionPolicyIdentity:q.publicProjectionPolicyIdentity,issuedAtUtc:'2026-09-17T09:00:00Z',p1ExecutionEnvelopeHash:e.hash,executionContractSha256:CONTRACT_SHA,authorizationId:AUTH,planIdentity:e.planIdentity,b4SaturationReceiptIdentity:e.b4SaturationReceiptIdentity},state={rows:[...Array(39).fill({}),s],terminals:new Map(),responses:new Map()},p={phase:1,inFlight:0,stopped:false,claims:new Set()};expect(claimStart(state,q,e,p)).toBe(q.logicalId+'.1');expect(()=>claimStart(state,q,e,p)).toThrow();expect(()=>claimStart({...state,rows:Array(39).fill({})},q,e,{...p,claims:new Set()})).toThrow()})
 it('honors reserve and concurrency capacity before claims',()=>{const p={phase:1,inFlight:4,stopped:false,claims:new Set()},s={rows:Array(39).fill({}),terminals:new Map(),responses:new Map()};expect(()=>claimStart(s,q,{exactLogicalIds:[q.logicalId]},p)).toThrow()})
})
