import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { beforeAll, afterAll, describe, expect, it, vi } from 'vitest'
import { bindAccepted } from '../../scripts/nq5-b1/authority.mjs'
import { identity, sha } from '../../scripts/nq5/schema.mjs'
import { clarificationAdmission, sourceCertificate, NULL_CLAUSES, TIME_CLAUSES, profiles, verifyCorpus, citedSources, answerBody } from '../../scripts/nq5-b1-r2/contracts.mjs'
import { corpusAt, priorEvidence } from '../../scripts/nq5-b1-r2/gates.mjs'
import { proposalBound, replayTransaction } from '../../scripts/nq5-b1-r2/replay.mjs'
import { correctedPlan, updatedAudit, validateContinuity } from '../../scripts/nq5-b1-r2/plan.mjs'
import { permitted, PAGES, QUESTIONS } from '../../scripts/nq5-b1-r2/fetch-docs.mjs'
import { sanitizeLog, pathScan } from '../../scripts/nq5-b1-r2/privacy.mjs'
import { fallbackSurvey } from '../../scripts/nq5-b1-r2/survey.mjs'

const root=fileURLToPath(new URL('../..',import.meta.url));let bound,docs,profile,original,schema
// Offline historical fixtures only; Date is fixed, not real timers or live gates.
beforeAll(()=>{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-09-17T12:00:00Z'));bound=bindAccepted(JSON.parse(fs.readFileSync(new URL('../fixtures/nq5-b1-accepted-public.json',import.meta.url))));docs=corpusAt(root);profile=profiles(docs.corpus,bound,docs.index);original=JSON.parse(priorEvidence(root)['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json']);schema=JSON.parse(fs.readFileSync(new URL('../../schemas/NANSEN_API_REQUEST_AUDIT.schema.json',import.meta.url)))},30000)
afterAll(()=>vi.useRealTimers())
function admission(kind){
  const clauses=kind==='transactions'?NULL_CLAUSES:TIME_CLAUSES,url='https://docs.nansen.ai'+(kind==='transactions'?PAGES.transactions:PAGES.balances)
  const token={type:'object',required:['token_symbol','token_amount','token_address','chain','from_address','to_address'],properties:{price_usd:{type:['number','null']},value_usd:{anyOf:[{type:'number'},{type:'null'}]}}}
  for(const field of token.required)token.properties[field]={type:field==='token_amount'?'number':'string'}
  const operation={description:clauses.join('\n'),...(kind==='balances'?{'x-temporal-profile':{timezone:'UTC',snapshotIntervalSeconds:3600,timestampLabel:'BUCKET_START',bounds:'CLOSED_INCLUSIVE',earlierBucketAllowed:false,requestBounds:'WHOLE_UTC_HOURS'}}:{})}
  if(kind==='transactions')operation.responses={'200':{content:{'application/json':{schema:{type:'object',properties:{data:{type:'array',items:{type:'object',properties:Object.fromEntries(['tokens_sent','tokens_received'].map(k=>[k,{type:'array',items:{$ref:'#/components/schemas/ProfilerTokenInfo'}}]))}}}}}}}}
  if(kind==='transactions'){const row=operation.responses['200'].content['application/json'].schema.properties.data.items;row.required=['transaction_hash','block_timestamp','chain','source_type','method'];for(const k of row.required)row.properties[k]={type:'string'}}
  const endpoint=kind==='transactions'?'/api/v1/profiler/address/transactions':'/api/v1/profiler/address/historical-balances'
  const endpointSchema={paths:{[endpoint]:{post:operation}},...(kind==='transactions'?{components:{schemas:{ProfilerTokenInfo:token}}}:{})}
  return {kind,answer:clauses.join('\n'),endpointBody:sourceCertificate(kind,endpointSchema),endpointUrl:url,endpointSchema,citations:[url],status:200}
}
const txRequest=()=>bound.plan.requests.find(r=>r.family.endsWith('transactions'))
function rawResponse(){const r=txRequest(),address='0x'+'1'.repeat(40);return {pagination:{page:1,per_page:100,is_last_page:true},data:[{chain:'ethereum',method:'transfer',source_type:'SYNTHETIC',block_timestamp:r.body.date.from,transaction_hash:'0x'+'2'.repeat(64),tokens_sent:[{chain:'ethereum',token_symbol:'SYNTHETIC',token_amount:2,token_address:address,from_address:address,to_address:'0x'+'3'.repeat(40),price_usd:null,value_usd:null,from_address_label:'PRIVATE_LABEL_SENTINEL'}],tokens_received:[]}]}}
const replay=object=>{const raw=Buffer.from(JSON.stringify(object));return replayTransaction(bound,txRequest(),raw,{rawSha256:sha(raw)},profile.transaction)}

describe('R2 bounded documentation provenance and exact clarification admission',()=>{
  it('captures9 primary pages,2 exact questions,2 fallback pages and original unavailable attempts',()=>{expect(docs.index.snapshots).toHaveLength(15);expect(docs.corpus.questionA.httpStatus).toBe(200);expect(docs.corpus.questionB.body).toBe("We couldn't answer this question.");expect(docs.index.snapshots.filter(s=>s.bytes===0)).toHaveLength(2);expect(verifyCorpus(docs.index,docs.bodies)).toEqual(docs.corpus)})
  it.each(['https://api.nansen.ai/api/v1/account','http://docs.nansen.ai/llms.txt','https://docs.nansen.ai@api.nansen.ai/llms.txt','https://docs.nansen.ai/llms.txt?ask=unapproved','https://docs.nansen.ai/api/profiler/address-transactions.md?ask=other','https://docs.nansen.ai:8443/llms.txt','https://docs.nansen.ai/llms.txt#fragment','https://docs.nansen.ai/getting-started/authentication.md'])('rejects unbounded URL %s',url=>{expect(permitted(url)).toBe(false)})
  it('permits exactly the approved question query and rejects duplicate/query additions',()=>{const u='https://docs.nansen.ai'+PAGES.transactions+'?ask='+encodeURIComponent(QUESTIONS.A);expect(permitted(u)).toBe(true);expect(permitted(u+'&goal=other')).toBe(false);expect(permitted(u+'&ask='+encodeURIComponent(QUESTIONS.A))).toBe(false)})
  it.each(['bytes','hash','status','url','timestamp','inventory'])('rejects corrupt corpus %s',kind=>{const i=structuredClone(docs.index),b={...docs.bodies};if(kind==='bytes')b[i.snapshots[0].filename]=Buffer.from('changed');if(kind==='hash')i.snapshots[0].sha256='0'.repeat(64);if(kind==='status')i.snapshots[0].httpStatus=404;if(kind==='url')i.snapshots[0].url='https://api.nansen.ai/api/v1/account';if(kind==='timestamp')i.snapshots[0].retrievedAtUtc='not-a-time';if(kind==='inventory')i.snapshots.pop();expect(()=>verifyCorpus(i,b)).toThrow()})
  it.each(['transactions','balances'])('admits only complete direct sourced consistent synthetic %s clarification',kind=>{expect(clarificationAdmission(admission(kind))).toBe(true)})
  it.each(['noAnswer','noSources','generic','speculative','contradictorySchema','sourceNotSupporting','unavailable','wrongEndpoint','partialTime'])('rejects inference-only/contradictory clarification %s',kind=>{const p=admission(kind==='partialTime'?'balances':'transactions');if(kind==='noAnswer')p.answer='';if(kind==='noSources')p.citations=[];if(kind==='generic')p.answer='Yes it works';if(kind==='speculative')p.answer+=' Probably infer UTC.';if(kind==='contradictorySchema')p.endpointSchema.components.schemas.ProfilerTokenInfo.properties.price_usd={type:'number'};if(kind==='sourceNotSupporting')p.endpointBody='A daily UTC snapshot for Smart Money Historical Holdings';if(kind==='unavailable')p.status=503;if(kind==='wrongEndpoint')p.citations=['https://docs.nansen.ai/api/smart-money/historical-holdings.md'];if(kind==='partialTime')p.endpointBody=TIME_CLAUSES.slice(0,2).join('\n');expect(clarificationAdmission(p)).toBe(false)})
  it('does not let the repeated question in a response heading become an answer',()=>{expect(answerBody('# '+QUESTIONS.A+'\nWe could not answer')).toBe('');expect(citedSources(docs.corpus.questionA.body)).toContain(docs.corpus.transactions.url)})
  it.each(['answerConflict','sourceConflict','negatedClaims','schemaConflict','sourceSchemaMismatch','missingTemporalBinding','changedTemporalBinding','wrongResponseLink','missingCoreProperty'])('rejects reviewed source/schema contradiction %s',kind=>{
    const tx=kind==='wrongResponseLink'||kind==='missingCoreProperty',p=admission(tx?'transactions':'balances')
    if(kind==='answerConflict')p.answer+='\nCorrection: timestamps do not use UTC, but Asia/Singapore; bucket labels end rather than start.'
    if(kind==='sourceConflict')p.endpointBody+='\nCorrection: timestamps do not use UTC, but Asia/Singapore; bucket labels end rather than start.'
    if(kind==='negatedClaims')p.answer='The following claims are false:\n'+p.answer
    const op=p.endpointSchema.paths[p.kind==='transactions'?'/api/v1/profiler/address/transactions':'/api/v1/profiler/address/historical-balances'].post
    if(kind==='schemaConflict'){op.description='Non-UTC daily buckets';p.endpointBody=sourceCertificate(p.kind,p.endpointSchema)}
    if(kind==='sourceSchemaMismatch')p.endpointSchema.extra=true
    if(kind==='missingTemporalBinding'){delete op['x-temporal-profile'];p.endpointBody=sourceCertificate(p.kind,p.endpointSchema)}
    if(kind==='changedTemporalBinding'){op['x-temporal-profile'].timezone='Asia/Singapore';p.endpointBody=sourceCertificate(p.kind,p.endpointSchema)}
    if(kind==='wrongResponseLink'){op.responses['200'].content['application/json'].schema.properties.data.items.properties.tokens_sent.items.$ref='#/components/schemas/Other';p.endpointBody=sourceCertificate(p.kind,p.endpointSchema)}
    if(kind==='missingCoreProperty'){delete p.endpointSchema.components.schemas.ProfilerTokenInfo.properties.token_amount;p.endpointBody=sourceCertificate(p.kind,p.endpointSchema)}
    expect(clarificationAdmission(p)).toBe(false)
  })
  it.each(['outerTypeConflict','allOfConflict','enumConflict','notConstraint','missingTransactionCore','nullableTransactionCore','wrongTransactionType','outerResponseConstraint','extraNullableEnrichment'])('rejects complete-schema/core falsifier %s',kind=>{
    const p=admission('transactions'),token=p.endpointSchema.components.schemas.ProfilerTokenInfo,response=p.endpointSchema.paths['/api/v1/profiler/address/transactions'].post.responses['200'].content['application/json'].schema,row=response.properties.data.items
    if(kind==='outerTypeConflict')token.properties.price_usd={type:'number',anyOf:[{type:'number'},{type:'null'}]}
    if(kind==='allOfConflict')token.properties.price_usd={anyOf:[{type:'number'},{type:'null'}],allOf:[{type:'number'}]}
    if(kind==='enumConflict')token.properties.price_usd={type:['number','null'],enum:[1]}
    if(kind==='notConstraint')token.properties.price_usd={type:['number','null'],not:{type:'null'}}
    if(kind==='missingTransactionCore')row.required=row.required.filter(k=>k!=='transaction_hash')
    if(kind==='nullableTransactionCore')row.properties.block_timestamp={type:['string','null']}
    if(kind==='wrongTransactionType')row.properties.source_type={type:'number'}
    if(kind==='outerResponseConstraint')response.not={type:'object'}
    if(kind==='extraNullableEnrichment')token.properties.extra_usd={type:['number','null']}
    p.endpointBody=sourceCertificate(p.kind,p.endpointSchema);expect(clarificationAdmission(p)).toBe(false)
  })
  it('current official answer/schema remains strict; source-free historical answer stays held',()=>{expect(profile.transaction.disposition).toBe('CURRENT_OPENAPI_STRICT_NO_NULL');expect(profile.transaction.clarificationClassification).toBe('DIRECT_SOURCED_STRICT_NO_NULL');expect(profile.historical.disposition).toBe('HELD_TIMEZONE_OR_BUCKET_AMBIGUOUS');expect(profile.historical.timezone).toBeNull();expect(profile.historical.snapshotIntervalSeconds).toBeNull();expect(profile.transaction.liveReadyContract).toBe(false)})
})
describe('R2 exact offline-only null compatibility, no imputation or leaked restricted values',()=>{
  it('admits only the two optional null enrichment fields through all replay stages, never count/authority',()=>{const result=replay(rawResponse());expect(result.safelyAdmissible).toBe(true);expect(result.nullEnrichmentFieldsObserved).toBe(2);expect(result.admittedResultCount).toBe(1);expect(Object.values(result.stages).every(s=>s.status==='PASS')).toBe(true);expect(result.nullImputedAsZero).toBe(false);expect(result.normalizedEnrichmentFieldsExported).toBe(0);expect(result.labelsExported).toBe(0);expect(result.qualificationAdmissionFromReplay).toBe(false);expect(result.AUTHORIZED_TO_ISSUE).toBe(false);expect(JSON.stringify(result)).not.toContain('PRIVATE_LABEL_SENTINEL')})
  it('does not mutate published schemas, source snapshots or raw bytes',()=>{const before=identity(bound),raw=Buffer.from(JSON.stringify(rawResponse())),copy=Buffer.from(raw);proposalBound(bound,profile.transaction);replayTransaction(bound,txRequest(),raw,{rawSha256:sha(raw)},profile.transaction);expect(identity(bound)).toBe(before);expect(raw.equals(copy)).toBe(true)})
  it.each(['token_symbol','token_amount','token_address','chain','from_address','to_address'])('rejects null core transfer field %s',field=>{const o=rawResponse();o.data[0].tokens_sent[0][field]=null;expect(replay(o).safelyAdmissible).toBe(false)})
  it.each(['transaction_hash','block_timestamp','chain','source_type','method'])('rejects null transaction core field %s',field=>{const o=rawResponse();o.data[0][field]=null;expect(replay(o).safelyAdmissible).toBe(false)})
  it.each(['missingCore','extraNull','unknownUnsafe','wrongTokenChain','page2','naiveTime','postCutoff','emptyTransfers'])('rejects incompatible response %s',kind=>{const o=rawResponse();if(kind==='missingCore')delete o.data[0].tokens_sent[0].token_amount;if(kind==='extraNull')o.data[0].volume_usd=null;if(kind==='unknownUnsafe')o.data[0].tokens_sent[0].private_sentinel='PRIVATE_VALUE';if(kind==='wrongTokenChain')o.data[0].tokens_sent[0].chain='solana';if(kind==='page2')o.pagination.page=2;if(kind==='naiveTime')o.data[0].block_timestamp='2023-03-13T11:00:00';if(kind==='postCutoff')o.data[0].block_timestamp='2023-03-13T12:16:00Z';if(kind==='emptyTransfers')o.data[0].tokens_sent=[];const result=replay(o);expect(result.safelyAdmissible).toBe(false);expect(JSON.stringify(result)).not.toContain('PRIVATE_VALUE');expect(result.qualificationAdmissionFromReplay).toBe(false)})
  it.each(['zeroImputation','extraNullable','wrongField','schemaDrift','authority'])('rejects widened profile %s',kind=>{const p=structuredClone(profile.transaction);if(kind==='zeroImputation')p.proposal.imputation=true;if(kind==='extraNullable')p.proposal.extraNullableFields=true;if(kind==='wrongField')p.affectedFields.push('token_amount');if(kind==='schemaDrift')p.responseSchemaIdentity='0'.repeat(64);if(kind==='authority')p.AUTHORIZED_TO_ISSUE=true;delete p.hash;p.hash=identity(p);expect(()=>proposalBound(bound,p)).toThrow()})
})
describe('R2 deterministic zero-ready plan, audit continuity and fallback holds',()=>{
  it('preserves all15 exact rows and their state;9 unissued historical plus4 transactions held',()=>{const plans=correctedPlan(bound,profile);expect(plans.plan.rows).toHaveLength(15);expect(plans.plan.rows.map(r=>r.originalRow)).toEqual(bound.plan.requests);expect(plans.plan.rows.slice(0,2).every(r=>r.classification==='ISSUED_TERMINAL_NONCOUNTED')).toBe(true);expect(plans.plan.rows.filter(r=>r.heldDisposition==='HELD_UNISSUED_PENDING_OFFICIAL_TEMPORAL_SEMANTICS')).toHaveLength(9);expect(plans.plan.rows.filter(r=>r.heldDisposition==='HELD_UNISSUED_CURRENT_OPENAPI_STRICT_NO_NULL')).toHaveLength(4);expect(plans.plan.requests).toEqual([]);expect(plans.supersession.replacements).toEqual([]);expect(plans.plan.AUTHORIZED_TO_ISSUE).toBe(false);expect(correctedPlan(bound,profile)).toEqual(plans)})
  it('does not turn hypothetical caller admission into a live-ready request',()=>{const p=structuredClone(profile);p.historical.liveReadyContract=true;p.historical.disposition='OFFICIALLY_CLARIFIED_ADMITTED';expect(()=>correctedPlan(bound,p)).toThrow()})
  it('protects250 reserve from627478 anchor with zero future credits',()=>{const {reserve}=correctedPlan(bound,profile);expect(reserve.additionalWorstCaseCredits).toBe(0);expect(reserve.remainingAfterWorstCase).toBe(627478);expect(reserve.reserveHeadroomAfterWorstCase).toBe(627228);expect(reserve.maximumCumulativeCampaignCredits).toBe(2);expect(reserve.unattributedAccountWideChange).toBe(2547);expect(reserve.AUTHORIZED_TO_ISSUE).toBe(false)})
  it('schema-valid audit adds source/lineage only and preserves every original field/attempt',()=>{const plans=correctedPlan(bound,profile),audit=updatedAudit(original,plans,profile);expect(validateContinuity(audit,original,plans,profile,schema)).toBe(true);for(const r of audit.records){const {r2ContractReview,...rest}=r;expect(rest).toEqual(original.records.find(o=>o.logicalId===r.logicalId));expect(r2ContractReview.AUTHORIZED_TO_ISSUE).toBe(false)}expect(audit.records.flatMap(r=>r.attempts)).toHaveLength(2);expect(audit.records.filter(r=>r.issued).every(r=>r.attempts[0].provider_request_id===null&&r.attempts[0].providerRequestIdDisposition==='NOT_CAPTURED_BY_B1_TRANSPORT_V1')).toBe(true)})
  it.each(['newAttempt','newTimestamp','newRequestId','newCredit','count','newPublicId','rawHash','contractDisposition','planLineage'])('rejects fabricated audit %s',kind=>{const plans=correctedPlan(bound,profile),a=updatedAudit(original,plans,profile),old=a.records.find(r=>r.issued);if(kind==='newAttempt')a.records.find(r=>!r.issued).attempts.push(structuredClone(old.attempts[0]));if(kind==='newTimestamp')old.attempts[0].completedAtUtc='2026-09-17T01:00:00Z';if(kind==='newRequestId')old.attempts[0].provider_request_id='invented';if(kind==='newCredit')old.attempts[0].actualCredits=0;if(kind==='count')old.qualificationCounted=true;if(kind==='newPublicId')old.publicCallId='NQ5-000001';if(kind==='rawHash')old.attempts[0].primarySha256='0'.repeat(64);if(kind==='contractDisposition')old.r2ContractReview.profileDisposition='OFFICIALLY_CLARIFIED_ADMITTED';if(kind==='planLineage')old.r2ContractReview.lineageOriginalLogicalId='0'.repeat(64);expect(()=>validateContinuity(a,original,plans,profile,schema)).toThrow()})
  it('both fallback beta families retain exact schemas and remain unadmitted/no public index',()=>{const s=fallbackSurvey(docs.corpus);expect(s.families).toHaveLength(2);for(const f of s.families){expect(f.stability).toBe('BETA_SUBJECT_TO_BREAKING_CHANGES');expect(f.admitted).toBe(false);expect(f.AUTHORIZED_TO_ISSUE).toBe(false);expect(f.requestSchema.properties.as_of_date.format).toBe('date');expect(f.redistribution.status).toContain('HELD');expect(f.chainCoverage.proseSchemaDiscrepancy).toBe(true)}expect(s.families[1].pagination.documentedResultCap).toBe(20);expect(s.families[1].privacy.labelsPresent).toBe(true)})
})
describe('R2 supplier-log absolute path privacy without altering governed source',()=>{
  it('preserves exact official Markdown/JSON line-break escapes rather than misreading word suffixes as drives',()=>{for(const name of ['balances','backtestingTransactions'])expect(pathScan({['OFFICIAL_DOCS/'+name+'.md']:docs.corpus[name].body}).status).toBe('PASS');expect(pathScan({'OFFICIAL_DOCS/example.md':'What it helps to answer:\\\nDifferences:\\n- Fact'}).status).toBe('PASS')})
  it('still detects actual Windows absolute drives after word-boundary correction',()=>{for(const p of ['C:\\Users\\Synthetic\\file','X:\\private\\data','path="D:\\tmp\\file"']){expect(pathScan({'VERIFICATION/example.log':p}).status).toBe('FAIL');expect(pathScan({'VERIFICATION/example.log':sanitizeLog(p,'/home/synthetic/project').text}).status).toBe('PASS')}})
  it('redacts executor, home, private/temp and Windows paths with stable placeholders',()=>{const text='/home/synthetic/project/file\nfile:///home/synthetic/private/key\n/tmp/synthetic-x/log\n/var/tmp/synthetic/file\nC:\\Users\\Synthetic\\file',s=sanitizeLog(text,'/home/synthetic/project');expect(s.text).toContain('<WORKSPACE>/file');expect(s.text).toContain('<TEMP_ROOT>');expect(pathScan({'VERIFICATION/synthetic.log':s.text}).status).toBe('PASS');expect(s.sourceSha256).not.toBe(s.sanitizedSha256)})
  it('rejects unsanitized logs, excludes Git/source literals only and preserves provider documentation paths',()=>{expect(pathScan({'VERIFICATION/log.log':'/home/synthetic/project'}).status).toBe('FAIL');const x=pathScan({'SOURCE_DIFF.patch':'+const x="/home/synthetic/source"','VERIFICATION/log.log':'POST /api/v1/profiler/address/transactions https://docs.nansen.ai/api/data-coverage.md'});expect(x.status).toBe('PASS');expect(x.governedSourceLiteralsChanged).toBe(false)})
})
