import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { buildFrozenFixture, syntheticFixture } from '../../src/investigation/fixture'
import { CANONICAL_SECTIONS } from '../../src/investigation/contracts'
import { createInvestigationState, investigationReducer } from '../../src/investigation/state'
import { compileRuntimeCatalogs } from '../../src/investigation/catalog'
import { validateActiveSchema, validateSourceInstallation } from '../../scripts/nq5-r2/authority.mjs'
import { proveUnchangedObservationCode, verifyLocalObservation } from '../../scripts/nq5-r2/observation.mjs'
import { ACCOUNT_ID } from '../../scripts/nq5/account.mjs'
import { seedQuestions, freezeNextBatch, freezeAcceptedT1, durableObservation, expandFrontier, LENS_FAMILIES } from '../../scripts/nq5-r2/frontier.mjs'
import { identity } from '../../scripts/nq5/schema.mjs'
import { logicalRequest } from '../../scripts/nq5/planner.mjs'
import { persistRaw, durable } from '../../scripts/nq5/journal.mjs'
import { readCampaignEvidence } from '../../scripts/nq5-r2/campaign-evidence.mjs'
import { accountReport, ledgerRecord } from '../fixtures/nq5-offline.mjs'

const base = 'public/scenarios/euler-2023-false-exit/', fixture = buildFrozenFixture(JSON.parse(fs.readFileSync(base + 'scenario.json')), JSON.parse(fs.readFileSync(base + 'evidence-graph.json')))
const refresh = JSON.parse(fs.readFileSync('docs/nq5/R1_OFFICIAL_SOURCE_REFRESH.json')), directories = []
beforeEach(() => { vi.useFakeTimers(); vi.setSystemTime(new Date(Date.parse(refresh.snapshots[0].retrievedAtUtc) + 1000)) })
afterEach(() => { vi.useRealTimers(); for (const directory of directories.splice(0)) fs.rmSync(directory, { recursive: true, force: true }) })
const emptyHistory = () => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'trace-r2-empty-synthetic-')); directories.push(directory); const file = path.join(directory, 'campaign.jsonl'); durable(file, Buffer.alloc(0), 'wx'); return readCampaignEvidence(file) }
const initial = () => freezeAcceptedT1(refresh, accountReport(630027), fixture, emptyHistory())
function storedResult({ last = false, empty = false, size = 1 } = {}) {
  const frozen = initial(), row = frozen.plan.requests.find(item => item.lens === 'ACTIVITY'), contract = frozen.plan.contracts.find(item => item.hash === row.contractHash)
  const address = n => '0x' + n.toString(16).padStart(40, '0')
  const data = empty ? [] : Array.from({ length: size }, (_, n) => ({ chain: 'ethereum', method: 'sent', block_timestamp: '2023-03-13T11:38:11Z', transaction_hash: '0x' + (1000 + n).toString(16).padStart(64, '0'), source_type: 'transfer', tokens_sent: [{ token_symbol: 'TEST', token_amount: 10, token_address: address(100), chain: 'ethereum', from_address: address(10000 + n * 2), to_address: address(10001 + n * 2) }] }))
  const pageData = data.length > 100 ? [{ ...data[0], tokens_sent: data.flatMap(item => item.tokens_sent) }] : data
  const bytes = Buffer.from(JSON.stringify({ pagination: { page: 1, per_page: 100, is_last_page: last }, data: pageData }))
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'trace-r2-synthetic-')); directories.push(directory)
  const terminal = { ...ledgerRecord(row.logicalId, persistRaw(path.join(directory, 'primary'), path.join(directory, 'mirror'), row.logicalId, bytes)), endpoint_family: row.family, endpoint_path: row.path, request_body_sha256: identity(row.body), purpose_code: row.purpose, investigative_question_id: row.questionId, question_lens: row.lens, consumer_ids: row.consumers, selection_lineage: row.lineage, coverage_key: row.coverageKey, coverage_cell_ids: row.coverageCells }
  terminal.classification.result_count = data.length; terminal.classification.coverage_supports_negative_evidence = empty
  const [fromUtc, toUtc] = row.coverageKey.time_window_id.split('/'), cell = { id: row.coverageCells[0], fromUtc, toUtc, status: empty ? 'EMPTY_COMPLETE' : 'COMPLETE', supportsNegative: empty }
  const journalFile = path.join(directory, 'campaign.jsonl')
  durable(journalFile, JSON.stringify({ event: 'START', sequence: 1, record: { logicalId: row.logicalId, attemptId: terminal.attempt_id } }) + '\n' + JSON.stringify({ event: 'TERMINAL', sequence: 2, record: terminal }) + '\n', 'wx')
  const history = readCampaignEvidence(journalFile)
  return { directory, journalFile, history, frozen, row, contract, terminal, cell, observation: durableObservation(row, terminal, contract, cell, fixture.cutoffUtc, history) }
}
const reviewFor = (observation, gaps) => ({ saturated: false, duplicateRatio: 0, closedQuestionIds: [], closedCoverageCellIds: [], gaps: gaps ?? [{ kind: 'WINDOW_COMPLETENESS', questionId: observation.row.questionId, parentTerminalIdentity: observation.terminalIdentity, unresolved: true, consumerId: 'TEST.T1.NAMED_COVERAGE', marginalUtility: 'Resolve the named still-open incident-window continuation gap.' }] })

describe('R2 exact source and canonical taxonomy — aliases cannot pass', () => {
  it('admits complete43-file v1.7.0/v1.7.1 exact source precedence, schema2.0.2 and held authority', () => { const report = validateSourceInstallation(); expect(report.exactGovernedFiles).toBe(43); expect(report.canonicalSections).toEqual(CANONICAL_SECTIONS); expect(report.networkHeld).toBe(true) })
  it.each(['ASK', 'ARCHIVE', 'EXPLORE_AS_ASK', 'LEDGER_AS_ARCHIVE'])('rejects reducer section alias:%s', section => { const state = investigationReducer(fixture, createInvestigationState(fixture), { type: 'EARN_ACCESS' }), next = investigationReducer(fixture, state, { type: 'SECTION', section }); expect(next.section).toBe('CASE'); expect(next.error).toContain('Noncanonical') })
  it('blocks cumulative prior attempt ceiling from reconciled durable noncounted terminals', () => {
    const saved = storedResult(), source = { ...saved.terminal, terminal_status: 'SUCCESS_NOT_COUNTED', qualification_counted: false, qualification_sequence: null, qualification_exclusion_reason: 'SYNTHETIC_ATTEMPT_CEILING_CONTROL', budget: { projected_credits: 0, actual_credits: 0, cumulative_actual_credit_delta: 0 }, storage: { primary_raw_sha256: null, mirror_raw_sha256: null, primary_path: null, mirror_path: null, bytes_equal: null } }
    let sequence = 0, text = ''
    for (let n = 0; n < 5001; n++) { const logicalId = n.toString(16).padStart(64, '0'), record = { ...source, logical_request_id: logicalId, ledger_sequence: sequence + 2 }; text += JSON.stringify({ event: 'START', sequence: ++sequence, record: { logicalId, attemptId: record.attempt_id } }) + '\n' + JSON.stringify({ event: 'TERMINAL', sequence: ++sequence, record }) + '\n' }
    fs.writeFileSync(saved.journalFile, text)
    const history = readCampaignEvidence(saved.journalFile), seed = seedQuestions(fixture).find(row => row.lens === 'ACTIVITY')
    expect(history.maximumPriorAttempts).toBe(15003); expect(history.counted).toBe(0)
    expect(() => freezeNextBatch([seed], saved.frozen.plan.contracts, accountReport(630027), history.logicalIds, 256, history)).toThrow(/ceiling/)
  }, 30000)
  it.each([['CASE', 'ASK', 'RESULTS', 'SOURCE', 'ARCHIVE'], ['CASE', 'EXPLORE', 'RESULTS', 'SOURCE', 'LEDGER'], ['CASE', 'RESULTS', 'EXPLORE', 'SOURCE', 'ARCHIVE']])('rejects old or reordered catalog sections:%s', (...sections) => { const terminal = compileRuntimeCatalogs(fixture, createInvestigationState(fixture)).terminal; terminal.sections = sections; expect(() => validateActiveSchema('terminal', terminal)).toThrow() })
  it.each(['ask_location', 'explore_role', 'ledger_role', 'archive_is_canonical_section'])('rejects false semantic relabeling:%s', key => { const terminal = compileRuntimeCatalogs(fixture, createInvestigationState(fixture)).terminal; terminal.section_semantics[key] = key === 'archive_is_canonical_section' ? true : 'ALIAS'; expect(() => validateActiveSchema('terminal', terminal)).toThrow() })
  it('keeps ASK workflow inside CASE and all five real state values', () => { let state = investigationReducer(fixture, createInvestigationState(fixture), { type: 'EARN_ACCESS' }); state = investigationReducer(fixture, state, { type: 'ASK_QUESTION' }); expect(state.section).toBe('CASE'); expect(state.askOpen).toBe(true); for (const section of CANONICAL_SECTIONS.filter(item => item !== 'SOURCE')) { state = investigationReducer(fixture, state, { type: 'SECTION', section }); expect(state.section).toBe(section) } })
})
describe('R2 utility-bound immutable next batch and deterministic durable frontier', () => {
  it('uses exact receipt/relationship/state families; only immediately justified page1 questions and no reserve', () => { const seeds = seedQuestions(fixture), frozen = initial(); expect(seeds.every(row => row.family === LENS_FAMILIES[row.lens] && row.partition.page === 1)).toBe(true); expect(seeds.filter(row => row.lens === 'RECEIPT').every(row => row.purpose === 'EXACT_RECEIPT' && !row.body.pagination)).toBe(true); expect(frozen.plan.requests.length).toBeLessThanOrEqual(256); expect(frozen.reserve.requests).toEqual([]); expect(frozen.completeTargetPlan).toBe(false); expect(frozen.report.blockedFamilies).toHaveLength(2); expect(frozen.plan.qualificationCallsAllowed).toBe(false) })
  it('rejects forged page2/serialized proof markers, count-shaped256/1024 padding, retries/local reuse and equivalent duplicates', () => { const frozen = initial(), seed = seedQuestions(fixture).find(row => row.lens === 'ACTIVITY'), forged = structuredClone(seed), history = emptyHistory(); forged.body.pagination.page = 2; forged.partition.page = 2; forged.frontierProof = { kind: 'DURABLE_NEXT_PAGE', explicitMore: true }; for (const requests of [[forged], [structuredClone(seed)], [seed, seed], Array(257).fill(seed), Array(1024).fill(seed)]) expect(() => freezeNextBatch(requests, frozen.plan.contracts, accountReport(630027), [], 256, history)).toThrow(); expect(() => freezeNextBatch([seed], frozen.plan.contracts, accountReport(630027), [logicalRequest(seed)], 256, history)).toThrow(); expect(() => freezeNextBatch([seed], frozen.plan.contracts, accountReport(250), [], 256, history)).toThrow() })
  it('never resets prior accounting by omitting history/IDs; missing initial snapshot stays unfrozen', () => { const saved = storedResult(), seed = seedQuestions(fixture).find(row => row.lens === 'ACTIVITY'); expect(() => freezeNextBatch([seed], saved.frozen.plan.contracts, accountReport(630027))).toThrow(/evidence/); expect(() => freezeNextBatch([seed], saved.frozen.plan.contracts, accountReport(630027), [], 256, saved.history)).toThrow(); const blocked = freezeAcceptedT1(refresh, accountReport(630027), fixture); expect(blocked.plan.frozen).toBe(false); expect(blocked.report.frozenNextBatchRequests).toBe(0); expect(blocked.report.noImplicitEmptyHistoryAssumption).toBe(true) })
  it('rejects synthetic or mutated accepted seed provenance', () => { expect(() => seedQuestions(syntheticFixture(fixture))).toThrow(); const fake = structuredClone(fixture); fake.records[0].source = '0x' + '9'.repeat(40); expect(() => seedQuestions(fake)).toThrow() })
  it('admits page2 only from dual durable counted page1, explicit-more and named unresolved utility', () => { const { observation, frozen, history } = storedResult(), next = expandFrontier(fixture, [observation], reviewFor(observation), frozen.plan.contracts); expect(next).toHaveLength(1); expect(next[0].partition.page).toBe(2); expect(next[0].frontierProof.parentTerminalIdentity).toBe(observation.terminalIdentity); expect(freezeNextBatch(next, frozen.plan.contracts, accountReport(630027), history.logicalIds, 256, history).plan.requests).toHaveLength(1); expect(() => expandFrontier(fixture, [structuredClone(observation)], reviewFor(observation), frozen.plan.contracts)).toThrow() })
  it.each([{ last: true }, { empty: true }])('stops durable last or empty page:%j', options => { const { observation, frozen } = storedResult(options); expect(expandFrontier(fixture, [observation], reviewFor(observation), frozen.plan.contracts)).toEqual([]) })
  it.each(['saturated', 'closed-question', 'closed-cell', 'no-utility', 'duplicate', 'high-duplicate'])('stops below floor:%s', stop => { const { observation, frozen } = storedResult(), review = reviewFor(observation); let prior = []; if (stop === 'saturated') review.saturated = true; if (stop === 'closed-question') review.closedQuestionIds = [observation.row.questionId]; if (stop === 'closed-cell') review.closedCoverageCellIds = observation.row.coverageCells; if (stop === 'no-utility') review.gaps[0].marginalUtility = ''; if (stop === 'high-duplicate') review.duplicateRatio = .81; if (stop === 'duplicate') prior = expandFrontier(fixture, [observation], review, frozen.plan.contracts).map(logicalRequest); expect(expandFrontier(fixture, [observation], review, frozen.plan.contracts, prior)).toEqual([]) })
  it.each(['body', 'lens', 'lineage', 'coverage', 'bytes'])('rejects terminal/raw mismatch:%s', mutation => { const saved = storedResult(); if (mutation === 'body') saved.terminal.request_body_sha256 = 'a'.repeat(64); if (mutation === 'lens') saved.terminal.question_lens = 'RECEIPT'; if (mutation === 'lineage') saved.terminal.selection_lineage = ['UNACCEPTED']; if (mutation === 'coverage') saved.cell.toUtc = '2023-03-13T13:00:00Z'; if (mutation === 'bytes') fs.appendFileSync(saved.terminal.storage.mirror_path, ' '); expect(() => durableObservation(saved.row, saved.terminal, saved.contract, saved.cell, fixture.cutoffUtc, saved.history)).toThrow() })
  it('demonstrates conditional1024 floor route in four bounded batches from observed gaps and reconciled synthetic terminals, not guessed pages or historical successes', () => {
    const saved = storedResult({ size: 512, last: true }), { frozen } = saved
    const gaps = saved.observation.facts.map(fact => ({ kind: 'SUBJECT_ACTIVITY', questionId: 'QUESTION.FACT.' + identity(fact), parentTerminalIdentity: saved.observation.terminalIdentity, normalizedFactIdentity: identity(fact), unresolved: true, consumerId: 'TEST.T1.OBSERVED_THREAD', marginalUtility: 'Test bounded incident activity for this observed exact transfer participant.' }))
    let history = saved.history, observation = saved.observation
    for (let batch = 0; batch < 4; batch++) {
      const remaining = 1024 - history.counted, next = expandFrontier(fixture, [observation], reviewFor(observation, gaps), frozen.plan.contracts, history.logicalIds).slice(0, Math.min(256, remaining))
      expect(next).toHaveLength(batch === 3 ? 255 : 256)
      const admitted = freezeNextBatch(next, frozen.plan.contracts, accountReport(630027), history.logicalIds, 256, history)
      expect(next.every(row => row.partition.page === 1 && row.frontierProof.kind === 'DURABLE_RESULT')).toBe(true)
      let sequence = history.logicalIds.length * 2, count = history.counted, cost = history.actualCredits, journalText = ''
      for (const row of admitted.plan.requests) {
        const bytes = Buffer.from(JSON.stringify({ pagination: { page: 1, per_page: 100, is_last_page: true }, data: [{ chain: 'ethereum', method: 'sent', source_type: 'transfer', block_timestamp: '2023-03-13T11:38:11Z', transaction_hash: '0x' + '7'.repeat(64), tokens_sent: [{ token_amount: 10, token_symbol: 'TEST', chain: 'ethereum', token_address: '0x' + '8'.repeat(40), from_address: row.body.address, to_address: '0x' + '9'.repeat(40) }] }] }))
        const storage = persistRaw(path.join(saved.directory, 'primary'), path.join(saved.directory, 'mirror'), row.logicalId, bytes), record = { ...ledgerRecord(row.logicalId, storage), ledger_sequence: sequence + 2, qualification_sequence: ++count, purpose_code: row.purpose, request_body_sha256: identity(row.body), investigative_question_id: row.questionId, consumer_ids: row.consumers, selection_lineage: row.lineage, coverage_key: row.coverageKey, coverage_cell_ids: row.coverageCells, budget: { projected_credits: 1, actual_credits: 1, cumulative_actual_credit_delta: ++cost } }
        journalText += JSON.stringify({ event: 'START', sequence: ++sequence, record: { logicalId: row.logicalId, attemptId: record.attempt_id } }) + '\n' + JSON.stringify({ event: 'TERMINAL', sequence: ++sequence, record }) + '\n'
      }
      durable(saved.journalFile, journalText, 'a'); history = readCampaignEvidence(saved.journalFile)
      observation = durableObservation(saved.row, saved.terminal, saved.contract, saved.cell, fixture.cutoffUtc, history)
    }
    expect(history.counted).toBe(1024); expect(new Set(history.logicalIds).size).toBe(history.logicalIds.length)
    const extra = expandFrontier(fixture, [observation], reviewFor(observation, gaps), frozen.plan.contracts, history.logicalIds)
    expect(extra).toHaveLength(1); expect(() => freezeNextBatch(extra, frozen.plan.contracts, accountReport(630027), history.logicalIds, 256, history)).toThrow(/ceiling/)
    expect(frozen.report.actualCountedSuccesses).toBe(0)
  }, 60000)
  it('rejects undurable/partial/mismatched journal terminals and stale proofs without repairing bytes', () => { const saved = storedResult(); expect(() => durableObservation(saved.row, saved.terminal, saved.contract, saved.cell, fixture.cutoffUtc)).toThrow(); expect(() => durableObservation(saved.row, saved.terminal, saved.contract, saved.cell, fixture.cutoffUtc, structuredClone(saved.history))).toThrow(); fs.appendFileSync(saved.journalFile, '{'); const before = fs.readFileSync(saved.journalFile); expect(() => readCampaignEvidence(saved.journalFile)).toThrow(); expect(() => expandFrontier(fixture, [saved.observation], reviewFor(saved.observation), saved.frozen.plan.contracts)).toThrow(); expect(fs.readFileSync(saved.journalFile)).toEqual(before) })
  it('blocks unknown spending, unmatched history, forged accounting, exhausted attempts and prior spend before new freeze', () => { const saved = storedResult(), seed = seedQuestions(fixture).find(row => row.lens === 'ACTIVITY' && logicalRequest(row) !== saved.row.logicalId); expect(() => freezeNextBatch([seed], saved.frozen.plan.contracts, accountReport(630027), Array.from({ length: 12288 }, (_, n) => n.toString(16).padStart(64, '0')))).toThrow(); expect(() => freezeNextBatch([seed], saved.frozen.plan.contracts, accountReport(630027), saved.history.logicalIds, 256, structuredClone(saved.history))).toThrow(); expect(() => freezeNextBatch([seed], saved.frozen.plan.contracts, accountReport(253), saved.history.logicalIds, 256, saved.history)).toThrow(/ceiling/); const rows = fs.readFileSync(saved.journalFile, 'utf8').trim().split('\n').map(JSON.parse); rows[1].record.budget.actual_credits = null; fs.writeFileSync(saved.journalFile, rows.map(row => JSON.stringify(row)).join('\n') + '\n'); expect(() => readCampaignEvidence(saved.journalFile)).toThrow(); rows[1].record.budget.actual_credits = 15000; rows[1].record.budget.cumulative_actual_credit_delta = 15000; fs.writeFileSync(saved.journalFile, rows.map(row => JSON.stringify(row)).join('\n') + '\n'); const spent = readCampaignEvidence(saved.journalFile); expect(() => freezeNextBatch([seed], saved.frozen.plan.contracts, accountReport(630027), spent.logicalIds, 256, spent)).toThrow(/ceiling/) })
})
describe('R2 consumed historical observation reuse proof fails closed without adapters or credentials', () => {
  it('revalidates synthetic original report/terminal/dual bytes without adapter/resolver/mutation and rejects report drift', () => {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'trace-r2-reuse-control-')); directories.push(directory)
    const bytes = Buffer.from('{"available_credits":630027,"plan":"pro","credits_cost":0}'), storage = persistRaw(path.join(directory, 'primary'), path.join(directory, 'mirror'), ACCOUNT_ID, bytes), report = accountReport(630027)
    report.account.plan_class = 'PRO'; report.response.credits_used = null; report.response.credits_remaining_header = null
    report.storage.primary_raw_sha256 = storage.primary_raw_sha256; report.storage.mirror_raw_sha256 = storage.mirror_raw_sha256
    const terminal = { ...ledgerRecord(ACCOUNT_ID, storage), tranche_id: 'ACCOUNT_BOOTSTRAP', batch_id: 'ADMIN', attempt_id: 'ACCOUNT-ONE-ATTEMPT', endpoint_family: 'account', endpoint_path: '/api/v1/account', purpose_code: 'ACCOUNT_PREFLIGHT', consumer_ids: ['PRECALL_AUTHORIZATION'], selection_lineage: ['LEAD-NQ5-ACCOUNT-PREFLIGHT-BOOTSTRAP-001'], request_body_sha256: identity(null), issued_at_utc: report.generated_at_utc, terminal_status: 'SUCCESS_NOT_COUNTED', qualification_counted: false, qualification_sequence: null, provider_headers: { credits_cost: 0, credits_used: null, credits_remaining: null }, classification: { temporal_class: 'ADMIN', public_export_disposition: 'PRIVATE_ONLY', route_disposition: 'ADMIN_NONQUALIFICATION', evidence_grade: 'NONE', result_count: 0 }, budget: { projected_credits: 0, actual_credits: 0, cumulative_actual_credit_delta: 0 }, investigative_question_id: null, question_lens: 'ADMIN', coverage_cell_ids: [], caseboard_consumer_ids: [] }
    delete terminal.coverage_key
    const journalBytes = Buffer.from(JSON.stringify({ event: 'START', sequence: 1, record: { logicalId: ACCOUNT_ID, attemptId: terminal.attempt_id } }) + '\n' + JSON.stringify({ event: 'TERMINAL', sequence: 2, record: terminal }) + '\n'), reportBytes = Buffer.from(JSON.stringify(report)), proof = proveUnchangedObservationCode(process.cwd())
    const result = verifyLocalObservation(reportBytes, journalBytes, proof)
    expect(result.receipt.status).toBe('PASS_LOCAL_REVALIDATION_ONLY'); expect(result.receipt.additionalAttempts).toBe(0); expect(result.receipt.accountAdapterInvoked).toBe(false); expect(result.receipt.credentialResolutionInGate).toBe(false); expect(result.receipt.bytesEqual).toBe(true)
    expect(fs.readFileSync(storage.primary_path)).toEqual(bytes); expect(fs.readFileSync(storage.mirror_path)).toEqual(bytes)
    report.account.available_credits--
    expect(() => verifyLocalObservation(Buffer.from(JSON.stringify(report)), journalBytes, proof)).toThrow()
  })
  it('proves actual relevant code unchanged from R1 without accessing any private account file', () => { const proof = proveUnchangedObservationCode(process.cwd()); expect(proof.status).toBe('PASS'); expect(proof.evidence.every(row => row.originalSha256 === row.currentSha256)).toBe(true) })
  it('rejects missing code proof, incomplete journal and second-attempt envelopes before raw read', () => { const proof = proveUnchangedObservationCode(process.cwd()); expect(() => verifyLocalObservation(Buffer.from('{}'), Buffer.from(''), proof)).toThrow(); expect(() => verifyLocalObservation(Buffer.from('{}'), Buffer.from('{}\n{}\n{}\n'), proof)).toThrow(); expect(() => verifyLocalObservation(Buffer.from('{}'), Buffer.from('{}\n'), { status: 'FAIL' })).toThrow() })
})
