import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { beforeAll, afterAll, afterEach, describe, it, expect, vi } from 'vitest'
import { bindAccepted } from '../../scripts/nq5-b1/authority.mjs'
import { BatchStore, replay } from '../../scripts/nq5-b1/store.mjs'
import { RateGate, Dispatcher } from '../../scripts/nq5-b1/dispatcher.mjs'
import { diagnose, diagnoseDurable, structuralSchema } from '../../scripts/nq5-b1-r1/diagnostic.mjs'
import { captureSafeHeaders } from '../../scripts/nq5-b1-r1/headers.mjs'
import { verifyPreservedState, CONSUMED, LEDGER_SHA } from '../../scripts/nq5-b1-r1/checkpoint.mjs'
import { requestAudit, validateAudit, balanceReconciliation, resumeEnvelope, utilityBuckets } from '../../scripts/nq5-b1-r1/audit.mjs'
import { assertResumeAdmission, assertRemainingIssue } from '../../scripts/nq5-b1-r1/resume-guard.mjs'
import { reconcile } from '../../scripts/nq5-b1/reconcile.mjs'
import { identity, sha } from '../../scripts/nq5/schema.mjs'

const root=fileURLToPath(new URL('../..',import.meta.url)),directories=[]
let bound
// Offline historical fixtures only; production freshness is not relaxed.
beforeAll(()=>{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-09-17T12:00:00Z'));bound=bindAccepted(JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/nq5-b1-accepted-public.json'))))},30000)
afterAll(()=>vi.useRealTimers())
afterEach(()=>{for(const dir of directories.splice(0))fs.rmSync(dir,{recursive:true,force:true})})
const observed=(remaining='627478')=>({'x-ratelimit-remaining-second':'149','x-ratelimit-remaining-minute':'2999','ratelimit-limit':'150','ratelimit-remaining':'149','ratelimit-reset':'1','x-ratelimit-limit-second':'150','x-ratelimit-limit-minute':'3000','x-ratelimit-remaining-credit-fails':'10','x-nansen-credits-cost':'1','x-nansen-credits-used':'1','x-nansen-credits-remaining':remaining,'x-ratelimit-limit':'75','x-ratelimit-remaining':'74','x-ratelimit-reset':'1','x-ratelimit-remaining-credit-fails-minute':'10','x-ratelimit-limit-credit-fails-minute':'10'})
const request=family=>bound.plan.requests.find(r=>r.family.endsWith(family))
function response(r,{timestamp=r.body.date.from,nullPrice=false,emptyTransfers=false,amount=2}={}){
  const address='0x'+'1'.repeat(40)
  const record=r.family.endsWith('balances')?{chain:'ethereum',block_timestamp:timestamp,token_symbol:'SYNTHETIC',token_address:address,token_amount:amount}:{chain:'ethereum',method:'transfer',source_type:'SYNTHETIC',block_timestamp:timestamp,transaction_hash:'0x'+'2'.repeat(64),tokens_sent:emptyTransfers?[]:[{chain:'ethereum',token_symbol:'SYNTHETIC',token_amount:amount,token_address:address,from_address:address,to_address:'0x'+'3'.repeat(40),from_address_label:'PRIVATE_SYNTHETIC_LABEL',...(nullPrice?{price_usd:null,value_usd:null}:{})}],tokens_received:[]}
  return Buffer.from(JSON.stringify({pagination:{page:1,per_page:100,is_last_page:true},data:[record]}))
}
function synthetic(){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'trace-b1-r1-synthetic-'));directories.push(dir)
  const roots=['primary','mirror'].map(n=>{const p=path.join(dir,n);fs.mkdirSync(p,{mode:0o700});for(const [n,v]of [['genesis.json','synthetic genesis'],['GENESIS_COMMIT.json','synthetic commit'],['qualification.jsonl','']])fs.writeFileSync(path.join(p,n),v,{mode:0o600});return p})
  const store=new BatchStore(roots,bound.envelope)
  const rows=CONSUMED.map(id=>bound.plan.requests.find(r=>r.logicalId===id))
  for(const r of rows)store.append({kind:'START',logicalId:r.logicalId,attempt:1,requestBodySha256:identity(r.body),issuedAtUtc:'2026-09-16T16:00:00Z',reservedCredits:1})
  for(const r of [...rows].reverse()){
    const raw=response(r,r.lens==='STATE'?{timestamp:'2023-03-13T11:00:00'}:{nullPrice:true}),headers=observed(r.lens==='STATE'?'627478':'627479')
    const saved=store.persist(r.logicalId,1,raw)
    store.append({kind:'RESPONSE',logicalId:r.logicalId,attempt:1,httpStatus:200,quotedCredits:1,actualCredits:1,remainingCredits:Number(headers['x-nansen-credits-remaining']),headers,...saved,latencyMs:12})
  }
  for(const r of rows)store.append({kind:'TERMINAL',logicalId:r.logicalId,attempt:1,disposition:'TERMINAL_FAILURE',reason:'B1_SCHEMA_TEMPORAL_OR_PROJECTION',publicRecord:null})
  const prior=replay(roots,bound.envelope),pins={ledgerSha256:prior.bytesSha256,ledgerBytes:prior.bytes,genesisSha256:sha(Buffer.from('synthetic genesis')),commitSha256:sha(Buffer.from('synthetic commit'))}
  const diagnostic={responses:rows.map(r=>{const rr=prior.responses.get(r.logicalId+'.1');return {logicalId:r.logicalId,...diagnose(bound,r,store.raw(rr),rr)}})}
  return {roots,store,prior,pins,diagnostic}
}
describe('R1 preserved structural diagnostics without raw-value echo',()=>{
  it('reports a stable durable-read stage without echoing arbitrary storage exceptions',()=>{const r=request('transactions');const d=diagnoseDurable(bound,r,{raw(){throw new Error('PRIVATE_EXCEPTION_VALUE')}},{});expect(d.firstFailedStage).toBe('durableStorage');expect(d.stages.durableStorage.code).toBe('DURABLE_RAW_READ_FAILED');expect(JSON.stringify(d)).not.toContain('PRIVATE_EXCEPTION_VALUE')})
  it('drains safely if raw breaks between admitted preflight and ordered flush',async()=>{
    const dir=fs.mkdtempSync(path.join(os.tmpdir(),'trace-r1-flush-synthetic-'));directories.push(dir)
    const roots=['primary','mirror'].map(n=>{const p=path.join(dir,n);fs.mkdirSync(p,{mode:0o700});for(const f of ['GENESIS_COMMIT.json','genesis.json','qualification.jsonl'])fs.writeFileSync(path.join(p,f),'',{mode:0o600});return p})
    const store=new BatchStore(roots,bound.envelope),read=store.raw.bind(store),reads=new Map();let calls=0,settled=0,t=Date.now()
    store.raw=row=>{const n=(reads.get(row.logicalId)??0)+1;reads.set(row.logicalId,n);if(n===2)fs.appendFileSync(path.join(roots[1],'raw-b1',row.rawName),'x');return read(row)}
    const clock={now:()=>t,sleep:async ms=>{t+=ms}},dispatcher=new Dispatcher({bound,store,rate:new RateGate(clock),...clock,transport:async r=>{calls++;await new Promise(resolve=>setTimeout(resolve,5));settled++;return {status:200,headers:observed(),bytes:response(r)}}})
    await expect(dispatcher.run()).resolves.toMatchObject({counted:0,stopReason:'B1_DURABLE_RAW_READ_FAILED'});expect(calls).toBeLessThanOrEqual(2);expect(settled).toBe(calls);expect(dispatcher.writerStopped).toBe(true);expect(dispatcher.inFlight).toBe(0)
  })
  it('admits positive synthetic documented responses through every stage',()=>{for(const family of ['transactions','historical-balances']){const r=request(family),raw=response(r);const d=diagnose(bound,r,raw,{rawSha256:sha(raw)});expect(d.safelyAdmissible).toBe(true);expect(Object.values(d.stages).every(s=>s.status==='PASS')).toBe(true);expect(d.admittedResultCount).toBe(1);expect(JSON.stringify(d)).not.toContain('PRIVATE_SYNTHETIC_LABEL')}})
  it('pinpoints null-versus-number schema failures without values or exception messages',()=>{const r=request('transactions'),raw=response(r,{nullPrice:true}),d=diagnose(bound,r,raw,{rawSha256:sha(raw)});expect(d.firstFailedStage).toBe('providerSchema');expect(d.stages.providerSchema.findings).toContainEqual(expect.objectContaining({pointer:'/data/0/tokens_sent/0/price_usd',code:'SCHEMA_TYPE',expectedTypes:['number'],observedType:'null'}));expect(d.stages.temporal.status).toBe('NOT_RUN');expect(JSON.stringify(d)).not.toContain('PRIVATE_SYNTHETIC_LABEL')})
  it('identifies timezone ambiguity and nominal pre-window balance time',()=>{const r=request('historical-balances'),raw=response(r,{timestamp:'2023-03-13T11:00:00'}),d=diagnose(bound,r,raw,{rawSha256:sha(raw)});expect(d.stages.temporal).toMatchObject({status:'FAIL',code:'TIMESTAMP_WITHOUT_EXPLICIT_TIMEZONE_NOT_ADMITTED',minimumTimestamp:'2023-03-13T11:00:00',nominalMinimumPrecedesRequestedFrom:true})})
  it('does not invent intraday timestamps from date-only snapshots',()=>{const r=request('historical-balances'),raw=response(r,{timestamp:'2023-03-13'});expect(diagnose(bound,r,raw,{rawSha256:sha(raw)}).stages.temporal.code).toBe('DATE_ONLY_SNAPSHOT_CANNOT_PROVE_INTRADAY_WINDOW')})
  it.each(['2023-03-13T10:00:00Z','2023-03-13T12:16:00Z'])('rejects exact out-of-window or post-cutoff %s',timestamp=>{const r=request('historical-balances'),raw=response(r,{timestamp});expect(diagnose(bound,r,raw,{rawSha256:sha(raw)}).stages.temporal.status).toBe('FAIL')})
  it('orders offset timestamps by actual instant',()=>{const r=request('historical-balances'),o=JSON.parse(response(r));o.data.push({...o.data[0],block_timestamp:'2023-03-13T12:45:00+01:00'});o.data[0].block_timestamp='2023-03-13T12:00:00Z';const raw=Buffer.from(JSON.stringify(o)),d=diagnose(bound,r,raw,{rawSha256:sha(raw)});expect(d.stages.temporal.minimumTimestamp).toBe('2023-03-13T12:45:00+01:00');expect(d.stages.temporal.maximumTimestamp).toBe('2023-03-13T12:00:00Z')})
  it('redacts unknown lowercase secret-bearing field names and pointer components',()=>{const sentinel=['synthetic','private','label'].join('_'),schema={type:'object',properties:{data:{type:'object',additionalProperties:{type:'number'}}},additionalProperties:false};const o={[sentinel]:'PRIVATE_VALUE',data:{[sentinel]:'PRIVATE_VALUE'}};const d=structuralSchema(o,schema);expect(JSON.stringify(d)).not.toContain(sentinel);expect(JSON.stringify(d)).not.toContain('PRIVATE_VALUE');expect(d.findings.some(f=>f.pointer==='')).toBe(true);expect(JSON.stringify(d)).toContain('REDACTED_FIELD_NAME')})
  it('forbids remote schema references locally',()=>{expect(structuralSchema({},{$ref:'https://example.invalid/schema'}).code).toBe('SCHEMA_DIAGNOSTIC_UNAVAILABLE')})
  it('rejects invalid JSON without arbitrary exception echo',()=>{const d=diagnose(bound,request('transactions'),Buffer.from('{PRIVATE_RAW'),{});expect(d.firstFailedStage).toBe('json');expect(JSON.stringify(d)).not.toContain('PRIVATE_RAW')})
  it('names pagination stage and missing allowlisted-transfer normalization stage',()=>{const r=request('transactions'),o=JSON.parse(response(r));o.pagination.page=2;let raw=Buffer.from(JSON.stringify(o));expect(diagnose(bound,r,raw,{rawSha256:sha(raw)}).firstFailedStage).toBe('pagination');raw=response(r,{emptyTransfers:true});expect(diagnose(bound,r,raw,{rawSha256:sha(raw)}).stages.normalizationProjection.code).toBe('NORMALIZATION_NO_ALLOWLISTED_TRANSFER_FACTS')})
})
describe('R1 safe audit headers and independent live rate windows',()=>{
  it('captures exact future provider request ID and only finite safe header names',()=>{const h=captureSafeHeaders({...observed(),'x-request-id':'req-123:abc','payment-receipt':'PRIVATE_PAYMENT','authorization':'PRIVATE_AUTH','set-cookie':'PRIVATE_COOKIE','x-prohibited':'PRIVATE_METADATA'});expect(h['x-request-id']).toBe('req-123:abc');expect(JSON.stringify(h)).not.toMatch(/PRIVATE_/);expect(Object.keys(h)).not.toContain('payment-receipt')})
  it.each(['x-request-id','x-nansen-ratelimit-scope','retry-after'])('prevents credential echo in %s',name=>{const key=['SYNTHETIC','NOT','REAL','KEY'].join('_');expect(()=>captureSafeHeaders({[name]:key},key)).toThrow('R1_UNSAFE_AUDIT_HEADER')})
  it('rejects unsafe identifier/header shapes rather than redacting or inventing IDs',()=>{for(const value of ['Bearer private','/home/synthetic/private','abc\nPRIVATE','x'.repeat(129)])expect(()=>captureSafeHeaders({'x-request-id':value})).toThrow()})
  it('retains20/second1200/minute with exact observed one-second generic windows',async()=>{let t=0;const rate=new RateGate({now:()=>t,sleep:async ms=>{t+=ms}});rate.headers(observed(),200);expect(rate.second).toBe(20);expect(rate.minute).toBe(1200);expect(rate.allowances.get('x-ratelimit-').duration).toBe(1000);expect(rate.allowances.get('ratelimit-').duration).toBe(1000);for(let i=0;i<5;i++)await rate.acquire(()=>false);expect(t).toBeGreaterThanOrEqual(200);t=1001;await rate.acquire(()=>false);expect(rate.allowances.has('x-ratelimit-')).toBe(false);expect(rate.minute).toBe(1200)})
  it('honors exhausted active generic allowance without permanently lowering minute ceiling',async()=>{let t=0;const rate=new RateGate({now:()=>t,sleep:async ms=>{t+=ms}});rate.headers({'x-ratelimit-limit':'75','x-ratelimit-remaining':'0','x-ratelimit-reset':'1'},200);await rate.acquire(()=>false);expect(t).toBeGreaterThanOrEqual(1000);expect(rate.minute).toBe(1200)})
  it('requires a known horizon for generic windows and honors unknown429scope/RetryAfter',async()=>{let t=0;const rate=new RateGate({now:()=>t,sleep:async ms=>{t+=ms}});expect(()=>rate.headers({'x-ratelimit-limit':'75'},200)).toThrow('B1_RATE_WINDOW_HORIZON_UNKNOWN');rate.headers({'retry-after':'3','x-nansen-ratelimit-scope':'future-window'},429);await rate.acquire(()=>false);expect(t).toBeGreaterThanOrEqual(3000)})
})
describe('R1 exact reviewed nonzero state and immutable consumed-call guard',()=>{
  it('reads a complete synthetic nonzero mirrored checkpoint without mutation',()=>{const x=synthetic(),before=x.roots.map(r=>fs.readFileSync(path.join(r,'qualification.jsonl')));expect(verifyPreservedState(bound,x.roots,x.pins).prior.starts.size).toBe(2);expect(x.roots.map(r=>fs.readFileSync(path.join(r,'qualification.jsonl')))).toEqual(before);expect(()=>verifyPreservedState(bound,x.roots)).toThrow('R1_REVIEWED_LEDGER_IDENTITY')})
  it.each(['ledger','raw','lock','genesis','commit','orphanRaw','unexpectedRoot','mode','crashTail'])('blocks altered preserved %s before any issue or credential',kind=>{const x=synthetic();for(const root of x.roots){if(kind==='ledger'||kind==='crashTail')fs.appendFileSync(path.join(root,'qualification.jsonl'),kind==='ledger'?'\n':'{');if(kind==='raw')fs.appendFileSync(path.join(root,'raw-b1',CONSUMED[0]+'.1.bin'),'x');if(kind==='lock')fs.writeFileSync(path.join(root,'B1_EXECUTION_LOCK.json'),'{}');if(kind==='genesis')fs.writeFileSync(path.join(root,'genesis.json'),'changed');if(kind==='commit')fs.writeFileSync(path.join(root,'GENESIS_COMMIT.json'),'changed');if(kind==='orphanRaw')fs.writeFileSync(path.join(root,'raw-b1','orphan.bin'),'x',{mode:0o600});if(kind==='unexpectedRoot')fs.writeFileSync(path.join(root,'other.json'),'{}',{mode:0o600});if(kind==='mode')fs.chmodSync(path.join(root,'qualification.jsonl'),0o644)}expect(()=>verifyPreservedState(bound,x.roots,x.pins)).toThrow()})
  it('binds13 exact remaining IDs and excludes two consumed IDs even for retry/replacement',()=>{const envelope=resumeEnvelope(bound);expect(envelope.remainingIds).toHaveLength(13);expect(envelope.resumeCanaryIds).toEqual(['141787f240ca281943f1d0be00366aa33166c76f1dc01838bdd4ee5329de9d18','2ba8e2f1d9c841b8781a736dbceb61ebd52eb78edbb5d6e8f04e5e39b1fad4e6']);for(const id of envelope.remainingIds)expect(assertRemainingIssue(envelope,id)).toBe(true);for(const id of CONSUMED)expect(()=>assertRemainingIssue(envelope,id)).toThrow();expect(()=>assertRemainingIssue(envelope,envelope.remainingIds[0],new Set([envelope.remainingIds[0]]))).toThrow();expect(()=>assertRemainingIssue(envelope,'f'.repeat(64))).toThrow()})
  it('requires exact reviewed baseline and unambiguous successful local admission, not a mutable flag',()=>{const x=synthetic(),envelope=resumeEnvelope(bound);expect(()=>assertResumeAdmission(bound,x.prior,x.diagnostic,envelope)).toThrow('R1_EXACT_REVIEWED_RESUME_BASELINE_REQUIRED');const pinned={...x.prior,bytesSha256:LEDGER_SHA,bytes:4659};expect(()=>assertResumeAdmission(bound,pinned,x.diagnostic,envelope)).toThrow('R1_ROOT_CAUSE_ADMISSION_BLOCKED');const diagnostic={responses:CONSUMED.map(id=>({logicalId:id,safelyAdmissible:true,firstFailedStage:null,stages:Object.fromEntries(['json','providerSchema','pagination','temporal','normalizationProjection','publicSchema'].map(k=>[k,{status:'PASS'}]))}))};expect(assertResumeAdmission(bound,pinned,diagnostic,envelope)).toBe(true);diagnostic.responses[0].stages.temporal.status='NOT_RUN';expect(()=>assertResumeAdmission(bound,pinned,diagnostic,envelope)).toThrow();expect(()=>assertResumeAdmission(bound,pinned,{responses:[]},{...envelope,executionContractSha256:'0'.repeat(64)})).toThrow()})
})
describe('R1 schema-validated request value audit and truthful accounting',()=>{
  it('audits all15, consumes two noncounted, leaves13 unissued, captures engineering-only value',()=>{const x=synthetic(),audit=requestAudit(bound,x.prior,x.diagnostic);expect(audit.records).toHaveLength(15);const old=audit.records.filter(r=>r.issued);expect(old).toHaveLength(2);for(const r of old){expect(r.qualification_value).toBe('ZERO_NOT_COUNTED');expect(r.gameplay_consumer_value).toBe('NO_ADMITTED_GAMEPLAY_EVIDENCE_FROM_B1_V1');expect(r.engineering_value.length).toBeGreaterThan(0);expect(r.attempts[0].provider_request_id).toBeNull();expect(r.attempts[0].providerRequestIdDisposition).toBe('NOT_CAPTURED_BY_B1_TRANSPORT_V1');expect(r.attempts[0].completedAtUtc).toBeNull()}expect(audit.records.filter(r=>!r.issued)).toHaveLength(13);expect(JSON.stringify(audit)).not.toContain('PRIVATE_SYNTHETIC_LABEL');expect(JSON.stringify(audit)).not.toContain(x.roots[0])})
  it.each(['extraRaw','payment','duplicate','question','consumer','count','providerId','headerValue','bytesEqual','schemaIdentity','terminalSequence','exclusionReason','engineeringValue','timestampDisposition','requestIdDisposition','competitionValue'])('rejects mutated audit %s',kind=>{const x=synthetic(),audit=requestAudit(bound,x.prior,x.diagnostic),old=audit.records.find(r=>r.issued);if(kind==='extraRaw')old.rawBody='PRIVATE_RAW';if(kind==='payment')old.attempts[0].safeHeaders['payment-receipt']='PRIVATE_PAYMENT';if(kind==='duplicate')audit.records[1]=structuredClone(audit.records[0]);if(kind==='question')old.businessQuestion+=' altered';if(kind==='consumer')old.consumerIds=[];if(kind==='count')old.qualificationCounted=true;if(kind==='providerId')old.attempts[0].provider_request_id='invented';if(kind==='headerValue')old.attempts[0].safeHeaders['retry-after']='/home/private/value';if(kind==='bytesEqual')old.attempts[0].bytesEqual=false;if(kind==='schemaIdentity')old.attempts[0].responseSchemaIdentity='0'.repeat(64);if(kind==='terminalSequence')old.attempts[0].terminalSequence=999;if(kind==='exclusionReason')old.exclusionReason='invented';if(kind==='engineeringValue')old.engineering_value=[];if(kind==='timestampDisposition')old.attempts[0].completedTimestampDisposition='CAPTURED';if(kind==='requestIdDisposition')old.attempts[0].providerRequestIdDisposition='CAPTURED';if(kind==='competitionValue')audit.records.find(r=>!r.issued).competition_evidence_value='SAFE_ADMITTED_QUALIFICATION_AUDIT';expect(()=>validateAudit(audit,bound,x.prior,x.diagnostic)).toThrow()})
  it('requires a trusted verified diagnostic context rather than schema-valid flags',()=>{const x=synthetic(),audit=requestAudit(bound,x.prior,x.diagnostic);expect(()=>validateAudit(audit,bound,x.prior)).toThrow('R1_TRUSTED_DIAGNOSTIC_CONTEXT_REQUIRED')})
  it('reports explicit zero-admission family/lens/cell/consumer buckets separately from spend',()=>{const x=synthetic(),audit=requestAudit(bound,x.prior,x.diagnostic),b=utilityBuckets(audit);expect(Object.keys(b.byEndpointFamily)).toHaveLength(2);expect(Object.keys(b.byQuestionLens)).toHaveLength(2);expect(Object.keys(b.byCoverageCell).length).toBeGreaterThan(0);expect(Object.keys(b.byNamedConsumer).length).toBeGreaterThan(0);for(const group of Object.values(b))for(const bucket of Object.values(group)){expect(bucket.countedSuccesses).toBe(0);expect(bucket.admittedNormalizedResultCount).toBe(0);expect(bucket.gameplayEvidenceDisposition).toBe('NO_ADMITTED_GAMEPLAY_EVIDENCE_FROM_B1_V1')}expect(Object.values(b.byEndpointFamily).reduce((n,r)=>n+r.knownActualCredits,0)).toBe(2)})
  it('separates2549 total decrease into2 campaign credits and2547 unattributed',()=>{const x=synthetic();expect(balanceReconciliation(x.prior)).toMatchObject({historicalAnchor:630027,campaignAttributedCreditUse:2,totalAccountWideDecreaseSinceHistoricalAnchor:2549,unattributedAccountWideDecrease:2547,classification:'UNATTRIBUTED_ACCOUNT_WIDE_CHANGE',latestSafeBudgetAnchor:627478,protectedReserve:250});expect(balanceReconciliation(x.prior).perResponseSequence.map(r=>r.remaining)).toEqual([627479,627478])})
  it('does not claim gameplay evidence when no record was admitted',()=>{const x=synthetic(),result=reconcile(bound,x.roots);expect(result.report.countedSuccesses).toBe(0);expect(result.utility.consumerEnablementClaim).toBe('NO_ADMITTED_GAMEPLAY_EVIDENCE_FROM_B1_V1');expect(result.utility.normalizedRecordCount).toBe(0);expect(result.utility.engineeringValidationValue).not.toBe('NONE')})
})
