import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { beforeAll, describe, expect, it } from 'vitest'
import { bindAccepted } from '../../scripts/nq5-b1/authority.mjs'
import { corpusAt } from '../../scripts/nq5-b1-r2/gates.mjs'
import { identity, sha } from '../../scripts/nq5/schema.mjs'
import { IDS, priorEvidence, seal } from '../../scripts/nq5-b1-r3/authority.mjs'
import { profile, acceptedTruth, admit, plans, temporal, TEMPORAL, DRIFT } from '../../scripts/nq5-b1-r3/compatibility.mjs'
import { authorizeContext, Executor, ResumeStore, resumeEnvelope, liveTransport } from '../../scripts/nq5-b1-r3/executor.mjs'
import { CONSUMED, LEDGER_SHA } from '../../scripts/nq5-b1-r1/checkpoint.mjs'
import { nextFrontier, claimMatrix } from '../../scripts/nq5-b1-r3/evidence.mjs'
import { assertFresh, assertLiveDocs, validateCapturedIndex, allowed, NAMES } from '../../scripts/nq5-b1-r3/docs.mjs'
import { assertLiveContext, assertRawInventory, assertPrivateAncestry } from '../../scripts/nq5-b1-r3/gate-proof.mjs'
import { blockedReports } from '../../scripts/nq5-b1-r3/blocked.mjs'

const root=fileURLToPath(new URL('../..',import.meta.url));let bound,old,truth,p,docs,accepted,auditSchema
beforeAll(()=>{bound=bindAccepted(JSON.parse(fs.readFileSync(new URL('../fixtures/nq5-b1-accepted-public.json',import.meta.url))));accepted=priorEvidence(root);old=JSON.parse(accepted.bytes['CONTRACTS/ADDRESS_TRANSACTIONS_NULL_COMPATIBILITY_PROFILE.json']);truth=acceptedTruth(root);p=profile(bound,old,truth);docs=corpusAt(root);auditSchema=JSON.parse(fs.readFileSync(new URL('../../schemas/NANSEN_API_REQUEST_AUDIT.schema.json',import.meta.url)))},30000)
const request=()=>bound.plan.requests.find(r=>r.logicalId===IDS[0])
function response(r=request()){const a='0x'+'1'.repeat(40);return {pagination:{page:1,per_page:100,is_last_page:true},data:[{transaction_hash:'0x'+'2'.repeat(64),block_timestamp:r.body.date.from.slice(0,-1),chain:'ethereum',source_type:'SYNTHETIC',method:'transfer',tokens_sent:[{token_symbol:'SYNTHETIC',token_amount:2,token_address:a,chain:'ethereum',from_address:r.body.address,to_address:'0x'+'3'.repeat(40),price_usd:null,value_usd:null,from_address_label:'PRIVATE_LABEL_SENTINEL'}],tokens_received:[]}]}}
const admission=(o,r=request(),pp=p,tt=truth)=>{const raw=Buffer.from(JSON.stringify(o));return admit(bound,r,raw,{rawSha256:sha(raw),rawBytes:raw.length},1,pp,old,tt)}
function context(){return {root,bound,accepted,auditSchema:structuredClone(auditSchema),oldProfile:old,truth,profile:p,plans:plans(bound,p),prior:{bytesSha256:LEDGER_SHA,bytes:4659,rows:[],starts:new Map(CONSUMED.map(id=>[id+'.1',{}])),responses:new Map(CONSUMED.map(id=>[id+'.1',{}])),terminals:new Map(CONSUMED.map(id=>[id,{disposition:'TERMINAL_FAILURE'}]))},diagnostic:{originalLockSha256:'331729a7393cf20a2d50533ef267b70102eef18fd4e892f43d44a0fb649edb37'}}}
const gates={localPass:true,reviewPass:true,docsPass:true,replayPass:true}
function memoryExecutor(transport,options={}){const c=authorizeContext(context(),gates),raw=new Map(),store={context:c,rows:[],append(r){const row={...r,sequence:this.rows.length+1,hash:identity(r)};this.rows.push(row);return row},persist(id,attempt,bytes){raw.set(id+'.'+attempt,Buffer.from(bytes));return{rawName:id+'.'+attempt+'.bin',rawSha256:sha(bytes),rawBytes:bytes.length}},raw(r){return raw.get(r.logicalId+'.'+r.attempt)},currentForAudit(){const current={rows:this.rows,starts:new Map(c.prior.starts),responses:new Map(c.prior.responses),terminals:new Map(c.prior.terminals)};for(const r of this.rows){if(r.kind==='START')current.starts.set(r.logicalId+'.'+r.attempt,r);if(r.kind==='RESPONSE')current.responses.set(r.logicalId+'.'+r.attempt,r);if(r.kind==='TERMINAL')current.terminals.set(r.logicalId,r)}return current}};return new Executor({context:c,store,transport,rate:{acquire:async stopped=>!stopped(),headers(){}},sleep:async()=>{},random:()=>0,...options})}
const received=(id,status=200,headers={})=>{const r=bound.plan.requests.find(r=>r.logicalId===id);return {status,bytes:Buffer.from(JSON.stringify(response(r))),headers:{'x-request-id':'synthetic-'+id.slice(0,8),'x-nansen-credits-used':'1','x-nansen-credits-cost':'1','x-nansen-credits-remaining':'627477',...headers}}}

describe('R3 exact Lead profile and contextual-only claim boundary',()=>{
 it('binds exact R2 identities and only four original byte-identical rows',()=>{const a=priorEvidence(root),q=plans(bound,p);expect(a.audit.records).toHaveLength(15);expect(q.plan.requests).toEqual(IDS.map(id=>bound.plan.requests.find(r=>r.logicalId===id)));expect(q.plan.requests.map(r=>r.logicalId)).toEqual(IDS);expect(q.plan.expectedCredits).toBe(4);expect(q.plan.worstCaseCredits).toBe(12);expect(q.reserve.remainingAfterWorstCase).toBe(627466);expect(q.reserve.reserveHeadroom).toBe(627216);expect(q.plan.AUTHORIZED_TO_ISSUE).toBe(false);expect(p.officialAdmission).toBe(false);expect(p.observedDriftNotice).toBe(DRIFT)})
 it('passes narrow null/unzoned compatibility while omitting all enrichment, labels and raw timestamps',()=>{const o=response(),before=identity(o),a=admission(o);expect(a.safelyAdmissible).toBe(true);expect(Object.values(a.stages).every(x=>x.status==='PASS')).toBe(true);expect(a.nullEnrichmentFieldsObserved).toBe(2);expect(a.publicRecord.evidence_grade).toBe('CONTEXTUAL');expect(a.publicRecord.temporal_class).toBe(TEMPORAL);expect(a.normalizedRecords[0]).not.toHaveProperty('block_timestamp');expect(JSON.stringify(a)).not.toMatch(/PRIVATE_LABEL_SENTINEL|price_usd|value_usd/);expect(identity(o)).toBe(before)})
 it('preserves exact decimal lexemes and never zero-imputes',()=>{const raw=Buffer.from(JSON.stringify(response()).replace('"token_amount":2','"token_amount":1.000000000000000001'));const a=admit(bound,request(),raw,{rawSha256:sha(raw),rawBytes:raw.length},1,p,old,truth);expect(a.normalizedRecords[0].amount).toBe('1.000000000000000001');expect(a.stages.normalization.nullImputed).toBe(false)})
 it.each(['transaction_hash','block_timestamp','chain','source_type','method'])('rejects null transaction core %s',k=>{const o=response();o.data[0][k]=null;expect(admission(o).safelyAdmissible).toBe(false)})
 it.each(['token_symbol','token_amount','token_address','chain','from_address','to_address'])('rejects null transfer core %s',k=>{const o=response();o.data[0].tokens_sent[0][k]=null;expect(admission(o).safelyAdmissible).toBe(false)})
 it.each(['missingCore','extraNull','unknownUnsafe','incompatibleType','invalidHash','invalidAddress','wrongChain','page2','perPage','noLastFlag','oversizedPage','noTransfer','badJsonDuplicate','rawMismatch'])('rejects drift %s',kind=>{const o=response();if(kind==='missingCore')delete o.data[0].method;if(kind==='extraNull')o.data[0].volume_usd=null;if(kind==='unknownUnsafe')o.data[0].private_only='PRIVATE_UNSAFE';if(kind==='incompatibleType')o.data[0].tokens_sent[0].token_amount='2';if(kind==='invalidHash')o.data[0].transaction_hash='x';if(kind==='invalidAddress')o.data[0].tokens_sent[0].from_address='x';if(kind==='wrongChain')o.data[0].tokens_sent[0].chain='base';if(kind==='page2')o.pagination.page=2;if(kind==='perPage')o.pagination.per_page=1;if(kind==='noLastFlag')delete o.pagination.is_last_page;if(kind==='oversizedPage')o.data=Array.from({length:101},()=>o.data[0]);if(kind==='noTransfer')o.data[0].tokens_sent=[];if(kind==='badJsonDuplicate'||kind==='rawMismatch'){let raw=Buffer.from(JSON.stringify(o));if(kind==='badJsonDuplicate')raw=Buffer.from(raw.toString().replace('"chain":"ethereum"','"chain":"ethereum","chain":"ethereum"'));expect(admit(bound,request(),raw,{rawSha256:kind==='rawMismatch'?'0'.repeat(64):sha(raw),rawBytes:raw.length},1,p,old,truth).safelyAdmissible).toBe(false)}else expect(admission(o).safelyAdmissible).toBe(false)})
 it.each(['nullMeansZero','otherField','officialAdmission','timezone','schema','wrongProfileHash'])('rejects widened profile %s',kind=>{const pp=structuredClone(p);if(kind==='nullMeansZero')pp.nullMeans='ZERO';if(kind==='otherField')pp.affectedNullableFields.push('token_amount');if(kind==='officialAdmission')pp.officialAdmission=true;if(kind==='timezone')pp.timezoneEstablished=true;if(kind==='schema')pp.compatibilitySchema.additionalProperties=true;if(kind!=='wrongProfileHash'){delete pp.hash;pp.hash=identity(pp)}else pp.hash='0'.repeat(64);expect(()=>admission(response(),request(),pp)).toThrow()})
 it.each(['2023-03-13T08:44:59','2023-03-13T12:15:01','2023-03-13T09:00:00.1','2023-03-13T09:00:00+00:00','2023-02-30T09:00:00','2023-03-13T25:00:00','2023-03-13 09:00:00'])('rejects malformed or out-of-bound nominal time %s',t=>{expect(()=>temporal(t,request())).toThrow()})
 it('compares calendar components without timezone inference and allows exact bounds',()=>{for(const t of ['2023-03-13T08:45:00','2023-03-13T12:15:00'])expect(temporal(t,request())).toMatchObject({classification:TEMPORAL,timezoneInferred:false,exactUtcFromAcceptedTruth:null})})
 it('rejects unzoned request bounds and accepted hash/time mismatches',()=>{const q=structuredClone(request());q.body.date.from=q.body.date.from.slice(0,-1);expect(()=>temporal('2023-03-13T09:00:00',q)).toThrow();expect(()=>temporal('2023-03-13T09:00:00',request(),'2023-03-13T09:00:01Z')).toThrow()})
 it('uses exact public-safe time only from accepted Euler hash join',()=>{const [h,t]=Object.entries(truth.times).find(([,t])=>t>=request().body.date.from&&t<=request().body.date.to),o=response();o.data[0].transaction_hash=h;o.data[0].block_timestamp=t.slice(0,-1);const a=admission(o);expect(a.safelyAdmissible).toBe(true);expect(a.normalizedRecords[0].accepted_exact_utc).toBe(t);expect(a.normalizedRecords[0].accepted_exact_time_source).toBe('ACCEPTED_EULER_TRUTH_HASH_JOIN');o.data[0].block_timestamp='2023-03-13T09:00:00';expect(admission(o).safelyAdmissible).toBe(false)})
 it('replay never assigns public call/count identity and prevents issued-ID admission for live',()=>{const raw=Buffer.from(JSON.stringify(response())),row={rawSha256:sha(raw),rawBytes:raw.length};expect(admit(bound,request(),raw,row,1,p,old,truth,{replayOnly:true}).publicRecord).toBeNull();const consumed=bound.plan.requests.find(r=>r.logicalId===CONSUMED[1]);expect(()=>admit(bound,consumed,raw,row,1,p,old,truth)).toThrow();expect(claimMatrix.forbidden).toContain('INFERRED_UTC');expect(claimMatrix.rawTimestampPublished).toBe(false)})
})
describe('R3 idempotency, bounded concurrency, ordered terminals and breaker controls',()=>{
 it.each(['localPass','reviewPass','docsPass','replayPass'])('rejects missing gate %s before private write/key',key=>{const g={...gates,[key]:false};expect(()=>authorizeContext(context(),g)).toThrow()})
 it.each(['hash','bytes','start','response','terminal'])('rejects wrong nonzero baseline %s',kind=>{const c=context();if(kind==='hash')c.prior.bytesSha256='0'.repeat(64);if(kind==='bytes')c.prior.bytes=0;if(kind==='start')c.prior.starts.clear();if(kind==='response')c.prior.responses.clear();if(kind==='terminal')c.prior.terminals.get(CONSUMED[0]).disposition='SUCCESS_COUNTED';expect(()=>authorizeContext(c,gates)).toThrow()})
 it('rejects store and credential creation without in-memory admission',()=>{const c=context();expect(()=>new ResumeStore(c,{})).toThrow('R3_PRIVATE_WRITE_GATE_REQUIRED');let calls=0;expect(()=>liveTransport(c,{context:c},{environmentCredential:()=>{calls++;return'not-a-real-key'}})).toThrow();expect(calls).toBe(0)})
 it('seals exact resume/attempt/reserve identity while preserving old chain envelope',()=>{const c=context(),e=resumeEnvelope(c,{commit:'synthetic',tree:'synthetic'},'1'.repeat(64),{});expect(e.priorEnvelopeIdentity).toBe(bound.envelope.hash);expect(e.consumedIds).toEqual(CONSUMED);expect(e.executionOrder).toEqual(IDS);expect(e.maximumAdditionalAttempts).toBe(12);expect(e.maximumConcurrency).toBe(2);expect(e.maximumCumulativeCredits).toBe(14)})
 it('captures exact provider ID/finite headers and counts only complete contextual pipeline',async()=>{const e=memoryExecutor(async r=>received(r.logicalId));await e.issue(IDS[0]);expect(e.counted).toBe(1);const rows=e.store.rows;expect(rows.map(r=>r.kind)).toEqual(['START','RESPONSE','TERMINAL']);expect(rows[1].providerRequestId).toBe('synthetic-'+IDS[0].slice(0,8));expect(rows[2].validationStages.contextualTemporal.status).toBe('PASS');expect(rows[2].publicRecord.evidence_grade).toBe('CONTEXTUAL')})
 it('rejects incomplete prospective audit before count and stops every later issue',async()=>{const e=memoryExecutor(async r=>received(r.logicalId));e.context.auditSchema={type:'object',required:['MISSING_REQUIRED_AUDIT_VALUE']};await e.issue(IDS[0]);await e.issue(IDS[1]);expect(e.counted).toBe(0);expect(e.attempts).toBe(1);expect(e.stopReason).toBe('R3_AUDIT_BEFORE_COUNT_REJECTED');expect(e.store.rows.at(-1).publicRecord).toBeNull();expect(e.store.rows.at(-1).auditDisposition).toBe('FAIL')})
 it('rejects durable canary audit failure before group2 without replacing either canary',async()=>{let e,calls=0;e=memoryExecutor(async r=>{calls++;return received(r.logicalId)},{reconcileState:()=>{const current=e.store.currentForAudit();e.context.auditSchema={type:'object',required:['MISSING_REQUIRED_AUDIT_VALUE']};return{current,report:{clean:true,newCounted:2,cumulativeAttempts:current.starts.size,newAttempts:2}}}});const r=await e.run();expect(r.stopReason).toBe('R3_CANARY_COMPLETE_AUDIT_BREAKER');expect(calls).toBe(2);expect(r.newAttempts).toBe(2);expect(r.newCounted).toBe(2);expect(e.started.size).toBe(2)})
 it('durably commits reverse-completing canary terminals in frozen order at concurrency2',async()=>{let release;const e=memoryExecutor(async r=>{if(r.logicalId===IDS[0])await new Promise(resolve=>release=resolve);else release();return received(r.logicalId)});await Promise.all(IDS.slice(0,2).map(id=>e.issue(id)));expect(e.maxInFlight).toBe(2);expect(e.store.rows.filter(r=>r.kind==='TERMINAL').map(r=>r.logicalId)).toEqual(IDS.slice(0,2));expect(e.counted).toBe(2)})
 it.each(['providerId','cost','unknownCost','reserve','auth','redirect','schema','transport','unsafeHeader','storage'])('stops first breaker %s with no replacement/next issue',async kind=>{const e=memoryExecutor(async r=>{if(kind==='transport')throw new Error('synthetic');const v=received(r.logicalId,kind==='auth'?401:kind==='redirect'?302:200);if(kind==='providerId')delete v.headers['x-request-id'];if(kind==='cost')v.headers['x-nansen-credits-used']='2';if(kind==='unknownCost')delete v.headers['x-nansen-credits-used'];if(kind==='reserve')v.headers['x-nansen-credits-remaining']='249';if(kind==='unsafeHeader')v.headers['x-request-id']='Bearer unsafe';if(kind==='schema')v.bytes=Buffer.from(JSON.stringify({data:[],pagination:null}));return v});if(kind==='storage')e.store.persist=()=>{throw new Error('synthetic')};await e.issue(IDS[0]);await e.issue(IDS[1]);expect(e.stopReason).not.toBeNull();expect(e.counted).toBe(0);expect(e.attempts).toBe(1)})
 it('never reissues consumed, duplicate or fifth ID',async()=>{const e=memoryExecutor(async r=>received(r.logicalId));for(const id of [...CONSUMED,'0'.repeat(64)])await expect(e.issue(id)).rejects.toThrow();await e.issue(IDS[0]);await expect(e.issue(IDS[0])).rejects.toThrow();expect(e.attempts).toBe(1)})
 it('uses only existing retry statuses, at most3 tries/id and mandatory Retry-After',async()=>{let calls=0;const e=memoryExecutor(async r=>{calls++;return received(r.logicalId,calls<3?503:200,{'retry-after':'0','x-nansen-credits-used':calls<3?'0':'1'})});await e.issue(IDS[0]);expect(e.attempts).toBe(3);expect(e.counted).toBe(1);expect(e.credits).toBe(1);expect(e.reserved).toBe(0)})
 it('stops indeterminate transport and never repairs/restarts unresolved attempt',async()=>{const e=memoryExecutor(async()=>{throw new Error('synthetic')});await e.issue(IDS[0]);expect(e.reserved).toBe(1);expect(e.store.rows.map(r=>r.kind)).toEqual(['START','TERMINAL']);await expect(e.issue(IDS[0])).rejects.toThrow()})
 it('respects attempt cap and protected-credit capacity before START',async()=>{const e=memoryExecutor(async r=>received(r.logicalId));e.attempts=12;await e.issue(IDS[0]);expect(e.store.rows).toHaveLength(0);expect(e.stopReason).not.toBeNull()})
})
describe('R3 bounded documentation freshness and no-padding frontier',()=>{
 function fresh(){const snapshots=NAMES.map(n=>{const {body,...r}=docs.corpus[n];return{...r,reusedR2:false,retrievedAtUtc:new Date().toISOString()}}),bodies=Object.fromEntries(NAMES.map(n=>[n,Buffer.from(docs.corpus[n].body)]));return{index:{snapshots},bodies}}
 it('reuses exact locally fresh five documents only',()=>{const f=fresh();expect(assertFresh(f.index,f.bodies,docs.corpus)).toBe(true)})
 it('rejects relabelled stale R2 capture time and admits only exact reuse provenance',()=>{const f=fresh();for(const r of f.index.snapshots){r.reusedR2=true;r.transport='LOCAL_EXACT_R2_REUSE'}expect(()=>assertFresh(f.index,f.bodies,docs.corpus)).toThrow();for(const r of f.index.snapshots)r.retrievedAtUtc=docs.corpus[r.name].retrievedAtUtc;const now=Math.max(...f.index.snapshots.map(r=>Date.parse(r.retrievedAtUtc)))+1000;expect(assertFresh(f.index,f.bodies,docs.corpus,now)).toBe(true)})
 it('denies serialized/fake document and live gate proofs without provider/key access',()=>{const f=fresh();expect(()=>assertLiveDocs(root,f)).toThrow('R3_BRANDED_DOCUMENT_PROOF_REQUIRED');expect(()=>assertLiveContext(context())).toThrow('R3_BRANDED_PRELIVE_PROOF_REQUIRED');const c=authorizeContext(context(),gates),fake={context:c,roots:['synthetic','synthetic']};let callbacks=0;expect(()=>liveTransport(c,fake,{environmentCredential:()=>{callbacks++;return'not-a-real-key'}})).toThrow('R3_CREDENTIAL_GATE_REQUIRED');expect(callbacks).toBe(0);expect(()=>new ResumeStore(c,{})).toThrow('R3_BRANDED_PRELIVE_PROOF_REQUIRED')})
 it.each(['filenameTraversal','reordered','extraPrivateField','unsafeUrl','wrongGetCount','nonHexHash'])('rejects serialized capture metadata before body read %s',kind=>{const f=fresh(),i={schemaVersion:'1.0.0',acceptedR2SourceIndexIdentity:'9dcd93f996b92d4c8afd44815a5786ace16ca8c667700ea342eeae3a8a3ffbcf',mode:'EXACT_FIVE_CONDITIONAL_REFRESH',unauthenticatedDocumentationGets:5,authenticatedNansenProviderRequests:0,accountRequests:0,browserRuntimeRequests:0,snapshots:f.index.snapshots.map(r=>({name:r.name,url:r.url,retrievedAtUtc:r.retrievedAtUtc,httpStatus:200,bytes:r.bytes,sha256:r.sha256,r2Sha256:r.sha256,unchangedFromR2:true,reusedR2:false,filename:r.name+'.md',transport:'UNAUTHENTICATED_HTTPS_GET_NO_REDIRECT'}))};expect(validateCapturedIndex(i)).toBe(i);if(kind==='filenameTraversal')i.snapshots[0].filename='../../synthetic-secret.txt';if(kind==='reordered')i.snapshots.reverse();if(kind==='extraPrivateField')i.private_only='synthetic';if(kind==='unsafeUrl')i.snapshots[0].url='https://api.nansen.ai/api/v1/account';if(kind==='wrongGetCount')i.unauthenticatedDocumentationGets=0;if(kind==='nonHexHash')i.snapshots[0].sha256='z'.repeat(64);expect(()=>validateCapturedIndex(i)).toThrow()})
 it('rejects post-admission orphan/missing/unsafe raw inventory before any credential callback',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'r3-synthetic-inventory-')),roots=[path.join(temp,'primary'),path.join(temp,'mirror')],names=CONSUMED.map(id=>id+'.1.bin');try{for(const r of roots){fs.mkdirSync(r,{mode:0o700});fs.mkdirSync(path.join(r,'raw-b1'),{mode:0o700});for(const name of names)fs.writeFileSync(path.join(r,'raw-b1',name),'synthetic',{mode:0o600})}expect(assertRawInventory(roots,names)).toBe(true);const orphan=path.join(roots[0],'raw-b1','orphan.bin');fs.writeFileSync(orphan,'synthetic',{mode:0o600});expect(()=>assertRawInventory(roots,names)).toThrow('R3_PREKEY_RAW_INVENTORY_CHANGED');fs.unlinkSync(orphan);fs.chmodSync(path.join(roots[1],'raw-b1',names[0]),0o644);expect(()=>assertRawInventory(roots,names)).toThrow('R3_PREKEY_RAW_METADATA_CHANGED')}finally{fs.rmSync(temp,{recursive:true,force:true})}})
 it('rejects post-admission ancestor symlink substitution before private reads/key',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'r3-synthetic-ancestry-')),real=path.join(temp,'real'),parent=path.join(temp,'parent');try{fs.mkdirSync(real,{mode:0o700});fs.mkdirSync(path.join(real,'root'),{mode:0o700});expect(assertPrivateAncestry([path.join(real,'root')])).toBe(true);fs.symlinkSync(real,parent,'dir');expect(()=>assertPrivateAncestry([path.join(parent,'root')])).toThrow('R3_PRIVATE_ANCESTRY_CHANGED')}finally{fs.rmSync(temp,{recursive:true,force:true})}})
 it.each(['R3_DOC_UNAVAILABLE_OR_CHANGE_REQUIRES_REVIEW','R3_DOC_UNAVAILABLE_CHANGED_OR_STALE'])('emits complete zero-issue blocked evidence for precredential docs failure %s',code=>{const c=context();c.accepted=priorEvidence(root);c.auditSchema={};const r=blockedReports(c,{code,phase:'DOCUMENT_FRESHNESS',knownNoNewProviderActivity:true,credentialResolvedAtRuntime:false});expect(r.status).toBe('BLOCKED_WITH_EVIDENCE');expect(r.readiness.newAttempts).toBe(0);expect(r.readiness.newCounted).toBe(0);expect(r.entries['EXECUTION/T1_B1_R3_RESUME_ENVELOPE.json'].liveAdmitted).toBe(false);expect(r.entries['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'].records).toHaveLength(15);expect(r.frontier).toBeNull()})
 it.each(['R3_ORPHAN_RAW_STOP_NO_REPAIR','R3_DURABLE_STATE_UNRECONCILED'])('emits unknown/null blocked counters after synthetic issued raw/journal failure %s',code=>{const c=context();c.accepted=priorEvidence(root);c.auditSchema={};const r=blockedReports(c,{code,phase:'RECONCILIATION',knownNoNewProviderActivity:false,credentialResolvedAtRuntime:true});expect(r.readiness.newAttempts).toBeNull();expect(r.readiness.newCounted).toBeNull();expect(r.readiness.newKnownActualCredits).toBeNull();expect(r.readiness.privateStateRepaired).toBe(false);expect(r.entries['EVIDENCE/PRIMARY_MIRROR_LEDGER_AND_PUBLIC_INDEX_RECONCILIATION.json'].publicIndex).toBeNull();expect(r.entries['EVIDENCE/NANSEN_API_REQUEST_AUDIT.json'].auditScope).toBe('HISTORICAL_ACCEPTED_R2_ONLY_NEW_STATE_UNVERIFIED')})
 it.each(['stale','future','changed','missing','url','status','hash'])('rejects document drift %s',kind=>{const f=fresh(),r=f.index.snapshots[0];if(kind==='stale')r.retrievedAtUtc=new Date(Date.now()-7200001).toISOString();if(kind==='future')r.retrievedAtUtc=new Date(Date.now()+60000).toISOString();if(kind==='changed')f.bodies[r.name]=Buffer.from('changed');if(kind==='missing')f.index.snapshots.pop();if(kind==='url')r.url+='?ask=forbidden';if(kind==='status')r.httpStatus=302;if(kind==='hash')r.sha256='0'.repeat(64);expect(()=>assertFresh(f.index,f.bodies,docs.corpus)).toThrow()})
 it.each(['https://docs.nansen.ai/api/profiler/address-historical-balances.md','https://docs.nansen.ai/api/backtesting-data/historical-address-balance.md','https://docs.nansen.ai/api/profiler/address-transactions.md?ask=anything','https://api.nansen.ai/api/v1/account'])('prohibits unrelated/ask/API URL %s',url=>{expect(allowed(url)).toBe(false)})
 function proof(count=4,last=false){return{report:{newCounted:count,clean:true,ledgerSha256:'1'.repeat(64)},publicIndex:IDS.map((id,i)=>({request_body_sha256:identity(bound.plan.requests.find(r=>r.logicalId===id).body),public_call_id:'NQ5-'+String(i+1).padStart(6,'0')})),projections:IDS.map(id=>({logicalId:id,rows:[{safeSyntheticFact:true}],pagination:{page:1,isLastPage:last}})),current:{responses:new Map([['synthetic',{remainingCredits:627474}]])}}}
 it.each([0,1,2,3])('generates no next frontier when only %i count',count=>{expect(nextFrontier(context(),proof(count))).toBeNull()})
 it('proposes only durable next pages, no fixed page ceiling/newsubject/artificialwindows/padding',()=>{const f=nextFrontier(context(),proof());expect(f.plan.requests.length).toBeGreaterThan(0);expect(f.plan.requests.length).toBeLessThanOrEqual(4);expect(f.plan.AUTHORIZED_TO_ISSUE).toBe(false);expect(f.plan.requests.every(r=>r.body.pagination.page===2&&r.partition.admittedOnlyByDurablePreviousPage===true&&!Object.hasOwn(r.partition,'maximumPages'))).toBe(true);expect(f.policy.minimumRequests).toBe(0);expect(f.policy.noMicroWindows).toBe(true);expect(f.report.nextRequestsIssued).toBe(0)})
 it('allows zero meaningful frontier and refuses unsafe/unaccepted subject or incomplete reconcile',()=>{expect(nextFrontier(context(),proof(4,true)).plan.requests).toHaveLength(0);const c=context();c.truth={...truth,seedAddresses:[]};expect(nextFrontier(c,proof()).plan.requests).toHaveLength(0);const q=proof();q.report.clean=false;expect(nextFrontier(context(),q)).toBeNull()})
})
