import fs from 'node:fs'
import {describe,it,expect} from 'vitest'
import {importActivity,parseCSV,identity,privacyBoundary,CLASSES,PROJECTS,preparePrincipalSample,sha} from '../../scripts/nq5-s2/activity.mjs'
import {compileCorpus,validateConcept,assertCandidateOnly} from '../../scripts/nq5-s2/corpus.mjs'
const sample=()=>{const filename='CPP_SAMPLE_ACTIVITY_OBSERVATION_2026-09-17.json',b=fs.readFileSync('docs/source/execution-s2/INPUTS/'+filename);return preparePrincipalSample(JSON.parse(b),{filename,sha256:sha(b),bytes:b.length})}
const input=()=>JSON.parse(fs.readFileSync('docs/G6P_NQ5_T1_S2_CURATED_INPUT.json'))
const clean=()=>{const s=sample();s.rows=s.rows.slice(0,1);return s}
const binding=s=>({sourceId:s.source_id,sourceIdentity:identity(s),sourceArtifactSha256:s.source_artifact.sha256,sourceArtifactBytes:s.source_artifact.bytes,independentlyVerified:true,reviewIdentity:'a'.repeat(64)})
const applicable={state:'RESOLVED',reviewIdentity:'b'.repeat(64),independentlyVerified:true}
const reseal=x=>{const{identity:h,...p}=x;return{...p,identity:identity(p)}}
describe('S2 account activity evidence, not credits or game records',()=>{
 it('sample yields exactly 20 successful requests, 32 credits, 10/7/3 endpoints and one explicit removed overlap',()=>{const r=importActivity(sample());expect(r.observed).toEqual({requests:20,successes:20,failures:0,credits:32});expect(Object.values(r.endpointTotals).map(x=>x.requests).sort((a,b)=>a-b)).toEqual([3,7,10]);expect(r.removedRows).toHaveLength(1);expect(r.removedRows[0].reason).toBe('EXPLICIT_OVERLAP');expect(r.verifiedSuccessfulLowerBound).toBe(0);expect(r.finalQuotaProofEligible).toBe(false);expect(r.quotaMet).toBe(false);expect(r.curatedGameEvidenceRows).toBe(0)})
 it('never automatically collapses same-timestamp same-endpoint legitimate rows',()=>{const s=clean();s.rows.push({...s.rows[0],source_row:2});expect(importActivity(s).observed.requests).toBe(2)})
 it('identical stable row identity is counted once',()=>{const s=clean();s.rows.push(structuredClone(s.rows[0]));expect(importActivity(s).observed.requests).toBe(1)})
 it('conflicting stable identity quarantines both rather than arbitrary retention',()=>{const s=clean();s.rows.push({...s.rows[0],displayed_credits:2});const r=importActivity(s);expect(r.observed.requests).toBe(0);expect(r.quarantined).toHaveLength(2)})
 it('explicit overlap contradictions quarantine all members',()=>{const s=clean();s.rows[0].explicit_overlap_group='GROUP';s.rows.push({...s.rows[0],source_row:2,status:'FAILURE'});expect(importActivity(s).quarantined).toHaveLength(2)})
 it('transitive explicit overlap plus stable identity never double counts',()=>{const s=clean();s.rows[0].explicit_overlap_group='GROUP';s.rows.push({...s.rows[0],source_row:2},{...s.rows[0],source_row:2,explicit_overlap_group:null});const r=importActivity(s);expect(r.observed.requests).toBe(1);expect(r.removedRows).toHaveLength(2)})
 it.each(['2026-09-13T23:59:59Z','2026-09-28T00:00:00Z','2026-09-27T23:59:01Z','2026-09-18T00:57:09','2026-09-18T00:57:09-07:00','2026-02-30T00:00:00Z'])('quarantines out-of-window/ambiguous time %s',time=>{const s=clean();s.rows[0].observed_at_utc=time;expect(importActivity(s).observed.requests).toBe(0);expect(importActivity(s).quarantined).toHaveLength(1)})
 it.each(['2026-09-14T00:00:00Z','2026-09-27T23:59:00Z'])('admits exact conservative boundary %s',time=>{const s=clean();s.rows[0].observed_at_utc=time;expect(importActivity(s).observed.requests).toBe(1)})
 it.each(CLASSES)('preserves evidence class %s without implicit verification',source_class=>{const s=clean();s.source_class=source_class;if(source_class==='PROJECT_LEDGER_SUMMARY'){expect(()=>importActivity(s)).toThrow('CONTRADICTION');return}const r=importActivity(s);expect(r.sourceBindings[0].sourceClass).toBe(source_class);expect(r.finalQuotaProofEligible).toBe(false)})
 it.each(PROJECTS)('separately classifies %s and never admits game evidence',project_class=>{const s=clean();s.project_class=project_class;const r=importActivity(s);expect(r.projectClass).toBe(project_class);expect(r.curatedGameEvidenceRows).toBe(0)})
 it('even 1,000 Principal rows and extrapolation never become proof',()=>{const s=clean();s.rows=Array.from({length:1000},(_,i)=>({...s.rows[0],source_row:i+1}));const r=importActivity(s,{estimatedProjections:{requestsPerDay:200,creditsPerDay:300,days:14,assumption:'SYNTHETIC_PLANNING'}});expect(r.quotaMet).toBe(false);expect(r.finalQuotaProofEligible).toBe(false);expect(r.ESTIMATED.projectedRequests).toBe(2800);expect(r.ESTIMATED.proofEligible).toBe(false)})
 it('verified source label or asserted proof flag alone is not external verification',()=>{const s=clean();s.source_class='VERIFIED_PORTAL_EXPORT';s.project_class='TRACE_ESCAPE';s.final_quota_proof_eligible=true;expect(importActivity(s).verifiedSuccessfulLowerBound).toBe(0);expect(importActivity(s).finalQuotaProofEligible).toBe(false)})
 it('ESTIMATED source rows appear only as estimates, never observed requests',()=>{const s=clean();s.source_class='ESTIMATED';const r=importActivity(s);expect(r.observed.requests).toBe(0);expect(r.unverifiedObservedRequests).toBe(0);expect(r.ESTIMATED.rowBasedEstimates.requests).toBe(1);expect(r.ESTIMATED.proofEligible).toBe(false)})
 it('hash-bound independent verification produces lower bound, not automatic CPP eligibility',()=>{const s=clean();s.source_class='VERIFIED_PORTAL_EXPORT';const o={verificationBindings:[binding(s)]};expect(importActivity(s,o).verifiedSuccessfulLowerBound).toBe(1);expect(importActivity(s,o).finalQuotaProofEligible).toBe(false);expect(importActivity(s,{...o,submissionApplicability:applicable}).finalQuotaProofEligible).toBe(true)})
 it('verified successful TRACE rows meet quota only at exact floor, failures/credits do not inflate it',()=>{const s=clean();s.source_class='VERIFIED_PROVIDER_ACTIVITY';s.project_class='TRACE_ESCAPE';s.rows=Array.from({length:1000},(_,i)=>({...s.rows[0],source_row:i+1,displayed_credits:5}));const o={verificationBindings:[binding(s)]};const r=importActivity(s,o);expect(r.verifiedSuccessfulLowerBound).toBe(1000);expect(r.observed.credits).toBe(5000);expect(r.providerRequestFloorEvidenced).toBe(true);expect(r.quotaMet).toBe(false);expect(importActivity(s,{...o,submissionApplicability:applicable}).quotaMet).toBe(true)})
 it('counts failures as observed requests, not conservative verified successful lower bound',()=>{const s=clean();s.rows[0].status='FAILURE';expect(importActivity(s).observed).toMatchObject({requests:1,successes:0,failures:1})})
 it.each(['source_row','status','endpoint'])('quarantines malformed %s without silent counting',key=>{const s=clean();s.rows[0][key]=null;expect(importActivity(s).observed.requests).toBe(0)})
 it('status contradiction is quarantined',()=>{const s=clean();s.rows[0].http_status=500;expect(importActivity(s).quarantined[0].reason).toBe('STATUS_CONTRADICTION')})
 it('CSV sample accounting matches JSON and quoted fields are parsed without coercion',()=>{const s=sample(),headers=Object.keys(s.rows[0]),csv=headers.join(',')+'\r\n'+s.rows.map(r=>headers.map(k=>r[k]??'').join(',')).join('\r\n');const p=parseCSV(csv,{schema_version:s.schema_version,source_id:s.source_id,source_class:s.source_class,project_class:s.project_class,measurement_class:s.measurement_class,source_artifact:s.source_artifact,credit_semantics:s.credit_semantics});expect(importActivity(p).observed).toEqual(importActivity(s).observed);expect(parseCSV('a,b\n"line\nwith ""quote""",x',{}).rows[0].a).toBe('line\nwith "quote"')})
 it.each(['a,a\n1,2','a,b\n1','a,b\n"x','a,b\n"x"y,z'])('rejects malformed CSV %s',csv=>{expect(()=>parseCSV(csv,{})).toThrow()})
 it.each(['raw_body','response_body','payload','account_id','account_identity','api_key'])('rejects forbidden input key %s before import',key=>{const s=clean();s[key]='SYNTHETIC_FORBIDDEN';expect(()=>importActivity(s)).toThrow('PRIVACY')})
 it('rejects private absolute paths and email without opening targets',()=>{expect(()=>privacyBoundary('/'+['home','HypotheticalPrivateUser','data.json'].join('/'))).toThrow('PRIVACY');expect(()=>privacyBoundary('synthetic@example.invalid')).toThrow('PRIVACY')})
 it('rejects unknown business payload fields even when their names are not a secret pattern',()=>{const s=clean();s.unrelated_business_values={foo:'bar'};expect(()=>importActivity(s)).toThrow('SOURCE_SHAPE')})
 it('rejects business data hidden inside optional source context',()=>{const s=clean();s.derived_summary.unrelated_business_values={foo:'bar'};expect(()=>importActivity(s)).toThrow('CONTEXT_SHAPE')})
 it('is deterministic under source row order including explicit overlap',()=>{const s=sample(),r=importActivity(s);s.rows.reverse();const b=importActivity(s);expect(b.observed).toEqual(r.observed);expect(b.endpointTotals).toEqual(r.endpointTotals)})
})
describe('S2 endpoint-independent RC, not Lane C freeze',()=>{
 it('maps the current accepted 25 once with exact provenance and no new count',()=>{const c=compileCorpus(input());expect(c.concepts).toHaveLength(25);c.concepts.forEach(x=>expect(validateConcept(x)).toBe(true));expect(c.newRequests).toBe(0);expect(c.exactTruthSeparation.firstExactFalsifierUtc).toBe('2023-03-13T11:38:11Z');expect(c.LaneCActive).toBe(false)})
 it('compiles byte-identical deterministic IDs/hashes twice',()=>{expect(compileCorpus(input())).toEqual(compileCorpus(input()))})
 it.each([{freeze:true},{activateLaneC:true},{runtimeProviderCalls:1}])('rejects authority escalation %j',flags=>{expect(()=>compileCorpus(input(),flags)).toThrow('NO_FREEZE');expect(()=>assertCandidateOnly(flags)).toThrow('NO_FREEZE')})
 it('rejects duplicate/count padding even after resealing the input',()=>{const x=input();x.rows.push(structuredClone(x.rows[0]));expect(()=>compileCorpus(reseal(x))).toThrow('EXACT_ADMITTED')})
 it('rejects CPP as corpus evidence',()=>{const x=input();x.rows[0].project_class='CPP';expect(()=>compileCorpus(reseal(x))).toThrow('EXACT_ADMITTED')})
 it('rejects endpoint response-schema leakage even after resealing concept',()=>{const c=compileCorpus(input()).concepts[0];c.tokens_sent=[];const {id,...p}=c;const q=reseal(p);expect(()=>validateConcept({id:'CONCEPT.'+q.identity,...q})).toThrow('CLOSED_SCHEMA')})
 it('rejects nested endpoint-schema leakage',()=>{const c=compileCorpus(input()).concepts[0];c.provenance.tokens_sent=[];expect(()=>validateConcept(c)).toThrow('NESTED_SCHEMA_LEAK')})
 it('rejects contextual grade/time promotion',()=>{const c=compileCorpus(input()).concepts[0];c.evidenceGrade='EXACT';expect(()=>validateConcept(c)).toThrow('PROMOTION')})
 it('rejects truthy nonboolean cross-project applicability and unsafe credit overflow',()=>{expect(()=>importActivity(clean(),{separateProjectCountingResolved:'false'})).toThrow('OPTIONS_SHAPE');const s=clean();s.rows[0].displayed_credits=Number.MAX_SAFE_INTEGER;s.rows.push({...s.rows[0],source_row:2});expect(()=>importActivity(s)).toThrow('OVERFLOW')})
 it.each(['exactTruthAuthority','recursiveFrontierAuthority'])('rejects positive %s even after resealing',key=>{const c=compileCorpus(input()).concepts[0];c[key]=true;expect(()=>validateConcept(c)).toThrow('CLAIM_BOUNDARY')})
 it('rejects historical-negative overreach and contextual proof promotion',()=>{const c=compileCorpus(input()).concepts[0];c.coverage.supportsHistoricalNegative=true;expect(()=>validateConcept(c)).toThrow('CLAIM_BOUNDARY');c.coverage.supportsHistoricalNegative=false;c.zeroResultClass='NEGATIVE_EVIDENCE_SUPPORTED';expect(()=>validateConcept(c)).toThrow('NEGATIVE_OVERREACH')})
 it('preserves explicit UNKNOWN identity joins and exact response/request/public identities',()=>{const c=compileCorpus(input());expect(c.concepts.filter(x=>x.provenance.logicalRequestId===null)).toHaveLength(3);expect(c.concepts.every(x=>/^[a-f0-9]{64}$/.test(x.provenance.requestBodySha256)&&/^[a-f0-9]{64}$/.test(x.provenance.providerResponseSha256)&&x.provenance.publicCallId.startsWith('NQ5-'))).toBe(true)})
})
