import fs from 'node:fs'
import {describe,it,expect} from 'vitest'
import {derive} from '../../scripts/nq5-s2-r1/generate.mjs'
import {importActivity,identity,parseCSV,sha} from '../../scripts/nq5-s2/activity.mjs'
const sample=()=>structuredClone(derive().inputs['PRINCIPAL_SAMPLE_TRANSFORMED.json'])
const cpp=()=>structuredClone(derive().inputs['CPP_SAFE_TRANSFORMED_INPUT.json'])
const small=()=>{const x=sample();x.rows=x.rows.slice(0,1);return x}
const verified=()=>{const x=small();x.source_id='SYNTHETIC_VERIFIED';x.source_class='VERIFIED_PROVIDER_ACTIVITY';x.project_class='TRACE_ESCAPE';return x}
const bind=x=>({sourceId:x.source_id,sourceIdentity:identity(x),sourceArtifactSha256:x.source_artifact.sha256,sourceArtifactBytes:x.source_artifact.bytes,reviewIdentity:'a'.repeat(64),independentlyVerified:true})
describe('S2-R1 explicit measurements and false-success closure',()=>{
 it('imports only safe CPP logical observations, never requests or zero-imputed credits',()=>{const r=importActivity(cpp());expect(r.logicalOperations).toMatchObject({distinctLogicalOperationLowerBound:3772,pureLiveControlledSuccessOperations:3758,operationsContainingLiveControlledSuccess:3760,unknownCreditOperations:3772,exactHttpAttemptCount:null,exactHttpResponseCount:null,exactBilledCredits:null,verifiedProviderRequestRows:0});expect(r.observed).toEqual({requests:0,successes:0,failures:0,credits:null});expect(r.quarantined).toHaveLength(0);expect(r.verifiedSuccessfulLowerBound).toBe(0);expect(r.providerRequestFloorEvidenced).toBe(false);expect(r.sameAccountSubmissionApplicability).toBe('UNRESOLVED');expect(r.finalQuotaClaimable).toBe(false);expect(r.curatedGameEvidenceRows).toBe(0)})
 it('rejects the independently reproduced old 3772-row syntactic conversion',()=>{const x=cpp();delete x.measurement_class;expect(()=>importActivity(x)).toThrow('MEASUREMENT_REQUIRED');x.measurement_class='PROVIDER_REQUEST_ROW';expect(()=>importActivity(x)).toThrow('CONTRADICTION')})
 it('quarantines a provider row relabeled inside logical evidence',()=>{const x=cpp();x.rows=x.rows.slice(0,1);x.rows[0].measurement_class='PROVIDER_REQUEST_ROW';const r=importActivity(x);expect(r.logicalOperations.distinctLogicalOperationLowerBound).toBe(0);expect(r.observed.requests).toBe(0);expect(r.quarantined).toHaveLength(1)})
 it('quarantines unknown logical credits rewritten as zero',()=>{const x=cpp();x.rows=x.rows.slice(0,1);x.rows[0].displayed_credits=0;const r=importActivity(x);expect(r.quarantined).toHaveLength(1);expect(r.logicalOperations.distinctLogicalOperationLowerBound).toBe(0)})
 it('rejects a source claiming conservative commitments are displayed/billed credits',()=>{const x=cpp();x.credit_semantics='DISPLAYED_CREDITS';expect(()=>importActivity(x)).toThrow('CONTRADICTION');x.credit_semantics='UNKNOWN';x.planning_commitment.metric='EXACT_BILLED_CREDITS';expect(()=>importActivity(x)).toThrow('COMMITMENT')})
 it('retains non-billed commitments separately from exact request/credit totals',()=>{const r=importActivity(cpp());expect(r.planningCommitments[0]).toMatchObject({completeDaysConservativeCommittedCredits:24124,partialDayConservativeCommittedCredits:299,metric:'NON_BILLED_CONSERVATIVE_PLANNING_COMMITMENT'});expect(r.displayedCreditAccounting.exactBilledCredits).toBe(null)})
 it('nullable provider credits preserve rows, known total and unknown count independently',()=>{const x=small();x.rows.push({...x.rows[0],source_row:99,displayed_credits:null});const r=importActivity(x);expect(r.observed.requests).toBe(2);expect(r.observed.credits).toBe(null);expect(r.displayedCreditAccounting).toMatchObject({knownCreditTotal:x.rows[0].displayed_credits,knownCreditRows:1,unknownCreditRows:1})})
 it('UNKNOWN provider-credit semantics reject any numeric zero row rather than impute',()=>{const x=small();x.credit_semantics='UNKNOWN';x.rows[0].displayed_credits=0;expect(importActivity(x).quarantined).toHaveLength(1)})
 it('JSON/CSV nullable-credit parity and explicit UNKNOWN lexeme',()=>{const x=small();x.rows[0].displayed_credits=null;const {rows,...meta}=x,headers=Object.keys(rows[0]),csv=headers.join(',')+'\n'+headers.map(k=>rows[0][k]??'UNKNOWN').join(',');const parsed=parseCSV(csv,meta);expect(importActivity(parsed).observed).toEqual(importActivity(x).observed);expect(parsed.rows[0].displayed_credits).toBe(null)})
 it('source name alone cannot verify provider rows',()=>{expect(importActivity(verified()).independentlyVerifiedProviderRequests).toBe(0)})
 it('contradictory unverified receipt cannot establish verified proof',()=>{const x=verified(),b=bind(x);x.review_receipt={identity:b.reviewIdentity,disposition:'UNVERIFIED'};expect(()=>importActivity(x,{verificationBindings:[bind(x)]})).toThrow('DISPOSITION_CONTRADICTION')})
 it('estimated logical rows cannot become an observed operation lower bound',()=>{const x=cpp();x.source_class='ESTIMATED';expect(()=>importActivity(x)).toThrow('NOT_LOGICAL_OBSERVATION')})
 it.each(['sourceArtifactSha256','sourceArtifactBytes','sourceIdentity'])('rejects verification mismatch %s',key=>{const x=verified(),b=bind(x);b[key]=key==='sourceArtifactBytes'?x.source_artifact.bytes+1:'f'.repeat(64);expect(()=>importActivity(x,{verificationBindings:[b]})).toThrow('MISMATCH')})
 it('retains original artifact, transformed identity, project/evidence and review receipt identity',()=>{const x=verified(),b=bind(x),r=importActivity(x,{verificationBindings:[b]});expect(r.sourceBindings[0]).toMatchObject({originalArtifact:x.source_artifact,transformedInputIdentity:identity(x),reviewIdentity:b.reviewIdentity,reviewDisposition:'VERIFIED_PROVIDER_REQUEST_EVIDENCE',projectClass:'TRACE_ESCAPE',sourceClass:'VERIFIED_PROVIDER_ACTIVITY'})})
 it('missing artifact bytes cannot establish independently verified provider proof',()=>{const x=verified();x.source_artifact.bytes=null;expect(importActivity(x,{verificationBindings:[bind(x)]}).verifiedSuccessfulLowerBound).toBe(0)})
 it('unverified ancillary observations and logical operations never erase a verified proof subset',()=>{const x=verified(),r=importActivity([x,sample(),cpp()],{verificationBindings:[bind(x)]});expect(r.independentlyVerifiedProviderRequests).toBe(1);expect(r.verifiedSuccessfulLowerBound).toBe(1);expect(r.unverifiedObservedRequests).toBe(20);expect(r.logicalOperations.distinctLogicalOperationLowerBound).toBe(3772);expect(r.sameAccountSubmissionApplicability).toBe('UNRESOLVED')})
 it('even contradictory ancillary overlap cannot poison verified lower bound',()=>{const x=verified(),y=small();x.rows[0].explicit_overlap_group='SYNTHETIC_JOIN';y.rows[0].explicit_overlap_group='SYNTHETIC_JOIN';y.rows[0].status='FAILURE';const r=importActivity([x,y],{verificationBindings:[bind(x)]});expect(r.observed.requests).toBe(1);expect(r.verifiedSuccessfulLowerBound).toBe(1);expect(r.quarantined[0].reason).toBe('ANCILLARY_CONFLICT_WITH_VERIFIED_PROOF_ROW')})
 it('verified floor alone does not resolve submission applicability or permit quota claim',()=>{const x=verified();x.rows=Array.from({length:1000},(_,i)=>({...x.rows[0],source_row:i+1}));const r=importActivity(x,{verificationBindings:[bind(x)],separateProjectCountingResolved:true});expect(r.providerRequestFloorEvidenced).toBe(true);expect(r.sameAccountSubmissionApplicability).toBe('UNRESOLVED');expect(r.finalQuotaProofEligible).toBe(false);expect(r.finalQuotaClaimable).toBe(false);expect(r.quotaMet).toBe(false)})
 it('aggregate-only bounded counts do not synthesize requests, operations or proof rows',()=>{const x=small();x.measurement_class='AGGREGATE_ONLY';x.source_class='PROJECT_LEDGER_SUMMARY';x.credit_semantics='UNKNOWN';x.rows=[];delete x.derived_summary;x.bounded_counts={measurement:'PROJECT_LOGICAL_OPERATION',lowerBound:3772,upperBound:null};const r=importActivity(x);expect(r.observed.requests).toBe(0);expect(r.logicalOperations.distinctLogicalOperationLowerBound).toBe(0);expect(r.aggregateOnlyEvidence[0].boundedCounts.lowerBound).toBe(3772);x.rows=[sample().rows[0]];expect(()=>importActivity(x)).toThrow('SYNTHESIZE')})
 it('uses scheduled fingerprint UTC, not terminal arrival timestamp',()=>{const x=cpp();x.rows=x.rows.slice(0,1);x.rows[0].scheduled_utc='2026-09-14T00:05:00Z';expect(importActivity(x).quarantined[0].reason).toBe('SCHEDULED_FINGERPRINT_UTC_MISMATCH')})
 it('deduplicates operation fingerprints without request synthesis',()=>{const x=cpp();x.rows=x.rows.slice(0,1);x.rows.push({...x.rows[0]});const r=importActivity(x);expect(r.logicalOperations.distinctLogicalOperationLowerBound).toBe(1);expect(r.removedRows).toHaveLength(1)})
 it('rejects ambiguous and orphan review bindings',()=>{const x=verified();expect(()=>importActivity(x,{verificationBindings:[bind(x),bind(x)]})).toThrow('AMBIGUOUS');expect(()=>importActivity(sample(),{verificationBindings:[bind(x)]})).toThrow('ORPHAN')})
 it('deterministic generation preserves exact accepted sample, corpus and all holds',()=>{const a=derive(),b=derive();expect(a).toEqual(b);expect(a.reports['MERIDIAN_ACCOUNT_ACTIVITY_REPORT.json'].observed).toEqual({requests:20,successes:20,failures:0,credits:32});expect(a.corpus.identity).toBe('64807a4cbfb7b5ea1fb4931c2b94731c9e8c6e4f7b751fc609f3ce1c45df5e53');expect(Object.values(a.reports['S2_R1_DECISION_RECEIPT.json'].authorities).every(x=>x===false)).toBe(true)})
 it('binds safe original CPP CSV bytes without opening original full CPP archive',()=>{const x=cpp(),b=fs.readFileSync('docs/source/execution-s2-r1/CPP_EVIDENCE/CPP_ELIGIBLE_WINDOW_LOGICAL_OPERATIONS_LOWER_BOUND.csv');expect(sha(b.toString().replace(/\r?\n/g,'\r\n'))).toBe(x.source_artifact.sha256);expect(x.source_artifact.bytes).toBe(737652)})
})
