import { describe, expect, it, vi } from 'vitest'
import { renderToStaticMarkup } from 'react-dom/server'
import { createElement } from 'react'
import scenario from '../../public/scenarios/euler-2023-false-exit/scenario.json'
import graph from '../../public/scenarios/euler-2023-false-exit/evidence-graph.json'
import candidate from '../../artifacts/g6p-s3/REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json'
import synthetic from '../../artifacts/g6p-s3/REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json'
import { buildFrozenFixture, syntheticFixture } from '../../src/investigation/fixture'
import { createInvestigationState, investigationReducer, availableCards } from '../../src/investigation/state'
import { controllerCorpus, canonicalFixture } from '../../src/controller/corpus/input'
import { deriveBlueprint } from '../../src/controller/foundation/blueprint'
import { VIEWPORT, validateViewport, validateScale, validateIntake, verifyIntakeBytes } from '../../src/controller/foundation/contracts.mjs'
import { admitFrozenCorpusCandidate, admitSyntheticCorpusFixture } from '../../src/investigation/corpus-seam/authority.mjs'
import { createCanonicalView, createSyntheticView, browse, type CorpusView } from '../../src/investigation/semantic-ux/model'
import { CorpusPresentation } from '../../src/app/corpus-presentation/CorpusPresentation'
import { testArtIndex, refreshTestArtIdentities } from '../fixtures/s5/art-index'

const fixture=buildFrozenFixture(scenario as Parameters<typeof buildFrozenFixture>[0],graph)
const step= (s: ReturnType<typeof createInvestigationState>,c: Parameters<typeof investigationReducer>[2])=>investigationReducer(fixture,s,c)
const earned=()=>step(createInvestigationState(fixture),{type:'EARN_ACCESS'})
const dispatch=(s: ReturnType<typeof earned>)=>step(step(s,{type:'REVIEW_RECEIPT'}),{type:'DISPATCH',path:'TERMINAL'})
const v=()=>JSON.parse(JSON.stringify(VIEWPORT)) as Record<string,unknown>
describe('S5 independently bounded false-success and foundation contracts',()=>{
 it('viewport contract is recursively immutable, including nested rectangles',()=>{expect(Object.isFrozen(VIEWPORT)).toBe(true);for(const value of Object.values(VIEWPORT))if(value && typeof value==='object')expect(Object.isFrozen(value)).toBe(true)})
 it('locks the whole 480x270 game, not merely the 480x180 room',()=>{expect(validateViewport(VIEWPORT)).toBe(true);const x=v();x.viewport={width:480,height:180};expect(()=>validateViewport(x)).toThrow()})
 it('rejects fractional/smoothed display scaling and separately scaled actors',()=>{expect(validateScale({scale:2,nearestNeighbor:true,actorIndependentScale:1})).toBe(true);for(const x of [{scale:2.5,nearestNeighbor:true,actorIndependentScale:1},{scale:2,nearestNeighbor:false,actorIndependentScale:1},{scale:2,nearestNeighbor:true,actorIndependentScale:2}])expect(()=>validateScale(x)).toThrow()})
 it('rejects baked raster text/evidence and a room-only terminal',()=>{for(const k of ['bakedText','bakedEvidence','bakedInteractiveState']){const x=v();x[k]=true;expect(()=>validateViewport(x)).toThrow()}const x=v();x.terminalReplaces='ROOM_ONLY';expect(()=>validateViewport(x)).toThrow()})
 it('canonical gameplay requires full accepted fixture equality, not a forged ID/mode',async()=>{expect(canonicalFixture(fixture)).toBe(true);expect((await controllerCorpus(fixture)).total).toBe(25);const f=structuredClone(fixture);f.records[0]!.summary='SYNTHETIC ALTERATION';expect(canonicalFixture(f)).toBe(false);await expect(controllerCorpus(f)).rejects.toThrow('NO_CANONICAL_AUTHORITY');expect((await controllerCorpus(syntheticFixture(fixture))).origin).toBe('synthetic')})
 it('keeps synthetic origin copy honest on all three surfaces',async()=>{const view=await createSyntheticView(await admitSyntheticCorpusFixture(synthetic));for(const surface of ['CASE','RESULTS','EXPLORE'] as const){const html=renderToStaticMarkup(createElement(CorpusPresentation,{view,mode:'PLAIN_LIST',surface}));expect(html).not.toContain('Search accepted display text');expect(html).not.toContain('Browse accepted questions');expect(html).not.toContain('Explore the accepted corpus');expect(html).toContain('Search synthetic example text')}})
 it('rejects canonical/synthetic cross-kind tokens and forged structural views',async()=>{const c=await admitFrozenCorpusCandidate(candidate),s=await admitSyntheticCorpusFixture(synthetic);await expect(createCanonicalView(s as unknown as typeof c)).rejects.toThrow();await expect(createSyntheticView(c as unknown as typeof s)).rejects.toThrow();expect(()=>browse({} as CorpusView)).toThrow()})
 for(const change of ['altered','dropped','added','quota-cpp'] as const) it('rejects '+change+' frozen membership',async()=>{const x=structuredClone(candidate);if(change==='altered')x.displayRecords[0]!.question='new';if(change==='dropped')x.displayRecords.pop();if(change==='added')x.displayRecords.push(x.displayRecords[0]!);if(change==='quota-cpp')x.displayRecords[0]!.question='CPP account quota row';await expect(admitFrozenCorpusCandidate(x)).rejects.toThrow()})
 it('executes every beat count and exact reducer proof without inventing STATE members',async()=>{const bp=await deriveBlueprint(),view=await controllerCorpus(fixture);expect(bp.semanticTotal).toBe(25);expect(bp.boundedNoMatches).toBe(7);for(const b of bp.beats){for(const [q,c] of [[b.acceptedCorpus.filterBefore,b.acceptedCorpus.before],[b.acceptedCorpus.filterAfter,b.acceptedCorpus.after]] as const){const replay=browse(view,q);expect(c.count).toBe(replay.visible);expect(c.displayIds).toEqual(replay.cards.map(x=>x.display.id))}}expect(bp.beats.find(b=>b.id==='LENS.STATE')!.acceptedCorpus.after.count).toBe(0);expect(bp.firstFalsifierUtc).toBe('2023-03-13T11:38:11Z');expect(bp.proofLayer.complete).toBe(true)})
 it('invented reported count fails exact local replay equality',async()=>{const view=await controllerCorpus(fixture);const actual=browse(view,{lens:'ACTIVITY'}).visible;expect(actual).toBe(10);const accept=(n:number)=>{if(n!==browse(view,{lens:'ACTIVITY'}).visible)throw Error('INVENTED_COUNT')};expect(()=>accept(actual+1)).toThrow('INVENTED_COUNT')})
 it('no undiscovered exact card, clue or source value can be staged',()=>{let s=earned();expect(availableCards(fixture,s).some(c=>c.id==='CARD.EXACT_RECEIPT')).toBe(false);s=step(s,{type:'STAGE_CARD',cardId:'CARD.EXACT_RECEIPT'});expect(s.error).toContain('not discovered');s=step(earned(),{type:'STAGE_CLUE',clueId:'CLUE.PROOF.'+fixture.proof.slots.LINK});expect(s.error).toContain('not been discovered');s=step(earned(),{type:'ADD_FILTER',filter:{field:'TRANSACTION',value:fixture.records.find(r=>r.id===fixture.proof.slots.LINK)!.transactionHash,origin:'PLAYER_FILTER',sourceId:'TEST'}});expect(s.error).toContain('not been discovered')})
 it('context/no-match IDs cannot fill exact slots',async()=>{const view=await controllerCorpus(fixture);for(const c of view.cards){const s=step(earned(),{type:'ASSEMBLE',slot:'LINK',recordId:c.display.id});expect(s.complete).toBe(false);expect(s.assembly.LINK).toBeUndefined()}})
 for(const journey of ['DIRECT_SOLVER','CURIOUS_EXPLORER','MISTAKEN_INVESTIGATOR'] as const)it('pure accepted '+journey+' has recoverable exact bounded ending',()=>{let s=step(earned(),{type:'COLLECT_CASE_FILE'});s=step(s,{type:'STAGE_CARD',cardId:'CARD.INCIDENT_DAI'});s=dispatch(s);if(journey==='MISTAKEN_INVESTIGATOR'){s=step(s,{type:'SELECT_RESULT',recordId:fixture.openingRecordId});s=step(s,{type:'STAGE_CARD',cardId:'CARD.FOLLOW_FORWARD'});s=dispatch(s);const pair=s.discoveredRecords.filter(id=>id!==fixture.openingRecordId).slice(0,2);s=step(s,{type:'COMPARE',recordId:pair[0]!});s=step(s,{type:'COMPARE',recordId:pair[1]!});s=step(s,{type:'THEORY',theory:'FIRST_TRAIL_STOPS_AT_FIRST_ENGINE'})}if(journey==='CURIOUS_EXPLORER'){s=step(s,{type:'STAGE_CARD',cardId:'CARD.STATE_CHANGE'});s=dispatch(s);expect(s.exactEventIds).toEqual([])}s=step(s,{type:'SELECT_RESULT',recordId:fixture.openingRecordId});s=step(s,{type:'STAGE_CARD',cardId:'CARD.FOLLOW_FORWARD'});s=dispatch(s);expect(s.candidateRouteResolved).toBe(true);s=step(s,{type:'SELECT_RESULT',recordId:fixture.proof.slots.LINK});s=step(s,{type:'STAGE_CARD',cardId:'CARD.EXACT_RECEIPT'});const guarded=step(s,{type:'DISPATCH',path:'TERMINAL'});expect(guarded.exactEventIds).toEqual([]);s=dispatch(s);expect(s.exactEventIds).toEqual(['EXACT.'+fixture.proof.slots.LINK]);if(journey==='MISTAKEN_INVESTIGATOR')expect(s.rejectedTheory?.firstContradiction).toBe(fixture.proof.slots.LINK);s=step(s,{type:'READ_BRANCH',branch:'SECOND'});for(const slot of ['AMOUNT','RECEIVER','LINK'] as const)s=step(s,{type:'ASSEMBLE',slot,recordId:fixture.proof.slots[slot]});expect(s.complete).toBe(true);const reset=step(s,{type:'RESET_CASE'});expect(reset.access).toBe(true);expect(reset.discoveredClues).toEqual(fixture.startingClueIds);expect(reset.result).toBeNull();expect(reset.complete).toBe(false)})
 it('no final optional title/density/production clip/filename is silently bound',async()=>{const bp=await deriveBlueprint();expect(bp.finalTitle).toBe('LATE_BOUND');expect(bp.finalDialogueDensity).toBe('LATE_BOUND');expect(bp.artClipIdsAndFilenames).toBe('LATE_BOUND');for(const b of bp.beats)expect(b.performance.productionClipIds).toBe('LATE_BOUND')})
 it('intake metadata supports order/timing/static fallback without granting approval',()=>{expect(validateIntake(testArtIndex())).toBe(true)})
 it('renaming required content or lying about its declared hash does not evade duplicate detection',()=>{const x=testArtIndex();x.capabilities.push({...x.capabilities[0]!,id:'TEST_RENAMED',contentIdentity:'d'.repeat(64)});expect(()=>validateIntake(x)).toThrow('CAPABILITY_CONTENT_IDENTITY');refreshTestArtIdentities(x);expect(()=>validateIntake(x)).toThrow('DUPLICATE_REQUIRED_CONTENT')})
 for(const change of ['malformed','duplicate-asset','unsafe-path','bad-order','bad-baseline','duplicate-required','derivative-approval'] as const)it('rejects art intake '+change,()=>{const x=testArtIndex();if(change==='malformed')Object.assign(x,{extra:true});if(change==='duplicate-asset')x.assets.push(x.assets[0]!);if(change==='unsafe-path')x.assets[0]!.path='../actor.png';if(change==='bad-order')x.clips[0]!.frames[0]!.order=7;if(change==='bad-baseline')x.assets[0]!.exclusiveFootBaseline=83;if(change==='duplicate-required')x.capabilities.push({...x.capabilities[0]!,id:'TEST_DUPLICATE'});if(change==='derivative-approval'){x.assets[0]!.approvalReceiptId='TEST_APPROVAL';x.approvalReceipts.push({id:'TEST_APPROVAL',assetOrClipId:x.assets[0]!.id,version:'OLDER_VERSION',sha256:x.assets[0]!.sha256,status:'USER_APPROVED_EXACT_VERSION',authority:'PRINCIPAL'})}expect(()=>validateIntake(x)).toThrow()})
 it('intake exact byte/member hashes fail closed on tamper or extra asset',async()=>{const x=testArtIndex();const bytes=new Uint8Array([1,2,3]);x.assets[0]!.sha256=Buffer.from(await crypto.subtle.digest('SHA-256',bytes)).toString('hex');refreshTestArtIdentities(x);await expect(verifyIntakeBytes(x,{'TEST_actor.png':bytes})).resolves.toBe(true);await expect(verifyIntakeBytes(x,{'TEST_actor.png':new Uint8Array([1,2,4])})).rejects.toThrow('ARCHIVE_HASH');await expect(verifyIntakeBytes(x,{'TEST_actor.png':bytes,'extra.png':bytes})).rejects.toThrow('MEMBER_SET')})
 it('all local admission/filter/blueprint rendering is transport-free',async()=>{const trap=vi.fn(()=>{throw Error('FORBIDDEN')});for(const key of ['fetch','XMLHttpRequest','WebSocket','EventSource'])vi.stubGlobal(key,trap);try{const view=await controllerCorpus(fixture);browse(view,{groupBy:'lens'});await deriveBlueprint();expect(trap).not.toHaveBeenCalled()}finally{vi.unstubAllGlobals()}})
})
