import {describe,it,expect,vi} from 'vitest'
import scenario from '../../public/scenarios/euler-2023-false-exit/scenario.json'
import graph from '../../public/scenarios/euler-2023-false-exit/evidence-graph.json'
import candidate from '../../artifacts/g6p-s3/REPORTS/TE_IFACE_CORPUS_FINAL_CANDIDATE.json'
import examples from '../../artifacts/g6p-s3/REPORTS/SYNTHETIC_SEMANTIC_FIXTURE.json'
import {buildFrozenFixture,syntheticFixture} from '../../src/investigation/fixture'
import {createInvestigationState,investigationReducer,restoreInvestigation,exportLocalSave,fixtureOrigin,type InvestigationState,type Command} from '../../src/investigation/state'
import {canonicalFixture,controllerCorpus} from '../../src/controller/corpus/input'
import {admitFrozenCorpusCandidate,admitSyntheticCorpusFixture} from '../../src/investigation/corpus-seam/authority.mjs'
import {createCanonicalView,createSyntheticView} from '../../src/investigation/semantic-ux/model'
import type {CaseFixture} from '../../src/investigation/contracts'
const hero=buildFrozenFixture(scenario as Parameters<typeof buildFrozenFixture>[0],graph),synthetic=syntheticFixture(hero)
function solve(f:CaseFixture):InvestigationState {let s=createInvestigationState(f);const commands:Command[]=[{type:'EARN_ACCESS'},{type:'COLLECT_CASE_FILE'},{type:'STAGE_CARD',cardId:'CARD.INCIDENT_DAI'},{type:'REVIEW_RECEIPT'},{type:'DISPATCH',path:'TERMINAL'},{type:'SELECT_RESULT',recordId:f.openingRecordId},{type:'STAGE_CARD',cardId:'CARD.FOLLOW_FORWARD'},{type:'REVIEW_RECEIPT'},{type:'DISPATCH',path:'TERMINAL'},{type:'READ_BRANCH',branch:'SECOND'},{type:'SELECT_RESULT',recordId:f.proof.slots.LINK},{type:'STAGE_CARD',cardId:'CARD.EXACT_RECEIPT'},{type:'REVIEW_RECEIPT'},{type:'DISPATCH',path:'TERMINAL'},...(['AMOUNT','RECEIVER','LINK'] as const).map(slot=>({type:'ASSEMBLE' as const,slot,recordId:f.proof.slots[slot]}))];for(const c of commands)s=investigationReducer(f,s,c);return s}
describe('S6-R1-RES1 origin boundary',()=>{
 for(const f of [hero,synthetic])it('positive complete/save/restore '+f.mode,()=>{const s=solve(f);expect(s.complete).toBe(true);expect(s.announcement).toContain(f.proof.conclusion);expect(restoreInvestigation(f,exportLocalSave(s))).toEqual(s);expect(s.fixtureMode).toBe(f.mode);expect(s.fixtureOrigin).toBe(fixtureOrigin(f))})
 for(const [target,foreign] of [[hero,synthetic],[synthetic,hero]] as const)for(const command of [{type:'EARN_ACCESS'},{type:'HINT',tier:'DIRECT_HINT'},{type:'ASSEMBLE',slot:'LINK',recordId:foreign.proof.slots.LINK}] as Command[])it('rejects foreign '+foreign.mode+' before '+command.type,()=>{const s=solve(foreign),snapshot=structuredClone(s);const next=investigationReducer(target,s,command);expect(next).toEqual(createInvestigationState(target));expect(next.commands).toEqual([]);expect(next.exactEventIds).toEqual([]);expect(next.discoveredRecords).toEqual([]);expect(next.discoveredClues).toEqual([]);expect(next.assembly).toEqual({});expect(next.complete).toBe(false);expect(next.announcement).not.toContain(foreign.proof.conclusion);expect(s).toEqual(snapshot)})
 for(const [target,foreign] of [[hero,synthetic],[synthetic,hero]] as const)for(const spoof of ['id','mode','id-and-mode','marker-only'])it('rejects state '+spoof+' spoof '+foreign.mode,()=>{const s=solve(foreign);if(spoof.includes('id'))s.fixtureId=target.id;if(spoof.includes('mode'))s.fixtureMode=target.mode;if(spoof==='marker-only')s.fixtureOrigin=fixtureOrigin(target);expect(investigationReducer(target,s,{type:'EARN_ACCESS'})).toEqual(createInvestigationState(target))})
 for(const [target,foreign] of [[hero,synthetic],[synthetic,hero]] as const)for(const spoof of ['id','mode','id-and-mode','marker-only','all-origin-fields'])it('rejects relabeled save '+spoof+' '+foreign.mode,()=>{const save=JSON.parse(exportLocalSave(solve(foreign)));if(spoof.includes('id')||spoof==='all-origin-fields')save.fixtureId=target.id;if(spoof.includes('mode')||spoof==='all-origin-fields')save.fixtureMode=target.mode;if(spoof.includes('marker')||spoof==='all-origin-fields')save.fixtureOrigin=fixtureOrigin(target);const next=restoreInvestigation(target,JSON.stringify(save));expect(next.complete).toBe(false);expect(next.exactEventIds).toEqual([]);expect(next.assembly).toEqual({});expect(next.announcement).not.toContain(target.proof.conclusion)})
 it('rejects legacy ID-only save rather than infer origin',()=>{const s=solve(hero);expect(restoreInvestigation(hero,JSON.stringify({fixtureId:hero.id,commands:s.commands}))).toEqual(createInvestigationState(hero))})
 for(const [target,foreign] of [[hero,synthetic],[synthetic,hero]] as const)it('rejects foreign identifiers even if all origin metadata rewritten '+foreign.mode,()=>{const s=solve(foreign);s.fixtureId=target.id;s.fixtureMode=target.mode;s.fixtureOrigin=fixtureOrigin(target);expect(investigationReducer(target,s,{type:'HINT',tier:'DIRECT_HINT'})).toEqual(createInvestigationState(target))})
 it('rejects open save envelope',()=>{const s=JSON.parse(exportLocalSave(solve(hero)));s.foreignOrigin='anything';expect(restoreInvestigation(hero,JSON.stringify(s))).toEqual(createInvestigationState(hero))})
 it('namespaces every record, proof and dependent result/exact reference',()=>{const ids=new Set(synthetic.records.map(r=>r.id)),heroIds=new Set(hero.records.map(r=>r.id));expect([...ids].some(id=>heroIds.has(id))).toBe(false);for(const id of [synthetic.openingRecordId,synthetic.secondRecordId,...Object.values(synthetic.proof.slots)])expect(ids.has(id)).toBe(true);for(const r of synthetic.records)for(const id of r.derivedFrom)expect(id).toMatch(/^SYNTHETIC_CAUSALITY_B\./);for(const c of synthetic.clues){for(const id of c.sourceRecordIds)expect(ids.has(id)).toBe(true);if(/^(RESULT|EXACT)\./.test(c.unlockEvent))expect(ids.has(c.unlockEvent.replace(/^(RESULT|EXACT)\./,''))).toBe(true)}expect(solve(synthetic).exactEventIds.every(id=>id.startsWith('EXACT.SYNTHETIC_CAUSALITY_B.RECORD.'))).toBe(true)})
 for(const slot of ['AMOUNT','RECEIVER','LINK'] as const)for(const id of [synthetic.proof.slots.LINK,'EXACT.'+synthetic.proof.slots.LINK,...examples.records.map(r=>r.id)])it('Hero rejects foreign '+slot+' / '+id,()=>{const state=solve(hero),before=structuredClone(state.assembly);const next=investigationReducer(hero,state,{type:'ASSEMBLE',slot,recordId:id});expect(next.assembly).toEqual(before);expect(next.exactEventIds).toEqual(state.exactEventIds);expect(next.error).toContain('required discovered exact evidence')})
 it('canonicalFixture rejects fixture-ID/mode spoof and controller admission',async()=>{const f=structuredClone(synthetic);f.id=hero.id;f.mode=hero.mode;expect(canonicalFixture(f)).toBe(false);await expect(controllerCorpus(f)).rejects.toThrow('NO_CANONICAL_AUTHORITY')})
 it('rejects synthetic token as canonical and canonical token as synthetic',async()=>{const c=await admitFrozenCorpusCandidate(candidate),s=await admitSyntheticCorpusFixture(examples);await expect(createCanonicalView(s as unknown as typeof c)).rejects.toThrow();await expect(createSyntheticView(c as unknown as typeof s)).rejects.toThrow()})
 it('origin and replay remain transport-free',()=>{const trap=vi.fn(()=>{throw Error('NETWORK_FORBIDDEN')});for(const n of ['fetch','XMLHttpRequest','WebSocket','EventSource'])vi.stubGlobal(n,trap);try{expect(solve(synthetic).complete).toBe(true);expect(restoreInvestigation(hero,exportLocalSave(solve(hero))).complete).toBe(true);expect(trap).not.toHaveBeenCalled()}finally{vi.unstubAllGlobals()}})
})
