import {describe,it,expect} from 'vitest'
import {deriveBlueprint,validatePreArchiveBeat} from '../../src/controller/foundation/blueprint'
describe('S6-R1 closed pre-archive blueprint',()=>{
 it('all42 semantic beats preserve exact proof/counts and late-bound fallback',async()=>{const b=await deriveBlueprint();expect(b.beats).toHaveLength(42);expect(b.semanticTotal).toBe(25);expect(b.boundedNoMatches).toBe(7);expect(b.proofLayer.complete).toBe(true);expect(b.proofLayer.exactVerified).toBe(true);expect(b.firstFalsifierUtc).toBe('2023-03-13T11:38:11Z');expect(b.beats.find(x=>x.id==='LENS.STATE')!.acceptedCorpus.after.count).toBe(0);for(const beat of b.beats){expect(validatePreArchiveBeat(beat)).toBe(true);expect(beat).not.toHaveProperty('requiredVisualCapability');for(const actor of [beat.performance.rook,beat.performance.arthur]){expect(actor.facing).toBe('LATE_BOUND');expect(actor.reducedMotion).toBe('STATIC_WITH_SEMANTIC_TEXT')}}})
 for(const direction of ['FRONT','LEFT','RIGHT','BACK'])it('rejects premature facing '+direction,async()=>{const b=structuredClone((await deriveBlueprint()).beats[0]!) as unknown as Record<string,unknown>;const p=b.performance as {rook:{facing:string}};p.rook.facing=direction;expect(()=>validatePreArchiveBeat(b)).toThrow('PREARCHIVE_BINDING_REJECTED')})
 for(const field of ['clipId','clipIds','frameId','frameIds','anchor','anchors','coordinates','durationMs','holdMs','timing','mirroring','transitionRecipe','productionFilename','objectFitCoordinates','requiredVisualCapability'])for(const location of ['beat','actor'])it('rejects '+location+' premature '+field,async()=>{const b=structuredClone((await deriveBlueprint()).beats[0]!) as unknown as Record<string,unknown>;if(location==='beat')b[field]='UNAPPROVED';else ((b.performance as Record<string,unknown>).rook as Record<string,unknown>)[field]='UNAPPROVED';expect(()=>validatePreArchiveBeat(b)).toThrow('PREARCHIVE_BINDING_REJECTED')})
 it('rejects actual production clip IDs despite placeholder field',async()=>{const b=structuredClone((await deriveBlueprint()).beats[0]!);b.performance.productionClipIds='CLIP.PREBOUND';expect(()=>validatePreArchiveBeat(b)).toThrow('PREARCHIVE_BINDING_REJECTED')})
 it('allows absent facing, never missing text/static fallback',async()=>{const b=structuredClone((await deriveBlueprint()).beats[0]!) as unknown as Record<string,unknown>;const actor=((b.performance as Record<string,unknown>).rook as Record<string,unknown>);delete actor.facing;expect(validatePreArchiveBeat(b)).toBe(true);delete actor.reducedMotion;expect(()=>validatePreArchiveBeat(b)).toThrow('PREARCHIVE_BINDING_REJECTED')})
 it('rejects nested frame binding in otherwise closed shape',async()=>{const b=structuredClone((await deriveBlueprint()).beats[0]!) as unknown as Record<string,unknown>;b.acceptedCorpus={...(b.acceptedCorpus as object),frameId:'FRAME.PREBOUND'};expect(()=>validatePreArchiveBeat(b)).toThrow('PREARCHIVE_BINDING_REJECTED')})
 it('rejects nonsemantic actor intention',async()=>{const b=structuredClone((await deriveBlueprint()).beats[0]!);b.performance.rook.intention='CLIP.PREBOUND';expect(()=>validatePreArchiveBeat(b)).toThrow('PREARCHIVE_BINDING_REJECTED')})
})
