import {readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {describe,it,expect} from 'vitest'
import {deriveBlueprint,validatePreArchiveBeat} from '../../src/controller/foundation/blueprint'
const fields=['clipId','clipIds','productionClipIds','filename','productionFilename','frameId','frameIds','frames','anchor','anchors','coordinate','coordinates','durationMs','duration','holdMs','hold','timing','timingMs','mirroring','mirror','transitionRecipe','transition','objectFit','objectFitCoordinates','requiredVisualCapability','facing']
const root=JSON.parse(readFileSync('artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.json','utf8')).beats[0]
type ObjectMap=Record<string,unknown>
const locations:Record<string,(b:ObjectMap)=>ObjectMap>={beat:b=>b,actor:b=>(b.performance as ObjectMap).rook as ObjectMap,acceptedCorpus:b=>b.acceptedCorpus as ObjectMap,nested:b=>(b.acceptedCorpus as ObjectMap).filterAfter as ObjectMap}
describe('RES2 closed recursive blueprint',()=>{
 for(const intention of [['INSPECT'],{toString:()=> 'INSPECT'},null,5])it('rejects coerced actor intention '+typeof intention,()=>{const b=structuredClone(root);b.performance.rook.intention=intention;expect(()=>validatePreArchiveBeat(b)).toThrow()})
 for(const [location,get] of Object.entries(locations))for(const field of fields)it('supplied matrix '+location+'.'+field,()=>{const b=structuredClone(root);get(b)[field]=field==='facing'?'LEFT':'UNAPPROVED.TEST_BINDING';expect(()=>validatePreArchiveBeat(b)).toThrow()})
 const nested:Record<string,(b:ObjectMap)=>ObjectMap>={filterBefore:b=>(b.acceptedCorpus as ObjectMap).filterBefore as ObjectMap,before:b=>(b.acceptedCorpus as ObjectMap).before as ObjectMap,after:b=>(b.acceptedCorpus as ObjectMap).after as ObjectMap,arthur:b=>(b.performance as ObjectMap).arthur as ObjectMap,performance:b=>b.performance as ObjectMap,optionalCopy:b=>b.optionalCopy as ObjectMap}
 for(const [location,get] of Object.entries(nested))for(const field of ['unknownObject','filename','transition','requiredVisualCapability','facing','productionClipIds','file_name','trans\u200bition','ＦＩＬＥＮＡＭＥ','object-fit','duration_ms'])it('expanded nested '+location+'.'+field,()=>{const b=structuredClone(root);get(b)[field]=location==='arthur'&&field==='facing'?'LEFT':location==='performance'&&field==='productionClipIds'?'BOUND': ['facing','productionClipIds'].includes(field)?'LATE_BOUND':{deeper:{filename:'FOREIGN'}};expect(()=>validatePreArchiveBeat(b)).toThrow()})
 for(const array of ['copyRefs','provenance','requiredClueIds','requiredCardIds'])it('closed array '+array,()=>{const b=structuredClone(root);b[array].filename='FOREIGN';expect(()=>validatePreArchiveBeat(b)).toThrow()})
 it('copy refs have closed authoritative shapes',()=>{const b=structuredClone(root);b.copyRefs.push({copyId:'TEST',status:'BINDING_ACCEPTED_REQUIRED_CONTENT_MECHANICS_NOT_FINAL_DIALOGUE_DENSITY',nested:{filename:'FOREIGN'}});expect(()=>validatePreArchiveBeat(b)).toThrow()})
 for(const key of ['displayIds','questionIds'])it('count array nested object '+key,()=>{const b=structuredClone(root);b.acceptedCorpus.before[key]=[{filename:'FOREIGN'}];expect(()=>validatePreArchiveBeat(b)).toThrow()})
 it('count type and vector lengths validated',()=>{const b=structuredClone(root);b.acceptedCorpus.before.count=-1;expect(()=>validatePreArchiveBeat(b)).toThrow()})
 it('filter primitive shapes validated',()=>{const b=structuredClone(root);b.acceptedCorpus.filterAfter.subjectId={filename:'FOREIGN'};expect(()=>validatePreArchiveBeat(b)).toThrow()})
 it('authorized placeholders may be absent only in approved locations',()=>{const b=structuredClone(root);delete b.performance.rook.facing;delete b.performance.arthur.facing;delete b.performance.productionClipIds;expect(validatePreArchiveBeat(b)).toBe(true);b.acceptedCorpus.facing='LATE_BOUND';expect(()=>validatePreArchiveBeat(b)).toThrow()})
 it('governed exact byte hash and all42 derived beats preserved',async()=>{const bytes=readFileSync('artifacts/g6p-s5/REPORTS/MVP_BLUEPRINT.json');expect(createHash('sha256').update(bytes).digest('hex')).toBe('397660b78184a697e21925220287fc1087f742d7f0cef572d0dc040f1f46587a');const bp=await deriveBlueprint();expect(JSON.stringify(bp,null,2)+'\n').toBe(bytes.toString());expect(bp.beats).toHaveLength(42);bp.beats.forEach(b=>expect(validatePreArchiveBeat(b)).toBe(true))})
})
