import {readFileSync} from 'node:fs'
import {describe,it,expect} from 'vitest'
import {buildFrozenFixture,syntheticFixture} from '../../src/investigation/fixture'
import {createInvestigationState,investigationReducer,restoreInvestigation,exportLocalSave,fixtureOrigin,type Command} from '../../src/investigation/state'
import type {CaseFixture} from '../../src/investigation/contracts'
const read=(n:string)=>JSON.parse(readFileSync('public/scenarios/euler-2023-false-exit/'+n,'utf8'))
const hero=buildFrozenFixture(read('scenario.json'),read('evidence-graph.json')),synthetic=syntheticFixture(hero)
function solve(f:CaseFixture){const cs:Command[]=[{type:'EARN_ACCESS'},{type:'COLLECT_CASE_FILE'},{type:'STAGE_CARD',cardId:'CARD.INCIDENT_DAI'},{type:'REVIEW_RECEIPT'},{type:'DISPATCH',path:'TERMINAL'},{type:'SELECT_RESULT',recordId:f.openingRecordId},{type:'STAGE_CARD',cardId:'CARD.FOLLOW_FORWARD'},{type:'REVIEW_RECEIPT'},{type:'DISPATCH',path:'TERMINAL'},{type:'READ_BRANCH',branch:'SECOND'},{type:'SELECT_RESULT',recordId:f.proof.slots.LINK},{type:'STAGE_CARD',cardId:'CARD.EXACT_RECEIPT'},{type:'REVIEW_RECEIPT'},{type:'DISPATCH',path:'TERMINAL'},...(['AMOUNT','RECEIVER','LINK'] as const).map(slot=>({type:'ASSEMBLE' as const,slot,recordId:f.proof.slots[slot]}))];return cs.reduce((s,c)=>investigationReducer(f,s,c),createInvestigationState(f))}
const envelope=(f:CaseFixture,entries:unknown[])=>({...JSON.parse(exportLocalSave(createInvestigationState(f))),commands:{source:{fixtureId:f.id,fixtureMode:f.mode,fixtureOrigin:fixtureOrigin(f)},entries}})
const malformed:unknown[]=[null,[],{},'EARN_ACCESS',5,{type:'UNKNOWN'},{type:'EARN_ACCESS',extra:true},{type:'SECTION',section:'ARCHIVE'},{type:'SECTION',section:5},{type:'PRESENTATION',mode:'RAW'},{type:'READ_BRANCH',branch:'THIRD'},{type:'STAGE_CLUE',clueId:'CLUE.UNKNOWN'},{type:'STAGE_CLUE',clueId:synthetic.startingClueIds[0]},{type:'STAGE_CARD',cardId:'CARD.UNKNOWN'},{type:'REMOVE_FILTER',index:-1},{type:'REMOVE_FILTER',index:0.5},{type:'REMOVE_FILTER',index:'0'},{type:'LOAD_QUERY',index:1e30},{type:'LOAD_QUERY',index:0},{type:'REMOVE_FILTER',index:0},{type:'DISPATCH',path:'NETWORK'},{type:'SELECT_RESULT',recordId:synthetic.proof.slots.LINK},{type:'SELECT_RESULT',recordId:hero.proof.slots.LINK},{type:'PIN',recordId:'FOREIGN'},{type:'SAVE_LEAD',recordId:'FOREIGN'},{type:'COMPARE',recordId:'FOREIGN'},{type:'THEORY',theory:'ACCEPTED'},{type:'ASSEMBLE',slot:'OTHER',recordId:hero.proof.slots.LINK},{type:'ASSEMBLE',slot:'LINK',recordId:synthetic.proof.slots.LINK},{type:'ASSEMBLE',slot:'LINK',recordId:hero.proof.slots.LINK},{type:'HINT',tier:'ALL'},{type:'ADD_FILTER',filter:null},{type:'ADD_FILTER',filter:{}},{type:'STAGE_CARD',cardId:'CARD.EXACT_RECEIPT'}]
const filterBase={field:'SUBJECT',value:hero.proof.linkSource,origin:'PLAYER_FILTER',sourceId:'PLAYER.EXPLICIT'}
for(const [key,value] of [['field','UNKNOWN'],['value',5],['value',''],['origin','FOREIGN'],['sourceId','FOREIGN'],['extra',{filename:'bound'}]] as const)malformed.push({type:'ADD_FILTER',filter:{...filterBase,[key]:value}})
for(const [field,value] of [['RECORD_SET',synthetic.proof.slots.LINK],['TRANSACTION','0xFOREIGN'],['SUBJECT','0xFOREIGN'],['ASSET','FOREIGN'],['GRADE','UNKNOWN'],['KIND','UNKNOWN'],['MIN_AMOUNT','NaN'],['MIN_AMOUNT','-1'],['FROM','NOT_TIME'],['TO','NOT_TIME']] as const)malformed.push({type:'ADD_FILTER',filter:{...filterBase,field,value}})
describe('RES2 atomic source-bound replay',()=>{
 for(const f of [hero,synthetic])it('positive exact self-restoration '+f.mode,()=>{const s=solve(f);expect(s.complete).toBe(true);expect(restoreInvestigation(f,exportLocalSave(s))).toEqual(s);expect(exportLocalSave(restoreInvestigation(f,exportLocalSave(s)))).toBe(exportLocalSave(s))})
 for(const [target,foreign] of [[hero,synthetic],[synthetic,hero]] as const)for(const complete of [false,true])it('outer relabel clean reset '+foreign.mode+' '+complete,()=>{const s=complete?solve(foreign):investigationReducer(foreign,createInvestigationState(foreign),{type:'EARN_ACCESS'});const save=JSON.parse(exportLocalSave(s));Object.assign(save,{fixtureId:target.id,fixtureMode:target.mode,fixtureOrigin:fixtureOrigin(target)});expect(restoreInvestigation(target,JSON.stringify(save))).toEqual(createInvestigationState(target))})
 malformed.forEach((bad,i)=>it('full history rejects bad entry '+i,()=>{const save=envelope(hero,[{type:'EARN_ACCESS'},{type:'SECTION',section:'EXPLORE'},bad,{type:'EARN_ACCESS'}]);expect(restoreInvestigation(hero,JSON.stringify(save))).toEqual(createInvestigationState(hero))}))
 for(const where of ['outer','history','source'])for(const field of ['extra','filename','__proto__'])it('closed save '+where+' '+field,()=>{const s=envelope(hero,[{type:'EARN_ACCESS'}]);const target=where==='outer'?s:where==='history'?s.commands:s.commands.source;Object.defineProperty(target,field,{value:'FOREIGN',enumerable:true});expect(restoreInvestigation(hero,JSON.stringify(s))).toEqual(createInvestigationState(hero))})
 for(const bad of [null,[],{}, {entries:[{type:'EARN_ACCESS'}]}, {source:{fixtureId:hero.id},entries:[]}])it('rejects originless prior history '+JSON.stringify(bad),()=>{const s=envelope(hero,[]);s.commands=bad;expect(restoreInvestigation(hero,JSON.stringify(s))).toEqual(createInvestigationState(hero))})
 it('unknown after full completion cannot retain any proof or prefix',()=>{const s=envelope(hero,[...solve(hero).commands,{type:'UNKNOWN'}]);expect(restoreInvestigation(hero,JSON.stringify(s))).toEqual(createInvestigationState(hero))})
 it('state-dependent unavailable clue aborts whole draft',()=>{const clue=hero.clues.find(c=>!hero.startingClueIds.includes(c.id))!;expect(restoreInvestigation(hero,JSON.stringify(envelope(hero,[{type:'EARN_ACCESS'},{type:'STAGE_CLUE',clueId:clue.id}])))).toEqual(createInvestigationState(hero))})
 it('wrong live attempts never acquire replay authority',()=>{const before=solve(hero);const next=investigationReducer(hero,before,{type:'SELECT_RESULT',recordId:synthetic.proof.slots.LINK});expect(next.commands).toEqual(before.commands);expect(restoreInvestigation(hero,exportLocalSave(next)).complete).toBe(true)})
 it('guarded physical dispatch remains deterministic recovery, not malformed authority',()=>{let s=investigationReducer(hero,createInvestigationState(hero),{type:'EARN_ACCESS'});s=investigationReducer(hero,s,{type:'DISPATCH',path:'PLUNGER'});expect(s.result).toBeNull();expect(restoreInvestigation(hero,exportLocalSave(s))).toEqual(s)})
 it('all synthetic identifier classes fully disjoint',()=>{const sets=(f:CaseFixture)=>[f.records.map(r=>r.id),f.clues.map(c=>c.id),f.clues.map(c=>c.unlockEvent),Object.values(f.proof.slots),f.records.flatMap(r=>r.derivedFrom)];sets(hero).forEach((xs,i)=>expect(xs.filter(x=>sets(synthetic)[i]!.includes(x))).toEqual([]));expect(synthetic.startingClueIds.every(id=>id.startsWith(synthetic.id+'.'))).toBe(true)})
 it('malformed JSON is exactly clean including announcement and history',()=>expect(restoreInvestigation(hero,'{invalid')).toEqual(createInvestigationState(hero)))
 it('explicit visible Hero history is not cryptographic protection',()=>expect(restoreInvestigation(hero,JSON.stringify(envelope(hero,[{type:'EARN_ACCESS'}]))).access).toBe(true))
})
