import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { buildFrozenFixture } from '../../src/investigation/fixture'
import { adventureReducer, createInitialAdventureState } from '../../src/adventure/reducer'
import { SIDE_LEAD_TOKENS } from '../../src/investigation/sideLead'
import type { AdventureState } from '../../src/adventure/types'
import {
  availableCards, createInvestigationState, exportLocalSave,
  investigationReducer, restoreInvestigation, terminalCapabilities,
  type Command,
} from '../../src/investigation/state'

const base = 'public/scenarios/euler-2023-false-exit/'
const frozen = buildFrozenFixture(JSON.parse(readFileSync(base + 'scenario.json', 'utf8')), JSON.parse(readFileSync(base + 'evidence-graph.json', 'utf8')))
type Office = AdventureState
const fresh = (): Office => createInitialAdventureState({ skipIntro: true })
const step = (s: Office, verb: 'OPEN' | 'CLOSE' | 'PULL' | 'PUSH' | 'USE' | 'LOOK_AT' | 'PICK_UP', target: 'official-case-file-cabinet' | 'miscellaneous-drawer-cabinet' | 'disorderly-stack-of-confidential-files' | 'miscellaneous-catch-all-contents'): Office => {
  const postauth = (target === 'official-case-file-cabinet' || target === 'miscellaneous-drawer-cabinet') && s.phase !== 'COMPLETE' ? { ...s, phase: 'COMPLETE' as const } : s
  let next = adventureReducer(postauth, { type: 'SELECT_VERB', verb })
  next = adventureReducer(next, { type: 'INTERACT', targetId: target })
  next = adventureReducer(next, { type: 'WALK_TICK', delta: 2000 })
  for (let i = 0; i < 30 && next.activeSequence; i++) next = adventureReducer(next, { type: 'ADVANCE_SEQUENCE' })
  for (let i = 0; i < 60 && next.speech; i++) next = adventureReducer(next, { type: 'ADVANCE_SPEECH' })
  return next
}
const earn = () => investigationReducer(frozen, createInvestigationState(frozen), { type: 'EARN_ACCESS' })
const collect = () => investigationReducer(frozen, earn(), { type: 'COLLECT_CASE_FILE' })
const review = (s: ReturnType<typeof earn>) => investigationReducer(frozen, s, { type: 'REVIEW_RECEIPT' })
const dispatchOnce = () => investigationReducer(frozen, review(collect()), { type: 'DISPATCH', path: 'TERMINAL' })
const run = (commands: Command[]) => commands.reduce((state, command) => investigationReducer(frozen, command.type === 'DISPATCH' ? review(state) : state, command), earn())

describe('S9-P1-R2 reconciliation, scene restoration, and cabinet seam', () => {
  it('R13.1: stage 4 exposes no comparison control, tray, or route card', () => {
    const d = dispatchOnce()
    expect(terminalCapabilities(frozen, d).stage).toBe(4)
    expect(terminalCapabilities(frozen, d).allowCompare).toBe(false)
    expect(terminalCapabilities(frozen, d).allowTheory).toBe(false)
    expect(availableCards(frozen, d).some((c) => c.id === 'CARD.COMPARE_ROUTES')).toBe(false)
  })
  it('R13.2: direct COMPARE before the milestone fails closed without mutation', () => {
    const d = dispatchOnce()
    const out = investigationReducer(frozen, d, { type: 'COMPARE', recordId: frozen.openingRecordId })
    expect(out.error).toBeTruthy()
    expect(out.comparison).toEqual([])
    expect(out.commands.some((cmd) => cmd.type === 'COMPARE')).toBe(false)
  })
  it('R13.3: crafted comparison history cannot bootstrap stage 5, theory, or exact', () => {
    const d = dispatchOnce()
    const pair = d.discoveredRecords.filter((id) => id !== frozen.openingRecordId).slice(0, 2)
    const crafted = JSON.stringify({ fixtureId: frozen.id, fixtureMode: frozen.mode, fixtureOrigin: createInvestigationState(frozen).fixtureOrigin, commands: { source: { fixtureId: frozen.id, fixtureMode: frozen.mode, fixtureOrigin: createInvestigationState(frozen).fixtureOrigin }, entries: [{ type: 'EARN_ACCESS' }, { type: 'COLLECT_CASE_FILE' }, { type: 'REVIEW_RECEIPT' }, { type: 'DISPATCH', path: 'TERMINAL' }, { type: 'COMPARE', recordId: pair[0] }, { type: 'COMPARE', recordId: pair[1] }] } })
    const restored = restoreInvestigation(frozen, crafted)
    expect(restored.comparison).toEqual([])
    expect(restored.candidateRouteResolved).toBe(false)
    expect(terminalCapabilities(frozen, restored).stage).toBe(4)
    expect(availableCards(frozen, restored).some((c) => c.id === 'CARD.COMPARE_ROUTES')).toBe(false)
    expect(investigationReducer(frozen, restored, { type: 'THEORY', theory: 'FIRST_TRAIL_JOINS_SECOND_ROUTE' }).error).toBeTruthy()
    expect(availableCards(frozen, restored).some((c) => c.stage === 'VERIFY')).toBe(false)
  })
  it('R13.4: comparison becomes optional tooling after resolution', () => {
    const routed = run([{ type: 'COLLECT_CASE_FILE' }, { type: 'DISPATCH', path: 'TERMINAL' }, { type: 'SELECT_RESULT', recordId: frozen.openingRecordId }, { type: 'STAGE_CARD', cardId: 'CARD.FOLLOW_FORWARD' }, { type: 'DISPATCH', path: 'TERMINAL' }])
    expect(terminalCapabilities(frozen, routed).allowCompare).toBe(true)
    const pair = routed.discoveredRecords.filter((id) => id !== frozen.openingRecordId).slice(0, 2)
    let s = investigationReducer(frozen, routed, { type: 'COMPARE', recordId: pair[0]! })
    s = investigationReducer(frozen, s, { type: 'COMPARE', recordId: pair[1]! })
    expect(s.comparison).toHaveLength(2)
    expect(availableCards(frozen, s).some((c) => c.id === 'CARD.COMPARE_ROUTES')).toBe(true)
    expect(terminalCapabilities(frozen, s).stage).toBe(5)
  })
  it('R14.5: layered scene nodes render when declared and props are not hidden', () => {
    const src = readFileSync('src/app/App.tsx', 'utf8')
    expect(src).toContain('scene.midgroundLayers.map')
    expect(src).toContain('scene.foregroundLayers.map')
    expect(src).not.toMatch(/visibility:\s*'hidden'/)
    expect(src).toContain('pneumaticTube')
  })
  it('R14.6: retired tube-family placements stay suppressed while others render', () => {
    const src = readFileSync('src/app/App.tsx', 'utf8')
    expect(src).toContain("placement.propId === 'pneumaticTube'")
    expect(src).toContain("placement.propId === 'dispatchPlunger'")
    expect(src).toContain("placement.propId === 'recordCanister'")
  })
  it('R15.7: placeholder manifest matches admitted direct-parent values', () => {
    const manifest = JSON.parse(readFileSync('public/art-packs/placeholder/manifest.json', 'utf8'))
    expect(manifest.scenes['records-office'].background.src).toBe('/art-packs/placeholder/backgrounds/records-office.svg')
    expect(manifest.scenes['records-office'].characterAnchors.rookStart).toEqual({ x: 228, y: 298 })
    expect(manifest.scenes['records-office'].characterAnchors.mrIndex).toEqual({ x: 532, y: 296 })
  })
  it('R16.8: drawer shells open/close/toggle without granting anything', () => {
    let s = fresh()
    s = step(s, 'OPEN', 'official-case-file-cabinet')
    expect(s.caseFileDrawer).toBe('OPEN')
    expect(s.inventory).toEqual([])
    s = step(s, 'OPEN', 'official-case-file-cabinet')
    expect(s.caseFileDrawer).toBe('OPEN')
    expect(s.inventory).toEqual([])
    s = step(s, 'USE', 'official-case-file-cabinet')
    expect(s.caseFileDrawer).toBe('CLOSED')
    s = step(s, 'PULL', 'official-case-file-cabinet')
    expect(s.caseFileDrawer).toBe('OPEN')
    s = step(s, 'PUSH', 'official-case-file-cabinet')
    expect(s.caseFileDrawer).toBe('CLOSED')
    s = step(s, 'CLOSE', 'official-case-file-cabinet')
    expect(s.caseFileDrawer).toBe('CLOSED')
    expect(s.inventory).toEqual([])
    let m = step(fresh(), 'PULL', 'miscellaneous-drawer-cabinet')
    expect(m.miscDrawer).toBe('OPEN')
    expect(m.inventory).toEqual([])
    m = step(m, 'USE', 'miscellaneous-drawer-cabinet')
    expect(m.miscDrawer).toBe('CLOSED')
  })
  it('R16.9: closing hides contents without resetting search state', () => {
    let s = step(step(fresh(), 'OPEN', 'official-case-file-cabinet'), 'PICK_UP', 'disorderly-stack-of-confidential-files')
    expect(s.caseStack).toBe('SEARCHED_EULER_REMOVED')
    s = step(s, 'CLOSE', 'official-case-file-cabinet')
    expect(s.caseFileDrawer).toBe('CLOSED')
    expect(s.caseStack).toBe('SEARCHED_EULER_REMOVED')
    expect(s.inventory).toContain('euler-case-file')
  })
  it('R16.10: contents LOOK AT is observational only', () => {
    const a = step(step(fresh(), 'OPEN', 'official-case-file-cabinet'), 'LOOK_AT', 'disorderly-stack-of-confidential-files')
    expect(a.inventory).toEqual([])
    expect(a.caseStack).toBe('UNSEARCHED')
    const b = step(step(fresh(), 'OPEN', 'miscellaneous-drawer-cabinet'), 'LOOK_AT', 'miscellaneous-catch-all-contents')
    expect(b.inventory).toEqual([])
    expect(b.miscContents).toBe('UNCOLLECTED')
  })
  it('R16.11: case PICK UP grants once at the rummage contact, never on opening', () => {
    let s = step(fresh(), 'OPEN', 'official-case-file-cabinet')
    expect(s.inventory).not.toContain('euler-case-file')
    s = step(s, 'PICK_UP', 'disorderly-stack-of-confidential-files')
    expect(s.inventory).toEqual(['euler-case-file'])
    expect(s.caseStack).toBe('SEARCHED_EULER_REMOVED')
    const events = s.sequenceEvents.filter((e) => e.semanticContact === 'CONTACT.CASEFILE_COLLECT')
    expect(events).toHaveLength(1)
    expect(events[0]!.inventoryBefore).not.toContain('euler-case-file')
    const again = step(s, 'PICK_UP', 'disorderly-stack-of-confidential-files')
    expect(again.inventory).toEqual(['euler-case-file'])
    expect(again.sequenceEvents.length).toBe(s.sequenceEvents.length)
  })
  it('R16.12: misc PICK UP adds five items in fixed order, one per contact, once', () => {
    const s = step(step(fresh(), 'OPEN', 'miscellaneous-drawer-cabinet'), 'PICK_UP', 'miscellaneous-catch-all-contents')
    expect(s.inventory).toEqual(['rubber-band', 'rubiks-cube', 'sharknado-2-vhs', 'piggy-bank-intact', 'small-toolbox-closed'])
    expect(s.miscContents).toBe('COLLECTED_GUM_REMAINS')
    const pickups = s.sequenceEvents.filter((e) => (e.semanticContact ?? '').startsWith('CONTACT.DRAWER_PICKUP'))
    expect(pickups.map((e) => e.semanticContact)).toEqual(['CONTACT.DRAWER_PICKUP_1', 'CONTACT.DRAWER_PICKUP_2', 'CONTACT.DRAWER_PICKUP_3', 'CONTACT.DRAWER_PICKUP_4', 'CONTACT.DRAWER_PICKUP_5'])
    const order = ['rubber-band', 'rubiks-cube', 'sharknado-2-vhs', 'piggy-bank-intact', 'small-toolbox-closed']
    pickups.forEach((event, index) => {
      expect(event.inventoryAfter.filter((id) => order.includes(id as never))).toEqual(order.slice(0, index + 1))
    })
    expect(s.inventory).not.toContain('peppermint-gum' as never)
    const again = step(s, 'PICK_UP', 'miscellaneous-catch-all-contents')
    expect(again.inventory).toEqual(s.inventory)
    expect(again.sequenceEvents.length).toBe(s.sequenceEvents.length)
  })
  it('R16.13: interrupted acquisition replays converge without duplication or loss', () => {
    let s: Office = { ...fresh(), phase: 'COMPLETE' }
    s = adventureReducer(s, { type: 'SELECT_VERB', verb: 'OPEN' })
    s = adventureReducer(s, { type: 'INTERACT', targetId: 'miscellaneous-drawer-cabinet' })
    s = adventureReducer(s, { type: 'WALK_TICK', delta: 2000 })
    for (let i = 0; i < 60 && s.speech; i++) s = adventureReducer(s, { type: 'ADVANCE_SPEECH' })
    s = adventureReducer(s, { type: 'SELECT_VERB', verb: 'PICK_UP' })
    s = adventureReducer(s, { type: 'INTERACT', targetId: 'miscellaneous-catch-all-contents' })
    s = adventureReducer(s, { type: 'WALK_TICK', delta: 2000 })
    for (let i = 0; i < 4 && s.activeSequence; i++) s = adventureReducer(s, { type: 'ADVANCE_SEQUENCE' })
    expect(s.inventory).toEqual(['rubber-band', 'rubiks-cube'])
    expect(s.miscContents).toBe('UNCOLLECTED')
    for (let i = 0; i < 30 && s.activeSequence; i++) s = adventureReducer(s, { type: 'ADVANCE_SEQUENCE' })
    for (let i = 0; i < 60 && s.speech; i++) s = adventureReducer(s, { type: 'ADVANCE_SPEECH' })
    expect(s.inventory).toEqual(['rubber-band', 'rubiks-cube', 'sharknado-2-vhs', 'piggy-bank-intact', 'small-toolbox-closed'])
    expect(s.miscContents).toBe('COLLECTED_GUM_REMAINS')
    expect(new Set(s.inventory).size).toBe(s.inventory.length)
  })
  it('R16.14: closed-drawer contents grant nothing', () => {
    const a = step(fresh(), 'PICK_UP', 'disorderly-stack-of-confidential-files')
    expect(a.inventory).toEqual([])
    expect(a.caseStack).toBe('UNSEARCHED')
    const b = step(fresh(), 'PICK_UP', 'miscellaneous-catch-all-contents')
    expect(b.inventory).toEqual([])
    expect(b.miscContents).toBe('UNCOLLECTED')
  })
  it('R17: review jumps and terminal saves migrate safely', () => {
    const jumped = adventureReducer(fresh(), { type: 'REVIEW_JUMP', phase: 'COMPLETE' })
    expect(jumped.caseFileDrawer).toBe('CLOSED')
    expect(jumped.caseStack).toBe('UNSEARCHED')
    expect(jumped.inventory).toContain('euler-case-file')
    const repick = step(step(jumped, 'OPEN', 'official-case-file-cabinet'), 'PICK_UP', 'disorderly-stack-of-confidential-files')
    expect(repick.inventory.filter((i) => i === 'euler-case-file')).toHaveLength(1)
    expect(repick.caseStack).toBe('SEARCHED_EULER_REMOVED')
    const saved = exportLocalSave(collect())
    const restored = restoreInvestigation(frozen, saved)
    expect(restored.discoveredClues).toEqual(frozen.startingClueIds)
    expect(terminalCapabilities(frozen, restored).stage).toBe(3)
  })
  it('R1 preservation pins still hold', () => {
    expect(frozen.startingClueIds).toEqual(['CLUE.ASSET', 'CLUE.FILE_ASSET_ADDRESS', 'CLUE.AMOUNT', 'CLUE.WINDOW'])
    expect(terminalCapabilities(frozen, collect()).askCardIds).toEqual(['CARD.INCIDENT_DAI'])
    expect(SIDE_LEAD_TOKENS).toHaveLength(1)
    let hidden = createInitialAdventureState({ skipIntro: true })
    for (let i = 0; i < 500; i++) hidden = adventureReducer(hidden, { type: 'IDLE_TICK', foreground: false })
    expect(hidden.inactiveSeconds).toBe(0)
    const reset = investigationReducer(frozen, run([{ type: 'COLLECT_CASE_FILE' }, { type: 'DISPATCH', path: 'TERMINAL' }]), { type: 'RESET_CASE' })
    expect(reset.access).toBe(true)
    expect(reset.discoveredClues).toEqual(frozen.startingClueIds)
  })
  it('R2 journeys complete in at most three mandatory dispatches', () => {
    const solved = run([{ type: 'COLLECT_CASE_FILE' }, { type: 'DISPATCH', path: 'TERMINAL' }, { type: 'SELECT_RESULT', recordId: frozen.openingRecordId }, { type: 'STAGE_CARD', cardId: 'CARD.FOLLOW_FORWARD' }, { type: 'DISPATCH', path: 'TERMINAL' }, { type: 'SELECT_RESULT', recordId: frozen.proof.slots.LINK }, { type: 'STAGE_CARD', cardId: 'CARD.EXACT_RECEIPT' }, { type: 'DISPATCH', path: 'TERMINAL' }, { type: 'ASSEMBLE', slot: 'AMOUNT', recordId: frozen.proof.slots.AMOUNT }, { type: 'ASSEMBLE', slot: 'RECEIVER', recordId: frozen.proof.slots.RECEIVER }, { type: 'ASSEMBLE', slot: 'LINK', recordId: frozen.proof.slots.LINK }])
    expect(solved.complete).toBe(true)
    expect(solved.commands.filter((c) => c.type === 'DISPATCH')).toHaveLength(3)
    expect(frozen.ledger.attempts).toBe(0)
  })
})
